"""Reviewed love poems with later Church guidance kept distinct."""
import json,sys
from book_common import ROOT,OUT,source,person,scripture,finish
def load(slug):return json.loads((OUT/(slug+'.json')).read_text(encoding='utf8'))
sources=[dict(next(s for s in load('genesis')['sources'] if s['id']==i)) for i in ['web','atlas-canaan']]
sources[0].update(title='Song of Solomon · World English Bible',url='https://ebible.org/engwebp/SNG01.htm',summary='The reading text supplies all eight chapters of love poems.',limits='Publisher speaker headings are removed from verses. Those headings assign voices that the Hebrew text does not explicitly name. Scenes and comparisons do not establish a continuous journey.')
sources[1].update(summary='The atlas names places and regions used in the poems.',limits='Coordinates are approximate display points. Regional markers do not establish the lovers’ movements.')
def reviewed(i,title,url,summary,author,year,coverage,scope,limits,publisher,category='Scholarly study',perspective='historical'):
 s=source(i,title,url,summary,category,perspective,limits);s.update(author=author,year=year,publisher=publisher,chapterCoverage=coverage,reviewed=dict(date='2026-10-05',scope=scope));sources.append(s);return s
reviewed('fishbane-song-excerpt','EXCERPT: Song of Songs · Michael Fishbane','https://unpblog.com/2015/02/20/excerpt-song-of-songs/','Fishbane explains how lovers use plants, animals, cities, and towers to describe each other.','Michael Fishbane',2015,list(range(1,9)),'Complete publisher-posted introductory excerpt reviewed. Its discussion supplies general context, not verse-by-verse commentary.','Fishbane distinguishes human love in the poems from later readings about God and Israel. His account of early religious interpretation includes proposals, not established events. The full commentary was not reviewed.','University of Nebraska Press · The Jewish Publication Society')
reviewed('openbible-song-geo','Places in Song of Solomon · OpenBible.info','https://www.openbible.info/geo/preview/song','The geography index lists named references and possible ancient locations.','OpenBible.info',2026,[],'Complete book geography index, location alternatives, and license footer reviewed. Coordinates remain approximate project display points.','Mahanaim, Heshbon, and other ancient places have competing identifications. Amana, Bether, Baal Hamon, and Bathrabbim have no separate secure markers here. Kedar names a people whose tents appear in a comparison. Place references are not evidence of travel.','OpenBible.info','Geography')
reviewed('kugler-hartin-song-record','An Introduction to the Bible · publisher record','https://www.eerdmans.com/9781467441407/an-introduction-to-the-bible/','Eerdmans verifies the authors and publication of the introduction cited by Wikipedia.','Robert A. Kugler · Patrick Hartin',2009,[],'Publisher description, author names, and publication record reviewed. The book text was not reviewed.','Bibliographic verification only. No chapter interpretation is attributed to unread book text.','Eerdmans')
w=reviewed('wiki-song','Song of Songs · Wikipedia','https://en.wikipedia.org/w/index.php?title=Song_of_Songs&oldid=1374761180','The overview identifies love poems and describes disputed authorship and structure.','Wikipedia contributors',2026,[],'Opening, structure, bibliography, revision footer, and license reviewed. Kugler and Hartin’s cited book checked against its publisher.','Overview and bibliography discovery. Reader notes use scripture and the reviewed Fishbane excerpt.','Wikipedia','Wikipedia overview');w.update(revisionId=1374761180,revisionUrl=w['url'],license='CC BY-SA 4.0',licenseUrl='https://creativecommons.org/licenses/by-sa/4.0/',citedSourceIds=['kugler-hartin-song-record'])
reviewed('lds-song-dictionary','Song of Solomon · Bible Dictionary','https://www.churchofjesuschrist.org/study/scriptures/bd/song-of-solomon?lang=eng','The entry questions Solomon’s authorship and reports the Joseph Smith Translation’s judgment.','The Church of Jesus Christ of Latter-day Saints',None,[1],'Complete two-paragraph Bible Dictionary entry reviewed. Its linked JST entry was not separately reviewed.','The entry quotes the JST: “the Songs of Solomon are not inspired writings.” This is Church guidance about the book, not chapter commentary. Questions in other chapters are original. No Come, Follow Me chapter lesson is claimed.','The Church of Jesus Christ of Latter-day Saints','LDS Bible Dictionary','lds')
rows=[
('The lovers speak and exchange praise','The woman asks to meet her lover. She describes vineyard work that her brothers forced upon her.','She calls herself lovely despite the sun darkening her skin. She answers those who stare instead of accepting their judgment.','How does the woman answer those who stare at her skin?'),
('Spring brings an invitation','The lover calls the woman outside as spring arrives. She warns against awakening love before it desires.','Flowers and ripening fruit express the pleasure of their meeting. Her warning places a limit beside that desire.','Why does the woman place a warning about love beside spring’s invitation?'),
('A night search and a royal carriage','The woman searches the streets and finds her lover. Another scene shows Solomon’s guarded wedding carriage.','Holding her lover answers the fear of losing him. The royal scene adds public wealth and protection.','How does the woman’s night search differ from Solomon’s guarded procession?'),
('Praise through animals, towers, and gardens','The lover praises the woman through many comparisons. She invites him into the garden.','The garden describes the woman and their desire. These comparisons express praise rather than describe her literally.','What does the woman’s garden invitation add to the lover’s praise?'),
('A missed visit and a harmful search','The woman opens too late for her lover. Watchmen beat her and take her cloak during her search.','Her search brings harm rather than help from city guards. She still asks the women to find her friend.','How do the watchmen’s actions change the woman’s search from chapter 3?'),
('The women offer help','The women offer to seek the lover. He praises the woman above queens and other women.','The women’s help answers her earlier request. His praise presents her as someone who cannot be replaced.','How does the women’s offer answer the request she made in chapter 5?'),
('The woman invites her lover outside','The lover praises the woman’s body through comparisons. She invites him to fields, villages, and vineyards.','The woman states her desire and chooses a meeting place. Her voice directs their time together.','How does the woman take action after hearing the lover’s praise?'),
('Love, family control, and a woman’s answer','The poem compares love with death and fire. Brothers discuss their sister, and a woman answers for herself.','Wealth cannot buy the love described here. Her answer presents her own strength beside her brothers’ plans.','How does the woman’s answer differ from her brothers’ plans for her?')]
people=[];reuse={'solomon':['1-kings','solomon'],'david':['1-samuel','david']}
def profile(i,name,role,relations,passages,meaning,coverage,aliases,scope=None):
 p=person(i,name,role,relations,passages,meaning);p.update(chapterCoverage=coverage,linkNames=aliases,placeIds=[])
 if scope:p['verseScope']={str(k):v for k,v in scope.items()}
 people.append(p)
profile('woman-song','The woman','Woman who speaks about her desire and her work','She seeks her lover and speaks to the women of Jerusalem.','Song of Solomon 1:5–7; 3:1–5; 5:2–16; 6:13; 7:10–13; 8','She asks for meetings and describes harm during her search. Her words give her wishes a direct voice.',list(range(1,9)),['woman','Shulammite'])
profile('lover-song','The lover','Man who invites and praises the woman','She calls him her beloved and her friend.','Song of Solomon 1:13–16; 2:8–14; 4; 5:10–16; 7','His praise uses the surrounding world to express his desire.',list(range(1,9)),['lover','my beloved','your beloved','her beloved'],{1:[13,14,16],2:[3,8,9,10,16,17],3:[1,2,3,4],4:[16],5:list(range(2,17)),6:[1,2,3],7:[9,10,11,13],8:[5,14]})
profile('women-song','The women of Jerusalem','Women who hear and answer the lovers','They ask about the lover and offer to help find him.','Song of Solomon 1:5; 2:7; 3:5, 10–11; 5:8–9, 16; 6:1; 8:4','Their questions lead the woman to explain why she wants him.',list(range(1,9)),['women of Jerusalem','daughters of Jerusalem','daughters of Zion'])
profile('brothers-song','The brothers','Family members who discuss work and their sister’s future','The woman describes angry brothers. Later brothers discuss a young sister.','Song of Solomon 1:6; 8:8–10','Their decisions show family control. The woman later gives her own answer.',[1,8],['brothers','mother’s sons'],{1:[6]})
profile('watchmen-song','The watchmen','Men who patrol the city and its walls','The woman meets watchmen during two night searches.','Song of Solomon 3:3; 5:7','The later search includes their violence against her. Their public role does not make her safe.',[3,5],['watchmen','keepers of the walls'],{3:[3],5:[7]})
profile('solomon-guards-song','Solomon’s guards','Sixty armed men around Solomon’s carriage','They carry swords because of danger at night.','Song of Solomon 3:7–8','The royal procession has protection unavailable to the woman during her later search.',[3],['Solomon’s guards','Sixty mighty men'],{3:[7]})
profile('solomon-mother-song','Solomon’s mother','Mother who crowns Solomon in the wedding scene','The poem names her relationship but does not give her name.','Song of Solomon 3:11','Her crown joins family honor with the king’s public celebration.',[3],['Solomon’s mother','his mother'],{3:[11]})
profile('woman-mother-song','The woman’s mother','Mother whose house appears in the woman’s words','The woman brings her lover toward her mother’s house.','Song of Solomon 3:4; 6:9; 8:1–2','The home connects her desire with the family that raised her.',[3,6,8],['woman’s mother','my mother'],{3:[4],8:[1,2]})
profile('pharaoh-song','Pharaoh','Unnamed Egyptian ruler mentioned in a comparison','The lover compares the woman with a horse among Pharaoh’s chariots.','Song of Solomon 1:9','The image gives his praise the force of a royal horse. Pharaoh does not act in this poem.',[1],['Pharaoh'],{1:[9]})
profile('solomon','Solomon','King named in the title and royal scenes','His carriage, mother, and vineyard appear in the poems.','Song of Solomon 1:1, 5; 3:7–11; 8:11–12','His wealth provides comparisons with the lovers’ desire. The book does not clearly identify him as the lover.',[1,3,8],['Solomon'])
profile('david','David','King named in the lover’s tower comparison','The lover compares the woman’s neck with David’s tower.','Song of Solomon 4:4','Shields and a tower give the praise an image of strength.',[4],['David'],{4:[4]})
places=[]
for slug,pid,summary in [('2-kings','jerusalem','The poems name Jerusalem’s women and compare beauty with the city.'),('1-samuel','en-gedi','The woman compares her lover with henna blossoms from En Gedi.'),('genesis','gilead','The lover compares the woman’s hair with goats on Gilead.'),('1-kings','damascus','A tower facing Damascus appears in praise of the woman.')]:
 p=dict(next(p for p in load(slug)['places'] if p['id']==pid));p.update(summary=summary,sourceIds=['web','atlas-canaan'],limits='This marker locates a named reference in the poem. It does not establish a visit by the lovers.');places.append(p)
text=scripture('song-of-solomon','SNG',8);chapters=[]
for slug,pid,name,summary in [('1-kings','lebanon','Lebanon','The poems use Lebanon’s wood, scent, and appearance in praise.'),('1-kings','tirzah','Tirzah','The lover compares the woman’s beauty with Tirzah.'),('1-kings','carmel','Mount Carmel','The lover compares the woman’s head with Carmel.'),('genesis','mahanaim','Mahanaim','A question about watching the Shulammite names the dance of Mahanaim.'),('numbers','heshbon','Heshbon','The lover compares the woman’s eyes with pools in Heshbon.')]:
 p=dict(next(p for p in load(slug)['places'] if p['id']==pid));p.update(name=name,summary=summary,sourceIds=['web','openbible-song-geo'],limits='This approximate marker locates a poetic reference. The exact pool, dance setting, or lovers’ visit is not established.');places.append(p)
places.append(dict(id='sharon',name='Sharon',lat=32.4,lng=34.883,summary='The woman calls herself a rose of Sharon.',limits='A display point for the coastal plain. It does not locate the woman.',sourceIds=['web','atlas-canaan']))
places.append(dict(id='hermon',name='Mount Hermon',lat=33.416,lng=35.857,summary='The lover names Hermon and Senir in his invitation.',limits='An approximate mountain marker. The invitation does not establish a literal visit.',sourceIds=['web','atlas-canaan']))
locations={1:['jerusalem','en-gedi'],2:['jerusalem','sharon'],3:['jerusalem','lebanon'],4:['gilead','lebanon','hermon'],5:['jerusalem','lebanon'],6:['jerusalem','gilead','tirzah','mahanaim'],7:['damascus','lebanon','carmel','heshbon'],8:['jerusalem']}
for n,(title,summary,meaning,question) in enumerate(rows,1):
 if n==3:summary+=' His mother gives him a wedding crown.'
 if n==8:summary+=' Solomon rents out a vineyard.'
 guidance='The Church’s Bible Dictionary reports the JST: “the Songs of Solomon are not inspired writings.” ' if n==1 else ''
 chapters.append(dict(chapter=n,title=title,summary=summary,meaning=meaning,people=[p['id'] for p in people if n in p['chapterCoverage']],places=locations[n],sourceIds=['web','fishbane-song-excerpt'],lds=dict(text=guidance+question,sourceIds=['lds-song-dictionary'] if n==1 else []),eventOrder=n,dateLabel='Poem order',historicalNote=meaning,mapNote='The map locates named comparisons and groups. It does not trace the lovers’ movements.',route=[],routeEvidence='No continuous journey or event date is reconstructed.'))
for p in people:p.pop('chapterCoverage')
data=dict(id='song-of-solomon',bibleCode='SNG',name='Song of Solomon',description='Love poems · night searches · family voices',chapterCount=8,scripture=text,chapters=chapters,people=people,places=places,sources=sources,review=dict(date='2026-10-05',scope='All 117 cleaned WEB verses reviewed. Publisher voice headings excluded. Church guidance attributed separately.',nextBook='jeremiah'))
assert sum(map(len,text.values()))==117
(ROOT/'scripts/song-of-solomon-art-reuse.json').write_text(json.dumps(reuse,indent=2)+'\n',encoding='utf8')
if '--ready' in sys.argv:finish(data)
else:(ROOT/'review/song-of-solomon-draft.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf8');print('Saved Song of Solomon draft: 8 chapters, 117 verses, 11 profiles.')
