"""Esther: reviewed Scripture and sources in the original Isaiah reader."""
import json
from book_common import OUT,source,person,place,scripture,finish
rows=[
('Vashti refuses the king','Ahasuerus holds large feasts. Vashti refuses his order to appear. Memucan urges him to replace her.','One refusal becomes a rule for every household. The king’s advisers fear women following Vashti’s example.','ahasuerus-esther,vashti,memucan,royal-servants-esther,royal-princes-esther','susa'),
('Esther becomes queen','Hegai helps Esther in the women’s house. Ahasuerus chooses her as queen. Mordecai reports a plot against him.','Esther keeps her people and family secret. The report of Mordecai’s help enters the king’s records.','ahasuerus-esther,vashti,esther,mordecai,hegai,shaashgaz,abihail-esther,mordecai-ancestors,bigthan-teresh,esther-maidens,jehoiachin,nebuchadnezzar','susa,jerusalem,babylon'),
('Haman orders the Jews’ deaths','Mordecai refuses to bow to Haman. Haman obtains the king’s ring and sends orders to kill all the Jews.','Haman turns anger at one man against a whole people. Written orders spread the danger.','ahasuerus-esther,mordecai,haman,jewish-families-esther,royal-scribes-esther,royal-couriers-esther','susa'),
('Esther decides to approach the king','Hathach carries messages between Mordecai and Esther. Esther asks the Jews to fast before she risks approaching the king.','The palace does not protect Esther from danger to her people. She asks others to share her preparation.','esther,mordecai,hathach,jewish-families-esther,esther-maidens','susa'),
('Two invitations and Haman’s anger','The king receives Esther. She invites him and Haman to two meals. Zeresh suggests preparing a gallows for Mordecai.','Haman’s honors cannot satisfy him while Mordecai refuses to bow. His friends strengthen his plan.','ahasuerus-esther,esther,haman,mordecai,zeresh','susa'),
('Haman must honor Mordecai','The king hears how Mordecai saved him. Haman must lead Mordecai through the city with royal clothing and a horse.','Haman expects honor for himself. Instead, he must praise the man he wants to kill.','ahasuerus-esther,haman,mordecai,zeresh,bigthan-teresh','susa'),
('Esther names Haman as the enemy','Esther asks for her life and her people’s lives. She names Haman. Harbonah points out the gallows, and Haman dies.','Esther connects the threat to herself before naming its author. The king turns against Haman.','ahasuerus-esther,esther,haman,harbonah','susa'),
('New orders allow the Jews to fight','Esther asks again for her people. Mordecai receives the king’s ring. New letters permit the Jews to gather and fight attackers.','Haman’s death does not cancel his letters. Esther keeps asking until new orders address the remaining danger.','ahasuerus-esther,esther,mordecai,haman,royal-scribes-esther,royal-couriers-esther,jewish-families-esther','susa'),
('Victory, violence, and Purim','The Jews kill their enemies without taking goods. Esther requests another day in Susa. Letters establish Purim with feasts and gifts.','The days of fear become days of joy. Gifts to people in need become part of remembering.','ahasuerus-esther,esther,mordecai,haman,jewish-families-esther,haman-sons,abihail-esther','susa'),
('Mordecai serves his people','Ahasuerus collects payment from his lands. Mordecai holds high office and works for his people’s good.','Mordecai’s lasting importance comes from helping his people, beyond the honor he receives.','ahasuerus-esther,mordecai','susa')]
defs=[
('ahasuerus-esther','Ahasuerus, the king in Esther','Persian king whose orders shape the crisis','He removes Vashti, makes Esther queen, and gives his ring to Haman and Mordecai.','His choices spread danger and later give the Jews power to fight their enemies.'),
('vashti','Vashti','Queen removed after refusing the king’s order','She holds a feast for women. She refuses to appear when the king sends servants.','Her refusal leads the king’s advisers to demand rules for all wives.'),
('memucan','Memucan','Adviser who urges the king to replace Vashti','He is one of seven princes close to the king.','He turns the king’s anger into a claim that all husbands need protection.'),
('royal-servants-esther','The seven royal servants','Servants sent to bring Vashti before the king','The list names Mehuman, Biztha, Harbona, Bigtha, Abagtha, Zethar, and Carcass.','They carry the order that Vashti refuses.'),
('royal-princes-esther','The king’s princes','Advisers who know the laws and meet the king','Carshena, Shethar, Admatha, Tarshish, Meres, and Marsena sit with Memucan.','The king asks these advisers how to answer Vashti’s refusal.'),
('esther','Esther','Jewish queen who asks the king to save her people','Also called Hadassah, she is Abihail’s daughter. Mordecai raises her after her parents die.','She risks approaching the king and keeps asking for help after Haman dies.'),
('mordecai','Mordecai','Esther’s cousin and guardian, later a high official','He raises Esther, reports a plot against the king, and refuses to bow to Haman.','His messages urge Esther to act. His later letters help organize defense and yearly remembrance.'),
('hegai','Hegai','Royal servant in charge of the first women’s house','He gives Esther food, cosmetics, attendants, and advice before she meets the king.','His care helps Esther within a household controlled by the king.'),
('shaashgaz','Shaashgaz','Royal servant keeping the second women’s house','Women enter his care after spending a night with the king.','His task shows how the king controls whether women return to see him.'),
('abihail-esther','Abihail, Esther’s father','Mordecai’s uncle and Esther’s deceased father','Mordecai takes Esther into his family after both her parents die.','Naming her father connects the queen to the family she first keeps secret.'),
('mordecai-ancestors','Jair, Shimei, and Kish in Mordecai’s family','Three ancestors named before the exile account','The list calls Mordecai a son of Jair, Shimei, and Kish, from Benjamin’s family.','Their names connect Mordecai’s family with the earlier loss of Jerusalem.'),
('bigthan-teresh','Bigthan and Teresh','Two doorkeepers who plot against the king','Mordecai reports their plot through Esther. The king’s investigation leads to their deaths.','The saved report later prompts the king to reward Mordecai. Chapter six calls Bigthan Bigthana.'),
('esther-maidens','Esther’s attendants','Women serving Esther in the palace','Hegai gives her seven attendants. Later, her women join her three-day fast.','Esther prepares with others before facing the danger of approaching the king.'),
('haman','Haman','Official who plans to kill all the Jews','Hammedatha’s son, called an Agagite, receives high office. His wife is Zeresh.','He uses the king’s authority against a whole people after Mordecai refuses to bow.'),
('zeresh','Zeresh','Haman’s wife and adviser','She joins his friends in proposing a gallows. Later, she warns that he will fall.','Her advice changes as Haman’s apparent success becomes public humiliation.'),
('hathach','Hathach','Servant carrying messages for Esther','The king assigns him to Esther. He visits Mordecai outside the gate.','His messages let Esther learn about the death order and answer Mordecai’s request.'),
('harbonah','Harbonah','Royal servant who points out Haman’s gallows','He speaks to the king after Esther names Haman as her enemy.','His words connect Haman’s death plan with Mordecai’s earlier service to the king.'),
('jewish-families-esther','The Jewish families in Esther','Men, women, and children threatened by Haman’s letters','They mourn and fast, then gather to fight. Later, they keep Purim each year.','The danger reaches whole families. Remembrance includes food gifts and help for people in need.'),
('royal-scribes-esther','The royal writers','Writers preparing orders in many languages','They write Haman’s orders and later write what Mordecai commands.','Written words carry the king’s power far beyond his palace.'),
('royal-couriers-esther','The royal couriers','Messengers carrying the king’s letters','They hurry out with the first death order. Later, riders carry the new letters.','The letters reach distant communities before the chosen day of fighting.'),
('haman-sons','Haman’s ten sons','Family members killed during the fighting in Susa','They are killed before Esther asks the king to hang their bodies.','Their deaths extend the conflict beyond Haman himself. The account gives none of their own words.')]
people=[person(i,n,r,rel,'Esther',m) for i,n,r,rel,m in defs]
prior=json.loads((OUT/'nehemiah.json').read_text(encoding='utf8'))
ancestors={p['id']:p for p in prior['people']}
kings=json.loads((OUT/'2-kings.json').read_text(encoding='utf8'))
people.append(dict(next(p for p in kings['people'] if p['id']=='jehoiachin')))
people.append(dict(ancestors['nebuchadnezzar']))
aliases={'ahasuerus-esther':['Ahasuerus'],'esther':['Hadassah'],'abihail-esther':['Abihail'],'mordecai-ancestors':['Jair','Shimei','Kish'],'bigthan-teresh':['Bigthan','Bigthana','Teresh'],'esther-maidens':['her maidens','my maidens'],'royal-servants-esther':['Mehuman','Biztha','Harbona','Bigtha','Abagtha','Zethar','Carcass'],'royal-princes-esther':['Carshena','Shethar','Admatha','Tarshish','Meres','Marsena'],'jewish-families-esther':['the Jews','all Jews'],'royal-scribes-esther':['the king’s scribes'],'royal-couriers-esther':['couriers'],'haman-sons':['Parshandatha','Dalphon','Aspatha','Poratha','Adalia','Aridatha','Parmashta','Arisai','Aridai','Vaizatha','Haman’s ten sons'],'jehoiachin':['Jeconiah'],'harbonah':['Harbonah']}
scopes={'royal-servants-esther':{1:[10]},'royal-princes-esther':{1:[14]},'mordecai-ancestors':{2:[5]},'abihail-esther':{2:[15],9:[29]},'bigthan-teresh':{2:[21],6:[2]},'esther-maidens':{2:[9],4:[4,16]},'haman-sons':{9:list(range(7,15))}}
for p in people:
 p['sourceIds']=['web'];p.pop('verseScope',None);p.pop('aliases',None)
 p['linkNames']=aliases.get(p['id'],[])
 if p['id'] in scopes:p['verseScope']={str(k):v for k,v in scopes[p['id']].items()}
 p['passages']='Esther '+', '.join(str(n) for n,row in enumerate(rows,1) if p['id'] in row[3].split(','))
 p['placeIds']=[] if p['id'] in ['jehoiachin','nebuchadnezzar','abihail-esther','mordecai-ancestors','royal-couriers-esther','jewish-families-esther'] else ['susa']
 if p['id']=='jehoiachin':p.update(role='Judah’s king named in the earlier exile account',relations='Esther’s family account names him among those carried away by Nebuchadnezzar.',meaning='His name connects the Persian setting with an earlier loss of Judah’s freedom.')
 if p['id']=='nebuchadnezzar':p.update(role='Earlier Babylonian king named in Esther’s family account',relations='The account recalls his capture of people from Jerusalem.',meaning='His earlier conquests form part of the family’s remembered past.')
sources=[source('web','Esther · World English Bible','https://ebible.org/engwebp/EST01.htm','Complete public-domain reading text for ten chapters.','Scripture',limits='The text supplies the story and its speakers’ claims. It does not independently verify events.')]
sources.extend(dict(s) for s in prior['sources'] if s['id'] in ['terrain','atlas','atlas-canaan'])
def reviewed(i,t,u,summary,author,year,coverage,scope,limits,category='Scholarly study',perspective='historical'):
 s=source(i,t,u,summary,category,perspective,limits);s.update(author=author,year=year,chapterCoverage=coverage,reviewed='2026-10-05: '+scope);sources.append(s)
reviewed('luther-esther','Summary of Esther · Luther Seminary','https://enterthebible.org/courses/esther/lessons/summary-of-esther/','Jacobson and Schifferdecker read Esther as a story about courage and life under foreign rulers.','Diane Jacobson · revised Kathryn Schifferdecker',2023,list(range(1,11)),'Complete main Summary, So What, Where, Who, When, What, and How sections reviewed.','A literary teaching overview. The story’s court setting does not verify its events.')
reviewed('luther-esther-6','Esther 6:1–14: The Great Reversal · Luther Seminary','https://enterthebible.org/passage/esther-61-14-the-great-reversal/','The study follows how Haman’s planned reward becomes honor for Mordecai.','Enter the Bible · Luther Seminary','Date not displayed',[6],'Complete main Summary and Analysis reviewed. Author not displayed in retrieved passage.','The linked Levenson quotation is indirect. His full commentary was not read.')
reviewed('luther-esther-9','Esther 9:1–17: The Jews Destroy their Enemies · Luther Seminary','https://enterthebible.org/passage/esther-91-17-the-jews-destroy-their-enemies/','The study asks how readers should understand the violent ending and repeated refusal of goods.','Enter the Bible · Luther Seminary','Date not displayed',[9],'Complete main Summary and Analysis retrieved through indexed primary-page text. Direct fetch timed out.','This is a literary interpretation. It does not verify the reported death totals.')
reviewed('mcclellan-esther','Esther and women’s use of power · McClellan interview','https://www.mormonstories.org/10-things-bible-dan-mcclellan/','McClellan discusses Esther’s use of the resources available to her under Persian rule.','Dan McClellan · interview with John Dehlin',2023,[2,4,5,7,8],'Original publisher transcript at 03:54:13–03:55:13 reviewed. Full interview and audio not reviewed.','Automatic transcript includes an awkward phrase at 03:55:13. Only the clear preceding argument is paraphrased. This is scholarly commentary, not Church teaching.','McClellan commentary')
record=source('berlin-record','The Book of Esther and Ancient Storytelling · verified article record','https://scholarlypublishingcollective.org/sblpress/jbl/article/120/1/3/181629/The-Book-of-Esther-and-Ancient-Storytelling','The publisher record identifies Berlin’s article, journal, date, pages, and DOI.','Verified bibliography',limits='Indexed publisher record and first-page search excerpt reviewed. Direct publisher and society PDF access failed. The full article was not read.');record.update(author='Adele Berlin',year=2001,doi='10.2307/3268590',reviewed='2026-10-05: Publisher-supplied bibliographic record verified.');sources.append(record)
u='https://en.wikipedia.org/w/index.php?oldid=1376976389&title=Book_of_Esther'
wiki=source('wiki-esther','Book of Esther · Wikipedia',u,'The opening describes the book and provides scholarly references.','Encyclopedia background',limits='Opening paragraphs and cited Berlin article record reviewed. Disputed historical claims are not adopted from this page alone.');wiki.update(author='Wikipedia contributors',revisionId='1376976389',revisionUrl=u,license='CC BY-SA 4.0',licenseUrl='https://creativecommons.org/licenses/by-sa/4.0/',citedSourceIds=['berlin-record'],reviewed='2026-10-05: Opening paragraphs and Berlin bibliography reviewed.');sources.append(wiki)
base='https://www.churchofjesuschrist.org/study/'
reviewed('cfm-esther-2026','Come, Follow Me 2026 · Esther',base+'manual/come-follow-me-for-home-and-church-old-testament-2026/32?lang=eng','The lesson studies family service, courage, fasting, and the harm caused by pride.','The Church of Jesus Christ of Latter-day Saints',2026,[2,3,4,5,7,8,9],'Complete main and children’s lesson sections reviewed. Detailed cited passages support these chapters.','The whole book is assigned, but detailed prompts focus on selected passages. Linked talks and videos were not reviewed.','Come, Follow Me','lds')
reviewed('lds-esther-109','Lesson 109: Esther · Seminary teacher material',base+'manual/old-testament-seminary-teacher-material-2018/esther/lesson-109?lang=eng','The lesson teaches using one’s circumstances to help others and seeking strength through fasting.','The Church of Jesus Christ of Latter-day Saints',2018,list(range(1,11)),'Introduction and main teaching lesson through its conclusion reviewed. Commentary, supplements, and linked talks were not reviewed.','Chapters 1 and 6–10 have brief summaries. Detailed questions focus on Esther’s choices in chapters 2–5 and 7.','LDS study manual','lds')
reviewed('atlas-persia','Bible Maps: The Persian Empire',base+'scriptures/bible-maps/map-7?lang=eng','The Seminary lesson recommends this map for the Persian setting.','The Church of Jesus Christ of Latter-day Saints','Current map',[],'Map page title and Seminary lesson reference reviewed. Map image was not reviewed.','Library reference only. Unreviewed map labels are not used to place events.','Geography')
known={p['id']:p for p in prior['places']}
places=[dict(known[i]) for i in ['susa','jerusalem','babylon']]
for p in places:p.pop('verseScope',None);p['sourceIds']=['web','atlas','atlas-canaan']
places[0]['summary']='The palace, gate, and city square form the setting for Esther’s choices.'
places[1]['summary']='The family account recalls people carried away from Jerusalem before the palace story.'
places[2]['summary']='Nebuchadnezzar’s earlier capture of people forms part of the family account.'
lds={1:'The Seminary lesson starts with the king’s decision to replace Vashti.',2:'Come, Follow Me studies Mordecai’s care for Esther after her parents die.',3:'Come, Follow Me asks how Haman’s anger turns into danger for other people.',4:'Come, Follow Me connects Esther’s decision with courage and fasting before difficult choices.',5:'Come, Follow Me compares Esther’s risk with Haman’s pride and anger.',6:'The Seminary lesson recalls how the king’s records bring Mordecai’s service back into view.',7:'Come, Follow Me asks what Haman’s choices reveal about his motives and their results.',8:'Come, Follow Me links the new letters with its study of fasting during danger.',9:'Come, Follow Me connects Esther’s courage with the later days of gladness.',10:'Mordecai works for his people’s good. Who benefits from the authority he receives?'}
chapters=[]
for n,(title,summary,meaning,pids,locs) in enumerate(rows,1):
 hs=[s['id'] for s in sources if s['perspective']=='historical' and n in s.get('chapterCoverage',[])];ls=[s['id'] for s in sources if s['perspective']=='lds' and n in s.get('chapterCoverage',[])]
 chapters.append(dict(chapter=n,title=title,summary=summary,meaning=meaning,people=pids.split(','),places=locs.split(','),sourceIds=['web','atlas','atlas-canaan']+hs,lds=dict(text=lds[n],sourceIds=ls),eventOrder=n,dateLabel='Chapter order',historicalNote='Luther Seminary reads the palace story through its changing fortunes.' if n!=9 else 'Luther Seminary asks how readers should understand the violent ending.',mapNote='Jerusalem and Babylon belong to the earlier family account. The palace story takes place in Susa.' if n==2 else 'Susa marks the story’s setting. Individual rooms and courier roads are not mapped.',route=[],routeEvidence='No exact travel route is reconstructed.'))
finish(dict(id='esther',bibleCode='EST',name='Esther',description='Palace choices · danger · courage · Purim',chapterCount=10,scripture=scripture('esther','EST',10),chapters=chapters,people=people,places=places,sources=sources,review=dict(date='2026-10-05',scope='All 167 verses reviewed. Selected people and groups have profiles. The Hebrew-form WEB text is used. Greek additions are not inserted.',nextBook='job')))

