"""Ecclesiastes draft with the Preacher's claims kept distinct."""
import json,sys
from book_common import ROOT,OUT,source,person,scripture,finish
def load(slug):return json.loads((OUT/(slug+'.json')).read_text(encoding='utf8'))
g=load('genesis');sources=[dict(next(s for s in g['sources'] if s['id']==i)) for i in ['web','atlas-canaan']]
sources[0].update(title='Ecclesiastes · World English Bible',url='https://ebible.org/engwebp/ECC01.htm',summary='The public-domain reading text supplies all twelve chapters.',limits='The Preacher’s observations and the closing writer’s advice have distinct voices. The book does not name Solomon.')
def reviewed(i,title,url,summary,author,year,coverage,scope,limits,publisher,category='Scholarly study',perspective='historical'):
 s=source(i,title,url,summary,category,perspective,limits);s.update(author=author,year=year,publisher=publisher,chapterCoverage=coverage,reviewed=dict(date='2026-10-05',scope=scope));sources.append(s);return s
reviewed('luther-ecclesiastes-background','Background of Ecclesiastes · Luther Seminary','https://enterthebible.org/courses/ecclesiastes/lessons/background-of-ecclesiastes/','The authors place the book’s questions within rule over Judah by larger powers.','James Limburg · revised Cameron B.R. Howard',2023,list(range(1,13)),'Complete main Background text reviewed. General setting for the book, not commentary on each verse.','The proposed date around 250 BCE is a scholarly estimate. It is not a date for each narrated example.','Luther Seminary')
reviewed('fox-ecclesiastes-record','The JPS Bible Commentary: Ecclesiastes · publisher record','https://jps.org/books/jps-bible-commentary-ecclesiastes/','JPS identifies Michael V. Fox’s commentary and describes questions about justice and lasting value.','Michael V. Fox',2004,[],'Publisher description and author record reviewed. Commentary text not reviewed.','Bibliographic verification only. No chapter interpretation is attributed to unread commentary.','The Jewish Publication Society')
w=reviewed('wiki-ecclesiastes','Ecclesiastes · Wikipedia','https://en.wikipedia.org/w/index.php?title=Ecclesiastes&oldid=1378255856','The opening overview distinguishes the Preacher from the closing writer.','Wikipedia contributors',2026,[],'Opening, structure, bibliography, revision footer, and license reviewed. Fox’s cited book checked against its publisher.','Overview and bibliography discovery. Detailed reader notes use scripture and reviewed named sources.','Wikipedia','Wikipedia overview');w.update(revisionId=1378255856,revisionUrl=w['url'],license='CC BY-SA 4.0',licenseUrl='https://creativecommons.org/licenses/by-sa/4.0/',citedSourceIds=['fox-ecclesiastes-record'])
church='https://www.churchofjesuschrist.org/study/manual/'
reviewed('cfm-ecclesiastes','Ecclesiastes · Come, Follow Me 2026 · lesson 37',church+'come-follow-me-for-home-and-church-old-testament-2026/37?lang=eng','The lesson connects temporary mortal life with trust in God and obedience.','The Church of Jesus Christ of Latter-day Saints',2026,[1,2,3,11,12],'Complete main and children’s lesson sections reviewed. Coverage uses assigned Ecclesiastes chapters. Linked talks and videos not separately reviewed.','Later Church teaching remains distinct from the Preacher’s questions and original study questions.','The Church of Jesus Christ of Latter-day Saints','Come, Follow Me','lds')
reviewed('lds-ecclesiastes-helps','Ecclesiastes · Scripture Helps',church+'scripture-helps-old-testament/35-proverbs-1-4-15-16-22-31-ecclesiastes-1-3-11-12?lang=eng','Church notes explain temporary life, generosity, and the image of cattle-prodding sticks.','The Church of Jesus Christ of Latter-day Saints',2026,[1,11,12],'Complete main Ecclesiastes sections reviewed, including vanity, bread on water, and goads. Linked works not separately reviewed.','The Church applications do not settle every disputed reading of the images.','The Church of Jesus Christ of Latter-day Saints','LDS study manual','lds')
rows=[
('The Preacher asks what work gains','The Preacher describes generations, wind, and rivers repeating their courses. He asks what lasting gain work brings.','Vanity here concerns what does not last, not pride in appearance. Learning leaves the Preacher with more questions and grief.','Why does the Preacher compare human work with wind and rivers?'),
('Pleasure and great works do not last','The Preacher builds houses, plants gardens, gathers wealth, and buys servants. He still finds no lasting gain.','Someone else will inherit his work. He cannot control whether that person will use it wisely.','Why does leaving his work to another person trouble the Preacher?'),
('Changing times and shared death','The Preacher lists times for opposite actions. He describes injustice and asks what happens after death.','People can enjoy their work without understanding all God does. Death also challenges claims of human superiority over animals.','Why does the Preacher connect enjoyment of work with what people cannot know?'),
('Power, lonely work, and companions','The Preacher sees people harmed without comfort. He compares a lonely worker with helpful companions.','A companion can lift someone who falls. Endless work for wealth leaves the solitary worker asking whom he serves.','What does a companion provide that the lonely worker’s wealth cannot?'),
('Listen before making promises','The Preacher warns against careless promises to God. He describes wealth that prevents sleep or disappears.','A promise creates a duty to act. More possessions can bring more demands without bringing satisfaction.','Why does the Preacher prefer making no promise to leaving one unpaid?'),
('Having wealth without enjoying it','The Preacher describes a wealthy person unable to enjoy his goods. He asks who knows what is good.','Long life and many children do not guarantee enjoyment. Another person can consume the goods the owner gathered.','How does the wealthy person’s experience challenge measuring life by possessions?'),
('Mourning and unfair outcomes','The Preacher considers mourning, patience, and unfair outcomes. He also describes a woman as a trap.','He sees good people die young and wrongdoers live long. These lives challenge simple rules about reward.','Why does the Preacher think a house of mourning can teach the living?'),
('A ruler’s power and delayed justice','The Preacher advises care before a king. He sees wrongdoers prosper and good people suffer.','Delayed punishment can encourage further harm. His confidence in God stands beside outcomes he cannot explain.','How does delayed punishment affect the people who watch wrongdoing?'),
('Death, chance, and forgotten wisdom','The Preacher urges enjoyment of food, work, and marriage. He recalls a poor man saving a city.','The city forgets its poor rescuer. Wisdom can help without securing honor or lasting remembrance.','Why do the poor man’s useful words fail to bring him lasting honor?'),
('Small mistakes and careless rulers','The Preacher compares foolishness with flies spoiling perfume. He describes poor choices by rulers and workers.','Sharpening an axe reduces wasted effort. Careful preparation matters more than using greater force.','How does the blunt axe show the value of preparing before work?'),
('Act without knowing every outcome','The Preacher urges giving, sowing seed, and enjoying youth. He warns that people cannot predict every result.','Waiting for perfect weather can prevent planting. Acting in several ways allows for outcomes the worker cannot foresee.','Why does the Preacher tell the worker to sow in morning and evening?'),
('Remember your Creator before old age','The Preacher describes fading strength and death. The closing writer praises his teaching and urges obedience to God.','The broken household images describe failing life. The closing writer turns from questions toward responsibility for hidden and public actions.','What does remembering the Creator change before the losses described in this chapter?')]
people=[];reuse={'david':['1-samuel','david']}
def profile(i,name,role,relations,passages,meaning,coverage,aliases=None,scope=None):
 p=person(i,name,role,relations,passages,meaning);p['chapterCoverage']=coverage;p['placeIds']=[]
 if aliases is not None:p['linkNames']=aliases
 if scope:p['verseScope']={str(k):v for k,v in scope.items()}
 people.append(p)
profile('preacher-ecclesiastes','The Preacher','Main speaker who examines work, pleasure, and death','The opening presents him as David’s son and a king in Jerusalem.','Ecclesiastes 1:1, 12; 2; 3; 12:8–10','His questions test whether effort, wealth, and wisdom can secure lasting gain.',list(range(1,13)),['Preacher'])
profile('david','David','Father named in the opening description','The title identifies the Preacher as his son. It does not name Solomon.','Ecclesiastes 1:1','The family description gives the speaker a royal setting.',[1])
profile('closing-writer-ecclesiastes','The closing writer','Voice that describes the Preacher’s teaching','He praises the Preacher’s careful words and urges obedience to God.','Ecclesiastes 12:9–14','His advice closes the book with responsibility for actions.',[12],['closing writer'])
profile('solitary-worker-ecclesiastes','The solitary worker','Worker with no son or brother','He keeps working and seeking wealth without asking whom the work serves.','Ecclesiastes 4:8','His question shows how gathering wealth can replace enjoyment and companionship.',[4],['solitary worker','one who is alone'],{4:[8]})
profile('young-king-ecclesiastes','The wise youth','Poor young man in the example of changing rulers','The account describes him leaving prison and gaining rule.','Ecclesiastes 4:13–16','His success still cannot secure the praise of later generations.',[4],['wise youth'],{4:[13]})
profile('old-king-ecclesiastes','The old king','Ruler who refuses further advice','The Preacher compares him unfavorably with a poor, wise youth.','Ecclesiastes 4:13','Refusing to listen makes his age and rank poor guides to wisdom.',[4],['old and foolish king'],{4:[13]})
profile('poor-rescuer-ecclesiastes','The poor rescuer','Wise man who saves a small city','The people forget him after his wisdom delivers their city.','Ecclesiastes 9:14–16','Poverty can cause people to ignore advice that already helped them.',[9],['poor wise man'],{9:[15]})
profile('attacking-king-ecclesiastes','The attacking king','Ruler who surrounds a small city','He builds defenses for his attack, but a poor man’s wisdom saves the city.','Ecclesiastes 9:14–15','The example compares armed strength with advice from a person of little status.',[9],['great king'],{9:[14]})
profile('beloved-wife-ecclesiastes','The beloved wife','Partner in the Preacher’s advice about enjoying life','He urges a listener to live joyfully with the wife he loves.','Ecclesiastes 9:9','Shared life appears among gifts that people can enjoy during their short lives.',[9],['wife'],{9:[9]})
jerusalem=dict(next(p for p in load('2-kings')['places'] if p['id']=='jerusalem'));jerusalem.update(summary='The opening places the royal speaker in Jerusalem.',sourceIds=['web','atlas-canaan'],limits='A setting for the royal voice in chapters 1–2. It does not verify Solomon’s authorship or date later examples.')
text=scripture('ecclesiastes','ECC',12);chapters=[]
lessons={1:'Come, Follow Me studies what gives temporary life lasting value.',2:'Come, Follow Me studies mortal life as temporary.',3:'Come, Follow Me studies wisdom while recognizing life’s limits.',11:'Scripture Helps connects bread on water with giving without expecting immediate repayment.',12:'Come, Follow Me connects lasting value with fearing God and keeping his commands.'}
for n,(title,summary,meaning,question) in enumerate(rows,1):
 hs=[s['id'] for s in sources if s['perspective']=='historical' and n in s.get('chapterCoverage',[])]
 ls=[s['id'] for s in sources if s['perspective']=='lds' and n in s.get('chapterCoverage',[])]
 chapters.append(dict(chapter=n,title=title,summary=summary,meaning=meaning,people=[p['id'] for p in people if n in p['chapterCoverage']],places=['jerusalem'] if n in [1,2] else [],sourceIds=['web']+hs,lds=dict(text=(lessons.get(n,'')+' '+question).strip(),sourceIds=ls),eventOrder=n,dateLabel='Chapter order',historicalNote=meaning,mapNote='Jerusalem supplies the opening speaker’s setting.' if n in [1,2] else 'The example does not name a secure map location.',route=[],routeEvidence='No travel route is reconstructed.'))
for p in people:p.pop('chapterCoverage')
data=dict(id='ecclesiastes',bibleCode='ECC',name='Ecclesiastes',description='Work · passing time · injustice · daily joy',chapterCount=12,scripture=text,chapters=chapters,people=people,places=[jerusalem],sources=sources,review=dict(date='2026-10-05',scope='All 222 WEB verses reviewed. Main speaker and closing advice distinguished.',nextBook='song-of-solomon'))
assert sum(map(len,text.values()))==222
(ROOT/'scripts/ecclesiastes-art-reuse.json').write_text(json.dumps(reuse,indent=2)+'\n',encoding='utf8')
if '--ready' in sys.argv:finish(data)
else:(ROOT/'review/ecclesiastes-draft.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf8');print('Saved Ecclesiastes draft: 12 chapters, 222 verses, 9 profiles.')
