"""Build Mark from reviewed Scripture, scoped sources, and original close readings."""
import json,sys,copy
from book_common import ROOT,OUT,scripture,source,place,finish
DATE='2026-10-07'
t=scripture('mark','MRK',16)
assert [len(t[str(n)]) for n in range(1,17)]==[45,28,35,41,43,56,37,38,50,52,33,44,37,72,47,20]
assert not any('\ufffd' in v['text'] for vv in t.values() for v in vv)
base=json.loads((OUT/'matthew.json').read_text(encoding='utf8'))
notes=json.loads((ROOT/'scripts/book-context-complete/mark.json').read_text(encoding='utf8'))
s=source('web','Mark · World English Bible','https://ebible.org/engwebp/MRK01.htm','All sixteen chapters appear in the reading text.','Scripture','historical','The account supports close reading. The publisher retains verses 9–20 in chapter sixteen with textual notes.')
s.update(author='World English Bible translators',publisher='eBible.org',chapterCoverage=list(range(1,17)),reviewed=dict(date=DATE,scope='All 678 verses read, including surrounding passages and the publisher’s chapter sixteen ending notes. Character integrity and verse counts checked.'))
sources=[s]
s=source('black-mark','Commentary on Mark 16:1-8','https://www.workingpreacher.org/commentaries/narrative-lectionary/resurrection-2/commentary-on-mark-161-8','Black discusses fear, the message to Peter, and competing endings after verse eight.','Scholarly study','historical','Black supplies the textual interpretation. Original manuscripts were not examined. The guide does not adopt proposed lost-ending explanations as facts.')
s.update(author='C. Clifton Black',publisher='Luther Seminary',year=2016,chapterCoverage=[16],reviewed=dict(date=DATE,scope='Complete commentary body read. Linked commentaries and podcast were not reviewed.'))
sources.append(s)
lessons=[(10,[2,3,4],'February 27–March 5 · Matthew 8; Mark 2–4; Luke 7','The lesson studies carriers’ faith, unity, and peace during the storm.'),(20,[10],'May 8–14 · Matthew 19–20; Mark 10; Luke 18','The lesson studies the wealthy man’s question and the demand to follow Jesus.'),(27,[16],'June 26–July 2 · Matthew 28; Mark 16; Luke 24; John 20–21','The lesson teaches resurrection through the Gospel accounts.')]
for number,coverage,title,summary in lessons:
 s=source('cfm-nt-2023-'+str(number),title,f'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-sunday-school-new-testament-2023/{number:02}?lang=eng',summary,'LDS Come, Follow Me','lds','This is selected Church teaching. Heading references alone do not establish teaching coverage.')
 s.update(author='The Church of Jesus Christ of Latter-day Saints',publisher='The Church of Jesus Christ of Latter-day Saints',year=2023,chapterCoverage=coverage,reviewed=dict(date=DATE,scope='Complete lesson body and additional resources read. Only specified Mark chapters receive coverage. Linked talks, videos, dictionary articles, and other editions were not separately reviewed.'));sources.append(s)
for sid in ['net-nt-map','atlas-canaan']:
 s=copy.deepcopy(next(x for x in base['sources'] if x['id']==sid))
 if sid=='net-nt-map':s['reviewed']['scope']+=' Bethsaida and Sea of Galilee opening geographic descriptions and coordinate lines reviewed. Bethsaida remains a broad vicinity reference, not a fixed ancient ruin.'
 sources.append(s)
people=[copy.deepcopy(p) for p in base['people'] if p['id']!='joseph-mary']
details={
 'jesus':('Teacher presented as the Christ and Son of God','Mary is his mother. Mark also names brothers and mentions sisters.','Mark 1–16','His works and suffering test how followers understand his identity.'),
 'mary-mother':('Mother named in the hometown discussion','Mark names her in the question about Jesus and his family.','Mark 3:31–35; 6:3','The family scenes place familiar relationships beside doing God’s will.'),
 'john-baptizer':('Preacher who baptizes Jesus and dies under Herod’s order','His disciples bury his body after the ruler’s feast.','Mark 1; 2:18; 6:14–29; 8:28; 11:30–32','His death places rulers’ promises beside the cost borne by another person.'),
 'peter':('Fisherman who follows Jesus and later denies knowing him','Andrew is his brother. Mark also mentions his wife’s mother.','Mark 1; 3; 5; 8–11; 13–14; 16:7','His confession, resistance, and denial remain beside the message that explicitly includes him.'),
 'mary-magdalene':('Witness of the cross, burial, and opened tomb','Mark distinguishes her from Mary the mother of James and Joses.','Mark 15:40–47; 16:1–11','Her witness connects the burial setting with the message of resurrection.')}
profileChapters={'jesus':list(range(1,17)),'mary-mother':[3,6],'john-baptizer':[1,2,6,8,11],'peter':[1,3,5,8,9,10,11,13,14,16],'mary-magdalene':[15,16]}
for p in people:
 p['role'],p['relations'],p['passages'],p['meaning']=details[p['id']]
 p['placeIds']=[];p['verseScope']={}
 if p['id']=='mary-mother':p['verseScope']={'6':[3]}
 if p['id']=='john-baptizer':p['verseScope']={'1':[4,6,9,14],'2':[18],'6':[14,16,17,18,20,24,25,27,29],'8':[28],'11':[30,32]}
 if p['id']=='peter':p['verseScope']={str(n):[v['verse'] for v in t[str(n)] if 'Peter' in v['text']] for n in profileChapters['peter']}
 if p['id']=='mary-magdalene':p['verseScope']={'15':[40,47],'16':[1,9]}
placeText={'jerusalem':'Jerusalem holds the temple disputes, arrest, execution, and burial setting.','jordan':'John baptizes Jesus in the Jordan. No exact baptism site is assigned.','galilee':'Galilee holds early work and the promised meeting named at the tomb.','nazareth':'Jesus comes from Nazareth for baptism. The hometown question later names his family.','capernaum':'Capernaum holds teaching, healing, and disputes inside crowded houses.','tyre':'The region of Tyre supplies the setting of the woman’s request for her daughter.','sidon':'Sidon appears among the crowd’s origins and in the return from Tyre.','caesarea-philippi':'The villages of Caesarea Philippi surround the question about Jesus’ identity.','jericho':'Bartimaeus asks for sight as Jesus leaves Jericho.','bethany':'Bethany appears beside the Jerusalem visits and the unnamed woman’s anointing.','olives':'The Mount of Olives holds the private warning and the departure after supper.'}
places=[]
for p in base['places']:
 if p['id'] in placeText:
  q=copy.deepcopy(p);q.update(summary=placeText[p['id']],verseScope={});places.append(q)
places.extend([place('bethsaida','Bethsaida · vicinity',32+54/60,35+37/60,'A blind man receives sight in two stages near Bethsaida.','Broad vicinity from the NET reference. This marker does not identify one ancient ruin or a boat landing.',['web','net-nt-map']),place('sea-galilee','Sea of Galilee',32.8,35+35/60,'The lake connects crossings, storms, and questions about Jesus’ identity.','Lake reference from the NET coordinate line. No exact storm position or crossing route is assigned.',['web','net-nt-map'])])
summaries=['John prepares the way. Jesus gathers followers and heals amid growing crowds.','Forgiveness, shared meals, fasting, and Sabbath action lead to disputes.','A healing deepens conflict. Crowds, accusations, and family claims surround Jesus.','Seed stories explain hearing. A storm leaves disciples asking who Jesus is.','Jesus frees a man among tombs, heals a woman, and restores a girl’s life.','Followers travel and return. Herod kills John, while Jesus feeds a crowd.','A washing dispute exposes neglected parents. A foreign woman asks for help.','Another feeding leads to bread confusion, partial sight, and Peter’s confession.','The mountain scene leads to healing, another death warning, and arguments about rank.','Marriage, children, possessions, and rank become tests of following Jesus.','Jerusalem’s entry leads to temple action, a tree lesson, and challenged authority.','Stories and disputes lead to a warning about scribes and a widow’s gift.','Jesus warns four disciples about destruction, deception, hardship, and watching.','An anointing and supper lead to arrest, flight, and Peter’s denials.','Pilate hands Jesus over. Mockery, death, witnesses, and burial follow.','Women find the tomb open. The message names a meeting in Galilee.']
questions=['Why does Jesus leave the gathered crowd to visit other towns?','How does the Sabbath answer connect its purpose with human need?','How does the question about saving life expose the opponents’ plan?','Why does fear remain after the disciples hear explanations and see the storm stop?','Why does Jesus stop to hear the woman while Jairus waits?','What should the disciples have understood from the loaves before the sea encounter?','How can calling property sacred become a refusal to help parents?','How does the two-stage healing sit beside Peter’s incomplete understanding?','How does the father’s request differ from the disciples’ silence about their fears?','How do the two answers to the same question reveal different desires?','How do the tree scenes frame the temple interruption?','How does the warning about widows’ houses affect reading the widow’s gift?','What work remains possible when the day and hour stay unknown?','How does the woman’s action differ from the disciples’ promises?','Why does the officer’s recognition follow death rather than escape from the cross?','Why does the tomb message name Peter after his denial?']
ldsTeach={2:'The selected lesson studies the carriers’ faith and shared help.',3:'The selected lesson uses the divided house saying to teach unity.',4:'The selected lesson reads the storm account through peace during trouble.',10:'The selected lesson studies the wealthy man’s question about following Jesus.',16:'The selected lesson teaches resurrection through the Gospel accounts.'}
ldsSources={c:['cfm-nt-2023-'+str(number)] for number,coverage,_,_ in lessons for c in coverage}
locs={1:['nazareth','jordan','galilee','capernaum','sea-galilee'],2:['capernaum'],3:['galilee','jerusalem','jordan','tyre','sidon','sea-galilee'],4:['sea-galilee'],5:['sea-galilee'],6:['galilee','sea-galilee','bethsaida'],7:['jerusalem','tyre','sidon','sea-galilee'],8:['sea-galilee','bethsaida','caesarea-philippi','jerusalem'],9:['galilee','capernaum'],10:['jordan','jerusalem','jericho'],11:['jerusalem','bethany','olives'],12:['jerusalem'],13:['jerusalem','olives'],14:['jerusalem','bethany','olives','galilee'],15:['jerusalem','galilee'],16:['jerusalem','galilee']}
chapters=[]
for n,v,title,meaning in notes:
 loc=locs.get(n,[])
 chapters.append(dict(chapter=n,title=title,summary=summaries[n-1],meaning=meaning,people=[pid for pid,cc in profileChapters.items() if n in cc],places=loc,sourceIds=['web']+(['black-mark'] if n==16 else []),lds=dict(text=ldsTeach.get(n,'')+(' ' if n in ldsTeach else '')+'Study question. '+questions[n-1],sourceIds=ldsSources.get(n,[])),eventOrder=n,dateLabel='Book order',historicalNote=meaning,mapNote='Selected markers separate named settings from remembered places. Exact houses, tombs, unnamed mountains, and travel routes remain unassigned.' if loc else 'This chapter has no selected place markers. No unnamed setting receives an invented location.',route=[],routeEvidence='Reference markers do not reconstruct exact movements or combine accounts from different Gospels.'))
data=dict(id='mark',bibleCode='MRK',name='Mark',description='Hearing · healing · incomplete understanding · service · cross · resurrection',chapterCount=16,scripture=t,chapters=chapters,people=people,places=places,sources=sources,review=dict(date=DATE,contextReviewDate=DATE,copyReviewDate=DATE,scope='All 678 WEB verses read for sixteen original explanations and exact selections. Five selected profiles do not cover every person. Three selected Church lessons retain actual chapter coverage. The disputed ending receives attributed textual interpretation. No original manuscripts, exact routes, archaeological event verification, or original language alignment were reviewed.',nextBook='luke'))
if '--ready' in sys.argv:finish(data)
else:(ROOT/'review/mark-draft.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
