import json
from book_common import ROOT,OUT,scripture,source,person,place,finish
EX=json.loads((OUT/'exodus.json').read_text(encoding='utf-8'))
rows='''
Burnt offerings|God calls Moses from the meeting tent. He gives instructions for offerings from livestock and birds.|The offering includes careful preparation. The different animals allow more than one kind of household to participate.|moses,aaron|Consider what an offering expresses about devotion and willing service.
Grain offerings|God gives instructions for grain, oil, incense, and first produce. Salt accompanies the offerings.|The chapter includes gifts from ordinary food. Worship involves the products of daily work.|moses,aaron|Consider how daily work and gratitude can become part of your worship.
Fellowship offerings|God gives instructions for offerings from cattle, sheep, and goats. Blood and fat receive special treatment.|The offering marks a relationship with God. The text places limits on what people may consume.|moses,aaron|Consider how gratitude can strengthen your relationship with God and other people.
Offerings for unintentional sin|Instructions address errors by a priest, the congregation, a leader, and an ordinary person.|Responsibility reaches every level of society. A leader's error can affect more than the leader.|moses,aaron|Consider how your responsibilities change the effects of your mistakes.
Confession and repair|The laws address withheld testimony, impurity, rash oaths, and misuse of sacred things.|Confession joins practical repair. The offering depends partly on the person's available resources.|moses,aaron|Consider how confession, restitution, and changed conduct belong together in repentance.
Restitution and priestly duties|Wrongdoers must return stolen or withheld property. Priests receive instructions for continuing offerings.|Worship does not replace repair of harm. Daily priestly work also requires sustained care.|moses,aaron|Consider what practical repair follows an apology or a confession.
Rules for shared offerings|The laws explain priestly portions, thanksgiving offerings, vows, and limits on eating.|The community shares food through defined rules. Gratitude and promises require care rather than casual handling.|moses,aaron|Consider how gratitude and promises shape the way you use what you receive.
Priests appointed|Moses washes and clothes Aaron and his sons. He performs the appointed offerings before the congregation.|Priestly appointment includes public preparation. The priests receive duties within a community, not only personal honor.|moses,aaron,nadab,abihu,eleazar,ithamar|The Church manual connects priestly service with sacred preparation. Consider the duties that follow an appointment.
The first priestly service|Aaron and his sons make offerings. Moses and Aaron bless the people. Fire consumes the altar offering.|The new service reaches its public beginning. The people's response recognizes the sacred presence described in the narrative.|moses,aaron,nadab,abihu,eleazar,ithamar|Consider how preparation leads toward service for the benefit of other people.
Nadab and Abihu die|Nadab and Abihu offer unauthorized fire and die. Moses gives further instructions. Aaron explains his response to grief.|The chapter places sacred limits beside a bereaved father's judgment. Aaron's silence and later explanation deserve careful reading.|moses,aaron,nadab,abihu,eleazar,ithamar|The Church manual discusses responsibility in sacred service. Read that theme alongside Aaron's grief.
Animals and food|God identifies clean and unclean animals. Contact with certain carcasses brings temporary impurity.|The food rules distinguish Israel's daily practices. Ritual impurity does not by itself establish moral guilt.|moses,aaron|The Church manual studies these rules within Israel's covenant. Avoid treating impurity as a person's worth.
After childbirth|The law gives periods and offerings after childbirth. A less costly offering is available.|The chapter addresses a bodily event through ritual rules. Childbirth is not presented as a moral offense.|moses|Consider the distinction between a ritual status and a person's moral conduct.
Inspection of skin and cloth|Priests inspect skin conditions and damaged clothing. The law specifies observation periods and separation.|The ancient categories do not match one modern medical diagnosis. Inspection concerns the community's ritual boundaries.|moses,aaron|Read these conditions within their ancient setting. Do not use them to judge a sick person's faith.
Return after cleansing|The law gives rites for a cleansed person. It also addresses affected houses and less costly offerings.|The rules include return after separation. The process involves both the person and the place where people live.|moses,aaron|Consider the importance of helping people return to community after a period of separation.
Bodily discharges|The laws address discharges, washing, waiting periods, and offerings.|Ordinary bodily processes can change ritual status. This status must remain distinct from moral wrongdoing.|moses,aaron|Consider how careful distinctions can prevent shame about ordinary bodily experiences.
The Day of Atonement|Aaron receives instructions for entry into the inner sanctuary. Two goats have different roles in the rite.|The annual rite addresses the sanctuary and the people together. Access to the inner space has strict limits.|moses,aaron|The Church manual reads these signs through Jesus Christ's Atonement. Keep that reading separately labeled.
Blood and the place of offering|The law regulates slaughter and offerings. It prohibits eating blood and explains blood's relation to life.|Life receives special protection within the ritual system. Worship is directed toward a shared sacred center.|moses,aaron|Consider how reverence for life affects both worship and ordinary conduct.
Limits on sexual conduct|God gives laws about prohibited relationships and acts. The chapter connects conduct with the land's condition.|The laws address family and community boundaries. Read each command within its ancient legal setting.|moses|Consider the duties that protect trust and prevent harm within relationships.
Holiness in daily life|God commands reverence, honest measures, care for the poor, and love for the neighbor and stranger.|Holiness includes economic fairness and care for others. Worship and daily justice appear in the same chapter.|moses|Consider how love for the neighbor changes your treatment of workers, strangers, and people in need.
Penalties and distinction|The chapter assigns severe penalties for specified offenses. It calls Israel to remain distinct.|These are ancient penalties within Israel's law. They require historical study rather than direct transfer into present practice.|moses|Consider moral responsibility while keeping ancient civil penalties distinct from present Church practice.
Rules for priests|The laws address priestly mourning, marriage, and access to sacred service.|Priests have special restrictions. The text's bodily rules do not justify denying a person's human worth.|moses,aaron|Consider the responsibilities of sacred service without judging a person's worth by bodily appearance.
Holy gifts and acceptable offerings|The laws regulate priestly access to food and the condition of offered animals.|The chapter protects what the community dedicates. Care for sacred gifts includes how they are handled.|moses,aaron|Consider how careful use of dedicated resources can show respect for those who provide them.
The sacred calendar|God names the Sabbath and appointed festivals. The harvest rules leave produce for the poor and stranger.|Time becomes part of worship. The calendar joins remembered deliverance, rest, harvest, and care for those in need.|moses|Consider how worship, rest, and care for others can shape your calendar.
Lamps, bread, and a judgment|The law maintains lamps and bread. An unnamed man curses the Name and is executed after judgment.|The account names his mother, Shelomith. It connects the case with laws about injury and equal standards.|moses,shelomith|Consider the seriousness of sacred speech. Keep the ancient punishment distinct from present religious practice.
Sabbath years and Jubilee|God commands rest for the land and restoration in the Jubilee. The laws address land, debt, and servitude.|The land belongs to God in this account. The rules limit permanent loss while preserving unequal ancient social categories.|moses|Consider how care for land and relief of hardship can accompany faithful stewardship.
Covenant promises and warnings|The chapter describes blessings, escalating disaster, exile, and possible return after confession.|The covenant account connects conduct and communal outcomes. Do not use it to assign guilt for every present disaster.|moses|Consider repentance and hope without blaming all suffering on the people who experience it.
Vows and dedicated property|The laws assign values for vowed persons, animals, land, and other dedicated things.|The final chapter regulates commitments made to God. Its valuation rules belong to a specific ancient legal system.|moses|Consider whether your promises are informed, careful, and matched by responsible action.
'''.strip().splitlines()
assert len(rows)==27
sources=[source('web','Leviticus — World English Bible','https://ebible.org/engwebp/LEV01.htm','The public-domain text supplies all 27 chapters.','Scripture',limits='This reading text preserves the narrative and laws. It does not establish their historical dates.')]
sources.extend(dict(s) for s in EX['sources'] if s['id'] in ['yale-9','yale-10','atlas-exodus','terrain'])
base='https://www.churchofjesuschrist.org/study/manual/old-testament-student-manual-genesis-2-samuel/'
for sid,title,slug in [
('lds-offerings','Leviticus 1–10: Sacrifices and Offerings','leviticus-1-10-a-law-of-performances-and-ordinances-part-1-sacrifices-and-offerings'),
('lds-purity','Leviticus 11–18: The Clean and the Unclean','leviticus-11-18-a-law-of-performances-and-ordinances-part-2-the-clean-and-the-unclean'),
('lds-holiness','Leviticus 19–27: Laws of Mercy and Righteousness','leviticus-19-27-a-law-of-performances-and-ordinances-part-3-laws-of-mercy-and-righteousness')]:
    sources.append(source(sid,title,base+slug+'?lang=eng','Church commentary studies this passage range through LDS teachings.','LDS study manual','lds',limits='This older manual includes interpretive commentary. It does not supply independent archaeological confirmation.'))
sources.append(source('mosiah-13','Mosiah 13:27–35','https://www.churchofjesuschrist.org/study/scriptures/bofm/mosiah/13?lang=eng&id=p27-p35#p27','Abinadi teaches about the law of Moses and salvation through Christ.','LDS scripture','lds',limits='This Restoration scripture is a related reading. Keep it distinct from Leviticus’s own text.'))
places=[dict(p) for p in EX['places'] if p['id']=='sinai']
places[0]['summary']='Leviticus places the laws within Israel’s Sinai setting. Many instructions concern the meeting tent and camp.'
people=[dict(p) for p in EX['people'] if p['id'] in ['moses','aaron','nadab','abihu','eleazar','ithamar']]
details={
'moses':('Leviticus 1–27','He conveys the laws and appoints the priests. His work joins worship with the community’s conduct.'),
'aaron':('Leviticus 8–10; 16; 21–22','He begins priestly service and performs the annual rite. His response to his sons’ deaths reveals personal grief.'),
'nadab':('Leviticus 8–10','His appointment precedes his death after unauthorized fire. The account concerns the responsibilities of sacred service.'),
'abihu':('Leviticus 8–10','He serves with his father and brothers. His death becomes the setting for further priestly instructions.'),
'eleazar':('Leviticus 10:6–20','He remains among Aaron’s surviving sons. Moses addresses him about mourning and the sacred offerings.'),
'ithamar':('Leviticus 10:6–20','He remains with Eleazar after his brothers’ deaths. The instructions place mourning beside continuing service.')}
for p in people:p['passages'],p['meaning']=details[p['id']];p['placeIds']=['sinai']
people.append(person('shelomith','Shelomith','Named mother in the judgment account','Daughter of Dibri, from Dan. Her son has an Egyptian father.','Leviticus 24:10–23','The narrative names her but leaves her son unnamed. It records no direct speech or action by her.'))
chapters=[]
for n,row in enumerate(rows,1):
    title,summary,meaning,pids,lds=row.split('|');group='lds-offerings' if n<=10 else 'lds-purity' if n<=18 else 'lds-holiness'
    chapters.append(dict(chapter=n,title=title,summary=summary,meaning=meaning,people=pids.split(','),places=['sinai'],sourceIds=['web','yale-9']+(['yale-10'] if n>=17 else []),lds=dict(text=lds,sourceIds=[group]+(['mosiah-13'] if n in [1,4,16] else [])),eventOrder=n,dateLabel='Chapter order · historical dating debated',mapNote='The marker represents the traditional Sinai region. Leviticus gives no chapter-by-chapter travel route.',historicalNote='Study the cited lectures for the ancient setting of these laws and rites.',route=[],routeEvidence='No chapter journey is mapped. The camp and sanctuary lack verified coordinates.'))
finish(dict(id='leviticus',bibleCode='LEV',name='Leviticus',description='Offerings · priestly service · holiness · justice',chapterCount=27,scripture=scripture('leviticus','LEV',27),chapters=chapters,people=people,places=places,sources=sources,review=dict(date='2026-10-04',scope='All chapters. The Sinai marker reflects a tradition, not a verified camp. Ritual status and moral conduct remain distinct.',nextBook='numbers')))
art=json.loads((OUT/'exodus-art.json').read_text(encoding='utf-8'))
selected={p['id']:art[p['id']] for p in people if p['id'] in art}
for pid in ['nadab','abihu']:selected[pid]['note']='Later artwork illustrating the death described in Leviticus 10. It does not establish actual appearance.'
selected['shelomith']=dict(src='assets/portraits/leviticus/shelomith.png',generated=True,credit='AI-generated illustration',description='Imaginative artistic depiction of Shelomith.',note='An artistic interpretation. The text does not describe her appearance.')
(OUT/'leviticus-art.json').write_text(json.dumps(selected,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
