"""Build Philippians from reviewed Scripture and original contextual notes."""
import json,copy,sys
from book_common import ROOT,OUT,scripture,source,person,finish
DATE='2026-10-07';t=scripture('philippians','PHP',4)
assert [len(t[str(n)]) for n in range(1,5)]==[30,30,21,23]
assert sum(map(len,t.values()))==104
assert not any('\ufffd' in str(v) for vv in t.values() for v in vv)
notes=json.loads((ROOT/'scripts/book-context-complete/philippians.json').read_text(encoding='utf8'));sources=[]
s=source('web','Philippians · World English Bible','https://ebible.org/engwebp/PHP01.htm','All four chapters supply the primary text for original close readings.','Scripture','historical','Exact dates, the prison city, original manuscripts, Greek forms, rival workers\x27 identities, and the cause of the women\x27s disagreement were not independently verified. The letter supplies Paul\x27s perspective rather than a complete reply from others.')
s.update(author='World English Bible translators',publisher='eBible.org',chapterCoverage=[1,2,3,4],reviewed=dict(date=DATE,scope='All 104 verses read for four original contextual explanations and exact selections. Surroundings, counts, and character integrity checked.'));sources.append(s)
s=source('works-philippians','Commentary on Philippians 4:4-7','https://www.workingpreacher.org/commentaries/revised-common-lectionary/third-sunday-of-advent-3/commentary-on-philippians-44-7-5','Works reads joy within suffering and uncertain waiting.','Scholarly study','historical','This is Works\x27 interpretation. Her Greek analysis, wider Roman setting, and broader account of peace were not independently verified. Linked works were not reviewed.')
s.update(author='Carla Works',publisher='Luther Seminary',year=2021,chapterCoverage=[4],reviewed=dict(date=DATE,scope='Complete commentary body read. The guide attributes her reading of joy without denial of suffering.'));sources.append(s)
s=source('cfm-nt-2023-42','October 9–15 · Philippians; Colossians','https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-sunday-school-new-testament-2023/42?lang=eng','The lesson studies changed conduct and joy through Christ.','LDS Come, Follow Me','lds','Philippians coverage follows actual discussion of chapters two and four. The lesson title does not establish coverage of every chapter. Linked talks, videos, and Restoration passages were not independently reviewed.')
s.update(author='The Church of Jesus Christ of Latter-day Saints',publisher='The Church of Jesus Christ of Latter-day Saints',year=2023,chapterCoverage=[2,4],reviewed=dict(date=DATE,scope='Complete lesson body read, including its Colossians sections. Only Philippians two and four support this book\x27s lesson references.'));sources.append(s)
acts=json.loads((OUT/'acts.json').read_text(encoding='utf8'));sources.extend(copy.deepcopy([s for s in acts['sources'] if s['id'] in ['atlas-canaan','net-acts-map']]))
rows=[('paul','Paul','Imprisoned letter speaker who depends on shared prayer and support','Timothy shares the opening greeting, and Epaphroditus brings the group\x27s gift.','Philippians 1–4','His uncertain condition gives the appeals to unity and joy their immediate setting.'),('jesus','Jesus Christ','Lord whose self-giving path supplies the pattern for shared conduct','Paul connects his own changed measure of life and the group\x27s hope with him.','Philippians 1–4','His service and raised position give humility and hope a common center.'),('timothy','Timothy','Trusted worker whom Paul hopes to send for news of the hearers','He shares the opening greeting and has served beside Paul.','Philippians 1:1; 2:19–23','His genuine concern gives the appeal to consider others a personal example.'),('epaphroditus','Epaphroditus','Messenger whose service for Paul brings him close to death','He carries the group\x27s gift and longs to return to them.','Philippians 2:25–30; 4:18','Paul asks the group to honor his costly service and welcome his return.'),('euodia','Euodia','Recognized fellow worker whom Paul asks to agree with Syntyche','An unnamed partner is asked to help both women.','Philippians 4:2–3','Her earlier service remains recognized within the present appeal for agreement.'),('syntyche','Syntyche','Recognized fellow worker whom Paul asks to agree with Euodia','An unnamed partner is asked to help both women.','Philippians 4:2–3','Her earlier service remains recognized within the present appeal for agreement.')]
people=[];pc={'paul':[1,2,3,4],'jesus':[1,2,3,4],'timothy':[1,2],'epaphroditus':[2,4],'euodia':[4],'syntyche':[4]}
for pid,name,role,relations,passages,meaning in rows:
 p=person(pid,name,role,relations,passages,meaning);p.update(placeIds=[],linkNames=['Jesus','Christ'] if pid=='jesus' else [name],verseScope={});people.append(p)
places=copy.deepcopy([p for p in acts['places'] if p['id']=='philippi'])
for p in places:p.update(summary='Philippi is named as the recipients\x27 city in the opening greeting.',verseScope={},linkNames=['Philippi'])
summaries=['Paul\x27s chains and uncertain future lead into an appeal for shared courage.','Christ\x27s self-giving path shapes humility and the honor given to faithful workers.','Former claims to rank give way to knowing Christ and continuing toward the goal.','Shared agreement, prayer, contentment, and practical help complete the appeal.']
questions=['Why does Paul place the hearers\x27 need beside his own desire to depart?','How do Timothy and Epaphroditus give personal examples of concern for others?','Why does Paul describe pursuit rather than claim completed perfection?','How does the gift show that contentment can still welcome help?'];teach={2:'The selected Church lesson teaches changed conduct through humility and care for others.',4:'The selected Church lesson teaches joy and contentment through Christ during difficult conditions.'};chapters=[]
for n,v,title,meaning in notes:
 chapters.append(dict(chapter=n,title=title,summary=summaries[n-1],meaning=meaning,people=[pid for pid,cc in pc.items() if n in cc],places=['philippi'] if n==1 else [],sourceIds=['web']+(['works-philippians'] if n==4 else []),lds=dict(text=teach.get(n,'')+(' ' if n in teach else '')+'Study question. '+questions[n-1],sourceIds=['cfm-nt-2023-42'] if n in teach else []),eventOrder=n,dateLabel='Book order',historicalNote=meaning,mapNote='The marker identifies the named recipient city. No exact prison, home, or heavenly location is assigned.',route=[],routeEvidence='The letter does not establish an exact delivery route or prison city.'))
data=dict(id='philippians',bibleCode='PHP',name='Philippians',description='Shared work · humility · costly service · joy · contentment',chapterCount=4,scripture=t,chapters=chapters,people=people,places=places,sources=sources,review=dict(date=DATE,contextReviewDate=DATE,copyReviewDate=DATE,scope='All 104 verses read for four original contextual explanations and exact selections. Six selected profiles and one city marker do not claim exhaustive coverage. One Church lesson retains actual chapter discussion. Works\x27 interpretation remains attributed. Exact dates, prison city, original manuscripts, Greek forms, rival identities, and the cause of the women\x27s disagreement were not independently verified.',nextBook='colossians'))
if '--ready' in sys.argv:finish(data)
else:(ROOT/'review/philippians-draft.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
