"""Build Ephesians from reviewed Scripture and original contextual notes."""
import json,copy,sys
from book_common import ROOT,OUT,scripture,source,person,finish
DATE='2026-10-07';t=scripture('ephesians','EPH',6)
assert [len(t[str(n)]) for n in range(1,7)]==[23,22,21,32,33,24]
assert sum(map(len,t.values()))==155
assert not any('\ufffd' in str(v) for vv in t.values() for v in vv)
notes=json.loads((ROOT/'scripts/book-context-complete/ephesians.json').read_text(encoding='utf8'));sources=[]
s=source('web','Ephesians · World English Bible','https://ebible.org/engwebp/EPH01.htm','All six chapters supply the primary text for original close readings.','Scripture','historical','The letter names Paul as its speaker. Authorship, date, original manuscripts, Greek forms, the exact prison setting, and the complete recipient group were not independently verified. Household commands are read within the letter rather than treated as proof that unequal power disappeared.')
s.update(author='World English Bible translators',publisher='eBible.org',chapterCoverage=list(range(1,7)),reviewed=dict(date=DATE,scope='All 155 verses read for six original contextual explanations and exact selections. Surroundings, counts, and character integrity checked.'));sources.append(s)
s=source('carlson-ephesians','Commentary on Ephesians 6:10-20','https://www.workingpreacher.org/commentaries/revised-common-lectionary/ordinary-21-2/commentary-on-ephesians-610-20-6','Carlson reads the armor as resistance supported by gifts from God.','Scholarly study','historical','This is Carlson\x27s interpretation. His Greek analysis, ancient speech comparisons, and proposed links with Isaiah were not independently verified. Linked commentaries and podcasts were not reviewed.')
s.update(author='Richard Carlson',publisher='Luther Seminary',year=2021,chapterCoverage=[6],reviewed=dict(date=DATE,scope='Complete commentary body read. The guide attributes his reading of standing through God\x27s gifts and shared prayer.'));sources.append(s)
s=source('cfm-nt-2023-41','October 2–8 · Ephesians','https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-sunday-school-new-testament-2023/41?lang=eng','The lesson studies shared Church work, family care, and protection from evil.','LDS Come, Follow Me','lds','Coverage follows actual chapter discussion. The lesson does not independently study chapters one and three. Its application to present Church leaders remains Church teaching rather than independent historical evidence.')
s.update(author='The Church of Jesus Christ of Latter-day Saints',publisher='The Church of Jesus Christ of Latter-day Saints',year=2023,chapterCoverage=[2,4,5,6],reviewed=dict(date=DATE,scope='Complete lesson body and included resources read. Linked talks, manuals, and Restoration passages were not independently reviewed.'));sources.append(s)
acts=json.loads((OUT/'acts.json').read_text(encoding='utf8'));sources.extend(copy.deepcopy([s for s in acts['sources'] if s['id'] in ['atlas-canaan','net-acts-map']]))
people=[person('paul','Paul','Named letter speaker who describes himself as a prisoner','He sends Tychicus to report his condition and comfort the hearers.','Ephesians 1:1; 3:1; 6:19–22','His appeal for prayer shows that the speaker also needs the group\x27s support.'),person('jesus','Jesus Christ','Lord whose gift joins former outsiders within one body','His love becomes the measure for the assembly and the household instructions.','Ephesians 1–6','The letter connects received belonging with conduct shaped by his self-giving love.'),person('tychicus','Tychicus','Trusted messenger sent to report the speaker\x27s condition','He is called a beloved brother and faithful servant in the Lord.','Ephesians 6:21–22','His visit carries personal news and comfort beyond the written appeal.')]
for p in people:p.update(placeIds=[],linkNames=['Jesus','Christ'] if p['id']=='jesus' else [p['name']],verseScope={})
places=copy.deepcopy([p for p in acts['places'] if p['id']=='ephesus'])
for p in places:p.update(summary='Ephesus is named in the opening address of the selected WEB text.',verseScope={},linkNames=['Ephesus'])
pc={'paul':[1,3,6],'jesus':list(range(1,7)),'tychicus':[6]}
summaries=['Received gifts lead into a prayer for hope and understanding.','Mercy and peace make former outsiders members of one household.','The imprisoned speaker explains shared inheritance and prays for inward strength.','Different gifts serve one body through truthful and caring conduct.','Light, shared worship, and Christ\x27s love shape household instructions.','Unequal household roles lead into spiritual resistance, shared prayer, and a messenger\x27s visit.']
questions=['Why does the opening blessing lead into a prayer for understanding?','How do good works follow received grace rather than supply a reason to boast?','Why does the speaker ask the hearers not to lose heart over his troubles?','How does truthful speech protect members of the same body?','How does Christ\x27s self-giving love shape the command to husbands?','Why does the armor passage lead into prayer for the imprisoned speaker?']
teach={2:'The selected Church lesson applies the building image to Christ, apostles, and prophets.',4:'The selected Church lesson teaches that different responsibilities strengthen and unify the Church.',5:'The selected Church lesson teaches family care through the Savior\x27s example.',6:'The selected lesson teaches care for children and protection through the armor of God.'};chapters=[]
for n,v,title,meaning in notes:
 chapters.append(dict(chapter=n,title=title,summary=summaries[n-1],meaning=meaning,people=[pid for pid,cc in pc.items() if n in cc],places=['ephesus'] if n==1 else [],sourceIds=['web']+(['carlson-ephesians'] if n==6 else []),lds=dict(text=teach.get(n,'')+(' ' if n in teach else '')+'Study question. '+questions[n-1],sourceIds=['cfm-nt-2023-41'] if n in teach else []),eventOrder=n,dateLabel='Book order',historicalNote=meaning,mapNote='The city marker identifies the opening recipient reference. No exact prison, house, or heavenly location is assigned.',route=[],routeEvidence='The letter does not establish an exact delivery route or prison location.'))
data=dict(id='ephesians',bibleCode='EPH',name='Ephesians',description='Grace · shared belonging · one body · household care · spiritual resistance',chapterCount=6,scripture=t,chapters=chapters,people=people,places=places,sources=sources,review=dict(date=DATE,contextReviewDate=DATE,copyReviewDate=DATE,scope='All 155 verses read for six original contextual explanations and exact selections. Three selected profiles and one city reference do not claim exhaustive coverage. One Church lesson retains actual chapter discussion. Carlson\x27s interpretation remains attributed. Authorship, date, original manuscripts, Greek forms, exact prison setting, and the full recipient group were not independently verified.',nextBook='philippians'))
if '--ready' in sys.argv:finish(data)
else:(ROOT/'review/ephesians-draft.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
