"""Second Chronicles: selected people, chapter studies, and reviewed sources."""
import json
from book_common import OUT,source,person,place,scripture,finish
rows=[
('Solomon seeks wisdom','Solomon seeks wisdom at Gibeon. The chapter also describes royal wealth, horses, and trade.','Wisdom is requested for public responsibility. Reported wealth is not an independently audited account.','solomon,david,moses,bezalel','gibeon,jerusalem,kiriath-jearim,egypt'),
('Temple workers and Tyrian cooperation','Solomon requests timber and skilled work from Huram. Foreign residents supply the labor force.','The project depends on international cooperation and imposed labor. The king and craft worker named Huram remain distinct.','solomon,david,hiram,hiram-artisan','jerusalem,tyre,lebanon,joppa'),
('The temple building','Solomon builds the temple at the site associated with David and Ornan. Rooms, decoration, and pillars receive detailed descriptions.','The narrated measurements express the building’s importance. They do not supply a verified modern reconstruction.','solomon,david,araunah','jerusalem'),
('Temple vessels and bronze work','Huram makes bronze vessels. Solomon provides the temple’s gold objects and furnishings.','Skilled labor supports worship. The craft worker is distinct from Tyre’s king, despite their shared name.','solomon,hiram-artisan','jerusalem,jordan'),
('The ark enters the temple','Priests bring the ark into the inner sanctuary. Singers and trumpeters praise together, and a cloud fills the house.','The narrative joins remembered covenant, music, and divine presence. Earlier ancestors are recalled rather than newly alive.','solomon,david,moses,asaph-singer,heman-singer,jeduthun','jerusalem,sinai'),
('Solomon’s dedication prayer','Solomon blesses the assembly and prays for justice, forgiveness, foreigners, and people taken captive.','The prayer says even heaven cannot contain God. It includes outsiders and anticipates responsibility beyond the building.','solomon,david','jerusalem,egypt'),
('Dedication and a conditional promise','The assembly celebrates the dedication. God’s response calls for humility and repentance and warns against abandoned commitments.','The promise concerns this narrated covenant community. It is not a mechanical guarantee for every later nation.','solomon,david','jerusalem,hamath,egypt'),
('Construction, labor, and sea trade','Solomon develops towns, assigns forced labor, organizes worship, and works with Huram’s sailors. Pharaoh’s daughter receives a separate residence.','The account highlights organization while recording unequal labor obligations. It does not justify forced service.','solomon,david,moses,hiram,pharaoh-daughter-solomon','jerusalem,beth-horon,hamath,lebanon,ezion-geber,edom'),
('Sheba’s queen and Solomon’s reputation','The queen of Sheba tests Solomon with questions. Gifts, trade, wealth, and the succession to Rehoboam close his reign.','The queen speaks and evaluates for herself. Her personal name and exact home capital are not supplied.','solomon,queen-sheba,hiram,nathan-prophet,ahijah-shiloh,iddo-seer,jeroboam,rehoboam,david','jerusalem,sheba,egypt'),
('Rehoboam refuses relief','The people ask Rehoboam to reduce their burden. He chooses harsh advice, and the northern tribes reject his rule.','A leader’s refusal to listen has public consequences. Hadoram is the labor officer, not Tou’s envoy.','rehoboam,jeroboam,solomon,ahijah-shiloh,adoram,david,jesse','shechem,jerusalem,egypt'),
('Defense, migration, and royal families','Shemaiah stops an attack on the northern tribes. Rehoboam strengthens towns, receives religious migrants, and arranges family succession.','The account connects loyalty with worship and family policy. A military roster is not an excavated boundary map.','rehoboam,shemaiah,jeroboam,solomon,david,mahalath-rehoboam,abihail-rehoboam,maacah-queen,abijam','jerusalem,bethlehem,tekoa,adullam,gath,lachish,hebron'),
('Shishak and a reduced kingdom','Shishak takes fortified towns and Jerusalem’s treasures. Rehoboam humbles himself but receives a mixed closing assessment.','Loss and limited relief coexist in the account. Humility does not erase the consequences of earlier rule.','rehoboam,shishak,shemaiah,naamah,iddo-seer,abijam,solomon','jerusalem,egypt'),
('Abijah’s speech and war','Abijah confronts Jeroboam and appeals to David’s covenant and temple worship. Judah wins the narrated battle.','The speech presents Judah’s claim to legitimacy. Its large military totals remain reported figures.','abijam,jeroboam,david,solomon,rehoboam,aaron,iddo-seer','jerusalem,bethel'),
('Asa’s reforms and appeal for help','Asa removes worship objects and strengthens towns. He calls for divine help against Zerah’s forces.','The narrative emphasizes trust while also describing killing and plunder. Faith application does not verify every military quantity.','asa,abijam,zerah-cushite','jerusalem,mareshah,gerar'),
('Azariah’s warning and covenant','Azariah addresses Asa. The assembly renews its covenant, and Asa removes Maacah’s royal status.','The covenant’s death penalty remains part of the ancient account. It is not an instruction for religious coercion today.','asa,azariah-oded,oded-azariah,maacah-queen','jerusalem,kidron'),
('Asa’s alliance and anger','Asa pays Ben Hadad to break his treaty with Baasha. Hanani rebukes Asa, who imprisons him and oppresses others.','The chapter judges the king’s response to correction. Its criticism of misplaced trust is not a general rejection of medical care.','asa,baasha,ben-hadad-asa,hanani-seer','jerusalem,damascus,ramah,dan,mizpah'),
('Jehoshaphat teaches and strengthens Judah','Jehoshaphat sends officials, Levites, and priests to teach the law. Town defenses and military service also receive attention.','Education and administration shape public life. Shared names do not identify these teachers with earlier prophets or rulers.','jehoshaphat,asa,david,amasiah','jerusalem'),
('Micaiah and the war with Ahab','Jehoshaphat joins Ahab. Micaiah challenges favorable predictions and reports a heavenly council before Ahab dies in battle.','The vision raises questions about divine agency and deception. Micaiah’s first answer must be read with the king’s demand for truth.','jehoshaphat,ahab,micaiah,zedekiah-chenaanah,amon-governor,joash-prince,ahab-prophets','samaria,ramoth-gilead'),
('Correction and impartial judgment','Jehu rebukes Jehoshaphat’s alliance. The king appoints judges and distinguishes religious and royal responsibilities.','Justice requires honesty and refusal of bribes. Courage does not remove a judge’s duty to fairness.','jehoshaphat,jehu-hanani,amariah-chief,zebadiah-ishmael','jerusalem,beersheba'),
('Prayer, Jahaziel, and deliverance','Jehoshaphat gathers the people for prayer. Jahaziel speaks encouragement. The opposing forces destroy one another, and Judah returns with plunder.','The account presents dependence and communal praise. Its later wrecked ships also qualify a simple success story.','jehoshaphat,jahaziel,asaph-singer,azubah,ahaziah-ahab,eliezer-dodavahu,abraham,asa','jerusalem,en-gedi,tekoa,ezion-geber,moab,edom'),
('Jehoram’s violence and decline','Jehoram kills his brothers and adopts Ahab’s family practices. Revolts, invasion, Elijah’s letter, and illness mark his reign.','Royal strength does not excuse family violence. The letter’s chronology should be compared with Elijah’s account in Kings.','jehoram-judah,jehoshaphat,ahab,elijah,ahaziah-judah,david','jerusalem,edom,libnah'),
('Ahaziah dies and Joash is hidden','Ahaziah follows Ahab’s family and dies during Jehu’s overthrow. Jehoshabeath and a nurse protect Joash from Athaliah.','The narrative preserves rescue within dynastic violence. Its age and naming variants remain visible beside Kings.','ahaziah-judah,jehoram-judah,joram-israel,athaliah,omri,ahab,hazael,jehu-nimshi,jehosheba,joash-nurse,joash-judah,jehoiada','jerusalem,ramoth-gilead,jezreel,samaria'),
('Jehoiada installs Joash','Jehoiada organizes guards and worship workers. Joash receives the crown, Athaliah dies, and a covenant follows.','The account combines temple authority, royal succession, and violence. Mattan’s death remains a reported act, not a present instruction.','jehoiada,joash-judah,athaliah,mattan-baal,david,moses','jerusalem'),
('Temple repair and Zechariah’s death','Joash repairs the temple during Jehoiada’s life. Afterward he rejects correction and orders Zechariah’s death. His own servants later kill him.','A good beginning does not guarantee lasting justice. Zechariah is Jehoiada’s son, not the later prophet or Israel’s king.','joash-judah,jehoiada,zibiah,zechariah-jehoiada,athaliah,moses,zabad-shimeath,jehozabad,amaziah','jerusalem,beersheba,damascus'),
('Amaziah’s victories and defeat','Amaziah dismisses hired troops, defeats Edom, adopts its gods, and refuses a prophet. Joash of Israel defeats him.','The account reports severe captive killings. Pride and refusal of correction accompany a victory that does not secure the king’s future.','amaziah,jehoaddan,joash-israel,joash-judah,jehoahaz-israel,jehu-nimshi,moses,amaziah-man-god,amaziah-prophet,obed-edom-amaziah','jerusalem,edom,samaria,beth-horon,beth-shemesh,lachish'),
('Uzziah’s strength and forbidden incense','Uzziah develops towns, agriculture, and military defenses. Azariah, the priest opposing Uzziah, leads resistance to his incense offering, and illness follows.','The king’s authority has limits. The ancient disease label does not establish a modern diagnosis or justify stigma.','azariah,amaziah,jechiliah,zechariah-uzziah,azariah-uzziah-priest,jotham,isaiah,aaron','jerusalem,gath,ashdod,egypt,ezion-geber'),
('Jotham builds and governs','Jotham strengthens Jerusalem and other defenses and receives Ammonite tribute. The narrator distinguishes his conduct from the people’s conduct.','A ruler’s faithful choices do not automatically reform the whole community. The short account leaves many details unstated.','jotham,azariah,jerushah,ahaz','jerusalem'),
('Ahaz, captives, and Oded’s intervention','Ahaz suffers defeats and seeks Assyrian help. Oded and northern leaders secure humane care and return for Judah’s captives.','Those who win a battle still answer for mistreatment. The account names people who resist enslavement and provide practical care.','ahaz,pekah,pul,oded-samaria,captive-care-leaders,hezekiah,david','jerusalem,damascus,samaria,jericho,assyria,beth-shemesh'),
('Hezekiah restores temple service','Hezekiah opens the temple and calls workers to cleanse it. Sacrifice and music resume with public thanksgiving.','Restoration requires practical labor as well as royal orders. Remembered Davidic musicians are not necessarily alive during this later reign.','hezekiah,abi,ahaz,david,gad,nathan-prophet,asaph-singer,heman-singer,jeduthun,aaron','jerusalem,kidron'),
('Passover invitations and pardon','Hezekiah invites northern communities to Jerusalem. Some mock the couriers, but others attend. He prays for participants who lack ritual preparation.','The narrative joins worship with welcome and healing. Care for guests matters alongside ceremonial rules.','hezekiah,moses,abraham,isaac,solomon,david','jerusalem,beersheba,dan,assyria,kidron'),
('Offerings and faithful distribution','Hezekiah supports service divisions and the people bring offerings. Azariah, Conaniah, Shimei, and Kore help organize supplies.','Trustworthy distribution supports workers and their families. The chapter does not equate all later financial systems with this arrangement.','hezekiah,azariah-hezekiah-priest,conaniah-hezekiah,shimei-conaniah,kore-imnah,aaron','jerusalem'),
('Sennacherib’s challenge and Hezekiah’s response','Hezekiah prepares defenses and water supplies. Sennacherib challenges trust in God. Hezekiah and Isaiah pray, and the invader withdraws.','Compare this presentation with Kings and Assyrian royal claims. Reported deliverance does not establish each account’s full chronology.','hezekiah,sennacherib,isaiah,manasseh-king,david','jerusalem,lachish,assyria,babylon'),
('Manasseh’s repentance and Amon’s refusal','Manasseh promotes forbidden worship, suffers captivity, then humbles himself and returns. Amon refuses humility and dies in a conspiracy.','Manasseh’s restoration is prominent here and absent from Kings. Repentance does not remove the earlier harm from the account.','manasseh-king,hezekiah,amon-king,josiah,david,solomon,moses','jerusalem,babylon,assyria'),
('Josiah’s reforms and Huldah’s answer','Josiah removes worship objects and repairs the temple. Hilkiah finds a law book, and Huldah explains its judgment and promise.','A woman’s prophetic answer guides the royal delegation. Listening leads to public commitments rather than possession of a book alone.','josiah,hilkiah-priest,shaphan,huldah,shallum-huldah,ahikam,achbor,asaiah,joah-joahaz,maaseiah-josiah,moses,david','jerusalem'),
('Josiah’s Passover and death','Josiah organizes a large Passover. Later he refuses Neco’s warning, suffers a battle wound, and dies after return to Jerusalem.','The narrator recognizes divine speech through an Egyptian ruler. Josiah’s earlier faithfulness does not make every later decision correct.','josiah,necho,jeremiah,hilkiah-priest,david,solomon,moses,aaron,asaph-singer,heman-singer,jeduthun,samuel','jerusalem,megiddo,carchemish,egypt'),
('Exile and Cyrus’s proclamation','The final kings face Egyptian and Babylonian power. Jerusalem and the temple fall. Cyrus’s proclamation opens a path toward return.','The closing joins judgment with renewed possibility. Its age variants and family terms require comparison with Kings.','jehoahaz-judah,jehoiakim,jehoiachin,zedekiah,nebuchadnezzar,necho,jeremiah,cyrus,josiah','jerusalem,babylon,egypt')]
prior={}
for slug in ['genesis','exodus','numbers','1-samuel','2-samuel','1-kings','2-kings','1-chronicles']:
 for p in json.loads((OUT/f'{slug}.json').read_text(encoding='utf8'))['people']:prior[p['id']]=p
new=[
('jeremiah','Jeremiah','Prophet remembered in lament and exile notices','The book connects him with mourning for Josiah and messages about captivity.','35:25; 36:12,21–22','These references do not retell his full prophetic book or identify every later collection of laments.'),
('jechiliah','Jechiliah','Mother of Uzziah','From Jerusalem. Named in Uzziah’s reign notice.','26:3','The notice identifies her without supplying a complete biography.'),
('jerushah','Jerushah','Mother of Jotham','Daughter of Zadok. The shared name does not identify her father with David’s priest.','27:1','Royal genealogy remembers women while often leaving their activities unstated.'),
('cyrus','Cyrus','Persian king issuing a return proclamation','The closing proclamation addresses those who may rebuild at Jerusalem.','36:22–23','The book ends with permission and possibility rather than a full account of rebuilding.'),
('azubah','Azubah, Jehoshaphat’s mother','Woman named in a royal reign notice','Daughter of Shilhi and mother of Jehoshaphat.','20:31','The short notice gives parentage without describing her influence or complete life.'),
('iddo-seer','Iddo, the seer','Seer associated with named records','The closing notices connect his records with Solomon, Rehoboam, and Abijah.','9:29; 12:15; 13:22','The records are named but their complete contents are not available.'),
('mahalath-rehoboam','Mahalath','Wife of Rehoboam','Daughter of Jerimoth and Abihail. Mother of Jeush, Shemariah, and Zaham.','11:18–19','The genealogy records a woman within royal family policy without a full biography.'),
('abihail-rehoboam','Abihail, Mahalath’s mother','Woman in the royal family genealogy','Daughter of Eliab and mother of Mahalath in the family notice.','11:18','Her name must not be confused with unrelated men or women named Abihail.'),
('zerah-cushite','Zerah, the Cushite','Leader opposed by Asa','Called the Ethiopian in the reading translation. His personal ancestry is not supplied.','14:9–13','The identification and reported troop total remain uncertain. He is not Judah’s son Zerah.'),
('azariah-oded','Azariah, son of Oded','Prophet addressing Asa','His father is Oded. He is distinct from King Uzziah and several priests named Azariah.','15:1–7','His warning connects seeking God with courage and perseverance.'),
('oded-azariah','Oded, Azariah’s father','Prophetic name in Asa’s account','Father of Azariah in 15:1. Verse 8 also names Oded in the prophecy notice.','15:1,8','The wording needs care. This profile is not the later Oded at Samaria.'),
('hanani-seer','Hanani, the seer','Critic of Asa’s alliance','He addresses Asa and is imprisoned after his warning.','16:7–10','Royal anger suppresses criticism rather than answering it.'),
('amasiah','Amasiah, son of Zichri','Military captain volunteering for service','Named among Jehoshaphat’s commanders.','17:16','The brief notice emphasizes willing service but supplies no complete life account.'),
('amariah-chief','Amariah, the chief priest','Leader over religious judgments','Named with Zebadiah in Jehoshaphat’s appointments.','19:11','His role is distinct from several Amariahs in service genealogies.'),
('zebadiah-ishmael','Zebadiah, son of Ishmael','Leader over royal judgments','Appointed alongside Amariah under Jehoshaphat.','19:11','The division of duties still requires honesty and courage.'),
('jahaziel','Jahaziel, the Levite','Speaker during Jehoshaphat’s assembly','Descendant of Asaph through Zechariah, Benaiah, Jeiel, and Mattaniah.','20:14–17','His speech encourages a fearful assembly. Same-name ancestors are not identified with earlier royal officers.'),
('eliezer-dodavahu','Eliezer, son of Dodavahu','Prophet criticizing a shipping alliance','From Mareshah. He addresses Jehoshaphat’s alliance with Ahaziah.','20:37','He is not Moses’s son Eliezer. The shipwreck qualifies the king’s success story.'),
('zechariah-jehoiada','Zechariah, son of Jehoiada','Prophet killed after correcting Joash','Son of Jehoiada, whose care Joash had received.','24:20–22','The king orders his death rather than accepting correction. Other Zechariahs remain distinct.'),
('zabad-shimeath','Zabad, son of Shimeath','Servant involved in Joash’s death','Son of Shimeath the Ammonitess.','24:26','Kings has a different name in its parallel notice. This profile preserves Chronicles’ wording.'),
('amaziah-man-god','The man of God advising Amaziah','Unnamed adviser opposing hired troops','Addresses Amaziah before the Edomite campaign.','25:7–9','The text does not name him or establish identity with the later warning prophet.'),
('amaziah-prophet','The prophet warning Amaziah','Unnamed critic of adopted Edomite gods','Addresses Amaziah after the campaign and receives a threat.','25:15–16','He is not automatically the earlier man of God. The text leaves his identity unspecified.'),
('obed-edom-amaziah','Obed-Edom, the temple custodian','Named in the account of seized temple property','The notice occurs during Amaziah’s reign.','25:24','Do not assume he is the ark host from David’s time. The name alone does not establish identity.'),
('zechariah-uzziah','Zechariah, Uzziah’s adviser','Teacher connected with Uzziah’s early faithfulness','The notice describes his understanding of divine vision.','26:5','He is not Jehoiada’s son, Israel’s king, or the later prophetic author merely because the name matches.'),
('azariah-uzziah-priest','Azariah, the priest opposing Uzziah','Priest defending limits on royal incense service','Leads eighty priests in opposing the king’s act.','26:17–20','He is distinct from King Azariah/Uzziah and the priest in Hezekiah’s later supply account.'),
('oded-samaria','Oded, the prophet at Samaria','Critic of captive enslavement','Addresses Israel’s returning army during Ahaz’s reign.','28:9–11','He insists that victory does not excuse cruelty. He is distinct from Azariah’s father in chapter 15.'),
('captive-care-leaders','The four leaders who care for captives','Northern officials resisting enslavement','Azariah son of Johanan, Berechiah son of Meshillemoth, Jehizkiah son of Shallum, and Amasa son of Hadlai.','28:12–15','They provide clothes, sandals, food, drink, treatment, and transport. Their shared names do not establish earlier identities.'),
('azariah-hezekiah-priest','Azariah, Hezekiah’s chief priest','Priest explaining abundant offerings','Of the house of Zadok. Named in Hezekiah’s supply arrangements.','31:10,13','Distinct from Uzziah and his opposing priest. Supplies support service and households.'),
('conaniah-hezekiah','Conaniah, the Levite','Supervisor of temple supplies','His brother Shimei assists him under Hezekiah.','31:12–13','This is not automatically David’s music leader Chenaniah or Josiah’s later donor Conaniah.'),
('shimei-conaniah','Shimei, Conaniah’s brother','Assistant over temple supplies','Serves as second to his brother under Hezekiah.','31:12–13','He is distinct from David’s critic Shimei son of Gera.'),
('kore-imnah','Kore, son of Imnah','Gatekeeper distributing voluntary offerings','A Levite at the east gate during Hezekiah’s reign.','31:14–15','Faithful distribution attends to people of different status. His name is not Korah’s biography.'),
('joah-joahaz','Joah, son of Joahaz','Recorder sent to oversee temple repair','Serves with Shaphan and Maaseiah under Josiah.','34:8','He is distinct from Hezekiah’s recorder Joah son of Asaph.'),
('maaseiah-josiah','Maaseiah, Josiah’s city governor','Official in temple repair administration','Sent with Shaphan and Joah during Josiah’s reign.','34:8','He is not Ahaz’s son Maaseiah or every earlier officer with the same name.')]
needed=list(dict.fromkeys(pid for row in rows for pid in row[3].split(',')))
defs={i:person(i,n,r,rel,'2 Chronicles '+refs,m) for i,n,r,rel,refs,m in new}
people=[dict(defs[pid] if pid in defs else prior[pid]) for pid in needed]
context={
'solomon':('King building and dedicating the temple','Wisdom, international cooperation, worship, and royal wealth shape his account.'),
'david':('Earlier king remembered in temple and royal traditions','His preparations and covenant recur as remembered foundations, not a new reign.'),
'hiram':('Tyrian king supplying temple materials and sailors','Huram cooperates with Solomon. He is distinct from the skilled worker Huram-abi.'),
'nathan-prophet':('Earlier prophet remembered in records and worship orders','His records and instructions are recalled without retelling his complete ministry.'),
'ahijah-shiloh':('Prophet recalled in records and the kingdom division','His earlier message explains the northern division within this account.'),
'rehoboam':('King whose harsh answer divides the kingdom','Refusal to reduce burdens has lasting consequences. Later humility brings limited relief.'),
'abijam':('King appealing to David’s covenant against Jeroboam','Chronicles emphasizes his speech and victory. Kings presents a different evaluation.'),
'asa':('Reforming king whose later response rejects correction','Early trust and covenant renewal contrast with imprisonment of Hanani and oppression.'),
'jehoshaphat':('King organizing teaching, justice, and communal prayer','His trust and public reforms coexist with criticized alliances and failed shipping.'),
'jehu-hanani':('Prophet correcting Jehoshaphat’s alliance','He criticizes support for Ahab while recognizing other faithful conduct.'),
'ahaziah-ahab':('Northern king allied in Jehoshaphat’s shipping venture','The criticized alliance ends in wrecked ships. He is distinct from Judah’s Ahaziah.'),
'abraham':('Earlier ancestor remembered as God’s friend','Jehoshaphat recalls the land promise in prayer. This is remembrance, not a new appearance.'),
'jehoram-judah':('Judean king who kills his brothers','Violence, revolt, invasion, and illness mark his account. Royal descent does not excuse his actions.'),
'elijah':('Prophet associated with a warning letter to Jehoram','Compare the letter’s placement with Elijah’s narrative in Kings. The chronology requires care.'),
'ahaziah-judah':('Judean king killed during Jehu’s overthrow','The reading says forty-two at accession, while 2 Kings 8:26 says twenty-two. The difference remains visible.'),
'joram-israel':('Northern king wounded in conflict with Hazael','Ahaziah visits him before Jehu’s overthrow. He is distinct from Judah’s Jehoram.'),
'joash-judah':('Protected child king who later rejects prophetic correction','Temple repair precedes the ordered killing of Jehoiada’s son Zechariah. A good beginning does not secure lasting justice.'),
'amaziah':('Judean king refusing correction after victory over Edom','His adoption of Edomite gods and defeat by Israel qualify the earlier military success.'),
'azariah':('Uzziah, king opposed by priests over incense service','Agricultural and military strength precede his temple conflict. Ancient disease language does not establish a modern diagnosis.'),
'jotham':('Judean king strengthening towns and Jerusalem','The narrator distinguishes his conduct from the community’s continued corruption.'),
'ahaz':('Judean king seeking foreign help during defeat','Oded and northern leaders protect captives while the king’s worship policies receive criticism.'),
'hezekiah':('King restoring temple service and welcoming Passover guests','Cleansing, worship, distribution, defense, and humility shape his account. Welcome accompanies ceremonial responsibility.'),
'manasseh-king':('Judean king whose captivity leads to humility and return','Chronicles reports captivity, humility, return, and reform. Kings does not include this restoration account.'),
'amon-king':('Judean king refusing his father’s humility','The narrative distinguishes his refusal from Manasseh’s repentance. A conspiracy ends his reign.'),
'josiah':('King renewing worship after the law book is found','Reform and Passover receive detailed attention. His refusal of Neco’s warning precedes his death.'),
'jehoiakim':('Judean king confronted by Babylonian power','The notice reports removal of temple vessels and captivity measures without a complete independent chronology.'),
'jehoiachin':('Judean king removed with temple treasures','The reading says eight at accession, while 2 Kings 24:8 says eighteen. The guide does not silently harmonize them.'),
'zedekiah':('Final Judean king before Jerusalem’s fall','Refusal of correction and rebellion precede destruction. The closing also opens a possibility of return.'),
'necho':('Egyptian ruler warning Josiah and controlling Judah’s succession','The narrator recognizes divine speech through his warning. He later removes Jehoahaz and imposes tribute.'),
'samuel':('Earlier prophet remembered in Passover comparison','Josiah’s celebration is compared with earlier Israel. The notice does not retell Samuel’s life.'),
'gad':('Earlier seer remembered in David’s musical arrangements','His instruction is recalled in Hezekiah’s later restoration of worship.'),
'isaac':('Earlier ancestor remembered in Hezekiah’s invitation','The appeal recalls ancestral covenant rather than presenting Isaac as alive during this reign.'),
'asaph-singer':('Earlier musical leader remembered through service traditions','Later sons and musical divisions preserve his name. He is not newly alive during Hezekiah or Josiah.'),
'heman-singer':('Earlier musical leader remembered through service traditions','Later descendants and divisions recall his name. This does not establish his presence in later royal reigns.'),
'jeduthun':('Earlier musical leader remembered through service traditions','Later descendants and divisions recall his name. The guide distinguishes remembrance from contemporary participation.')}
for p in people:
 if p['id'] in context:p['role'],p['meaning']=context[p['id']]
aliases={'hiram':['Huram'],'hiram-artisan':['Huram-abi','Huram'],'abijam':['Abijah'],'adoram':['Hadoram'],'ben-hadad-asa':['Ben Hadad'],'jehu-hanani':['Jehu'],'micaiah':['Micaiah'],'zedekiah-chenaanah':['Zedekiah'],'joash-judah':['Joash'],'joash-israel':['Joash'],'joash-prince':['Joash'],'ahaziah-judah':['Ahaziah','Azariah','Jehoahaz'],'ahaziah-ahab':['Ahaziah'],'jehoram-judah':['Jehoram'],'joram-israel':['Jehoram','Joram'],'jehu-nimshi':['Jehu'],'jehosheba':['Jehoshabeath'],'azariah':['Uzziah','Azariah'],'abi':['Abijah'],'jehoahaz-judah':['Joahaz','Jehoahaz'],'necho':['Neco'],'pul':['Tilgath-pilneser'],'araunah':['Ornan'],'gad':['Gad'],'asaph-singer':['Asaph'],'heman-singer':['Heman'],'azariah-oded':['Azariah'],'oded-azariah':['Oded'],'amariah-chief':['Amariah'],'zebadiah-ishmael':['Zebadiah'],'eliezer-dodavahu':['Eliezer'],'zechariah-jehoiada':['Zechariah'],'zabad-shimeath':['Zabad'],'obed-edom-amaziah':['Obed-Edom'],'zechariah-uzziah':['Zechariah'],'azariah-uzziah-priest':['Azariah'],'oded-samaria':['Oded'],'azariah-hezekiah-priest':['Azariah'],'conaniah-hezekiah':['Conaniah'],'shimei-conaniah':['Shimei'],'kore-imnah':['Kore'],'joah-joahaz':['Joah'],'maaseiah-josiah':['Maaseiah'],'manasseh-king':['Manasseh'],'amon-king':['Amon'],'amon-governor':['Amon']}
scopes={'hiram':{2:[3,11,12]},'hiram-artisan':{2:[13],4:[11,16]},'abijam':{11:[20,22]},'ahaziah-judah':{21:[17],22:[1,2,6,7,8,9,10,11]},'jehoram-judah':{22:[1,11]},'joram-israel':{22:[5,7]},'joash-judah':{22:[11],25:[]},'joash-israel':{25:[17,18,21]},'joash-prince':{18:[25]},'azariah':{26:[1,2,3,4,5,6,8,9,11,14,16,18,19,21,22,23]},'azariah-uzziah-priest':{26:[17,20]},'azariah-oded':{15:[1]},'oded-azariah':{15:[1,8]},'asaph-singer':{29:[13,30],35:[15]},'heman-singer':{29:[14],35:[15]},'jeduthun':{29:[14],35:[15]},'nathan-prophet':{9:[29],29:[25]},'gad':{29:[25]},'jehu-nimshi':{25:[17]},'jehoahaz-israel':{25:[17]},'manasseh-king':{32:[33]},'achbor':{34:[20]}}
for p in people:
 p['verseScope']={str(k):v for k,v in scopes.get(p['id'],{}).items()}
 p['linkNames']=aliases.get(p['id'],[])
 if p['id']=='achbor':p['name']='Abdon / Achbor';p['linkNames']=['Abdon'];p['relations']='Son of Micah in 34:20. Kings uses Achbor son of Micaiah in the parallel.'
 if p['id']=='jehosheba':p['name']='Jehoshabeath / Jehosheba';p['relations']='Daughter of Jehoram, sister of Ahaziah, and wife of Jehoiada in 22:11.'
 if p['id']=='adoram':p['name']='Hadoram / Adoram';p['meaning']='Forced-labor officer killed during the northern revolt. Distinct from Tou’s envoy.'
 if p['id']=='hiram-artisan':p['name']='Huram-abi / Hiram, the craft worker';p['relations']='Son of a woman of Dan and a Tyrian father in 2:14. Kings gives different maternal wording.'
 if p['id']=='abijam':p['name']='Abijah / Abijam';p['relations']='Son of Rehoboam. Chapter 11 names Maacah, while 13:2 names Micaiah daughter of Uriel.'
 if p['id']=='azariah':p['name']='Uzziah / Azariah'
 if p['id']=='abi':p['name']='Abijah / Abi, Hezekiah’s mother'
 if p['id']=='jehozabad':p['relations']='Son of Shimrith the Moabitess in 24:26. Kings spells his mother’s name differently.'
 chapters=[i for i,row in enumerate(rows,1) if p['id'] in row[3].split(',')]
 p['passages']='2 Chronicles '+', '.join(map(str,chapters))
 p['sourceIds']=['web'];p['placeIds']=[]
 p['life']='Birth and death years are not securely known.'
 if p['id']=='manasseh-king':p['meaning']='Chronicles reports captivity, humility, return, and reform. Kings does not include this restoration account.'
 if p['id']=='ahaziah-judah':p['meaning']='The reading says forty-two at accession, while 2 Kings 8:26 says twenty-two. The difference remains visible.'
 if p['id']=='jehoiachin':p['meaning']='The reading says eight at accession, while 2 Kings 24:8 says eighteen. The guide does not silently harmonize them.'
 if p['id']=='zedekiah':p['relations']='Josiah’s son and Jehoiachin’s uncle in Kings. Chronicles 36:10 uses brother, a differing family term.'
 if p['id']=='hanani-seer':p['relations']+=' Jehu is called Hanani’s son in 19:2; the text does not independently resolve every namesake.'
locations={'solomon':['jerusalem','gibeon'],'david':['jerusalem'],'hiram':['tyre'],'hiram-artisan':['tyre','jerusalem'],'queen-sheba':['sheba','jerusalem'],'rehoboam':['shechem','jerusalem'],'jeroboam':['egypt','shechem'],'shishak':['egypt','jerusalem'],'asa':['jerusalem','mareshah'],'zerah-cushite':['mareshah'],'ben-hadad-asa':['damascus'],'ahab':['samaria','ramoth-gilead'],'jehoshaphat':['jerusalem','ramoth-gilead'],'micaiah':['samaria'],'jahaziel':['jerusalem'],'huldah':['jerusalem'],'josiah':['jerusalem','megiddo'],'necho':['egypt','carchemish'],'sennacherib':['lachish','assyria'],'hezekiah':['jerusalem'],'manasseh-king':['jerusalem','babylon'],'oded-samaria':['samaria'],'captive-care-leaders':['samaria','jericho'],'nebuchadnezzar':['babylon'],'cyrus':['babylon']}
for p in people:p['placeIds']=locations.get(p['id'],[])
places_prior={}
for slug in ['genesis','exodus','joshua','1-samuel','2-samuel','1-kings','2-kings','1-chronicles']:
 for p in json.loads((OUT/f'{slug}.json').read_text(encoding='utf8'))['places']:places_prior[p['id']]=p
extra=[('carchemish','Carchemish',36.829,38.015,'Euphrates town named as Neco’s campaign destination.'),('mareshah','Mareshah',31.603,34.899,'Town near the narrated battle with Zerah.'),('tekoa','Tekoa',31.635,35.214,'Town region named in defense and assembly movements.'),('kidron','Kidron valley',31.776,35.238,'Valley east of Jerusalem receiving removed worship objects.'),('libnah','Libnah · site uncertain',31.655,34.912,'Town named in revolt. Identification remains disputed.'),('joppa','Joppa',32.054,34.751,'Mediterranean port receiving timber rafts.'),('sheba','Sheba · broad southern Arabian reference',15.4,45.3,'Broad reference for the queen’s kingdom, not her verified capital.')]
for i,n,lat,lng,m in extra:places_prior[i]=place(i,n,lat,lng,m,'Broad reference marker. Ancient boundaries and exact narrative movements are not established.',['web','atlas-canaan'])
needed_places=list(dict.fromkeys(pid for row in rows for pid in row[4].split(',')))
places=[dict(places_prior[pid]) for pid in needed_places]
for p in places:
 p.pop('verseScope',None)
 if p['id']=='dan':p['verseScope']={'2':[]}
old=json.loads((OUT/'1-chronicles.json').read_text(encoding='utf8'))
sources=[source('web','2 Chronicles · World English Bible','https://ebible.org/engwebp/2CH01.htm','Public-domain reading text for all 36 chapters.','Scripture',limits='Narration does not independently verify quantities, dates, appearances, or private motives.')]
sources.append(dict(next(s for s in json.loads((OUT/'exodus.json').read_text(encoding='utf8'))['sources'] if s['id']=='atlas-exodus')))
for s in old['sources']:
 if s['id'] in ['terrain','atlas','atlas-canaan','tuell-chronicles','japhet-record','mcclellan-chronicles','cfm-chronicles-context']:
  s=dict(s)
  if s['id']=='tuell-chronicles':s['chapterCoverage']=list(range(1,37))
  if s['id']=='mcclellan-chronicles':s['chapterCoverage']=[2,5,13,23,26,29,31,35]
  if s['id']=='cfm-chronicles-context':s['chapterCoverage']=[1,8,9,32,33,35,36]
  sources.append(s)
for s in json.loads((OUT/'2-kings.json').read_text(encoding='utf8'))['sources']:
 if s['id'] in ['millard-hezekiah','taylor-prism']:
  s=dict(s);s['chapterCoverage']=[32];sources.append(s)
def reviewed(i,title,url,summary,author,year,coverage,scope,limits,category='Scholarly study',perspective='historical'):
 s=source(i,title,url,summary,category,perspective,limits);s.update(author=author,year=year,chapterCoverage=coverage,reviewed='2026-10-05: '+scope);sources.append(s)
reviewed('luther-2-chronicles','Summary of 2 Chronicles · Luther Seminary','https://enterthebible.org/courses/2-chronicles/lessons/summary-of-2-chronicles/','The overview studies temple worship, royal evaluation, exile, and restoration.','Mark Throntveit · revised Nicholas Schaser',2024,[1,9,10,29,33,36],'Complete main summary, authorship, date, purpose, and reading sections reviewed.','A scholarly teaching overview. Authorship, date, and literary interpretation are not independent verification of each event.')
reviewed('schaser-2-chronicles','Divine images, music, and literary parallels · Luther Seminary','https://enterthebible.org/courses/2-chronicles/lessons/bible-in-the-world-2-chronicles/','Schaser compares divine language, musical prophecy, temple preparation, Asa’s reforms, and trust.','Nicholas Schaser · Luther Seminary',2024,[2,5,8,13,15,20,23,24,25,28,29,32,34,35,36],'Sections 4–11 and 13 reviewed. Sections 14–15 were unavailable during follow-up and are not used.','Named scholarly interpretations, not unanimous conclusions. Connections to later Christian texts are interpretive comparisons.')
wiki=dict(next(s for s in old['sources'] if s['id']=='wiki-1-chronicles'));wiki.update(id='wiki-2-chronicles',chapterCoverage=[1,9,10,36]);sources.append(wiki)
base='https://www.churchofjesuschrist.org/study/manual/'
reviewed('cfm-2026-30','Come, Follow Me 2026 · 2 Chronicles 14–20; 26; 30',base+'come-follow-me-for-home-and-church-old-testament-2026/30?lang=eng','The lesson studies trust, truthful speech, humility, prayer, and welcoming Passover guests.','The Church of Jesus Christ of Latter-day Saints',2026,[14,15,16,18,20,26,30],'Complete main lesson, home and Church sections, and children’s teaching sections reviewed. Linked supplementary videos and talks were not reviewed.','Faith teaching and application. The lesson does not independently verify ancient battles or disease diagnoses.','Come, Follow Me','lds')
reviewed('lds-2-chronicles','2 Chronicles 1–36 · Seminary teacher manual',base+'old-testament-seminary-teacher-resource-manual/the-second-book-of-the-chronicles/2-chronicles-1-36?lang=eng','The teaching sections connect temple worship, correction, humility, scripture, and covenants.','The Church of Jesus Christ of Latter-day Saints',2003,[3,5,7,15,19,30,32,33,34,36],'Complete main article, Gospel Principles, and teaching sections reviewed.','LDS teaching, not an archaeological reconstruction. Named place associations do not establish every construction detail.','LDS study manual','lds')
notes={2:'Schaser compares differing ways the book describes gods and images.',15:'Schaser compares Asa’s disposal of the image with Moses’s golden-calf account.',20:'Schaser reads the call to believe as trust in God and prophetic leadership.',24:'Schaser discusses the language of being clothed with God’s spirit.',26:'McClellan’s discussion offers priesthood context, not proof of this episode’s complete history.',33:'Compare the restoration account with Kings, which gives a different presentation.',36:'Schaser compares royal captivity language with Matthew’s passion narrative.'}
lds_notes={3:'The Seminary manual connects Moriah with sacred space and temple worship.',5:'The Seminary manual compares dedication experiences with later LDS temple worship.',7:'The Seminary manual studies the dedication as an account of divine acceptance.',14:'Come, Follow Me invites study of Asa’s trust during danger.',15:'Come, Follow Me studies perseverance and trust through Asa’s reforms.',16:'Come, Follow Me compares where Asa places his trust at different times.',18:'Come, Follow Me studies Micaiah’s truthful speech under pressure.',19:'The Seminary manual connects correction with faithful service.',20:'Come, Follow Me studies prayer, trust, and prophetic encouragement.',26:'Come, Follow Me studies humility and the limits on Uzziah’s incense offering.',30:'Come, Follow Me studies welcome, pardon, and peacemaking at Passover.',32:'The Seminary manual highlights Hezekiah’s humility.',33:'The Seminary manual highlights Manasseh’s prayer and humility.',34:'The Seminary manual connects scripture hearing with renewed covenants.',36:'The Seminary manual reads captivity alongside God’s continuing care.'}
chapters=[]
for n,(title,summary,meaning,pids,locs) in enumerate(rows,1):
 hs=[s['id'] for s in sources if s['perspective']=='historical' and n in s.get('chapterCoverage',[])]
 ls=[s['id'] for s in sources if s['perspective']=='lds' and n in s.get('chapterCoverage',[])]
 chapters.append(dict(chapter=n,title=title,summary=summary,meaning=meaning,people=pids.split(','),places=locs.split(','),sourceIds=['web','atlas-canaan']+hs,lds=dict(text=lds_notes.get(n,'Original study reflection: consider leadership, responsibility, and care for the worship community.'),sourceIds=ls),eventOrder=n,dateLabel='Chapter order · reign and composition dates require comparison',historicalNote=notes.get(n,'Compare parallel accounts and distinguish narrated evaluation from independently verified evidence.'),mapNote='Selected named towns and broad reference regions. Markers do not establish exact ancient roads or political boundaries.',route=[],routeEvidence='No reconstructed route is assigned.'))
finish(dict(id='2-chronicles',bibleCode='2CH',name='2 Chronicles',description='Solomon’s temple · Judah’s kings · reform · exile · return',chapterCount=36,scripture=scripture('2-chronicles','2CH',36),chapters=chapters,people=people,places=places,sources=sources,review=dict(date='2026-10-05',scope='All scripture and original chapter studies reviewed. Profiles cover selected people, not every service-list name. Source records distinguish actual review from inaccessible full works.',nextBook='ezra')))

