"""Second Samuel: reviewed chapters, distinct people, and Isaiah's shared reader."""
import json
from book_common import ROOT,OUT,source,person,place,scripture,finish
rows=[
('David laments Saul and Jonathan','An Amalekite brings Saul’s royal objects and claims to have killed him. David orders his death, then laments Saul and Jonathan.','The messenger’s claim differs from 1 Samuel 31. The guide preserves that difference instead of treating both accounts as identical.','david,saul,jonathan-saul,amalekite-messenger','ziklag,gilboa','The older manual treats the messenger’s claim as deception. This remains its interpretation of the differing accounts.'),
('Two kingdoms and the battle at Gibeon','Judah anoints David at Hebron. Abner installs Ishbosheth at Mahanaim. Fighting at Gibeon leads to Asahel’s death.','A contest expands into broader killing. The division and pursuit reveal the human costs of succession.','david,abner,ishbosheth,joab,asahel,abishai,abigail,ahinoam-david','hebron,mahanaim,gibeon,bethlehem,jabesh-gilead','Original study reflection: examine how competition becomes violence and what stopping it requires.'),
('Abner changes allegiance and Joab kills him','After conflict with Ishbosheth over Rizpah, Abner negotiates with David. Michal is returned. Joab kills Abner, and David mourns.','Women’s household positions enter negotiations over power. David publicly rejects responsibility for Abner’s killing.','david,abner,ishbosheth,rizpah,joab,asahel,abishai,michal,palti,abigail,ahinoam-david,amnon,absalom','hebron,bahurim','Original study reflection: consider people’s interests when leaders negotiate control over their households.'),
('Ishbosheth is murdered','Rechab and Baanah kill Ishbosheth and bring his head to David. David condemns them and orders their execution.','The account also recalls Jonathan’s injured son Mephibosheth. Physical disability does not remove his later place in the story.','david,ishbosheth,rechab,baanah,mephibosheth-jonathan,jonathan-saul,saul','hebron,mahanaim','Original study reflection: distinguish public justice from seeking a reward through another person’s death.'),
('David becomes king of Israel and takes Jerusalem','The tribes anoint David at Hebron. He captures Jerusalem, receives help from Hiram, and fights the Philistines.','Jerusalem becomes the political center. The capture account contains difficult language about a watercourse and disability. No exact entry route is established here.','david,hiram,solomon','hebron,jerusalem,tyre,rephaim,gezer','Come, Follow Me studies seeking divine guidance.'),
('The ark reaches Jerusalem','Uzzah dies during the ark’s transport. The ark stays with Obed Edom before David brings it to Jerusalem. Michal challenges David’s public conduct.','Celebration, fear, sacred danger, and household conflict occur together. The narrative does not explain every person’s motives.','david,uzzah,ahio,obed-edom,michal,abinadab-ark','kiriath-jearim,jerusalem','The older manual connects the ark’s handling with sacred responsibility. Its proposed motives are interpretations.'),
('Nathan announces a promised house','David proposes a house for God. Nathan announces that God will establish David’s house and that his offspring will build a house.','House means both a building and a continuing royal family. Scholarly discussion distinguishes the dynastic promise from later messianic interpretation.','david,nathan-prophet','jerusalem','Come, Follow Me connects the promised house with Jesus Christ.'),
('Wars, tribute, and royal officials','The chapter collects David’s campaigns, tribute, dedicated wealth, and court officials. Joab, Zadok, and Benaiah hold named offices.','The victories include killing captives and taking wealth. Royal success does not make every action a moral example.','david,joab,hadadezer,toi,joram-hamath,zadok,benaiah','jerusalem,moab,aram,hamath,edom','Original study reflection: include defeated people when assessing descriptions of a powerful kingdom.'),
('Mephibosheth receives land and a place at the table','David seeks a surviving member of Saul’s household for Jonathan’s sake. Ziba identifies Mephibosheth, whom David brings from Machir’s house.','A former rival’s descendant receives provision. His disability remains part of his description, not evidence of lesser worth.','david,mephibosheth-jonathan,jonathan-saul,saul,ziba,machir','jerusalem,lodebar','The older manual studies David’s kindness to Jonathan’s son.'),
('Humiliated envoys and war with Ammon','Hanun humiliates David’s messengers. Ammon hires allies. Joab and Abishai divide their forces, and the conflict expands.','Suspicion turns an intended condolence into public humiliation and war. The guide does not reconstruct all battle positions.','david,hanun,nahash,joab,abishai,hadadezer','rabbah,jericho,aram','Original study reflection: assess information before assuming hostile intent.'),
('David takes Bathsheba and arranges Uriah’s death','David sends for Bathsheba while Uriah serves at Rabbah. After she reports pregnancy, David arranges Uriah’s death through Joab.','The king controls access, orders, and the cover-up. The account condemns David. It does not report Bathsheba’s consent or make her responsible for his commands.','david,bathsheba,uriah,joab,abimelech,thembez-woman','jerusalem,rabbah,thebez','Come, Follow Me studies resisting temptation and David’s harmful choices. This application does not transfer responsibility to Bathsheba.'),
('Nathan confronts David and the child dies','Nathan uses a story to confront David. David confesses. The unnamed infant dies, Solomon is later born, and Rabbah is taken.','The child’s death raises a difficult question about suffering after another person’s wrongdoing. The guide does not make a sick child morally responsible.','david,nathan-prophet,bathsheba,uriah,unnamed-infant,solomon,joab','jerusalem,rabbah','The older manual cites a Joseph Smith Translation reading that differs from the reading text at 12:13.'),
('Amnon assaults Tamar and Absalom takes revenge','Jonadab advises Amnon’s deception. Amnon rapes Tamar and expels her. Absalom later orders Amnon’s killing and flees.','Tamar clearly protests and publicly expresses grief. Responsibility belongs to the attacker. Revenge does not restore her safety or tell readers her later life.','david,amnon,tamar-david,jonadab,absalom','jerusalem,baal-hazor,geshur','Original study reflection: hear Tamar’s words and consider the failure to protect her.'),
('The woman of Tekoa and Absalom’s return','Joab sends a wise woman to persuade David through a constructed legal appeal. Absalom returns, then later regains access to David.','A persuasive story can expose inconsistent judgment but also serve a political plan. Returning to the city does not immediately restore the relationship.','david,joab,tekoa-woman,absalom','jerusalem,tekoa','Original study reflection: test a persuasive argument without ignoring the person who arranged it.'),
('Absalom gathers support and David leaves Jerusalem','Absalom promises better justice and begins a revolt from Hebron. David leaves Jerusalem. Ittai stays with him, while Hushai returns as his agent.','Claims about justice gain political force. The flight also depends on foreigners, priests, messengers, and household members.','david,absalom,ittai,hushai,ahithophel,zadok,abiathar,ahimaaz,jonathan-abiathar','jerusalem,hebron,kidron,olives','Original study reflection: compare promises of justice with the methods used to gain power.'),
('Ziba’s accusation, Shimei’s curses, and Absalom’s public act','Ziba accuses Mephibosheth. Shimei curses David. Hushai approaches Absalom, who follows Ahithophel’s advice concerning David’s concubines.','The reader later hears Mephibosheth’s conflicting account. The concubines become targets in a public struggle over kingship.','david,ziba,mephibosheth-jonathan,shimei-gera,abishai,absalom,hushai,ahithophel,royal-concubines','olives,bahurim,jerusalem','Original study reflection: do not treat an accusation as proof before hearing the affected person.'),
('Hushai’s counsel and the messengers’ escape','Absalom rejects Ahithophel’s immediate attack plan for Hushai’s advice. Two women help messages reach David. Allies bring supplies at Mahanaim.','The escape depends on people outside the royal council. Food, shelter, and risk matter alongside strategy. Ahithophel’s death remains a tragic part of the account.','david,absalom,hushai,ahithophel,zadok,abiathar,ahimaaz,jonathan-abiathar,en-rogel-servant,bahurim-woman,amasa,abigail-sister,shobi,machir,barzillai','jerusalem,en-rogel,bahurim,jordan,mahanaim,rogellim,rabbah','Original study reflection: identify the care and practical help that make survival possible.'),
('Absalom dies and David grieves','David orders his commanders to deal gently with Absalom. Joab kills Absalom, and a Cushite messenger reports the outcome. David mourns his son.','Victory for the king and devastating personal loss occur together. The text says Absalom’s head catches in the tree, not specifically his hair.','david,absalom,joab,abishai,ittai,ahimaaz,cushite-messenger','mahanaim,gilead','Original study reflection: allow grief without reducing a family member to political allegiance.'),
('David returns and hears competing claims','Joab confronts David’s withdrawal. David returns, spares Shimei, hears Mephibosheth, and offers care to Barzillai, who sends Chimham instead.','Mephibosheth disputes Ziba’s account. David divides the land without the narrative resolving every factual question. Tribal rivalry remains.','david,joab,amasa,zadok,abiathar,shimei-gera,abishai,ziba,mephibosheth-jonathan,barzillai,chimham','mahanaim,jordan,gilgal,jerusalem,rogellim','Original study reflection: distinguish restored authority from fully repaired relationships.'),
('Sheba’s revolt and the wise woman of Abel','Sheba leads another revolt. Joab kills Amasa. A wise woman negotiates during the siege of Abel, and the townspeople kill Sheba.','The woman challenges the destruction of a whole town. Her intervention saves the city, while its resolution still includes a violent death.','david,sheba-bichri,amasa,joab,abishai,abel-woman,benaiah,zadok,abiathar,royal-concubines','jerusalem,gibeon,abel','The older manual states that David’s concubines were not responsible for Absalom’s violation.'),
('Rizpah guards the dead and warriors defend David','David hands seven descendants of Saul to the Gibeonites. Rizpah guards their exposed bodies. Later scenes recall battles with Philistine warriors.','Two Mephibosheths are distinct here. The executed sons must remain visible. The Hebrew Goliath reading differs from this translation’s harmonized wording.','david,saul,jonathan-saul,mephibosheth-jonathan,mephibosheth-saul,armoni,rizpah,merab,adriel,abishai,sibbecai,elhanan-jaare,jonathan-shimei,goliath','gibeah,jabesh-gilead,beth-shan,gilboa,zela,gath','The older manual questions the executions under the law against punishing children for parents’ sins.'),
('David’s song of deliverance','David praises God through images of rescue, storm, battle, and protection. The song closely parallels Psalm 18.','Poetry expresses remembered deliverance and claimed integrity. Readers should also retain the prose account’s criticism of David’s conduct.','david,saul','jerusalem','Original study reflection: compare a person’s self-description with actions elsewhere in the narrative.'),
('Last words and remembered warriors','David’s final oracle describes righteous rule. The chapter lists warriors and recalls risky service, including the water from Bethlehem.','The account collects memory rather than providing a continuous event sequence. Uriah’s inclusion keeps the victim of David’s command within the list.','david,jesse,josheb-basshebeth,eleazar-dodai,shammah-agee,abishai,joab,benaiah,uriah,asahel','jerusalem,bethlehem,adullam,rephaim,moab','Original study reflection: compare righteous rule in the poem with the king’s responsibilities toward those who serve him.'),
('The census, plague, and Araunah’s threshing floor','David orders a census despite Joab’s objection. Gad announces judgment. David buys Araunah’s threshing floor and offers sacrifice after the plague.','David asks why the people suffer for his wrongdoing. Samuel attributes the incitement to God, while 1 Chronicles 21 attributes it to Satan.','david,joab,gad,araunah','jerusalem,jordan,gilead,dan,sidon,tyre,beersheba','The older manual notes the different account in Chronicles. Its proposed census motive remains an interpretation.')]
defs=[
('amalekite-messenger','The Amalekite messenger','Messenger who claims to have killed Saul','Brings Saul’s crown and bracelet to David.','1','His report differs from 1 Samuel 31. David orders his death.'),
('ishbosheth','Ishbosheth','Saul’s son installed as king by Abner','Rival to David after Saul’s death.','2–4','His dependent position and murder show the danger of disputed succession.'),
('joab','Joab','Commander in David’s service','Son of Zeruiah. Brother of Abishai and Asahel.','2–3; 8; 10–12; 14; 18–20; 23–24','He protects the kingdom but kills Abner, Absalom, and Amasa. Service does not excuse these actions.'),
('asahel','Asahel','Swift warrior killed during pursuit','Brother of Joab and Abishai. Son of Zeruiah.','2–3; 23','Abner kills him after warnings. His death leads to another killing.'),
('rizpah','Rizpah','Mother who guards exposed bodies','Daughter of Aiah. Saul’s concubine. Mother of Armoni and one Mephibosheth.','3; 21','Her extended vigil prompts the report that reaches David and precedes burial.'),
('rechab','Rechab','Officer who murders Ishbosheth','Son of Rimmon. Brother of Baanah.','4','David rejects the expected reward and orders his execution.'),
('baanah','Baanah','Officer who murders Ishbosheth','Son of Rimmon. Brother of Rechab.','4','He participates in killing the sleeping king. He is distinct from other same-name figures.'),
('mephibosheth-jonathan','Mephibosheth, Jonathan’s son','Surviving descendant supported by David','Son of Jonathan and grandson of Saul. Father of Mica.','4; 9; 16; 19; 21:7','He receives provision, disputes Ziba’s accusation, and is spared in chapter 21. He is not Rizpah’s executed son.'),
('mephibosheth-saul','Mephibosheth, Rizpah’s son','Son of Saul handed to the Gibeonites','Son of Saul and Rizpah. Brother of Armoni.','21:8–10','He dies among the seven. He is distinct from Jonathan’s son, who is spared.'),
('armoni','Armoni','Son of Rizpah handed to the Gibeonites','Son of Saul. Brother of Rizpah’s Mephibosheth.','21:8–10','His death forms part of the account’s troubling response to famine.'),
('uzzah','Uzzah','Man who reaches toward the ark','Son of Abinadab. Accompanies Ahio.','6','His death interrupts the procession. The text supplies limited personal background.'),
('ahio','Ahio','Man who walks before the ark','Son of Abinadab. Accompanies Uzzah.','6','He helps guide the cart. The narrative does not give a wider life story.'),
('obed-edom','Obed Edom','Householder who receives the ark','Called a Gittite in this chapter.','6','His household is blessed during the ark’s stay. This profile does not combine every later same-name figure.'),
('nathan-prophet','Nathan','Prophet who addresses the king','Counselor who announces the house promise and confronts David.','7; 12','He changes his initial advice after revelation. He uses a story to expose David’s wrongdoing.'),
('hiram','Hiram','King of Tyre who sends builders','Provides cedar and craftsmen for David’s house.','5','This chapter records royal cooperation without establishing an exact construction date.'),
('hadadezer','Hadadezer','King of Zobah opposed by David','Son of Rehob. Associated with Aramean forces.','8; 10','His defeat belongs to the account’s presentation of David’s expanding rule.'),
('toi','Toi','King of Hamath who sends congratulations','Father of Joram in this account.','8','He sends gifts after David defeats his opponent Hadadezer.'),
('joram-hamath','Joram','Envoy from Hamath','Son of King Toi.','8','He is distinct from later Israelite and Judean kings with the same name.'),
('zadok','Zadok','Priest who supports David during the revolt','Son of Ahitub. Father of Ahimaaz.','8; 15; 17; 19–20','He returns the ark to Jerusalem and helps transmit information.'),
('benaiah','Benaiah','Commander of the royal guard','Son of Jehoiada. From Kabzeel.','8; 20; 23','The chapter recalls his feats. They are narrative claims, not independently verified casualty counts.'),
('ziba','Ziba','Servant managing Saul’s family property','Works under David’s grant to Mephibosheth.','9; 16; 19','His accusation conflicts with Mephibosheth’s later explanation. The guide does not declare the dispute resolved.'),
('machir','Machir','Householder who helps vulnerable people','Son of Ammiel. From Lodebar.','9; 17','He houses Mephibosheth and later brings supplies to David’s company.'),
('hanun','Hanun','Ammonite ruler who humiliates envoys','Son and successor of Nahash.','10','Suspicion leads him to reject David’s condolences and mistreat the messengers.'),
('bathsheba','Bathsheba','Woman taken into David’s household','Daughter of Eliam. Wife of Uriah, later wife of David. Mother of Solomon.','11–12','David sends for her. She reports pregnancy and mourns Uriah. The text does not report her consent.'),
('uriah','Uriah','Soldier whose death David arranges','Called a Hittite. Husband of Bathsheba.','11–12; 23','His loyalty contrasts with the king’s deception. Joab carries out David’s order.'),
('unnamed-infant','Bathsheba’s unnamed infant','Child who dies after Nathan’s judgment','Son of Bathsheba and David. Distinct from Solomon.','12:14–23','The text supplies no name. The guide does not invent personal guilt to explain his death.'),
('solomon','Solomon','Son born after the infant’s death','Son of Bathsheba and David. Nathan also calls him Jedidiah.','5:14; 12:24–25','This book reports his birth and naming. His later reign belongs to Kings.'),
('amnon','Amnon','David’s firstborn son who assaults Tamar','Son of Ahinoam. Half-brother of Tamar and Absalom.','3; 13','He uses deception and force. Tamar’s protests make his responsibility clear.'),
('absalom','Absalom','David’s son who leads a revolt','Son of Maacah. Tamar’s brother. Father of a daughter also named Tamar.','3; 13–19','He avenges Tamar, returns from exile, gathers support, and dies during the revolt.'),
('tamar-david','Tamar','Woman who protests Amnon’s assault','Daughter of David. Sister of Absalom and half-sister of Amnon.','13','She speaks, resists, and cries out. The account does not report her later recovery.'),
('jonadab','Jonadab','Adviser who proposes Amnon’s deception','Son of Shimeah, David’s brother.','13','He advises the scheme and later interprets the news of Amnon’s death.'),
('tekoa-woman','The wise woman of Tekoa','Unnamed speaker who appeals to David','Joab instructs her constructed household story.','14','She challenges the king’s judgment while participating in Joab’s plan.'),
('ittai','Ittai','Gittite commander who chooses to stay','A foreigner and recent arrival with David.','15; 18','He pledges loyalty despite the offered opportunity to leave. This profile does not merge every same-name warrior.'),
('hushai','Hushai','David’s friend and agent in Jerusalem','Called an Archite. Opposes Ahithophel’s counsel.','15–17','His strategic advice buys time. Priests and messengers make it useful.'),
('ahithophel','Ahithophel','Counselor who supports Absalom','From Giloh. Opposed by Hushai.','15–17','His advice is highly regarded. He dies by suicide after it is rejected. No modern diagnosis is established.'),
('shimei-gera','Shimei','Benjaminite who curses David','Son of Gera. From Bahurim.','16; 19','David restrains retaliation during flight and grants him an oath on return.'),
('ahimaaz','Ahimaaz','Priest’s son and messenger','Son of Zadok. Works with Jonathan son of Abiathar.','15; 17–18','He escapes detection and later runs to David with news.'),
('jonathan-abiathar','Jonathan, Abiathar’s son','Messenger during Absalom’s revolt','Son of Abiathar. Companion of Ahimaaz.','15; 17','He is distinct from Saul’s son and David’s nephew.'),
('en-rogel-servant','The servant woman at En Rogel','Unnamed messenger in the information network','Reports to Jonathan and Ahimaaz.','17:17','Her work carries information beyond the council room. No name is supplied.'),
('bahurim-woman','The woman at Bahurim','Unnamed woman who protects the messengers','Conceals the courtyard well and misdirects pursuers.','17:18–20','Her practical action helps David’s company escape. She is distinct from the servant at En Rogel.'),
('amasa','Amasa','Commander appointed by Absalom and then David','Son of Ithra and Abigail, sister of Zeruiah.','17; 19–20','David offers him Joab’s command. Joab later kills him.'),
('abigail-sister','Abigail, David’s sister','Mother of Amasa','Sister of Zeruiah. The chapter calls her a daughter of Nahash.','17:25','She is distinct from David’s wife Abigail. The guide does not invent a solution to the family wording.'),
('shobi','Shobi','Ammonite supplier during David’s flight','Son of Nahash, from Rabbah.','17:27–29','He brings supplies with Machir and Barzillai. His aid contrasts with earlier hostility involving Ammon.'),
('barzillai','Barzillai','Older Gileadite who supplies David’s company','From Rogelim. Sends Chimham with David.','17; 19','He declines court support and chooses to return home. He is distinct from Adriel’s Meholathite father.'),
('cushite-messenger','The Cushite messenger','Unnamed runner who reports Absalom’s death','Sent by Joab after the battle.','18:21–32','Cushite is a regional designation, not his personal name. He gives news David finds devastating.'),
('chimham','Chimham','Companion sent with the returning king','Commended to David by Barzillai.','19','The chapter promises care without describing his later life.'),
('sheba-bichri','Sheba','Leader of a revolt after David’s return','Son of Bichri. A Benjaminite.','20','He takes refuge at Abel and dies during the negotiated end of the siege.'),
('abel-woman','The wise woman of Abel','Unnamed negotiator who challenges Joab','Speaks for the threatened city of Abel Beth Maacah.','20:16–22','She argues against destroying the town and negotiates a resolution that includes Sheba’s death.'),
('royal-concubines','David’s ten concubines','Women targeted during the struggle for kingship','Left in Jerusalem when David flees.','15:16; 16:21–22; 20:3','Absalom publicly violates them. David later confines and provides for them. The text gives no names or account of their consent.'),
('sibbecai','Sibbecai','Warrior in a recalled Philistine battle','Called a Hushathite.','21:18','He kills Saph in the account. The guide does not invent his wider biography.'),
('elhanan-jaare','Elhanan','Warrior associated with the disputed Goliath reading','Son of Jaare-Oregim, a Bethlehemite.','21:19','The Hebrew text names Goliath as his victim. This reading text adds brother, following a harmonizing interpretation.'),
('jonathan-shimei','Jonathan, David’s nephew','Warrior who defeats a large Philistine','Son of Shimei, David’s brother.','21:21','He is distinct from Jonathan son of Saul and Jonathan son of Abiathar.'),
('josheb-basshebeth','Josheb Basshebeth','Warrior at the head of the list','Called a Tahchemonite and Adino the Eznite in the reading text.','23:8','The account gives a heroic casualty claim. Its names and numbers require textual caution.'),
('eleazar-dodai','Eleazar','Warrior who stands with David','Son of Dodai, associated with an Ahohite.','23:9–10','He is distinct from the ark keeper and Aaron’s son.'),
('shammah-agee','Shammah','Warrior who defends a lentil field','Son of Agee, a Hararite.','23:11–12','He is distinct from David’s brother. The chapter recalls his refusal to abandon the field.'),
('araunah','Araunah','Jebusite owner of the threshing floor','Offers the site, cattle, and wood to David.','24:16–25','David insists on paying. The map marks Jerusalem, not a verified private property boundary.')]
people=[person(i,n,r,rel,'2 Samuel '+refs,m) for i,n,r,rel,refs,m in defs]
reused={'david':'1–24','saul':'1–4; 6–7; 9; 16; 19; 21–22','jonathan-saul':'1; 4; 9; 21:7,12–14','abner':'2–4','abigail':'2–3','ahinoam-david':'2–3','michal':'3; 6','palti':'3','abinadab-ark':'6','abishai':'2–3; 10; 16; 18–21; 23','abiathar':'15; 17; 19–20','gad':'24','goliath':'21:19','jesse':'23:1','nahash':'10','merab':'21:8','adriel':'21:8'}
old=json.loads((OUT/'1-samuel.json').read_text(encoding='utf-8'))
for p in old['people']:
 if p['id'] in reused:
  q=dict(p,passages='2 Samuel '+reused[p['id']],placeIds=[],linkNames=[]);people.append(q)
for p in people:
 if p['id']=='david':p.update(role='King whose rule includes achievement and destructive wrongdoing',relations='Son of Jesse. Father of Amnon, Absalom, Tamar, Solomon, and other children.',meaning='He establishes Jerusalem, supports Jonathan’s son, and receives a dynastic promise. He also arranges Uriah’s death and fails amid family violence.')
 if p['id']=='abner':p.update(meaning='He establishes Ishbosheth’s rule, then negotiates with David. Joab kills him after Asahel’s death.')
 if p['id']=='michal':p.update(meaning='She is returned to David during negotiations and later challenges his public conduct. Her interests are not fully reported.')
 if p['id']=='abigail':p.update(meaning='David’s wife accompanies his move to Hebron. She is distinct from Amasa’s mother.')
 if p['id']=='abishai':p.update(meaning='He commands forces, proposes retaliation against Shimei, and rescues David during battle.')
 if p['id']=='gad':p.update(meaning='He announces the choices after the census and instructs David to build an altar.')
 if p['id']=='palti':p.update(meaning='Also called Paltiel. He follows Michal weeping until Abner sends him home.',linkNames=['Paltiel'])
aliases={'mephibosheth-jonathan':['Mephibosheth'],'mephibosheth-saul':['Mephibosheth'],'jonathan-abiathar':['Jonathan'],'jonathan-shimei':['Jonathan'],'abigail-sister':['Abigail'],'obed-edom':['Obed-Edom'],'cushite-messenger':['Cushite'],'tekoa-woman':['woman'],'abel-woman':['woman'],'bahurim-woman':['woman'],'en-rogel-servant':['female servant'],'royal-concubines':['concubines'],'solomon':['Jedidiah']}
for p in people:p['linkNames']=aliases.get(p['id'],p.get('linkNames',[]))
scopes={'mephibosheth-jonathan':{'21':[7]},'mephibosheth-saul':{'21':[8]},'jonathan-saul':{'21':[7,12,13,14]},'jonathan-shimei':{'21':[21]},'abigail':{'17':[]},'abigail-sister':{'17':[25]},'en-rogel-servant':{'17':[17]},'bahurim-woman':{'17':[19,20]},'nathan-prophet':{'5':[]},'goliath':{'21':[19]},'shammah-agee':{'23':[11,12]},'benaiah':{'23':[20,21,22,23]},'gad':{'24':[11,13,14,18,19]}}
scopes.update({'tekoa-woman':{'14':list(range(2,21))},'abel-woman':{'20':[16,17,18,19,21,22]}})
for p in people:
 if p['id'] in scopes:p['verseScope']=scopes[p['id']]
coords=[('jerusalem','Jerusalem',31.778,35.235),('hebron','Hebron',31.533,35.10),('mahanaim','Mahanaim · proposed locality',32.19,35.71),('gibeon','Gibeon',31.85,35.18),('bahurim','Bahurim · uncertain locality',31.815,35.265),('tyre','Tyre',33.27,35.20),('rephaim','Valley of Rephaim · broad setting',31.755,35.20),('gezer','Gezer',31.86,34.92),('aram','Aram · broad region',33.55,36.30),('hamath','Hamath',35.13,36.75),('edom','Edom · broad region',30.75,35.55),('lodebar','Lodebar · uncertain locality',32.58,35.74),('rabbah','Rabbah · Amman',31.951,35.94),('jericho','Jericho',31.87,35.45),('thebez','Thebez · proposed locality',32.32,35.37),('baal-hazor','Baal Hazor · proposed locality',31.979,35.28),('geshur','Geshur · broad region',32.9,35.65),('tekoa','Tekoa',31.638,35.214),('kidron','Kidron · Jerusalem valley',31.774,35.24),('olives','Mount of Olives',31.779,35.247),('en-rogel','En Rogel · proposed spring locality',31.766,35.234),('jordan','Jordan · crossing area uncertain',31.90,35.55),('rogellim','Rogelim · locality uncertain',32.35,35.80),('gilead','Gilead · broad region',32.20,35.80),('gilgal','Gilgal · uncertain locality',31.855,35.49),('abel','Abel Beth Maacah · proposed locality',33.268,35.575),('zela','Zela · uncertain Benjamin locality',31.85,35.20),('dan','Dan · broad northern locality',33.249,35.653),('sidon','Sidon',33.56,35.37)]
needed=['ziklag','gilboa','bethlehem','jabesh-gilead','kiriath-jearim','moab','gibeah','beth-shan','adullam','beersheba','gath']
places=[dict(p) for p in old['places'] if p['id'] in needed]+[place(i,n,lat,lng,'Named locality or broad region in the narrative.','Reference marker only. Exact houses, camps, battle lines, property boundaries, and ancient roads remain uncertain.',['web','atlas-canaan']) for i,n,lat,lng in coords]
sources=[source('web','2 Samuel · World English Bible','https://ebible.org/engwebp/2SA01.htm','Public-domain reading text for all 24 chapters.','Scripture',limits='Narrative and poetic claims do not independently verify event dates, appearance, numbers, or every historical action.')]+[dict(s) for s in old['sources'] if s['id'] in ['terrain','atlas','atlas-canaan']]
next(s for s in sources if s['id']=='atlas-canaan')['limitations']='Coordinates are display estimates. A town marker does not verify each narrated event.'
def reviewed(i,title,url,summary,author,year,coverage,scope,limits,category='Scholarly study',perspective='historical',group=None):
 s=source(i,title,url,summary,category,perspective,limits);s.update(author=author,year=year,chapterCoverage=coverage,reviewed='2026-10-05: '+scope)
 if group:s['group']=group
 sources.append(s)
reviewed('yale-david','David and Solomon · Open Yale Courses, Lecture 14','https://oyc.yale.edu/religious-studies/rlst-145/lecture-14','Hayes studies royal ideology alongside the narrative’s frank criticism of David.','Christine Hayes · Yale University',2006,[5,6,7,11,12,15,18,19],'Published transcript 00:00–10:29 reviewed.','Audio and video were not checked. Literary interpretation does not verify every narrated event.')
reviewed('yale-kingship','David and the Kingship · Yale Bible Study','https://yalebiblestudy.org/wp-content/uploads/2019/09/Samuel-David-and-the-Kingship-Study-Guide.pdf','The guide studies Jerusalem, the ark, the two meanings of house, and later messianic readings.','Yale Divinity School · course presented by Joel S. Baden and John J. Collins','Linked course PDF',[5,6,7],'Four-page study guide reviewed; course presenter identities verified.','Its water-shaft reconstruction and assessment of Michal are interpretations. Proposed composition layers and dates remain debated.')
reviewed('yale-bathsheba','Bathsheba · Yale Bible Study','https://yalebiblestudy.org/courses/the-books-of-samuel/lessons/bathsheba-study-guide/','The guide examines David’s power, Uriah’s contrasting conduct, Nathan’s story, and the child’s death.','Yale Divinity School · Samuel course','Linked course',[11,12],'Main study-guide text reviewed.','The opening puts Bathsheba on a roof, but the biblical text places David there. Her bathing location and consent are not supplied. Proposed literary layers remain interpretations.')
reviewed('mccarter-ii','II Samuel · Anchor Yale Bible Commentary','https://yalebooks.yale.edu/book/9780300139518/ii-samuel/','The publisher describes McCarter’s work on textual transmission, composition, and historical reconstruction.','P. Kyle McCarter · Yale University Press',1984,[],'Publisher edition record and description reviewed.','The full commentary was not read. This record verifies publication identity and scope, not its arguments.')
reviewed('wiki-2-samuel','Books of Samuel · Wikipedia','https://en.wikipedia.org/wiki/Books_of_Samuel','The opening overview locates Samuel among the Bible’s narratives of leadership and kingship.','Wikipedia contributors','Reviewed revision',[1,5,7,24],'Opening four paragraphs reviewed at revision 1378224492.','Use for background and source discovery. Composition dates and historical claims require separate scholarly review.','Encyclopedia background')
sources[-1].update(revisionId='1378224492',revisionUrl='https://en.wikipedia.org/w/index.php?oldid=1378224492',license='CC BY-SA 4.0',licenseUrl='https://creativecommons.org/licenses/by-sa/4.0/',citedSourceIds=['mccarter-ii'])
reviewed('dm-2-samuel-5','1 Chronicles 14 · comparison with 2 Samuel 5','https://danielomcclellan.wordpress.com/2010/05/11/1-chronicles-14/','McClellan compares wording and textual witnesses in the parallel battle accounts.','Dan McClellan','May 11, 2010',[5],'Original translation post and relevant footnotes reviewed.','This older textual argument does not independently verify a battle or establish scholarly consensus.','Scholar commentary',group='mcclellan')
reviewed('dm-2-samuel-15','Psalm 82 · Absalom and claims about justice','https://danielomcclellan.wordpress.com/2009/12/02/psalm-82-2/','McClellan discusses a proposed literary parallel involving Absalom’s criticism of his father’s justice.','Dan McClellan','December 2, 2009',[15],'Original post’s paragraph on 2 Samuel 15 reviewed.','The proposed parallel does not establish direct borrowing or independently verify events. Broader claims about consensus are not adopted.','Scholar commentary',group='mcclellan')
reviewed('net-2-samuel-21','2 Samuel 21 · NET Bible textual notes','https://bible.org/sites/bible.org/resources/netbible/2sa21_notes.htm','The notes identify Michal/Merab variation and the differing Goliath readings in Samuel and Chronicles.','NET Bible translation team','Linked published notes',[21],'Notes 10 and 33–34 reviewed.','Manuscripts were not inspected. The proposed reconstruction is an interpretation, not an undisputed original reading.')
inst='https://www.churchofjesuschrist.org/study/manual/old-testament-student-manual-genesis-2-samuel/'
reviewed('lds-2-samuel-early','2 Samuel 1–12 · Institute commentary',inst+'2-samuel-1-12-the-fall-of-king-david?lang=eng','The manual studies succession, the ark, the promised house, and David’s wrongdoing.','The Church of Jesus Christ of Latter-day Saints',1980,list(range(1,13)),'Sections 26-2–26-23 reviewed.','Church teaching and older historical proposals remain separate from archaeological verification. Claims about private motives are interpretations.','LDS study manual','lds')
reviewed('lds-2-samuel-late','2 Samuel 13–24 · Institute commentary',inst+'2-samuel-13-24-the-price-of-sin-tragedy-in-the-house-of-david?lang=eng','The manual studies family violence, revolt, Rizpah, remembered warriors, and the census.','The Church of Jesus Christ of Latter-day Saints',1980,list(range(13,25)),'Sections 27-2–27-27 reviewed.','Theological explanations and historical reconstructions remain interpretations. They do not establish exact dates or every participant’s motives.','LDS study manual','lds')
routes={2:['hebron','gibeon'],3:['bahurim','hebron'],5:['hebron','jerusalem'],6:['kiriath-jearim','jerusalem'],13:['jerusalem','baal-hazor','geshur'],15:['jerusalem','kidron','olives'],17:['en-rogel','bahurim','jordan','mahanaim'],19:['mahanaim','jordan','gilgal','jerusalem'],20:['jerusalem','gibeon','abel'],21:['jabesh-gilead','zela']}
chapters=[]
for n,(title,summary,meaning,pids,locs,lds) in enumerate(rows,1):
 ids=['web','atlas-canaan']+[s['id'] for s in sources if s['perspective']=='historical' and n in s.get('chapterCoverage',[])]
 refs=[] if lds.startswith('Original study') else ['lds-2-samuel-early' if n<=12 else 'lds-2-samuel-late']
 chapters.append(dict(chapter=n,title=title,summary=summary,meaning=meaning,people=pids.split(','),places=locs.split(','),sourceIds=ids,lds=dict(text=lds,sourceIds=refs),eventOrder=n,dateLabel='Chapter order · historical year uncertain',historicalNote='Literary order is not an independently established chronology.',mapNote='Named localities and broad settings only. Exact houses, battle positions, and travel paths remain uncertain.',route=routes.get(n,[]),routeEvidence='Connects named places in narrative order. This is not a reconstructed road, exact crossing, or complete journey.'))
# Add two explicitly recalled Judges figures without merging their scenes with current events.
judges=json.loads((OUT/'judges.json').read_text(encoding='utf-8'))
for original in judges['people']:
 if original['id']=='abimelech-judges':
  people.append(dict(original,id='abimelech',passages='2 Samuel 11:21',placeIds=['thebez'],sourceIds=['web']))
# Their existing IDs are checked below; the unnamed woman receives her existing portrait.
if not any(p['id']=='thembez-woman' for p in people):
 people.append(dict(person('thembez-woman','The woman at Thebez','Unnamed defender recalled in Joab’s message','Drops a millstone on Abimelech in Judges 9.','2 Samuel 11:21','Joab recalls her action as a warning about approaching a defended wall.'),placeIds=['thebez'],linkNames=['woman'],verseScope={'11':[21]}))
locations={'amalekite-messenger':['ziklag','gilboa'],'ishbosheth':['mahanaim'],'rizpah':['gibeah'],'mephibosheth-jonathan':['lodebar','jerusalem'],'mephibosheth-saul':['gibeah'],'armoni':['gibeah'],'uzzah':['kiriath-jearim'],'ahio':['kiriath-jearim'],'obed-edom':[],'nathan-prophet':['jerusalem'],'hiram':['tyre'],'hadadezer':['aram'],'toi':['hamath'],'joram-hamath':['hamath'],'machir':['lodebar','mahanaim'],'hanun':['rabbah'],'bathsheba':['jerusalem'],'uriah':['rabbah','jerusalem'],'unnamed-infant':['jerusalem'],'solomon':['jerusalem'],'amnon':['jerusalem','baal-hazor'],'tamar-david':['jerusalem'],'tekoa-woman':['tekoa','jerusalem'],'en-rogel-servant':['en-rogel'],'bahurim-woman':['bahurim'],'shobi':['rabbah','mahanaim'],'barzillai':['rogellim','mahanaim'],'cushite-messenger':['gilead','mahanaim'],'abel-woman':['abel'],'araunah':['jerusalem'],'abigail-sister':[],'jesse':['bethlehem'],'abigail':['hebron'],'ahinoam-david':['hebron'],'merab':[],'adriel':[],'palti':['bahurim'],'goliath':['gath'],'elhanan-jaare':['bethlehem'],'sibbecai':[],'jonathan-shimei':['gath']}
locations.update({'saul':['gilboa','jabesh-gilead','zela'],'jonathan-saul':['gilboa','jabesh-gilead','zela'],'abimelech':['thebez'],'thembez-woman':['thebez']})
for p in people:
 p['placeIds']=locations.get(p['id'],list(dict.fromkeys(pid for c in chapters if p['id'] in c['people'] for pid in c['places'])))
for s in sources:
 if s['perspective']=='lds':s['chapterCoverage']=[c['chapter'] for c in chapters if s['id'] in c['lds']['sourceIds']]
finish(dict(id='2-samuel',bibleCode='2SA',name='2 Samuel',description='David’s kingdom · Nathan · Bathsheba · Tamar · Absalom · Rizpah',chapterCount=24,scripture=scripture('2-samuel','2SA',24),chapters=chapters,people=people,places=places,sources=sources,review=dict(date='2026-10-05',scope='Chapter-level studies and selected people. Same-name people remain distinct. Historical interpretation and Church teaching have separate records.',nextBook='1-kings')))
