"""Build Romans from reviewed Scripture and original contextual explanations."""
import json,sys,copy
from book_common import ROOT,OUT,scripture,source,person,finish
DATE='2026-10-07';t=scripture('romans','ROM',16)
assert [len(t[str(n)]) for n in range(1,17)]==[32,29,31,25,21,23,25,39,33,21,36,21,14,26,33,25]
assert sum(map(len,t.values()))==434
assert not any('\ufffd' in str(v) for vv in t.values() for v in vv)
notes=json.loads((ROOT/'scripts/book-context-complete/romans.json').read_text(encoding='utf8'))
sources=[]
s=source('web','Romans · World English Bible','https://ebible.org/engwebp/ROM01.htm','All sixteen chapters supply the text for original close readings.','Scripture','historical','The letter supplies the primary text. Original manuscripts, authorship, dates, and each recalled event were not independently verified. The publisher places the closing praise at 14:24–26 and leaves 16:25 empty with a note. No duplicated or invented verses fill that position.')
s.update(author='World English Bible translators',publisher='eBible.org',chapterCoverage=list(range(1,17)),reviewed=dict(date=DATE,scope='All 434 numbered positions and publisher notes read. Sixteen original explanations and exact selections checked in their surroundings. Counts and character integrity checked. The empty position at 16:25 retains its exact publisher note.'));sources.append(s)
s=source('shore-romans','Commentary on Romans 14:1-12','https://www.workingpreacher.org/commentaries/revised-common-lectionary/ordinary-24/commentary-on-romans-141-12-2','Shore reads welcome through shared belonging and God’s authority to judge.','Scholarly study','historical','This is Shore’s interpretation. Her cited books and historical comparisons were not independently reviewed. Linked commentaries and podcasts were not reviewed.')
s.update(author='Mary Hinkle Shore',publisher='Luther Seminary',year=2011,chapterCoverage=[14],reviewed=dict(date=DATE,scope='Complete commentary body read. Its reading of welcome and shared belonging remains attributed. No independent claim about the exact origin of the food dispute is added.'));sources.append(s)
lessons=[(33,[1,2,3,5,6],'August 7–13 · Romans 1–6','The lesson studies inward commitment, grace, and changed conduct.'),(34,[8,10,13,14,15],'August 14–20 · Romans 7–16','The lesson studies becoming like Heavenly Father, faith, love, and acceptance.')]
for number,coverage,title,summary in lessons:
 s=source('cfm-nt-2023-'+str(number),title,f'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-sunday-school-new-testament-2023/{number}?lang=eng',summary,'LDS Come, Follow Me','lds','Church teaching remains distinct from Paul’s own words. Coverage follows actual teaching and cited Bible passages in the body, not the whole chapter range in the heading.')
 s.update(author='The Church of Jesus Christ of Latter-day Saints',publisher='The Church of Jesus Christ of Latter-day Saints',year=2023,chapterCoverage=coverage,reviewed=dict(date=DATE,scope='Complete lesson body and included resources read. Quoted talk passages were read in this lesson. Linked full talks, videos, Gospel Topics, and Restoration passages were not independently reviewed. Only listed chapters receive selected teaching.'));sources.append(s)
acts=json.loads((OUT/'acts.json').read_text(encoding='utf8'))
sources.extend(copy.deepcopy([s for s in acts['sources'] if s['id'] in ['atlas-canaan','net-acts-map']]))
people=[]
rows=[
 ('acts','paul','Paul','Letter speaker who hopes to visit the Roman believers','His companions send greetings. Tertius names his own writing role.','Romans 1–16','He seeks encouragement from the believers as well as sharing his teaching.',['Paul']),
 ('matthew','jesus','Jesus Christ','The one through whom Paul describes God’s gift and welcome','Paul connects his death and resurrection with the believers’ changed life.','Romans 1–16','His welcome supplies the pattern for receiving others across disputed practices.',['Jesus','Christ']),
 ('genesis','abraham','Abraham','Ancestor whose trust comes before circumcision','Sarah shares the promised birth despite their old age.','Romans 4; 9; 11','The order of promise and sign connects him with believers from different peoples.',['Abraham']),
 ('genesis','sarah','Sarah','Abraham’s wife whose condition makes the promised birth seem impossible','Paul connects her body with Abraham’s old age and God’s promise.','Romans 4:19; 9:9','Her remembered condition makes the promise depend on God’s power rather than visible strength.',['Sarah']),
 ('1-samuel','david','David','Remembered king whose words Paul cites in his argument','Paul names Jesus as David’s descendant and cites David’s words about forgiveness.','Romans 1:3; 4:6–8; 11:9–10','His cited words join earlier Scripture with the letter’s questions about mercy and failure.',['David']),
 ('acts','priscilla','Prisca, also called Priscilla','Worker whom Paul greets with Aquila','Paul says they risked their lives for him. A church meets in their house.','Romans 16:3–5','Their household and risk show the personal help behind Paul’s wider teaching task.',['Prisca']),
 ('acts','aquila','Aquila','Worker whom Paul greets with Prisca','A church meets in their house. Paul and Gentile churches thank them.','Romans 16:3–5','His shared work connects a household with the needs of a wider group of believers.',['Aquila']),
 (None,'phoebe','Phoebe','Servant or deacon of the church in Cenchreae','Paul asks the Roman believers to welcome her and help with her needs.','Romans 16:1–2','Her previous help to many people supports Paul’s request for practical welcome.',['Phoebe']),
 (None,'tertius','Tertius','Writer who adds his own greeting within Paul’s letter','He greets the Roman believers alongside Paul’s other companions.','Romans 16:22','His named writing role makes another person’s contribution visible within the letter.',['Tertius']),
 (None,'timothy','Timothy','Worker who sends greetings with Paul’s companions','Lucius, Jason, and Sosipater also send greetings in the same verse.','Romans 16:21','His greeting connects the letter’s readers with workers beyond Paul alone.',['Timothy'])]
profileChapters={'paul':[1,15,16],'jesus':list(range(1,17)),'abraham':[4,9,11],'sarah':[4,9],'david':[1,4,11],'priscilla':[16],'aquila':[16],'phoebe':[16],'tertius':[16],'timothy':[16]}
for book,pid,name,role,relations,passages,meaning,links in rows:
 p=person(pid,name,role,relations,passages,meaning)
 if book:
  old=json.loads((OUT/(book+'.json')).read_text(encoding='utf8'));original=next(x for x in old['people'] if x['id']==pid)
  p['life']=original['life']
 p.update(placeIds=[],linkNames=links,verseScope={});people.append(p)
places=copy.deepcopy([p for p in acts['places'] if p['id'] in ['rome','jerusalem']])
for p in places:
 p.update(verseScope={},summary='Rome is the intended visit named near the letter’s beginning and close.' if p['id']=='rome' else 'Jerusalem is the planned destination of the material gift before Paul’s hoped-for visit.')
summaries=['Paul introduces his task, desired visit, and the need for the gospel.','Paul challenges judgment of others and confidence based on outward signs.','Shared failure leads into God’s gift for both peoples.','Abraham’s trust and the order of promise and circumcision support Paul’s argument.','Peace and hope lead into Christ’s gift, contrasted with Adam’s trespass.','Baptism and changed service answer the proposed use of sin to increase grace.','Paul distinguishes the law’s goodness from sin’s use of its command.','Life through the Spirit includes belonging, suffering, hope, prayer, and assurance.','Paul grieves for Israel and asks hard questions about God’s promise and mercy.','Paul connects calling with faith, hearing, and sent speakers.','A remaining group and the olive tree image warn Gentiles against pride.','Shared gifts and concrete love lead into the refusal of personal revenge.','Rulers, public obligations, love, and the approaching day shape Paul’s instructions.','Food and chosen days lead into welcome, restraint, and shared belonging.','Shared welcome leads into Paul’s work, material help, and desired journeys.','Paul commends Phoebe and sends greetings that name many people’s work.']
questions=['Why does Paul explain his visit through mutual encouragement?','Why does judging another person fail to establish the judge’s innocence?','How does one God connect the two peoples in Paul’s argument?','Why does the timing of Abraham’s circumcision matter?','Why does Paul stress that Christ died while the recipients remained sinners?','How does the contrast between wages and gift shape the closing verse?','Why does Paul distinguish the command from sin’s use of it?','How does the Spirit help when believers cannot supply fitting words?','Why does Paul begin with Israel’s gifts and his own grief?','What must happen before another person can hear and call?','Why must the added branches refuse to boast over the root?','How do the peace command’s limits affect personal responsibility?','How does love explain the listed commands through preventing harm?','How can using freedom damage the person one should welcome?','How does the Jerusalem gift make the relationship between peoples practical?','Why does Paul ask for Phoebe’s welcome before the other greetings?']
teach={1:'The selected lesson teaches courage in sharing the gospel.',2:'The selected lesson connects inward commitment with conduct.',3:'The selected lesson teaches grace as God’s gift rather than earned salvation.',5:'The selected lesson connects grace with changed conduct.',6:'The selected lesson teaches that grace calls believers toward changed conduct.',8:'The selected lesson teaches becoming like Heavenly Father through Jesus Christ. This is Church teaching.',10:'The selected lesson connects hearing with growing faith.',13:'The selected lesson teaches that love fulfills God’s commands.',14:'The selected lesson warns against judging others through differences in practice.',15:'The selected lesson connects Scripture with faith and hope.'}
lessonIds={c:['cfm-nt-2023-'+str(num)] for num,cc,_,_ in lessons for c in cc}
chapters=[]
for n,v,title,meaning in notes:
 loc=['rome'] if n==1 else ['rome','jerusalem'] if n==15 else []
 chapters.append(dict(chapter=n,title=title,summary=summaries[n-1],meaning=meaning,people=[pid for pid,cc in profileChapters.items() if n in cc],places=loc,sourceIds=['web']+(['shore-romans'] if n==14 else []),lds=dict(text=teach.get(n,'')+(' ' if n in teach else '')+'Study question. '+questions[n-1],sourceIds=lessonIds.get(n,[])),eventOrder=n,dateLabel='Book order',historicalNote=meaning,mapNote='Selected markers show intended destinations named in the letter. They do not prove completed journeys.',route=[],routeEvidence='The letter’s travel plans do not establish an exact journey.'))
data=dict(id='romans',bibleCode='ROM',name='Romans',description='Grace · shared belonging · Israel · changed conduct · welcome',chapterCount=16,scripture=t,chapters=chapters,people=people,places=places,sources=sources,review=dict(date=DATE,contextReviewDate=DATE,copyReviewDate=DATE,scope='All 434 numbered positions read for sixteen original contextual explanations and exact selections. Ten selected profiles and two destination references do not claim exhaustive coverage. Two Church lessons retain actual chapter teaching. Shore’s interpretation remains attributed. Publisher note at 16:25 remains separate. Original manuscripts, authorship, dates, Greek terms, historical reconstruction of disputes, and fulfillment of travel plans were not independently verified.',nextBook='1-corinthians'))
if '--ready' in sys.argv:finish(data)
else:(ROOT/'review/romans-draft.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
