"""Build Second Corinthians from reviewed Scripture and original close readings."""
import json,copy,sys
from book_common import ROOT,OUT,scripture,source,person,finish
DATE='2026-10-07';t=scripture('2-corinthians','2CO',13)
assert [len(t[str(n)]) for n in range(1,14)]==[24,17,18,18,21,18,16,24,15,18,33,21,14]
assert sum(map(len,t.values()))==257
assert not any('\ufffd' in str(v) for vv in t.values() for v in vv)
notes=json.loads((ROOT/'scripts/book-context-complete/2-corinthians.json').read_text(encoding='utf8'))
sources=[]
s=source('web','2 Corinthians · World English Bible','https://ebible.org/engwebp/2CO01.htm','All thirteen chapters supply the primary text for original close readings.','Scripture','historical','The letter’s claims and remembered events remain its own account. Original manuscripts, dates, authorship, possible earlier letters, the unnamed offender’s identity, and the thorn’s exact condition were not independently verified.')
s.update(author='World English Bible translators',publisher='eBible.org',chapterCoverage=list(range(1,14)),reviewed=dict(date=DATE,scope='All 257 verses read for thirteen original explanations and exact selections. Surroundings, counts, and character integrity checked.'));sources.append(s)
s=source('tiede-2cor','Commentary on 2 Corinthians 12:2-10','https://www.workingpreacher.org/commentaries/revised-common-lectionary/ordinary-14-2/commentary-on-2-corinthians-122-10-2','Tiede reads Paul’s confidence through Christ’s power within weakness.','Scholarly study','historical','This remains Tiede’s interpretation. His broader claims about ancient speaking customs, mystery religions, and visionary experiences were not independently verified. His cited Newbigin book and related commentaries were not reviewed.')
s.update(author='David Tiede',publisher='Luther Seminary',year=2009,chapterCoverage=[12],reviewed=dict(date=DATE,scope='Complete commentary body and note read. The guide attributes the reading of confidence grounded in Christ rather than superior spiritual experience. It does not adopt an exact diagnosis of the thorn.'));sources.append(s)
lessons=[(38,[1,2,4,5,7],'September 11–17 · 2 Corinthians 1–7','The lesson studies comfort, forgiveness, restored relationship with God, and repentance.'),(39,[8,9,11,12],'September 18–24 · 2 Corinthians 8–13','The lesson studies generous giving, simple discipleship, and grace within weakness.')]
for num,cc,title,summary in lessons:
 s=source('cfm-nt-2023-'+str(num),title,f'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-sunday-school-new-testament-2023/{num}?lang=eng',summary,'LDS Come, Follow Me','lds','Church teaching remains separate from original close reading. Coverage follows the lesson body rather than its broader heading. Linked full talks, manuals, videos, and Restoration passages were not independently reviewed.')
 s.update(author='The Church of Jesus Christ of Latter-day Saints',publisher='The Church of Jesus Christ of Latter-day Saints',year=2023,chapterCoverage=cc,reviewed=dict(date=DATE,scope='Complete lesson body and included resources read. Uchtdorf quotations were read within these lessons, not in their complete original talks. Omitted chapters do not receive lesson coverage.'));sources.append(s)
acts=json.loads((OUT/'acts.json').read_text(encoding='utf8'));sources.extend(copy.deepcopy([s for s in acts['sources'] if s['id'] in ['atlas-canaan','net-acts-map']]))
rows=[
 ('acts','paul','Paul','Letter speaker who explains strained relationships and disputed authority','Timothy shares the opening greeting. Titus brings news and helps with the gift.','2 Corinthians 1–13','His defense repeatedly connects authority with building others rather than winning personal honor.',['Paul']),
 ('matthew','jesus','Jesus Christ','The crucified and risen Lord through whom Paul describes restored relationship','Paul connects his gift and power with the believers’ present life.','2 Corinthians 1–13','His power within weakness changes the measures used to judge Paul’s service.',['Jesus','Christ']),
 ('romans','timothy','Timothy','Worker named with Paul in the opening greeting','Paul recalls that Timothy helped teach Jesus Christ among the believers.','2 Corinthians 1:1, 19','His named work keeps the opening defense connected with shared service.',['Timothy']),
 ('acts','silas','Silvanus','Worker named among those who taught Jesus Christ in Corinth','Paul names himself and Timothy beside him.','2 Corinthians 1:19','The remembered shared message answers the accusation that Paul’s changed plans make him unreliable.',['Silvanus']),
 ('exodus','moses','Moses','Remembered leader whose shining face and veil become part of Paul’s comparison','Paul compares the stone tablets with changed hearts through the Spirit.','2 Corinthians 3:7–15','His earlier glory matters because Paul claims greater glory rather than denying its existence.',['Moses']),
 (None,'titus','Titus','Trusted worker whose report comforts Paul and who helps complete the collection','The believers refresh his spirit. Other chosen workers travel with him.','2 Corinthians 2; 7; 8; 12','His welcome and careful work connect restored relationships with practical handling of material help.',['Titus'])]
people=[];profileChapters={'paul':list(range(1,14)),'jesus':list(range(1,14)),'timothy':[1],'silas':[1],'moses':[3],'titus':[2,7,8,12]}
for book,pid,name,role,relations,passages,meaning,links in rows:
 p=person(pid,name,role,relations,passages,meaning)
 if book:
  old=json.loads((OUT/(book+'.json')).read_text(encoding='utf8'));p['life']=next(x for x in old['people'] if x['id']==pid)['life']
 p.update(placeIds=[],linkNames=links,verseScope={});people.append(p)
places=copy.deepcopy([p for p in acts['places'] if p['id'] in ['corinth','damascus']])
for p in places:p.update(verseScope={},summary='Corinth names the church receiving the letter and Paul’s intended visit.' if p['id']=='corinth' else 'Damascus appears in Paul’s remembered basket escape through the city wall.')
summaries=['Comfort and recalled danger lead into Paul’s explanation of a changed visit.','An earlier painful letter leads into forgiveness and Paul’s unrest about Titus.','The believers become Paul’s recommendation letter before a comparison involving Moses’ veil.','Fragile clay vessels and pressures connect service with hope beyond visible decay.','Future life and judgment lead into restored relationship through Christ.','Hardships and open hearts stand beside a warning about incompatible worship.','Titus’ report brings comfort through the hearers’ changed response to Paul’s letter.','Macedonian generosity leads into completed giving and careful handling of the collection.','Advance preparation leads into willing giving, help, thanksgiving, and prayer.','Paul answers judgments about his presence, letters, and claimed authority.','A rival message leads into Paul’s deliberately foolish record of hardship.','A heavenly experience and thorn lead into grace within weakness and further defense.','Another intended visit brings a warning, self examination, and a prayer for repair.']
questions=['Why does Paul end his travel explanation by refusing control over their faith?','Why must sufficient punishment give way to comfort and confirmed love?','How can the believers themselves function as a recommendation letter?','Why does Paul compare powerful treasure with fragile clay carriers?','How does restored relationship change the purpose of the speakers’ appeal?','Why does Paul pair sorrow with joy and poverty with riches?','Why does Paul value changed conduct rather than sorrow by itself?','How do chosen companions protect the collection from blame?','Why does advance preparation help protect giving from pressure?','How does authority’s purpose limit its use against the hearers?','Why does Paul’s boasting list so many dangers and weaknesses?','How does the answer about grace differ from Paul’s requested removal?','Why does Paul pray for right conduct even if he appears to fail?']
teach={1:'The selected lesson studies comfort received and shared during trials.',2:'The selected lesson teaches forgiveness as a gift both given and received.',4:'The selected lesson studies hope and comfort during trials.',5:'The selected lesson teaches restored relationship with God through Jesus Christ’s Atonement.',7:'The selected lesson teaches sorrow that leads to repentance and changed conduct.',8:'The selected lesson teaches sharing with people in need.',9:'The selected lesson teaches cheerful giving rather than reluctant action.',11:'The selected lesson teaches a simple focus on following Jesus Christ.',12:'The selected lesson teaches finding strength through the Savior’s grace within weakness.'}
lessonIds={c:['cfm-nt-2023-'+str(num)] for num,cc,_,_ in lessons for c in cc};chapters=[]
for n,v,title,meaning in notes:
 loc=['corinth'] if n==1 else ['damascus'] if n==11 else []
 chapters.append(dict(chapter=n,title=title,summary=summaries[n-1],meaning=meaning,people=[pid for pid,cc in profileChapters.items() if n in cc],places=loc,sourceIds=['web']+(['tiede-2cor'] if n==12 else []),lds=dict(text=teach.get(n,'')+(' ' if n in teach else '')+'Study question. '+questions[n-1],sourceIds=lessonIds.get(n,[])),eventOrder=n,dateLabel='Book order',historicalNote=meaning,mapNote='Selected cities show the receiving church and one recalled setting. No exact house, window, or journey is assigned.',route=[],routeEvidence='The letter does not supply an independently verified travel route.'))
data=dict(id='2-corinthians',bibleCode='2CO',name='2 Corinthians',description='Comfort · restored relationships · giving · weakness · disputed authority',chapterCount=13,scripture=t,chapters=chapters,people=people,places=places,sources=sources,review=dict(date=DATE,contextReviewDate=DATE,copyReviewDate=DATE,scope='All 257 verses read for thirteen original contextual explanations and exact selections. Six selected profiles and two city references do not claim exhaustive coverage. Two Church lesson bodies retain actual chapter coverage. Tiede’s interpretation remains attributed. Earlier letter identities, exact dates, original manuscripts, Greek forms, the thorn’s condition, and detailed historical reconstruction were not independently verified.',nextBook='galatians'))
if '--ready' in sys.argv:finish(data)
else:(ROOT/'review/2-corinthians-draft.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
