"""Reviewed chapter studies for Samuel, Saul, and David. Reuse Isaiah's interface."""
import json
from book_common import OUT,source,person,place,scripture,finish
rows=[
('Hannah prays and dedicates Samuel','Hannah endures Peninnah’s provocation, prays at Shiloh, and later brings Samuel to serve there.','Her distress deserves attention before the happy outcome. The account does not make infertility a personal fault.','hannah,peninnah,elkanah,eli,samuel','ramah,shiloh','The Church lesson studies prayer during hardship. It expressly says that not everyone who prays for a child receives one.'),
('Hannah’s song and the failure of Eli’s sons','Hannah praises God. Hophni and Phinehas abuse their office. An unnamed messenger announces judgment against Eli’s household.','The song describes changed social fortunes. Priestly authority does not excuse taking offerings by force or exploiting people.','hannah,elkanah,samuel,eli,hophni,phinehas-eli,man-of-god','shiloh','The older manual reads Hannah’s song through Jesus Christ. That Christian interpretation remains distinct from the poem’s royal language.'),
('Samuel hears the call','Samuel repeatedly mistakes the call for Eli’s voice. Eli guides his response, and Samuel receives a difficult message.','Listening includes learning from another person. The message concerns Eli’s failure to restrain wrongdoing, not only Samuel’s private experience.','samuel,eli','shiloh','Come, Follow Me connects Samuel’s response with learning to recognize revelation.'),
('The ark is captured and Eli’s household suffers loss','Israel brings the ark from Shiloh into battle. The Philistines capture it. Eli and his sons die, and Ichabod is born.','The losses affect a whole household. Ichabod’s unnamed mother expresses the catastrophe while dying after childbirth.','eli,hophni,phinehas-eli,ichabod,ichabod-mother','shiloh,aphek,ebenezer-battle','The Church lesson distinguishes possession of a sacred object from faithful conduct.'),
('The ark among the Philistine towns','The ark is placed beside Dagon at Ashdod. Distress follows its movement to Gath and Ekron.','The narrative contests the idea that capturing the ark proves superiority over Israel’s God. It does not establish a modern medical diagnosis.','','ashdod,gath,ekron','The older manual studies the ark’s capture and return. Its proposed disease identification is not verified here.'),
('The ark returns to Beth Shemesh','The Philistines send offerings with the ark on a cart. It reaches Beth Shemesh, where rejoicing gives way to mourning.','The account joins relief with danger around a sacred object. The large casualty figure remains the reading text’s number, not a verified count.','joshua-beth-shemesh','ekron,beth-shemesh,kiriath-jearim','The Church lesson uses these events to study trust and obedience.'),
('Samuel leads the gathering at Mizpah','The ark stays with Abinadab’s household. Samuel calls Israel to renewed worship and leads the gathering at Mizpah.','The memorial stone marks received help. Samuel’s circuit combines worship, leadership, and judgment.','samuel,abinadab-ark,eleazar-ark','kiriath-jearim,mizpah,ramah,bethel,gilgal','Come, Follow Me studies turning toward God after earlier failure.'),
('The people request a king','Samuel’s sons take bribes. The elders request a king, and Samuel warns about royal demands on families, property, and work.','The demand responds to real leadership failures. The warning asks readers to consider the costs of concentrated power.','samuel,joel-samuel,abijah-samuel','ramah,beersheba','The Church lesson invites readers to consider Jesus Christ as their King.'),
('Saul searches for donkeys and meets Samuel','Kish sends Saul with a servant to find missing donkeys. Their search brings them to Samuel.','An ordinary household task introduces public responsibility. Saul’s physical appearance does not establish his later fitness to rule.','saul,kish,samuel,saul-servant','ramah','Come, Follow Me connects Saul’s selection with a call to service.'),
('Saul is anointed and presented publicly','Samuel anoints Saul privately. Later, Saul is selected before the gathering at Mizpah and found among the baggage.','Private anointing and public selection are distinct scenes. Hayes studies their place among differing presentations of kingship.','samuel,saul,kish','ramah,mizpah,gibeah','The Church lesson connects anointing and changed purpose with service by revelation.'),
('Saul relieves Jabesh Gilead','Nahash threatens the people of Jabesh Gilead. Saul gathers help, wins the battle, and refuses to execute earlier opponents.','Leadership includes protecting people and limiting retaliation after victory. The narrative renews Saul’s public support at Gilgal.','saul,samuel,nahash','gibeah,jabesh-gilead,gilgal','The older manual studies Saul’s early leadership and the renewed kingdom.'),
('Samuel reviews leadership and covenant responsibility','Samuel asks the people to assess his conduct. He recalls earlier deliverers and warns both people and king to remain faithful.','Public office remains accountable. Installing a king does not remove the people’s responsibility for their own conduct.','samuel,saul,nahash,moses,aaron,gideon,jephthah','gilgal','The older manual studies Samuel’s final address and continued prayer for the people.'),
('Pressure at Michmash and Saul’s offering','Jonathan strikes a garrison. Facing Philistine forces and desertion, Saul offers sacrifice before Samuel arrives. Samuel rejects Saul’s continuing dynasty.','Fear and time pressure shape Saul’s explanation. The chapter’s opening reign figures vary across textual witnesses and translations.','saul,samuel,jonathan-saul','michmash,gibeah,gilgal','The Church lesson studies obedience under pressure. The older manual also reads the offering as unauthorized priesthood action.'),
('Jonathan’s attack and Saul’s dangerous oath','Jonathan and his armor bearer attack a garrison. Saul’s food prohibition places Jonathan under sentence of death, but the people rescue him.','An order can harm the people it should protect. The soldiers challenge a deadly application of the king’s oath.','saul,jonathan-saul,jonathan-armor-bearer,ahijah-priest,abner,ahinoam-saul,merab,michal,ishvi,malchishua','michmash,gibeah','The older manual studies Jonathan’s faith and the harmful effect of Saul’s oath.'),
('Amalek, Agag, and Saul’s rejection','Saul attacks Amalek but spares Agag and selected livestock. Samuel rejects Saul’s defense and later kills Agag.','The command includes women and infants. The guide records that disturbing content without turning ancient warfare into permission for present violence.','saul,samuel,agag','carmel-judah,gilgal','Come, Follow Me studies obedience rather than religious display. This application does not independently verify the campaign or remove its victims.'),
('David is anointed and enters Saul’s service','Samuel anoints Jesse’s youngest son David. David later plays music for Saul and serves in his household.','The selection challenges judgment by appearance. The text’s troubling spirit language should not become a diagnosis of a living person.','samuel,jesse,david,eliab-david,abinadab-david,shammah,saul','bethlehem,ramah,gibeah','The Church lesson studies inward character. The older manual cites a Joseph Smith Translation reading that changes the spirit’s stated origin.'),
('David faces Goliath in the Valley of Elah','David brings provisions to his brothers, accepts Goliath’s challenge, and defeats him with a sling and then his sword.','The account contrasts fear, status, skill, and stated trust in God. Its violent conclusion remains part of the story.','david,goliath,saul,jesse,eliab-david,abinadab-david,shammah,abner','bethlehem,elah,gath','Come, Follow Me studies faith and courage. Spiritual application does not independently confirm the duel’s details.'),
('Friendship, jealousy, and royal marriage plans','Jonathan forms a bond with David. Saul grows jealous, offers Merab, then arranges David’s marriage to Michal through a deadly demand.','Friendship contrasts with treating a person as a threat. The women’s marriages also serve Saul’s political plans.','david,jonathan-saul,saul,merab,michal,adriel','gibeah','The Church lesson compares Jonathan’s support with Saul’s jealousy.'),
('Michal helps David escape','Saul resumes attempts to kill David. Michal helps David through a window. David joins Samuel at Ramah, where pursuit is interrupted.','Michal takes action in danger. A household idol appears in her deception, complicating a simple picture of household religion.','saul,david,jonathan-saul,michal,samuel','gibeah,ramah','The older manual compares the prophetic group with a later Church school. This is a religious comparison, not proof of identical institutions.'),
('Jonathan warns David and renews their covenant','Jonathan tests Saul’s intent at the new-moon meal. He signals danger with arrows and parts from David in grief.','Their promise extends beyond immediate friendship to their households. Saul’s attack also puts Jonathan at risk.','david,jonathan-saul,saul,jonathan-boy','gibeah','Original study reflection: consider the cost of protecting a friend under pressure from a powerful family member.'),
('David seeks food at Nob and refuge at Gath','Ahimelech gives David consecrated bread and Goliath’s sword. Doeg observes him. David then escapes danger at Achish’s court.','David’s misleading claim about a royal mission places others in danger. Need, survival, and responsibility all matter.','david,ahimelech-priest,doeg,achish,goliath','nob,gath','The older manual connects the bread account with Jesus’s later teaching about human need.'),
('David gathers followers and Saul orders the Nob massacre','David gathers distressed followers and seeks safety for his parents. Saul orders the priests’ deaths. Doeg carries out the killing, and Abiathar escapes.','The guards refuse the order, but Doeg acts. The massacre includes children. David acknowledges responsibility for danger to Abiathar’s family.','david,jesse,gad,saul,doeg,ahimelech-priest,abiathar','adullam,moab,nob,gibeah','The older manual condemns Saul’s killing of innocent people. Religious office does not excuse destructive power.'),
('Keilah, wilderness pursuit, and Jonathan’s support','David rescues Keilah, leaves after consulting God, and meets Jonathan during Saul’s pursuit. A Philistine attack interrupts the chase.','Helping a town does not guarantee protection from its people. Jonathan strengthens David while the danger continues.','david,abiathar,saul,jonathan-saul','keilah,ziph,maon','Original study reflection: distinguish wise precautions from a demand that every grateful person must guarantee your safety.'),
('David spares Saul in the cave','David cuts part of Saul’s robe but refuses to kill him. Afterward he speaks openly, and Saul acknowledges David’s future.','Restraint does not require David to return to Saul’s control. He remains apart after the encounter.','david,saul','en-gedi','Come, Follow Me studies self-control and forgiveness. The passage does not require a threatened person to return to danger.'),
('Abigail prevents David’s revenge','After Nabal refuses assistance, David prepares an attack. Abigail brings provisions and persuades him to stop. After Nabal dies, she marries David.','Abigail prevents bloodshed through informed action. David needs correction here. The story does not establish a medical diagnosis for Nabal’s death.','david,samuel,abigail,nabal,ahinoam-david,michal,palti','ramah,maon,carmel-judah','The Church lesson studies restraint and forgiveness. It compares Abigail’s intervention with Jesus Christ.'),
('David takes the spear and water jar','David and Abishai enter Saul’s camp. David again refuses to kill Saul, then confronts Abner about the failure to protect him.','This second spared-life account resembles chapter 24 but uses different objects and companions. The guide keeps both narrated scenes.','david,saul,abishai,ahimelech-hittite,abner','ziph','Come, Follow Me studies self-control. Restraint and continued separation occur together in the story.'),
('David lives under Achish and conceals his raids','David moves with his household and followers into Philistine territory. Achish grants Ziklag. David raids other populations and misleads Achish.','David kills men and women to prevent reports. These victims must remain visible even within a story favorable to David.','david,achish,abigail,ahinoam-david','gath,ziklag','The older manual defends these raids as conquest fulfillment. This is its theological interpretation, not an independently verified justification.'),
('Saul consults the woman at Endor','Saul seeks a forbidden consultation through an unnamed woman. The narrative identifies Samuel in the encounter and announces approaching defeat.','Fear drives Saul to a practice he had suppressed. The woman also gives food and care to the distressed king.','saul,samuel,endor-medium,david,achish','shunem,gilboa,endor','The older manual argues that Samuel did not actually appear. Keep that interpretation distinct from the narrative’s repeated identification of Samuel.'),
('Philistine leaders send David away','Achish defends David, but the other leaders distrust him in battle against Israel. David and his men are sent back.','Achish’s confidence conflicts with the other leaders’ concern. Readers also know about David’s earlier deception.','david,achish','aphek,jezreel,ziklag','Original study reflection: examine what information each person has before judging a decision.'),
('David recovers the captives and shares the spoil','David returns to burned Ziklag. An abandoned Egyptian servant guides the pursuit. David recovers the captives and gives equal shares to those guarding baggage.','Care for a sick outsider makes the pursuit possible. David refuses to treat exhausted companions as worthless.','david,abigail,ahinoam-david,abiathar,egyptian-servant','ziklag,besor','Original study reflection: consider how recovery depends on care, cooperation, and fair treatment of those unable to continue.'),
('Saul and his sons die at Gilboa','The Philistines defeat Israel. Jonathan and two brothers die. Saul falls on his sword, and the people of Jabesh Gilead recover the bodies.','The ending records loss and dignity after defeat. The people who once received Saul’s help now honor his household.','saul,jonathan-saul,abinadab-saul,malchishua,saul-armor-bearer','gilboa,beth-shan,jabesh-gilead','Original study reflection: consider grief and remembrance without treating a person’s whole life as only its final failure.')]

defs=[
('hannah','Hannah','Mother who dedicates Samuel','Wife of Elkanah. Mother of Samuel and later children.','1 Samuel 1–2','She speaks about distress, makes a vow, and gives a song of praise. Infertility is not presented here as her moral failure.'),
('peninnah','Peninnah','Elkanah’s other wife','Mother of sons and daughters in the household.','1 Samuel 1','She provokes Hannah. The text gives no account of her later life.'),
('elkanah','Elkanah','Head of the household that visits Shiloh','Husband of Hannah and Peninnah. Father of Samuel.','1 Samuel 1–2','His family life introduces the account. His reassurance does not erase Hannah’s distress.'),
('samuel','Samuel','Prophet and judge who anoints kings','Son of Hannah and Elkanah. Father of Joel and Abijah.','1 Samuel 1–3; 7–16; 19; 25; 28','He connects the shrine narrative with the rise of monarchy. His sons’ failure complicates succession. His death is reported in chapter 25.'),
('eli','Eli','Priest and judge at Shiloh','Father of Hophni and Phinehas. Guides the young Samuel.','1 Samuel 1–4','He helps Samuel recognize the call but fails to restrain his sons. He dies after hearing of the ark’s capture.'),
('hophni','Hophni','Priest accused of abuse','Son of Eli and brother of Phinehas.','1 Samuel 1–4','His office does not prevent the text from condemning him. He dies when the ark is captured.'),
('phinehas-eli','Phinehas','Eli’s son and priest at Shiloh','Brother of Hophni. Father of Ichabod.','1 Samuel 1–4; 14:3','He is distinct from Aaron’s grandson of the same name. His death leaves a household facing further loss.'),
('man-of-god','The unnamed man of God','Messenger who confronts Eli','Addresses Eli about his household and priestly office.','1 Samuel 2:27–36','The text supplies a warning, not his name or a personal biography.'),
('ichabod','Ichabod','Child born during the household’s catastrophe','Son of Phinehas and his unnamed wife.','1 Samuel 4:19–22; 14:3','His naming expresses loss after the ark’s capture. His later personal life is not narrated.'),
('ichabod-mother','Ichabod’s mother','Unnamed woman who dies after childbirth','Wife of Phinehas and daughter-in-law of Eli.','1 Samuel 4:19–22','She voices the loss of glory amid deaths and the ark’s capture. Her own name is not supplied.'),
('joshua-beth-shemesh','Joshua','Owner of the field at Beth Shemesh','The returning cart stops in his field.','1 Samuel 6:14,18','He is distinct from Moses’s successor. The account names his field without giving his life story.'),
('abinadab-ark','Abinadab','Householder associated with the ark','Father of Eleazar, the appointed ark keeper.','1 Samuel 7:1','His hilltop house receives the ark. He is distinct from David’s brother and Saul’s son.'),
('eleazar-ark','Eleazar','Appointed keeper of the ark','Son of Abinadab at Kiriath Jearim.','1 Samuel 7:1','He is distinct from Aaron’s son. The account gives his responsibility without a wider biography.'),
('joel-samuel','Joel','Judge accused of corruption','Samuel’s firstborn son. Brother of Abijah.','1 Samuel 8:1–3','He takes bribes and distorts justice. He is not the later prophetic book’s named figure.'),
('abijah-samuel','Abijah','Judge accused of corruption','Samuel’s second son. Brother of Joel.','1 Samuel 8:1–3','His failure forms part of the elders’ case for a king. Same-name kings and priests are different profiles.'),
('saul','Saul','Israel’s first king in the narrative','Son of Kish. Father of Jonathan, Merab, Michal, and other children.','1 Samuel 9–31','Early deliverance gives way to jealousy, destructive commands, rejection, and defeat. The guide does not give him a modern medical diagnosis.'),
('kish','Kish','Saul’s father','A Benjaminite whose missing donkeys begin Saul’s search.','1 Samuel 9–10; 14:51','His household task brings Saul toward Samuel. Further personal details are limited.'),
('saul-servant','Saul’s searching companion','Unnamed servant who proposes consulting the seer','Travels with Saul to find Kish’s donkeys.','1 Samuel 9','His practical advice changes the journey. The guide does not invent a name.'),
('nahash','Nahash','Ammonite ruler who threatens Jabesh','Opponent of Saul’s rescue of Jabesh Gilead.','1 Samuel 11; 12:12','He demands mutilation as a condition of surrender. The account reports coercion, not a model of good rule.'),
('jonathan-saul','Jonathan','Saul’s son, warrior, and David’s covenant friend','Brother of Merab and Michal. Son of Saul.','1 Samuel 13–14; 18–20; 23; 31','He challenges dangerous orders and supports David despite succession stakes. He is distinct from the priest in Judges.'),
('jonathan-armor-bearer','Jonathan’s armor bearer','Unnamed companion in the garrison attack','Accompanies Jonathan rather than Saul.','1 Samuel 14:1–14','His active participation is part of the victory account. He is not Saul’s final armor bearer.'),
('ahijah-priest','Ahijah','Priest wearing an ephod with Saul’s force','Son of Ahitub, from Eli’s household.','1 Samuel 14:3,18','He is not the prophet who later addresses Jeroboam. Identification with Ahimelech is not assumed here.'),
('abner','Abner','Commander of Saul’s army','Son of Ner. Connected with Saul’s family.','1 Samuel 14:50; 17:55–57; 20:25; 26','He serves Saul and is challenged after David enters the camp. His later story continues in 2 Samuel.'),
('ahinoam-saul','Ahinoam','Saul’s wife','Daughter of Ahimaaz.','1 Samuel 14:50','She is distinct from David’s wife Ahinoam of Jezreel. The text supplies little personal biography.'),
('merab','Merab','Saul’s elder daughter','Offered to David but married to Adriel.','1 Samuel 14:49; 18:17–19','Her marriage appears within Saul’s political use of his household. Her own wishes are not narrated.'),
('michal','Michal','Saul’s daughter who helps David escape','Wife of David, later given by Saul to Palti.','1 Samuel 14:49; 18–19; 25:44','The text states that she loves David. Her escape plan protects him. Her transfers between households are not described as her choices.'),
('ishvi','Ishvi','Son listed in Saul’s household','Named with Jonathan and Malchishua.','1 Samuel 14:49','The guide does not silently equate him with every differently named son in later lists.'),
('malchishua','Malchishua','Saul’s son who dies at Gilboa','Brother of Jonathan and Abinadab in the death account.','1 Samuel 14:49; 31:2','His death forms part of the royal household’s loss. Little further biography is supplied.'),
('agag','Agag','Amalekite king spared by Saul, then killed by Samuel','Captive in the campaign account.','1 Samuel 15','The disagreement over his survival marks Saul’s rejection. His death is explicitly narrated.'),
('eliab-david','Eliab','Jesse’s oldest son','David’s older brother.','1 Samuel 16:6; 17:13,28','He appears during the selection and criticizes David at the battlefront. He is distinct from Numbers’ tribal leader.'),
('abinadab-david','Abinadab','One of Jesse’s older sons','Brother of David, Eliab, and Shammah.','1 Samuel 16:8; 17:13','He is distinct from the ark’s host and Saul’s son. He appears among the brothers at the battlefront.'),
('shammah','Shammah','One of Jesse’s older sons','Brother of David, Eliab, and Abinadab.','1 Samuel 16:9; 17:13','Samuel passes him over in the selection. He later serves with the army.'),
('goliath','Goliath','Philistine champion from Gath','Opponent of David in the duel account.','1 Samuel 17; 21:9; 22:10','His challenge organizes the armies’ confrontation. Portraits and this guide do not verify an exact height.'),
('adriel','Adriel','Man who marries Merab','Called the Meholathite.','1 Samuel 18:19','He receives the marriage first offered to David. The book provides no extended personal account.'),
('jonathan-boy','Jonathan’s young attendant','Unnamed boy who retrieves arrows','Assists Jonathan during the warning signal.','1 Samuel 20:35–40','He does not know the signal’s meaning. The guide does not portray him as a co-planner.'),
('ahimelech-priest','Ahimelech','Priest at Nob who assists David','Son of Ahitub. Father of Abiathar.','1 Samuel 21–22','He gives food and a sword, then is accused and killed. He is distinct from the Hittite companion in chapter 26.'),
('doeg','Doeg','Saul’s Edomite servant and informer','Chief among Saul’s herdsmen in the reading text.','1 Samuel 21–22','He reports David’s visit and carries out the massacre after the guards refuse.'),
('achish','Achish','King of Gath who hosts David','Son of Maoch. Grants David Ziklag.','1 Samuel 21; 27–29','He trusts David’s reports, but readers know they conceal the raids’ targets.'),
('gad','Gad','Prophet who advises David during flight','Directs David away from the stronghold toward Judah.','1 Samuel 22:5','He is distinct from Jacob’s son Gad and the tribe bearing that name.'),
('abiathar','Abiathar','Priest who escapes the Nob massacre','Son of Ahimelech. Joins David with an ephod.','1 Samuel 22–23; 30:7','He survives violence against his household and helps David seek direction.'),
('abigail','Abigail','Woman who prevents David’s retaliatory attack','Wife of Nabal, then David.','1 Samuel 25; 27:3; 30:5,18','Her judgment and action correct David’s dangerous plan. Her skill is not reduced to beauty.'),
('nabal','Nabal','Wealthy flock owner who refuses David’s request','Husband of Abigail. Connected with Caleb’s house.','1 Samuel 25','His refusal prompts a threatened attack. The text describes his death without establishing a modern diagnosis.'),
('ahinoam-david','Ahinoam','David’s wife from Jezreel','Captured at Ziklag with Abigail, then recovered.','1 Samuel 25:43; 27:3; 30:5,18','She is distinct from Saul’s wife. Her presence makes household vulnerability part of David’s flight.'),
('palti','Palti','Man to whom Saul gives Michal','Son of Laish, from Gallim.','1 Samuel 25:44','The text records Saul’s action without explaining Michal’s consent or Palti’s personal motives.'),
('abishai','Abishai','David’s companion in Saul’s camp','Son of Zeruiah and brother of Joab.','1 Samuel 26:6–9','He proposes killing Saul. David refuses the proposal and limits the action.'),
('ahimelech-hittite','Ahimelech','Hittite companion addressed by David','Named with Abishai before the camp visit.','1 Samuel 26:6','He is distinct from the priest killed at Nob. Abishai volunteers for the visit.'),
('endor-medium','The woman at Endor','Unnamed woman who conducts Saul’s consultation','Receives Saul in disguise and later feeds him.','1 Samuel 28','She fears the ban Saul imposed. The text never gives her a personal name. Later art often uses the title Witch of Endor.'),
('egyptian-servant','The Egyptian servant','Abandoned sick man who guides David','Servant of an Amalekite participant in the raid.','1 Samuel 30:11–16','He receives food and asks for protection from death or return to his master. The text gives no name.'),
('abinadab-saul','Abinadab','Saul’s son who dies at Gilboa','Brother of Jonathan and Malchishua.','1 Samuel 31:2','He is distinct from David’s brother and the ark’s host.'),
('saul-armor-bearer','Saul’s armor bearer','Unnamed attendant at the final battle','Serves Saul at Gilboa.','1 Samuel 31:4–6','He refuses Saul’s request to kill him, then dies himself. He is distinct from Jonathan’s earlier companion.')]
people=[person(*row) for row in defs]
for slug,ids in [('ruth',['david','jesse']),('exodus',['moses','aaron']),('judges',['gideon','jephthah'])]:
 b=json.loads((OUT/(slug+'.json')).read_text(encoding='utf-8'))
 for p in b['people']:
  if p['id'] not in ids:continue
  p=dict(p);p.update(sourceIds=['web'],placeIds=[])
  if p['id']=='david':p.update(role='Anointed successor, musician, warrior, and fugitive',relations='Son of Jesse. Covenant friend of Jonathan. Husband of Michal, Abigail, and Ahinoam.',passages='1 Samuel 16–31',meaning='He receives favor and protection but also misleads others and kills civilians. The guide preserves these tensions rather than making him flawless.')
  elif p['id']=='jesse':p.update(role='David’s father at Bethlehem',relations='Father of Eliab, Abinadab, Shammah, David, and other sons.',passages='1 Samuel 16–17; 22',meaning='He presents sons to Samuel and sends provisions to the battlefront. David later seeks safety for his parents.')
  else:p.update(passages='1 Samuel 12',meaning='Samuel recalls this earlier leader. The portrait does not place the person at the current gathering.')
  people.append(p)
coordinates=[('ramah','Ramah · broad locality',31.85,35.24),('shiloh','Shiloh',32.055,35.289),('aphek','Aphek · proposed locality',32.10,34.93),('ebenezer-battle','Ebenezer battle area · uncertain',32.09,34.99),('ashdod','Ashdod',31.75,34.66),('gath','Gath · Tell es-Safi',31.70,34.846),('ekron','Ekron · Tel Miqne',31.777,34.849),('beth-shemesh','Beth Shemesh',31.752,34.976),('kiriath-jearim','Kiriath Jearim',31.81,35.105),('mizpah','Mizpah · proposed locality',31.884,35.218),('bethel','Bethel',31.927,35.238),('gilgal','Gilgal · uncertain locality',31.855,35.49),('beersheba','Beersheba',31.245,34.842),('gibeah','Gibeah · proposed locality',31.823,35.231),('jabesh-gilead','Jabesh Gilead · broad locality',32.397,35.658),('michmash','Michmash',31.87,35.275),('carmel-judah','Carmel in Judah',31.434,35.128),('bethlehem','Bethlehem',31.705,35.202),('elah','Valley of Elah · broad setting',31.686,34.956),('nob','Nob · uncertain locality',31.797,35.243),('adullam','Adullam · broad locality',31.651,35.00),('moab','Moab · broad region',31.50,35.75),('keilah','Keilah · proposed locality',31.615,35.003),('ziph','Ziph · broad wilderness setting',31.476,35.136),('maon','Maon · broad locality',31.414,35.166),('en-gedi','En Gedi',31.462,35.389),('ziklag','Ziklag · uncertain locality',31.37,34.83),('shunem','Shunem',32.606,35.334),('gilboa','Mount Gilboa · broad setting',32.52,35.405),('endor','Endor · broad locality',32.635,35.397),('jezreel','Jezreel',32.559,35.327),('besor','Besor · broad stream region',31.31,34.60),('beth-shan','Beth Shan',32.50,35.50)]
places=[place(id,name,lat,lng,'Named locality or broad region in the chapter account.','Reference marker only. The guide does not identify a private house, exact camp, cave, field, shrine room, or ancient road. Proposed localities remain uncertain.',['web','atlas-canaan']) for id,name,lat,lng in coordinates]
base=json.loads((OUT/'joshua.json').read_text(encoding='utf-8'))
sources=[source('web','1 Samuel · World English Bible','https://ebible.org/engwebp/1SA01.htm','The public-domain text supplies all 31 chapters.','Scripture',limits='The reading text reports narrative actions. It does not independently verify dates, casualty figures, reign lengths, or appearance.')]+[dict(s) for s in base['sources'] if s['id'] in ['terrain','atlas','atlas-canaan']]
def reviewed(s,author,year,coverage,scope):s.update(author=author,year=year,chapterCoverage=coverage,reviewed='2026-10-05: '+scope);sources.append(s)
reviewed(source('yale-samuel','Prophets and Kings · Open Yale Courses, Lecture 13','https://oyc.yale.edu/religious-studies/rlst-145/lecture-13','Hayes studies Samuel’s leadership, differing presentations of monarchy, and the narrative’s changing assessments of Saul and David.',limits='Published transcript sections beginning at 23:05 and 32:46 reviewed. Audio and video were not checked. The transcript occasionally says Judges or names Samuel where 1 Samuel or Saul is intended; this guide follows the biblical text.'),'Christine Hayes · Yale University',2006,[1,2,3,4,7,8,9,10,11,12,13,15,16,17,18,21,24,26],'Relevant published transcript reviewed. Its literary interpretation does not independently verify events.')
reviewed(source('scholar-mccarter','I Samuel · Anchor Yale Bible Commentary','https://yalebooks.yale.edu/book/9780300139501/i-samuel/','The publisher describes McCarter’s work on Samuel’s textual transmission, literary sources, language, and ancient setting.',limits='The linked 1995 paperback edition record and publisher description were reviewed. The full commentary was not read.'),'P. Kyle McCarter · Yale University Press',1995,[1,13,17,31],'Publisher description, author, series, and edition verified. Used only as publication context.')
reviewed(source('dm-samuel','Scholarly Hubris, James White, and Psalm 82 · 1 Samuel 2:25 discussion','https://danielomcclellan.wordpress.com/2010/11/28/scholarly-hubris-james-white-and-psalm-82/','McClellan rejects treating elohim as a lexical equivalent for human judges. His discussion includes the translation of 1 Samuel 2:25.',category='Scholar commentary',limits='Only the original post’s relevant translation discussion is used. This is one scholar’s older argument. The guide does not adopt its personal criticisms or claim verified scholarly consensus.'),'Dan McClellan','November 28, 2010',[2],'Original post’s cited verse and adjoining translation argument reviewed.')
sources[-1]['group']='mcclellan'
reviewed(source('net-saul-reign','1 Samuel 13:1 · NET Bible textual notes','https://bible.org/sites/bible.org/resources/netbible/1sa13_notes.htm','The translation notes describe missing or disputed reign figures and uncertain proposed restorations.',limits='Published notes 1–2 reviewed. Proposed numbers do not establish an exact chronology. Manuscripts were not inspected.'),'NET Bible translation team','Linked published notes',[13],'Notes 1–2 reviewed for the opening reign figures.')
institute='https://www.churchofjesuschrist.org/study/manual/old-testament-student-manual-genesis-2-samuel/'
reviewed(source('lds-samuel-early','1 Samuel 1–15 · Institute commentary',institute+'1-samuel-1-15-the-prophet-samuel-and-saul-king-of-israel?lang=eng','The older manual studies Hannah, Samuel’s call, the ark, kingship, and Saul’s conduct.','LDS study manual','lds',limits='The relevant 1980 commentary sections were reviewed. Older historical claims about disease, metallurgy, and ancient beliefs are not independently verified here.'),'The Church of Jesus Christ of Latter-day Saints',1980,list(range(1,16)),'Sections 24-2–24-35 reviewed for the chapter notes.')
reviewed(source('lds-samuel-late','1 Samuel 16–31 · Institute commentary',institute+'1-samuel-16-31-king-davids-call-to-lead-israel?lang=eng','The older manual studies David’s selection, flight, restraint, Abigail’s intervention, and Saul’s consultation.','LDS study manual','lds',limits='Church interpretation remains distinct from the reading text and historical verification.'),'The Church of Jesus Christ of Latter-day Saints',1980,list(range(16,30)),'Sections 25-2–25-35 reviewed.')
routes={1:['ramah','shiloh'],4:['shiloh','ebenezer-battle'],5:['ashdod','gath','ekron'],6:['ekron','beth-shemesh','kiriath-jearim'],7:['bethel','gilgal','mizpah','ramah'],11:['gibeah','jabesh-gilead','gilgal'],16:['ramah','bethlehem'],17:['bethlehem','elah'],19:['gibeah','ramah'],21:['nob','gath'],22:['adullam','moab'],23:['keilah','ziph','maon'],27:['gath','ziklag'],29:['aphek','ziklag'],30:['ziklag','besor'],31:['gilboa','beth-shan','jabesh-gilead']}
chapters=[]
for n,(title,summary,meaning,pids,locs,lds) in enumerate(rows,1):
 ids=['web','atlas-canaan']+[s['id'] for s in sources if s.get('perspective')=='historical' and n in s.get('chapterCoverage',[])]
 chapters.append(dict(chapter=n,title=title,summary=summary,meaning=meaning,people=pids.split(',') if pids else [],places=locs.split(','),sourceIds=ids,lds=dict(text=lds,sourceIds=['lds-samuel-early'] if n<=15 else ['lds-samuel-late'] if n<=29 else []),eventOrder=n,dateLabel='Chapter order · historical year uncertain',historicalNote='The account concerns the rise of kingship. Exact event years and a complete sequence cannot be independently established here.',mapNote='Named localities and broad regions only. Camp, cave, household, and road positions remain uncertain.',route=routes.get(n,[]),routeEvidence='The line connects named places in narrative order. It does not reconstruct an ancient road or every intervening movement.'))
for p in people:
 if p['id'] in ['david','jesse']:p['placeIds']=['bethlehem']+[id for c in chapters if p['id'] in c['people'] for id in c['places'] if id!='bethlehem']
 p['placeIds']=list(dict.fromkeys(p.get('placeIds',[]))) if 'placeIds' in p else list(dict.fromkeys(id for c in chapters if p['id'] in c['people'] for id in c['places']))
 p['linkNames']={'samuel':[],'jonathan-saul':[],'goliath':[],'jonathan-armor-bearer':[],'saul-armor-bearer':[]}.get(p['id'],[])
locations={
 'hannah':['ramah','shiloh'],'peninnah':['ramah','shiloh'],'elkanah':['ramah','shiloh'],
 'eli':['shiloh'],'hophni':['shiloh','ebenezer-battle'],'phinehas-eli':['shiloh','ebenezer-battle'],
 'man-of-god':['shiloh'],'ichabod':['shiloh'],'ichabod-mother':['shiloh'],
 'joshua-beth-shemesh':['beth-shemesh'],'abinadab-ark':['kiriath-jearim'],'eleazar-ark':['kiriath-jearim'],
 'joel-samuel':['beersheba'],'abijah-samuel':['beersheba'],'kish':['gibeah'],
 'nahash':['jabesh-gilead'],'jonathan-armor-bearer':['michmash'],'ahijah-priest':['gibeah','michmash'],
 'ahinoam-saul':['gibeah'],'merab':['gibeah'],'michal':['gibeah'],'ishvi':['gibeah'],'malchishua':['gilboa'],
 'agag':['gilgal'],'jesse':['bethlehem','moab'],'eliab-david':['bethlehem','elah'],
 'abinadab-david':['bethlehem','elah'],'shammah':['bethlehem','elah'],'goliath':['gath','elah'],
 'adriel':[],'jonathan-boy':['gibeah'],'ahimelech-priest':['nob'],'doeg':['nob','gibeah'],
 'achish':['gath','aphek'],'gad':['moab'],'abiathar':['nob','keilah','ziklag'],
 'abigail':['maon','carmel-judah','gath','ziklag'],'nabal':['maon','carmel-judah'],
 'ahinoam-david':['gath','ziklag'],'palti':[],'abishai':['ziph'],'ahimelech-hittite':['ziph'],
 'endor-medium':['endor'],'egyptian-servant':['besor'],'abinadab-saul':['gilboa'],'saul-armor-bearer':['gilboa']}
aliases={'man-of-god':['man of God'],'ichabod-mother':['daughter-in-law'],
 'jonathan-armor-bearer':['armor bearer'],'saul-armor-bearer':['armor bearer'],
 'jonathan-boy':['boy'],'egyptian-servant':['Egyptian'],'endor-medium':['woman']}
for p in people:
 if p['id'] in locations:p['placeIds']=locations[p['id']]
 if p['id'] in aliases:p['linkNames']=aliases[p['id']]
routes[6]=['ekron','beth-shemesh']
chapters[5]['route']=routes[6]
finish(dict(id='1-samuel',bibleCode='1SA',name='1 Samuel',description='Hannah · Samuel · Saul · David · the rise of kingship',chapterCount=31,scripture=scripture('1-samuel','1SA',31),chapters=chapters,people=people,places=places,sources=sources,review=dict(date='2026-10-05',scope='Chapter studies and selected named and unnamed people. Same-name profiles remain distinct. Narrative, literary interpretation, and Church application use separate source records.',nextBook='2-samuel')))
