"""Ruth: loss, care, household security, and David's narrated ancestry."""
import json
from book_common import OUT,source,person,place,scripture,finish
rows=[
('Loss and the return to Bethlehem','Famine takes Elimelech’s household to Moab. After three deaths, Naomi returns. Ruth stays with her, while Orpah returns home.','Grief and chosen loyalty shape the opening. Orpah receives Naomi’s blessing. Her departure does not make her an enemy.','elimelech,naomi,mahlon,chilion,ruth,orpah','moab,bethlehem','The Church lesson studies faith through loss. Its application does not promise that every bereaved person will remarry.'),
('Ruth gleans in Boaz’s field','Ruth gathers leftover grain. Boaz provides protection, food, and additional grain. Naomi recognizes his connection with their family.','Gleaning means collecting grain left after harvest. The account makes safety, work, and practical care central to household survival.','ruth,naomi,boaz,harvest-supervisor,elimelech','bethlehem','Come, Follow Me studies kindness and trust. Consider how practical help changes the conditions another person faces.'),
('The request at the threshing floor','Naomi proposes a plan. Ruth approaches Boaz at night and asks for his protection. He promises action after consulting a nearer relative.','Ruth speaks directly about family redemption. Readers debate the scene’s implications. The text does not explicitly describe a sexual act.','ruth,naomi,boaz,nearer-redeemer','bethlehem','The older manual reads Ruth’s request as a marriage proposal. Keep that interpretation distinct from unstated details.'),
('The gate agreement and Obed’s birth','Boaz consults the nearer relative and witnesses at the gate. He marries Ruth. Obed is born, and the closing genealogy reaches David.','Public witnesses connect household care with recognized responsibility. The genealogy is the book’s claim about ancestry, not an independently verified record.','ruth,naomi,boaz,nearer-redeemer,obed,jesse,david,rachel,leah,tamar,judah,perez,hezron,ram,amminadab,nahshon,salmon,mahlon,chilion,elimelech','bethlehem','Come, Follow Me compares Ruth and Boaz with Jesus Christ. This Christian reading is separate from the ancient narrated transaction.')]
sources=[source('web','Ruth — World English Bible','https://ebible.org/engwebp/RUT01.htm','The public-domain reading text supplies all four chapters.','Scripture',limits='The text supplies the narrated actions and genealogy. It does not independently verify event years or personal appearance.')]
j=json.loads((OUT/'joshua.json').read_text(encoding='utf-8'))
sources.extend(dict(s) for s in j['sources'] if s['id'] in ['terrain','atlas','atlas-canaan'])
s=source('yale-ruth','The Book of Ruth, Part 2 · Yale Bible Study','https://yalebiblestudy.org/courses/ruth-song-of-songs-lamentations-and-esther/lessons/the-book-of-ruth-part-2-study-guide/','The study examines the women’s relationship, household survival, devotion, and uncertainty about the threshing-floor encounter.',limits='The published study guide was reviewed, not its video. Its final paragraph incorrectly contrasts Ruth with Boaz in the genealogy. Ruth 4:18–22 names Boaz; this guide follows the biblical text.')
s.update(author='Yale Bible Study · course presenters Joel S. Baden and Jacqueline Vayntrub',reviewed='2026-10-05: Published study guide and course presenter record reviewed.',chapterCoverage=[1,2,3,4]);sources.append(s)
s=source('scholar-schipper','Ruth: A New Translation with Introduction and Commentary','https://yalebooks.yale.edu/book/9780300216547/ruth/','The publisher describes Schipper’s study of relationships, household status, gender, and ethnicity in Ruth.',limits='The 2016 publisher description and author record were reviewed. The full commentary was not read.')
s.update(author='Jeremy Schipper',year=2016,reviewed='2026-10-05: Yale University Press edition and description reviewed.',chapterCoverage=[1,2,3,4]);sources.append(s)
s=source('dm-ruth','Ruth 2: Translation and Notes','https://danielomcclellan.wordpress.com/2010/05/05/ruth-2-translation-and-notes/','McClellan discusses Hebrew grammar and differences between Hebrew and Greek readings in Ruth 2, including the uncertain wording of verse 7.',limits='This is one scholar’s 2010 translation and notes. The guide retains the World English Bible reading and does not treat each proposed reconstruction as settled.',category='Scholar commentary')
s.update(author='Dan McClellan',year='May 5, 2010',group='mcclellan',reviewed='2026-10-05: Original translation and notes reviewed, particularly notes 1, 6, 10, and 16.',chapterCoverage=[2]);sources.append(s)
s=source('lds-ruth','Ruth 1–4 · Institute commentary','https://www.churchofjesuschrist.org/study/manual/old-testament-student-manual-genesis-2-samuel/judges-13-21-ruth-1-4-the-reign-of-the-judges-part-2?lang=eng','The manual explains gleaning, family redemption, the proposal, and the witnessed gate agreement.','LDS study manual','lds',limits='The Ruth sections of the 1980 manual were reviewed. Its historical explanations remain distinct from independent evidence. Boaz is a relative, not Mahlon’s stated brother.')
s.update(author='The Church of Jesus Christ of Latter-day Saints',year=1980,reviewed='2026-10-05: Sections 23-14–23-20 and the Ruth portion of 23-22 reviewed.',chapterCoverage=[1,2,3,4]);sources.append(s)
defs=[
('elimelech','Elimelech','Naomi’s husband','Father of Mahlon and Chilion.','Ruth 1; 4','His household moves during famine. His death begins the account’s family losses.'),
('naomi','Naomi','Widow who returns to Bethlehem','Mother-in-law of Ruth and Orpah.','Ruth 1–4','She expresses grief, advises Ruth, and receives Obed into her care. Her changing circumstances organize the account.'),
('mahlon','Mahlon','Naomi’s son and Ruth’s first husband','Brother of Chilion. Ruth 4:10 identifies Ruth as his widow.','Ruth 1; 4','His death leaves Ruth widowed. Boaz’s stated responsibility includes preserving his name.'),
('chilion','Chilion','Naomi’s son who dies in Moab','Brother of Mahlon. Orpah belongs to the household’s other marriage.','Ruth 1; 4','His death contributes to Naomi’s loss. The text gives little personal biography.'),
('ruth','Ruth','Moabite widow, worker, and mother of Obed','Daughter-in-law of Naomi. Wife of Mahlon, then Boaz.','Ruth 1–4','She chooses loyalty, works for food, and makes a direct request for family protection. Her foreign identity remains visible.'),
('orpah','Orpah','Widowed daughter-in-law who returns home','Related by marriage to Naomi’s household.','Ruth 1','She weeps and initially accompanies Naomi. Naomi blesses her before she returns. The guide does not invent later descendants.'),
('boaz','Boaz','Relative who provides protection and family redemption','From Elimelech’s family. Husband of Ruth and father of Obed.','Ruth 2–4','He makes concrete provision in the field and accepts responsibility before witnesses. He is not identified as Mahlon’s brother.'),
('harvest-supervisor','The harvest supervisor','Unnamed servant responsible for Boaz’s reapers','Reports Ruth’s work to Boaz.','Ruth 2:5–7','His report introduces Ruth to Boaz. His name and personal background are not supplied.'),
('nearer-redeemer','The nearer relative','Unnamed relative consulted before Boaz’s agreement','Has a prior family claim in the narrated transaction.','Ruth 3:12–13; 4:1–8','He first agrees to redeem land, then declines the combined responsibility. The text does not supply his name.'),
('obed','Obed','Child born to Ruth and Boaz','Grandfather of David through Jesse. Naomi cares for him.','Ruth 4:13–22','His birth changes the household’s future. He is not described as Naomi’s biological son.'),
('jesse','Jesse','Father of David in the genealogy','Son of Obed.','Ruth 4:17,22','He connects Obed with David in the narrated family line. The book gives no further life story.'),
('david','David','King named at the end of the genealogy','Son of Jesse.','Ruth 4:17,22','His name gives the family account a royal connection. He does not participate in Ruth’s earlier scenes.'),
('perez','Perez','Ancestor named in the blessing and genealogy','Son of Judah and Tamar.','Ruth 4:12,18','The witnesses recall his family, and the genealogy begins with him. His portrait represents an ancestor, not a gate attendee.'),
('hezron','Hezron','Ancestor in the closing genealogy','Named between Perez and Ram.','Ruth 4:18–19','His name links generations in the narrated genealogy. He does not attend the story’s earlier events.'),
('ram','Ram','Ancestor in the closing genealogy','Named between Hezron and Amminadab.','Ruth 4:19','The book supplies his genealogical place without an extended biography.'),
('amminadab','Amminadab','Ancestor in the closing genealogy','Father of Nahshon in the genealogy.','Ruth 4:19–20','His place in the family line does not put him at Boaz’s agreement.'),
('salmon','Salmon','Ancestor in the closing genealogy','Named as father of Boaz.','Ruth 4:20–21','The book supplies a family link, not a scene involving his life.')]
defs.append(('nahshon','Nahshon','Ancestor in the closing genealogy','Named between Amminadab and Salmon.','Ruth 4:20','The genealogy recalls an ancestral name. It does not place him in Ruth’s earlier scenes.'))
people=[person(*row) for row in defs]
for slug,ids in [('genesis',['rachel','leah','tamar','judah']),('numbers',['nahshon'])]:
 b=json.loads((OUT/(slug+'.json')).read_text(encoding='utf-8'))
 for p in b['people']:
  if p['id'] in ids:
   p=dict(p);p.update(passages='Ruth 4',placeIds=[],sourceIds=['web'],meaning='The account recalls this ancestral name in a blessing or genealogy. The portrait does not place the ancestor at the gate agreement.');people.append(p)
for p in people:
 p.setdefault('placeIds',['moab','bethlehem'] if p['id'] in ['ruth','naomi'] else ['moab'] if p['id'] in ['elimelech','mahlon','chilion','orpah'] else ['bethlehem'] if p['id'] in ['boaz','harvest-supervisor','nearer-redeemer','obed'] else [])
 p['linkNames']={'naomi':['Mara'],'harvest-supervisor':['servant who was set over the reapers'],'nearer-redeemer':['nearer kinsman']}.get(p['id'],[])
places=[place('moab','Moab · broad region',31.50,35.75,'The household’s destination during famine. Naomi and Ruth later leave this region.','Regional marker only. The family’s home and the journey’s exact path are unknown.',['web','atlas-canaan']),place('bethlehem','Bethlehem',31.705,35.202,'Naomi’s return town and the setting of Ruth’s work and marriage agreement.','Town locality only. Boaz’s field, threshing floor, and gate are not securely identified.',['web','atlas-canaan'])]
chapters=[]
for n,(title,summary,meaning,pids,locs,lds) in enumerate(rows,1):
 chapters.append(dict(chapter=n,title=title,summary=summary,meaning=meaning,people=pids.split(','),places=locs.split(','),sourceIds=['web','yale-ruth','scholar-schipper','atlas-canaan']+(['dm-ruth'] if n==2 else []),lds=dict(text=lds,sourceIds=['lds-ruth']),eventOrder=n,dateLabel='Chapter order · historical year uncertain',historicalNote='The story is set in the time of the judges. Its composition date and event dates are not established here.',mapNote='The map shows the named town and broad region. It does not identify private buildings or an ancient road.',route=['moab','bethlehem'] if n==1 else [],routeEvidence='The text names departure from Moab and arrival at Bethlehem. The line omits an unknown path around the Dead Sea.'))
finish(dict(id='ruth',bibleCode='RUT',name='Ruth',description='Loss · loyalty · gleaning · family redemption',chapterCount=4,scripture=scripture('ruth','RUT',4),chapters=chapters,people=people,places=places,sources=sources,review=dict(date='2026-10-05',scope='All four chapters, named people, two unnamed roles, and narrative geography. Genealogy and religious interpretation remain distinct from independent evidence.',nextBook='1-samuel')))
