"""Build First Thessalonians from reviewed Scripture and original context."""
import json,copy,sys
from book_common import ROOT,OUT,scripture,source,person,place,finish
DATE='2026-10-07';t=scripture('1-thessalonians','1TH',5)
assert [len(t[str(n)]) for n in range(1,6)]==[10,20,13,18,28]
assert sum(map(len,t.values()))==89
assert not any('\ufffd' in str(v) for vv in t.values() for v in vv)
notes=json.loads((ROOT/'scripts/book-context-complete/1-thessalonians.json').read_text(encoding='utf8'));sources=[]
s=source('web','First Thessalonians · World English Bible','https://ebible.org/engwebp/1TH01.htm','All five chapters supply the primary text for original close readings.','Scripture','historical','Dates, original manuscripts, Greek forms, the blocked visits\x27 exact cause, and a complete harmony with Acts were not independently verified. The accusations in chapter two remain part of the letter\x27s conflict rather than independent evidence against all Jewish people. No return date is assigned.')
s.update(author='World English Bible translators',publisher='eBible.org',chapterCoverage=[1,2,3,4,5],reviewed=dict(date=DATE,scope='All 89 verses read for five original contextual explanations and exact selections. Surroundings, counts, and character integrity checked.'));sources.append(s)
s=source('carr-thessalonians','Commentary on 1 Thessalonians 2:1-8','https://www.workingpreacher.org/commentaries/revised-common-lectionary/ordinary-30/commentary-on-1-thessalonians-21-8-6','Carr reads the remembered conduct as a defense of the teachers\x27 trustworthiness.','Scholarly study','historical','This is Carr\x27s interpretation. His Greek analysis, manuscript preference for infants, ancient teacher comparisons, and cited books were not independently verified. The selected WEB wording remains unchanged.')
s.update(author='David Carr',publisher='Luther Seminary',year=2023,chapterCoverage=[2],reviewed=dict(date=DATE,scope='Complete commentary body and notes read. The guide attributes his reading of remembered conduct and trustworthiness.'));sources.append(s)
s=source('cfm-nt-2023-43','October 16–22 · First and Second Thessalonians','https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-sunday-school-new-testament-2023/43?lang=eng','The lesson studies sincere teaching, growing holiness, and useful work.','LDS Come, Follow Me','lds','First Thessalonians coverage follows actual discussion of chapters one through four. The lesson does not independently discuss chapter five. Linked hymns, talks, and Restoration passages were not independently reviewed.')
s.update(author='The Church of Jesus Christ of Latter-day Saints',publisher='The Church of Jesus Christ of Latter-day Saints',year=2023,chapterCoverage=[1,2,3,4],reviewed=dict(date=DATE,scope='Complete lesson body and included resource list read. Its Second Thessalonians sections were also read, but support only that book\x27s separate lesson references.'));sources.append(s)
s=source('net-thessalonica','NET Bible · Thessalonica','https://classic.net.bible.org/dictionary.php?word=Thessalonica','The dictionary identifies the city on the Thermaic Gulf and supplies coordinates.','Reference work','historical','Only the opening locality description and coordinate line support the marker. Old population figures, wider historical claims, inscriptions, exact buildings, and routes were not independently verified.')
s.update(author='NET Bible reference editors',publisher='Bible.org',reviewed=dict(date=DATE,scope='Opening location description and coordinate line read: 40 degrees 37 minutes north, 22 degrees 55 minutes east. Only the city reference is used.'));sources.append(s)
acts=json.loads((OUT/'acts.json').read_text(encoding='utf8'));sources.extend(copy.deepcopy([s for s in acts['sources'] if s['id'] in ['atlas-canaan','net-acts-map']]))
rows=[('paul','Paul','Letter speaker who recalls shared work and longs to visit the hearers','Silvanus and Timothy share the opening greeting, and Timothy returns with news.','First Thessalonians 1–5','His need for comfort makes the hearers\x27 faith part of a relationship of shared support.'),('silas','Silvanus','Worker named beside Paul and Timothy in the opening greeting','The shared greeting introduces the letter\x27s repeated account of the teachers\x27 work.','First Thessalonians 1:1','His named place keeps the appeal connected with a team rather than a solitary teacher.'),('timothy','Timothy','Worker sent to strengthen the hearers and bring news of their faith','He returns with good news that comforts the teachers in their own distress.','First Thessalonians 1:1; 3:2–6','His visit connects separation with personal care and renewed confidence.'),('jesus','Jesus Christ','Risen Lord whose coming gives the hearers hope for themselves and the dead','The teachers connect faithful conduct and continued waiting with him.','First Thessalonians 1–5','His death and resurrection supply the basis for shared comfort rather than a calculated date.')]
people=[];pc={'paul':[1,2,3,4,5],'silas':[1],'timothy':[1,3],'jesus':[1,2,3,4,5]}
for pid,name,role,relations,passages,meaning in rows:
 p=person(pid,name,role,relations,passages,meaning);p.update(placeIds=[],linkNames=['Jesus','Christ'] if pid=='jesus' else [name],verseScope={});people.append(p)
places=[place('thessalonica','Thessalonica',40+37/60,22+55/60,'Thessalonica identifies the assembly addressed in the opening greeting.','City reference rather than an exact meeting house.',['web','net-thessalonica'])]+copy.deepcopy([p for p in acts['places'] if p['id'] in ['philippi','athens']])
for p in places:
 p.update(verseScope={},linkNames=['Thessalonians'] if p['id']=='thessalonica' else [p['name']])
 if p['id']=='philippi':p['summary']='Philippi is recalled as the place of earlier suffering before the teachers\x27 visit.'
 if p['id']=='athens':p['summary']='Athens is the place from which Timothy is sent to strengthen the hearers.'
summaries=['Received faith amid suffering becomes an example to others.','Remembered care and work support trust during continued separation.','Timothy\x27s good report gives comfort and leads into renewed prayer.','Careful conduct and resurrection hope support daily work and shared comfort.','Waiting for an unknown day requires alert conduct and care for different needs.']
questions=['How does receiving the message amid suffering become an example to others?','Why does Paul ask the hearers to remember the teachers\x27 own conduct?','How does Timothy\x27s report give comfort to the teachers as well as the hearers?','Why does the account of the dead end with shared comfort?','How do different needs require different kinds of care?'];teach={1:'The selected Church lesson teaches sincere sharing through a faithful personal example.',2:'The selected Church lesson teaches sharing the gospel with sincerity and love.',3:'The selected Church lesson connects increased love with growing holiness.',4:'The selected Church lesson teaches gradual growth in holiness and work that supports others.'};chapters=[]
for n,v,title,meaning in notes:
 loc=['thessalonica'] if n==1 else ['philippi'] if n==2 else ['athens'] if n==3 else []
 chapters.append(dict(chapter=n,title=title,summary=summaries[n-1],meaning=meaning,people=[pid for pid,cc in pc.items() if n in cc],places=loc,sourceIds=['web']+(['carr-thessalonians'] if n==2 else []),lds=dict(text=teach.get(n,'')+(' ' if n in teach else '')+'Study question. '+questions[n-1],sourceIds=['cfm-nt-2023-43'] if n in teach else []),eventOrder=n,dateLabel='Book order',historicalNote=meaning,mapNote='Markers identify the addressed city and named places in the teachers\x27 remembered work.',route=[],routeEvidence='The letter does not supply an exact travel route or a complete sequence of visits.'))
data=dict(id='1-thessalonians',bibleCode='1TH',name='1 Thessalonians',description='Shared work · remembered care · waiting · resurrection hope · alert conduct',chapterCount=5,scripture=t,chapters=chapters,people=people,places=places,sources=sources,review=dict(date=DATE,contextReviewDate=DATE,copyReviewDate=DATE,scope='All 89 verses read for five original contextual explanations and exact selections. Four selected profiles and three city references do not claim exhaustive coverage. Church lesson coverage follows actual discussion. Carr\x27s interpretation remains attributed. NET locality and coordinates support Thessalonica. Dates, original manuscripts, Greek forms, exact causes of blocked visits, and complete harmony with Acts were not independently verified.',nextBook='2-thessalonians'))
if '--ready' in sys.argv:
 art={}
 for book,ids in [('acts',['paul','silas']),('matthew',['jesus']),('romans',['timothy'])]:
  a=json.loads((OUT/(book+'-art.json')).read_text(encoding='utf8'));art.update({pid:a[pid] for pid in ids})
 (OUT/'1-thessalonians-art.json').write_text(json.dumps(art,ensure_ascii=False,indent=2)+'\n',encoding='utf8');finish(data)
else:(ROOT/'review/1-thessalonians-draft.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
