"""Build John from reviewed complete Scripture and persistent close readings."""
import json,sys,copy
from book_common import ROOT,OUT,scripture,source,person,place,finish
DATE='2026-10-07';t=scripture('john','JHN',21)
assert [len(t[str(n)]) for n in range(1,22)]==[51,25,36,54,47,71,53,59,41,42,57,50,38,31,27,33,26,40,42,31,25]
assert sum(map(len,t.values()))==879
assert not any('\ufffd' in v['text'] for vv in t.values() for v in vv)
notes=json.loads((ROOT/'scripts/book-context-complete/john.json').read_text(encoding='utf8'))
base=json.loads((OUT/'matthew.json').read_text(encoding='utf8'));mark=json.loads((OUT/'mark.json').read_text(encoding='utf8'))
sources=[]
s=source('web','John · World English Bible','https://ebible.org/engwebp/JHN01.htm','All 21 chapters appear in the reading text.','Scripture','historical','Close reading does not establish every event, date, or traditional identity. The publisher retains John 7:53–8:11 and notes textual uncertainty.')
s.update(author='World English Bible translators',publisher='eBible.org',chapterCoverage=list(range(1,22)),reviewed=dict(date=DATE,scope='All 879 verses read with every selected passage’s surrounding chapter. Publisher notes at John 8:11 read. Verse counts and character integrity checked.'));sources.append(s)
s=source('scott-john','Commentary on John 9:1-41','https://www.workingpreacher.org/commentaries/narrative-lectionary/the-man-born-blind/commentary-on-john-91-41-8','Scott discusses blame, disability, the healed man’s testimony, and translation choices.','Scholarly study','historical','This is Scott’s interpretation. Greek manuscripts and the separately cited Brant and Black books were not reviewed. The guide retains the WEB text.')
s.update(author='Lindsey Scott',publisher='Luther Seminary',year=2022,chapterCoverage=[9],reviewed=dict(date=DATE,scope='Complete commentary and notes read. Linked material, cited books, related commentaries, and podcast were not reviewed. Broad ancient social generalizations were not independently verified.'));sources.append(s)
lessons=[(4,[1],'January 16–22 · John 1','The lesson studies Christ before birth, light, and inviting others to come and see.'),(7,[2,3,4],'February 6–12 · John 2–4','The lesson studies signs, spiritual rebirth, and living water.'),(24,[14,15,16,17],'June 5–11 · John 14–17','The lesson teaches help from the Holy Spirit, remaining in Christ, and unity.'),(27,[20,21],'June 26–July 2 · Matthew 28; Mark 16; Luke 24; John 20–21','The lesson teaches resurrection and the call to feed Christ’s sheep.')]
for number,coverage,title,summary in lessons:
 s=source('cfm-nt-2023-'+str(number),title,f'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-sunday-school-new-testament-2023/{number:02}?lang=eng',summary,'LDS Come, Follow Me','lds','This is selected Church teaching. Other chapter headings and linked resources receive no automatic coverage.')
 s.update(author='The Church of Jesus Christ of Latter-day Saints',publisher='The Church of Jesus Christ of Latter-day Saints',year=2023,chapterCoverage=coverage,reviewed=dict(date=DATE,scope='Complete lesson body and additional resources read. Linked talks, videos, dictionary articles, and other editions were not separately reviewed. Only listed John chapters receive teaching coverage.'));sources.append(s)
for s in copy.deepcopy([s for s in mark['sources'] if s['id'] in ['net-nt-map','atlas-canaan']]):
 if s['id']=='net-nt-map':s['reviewed']['scope']+=' Cana and Sychar opening descriptions and coordinate lines checked. Their markers are broad reference areas, not verified ruins or a well.'
 sources.append(s)
people=copy.deepcopy([p for p in base['people'] if p['id']!='joseph-mary'])
details={
 'jesus':('Person presented as the Word made flesh and the Son of God','His mother and brothers appear in the account. The beloved disciple receives care for his mother.','John 1–21','Signs and words lead toward his death, resurrection, and the task of testimony.'),
 'mary-mother':('Mother present at the wedding and cross','The account does not give her personal name. Jesus joins her care with the beloved disciple.','John 2:1–12; 19:25–27','Her request at the wedding and presence at the cross connect need with continued care.'),
 'john-baptizer':('Witness who directs his own followers toward Jesus','His disciples question the growth of Jesus’ following.','John 1; 3:23–30; 4:1; 5:33–36; 10:40–41','He refuses the Christ title and describes joy when Jesus increases.'),
 'peter':('Disciple who confesses, resists washing, denies, and receives a renewed task','Andrew is his brother. John names his father as Jonah.','John 1; 6; 13; 18; 20–21','Three questions about love connect his renewed following with feeding the flock.'),
 'mary-magdalene':('Witness at the cross who reports seeing the risen Jesus','John distinguishes her from Jesus’ mother, Mary of Clopas, and Mary of Bethany.','John 19:25; 20:1–18','Hearing her name changes her mistaken recognition and leads to her testimony.')}
profileChapters={'jesus':list(range(1,22)),'mary-mother':[2,19],'john-baptizer':[1,3,4,5,10],'peter':[1,6,13,18,20,21],'mary-magdalene':[19,20],'nicodemus':[3,7,19],'thomas':[11,14,20,21],'martha':[11,12],'mary-bethany':[11,12],'lazarus':[11,12]}
for p in people:
 p['role'],p['relations'],p['passages'],p['meaning']=details[p['id']];p['placeIds']=[];p['verseScope']={}
 if p['id']=='mary-mother':p['linkNames']=[];p['verseScope']={'19':[25,26,27]}
 if p['id']=='john-baptizer':p['linkNames']=['John'];p['verseScope']={str(n):[v['verse'] for v in t[str(n)] if 'John' in v['text']] for n in profileChapters['john-baptizer']}
 if p['id']=='peter':p['verseScope']={str(n):[v['verse'] for v in t[str(n)] if 'Peter' in v['text']] for n in profileChapters['peter']}
 if p['id']=='mary-magdalene':p['linkNames']=['Mary Magdalene'];p['verseScope']={'19':[25],'20':[1,11,16,18]}
for pid,name,role,relations,passages,meaning,links in [
 ('nicodemus','Nicodemus','Teacher and council member who visits Jesus at night','He later requests a lawful hearing and brings spices for burial.','John 3; 7:50–52; 19:39','His appearances move from questions toward a hearing request and public burial care.',['Nicodemus']),
 ('thomas','Thomas','Disciple who asks questions and later confesses Jesus as Lord and God','John also calls him Didymus. He joins the later fishing group.','John 11:16; 14:5; 20:24–29; 21:2','His absence from one appearance makes another encounter address the problem of unseen testimony.',['Thomas','Didymus']),
 ('martha','Martha of Bethany','Woman who confesses Jesus as the Christ before Lazarus leaves the tomb','Mary is her sister, and Lazarus is her brother.','John 11; 12:2','Her confession remains beside grief and a practical objection about the body after four days.',['Martha']),
 ('mary-bethany','Mary of Bethany','Woman who mourns her brother and later anoints Jesus','Martha is her sister, and Lazarus is her brother. She is not Mary Magdalene.','John 11–12','Her tears and costly gift place grief and preparation for burial beside restored life.',['Mary']),
 ('lazarus','Lazarus of Bethany','Man whom Jesus calls from the tomb','Martha and Mary are his sisters. He later shares the meal at Bethany.','John 11–12','His restored life brings both belief and another plan for killing. He is not Luke’s story character.',['Lazarus'])]:
 p=person(pid,name,role,relations,passages,meaning);p.update(placeIds=[],linkNames=links,verseScope={});people.append(p)
next(p for p in people if p['id']=='mary-bethany')['verseScope']={str(n):[v['verse'] for v in t[str(n)] if 'Mary' in v['text']] for n in [11,12]}
placeText={'jerusalem':'Jerusalem holds feast disputes, final conflict, and the burial and appearance setting.','jordan':'Beyond the Jordan holds John’s early witness and Jesus’ later withdrawal.','galilee':'Galilee holds early signs and the final shared meal by the lake.','nazareth':'Nazareth appears in identity questions and the execution title.','capernaum':'Capernaum holds the bread teaching and the official’s sick son.','bethsaida':'Bethsaida identifies the origins of Andrew, Peter, and Philip.','bethlehem':'Bethlehem appears in the crowd’s disputed claim about the Christ’s origin.','olives':'The Mount of Olives appears in the retained opening of chapter eight.','bethany':'Bethany near Jerusalem holds Lazarus’ home and the anointing meal.','sea-galilee':'The Sea of Galilee, also called Tiberias, holds crossings and the final fishing scene.'}
places=[]
for p in base['places']+mark['places']:
 if p['id'] in placeText and not any(q['id']==p['id'] for q in places):
  q=copy.deepcopy(p);q.update(summary=placeText[p['id']],verseScope={});places.append(q)
next(p for p in places if p['id']=='bethany')['verseScope']={'1':[],'10':[],'11':[1,18],'12':[1]}
places.extend([place('cana','Cana of Galilee · vicinity',32+44/60,35+20/60,'Cana holds the wedding sign and the official’s request. It also names Nathanael’s hometown.','Broad NET reference vicinity. Competing site claims remain unresolved. No wedding house receives a fixed point.',['web','net-nt-map']),place('sychar','Sychar · vicinity',32.2,35.3,'The well conversation occurs near Sychar in Samaria.','Broad NET reference vicinity. The marker does not identify an ancient ruin or authenticate the well.',['web','net-nt-map'])])
locs={1:['jerusalem','jordan','galilee','bethsaida','nazareth'],2:['cana','galilee','capernaum','jerusalem'],3:['jordan'],4:['galilee','sychar','jerusalem','cana','capernaum'],5:['jerusalem'],6:['sea-galilee','capernaum'],7:['galilee','jerusalem','bethlehem'],8:['olives','jerusalem'],9:['jerusalem'],10:['jerusalem','jordan'],11:['bethany','jerusalem'],12:['bethany','jerusalem','bethsaida'],18:['jerusalem','nazareth'],19:['jerusalem','nazareth'],20:['jerusalem'],21:['sea-galilee','galilee','cana']}
summaries=['The Word and John’s witness lead to invitations and first encounters.','A wedding sign leads to temple conflict and a misunderstood saying.','Nicodemus asks about new birth. John explains joy in another’s increase.','The well conversation brings a town’s response before an official trusts a healing promise.','A healing leads to Sabbath conflict and teaching about life and testimony.','A meal leads to bread teaching, disagreement, departures, and Peter’s reply.','A feast visit divides hearers and stops an attempted arrest.','Accusers leave a woman before arguments about light, freedom, and ancestry.','A healed man answers repeated questions before exclusion and another encounter with Jesus.','Shepherd images lead to disputes about identity and belief beyond the Jordan.','Lazarus leaves the tomb, while the council plans Jesus’ death.','An anointing and royal welcome lead to the dying seed image.','Jesus washes feet before betrayal, a love command, and Peter’s promised denial.','Questions about the way and the Father meet promises of teaching and peace.','The vine image connects continued belonging with fruit, love, and testimony.','Warnings and promised guidance lead to grief, joy, and predicted scattering.','Jesus prays for protection, truth, unity, and future believers.','Arrest and Peter’s denials lead to Pilate’s questions about kingship.','Pilate hands Jesus over. Execution, witnesses, and burial care follow.','Mary reports seeing Jesus. Gathered disciples and Thomas receive later appearances.','Fishing leads to shared breakfast, Peter’s renewed task, and a corrected rumor.']
questions=['Why does John direct his own followers toward another person?','How does later remembrance change the meaning of the temple saying?','How does John’s bridegroom comparison answer his disciples’ concern about losing followers?','How does the town’s own hearing develop the woman’s invitation?','What prevents the man from reaching the water before Jesus speaks?','Why does Peter remain when other disciples leave after the same teaching?','How does Nicodemus’ hearing request challenge the proposed judgment?','How does claimed ancestry differ from the conduct Jesus names?','What remains consistent in the man’s answers as the questions repeat?','What distinguishes the shepherd from the hired worker when danger comes?','How does restored life become a reason for the council’s death plan?','How does the dying seed change expectations about the announced hour?','Why does Jesus keep the titles Teacher and Lord while washing feet?','How will remembered words connect the promised Spirit with Jesus’ earlier teaching?','Why does the branch need to remain joined even when it already bears fruit?','How does the scattering warning qualify the disciples’ new confidence?','Why does protection leave the followers within the world rather than remove them?','How does Jesus’ answer about fighting explain his kingdom to Pilate?','How does care for his mother stand beside the statement of completed work?','How does the account’s stated purpose address readers who have not seen these signs?','How does the final correction distinguish a conditional saying from a certain prediction?']
ldsTeach={1:'The selected lesson studies light and inviting others to come and see.',2:'The selected lesson studies the wedding sign and care for sacred places.',3:'The selected lesson teaches spiritual rebirth through Christ.',4:'The selected lesson reads living water through spiritual needs and growing testimony.',14:'The selected lesson teaches the Holy Spirit’s help through teaching and remembrance.',15:'The selected lesson connects remaining in Christ with fruit and joy.',16:'The selected lesson teaches guidance from the Holy Spirit.',17:'The selected lesson studies unity with the Father and among followers.',20:'The selected lesson teaches resurrection through the Gospel accounts.',21:'The selected lesson connects love for Christ with feeding his sheep.'}
ldsSources={c:['cfm-nt-2023-'+str(number)] for number,coverage,_,_ in lessons for c in coverage}
chapters=[]
for n,v,title,meaning in notes:
 loc=locs.get(n,[])
 chapters.append(dict(chapter=n,title=title,summary=summaries[n-1],meaning=meaning,people=[pid for pid,cc in profileChapters.items() if n in cc],places=loc,sourceIds=['web']+(['scott-john'] if n==9 else []),lds=dict(text=ldsTeach.get(n,'')+(' ' if n in ldsTeach else '')+'Study question. '+questions[n-1],sourceIds=ldsSources.get(n,[])),eventOrder=n,dateLabel='Book order',historicalNote=meaning,mapNote='Selected markers distinguish events from quoted origins and remembered places. Bethany beyond the Jordan is separate from Bethany near Jerusalem. Exact gardens, pools, houses, and routes remain unassigned.' if loc else 'This chapter has no selected place markers. Speech images do not establish an exact teaching location.',route=[],routeEvidence='Reference markers do not verify events or reconstruct exact routes.'))
data=dict(id='john',bibleCode='JHN',name='John',description='Signs · testimony · life · love · cross · resurrection',chapterCount=21,scripture=t,chapters=chapters,people=people,places=places,sources=sources,review=dict(date=DATE,contextReviewDate=DATE,copyReviewDate=DATE,scope='All 879 WEB verses read for 21 original explanations and exact selections. Ten selected profiles distinguish the Marys and story Lazarus. Four selected Church lessons retain actual coverage. Scott’s translation discussion remains attributed. The beloved disciple is not assigned a traditional name. No original manuscripts, authorship determination, exact dates, pools, gardens, routes, or original language alignment were verified.',nextBook='acts'))
if '--ready' in sys.argv:finish(data)
else:(ROOT/'review/john-draft.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
