"""Build Colossians from reviewed Scripture and original contextual notes."""
import json,sys
from book_common import ROOT,OUT,scripture,source,person,place,finish
DATE='2026-10-07';t=scripture('colossians','COL',4)
assert [len(t[str(n)]) for n in range(1,5)]==[29,23,25,18]
assert sum(map(len,t.values()))==95
assert not any('\ufffd' in str(v) for vv in t.values() for v in vv)
notes=json.loads((ROOT/'scripts/book-context-complete/colossians.json').read_text(encoding='utf8'));sources=[]
s=source('web','Colossians · World English Bible','https://ebible.org/engwebp/COL01.htm','All four chapters supply the primary text for original close readings.','Scripture','historical','The letter names Paul as its speaker. Authorship, date, prison city, original manuscripts, Greek forms, and the exact rival teaching were not independently verified. Jesus called Justus is not linked to Jesus Christ. Household commands do not establish that unequal conditions disappeared.')
s.update(author='World English Bible translators',publisher='eBible.org',chapterCoverage=[1,2,3,4],reviewed=dict(date=DATE,scope='All 95 verses read for four original contextual explanations and exact selections. Surroundings, counts, and character integrity checked.'));sources.append(s)
s=source('carlson-colossians','Commentary on Colossians 3:1-11','https://www.workingpreacher.org/commentaries/revised-common-lectionary/ordinary-18-3/commentary-on-colossians-31-11-3','Carlson connects received new identity with changed conduct.','Scholarly study','historical','This is Carlson\x27s interpretation. His Greek analysis, proposed links with other letters, and account of the barbarian and Scythian pair were not independently verified. Linked works were not reviewed.')
s.update(author='Richard Carlson',publisher='Luther Seminary',year=2013,chapterCoverage=[3],reviewed=dict(date=DATE,scope='Complete commentary body read. The guide attributes his connection between received identity and changed conduct.'));sources.append(s)
s=source('cfm-nt-2023-42','October 9–15 · Philippians; Colossians','https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-sunday-school-new-testament-2023/42?lang=eng','The lesson studies changed conduct and being rooted in Christ.','LDS Come, Follow Me','lds','Colossians coverage follows actual discussion of chapters one through three. The lesson does not independently discuss chapter four. Linked talks, videos, and Restoration passages were not independently reviewed.')
s.update(author='The Church of Jesus Christ of Latter-day Saints',publisher='The Church of Jesus Christ of Latter-day Saints',year=2023,chapterCoverage=[1,2,3],reviewed=dict(date=DATE,scope='Complete lesson body read, including its Philippians sections. Only Colossians one through three support this book\x27s lesson references.'));sources.append(s)
for pid,name in [('colossae','Colossae'),('laodicea','Laodicea'),('hierapolis','Hierapolis')]:
 url='https://classic.net.bible.org/dictionary.php?word='+name if pid!='colossae' else 'https://classic.net.bible.org/dictionary.php/xml/xml/dictionary.php?word=Colossae'
 s=source('net-'+pid,'NET Bible · '+name,url,'The dictionary supplies a general city reference and a coordinate line.','Reference work','historical','Only the opening location description and coordinate line support this marker. Historical dictionary claims, exact buildings, and delivery routes were not independently verified.')
 s.update(author='NET Bible reference editors',publisher='Bible.org',reviewed=dict(date=DATE,scope='Opening locality description and published coordinate line read. Only the city reference is used.'));sources.append(s)
rows=[('paul','Paul','Named letter speaker who describes costly work and imprisonment','Timothy shares the opening greeting, and messengers carry news of his condition.','Colossians 1:1, 23–29; 2:1; 4:3, 18','His appeal depends on prayer and personal help as well as written instruction.'),('jesus','Jesus Christ','Lord described as creation\x27s center and the assembly\x27s head','The hearers\x27 changed belonging and conduct are measured through him.','Colossians 1–4','His place above every power answers competing claims to wisdom and acceptance.'),('timothy','Timothy','Brother who shares the opening greeting with Paul','The letter names him beside Paul before addressing the hearers.','Colossians 1:1','His presence places the message within shared work rather than a solitary voice.'),('tychicus','Tychicus','Trusted messenger sent to explain the speaker\x27s condition','He travels with Onesimus to bring news and comfort.','Colossians 4:7–9','His personal report joins written instruction with care for the hearers.'),('epaphras','Epaphras','Teacher whose report and prayers connect the hearers with the speaker','He has concern for Colossae, Laodicea, and Hierapolis.','Colossians 1:7–8; 4:12–13','His teaching and prayer connect faith\x27s beginning with continued growth.'),('onesimus','Onesimus','Faithful brother who joins Tychicus in carrying news','The letter describes him as one of the hearers.','Colossians 4:9','His named belonging joins personal recognition with the wider message of shared life.')]
people=[];pc={'paul':[1,2,4],'jesus':[1,2,3,4],'timothy':[1],'tychicus':[4],'epaphras':[1,4],'onesimus':[4]}
for pid,name,role,relations,passages,meaning in rows:
 p=person(pid,name,role,relations,passages,meaning);p.update(placeIds=[],linkNames=['Jesus','Christ'] if pid=='jesus' else [name],verseScope={'4':[3,12]} if pid=='jesus' else {});people.append(p)
places=[place('colossae','Colossae',37+46/60,29+15/60,'Colossae is named as the recipients\x27 city in the opening address.','City reference rather than an exact meeting house.',['web','net-colossae']),place('laodicea','Laodicea',37+46/60,29+3/60,'Laodicea shares the speaker\x27s concern and the request for exchanged letters.','City reference rather than an exact meeting house.',['web','net-laodicea']),place('hierapolis','Hierapolis',37+55/60,29+7/60,'Hierapolis is named among the places for which Epaphras has concern.','City reference rather than an exact assembly location.',['web','net-hierapolis'])]
for p in places:p.update(verseScope={},linkNames=[p['name']])
summaries=['Received hope and Christ\x27s place above every power support the hearers\x27 growth.','Rooted belonging through Christ answers competing demands for wisdom and acceptance.','New life shapes speech, shared care, and household commands within unequal roles.','Prayer, messengers, greetings, and exchanged letters connect neighboring assemblies.']
questions=['Why does the account of Christ\x27s place support the hearers\x27 received hope?','How does holding the head differ from depending on added rules?','How does seeking what is above change conduct toward earthly neighbors?','Why do personal messengers matter beside the request to exchange letters?'];teach={1:'The selected Church lesson studies faith strengthened through Christ\x27s saving work.',2:'The selected Church lesson teaches remaining rooted in Christ against deceptive influences.',3:'The selected Church lesson teaches putting away former conduct and practicing shared care.'};chapters=[]
for n,v,title,meaning in notes:
 loc=['colossae'] if n==1 else ['laodicea'] if n==2 else ['laodicea','hierapolis'] if n==4 else []
 chapters.append(dict(chapter=n,title=title,summary=summaries[n-1],meaning=meaning,people=[pid for pid,cc in pc.items() if n in cc],places=loc,sourceIds=['web']+(['carlson-colossians'] if n==3 else []),lds=dict(text=teach.get(n,'')+(' ' if n in teach else '')+'Study question. '+questions[n-1],sourceIds=['cfm-nt-2023-42'] if n in teach else []),eventOrder=n,dateLabel='Book order',historicalNote=meaning,mapNote='Markers identify named cities rather than exact homes or a prison setting.',route=[],routeEvidence='Named messengers do not establish an exact delivery route.'))
data=dict(id='colossians',bibleCode='COL',name='Colossians',description='Christ\x27s fullness · received life · changed conduct · shared letters',chapterCount=4,scripture=t,chapters=chapters,people=people,places=places,sources=sources,review=dict(date=DATE,contextReviewDate=DATE,copyReviewDate=DATE,scope='All 95 verses read for four original contextual explanations and exact selections. Six selected profiles and three city references do not claim exhaustive coverage. Church lesson coverage follows actual discussion. Carlson\x27s interpretation remains attributed. NET locality descriptions and coordinate lines were checked for three city references. Authorship, dates, original manuscripts, Greek forms, rival identities, and exact prison setting were not independently verified.',nextBook='1-thessalonians'))
if '--ready' in sys.argv:finish(data)
else:(ROOT/'review/colossians-draft.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
