"""Build Second Thessalonians from reviewed Scripture and original context."""
import json,copy,sys
from book_common import ROOT,OUT,scripture,source,person,finish
DATE='2026-10-07';slug='2-thessalonians';t=scripture(slug,'2TH',3)
assert [len(t[str(n)]) for n in range(1,4)]==[12,17,18]
assert sum(map(len,t.values()))==47
assert not any('\ufffd' in str(v) for vv in t.values() for v in vv)
notes=json.loads((ROOT/'scripts/book-context-complete/2-thessalonians.json').read_text(encoding='utf8'));sources=[]
s=source('web','Second Thessalonians · World English Bible','https://ebible.org/engwebp/2TH01.htm','All three chapters supply the primary text for original close readings.','Scripture','historical','The letter names Paul as its speaker. Authorship, dates, original manuscripts, Greek forms, the lawless figure\x27s identity, the restraining force, and the cause of refused work were not independently verified. No present person or event is assigned to the predicted sequence.')
s.update(author='World English Bible translators',publisher='eBible.org',chapterCoverage=[1,2,3],reviewed=dict(date=DATE,scope='All 47 verses read for three original contextual explanations and exact selections. Surroundings, counts, and character integrity checked.'));sources.append(s)
s=source('wyant-thessalonians','Commentary on 2 Thessalonians 3:6-13','https://www.workingpreacher.org/commentaries/revised-common-lectionary/ordinary-33-3/commentary-on-2-thessalonians-36-13-5','Wyant reads the work commands within the group\x27s problem of irresponsible conduct.','Scholarly study','historical','This is Wyant\x27s interpretation. Her proposed identities of the busybodies remain alternatives. Greek analysis, ancient military usage, the Didache, and the linked news report were not independently reviewed.')
s.update(author='Jennifer S. Wyant',publisher='Luther Seminary',year=2022,chapterCoverage=[3],reviewed=dict(date=DATE,scope='Complete commentary body and notes read. The guide attributes her reading of irresponsible work and interference within the group.'));sources.append(s)
first=json.loads((OUT/'1-thessalonians.json').read_text(encoding='utf8'))
s=copy.deepcopy(next(s for s in first['sources'] if s['id']=='cfm-nt-2023-43'));s.update(summary='The lesson studies work and a falling away before Christ\x27s return.',chapterCoverage=[2,3],limits='Second Thessalonians coverage follows actual discussion of chapters two and three. Its application to the Great Apostasy remains Church teaching rather than independent historical evidence. Linked Restoration passages were not independently reviewed.',reviewed=dict(date=DATE,scope='Complete lesson body and resource list read. Its Second Thessalonians sections discuss falling away and useful work.'));sources.append(s)
sources.append(copy.deepcopy(next(s for s in first['sources'] if s['id']=='net-thessalonica')))
rows=[('paul','Paul','Named letter speaker who asks for prayer and recalls the teachers\x27 example','Silvanus and Timothy share the opening greeting.','Second Thessalonians 1:1; 2:5; 3:1–18','His handwritten greeting answers concern about messages falsely claiming the teachers\x27 authority.'),('silas','Silvanus','Worker named beside Paul and Timothy in the shared greeting','The greeting introduces a repeated appeal from the teachers to the hearers.','Second Thessalonians 1:1','His named presence keeps the message connected with shared work.'),('timothy','Timothy','Worker named beside Paul and Silvanus in the shared greeting','The greeting introduces the teachers\x27 praise, instruction, and requests for prayer.','Second Thessalonians 1:1','His named presence keeps the message connected with shared work.'),('jesus','Jesus Christ','Lord whose coming brings judgment, relief, and the defeat of deception','The teachers connect patient work and received comfort with him.','Second Thessalonians 1–3','His promised coming answers alarm without supplying a calculated date.')]
people=[]
for pid,name,role,relations,passages,meaning in rows:
 p=person(pid,name,role,relations,passages,meaning);p.update(placeIds=[],linkNames=['Jesus','Christ'] if pid=='jesus' else [name],verseScope={});people.append(p)
places=copy.deepcopy([p for p in first['places'] if p['id']=='thessalonica'])
summaries=['Growing faith and love amid suffering lead into promised relief and prayer.','Received teaching answers an alarming claim about the Lord\x27s coming.','Prayer and remembered labor lead into correction that still recognizes a brother.']
questions=['Why does promised relief lead into prayer for continued good work?','Why can a message claimed to come from the teachers still require testing?','How does treating the person as a brother limit the aim of separation?'];teach={2:'The selected Church lesson applies falling away to the Great Apostasy before Christ\x27s return.',3:'The selected Church lesson teaches useful work for oneself and people in need.'};chapters=[]
for n,v,title,meaning in notes:
 chapters.append(dict(chapter=n,title=title,summary=summaries[n-1],meaning=meaning,people=['paul','jesus']+(['silas','timothy'] if n==1 else []),places=['thessalonica'] if n==1 else [],sourceIds=['web']+(['wyant-thessalonians'] if n==3 else []),lds=dict(text=teach.get(n,'')+(' ' if n in teach else '')+'Study question. '+questions[n-1],sourceIds=['cfm-nt-2023-43'] if n in teach else []),eventOrder=n,dateLabel='Book order',historicalNote=meaning,mapNote='The marker identifies the addressed city. No exact temple or heavenly location is assigned.',route=[],routeEvidence='The letter supplies no exact delivery route.'))
data=dict(id=slug,bibleCode='2TH',name='2 Thessalonians',description='Endurance · relief · tested messages · quiet work · correction',chapterCount=3,scripture=t,chapters=chapters,people=people,places=places,sources=sources,review=dict(date=DATE,contextReviewDate=DATE,copyReviewDate=DATE,scope='All 47 verses read for three original contextual explanations and exact selections. Four selected profiles and one city reference do not claim exhaustive coverage. Church lesson coverage follows actual discussion. Wyant\x27s interpretation remains attributed. Authorship, dates, original manuscripts, Greek forms, the lawless figure, restraining force, and cause of refused work were not independently verified.',nextBook='1-timothy'))
if '--ready' in sys.argv:
 art=json.loads((OUT/'1-thessalonians-art.json').read_text(encoding='utf8'));(OUT/(slug+'-art.json')).write_text(json.dumps(art,ensure_ascii=False,indent=2)+'\n',encoding='utf8');finish(data)
else:(ROOT/'review/2-thessalonians-draft.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
