"""Build an unpublished Jeremiah draft from manually written chapter notes."""
import csv,json,sys
from book_common import ROOT,OUT,source,person,scripture,finish

def load(slug):return json.loads((OUT/(slug+'.json')).read_text(encoding='utf8'))
sources=[dict(next(s for s in load('genesis')['sources'] if s['id']==i)) for i in ['web','atlas-canaan']]
sources[0].update(title='Jeremiah · World English Bible',url='https://ebible.org/engwebp/JER01.htm',summary='The public-domain reading text supplies all 52 chapters.',limits='Chapter order is not a continuous timeline. Speakers’ claims remain attributed. Names shared by different people require separate links.')
sources[0]['limits']+=' Jeremiah 27:1 names Jehoiakim, but 27:3 and 27:12 name Zedekiah. The reading preserves this difference. Jezaniah in 42:1 and Azariah in 43:2 share Hoshaiah as father. Their different names do not establish two separate historical people. Nergal Sharezer occurs twice in 39:3. The group profile does not identify these officials as one person.'
def reviewed(i,title,url,summary,author,year,coverage,scope,limits,publisher,category='Scholarly study',perspective='historical'):
 s=source(i,title,url,summary,category,perspective,limits);s.update(author=author,year=year,publisher=publisher,chapterCoverage=coverage,reviewed=dict(date='2026-10-05',scope=scope));sources.append(s);return s
reviewed('luther-jeremiah-summary','Summary of Jeremiah · Enter the Bible','https://enterthebible.org/courses/jeremiah/lessons/summary-of-jeremiah/','The overview explains warnings, suffering, and hope after Jerusalem’s fall.','Terence E. Fretheim · revised by Michael Chan',2024,list(range(1,53)),'Complete main summary reviewed. Revision marked 08/24. General book context only.','The page’s broad length claim is not used. No verse commentary is attributed to this overview.','Luther Seminary')
reviewed('luther-jeremiah-background','Background of Jeremiah · Enter the Bible','https://enterthebible.org/courses/jeremiah/lessons/background-of-jeremiah/','The background describes Judah’s final kings and the book’s growth.','Terence E. Fretheim · revised by Michael Chan',2024,[1,25,36,39,45,52],'Complete main background reviewed. Revision marked 08/24.','Its proposals about Baruch and later writers are qualified. It dates Jerusalem’s fall to 587 BCE. Other reviewed sources use 586 BCE. Neither date is treated as undisputed. Greek and Hebrew versions differ in length and arrangement.','Luther Seminary')
reviewed('mcclellan-queen','The Queen of Heaven? · Data Over Dogma','https://www.youtube.com/watch?v=rt16_25Irx8','The hosts discuss household offerings and argue for identifying the queen with Astarte.','Dan McClellan · Dan Beecher',None,[7,44],'Original YouTube auto-generated captions reviewed from 12:27 through 19:51. Opening identifies both hosts. The discussion cites Susan Ackerman.','Captions lack reliable speaker labels and may contain errors. Audio and the full episode were not reviewed. No caption wording is quoted. Astarte is the program’s argued identification, not an explicit name in Jeremiah. The cited inscriptions and the full Ackerman book were not independently reviewed.','Data Over Dogma','McClellan commentary')
reviewed('ackerman-record','Gods, Goddesses, and the Women Who Serve Them · publisher record','https://www.eerdmans.com/9780802879561/gods-goddesses-and-the-women-who-serve-them/','Eerdmans verifies the book that Data Over Dogma cites.','Susan Ackerman',2022,[],'Publisher description, contents, author record, and publication details reviewed.','Bibliographic verification only. The full book and its inscriptions were not reviewed. Its claims are not presented as independently examined evidence.','Eerdmans')
reviewed('redditt-record','Introduction to the Prophets · publisher record','https://www.eerdmans.com/9780802828965/introduction-to-the-prophets/','Eerdmans verifies the author, title, ISBN, and date of a book cited by Wikipedia.','Paul L. Redditt',2008,[],'Complete publisher description and publication metadata reviewed. Paperback ISBN 9780802828965 matches the Wikipedia bibliography.','The full book and cited pages 132–33 were not reviewed. This record verifies publication rather than chapter interpretation.','Eerdmans')
w=reviewed('wiki-jeremiah','Book of Jeremiah · Wikipedia','https://en.wikipedia.org/w/index.php?title=Book_of_Jeremiah&oldid=1376288136','The overview describes the book’s sections and different manuscript forms.','Wikipedia contributors',2026,[],'Opening, structure, composition overview, bibliography, revision footer, and license reviewed. Redditt’s cited book checked against Eerdmans.','Overview and bibliography discovery. Reader notes use scripture and reviewed primary material. The bibliography contains a mismatched Kugler and Hartin title that is not adopted here.','Wikipedia','Wikipedia overview');w.update(revisionId=1376288136,revisionUrl=w['url'],license='CC BY-SA 4.0',licenseUrl='https://creativecommons.org/licenses/by-sa/4.0/',citedSourceIds=['redditt-record'])
church='The Church of Jesus Christ of Latter-day Saints'
reviewed('cfm-jeremiah-1','October 19–25. “Before I Formed Thee in the Belly I Knew Thee”: Jeremiah 1–3; 7; 16–18; 20','https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-old-testament-2026/43?lang=eng','The lesson studies Jeremiah’s call, returning to God, temple conduct, and the potter.','The Church of Jesus Christ of Latter-day Saints',2026,[1,2,3,7,16,17,18,20],'Complete main lesson and children’s section reviewed.','Linked talks were not separately reviewed. The lesson’s missionary use of fishers and hunters remains distinct from the pursuit in Jeremiah 16:16–18. Passage-specific questions are original.','The Church of Jesus Christ of Latter-day Saints','Come, Follow Me','lds')
reviewed('cfm-jeremiah-2','October 26–November 1. “I Will Turn Their Mourning into Joy”: Jeremiah 31–33; 36–39; Lamentations 1; 3','https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-old-testament-2026/44?lang=eng','The lesson studies a changed heart, scripture, prophetic counsel, and Ebed-melech’s courage.',church,2026,[31,32,33,36,37,38,39],'Complete main lesson and children’s section reviewed.','Linked talks were not separately reviewed. The Messiah identification is Church teaching. The 2026 assignment does not include Jeremiah 30. Passage-specific questions are original.',church,'Come, Follow Me','lds')
reviewed('lds-jeremiah-helps','Jeremiah 31–33; 36–38; Lamentations 1; 3 · Scripture Helps','https://www.churchofjesuschrist.org/study/manual/scripture-helps-old-testament/42-jeremiah-31-33-36-38-lamentations-1-3?lang=eng','The manual explains Rachel’s grief, the field purchase, Baruch, and Zedekiah’s choices.',church,None,[31,32,33,36,37,38,39],'Jeremiah overview and all Jeremiah Background and Context sections reviewed. Lamentations sections also read for later work.','The manual’s outside references and linked talks were not independently read. Its interpretation of the new covenant and righteous Branch remains in the Church layer. Jeremiah’s death in Egypt is a belief, not an event stated in this book.',church,'LDS Scripture Helps','lds')
rows=list(csv.DictReader((ROOT/'scripts/jeremiah-notes.tsv').open(encoding='utf8'),delimiter='\t'))
text=scripture('jeremiah','JER',52)
people=[];reuse={}
def profile(i,name,role,relations,passages,meaning,coverage,aliases=None,scope=None,art=None):
 p=person(i,name,role,relations,passages,meaning);p.update(chapterCoverage=coverage,placeIds=[])
 if aliases is not None:p['linkNames']=aliases
 if scope:p['verseScope']={str(k):v for k,v in scope.items()}
 if art:reuse[i]=art
 people.append(p)
profile('jeremiah','Jeremiah','Prophet who warns Judah and speaks about its return','He dictates warnings to Baruch and faces attacks from Judah’s officials.','Jeremiah 1; 7; 20; 26; 32; 36–45','He speaks through danger while also expressing anger, grief, and questions.',list(range(1,53)),['Jeremiah'],{35:[1,2,12,18],52:[]},['2-chronicles','jeremiah'])
profile('hilkiah-father','Hilkiah, Jeremiah’s father','Priest named in Jeremiah’s family description','The opening connects his household with Anathoth in Benjamin.','Jeremiah 1:1','His name locates Jeremiah within a priestly family. The passage does not identify him as Josiah’s high priest.',[1],['Hilkiah'],{1:[1]})
profile('josiah','Josiah','King during the start of Jeremiah’s work','Jeremiah later contrasts his care for poor people with Jehoiakim’s conduct.','Jeremiah 1:2; 22:15–16; 25:3; 36:2','His care gives the criticism of later royal wealth a concrete comparison.',[1,22,25,36],['Josiah'],art=['2-kings','josiah'])
profile('amon-king','Amon, king of Judah','Josiah’s father named in the opening date','Jeremiah’s first dated call falls during his son’s reign.','Jeremiah 1:2; 25:3','His name helps identify the royal family in the dated notices.',[1,25],['Amon'],art=['2-kings','amon-king'])
profile('jehoiakim','Jehoiakim','King who uses unpaid labor and burns Jeremiah’s scroll','He is Josiah’s son and Jehoiachin’s father.','Jeremiah 22; 26; 36','Destroying the scroll shows his refusal to hear correction despite officials’ objections.',[1,22,24,25,26,27,28,35,36,37,45,46,52],['Jehoiakim'],art=['2-kings','jehoiakim'])
profile('zedekiah','Zedekiah, king of Judah','King who seeks private advice but fears surrender','He questions Jeremiah and permits Ebedmelech’s rescue. Babylon captures and blinds him.','Jeremiah 21; 32; 37–39; 52','His fear of ridicule helps explain his failure to follow life-saving advice.',[1,21,24,27,28,29,32,34,37,38,39,43,44,51,52],['Zedekiah'],{29:[3]},art=['2-kings','zedekiah'])
profile('nebuchadnezzar','Nebuchadnezzar','Babylonian king whose armies capture Jerusalem','He rules over Judah, orders Jeremiah’s protection, and takes captives.','Jeremiah 21; 25; 27; 39; 52','His role in announced punishment does not excuse Babylon’s later violence.',[21,22,24,25,27,28,29,32,34,35,37,39,40,43,44,46,49,50,51,52],['Nebuchadnezzar'],art=['2-kings','nebuchadnezzar'])
profile('jehoiachin','Jehoiachin / Jeconiah / Coniah','Judean king taken to Babylon and later released from prison','He is Jehoiakim’s son. His mother and officials share the deportation.','Jeremiah 22:24–30; 24:1; 29:2; 52:31–34','His eventual release changes his treatment without restoring Judah’s lost kingdom.',[22,24,27,28,29,37,52],['Jehoiachin','Jeconiah','Coniah'],art=['2-kings','jehoiachin'])
profile('jehoahaz-judah','Shallum / Jehoahaz, king of Judah','Josiah’s son whose captivity Jeremiah mourns','Jeremiah says he will not return to his homeland.','Jeremiah 22:10–12; 2 Kings 23:30–34','His lost home gives the warning against royal wrongdoing a personal cost.',[22],['Shallum'],{22:[11]},['2-kings','jehoahaz-judah'])
profile('david','David','Earlier king whose family appears in promises of future rule','Jeremiah connects the promised just ruler with David’s family.','Jeremiah 21:12; 23:5; 30:9; 33:15–26','The royal promises emphasize justice rather than buildings or military display.',[17,21,22,23,29,30,33,36],['David'],art=['1-samuel','david'])
profile('manasseh-king','Manasseh, king of Judah','Earlier ruler whose wrongdoing appears in the warning','God’s speech names him as a cause of Judah’s disaster.','Jeremiah 15:4','His example connects present danger with choices made under earlier rule.',[15],['Manasseh'],{15:[4]},['2-kings','manasseh-king'])
profile('moses','Moses','Earlier leader named in the warning about unanswered prayer','God says even Moses and Samuel could not secure relief here.','Jeremiah 15:1','Their example shows the stated limit of further pleading for Judah.',[15],['Moses'],art=['exodus','moses'])
profile('samuel','Samuel','Earlier prophet named beside Moses','God says his prayer would not turn aside this judgment.','Jeremiah 15:1','Even this respected prophet could not secure relief for Judah.',[15],['Samuel'],art=['1-samuel','samuel'])
profile('rachel','Rachel','Israel’s ancestor pictured weeping for lost children','The poem gives her grief a voice and promises her children’s return.','Jeremiah 31:15–17','Her mourning connects the scattered people with a family’s loss.',[31],['Rachel'],art=['genesis','rachel'])
profile('baruch','Baruch','Writer who records and reads Jeremiah’s words','He keeps purchase deeds and accompanies Jeremiah when survivors take them to Egypt.','Jeremiah 32; 36; 43; 45','His writing lets others hear the message when Jeremiah cannot come.',[32,36,43,45],['Baruch'])
profile('pashhur-immer','Pashhur, son of Immer','Temple officer who strikes Jeremiah and puts him in stocks','Jeremiah warns him of captivity and death in Babylon.','Jeremiah 20:1–6','His position allows him to punish speech that challenges religious leaders.',[20],['Pashhur'],{20:[1,2,3,6]})
profile('pashhur-malchijah','Pashhur, son of Malchijah','Official sent to Jeremiah who later joins demands for his death','He appears with Zephaniah in the king’s request and with hostile officials.','Jeremiah 21:1; 38:1','He asks for God’s help but later demands the prophet’s death.',[21,38],['Pashhur the son of Malchijah'],{21:[1],38:[1]})
profile('zephaniah-priest','Zephaniah, the priest','Priest who carries royal requests and reads Shemaiah’s letter','He is Maaseiah’s son. Babylon later executes him at Riblah.','Jeremiah 21:1; 29:25–29; 37:3; 52:24–27','Reading the hostile letter allows Jeremiah to answer the attempt to silence him.',[21,29,37,52],['Zephaniah'],art=['2-kings','zephaniah-priest'])
profile('hananiah-azzur','Hananiah, son of Azzur','Prophet who promises a quick end to Babylon’s rule','He breaks Jeremiah’s yoke and predicts the captives’ return within two years.','Jeremiah 28','His comforting claim conflicts with Jeremiah’s message and fails within the chapter.',[28],['Hananiah'])
profile('uriah-shemaiah','Uriah, son of Shemaiah','Prophet killed after making warnings like Jeremiah’s','He flees to Egypt, but Jehoiakim has him brought back and killed.','Jeremiah 26:20–23','His death shows how royal power threatens people who challenge the city’s conduct.',[26],['Uriah'])
profile('micah-prophet','Micah, the Morashtite','Earlier prophet whose warning helps defend Jeremiah','Elders recall his warning about Zion during Hezekiah’s reign.','Jeremiah 26:18–19; Micah 3:12','His example gives the elders a reason to oppose Jeremiah’s execution.',[26],['Micah'])
profile('hezekiah','Hezekiah','Earlier king recalled for hearing Micah’s warning','The elders say he sought God’s favor instead of killing Micah.','Jeremiah 26:18–19','His response supplies a different royal choice from Jehoiakim’s treatment of Uriah.',[26],['Hezekiah'],art=['2-kings','hezekiah'])
profile('ahikam','Ahikam','Official whose protection helps keep Jeremiah alive','He is Shaphan’s son and Gedaliah’s father.','Jeremiah 26:24; 39:14; 40:5','His support gives practical protection when hostile listeners demand death.',[26,39,40,41,43],['Ahikam'],art=['2-kings','ahikam'])
profile('shaphan','Shaphan','Father named in the families of several helpful officials','Ahikam, Elasah, and Gemariah are identified as his sons.','Jeremiah 26:24; 29:3; 36:10–12','His family connections link protection, letter delivery, and public reading.',[26,29,36,39,40,41,43],['Shaphan'],art=['2-kings','shaphan'])
profile('elnathan-achbor','Elnathan, son of Achbor','Official involved in Uriah’s capture and objections to burning the scroll','Jehoiakim sends him to Egypt. Later he asks the king to spare the scroll.','Jeremiah 26:22–23; 36:12, 25','His different actions complicate a simple division between helpful and hostile officials.',[26,36],['Elnathan'])
profile('elasah-shaphan','Elasah, son of Shaphan','Messenger who carries Jeremiah’s letter to Babylon','He travels with Gemariah, son of Hilkiah, on Zedekiah’s business.','Jeremiah 29:3','The delivery allows captives to hear counsel from someone still in Jerusalem.',[29],['Elasah'])
profile('gemariah-hilkiah','Gemariah, son of Hilkiah','Messenger who helps carry Jeremiah’s letter to Babylon','He accompanies Elasah on the king’s business.','Jeremiah 29:3','His journey carries advice about homes, families, and peace to the captives.',[29],['Gemariah'])
profile('ahab-kolaiah','Ahab, son of Kolaiah','Prophet in Babylon whom Jeremiah accuses of false speech','Jeremiah names him beside Zedekiah, son of Maaseiah.','Jeremiah 29:21–23','The warning connects false claims of divine authority with harm to neighbors.',[29],['Ahab'])
profile('zedekiah-maaseiah','Zedekiah, son of Maaseiah','Prophet in Babylon whom Jeremiah accuses of false speech','He appears beside Ahab, son of Kolaiah, in the announced punishment.','Jeremiah 29:21–23','Jeremiah accuses them of lying in God’s name and adultery with neighbors’ wives.',[29],['Zedekiah'],{29:[21,22]})
profile('shemaiah-nehelamite','Shemaiah, the Nehelamite','Man whose letter urges Zephaniah to restrain Jeremiah','He rejects Jeremiah’s advice about a long stay in Babylon.','Jeremiah 29:24–32','He tries to stop the message by controlling its speaker.',[29],['Shemaiah'])
profile('hanamel','Hanamel','Jeremiah’s cousin who offers him a field in Anathoth','He is Shallum’s son and meets Jeremiah while Jeremiah is confined.','Jeremiah 32:7–12','His offer leads to a purchase that expresses hope beyond the siege.',[32],['Hanamel'])
profile('rechabites','The Rechabites','Family who refuses wine because of Jonadab’s instructions','They live in tents but enter Jerusalem when armies threaten them.','Jeremiah 35','Their repeated obedience gives Jeremiah a comparison with Judah’s refusal to listen.',[35],['Rechabites'])
profile('jaazaniah-rechabite','Jaazaniah, the Rechabite','Family leader whom Jeremiah brings to the temple','He is the son of another Jeremiah and the grandson of Habazziniah.','Jeremiah 35:3','He appears with the household that explains its refusal of wine.',[35],['Jaazaniah'])
profile('jehonadab','Jonadab / Jehonadab','Ancestor whose household instructions the Rechabites preserve','He is Rechab’s son. His descendants follow his rules about wine and tents.','Jeremiah 35:6–19; 2 Kings 10:15–23','His lasting influence supplies the contrast with Judah’s ignored prophetic warnings.',[35],['Jonadab'],art=['2-kings','jehonadab'])
profile('gemariah-shaphan','Gemariah, son of Shaphan','Official whose temple room hosts Baruch’s reading','He asks Jehoiakim not to burn the scroll. Micaiah is his son.','Jeremiah 36:10–12, 25','His room and objection help make the warning public and resist its destruction.',[36],['Gemariah'])
profile('micaiah-gemariah','Micaiah, son of Gemariah','Listener who reports Baruch’s reading to officials','His report brings the scroll before more officials and then the king.','Jeremiah 36:11–13','Repeating what he heard extends the message’s audience.',[36],['Micaiah'])
profile('elishama-scribe','Elishama, the scribe','Official whose room holds the scroll before the king hears it','The officials store the scroll there after hearing Baruch.','Jeremiah 36:12, 20–21','The scroll passes through official rooms before the king destroys it.',[36],['Elishama'])
profile('delaiah-shemaiah','Delaiah, son of Shemaiah','Official who asks the king not to burn the scroll','He joins Elnathan and Gemariah in their unsuccessful appeal.','Jeremiah 36:12, 25','His objection shows that the king’s refusal was not shared by every official.',[36],['Delaiah'])
profile('zedekiah-hananiah','Zedekiah, son of Hananiah','Official present when the princes hear about Baruch’s reading','He sits among the officials listed in the scribe’s room.','Jeremiah 36:12','The warning reaches the officials before the king hears and burns the scroll.',[36],['Zedekiah'])
profile('jehudi','Jehudi','Messenger who reads the scroll to Jehoiakim','He first summons Baruch and later retrieves the scroll from Elishama’s room.','Jeremiah 36:14, 21–23','His reading brings the warning directly before the king who burns it.',[36],['Jehudi'])
profile('arrest-officers','The officers sent to arrest Jeremiah and Baruch','Jerahmeel, Seraiah, and Shelemiah receive the king’s arrest order','Seraiah is Azriel’s son. Shelemiah is Abdeel’s son.','Jeremiah 36:26','The order extends the king’s rejection from the written warning to its speakers.',[36],['Jerahmeel','Seraiah','Shelemiah'],{36:[26]})
profile('jehucal-shelemiah','Jehucal / Jucal, son of Shelemiah','Official who seeks prayer and later opposes Jeremiah','He joins the request to Zedekiah that Jeremiah be killed.','Jeremiah 37:3; 38:1–4','Seeking prayer does not stop him from rejecting the prophet’s costly answer.',[37,38],['Jehucal','Jucal'])
profile('irijah','Irijah','Guard who accuses Jeremiah of leaving to join the enemy','He seizes Jeremiah at Benjamin’s gate despite Jeremiah’s denial.','Jeremiah 37:13–14','He ignores Jeremiah’s denial and sends him to the officials. They beat and imprison Jeremiah.',[37],['Irijah'])
profile('jonathan-scribe','Jonathan, the scribe','Man whose house is used as Jeremiah’s prison','Jeremiah asks Zedekiah not to return him there because he fears death.','Jeremiah 37:15–20; 38:26','Officials turn his house into a prison where Jeremiah fears dying.',[37,38],['Jonathan'])
profile('hostile-officials','Shephatiah and Gedaliah, the officials opposing Jeremiah','Officials who hear Jeremiah and demand his death','Shephatiah is Mattan’s son. Gedaliah is Pashhur’s son.','Jeremiah 38:1–6','They call the warning harmful because it discourages soldiers from continuing resistance.',[38],['Shephatiah','Gedaliah'],{38:[1]})
profile('malchijah-royal','Malchijah, the king’s son','Royal son whose pit holds Jeremiah','Officials lower Jeremiah into mud in the pit within the guard court.','Jeremiah 38:6','His named property gives the attack a place within the royal compound.',[38],['Malchijah'],{38:[6]})
profile('ebedmelech','Ebedmelech / Ebed-melech','Ethiopian palace servant who rescues Jeremiah','He appeals to Zedekiah and uses cloth under the rescue ropes.','Jeremiah 38:7–13; 39:15–18','He notices danger and acts despite the officials who created it.',[38,39],['Ebedmelech','Ebed-melech'])
profile('babylonian-officers','The Babylonian officers at Jerusalem','Officials who enter the city and help release Jeremiah','The account names Nergal Sharezer, Samgarnebo, Sarsechim, and Nebushazban.','Jeremiah 39:3, 13–14','Their orders connect the conquered city with Jeremiah’s release.',[39],['Nergal Sharezer','Samgarnebo','Sarsechim','Nebushazban'])
profile('nebuzaradan','Nebuzaradan','Babylonian commander who destroys buildings, deports people, and frees Jeremiah','He places remaining people under Gedaliah and offers Jeremiah a choice of destination.','Jeremiah 39–40; 43:6; 52','His differing actions show the conqueror’s power over both punishment and release.',[39,40,41,43,52],['Nebuzaradan'],art=['2-kings','nebuzaradan'])
profile('gedaliah','Gedaliah, son of Ahikam','Governor placed over Judah’s remaining people','He urges farming and rejects Johanan’s warning about Ishmael.','Jeremiah 39:14; 40–41','His death destroys a fragile attempt to resume life after Jerusalem’s fall.',[39,40,41,43],['Gedaliah'],art=['2-kings','gedaliah'])
profile('ishmael-nethaniah','Ishmael, son of Nethaniah','Royal descendant who kills Gedaliah and takes captives','Johanan recovers the captives, but Ishmael escapes toward Ammon.','Jeremiah 40:8–16; 41','His violence turns the survivors’ attempted recovery into flight and fear.',[40,41],['Ishmael'],art=['2-kings','ishmael-nethaniah'])
profile('johanan-kareah','Johanan, son of Kareah','Commander who warns Gedaliah and later leads survivors toward Egypt','He rescues Ishmael’s captives but rejects Jeremiah’s instruction to remain in Judah.','Jeremiah 40–43','Protecting people in one crisis does not make his later decision consistent with Jeremiah’s warning.',[40,41,42,43],['Johanan'],art=['2-kings','johanan-kareah'])
profile('jonathan-kareah','Jonathan, son of Kareah','Commander named beside his brother Johanan','He joins the commanders who come to Gedaliah at Mizpah.','Jeremiah 40:8','The commanders must decide whether to accept Babylon’s appointed governor.',[40],['Jonathan'])
profile('seraiah-captain','Seraiah, son of Tanhumeth','Commander who comes to Gedaliah at Mizpah','He appears among military leaders who hear the governor’s advice.','Jeremiah 40:8; 2 Kings 25:23','His arrival helps show the survivors gathering around the new governor.',[40],['Seraiah'],art=['2-kings','seraiah-captain'])
profile('jezaniah-maacathite','Jezaniah / Jaazaniah, the Maacathite’s son','Commander who joins the gathering at Mizpah','The account identifies him by his father’s origin.','Jeremiah 40:8; 2 Kings 25:23','Gedaliah urges these commanders to stop fearing Babylon’s officials and gather food.',[40],['Jezaniah'],art=['2-kings','jaazaniah'])
profile('baalis','Baalis','Ammonite king accused of sending Ishmael to kill Gedaliah','Johanan reports the plot, but Gedaliah rejects his warning.','Jeremiah 40:14','The accusation connects the local threat with a neighboring kingdom. The verse reports Johanan’s claim.',[40],['Baalis'])
profile('jezaniah-hoshaiah','Jezaniah, son of Hoshaiah','Leader who asks Jeremiah to pray for the survivors','He appears beside Johanan in the request for guidance.','Jeremiah 42:1–6','His request joins a promise to obey answers that might be unwelcome.',[42],['Jezaniah'])
profile('azariah-hoshaiah','Azariah, son of Hoshaiah','Leader who accuses Jeremiah of lying about Egypt','He joins Johanan in blaming Baruch for Jeremiah’s answer.','Jeremiah 43:2–3','His accusation replaces the requested guidance with a claim about hidden motives.',[43],['Azariah'])
profile('women-queen','The women defending offerings to the queen','Judean women in Egypt who defend their goddess offerings','They say their husbands knew about the cakes and drink offerings.','Jeremiah 44:15–19','Their explanation of the disaster directly conflicts with Jeremiah’s account of its cause.',[44],['women'],{44:[15,19,24]})
profile('hophra','Pharaoh Hophra','Egyptian king named in Jeremiah’s warning','Jeremiah predicts that enemies will take him as they took Zedekiah.','Jeremiah 44:30','His threatened fall challenges the survivors’ hope that Egypt offers lasting protection.',[44],['Pharaoh Hophra','Hophra'])
profile('necho','Pharaoh Necoh / Neco','Egyptian king whose army loses at Carchemish','The account places his army against Nebuchadnezzar by the Euphrates.','Jeremiah 46:2','His defeat gives the warning against Egypt a specific military setting.',[46],['Pharaoh Necoh','Necoh'],art=['2-kings','necho'])
profile('seraiah-neriah','Seraiah, son of Neriah','Official instructed to read and sink Jeremiah’s Babylon scroll','He accompanies Zedekiah to Babylon and is Baruch’s brother through their father.','Jeremiah 51:59–64; 32:12','Reading and sinking the scroll carry the warning into the place it names.',[51],['Seraiah'])
profile('hamutal','Hamutal','Zedekiah’s mother named in the closing royal account','The passage identifies her as the daughter of Jeremiah of Libnah.','Jeremiah 52:1','Her family description distinguishes the royal household from Jeremiah the prophet’s family.',[52],['Hamutal'],art=['2-kings','hamutal'])
profile('seraiah-priest','Seraiah, the chief priest','Priest captured and executed after Jerusalem’s fall','Nebuzaradan takes him with Zephaniah and other officials to Riblah.','Jeremiah 52:24–27','His death shows the siege’s cost to the city’s religious leadership.',[52],['Seraiah'],art=['2-kings','seraiah-priest'])
profile('solomon','Solomon','Earlier king named as maker of temple furnishings','The account describes the bronze objects broken and carried to Babylon.','Jeremiah 52:20','Naming their maker connects the lost objects with the temple’s earlier royal history.',[52],['Solomon'],art=['1-kings','solomon'])
profile('evil-merodach','Evilmerodach / Evil Merodach','Babylonian king who releases Jehoiachin from prison','He changes Jehoiachin’s clothing and gives him a continuing allowance.','Jeremiah 52:31–34','His kindness changes the captive king’s daily life without restoring Judah’s rule.',[52],['Evilmerodach'],art=['2-kings','evil-merodach'])
geo=reviewed('openbible-jeremiah-geo','Jeremiah · OpenBible.info geographic index','https://www.openbible.info/geo/preview/jer','The index connects named places with passages and possible modern locations.','OpenBible.info',None,[],'Complete Jeremiah place table, passage references, competing locations, and license footer reviewed.','An open geographic compilation, not archaeological proof of narrated events. Coordinates are approximate display points. Competing identifications remain uncertain. No index photographs are copied.','OpenBible.info','Geographic reference')
geo.update(license='CC BY 4.0',licenseUrl='https://creativecommons.org/licenses/by/4.0/')
places=[]
for slug,pid,summary in [
 ('2-kings','jerusalem','Jeremiah warns the city before Babylon captures and burns it.'),
 ('1-kings','anathoth','Jeremiah’s family lives here. He later buys his cousin’s field.'),
 ('2-kings','babylon','Captives receive Jeremiah’s letter here. Later poems warn against Babylon.'),
 ('2-kings','mizpah','Gedaliah gathers survivors here before Ishmael kills him.'),
 ('1-kings','ramah','The poems place Rachel’s mourning here. Jeremiah also meets the captives here.'),
 ('2-kings','riblah','Babylon’s king judges Zedekiah and captured officials here.'),
 ('2-kings','jericho','Babylonian forces capture Zedekiah near Jericho.'),
 ('2-chronicles','carchemish','Egypt’s army loses to Nebuchadnezzar beside the Euphrates.'),
 ('1-kings','shiloh','Jeremiah names its ruined sanctuary when warning the temple’s visitors.'),
 ('2-kings','samaria','Jeremiah compares Jerusalem’s prophets with Samaria’s prophets.'),
 ('2-kings','lachish','The city still resists Babylon when Jerusalem faces siege.'),
 ('joshua','azekah','The city still resists Babylon when Jerusalem faces siege.'),
 ('joshua','gibeon','Johanan meets Ishmael’s captives near the large pool.'),
 ('genesis','bethlehem','The survivors stop near Bethlehem before heading toward Egypt.'),
 ('1-kings','tyre','Jeremiah includes Tyre among the kingdoms facing Babylon’s power.'),
 ('1-kings','sidon','Jeremiah includes Sidon among the kingdoms facing Babylon’s power.'),
 ('judges','gaza','The warning against Philistia names Gaza’s grief.'),
 ('judges','ashkelon','The warning against Philistia names Ashkelon’s destruction.'),
 ('numbers','heshbon','Warnings against Moab and Ammon name Heshbon.'),
 ('2-samuel','rabbah','Jeremiah predicts destruction for Ammon’s royal city.'),
 ('2-kings','damascus','The warning against Damascus describes fear and flight.'),
 ('2-kings','moab','Jeremiah describes Moab’s pride, destruction, grief, and promised return.'),
 ('2-kings','edom','Jeremiah warns Edom that its mountain homes cannot prevent attack.'),
 ('2-kings','gilead','Jeremiah asks about its healing balm while describing Judah’s pain.'),
 ('2-kings','egypt','Survivors seek safety here despite Jeremiah’s warning.')]:
 p=dict(next(p for p in load(slug)['places'] if p['id']==pid))
 p.update(summary=summary,sourceIds=['web','openbible-jeremiah-geo'],limits='Approximate location. Region markers do not define ancient borders. Anathoth, Mizpah, Ramah, and Heshbon have competing site identifications.')
 places.append(p)
for pid,name,lat,lng,summary,limits in [
 ('tahpanhes','Tahpanhes',30.865,32.167,'Jeremiah places stones near Pharaoh’s palace after the survivors enter Egypt.','Approximate Tell Defenneh marker. It does not locate the buried stones.'),
 ('memphis','Memphis',29.85,31.25,'Jeremiah names Memphis among Egypt’s cities facing destruction.','Approximate ancient city marker.'),
 ('hinnom','Valley of Hinnom',31.765,35.23,'Jeremiah condemns child sacrifice and announces destruction in this valley.','Approximate valley marker. It does not establish a particular altar location.')]:
 places.append(dict(id=pid,name=name,lat=lat,lng=lng,summary=summary,limits=limits,sourceIds=['web','openbible-jeremiah-geo']))
locations={1:['anathoth','jerusalem'],2:['jerusalem','egypt','memphis'],3:['jerusalem'],4:['jerusalem'],5:['jerusalem'],6:['jerusalem'],7:['jerusalem','shiloh','hinnom'],8:['jerusalem','gilead'],9:['jerusalem'],10:['jerusalem'],11:['jerusalem','anathoth'],12:[],13:['jerusalem'],14:['jerusalem'],15:['jerusalem'],16:[],17:['jerusalem'],18:['jerusalem'],19:['jerusalem','hinnom'],20:['jerusalem','babylon'],21:['jerusalem','babylon'],22:['jerusalem'],23:['jerusalem','samaria'],24:['jerusalem','babylon','egypt'],25:['jerusalem','babylon','egypt','tyre','sidon','moab','edom'],26:['jerusalem','shiloh','egypt'],27:['jerusalem','babylon','tyre','sidon','moab','edom'],28:['jerusalem','babylon'],29:['jerusalem','babylon'],30:['jerusalem'],31:['ramah','jerusalem'],32:['anathoth','jerusalem'],33:['jerusalem'],34:['jerusalem','lachish','azekah'],35:['jerusalem'],36:['jerusalem'],37:['jerusalem','egypt'],38:['jerusalem'],39:['jerusalem','jericho','riblah','babylon'],40:['ramah','mizpah'],41:['mizpah','gibeon','bethlehem'],42:['egypt'],43:['egypt','tahpanhes'],44:['egypt','tahpanhes','memphis'],45:[],46:['egypt','carchemish','memphis','gilead'],47:['gaza','ashkelon','tyre','sidon'],48:['moab','heshbon'],49:['rabbah','heshbon','edom','damascus'],50:['babylon'],51:['babylon'],52:['jerusalem','jericho','riblah','babylon']}
chapters=[]
for row in rows:
 n=int(row['chapter']);hs=[s['id'] for s in sources if s['perspective']=='historical' and n in s.get('chapterCoverage',[])];ls=[s['id'] for s in sources if s['perspective']=='lds' and n in s.get('chapterCoverage',[])]
 route={29:['jerusalem','babylon'],39:['jerusalem','jericho','riblah','babylon'],40:['ramah','mizpah'],52:['jerusalem','jericho','riblah','babylon']}.get(n,[])
 route_evidence={29:'Jeremiah 29:1–3 describes Elasah and Gemariah delivering the letter from Jerusalem to captives in Babylon. Intermediate roads are not specified.',39:'Jeremiah 39:4–7 traces Zedekiah’s escape, capture near Jericho, judgment at Riblah, and removal to Babylon. Lines connect approximate named locations, not known roads.',40:'Jeremiah 40:1–6 places Jeremiah among captives at Ramah and then with Gedaliah at Mizpah. The exact road and competing site locations remain uncertain.',52:'Jeremiah 52:7–11 repeats Zedekiah’s escape, capture near Jericho, judgment at Riblah, and removal to Babylon. It does not supply the roads.'}.get(n,'Place references do not establish a continuous journey. No travel line is reconstructed.')
 chapters.append(dict(chapter=n,title=row['title'],summary=row['summary'],meaning=row['meaning'],lds=dict(text=row['question'],sourceIds=ls),sourceIds=['web']+hs,people=[p['id'] for p in people if n in p['chapterCoverage']],places=locations[n],eventOrder=n,dateLabel='Chapter order',historicalNote=row['meaning'],mapNote='Map points locate named places. Lines connect stated movements where the passage gives endpoints.',route=route,routeEvidence=route_evidence))
assert [c['chapter'] for c in chapters]==list(range(1,53))
assert sum(map(len,text.values()))==1364
data=dict(id='jeremiah',bibleCode='JER',name='Jeremiah',chapterCount=52,description='Warnings · competing prophets · Jerusalem’s fall · return',scripture=text,chapters=chapters,people=people,places=places,sources=sources,review=dict(date='2026-10-05',scope='All 1364 WEB verses read. Chapter writing, profiles, and approximate place references drafted. Travel review, portraits, same-name checks, and publication checks remain incomplete.',status='draft',nextBook='lamentations'))
(ROOT/'review/jeremiah-draft.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
(ROOT/'scripts/jeremiah-art-reuse.json').write_text(json.dumps(reuse,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
if '--ready' in sys.argv:
 art=json.loads((OUT/'jeremiah-art.json').read_text(encoding='utf8'))
 assert set(art)=={p['id'] for p in people}, 'Every profile requires reviewed art'
 assert all((ROOT/'dist'/a['src']).is_file() for a in art.values())
 data['review'].update(status='reviewed',scope='All 1364 WEB verses read. Short chapter studies and profiles reviewed against the passages. Historical sources and Church teaching remain distinct. Portraits inspected. Approximate map references and four stated movements reviewed. Same-name reader checks remain required before deployment.')
 for p in data['people']:p.pop('chapterCoverage')
 finish(data)
print('Saved unpublished Jeremiah draft:',len(people),'profiles,',len(reuse),'same-person art references.')
