"""Joshua: textual campaigns, land lists, covenant memory, and evidence limits."""
import json,re
from book_common import OUT,scripture,source,person,place,finish
parents={s:json.loads((OUT/f'{s}.json').read_text(encoding='utf-8')) for s in ['genesis','numbers','deuteronomy']}
rows='''
Joshua receives the charge|Joshua succeeds Moses. Israel prepares to cross the Jordan, and the eastern tribes promise to help.|Leadership rests on the law and shared obligations. The promised territory is a textual claim, not a modern boundary.|joshua,moses,reuben,gad,manasseh|shittim,jordan,canaan|The Church lesson connects courage with God’s presence and repeated scripture study.
Rahab protects the spies|Two spies enter Jericho. Rahab hides them and obtains a promise to protect her household.|A woman described as a prostitute acts decisively for her household. Later biblical writers recognize both her faith and her actions.|rahab,joshua,sihon,og|jericho,shittim|Come, Follow Me studies Rahab as an example of faith expressed through action.
Crossing the Jordan|The priests carry the ark into the Jordan. The account describes the waters stopping while Israel crosses.|The crossing establishes Joshua’s authority through a pattern that recalls Moses. No exact crossing point is securely identified here.|joshua|shittim,jordan|The Church lesson connects the crossing with trust in Christ. Its baptism comparison is a later symbolic reading.
Stones for remembrance|Twelve representatives take stones from the Jordan. Israel camps at Gilgal and prepares to explain the memorial to children.|The stones connect an event with future teaching. This account does not identify a surviving group of twelve stones.|joshua,reuben,gad,manasseh|jordan,gilgal|Come, Follow Me asks readers to recognize God’s help and teach the next generation.
Passover and the commander|Israel renews circumcision and observes Passover. Manna ends. Joshua encounters the commander of the Lord’s army near Jericho.|The chapter joins covenant signs, food, and sacred ground. The commander is unnamed in the account.|joshua|gilgal,jericho|The older manual proposes that the commander may be the Lord. It acknowledges the limited details.
Jericho and Rahab’s rescue|The account describes Jericho’s walls falling after a ritual march. Israel destroys the city but preserves Rahab and her household.|The narrative combines ritual obedience, collective killing, and an honored promise. Its theological explanation does not independently establish the destruction’s date.|joshua,rahab|jericho|The Church lesson applies obedience to resisting temptation. That application does not authorize violence against people today.
Achan and defeat at Ai|Israel loses at Ai. Achan admits taking forbidden goods. The account ends with the destruction of his household and possessions.|The story connects individual wrongdoing with collective disaster. The severe punishment is part of its ancient setting.|joshua,achan|ai,gilgal|The lesson studies removing wrongdoing from one’s life. Keep that application distinct from the account’s collective punishment.
Ai and the law at Ebal|Joshua captures Ai through an ambush. He then builds an altar on Ebal and reads the law before the assembly.|The account moves from warfare to a public covenant ceremony. The identity and chronology of ancient Ai remain disputed.|joshua|ai,bethel,ebal,gerizim|The manual connects the public reading with Moses’s instructions. Consider who hears a community’s commitments.
The Gibeonite agreement|Gibeonite envoys disguise their nearby origin. Israel swears an oath, then assigns them forced labor after discovering the deception.|The oath protects lives but produces an unequal arrangement. Survival through a treaty is not the same as equal membership.|joshua|gibeon,gilgal|The older manual studies the duty to keep an oath. Read that duty beside the imposed labor.
The southern coalition|Five kings attack Gibeon. Joshua comes to its aid. The account describes hail, an extended day, and southern campaigns.|The narrative includes poetry attributed to the Book of Jasher. Its total victory language requires separate historical review.|joshua,adoni-zedek,hoham,piram,japhia,debir-king|gilgal,gibeon,beth-horon,azekah,jerusalem,hebron,jarmuth,lachish|The manual interprets the extended day through Helaman 12. This is a religious interpretation, not an astronomical measurement.
Hazor and northern war|Jabin gathers northern allies. Joshua defeats them and burns Hazor. The chapter describes long warfare and broad conquest.|Hazor has excavated fire damage. That evidence does not identify Joshua as its cause or verify every campaign in the chapter.|joshua,jabin-joshua,jobab-madon|hazor,canaan|The manual studies reliance on God in the northern campaign. Its historical claims need separate archaeological evidence.
The defeated kings listed|The chapter lists eastern victories under Moses and western kings defeated under Joshua.|A victory list summarizes claims within the book. Listing a king does not establish an independent archaeological identification.|joshua,moses,sihon,og|canaan,gilead,bashan|Read the list as part of the book’s account. Keep its religious purpose distinct from evidence for individual kings.
Remaining land and eastern inheritance|Joshua is old, and land remains to be possessed. The chapter records eastern inheritances and recalls Balaam’s death.|Remaining territory complicates a reading of earlier conquest language as complete settlement. A tribal grant is not an excavated boundary.|joshua,moses,sihon,og,balaam,reuben,gad,manasseh|canaan,gilead,bashan,heshbon|The manual describes the distribution of land. Consider obligations that remain after receiving an inheritance.
Caleb requests Hebron|Joshua and Eleazar oversee allotments. Caleb recalls the scouting mission and requests Hebron.|Caleb’s request joins remembered service with a land claim. His stated age belongs to the narrative chronology.|joshua,eleazar,moses,caleb|gilgal,hebron|The manual places this account within inheritance. Consider how long service can shape a request without proving every historical detail.
Judah’s land and Achsah’s request|The chapter lists Judah’s boundaries and towns. Othniel takes Debir. Achsah asks Caleb for springs. Jebusites remain in Jerusalem.|The account includes warfare, a woman’s resource request, and incomplete occupation. It does not describe an empty land.|caleb,othniel,achsah,judah|hebron,debir-town,jerusalem|The manual studies land distribution. Consider Achsah’s direct request for the water needed with her land.
Ephraim’s allotment|The chapter describes Joseph’s descendants and Ephraim’s territory. Canaanites remain at Gezer under forced labor.|The closing note qualifies complete conquest claims. Territorial lists record the text’s arrangement rather than a surveyed modern border.|joseph,ephraim,manasseh|canaan,bethel,gezer|Read the inheritance account beside its statement about people who remain. Do not confuse forced labor with equal inclusion.
Manasseh and the daughters’ inheritance|Zelophehad’s daughters receive land under the earlier ruling. Joseph’s descendants request more territory. Canaanite towns remain.|The daughters’ claim connects a legal promise with its stated fulfillment. The chapter also records resistance to displacement.|joshua,eleazar,manasseh,joseph,mahlah,noah-daughter,hoglah,milcah-daughter,tirzah|canaan,gilead|The manual studies inheritance. Consider how honoring a prior ruling requires a concrete distribution of resources.
Shiloh and Benjamin’s portion|Israel assembles at Shiloh. Surveyors describe the remaining land. Joshua assigns Benjamin’s allotment by lot.|The sanctuary setting joins worship and allocation. The chapter’s descriptions do not supply precise archaeological boundary polygons.|joshua,benjamin|shiloh,jericho,jerusalem,gibeon|The manual connects the allocation with Moses’s instructions. Keep named places distinct from exact modern boundary claims.
Remaining allotments and Joshua’s town|The chapter lists portions for Simeon, Zebulun, Issachar, Asher, Naphtali, and Dan. Joshua receives Timnath-serah.|The lists organize tribal communities. Portraits of their ancestors do not mean those ancestors attended the distribution.|joshua,eleazar,simeon,zebulun,issachar,asher,naphtali,dan|shiloh,timnath-serah,canaan|The manual studies the division of land. Consider how a community records both shared and personal provision.
Cities of refuge|Six towns provide refuge for a person accused of accidental killing until a hearing.|The procedure distinguishes an accident from deliberate killing. It offers a hearing rather than declaring every fugitive innocent.|joshua|shechem,hebron,gilead,bashan|The manual explains refuge within the inherited legal system. Consider why circumstances and a fair hearing matter.
Levitical towns and fulfillment|Levite leaders request the towns promised through Moses. The chapter lists towns and ends with a statement of fulfilled promises.|A strong closing claim stands beside earlier notices of remaining populations. Both features belong to the book’s presentation.|joshua,eleazar,moses,levi|shiloh,canaan|The manual connects these towns with support for Levites. Consider how public service receives material provision.
An altar and a dispute|Eastern tribes return home and build an altar. Phinehas leads a delegation. An explanation prevents war between the tribes.|A threatening interpretation changes after direct inquiry. The altar is explained as a witness, not a rival place of sacrifice.|joshua,phinehas,eleazar,achan,reuben,gad,manasseh|shiloh,jordan,gilead|The manual studies the altar’s purpose. Consider how asking for an explanation can prevent harm from an assumption.
Joshua’s farewell warning|Joshua warns the leaders about remaining nations, other gods, and the consequences of abandoning the covenant.|The farewell acknowledges neighboring peoples still present. Its separation commands belong to this ancient covenant setting.|joshua|canaan|Come, Follow Me studies Joshua’s final counsel and choosing to remain faithful to God.
The covenant at Shechem|Joshua recalls the ancestors and Israel’s journey. The people renew the covenant. The book records Joshua’s death and the burials of Joseph and Eleazar.|Remembered history supports a public commitment. The named burials do not establish that a modern shrine contains the described remains.|joshua,terah,nahor,abraham,isaac,jacob,esau,moses,aaron,balak,balaam,joseph,eleazar|shechem,timnath-serah,egypt,canaan|Come, Follow Me studies a deliberate choice to serve God. Consider the actions needed to carry out that choice.
'''.strip().splitlines()
assert len(rows)==24
sources=[source('web','Joshua — World English Bible','https://ebible.org/engwebp/JOS01.htm','The public-domain reading text supplies all 24 chapters.','Scripture',limits='This is textual evidence for the account. It does not independently verify each event or identify every location.')]
sources.extend(dict(s) for s in parents['numbers']['sources'] if s['id'] in ['terrain','atlas','atlas-exodus','atlas-canaan'])
s=source('yale-12','The Deuteronomistic History: Life in the Land · Open Yale Courses','https://oyc.yale.edu/religious-studies/rlst-145/lecture-12','Hayes studies Joshua’s structure, conquest language, remaining Canaanite populations, and archaeological questions.',limits='This is a 2006 lecture interpretation. Compare broad historical conclusions with newer site-specific evidence. It does not date every narrated event.')
s.update(author='Christine Hayes',year='Fall 2006 course',reviewed='2026-10-05: Relevant published transcript sections on Joshua’s structure, conquest claims, and remaining populations reviewed.');sources.append(s)
s=source('lds-joshua','Joshua 1–24: The Entry into the Promised Land','https://www.churchofjesuschrist.org/study/manual/old-testament-student-manual-genesis-2-samuel/joshua-1-24-the-entry-into-the-promised-land?lang=eng','The manual studies Joshua’s leadership, Rahab, covenant signs, inheritance, the altar dispute, and the final choice to serve God.','LDS study manual','lds',limits='This is 1980 Institute commentary. Its historical and physical explanations are not independent archaeology or astronomy. Its ancient punishment discussion is not a present instruction.')
s.update(author='The Church of Jesus Christ of Latter-day Saints',year=1980,reviewed='2026-10-05: Relevant commentary sections across the stated chapter coverage reviewed.',chapterCoverage=list(range(1,25)));sources.append(s)
s=source('hazor-study','Fire at the gate of Hazor: A micro-geoarchaeological study of the depositional history of a Bronze Age City gate','https://cris.huji.ac.il/en/publications/fire-at-the-gate-of-hazor-a-micro-geoarchaeological-study-of-the-/','The study reports fire and collapse at Hazor’s Lower City gate at the end of the Late Bronze Age. It does not identify Joshua as the cause.',limits='The public abstract and publication record were reviewed. The full paper was not read. Evidence at this gate does not verify every conquest claim.')
s.update(author='Marko Runjajić, Yosef Garfinkel, Michael G. Hasel, Assaf Yasur-Landau, and David E. Friesem',year=2023,reviewed='2026-10-05: University publication record, peer-reviewed journal identity, and public abstract reviewed.',chapterCoverage=[11],doi='10.1016/j.jasrep.2023.103914');sources.append(s)
s=source('hazor-project','Tel Hazor · Hebrew University excavation project','https://archaeology.huji.ac.il/tel-hazor','The project describes Hazor’s upper and lower cities, Canaanite buildings, and written finds.',limits='The project overview supplies site context. It does not establish the identity of Joshua, Jabin, or the cause of each destruction.')
s.update(author='Hebrew University of Jerusalem · Institute of Archaeology',reviewed='2026-10-05: Published excavation overview and bibliography reviewed.',chapterCoverage=[11]);sources.append(s)
places=[dict(p) for p in parents['deuteronomy']['places'] if p['id'] in ['canaan','egypt','gilead','bashan','heshbon','hebron','gerizim','ebal']]
for p in places:
 p['summary']='Named geographical reference in Joshua.';p['limits']='The marker shows a broad locality or traditional identification. It does not verify occupation dates, an event, or precise tribal boundaries.'
for pid,name,lat,lng,note in [
('shittim','Shittim · proposed region',31.86,35.70,'The precise camp location is uncertain.'),('jordan','Jordan · crossing region',31.86,35.55,'This shows a river region, not an identified ancient ford.'),('gilgal','Gilgal · approximate region',31.86,35.50,'The camp’s precise identification is uncertain.'),('jericho','Jericho · Tell es-Sultan',31.871,35.444,'The site marker does not establish the date or cause of the narrated destruction.'),('ai','Ai · traditional et-Tell identification',31.916,35.26,'The identification and conquest chronology are disputed.'),('bethel','Bethel · traditional Beitin locality',31.93,35.22,'The marker is a traditional locality, not an event verification.'),('gibeon','Gibeon · el-Jib locality',31.847,35.183,'The location does not identify a precise battle site.'),('jerusalem','Jerusalem',31.777,35.235,'The marker does not identify a particular king or campaign.'),('jarmuth','Jarmuth · Tel Yarmut locality',31.708,34.975,'The marker shows the traditional site, not a verified king’s residence.'),('lachish','Lachish · Tel Lachish',31.565,34.849,'The site has a long history. Its presence does not verify Joshua’s campaign.'),('beth-horon','Beth-horon · pass region',31.89,35.125,'This shows the pass region, not an excavated campaign road.'),('azekah','Azekah · traditional locality',31.699,34.936,'The marker does not identify the described pursuit route.'),('hazor','Hazor · excavated site',33.017,35.569,'Excavated fire deposits do not identify Joshua as their cause.'),('debir-town','Debir · approximate southern region',31.42,35.02,'Competing site identifications remain. This regional marker is not a certain town location.'),('gezer','Gezer · traditional Tel Gezer',31.86,34.919,'The marker does not establish the chronology of forced labor described in the chapter.'),('shiloh','Shiloh · traditional locality',32.055,35.289,'The marker does not independently date the assembly or sanctuary.'),('shechem','Shechem · Tell Balata locality',32.214,35.282,'The locality does not verify the covenant ceremony or Joseph’s burial.'),('timnath-serah','Timnath-serah · traditional region',32.117,35.157,'The identification is debated. The marker does not identify Joshua’s grave.')]:
 places.append(place(pid,name,lat,lng,'Named locality or region in Joshua.',note,['web','atlas-canaan']+(['hazor-project'] if pid=='hazor' else [])))
people=[]
for slug,ids in [('numbers',['joshua','moses','aaron','caleb','eleazar','phinehas','sihon','og','balaam','balak','mahlah','noah-daughter','hoglah','milcah-daughter','tirzah']),('genesis',['abraham','isaac','jacob','esau','joseph']),('deuteronomy',['reuben','simeon','levi','judah','benjamin','ephraim','manasseh','zebulun','issachar','dan','naphtali','gad','asher'])]:
 for p in parents[slug]['people']:
  if p['id'] in ids:people.append(dict(p))
new=[
('rahab','Rahab','Jericho resident who protects the spies','Her household is preserved after she protects two Israelite spies.','Joshua 2; 6:17,22–25','She acts to preserve her family and obtains a promise from the spies. Her occupation does not erase her agency.'),
('achan','Achan','Man accused of taking forbidden goods','Son of Carmi, within Judah’s lineage.','Joshua 7; 22:20','His confession supplies the narrative explanation for defeat at Ai. The account includes severe collective punishment.'),
('othniel','Othniel','Caleb’s kinsman and captor of Debir','Son of Kenaz. He marries Caleb’s daughter Achsah.','Joshua 15:16–17','His capture of Debir links military success with a marriage arrangement. Read Achsah’s subsequent request as her own action.'),
('achsah','Achsah','Caleb’s daughter who requests springs','Daughter of Caleb and wife of Othniel.','Joshua 15:16–19','She requests water in addition to land. The short account gives her a direct role in securing resources.'),
('adoni-zedek','Adoni-zedek','King of Jerusalem in the southern coalition','He gathers four other kings against Gibeon.','Joshua 10','His coalition opposes Gibeon’s agreement with Israel. The text’s king is not independently identified by this guide.'),
('hoham','Hoham','King of Hebron in the southern coalition','Named with Adoni-zedek and three other kings.','Joshua 10:3,23','The account names him as a coalition member. It supplies little personal detail.'),
('piram','Piram','King of Jarmuth in the southern coalition','Named among the five allied kings.','Joshua 10:3,23','His role connects Jarmuth with the coalition. The narrative does not supply a detailed biography.'),
('japhia','Japhia','King of Lachish in the southern coalition','Named among the five allied kings.','Joshua 10:3,23','He belongs to the coalition defeated in the account. His name alone does not identify an excavated ruler.'),
('debir-king','Debir','King of Eglon in the southern coalition','Named among the five allied kings.','Joshua 10:3,23','This Debir is a person. He is distinct from the town of Debir in Joshua 15.'),
('jabin-joshua','Jabin','King of Hazor in Joshua’s northern campaign','He summons Jobab and other northern rulers.','Joshua 11','This is Joshua’s Jabin. The later Jabin in Judges 4 is kept separate.'),
('jobab-madon','Jobab','King of Madon in the northern coalition','Summoned by Jabin of Hazor.','Joshua 11:1','He is distinct from the Jobab listed as an Edomite king in Genesis 36.'),
('terah','Terah','Ancestor recalled at Shechem','Father of Abraham and Nahor.','Joshua 24:2','Joshua recalls an ancestral household that served other gods. Terah does not attend the present assembly.'),
('nahor','Nahor','Abraham’s brother recalled at Shechem','Son of Terah and brother of Abraham.','Joshua 24:2','This is Abraham’s brother, not the earlier Nahor who was Terah’s father. The reference is retrospective.')]
for row in new:people.append(person(*row))
active={'joshua':('Leader after Moses','He leads the crossing, campaigns, allotments, and covenant assembly.'),'caleb':('Claimant of Hebron','He recalls the scouting mission and asks Joshua for Hebron.'),'eleazar':('Priest at the allotments','He helps oversee inheritance and dies at the book’s close.'),'phinehas':('Leader of the altar inquiry','He leads the delegation that hears the eastern tribes’ explanation.')}
chapters=[]
for n,row in enumerate(rows,1):
 title,summary,meaning,pids,locs,lds=row.split('|');locs=locs.split(',')
 refs=['web','yale-12','atlas-canaan']+(['hazor-study','hazor-project'] if n==11 else [])
 route={3:['shittim','jordan'],4:['jordan','gilgal'],10:['gilgal','gibeon','beth-horon','azekah'],22:['shiloh','gilead']}.get(n,[])
 chapters.append(dict(chapter=n,title=title,summary=summary,meaning=meaning,people=pids.split(','),places=locs,sourceIds=refs,lds=dict(text=lds,sourceIds=['lds-joshua']),eventOrder=n,dateLabel='Chapter order · historical year uncertain',historicalNote='Read the biblical account beside independent evidence. A named place does not prove an event or date.',mapNote='Markers show named places and approximate regions. They do not establish exact campaign roads, tribal boundaries, or the date of a conquest.',route=route,routeEvidence='A simplified line connects the named sequence in this chapter. It omits uncertain intermediate places and does not trace an excavated road.'))
text=scripture('joshua','JOS',24)
new_ids={r[0] for r in new}
for c in chapters:
 chapter_text=' '.join(v['text'] for v in text[str(c['chapter'])])
 for p in people:
  if p['id'] in new_ids:continue
  name=p['name'].split(' / ')[0]
  if re.search(r'\b'+re.escape(name)+r'\b',chapter_text) and p['id'] not in c['people']:c['people'].append(p['id'])
for p in people:
 pid=p['id'];chap=[str(c['chapter']) for c in chapters if pid in c['people']]
 p.update(placeIds=[],linkNames=[],sourceIds=['web'],life='Historical birth and death years are not securely known.')
 p['placeIds']={'joshua':['shittim','gilgal','shiloh','shechem'],'rahab':['jericho'],'caleb':['hebron'],'othniel':['debir-town'],'achsah':['debir-town'],'eleazar':['shiloh'],'phinehas':['gilead'],'adoni-zedek':['jerusalem'],'hoham':['hebron'],'piram':['jarmuth'],'japhia':['lachish'],'jabin-joshua':['hazor']}.get(pid,[])
 if pid not in {r[0] for r in new}:
  p['passages']='Joshua '+', '.join(chap)
  if pid in active:p['role'],p['meaning']=active[pid]
  elif pid in ['mahlah','noah-daughter','hoglah','milcah-daughter','tirzah']:
   p['role']='Daughter of Zelophehad who receives inheritance';p['meaning']='She receives an inheritance under the earlier ruling. This book records the allocation, not a new legal petition.'
  elif pid in ['reuben','simeon','levi','judah','benjamin','ephraim','manasseh','zebulun','issachar','dan','naphtali','gad','asher','joseph']:
   p['role']='Ancestor recalled through a tribal name';p['meaning']='The name identifies an ancestral line or tribal community. The portrait does not place the ancestor at the allotment assembly.'
  else:p['meaning']='The book recalls this earlier figure. The reference does not place that person in Joshua’s present assembly.'
 if pid in ['jacob','esau','abraham']:p['name']=p['name'].split(' / ')[0]
finish(dict(id='joshua',bibleCode='JOS',name='Joshua',description='Crossing · campaigns · inheritance · covenant',chapterCount=24,scripture=text,chapters=chapters,people=people,places=places,sources=sources,review=dict(date='2026-10-05',scope='Chapter-level events and selected named people. Campaign claims remain separate from site evidence. Tribal portraits recall ancestors.',nextBook='judges')))

