"""Nehemiah: reviewed text, plain chapter notes, and distinct named people."""
import json
from book_common import OUT,source,person,place,scripture,finish

rows=[
('News of broken walls','Hanani reports that Jerusalem has broken walls and burned gates. Nehemiah weeps, fasts, and prays.','Nehemiah includes his own family when he confesses sin. He asks for help before approaching the king.','nehemiah,hanani-nehemiah,moses','susa,jerusalem'),
('Permission to rebuild','Artaxerxes grants Nehemiah letters and wood. Nehemiah checks the walls at night before asking people to build.','Nehemiah asks for specific help. His quiet inspection lets him see the damage before sharing his plan.','nehemiah,artaxerxes-ezra,asaph-forest,sanballat,tobiah-nehemiah,geshem','susa,jerusalem'),
('Neighbors repair the walls','Priests, families, and workers repair different sections. Shallum and his daughters join the work. Some nobles refuse.','The list names work beside homes as well as gates. Many people share the task.','eliashib-nehemiah,wall-builders,shallum-daughters,meremoth,meshullam-berechiah,nehemiah-azbuk,david','jerusalem,jericho,gibeon,mizpah'),
('Builders keep watch','Sanballat and Tobiah mock the builders. Threats bring guards, weapons, and a trumpet signal to the work.','The builders pray and set guards. The trumpet lets people gather when danger reaches a distant section.','nehemiah,sanballat,tobiah-nehemiah,wall-builders','jerusalem,samaria,ashdod'),
('Families lose land and freedom','Families lack food and borrow money. Some children become servants. Nehemiah orders lenders to return land and stop charges.','Danger also comes from neighbors who demand payment. Nehemiah gives up the governor’s food allowance to ease the burden.','nehemiah,debt-families,artaxerxes-ezra','jerusalem'),
('Letters, threats, and a finished wall','Nehemiah rejects meetings and a false warning. The wall is finished in fifty-two days. Tobiah still sends threats.','Tobiah has family ties with people inside Judah. Letters carry news between them despite the finished wall.','nehemiah,sanballat,tobiah-nehemiah,geshem,shemaiah-delaiah,noadiah-prophetess,meshullam-berechiah','jerusalem'),
('Guards and the return register','Nehemiah puts Hanani and Hananiah in charge. An earlier list names returning families and their gifts.','The city has walls but few people and houses. Family records decide who can serve as priests.','nehemiah,hanani-nehemiah,hananiah-fortress,zerubbabel,jeshua-priest,nebuchadnezzar,returning-families,asaph-singer','jerusalem,babylon,bethlehem,jericho,bethel'),
('Ezra reads and teachers explain','Ezra reads God’s law to men and women. Teachers explain it. The people share food and make shelters for a feast.','The leaders turn weeping toward joy. People send food to those who have none prepared.','nehemiah,ezra,moses,law-teachers,sherebiah,shabbethai-nehemiah,joshua','jerusalem'),
('A prayer remembers mercy and failure','The people fast and confess. Their prayer recalls Abraham, Egypt, the wilderness, and repeated rescue after sin.','The prayer ends with a present need. Foreign kings take the land’s crops and control people and livestock.','law-teachers,sherebiah,abraham,moses,sihon,og','jerusalem,egypt'),
('Promises to support worship','Leaders seal a written promise. Families agree to keep God’s law, rest on the Sabbath, and supply the temple.','The promises name food, wood, money, and workers. Worship requires regular gifts rather than one celebration.','nehemiah,covenant-families,jeshua-azaniah,sherebiah,moses,aaron,levi','jerusalem'),
('Families move into Jerusalem','One family in ten is chosen to live in Jerusalem. Volunteers also move there. The list names workers and nearby towns.','Living in the city changes where families farm and work. Singers, guards, and temple workers need daily support.','city-settlers,shabbethai-nehemiah,asaph-singer','jerusalem,beersheba,lachish,bethel,anathoth'),
('Singers celebrate the rebuilt walls','Priests and Levites gather for the wall’s dedication. Two groups sing along the walls. Women and children join the joy.','The celebration ends with plans to supply the workers. Food gifts help singers and priests continue their service.','nehemiah,ezra,zerubbabel,jeshua-priest,eliashib-nehemiah,david,solomon,asaph-singer,aaron,wall-singers','jerusalem'),
('Nehemiah returns and changes the rules','Nehemiah removes Tobiah’s goods, restores temple gifts, and closes the gates on the Sabbath. He confronts marriages with foreign women.','He also strikes some men and pulls out their hair. His marriage rules cause conflict within families.','nehemiah,tobiah-nehemiah,eliashib-nehemiah,moses,balaam,solomon,sanballat,foreign-families-nehemiah','jerusalem,tyre,ashdod')]

prior={};known_places={}
for slug in ['genesis','exodus','numbers','joshua','1-samuel','2-samuel','1-kings','2-kings','1-chronicles','2-chronicles','ezra']:
 b=json.loads((OUT/f'{slug}.json').read_text(encoding='utf8'))
 prior.update({p['id']:p for p in b['people']});known_places.update({p['id']:p for p in b['places']})

new=[
('nehemiah','Nehemiah, son of Hacaliah','King’s cupbearer and later governor','He serves Artaxerxes and leads repairs to Jerusalem’s walls.','1–2; 4–8; 10; 12–13','He organizes guards and challenges lenders. Later, he forces changes in worship and family life.'),
('hanani-nehemiah','Hanani, Nehemiah’s brother','Messenger who later helps lead Jerusalem','He reports the city’s broken walls. Nehemiah later gives him work in the city.','1:2; 7:2','His news leads Nehemiah to pray and ask the king for help.'),
('asaph-forest','Asaph, keeper of the king’s forest','Official asked to supply wood','Nehemiah asks for a royal letter to him.','2:8','The wood is for gates, the city wall, and Nehemiah’s house.'),
('sanballat','Sanballat the Horonite','Opponent of Nehemiah’s building work','He works with Tobiah and Geshem. His daughter marries into a priest’s family.','2:10,19; 4:1–7; 6; 13:28','He mocks the builders and sends accusations. Family ties also connect him with Jerusalem’s priests.'),
('tobiah-nehemiah','Tobiah the Ammonite','Opponent with friends inside Judah','His family has marriage ties in Judah. Eliashib gives him a temple room.','2:10,19; 4; 6:1,12,14,17–19; 13:4–8','His letters threaten Nehemiah. Nehemiah later throws his goods out of the temple room.'),
('geshem','Geshem the Arabian','Opponent who asks Nehemiah to meet','He joins Sanballat’s demands and accusations.','2:19; 6:1–6','Nehemiah refuses to leave the wall work for the proposed meeting.'),
('eliashib-nehemiah','Eliashib, the high priest','Priest whose family has ties with opponents','He helps repair the Sheep Gate. His grandson marries Sanballat’s daughter.','3:1,20–21; 12:10; 13:28','His family links temple leadership with people Nehemiah opposes.'),
('wall-builders','The wall builders','Families, priests, and workers repairing the city','They build separate sections. Later, some stand guard while others work.','3–4','People from nearby towns join the repairs. Work near homes helps divide the large task.'),
('shallum-daughters','Shallum and his daughters','Family repairing a section of wall','Shallum rules half the district of Jerusalem. His daughters work with him.','3:12','The repair list names women as workers alongside their father.'),
('meshullam-berechiah','Meshullam, son of Berechiah','Builder whose daughter marries Tobiah’s son','He repairs two sections, including one across from his room.','3:4,30; 6:18','His building work and family tie place him on both sides of Nehemiah’s conflict.'),
('nehemiah-azbuk','Nehemiah, son of Azbuk','District ruler repairing part of the wall','He rules half the district of Beth Zur.','3:16','He repairs near David’s tombs and a pool. He is not Hacaliah’s son.'),
('debt-families','Families burdened by debt','Parents and children short of food and money','Some pledge fields and homes. Some children become servants to pay family debts.','5:1–5','The wives join the protest. Their need leads Nehemiah to demand changes from lenders.'),
('shemaiah-delaiah','Shemaiah, son of Delaiah','Man who urges Nehemiah to hide in the temple','Nehemiah says Tobiah and Sanballat hired him.','6:10–13','His warning could frighten Nehemiah into an act others would use against him.'),
('noadiah-prophetess','Noadiah, the prophetess','Prophet named among those who frighten Nehemiah','Nehemiah names her in a prayer about his opponents.','6:14','The verse reports Nehemiah’s complaint. It gives none of her own words.'),
('hananiah-fortress','Hananiah, commander of the fortress','Official trusted with Jerusalem’s safety','Nehemiah appoints him alongside Hanani.','7:2','Nehemiah praises his faithfulness and respect for God when choosing him.'),
('law-teachers','The teachers of God’s law','Levites helping people understand the reading','They explain the law, calm the people, and help lead prayer.','8:7–11; 9:4–5','Reading aloud is followed by explanation. The people understand before they celebrate.'),
('jeshua-azaniah','Jeshua, son of Azaniah','Levite named in the covenant list','The list names his father as Azaniah.','10:9','His name differs from the priest Jeshua, whose father is Jozadak.'),
('shabbethai-nehemiah','Shabbethai, the Levite in Nehemiah','Teacher who also manages temple work','He helps explain the law. Later, he oversees work outside God’s house with Jozabad.','8:7; 11:16','Teaching and daily temple work both need his service.'),
('covenant-families','The families making the covenant','Men, women, and children agreeing to keep God’s law','They join the leaders’ written promise.','10:28–39','Their promises include marriage rules, Sabbath rest, debt release, and gifts for the temple.'),
('city-settlers','The families settling in Jerusalem','Households chosen or willing to live in the city','One in ten is chosen by lot. The people bless those who volunteer.','11','They supply people for a city that has walls but too few homes and residents.'),
('wall-singers','The singers at the wall’s dedication','Two groups giving thanks along the city walls','Ezra leads one group. Nehemiah follows the other.','12:27–43','They gather from nearby villages. Their songs join the work of builders with public thanks.'),
('foreign-families-nehemiah','The foreign wives and their children in Nehemiah','Families challenged by Nehemiah’s marriage rules','Nehemiah names women from Ashdod, Ammon, and Moab, and speaks about their children’s languages.','13:23–27','He orders the men to stop these marriages. The chapter gives no account from the wives.')]
defs={i:person(i,n,r,rel,'Nehemiah '+refs,m) for i,n,r,rel,refs,m in new}
ids=list(dict.fromkeys(pid for row in rows for pid in row[3].split(',')))
people=[dict(defs[pid] if pid in defs else prior[pid]) for pid in ids]
adapted={
 'moses':('Teacher recalled through God’s law','Nehemiah’s prayer and the public reading recall the law given through Moses.','His law guides the people’s written promises about worship and family life.'),
 'artaxerxes-ezra':('Persian king who sends Nehemiah','Nehemiah serves him as cupbearer and asks permission to rebuild Jerusalem.','He grants letters, wood, and guards. Nehemiah later returns to his court.'),
 'meremoth':('Builder named with Uriah and Hakkoz','He repairs two sections near Eliashib’s house.','His work helps join neighboring sections of Jerusalem’s wall.'),
 'ezra':('Priest and scribe who reads God’s law','He reads to an assembly of men and women. He later leads a singing group.','He reads while Levites explain. The people respond with worship, shared food, and a feast.'),
 'zerubbabel':('Earlier leader recalled in the return lists','The register names him with Jeshua among leaders of the earlier return.','His name links the present city with families who returned before Nehemiah.'),
 'jeshua-priest':('Earlier priest named in the return lists','His father is Jozadak. The priestly family list traces later generations from him.','The earlier priest is recalled through lists rather than placed at every later gathering.'),
 'nebuchadnezzar':('Babylonian king recalled in the return register','The register recalls people he carried away before their families returned.','The list connects the return with the earlier loss of homes and freedom.'),
 'returning-families':('Families and workers in the earlier return register','Nehemiah finds the list while preparing to count the people.','The list records family names, workers, gifts, and claims to priestly service.'),
 'asaph-singer':('Earlier singer recalled through his descendants','The service lists name his descendants among temple singers.','His name links later singers with earlier songs of praise.'),
 'sherebiah':('Levite who explains the law and leads prayer','He helps the people understand Ezra’s reading and joins the public prayer.','His service joins clear teaching with worship and thanks.'),
 'joshua':('Earlier leader recalled during the feast','The account compares the joyful feast with the days of Joshua, son of Nun.','His name connects the people’s feast with their earlier life in the land.'),
 'abraham':('Ancestor recalled in the prayer','The prayer recalls God choosing Abram and giving him the name Abraham.','The people remember God’s promise of land while praying about their present lack of freedom.'),
 'sihon':('Earlier king recalled in the prayer','The prayer names his land while recalling Israel’s journey.','His defeat belongs to the remembered past rather than Nehemiah’s wall repairs.'),
 'og':('Earlier king of Bashan recalled in the prayer','The prayer names his land with Sihon’s land.','The people recall earlier victories while describing their present hardship.'),
 'aaron':('Ancestor named in temple service rules','The promises and service lists name the sons of Aaron.','His family name marks the priests who receive and guard gifts for worship.'),
 'levi':('Ancestor recalled through Levite families','The service lists use his name for families working in the temple.','The Levites teach, sing, keep watch, and receive gifts for their work.'),
 'david':('Earlier king recalled in places and worship','Builders repair near his tombs. Singers follow rules and use instruments linked with him.','His name connects Jerusalem’s repairs and worship with the city’s earlier life.'),
 'solomon':('Earlier king recalled in worship and marriage warnings','The account recalls his worship rules. Nehemiah also recalls his marriages.','Nehemiah uses Solomon’s failure as a warning to men who marry foreign women.'),
 'balaam':('Earlier speaker recalled in the law reading','The reading recalls how he was hired to curse Israel.','God’s change of a curse into blessing becomes part of the people’s reason for separation.')}
scopes={'nehemiah':{1:[1],2:list(range(1,21)),5:list(range(1,20)),6:list(range(1,20)),7:[2,3],8:[9],10:[1],12:[26,47],13:list(range(1,32))},'hanani-nehemiah':{1:[2],7:[2]},'asaph-forest':{2:[8]},'eliashib-nehemiah':{3:[1,20,21],12:[10,22,23],13:[28]},'meshullam-berechiah':{3:[4,30],6:[18]},'nehemiah-azbuk':{3:[16]},'shemaiah-delaiah':{6:[10]},'noadiah-prophetess':{6:[14]},'hananiah-fortress':{7:[2]},'jeshua-azaniah':{10:[9]},'shabbethai-nehemiah':{8:[7],11:[16]},'meremoth':{3:[4,21]},'ezra':{8:[1,2,4,5,6,9,13],12:[26,36]},'jeshua-priest':{7:[7],12:[1,7,10,26]},'asaph-singer':{7:[44],11:[17,22],12:[35,46]},'sherebiah':{8:[7],9:[4,5]},'david':{3:[15,16],12:[24,36,37,45,46]},'solomon':{12:[45],13:[26]}}
aliases={'nehemiah':['Nehemiah'],'hanani-nehemiah':['Hanani'],'asaph-forest':['Asaph'],'sanballat':['Sanballat'],'tobiah-nehemiah':['Tobiah'],'geshem':['Geshem','Gashmu'],'eliashib-nehemiah':['Eliashib'],'meshullam-berechiah':['Meshullam'],'nehemiah-azbuk':['Nehemiah'],'shemaiah-delaiah':['Shemaiah'],'noadiah-prophetess':['Noadiah'],'hananiah-fortress':['Hananiah'],'jeshua-azaniah':['Jeshua'],'shabbethai-nehemiah':['Shabbethai'],'wall-builders':['builders'],'shallum-daughters':['Shallum','his daughters'],'debt-families':['their wives'],'law-teachers':['the Levites'],'covenant-families':['their wives','their sons','their daughters'],'city-settlers':['the rest of the people'],'wall-singers':['the singers'],'foreign-families-nehemiah':['foreign women','women of Ashdod'],'artaxerxes-ezra':['Artaxerxes'],'asaph-singer':['Asaph'],'jeshua-priest':['Jeshua']}
scopes.update({'shallum-daughters':{3:[12]},'debt-families':{5:[1]},'law-teachers':{8:[7,9,11],9:[4,5]},'covenant-families':{10:[28]},'city-settlers':{11:[1]},'wall-singers':{12:[28,42]},'foreign-families-nehemiah':{13:[23,26,27]}})
aliases.update({'returning-families':['the priests'],'abraham':['Abram'],'wall-builders':['builders','workers']})
scopes['returning-families']={7:[73]}
aliases.update({'meremoth':['Meremoth'],'ezra':['Ezra'],'sherebiah':['Sherebiah'],'moses':['Moses'],'david':['David'],'zerubbabel':['Zerubbabel'],'nebuchadnezzar':['Nebuchadnezzar'],'joshua':['Joshua'],'sihon':['Sihon'],'og':['Og'],'aaron':['Aaron'],'levi':['Levi'],'solomon':['Solomon'],'balaam':['Balaam']})
for p in people:
 if p['id']=='og':aliases['og']=['Og king of Bashan']
 if p['id'] in adapted:p['role'],p['relations'],p['meaning']=adapted[p['id']]
 p['sourceIds']=['web'];p['passages']='Nehemiah '+(', '.join(str(n) for n,r in enumerate(rows,1) if p['id'] in r[3].split(',')))
 p.pop('verseScope',None);p.pop('aliases',None)
 if p['id'] in scopes:p['verseScope']={str(k):v for k,v in scopes[p['id']].items()}
 p['linkNames']=aliases.get(p['id'],[])
 p['placeIds']=[] if p['id'] in ['moses','david','solomon','aaron','levi','abraham','sihon','og','balaam','joshua','nebuchadnezzar','asaph-singer'] else ['susa'] if p['id'] in ['artaxerxes-ezra','asaph-forest'] else ['susa','jerusalem'] if p['id']=='nehemiah' else ['jerusalem']
 if p['id'] in ['asaph-forest','sanballat','geshem']:p['placeIds']=[]

sources=[source('web','Nehemiah · World English Bible','https://ebible.org/engwebp/NEH01.htm','Complete public-domain reading text for thirteen chapters.','Scripture',limits='The text presents the account and its speakers’ claims. It does not independently verify every event.')]
previous=json.loads((OUT/'ezra.json').read_text(encoding='utf8'))
sources.extend(dict(s) for s in previous['sources'] if s['id'] in ['terrain','atlas','atlas-canaan'])
def reviewed(i,title,url,summary,author,year,coverage,scope,limits,category='Scholarly study',perspective='historical'):
 s=source(i,title,url,summary,category,perspective,limits);s.update(author=author,year=year,chapterCoverage=coverage,reviewed='2026-10-05: '+scope);sources.append(s)
reviewed('luther-nehemiah','Summary of Nehemiah · Luther Seminary','https://enterthebible.org/courses/nehemiah/lessons/summary-of-nehemiah/','The overview connects the walls, public law reading, settlement, and later changes.','Mark Throntveit · revised Jione Havea',2023,list(range(1,14)),'Complete main summary and introductory sections reviewed.','A scholarly teaching overview. Precise editing dates and authorship remain uncertain.')
reviewed('luther-nehemiah-background','Background of Nehemiah · Luther Seminary','https://enterthebible.org/courses/nehemiah/lessons/background-of-nehemiah/','The discussion studies how returning families understand their losses and shared past.','Mark Throntveit · revised Jione Havea',2023,[1,7,9,10],'Complete main Background section reviewed.','A named reading of community identity. Its historical outline does not verify every scene.')
reviewed('havea-nehemiah','Bible in the World: Nehemiah · Luther Seminary','https://enterthebible.org/courses/nehemiah/lessons/bible-in-the-world-nehemiah/','Havea emphasizes the workers’ choices and questions the harsh rules about foreign wives.','Jione Havea','Date not displayed',[3,5,13],'Complete main sections reviewed.','A scholarly interpretation and modern comparison. It does not recover the wives’ individual beliefs.')
m=dict(next(s for s in previous['sources'] if s['id']=='mcclellan-ezra'));m.update(id='mcclellan-nehemiah',chapterCoverage=[13],reviewed='2026-10-05: Publisher transcript paragraphs on Ezra–Nehemiah marriages reviewed again. Section begins 01:08:49. Audio and the complete interview were not reviewed.');sources.append(m)
record=source('throntveit-record','Ezra–Nehemiah · verified bibliography','https://books.google.com/books/about/Ezra_Nehemiah.html?id=VI1bMiMXLs0C','The record identifies Throntveit’s commentary, publisher, year, and ISBN.','Verified bibliography',limits='Bibliographic record reviewed. The full commentary was not read.');record.update(author='Mark A. Throntveit',year=1992,reviewed='2026-10-05: Publisher-supplied bibliographic metadata reviewed.',isbn='9780664237448');sources.append(record)
wiki=source('wiki-nehemiah','Book of Nehemiah · Wikipedia','https://en.wikipedia.org/w/index.php?oldid=1377330731&title=Book_of_Nehemiah','The opening describes the book and supplies bibliography.','Encyclopedia background',limits='Opening four paragraphs reviewed. Disputed historical claims are not adopted from this page alone.');wiki.update(author='Wikipedia contributors',year='Reviewed revision',revisionId='1377330731',revisionUrl='https://en.wikipedia.org/w/index.php?oldid=1377330731&title=Book_of_Nehemiah',license='CC BY-SA 4.0',licenseUrl='https://creativecommons.org/licenses/by-sa/4.0/',citedSourceIds=['throntveit-record'],reviewed='2026-10-05: Opening four paragraphs and cited Throntveit bibliography record reviewed.');sources.append(wiki)
base='https://www.churchofjesuschrist.org/study/manual/'
reviewed('cfm-nehemiah-2026','Come, Follow Me 2026 · Nehemiah 2; 4–6; 8',base+'come-follow-me-for-home-and-church-old-testament-2026/31?lang=eng','The lesson studies work despite opposition and help in understanding scripture.','The Church of Jesus Christ of Latter-day Saints',2026,[2,4,5,6,8],'Complete main and children’s lesson sections reviewed. Linked supplements were not reviewed.','Selected chapters only. The lesson’s detailed opposition questions concern chapters 2, 4, and 6.','Come, Follow Me','lds')
reviewed('lds-nehemiah-108','Lesson 108: Nehemiah · Seminary student material',base+'old-testament-seminary-student-material-2018/nehemiah/lesson-108?lang=eng','The lesson teaches shared work, focus, scripture study, and keeping covenants.','The Church of Jesus Christ of Latter-day Saints',2018,list(range(1,14)),'Main lesson through The Lord’s Work reviewed. Linked talks and the separate doctrinal mastery quiz were not reviewed.','Chapters 7–13 receive a brief overview rather than detailed treatment. Church application remains separate from historical evidence.','LDS study manual','lds')

place_ids=list(dict.fromkeys(pid for r in rows for pid in r[4].split(',')))
known_places['susa']=place('susa','Susa',32.189,48.257,'Nehemiah serves the king here before asking to go to Jerusalem.','Ancient city location. No precise palace room or journey road is reconstructed.',['web','atlas'])
places=[dict(known_places[pid]) for pid in place_ids]
simple={'jerusalem':'Families repair the walls, gather for the law reading, and plan daily temple service.','babylon':'The earlier return list recalls families carried away under Nebuchadnezzar.','jericho':'Men from Jericho repair a section of Jerusalem’s wall.','gibeon':'Workers from Gibeon join the wall repairs.','mizpah':'The repair list names people and district leaders from Mizpah.','samaria':'Sanballat speaks about the builders before the army of Samaria.','ashdod':'Ashdodites oppose the work. Later, Nehemiah speaks about wives and children from Ashdod.','bethlehem':'The return list includes people from Bethlehem and Netophah.','bethel':'Bethel appears in the return list and the later list of towns.','egypt':'The public prayer recalls rescue from Egypt. The praying people gather in Jerusalem.','beersheba':'The settlement list names villages extending south to Beersheba.','lachish':'Families live near Lachish and its fields after the return.','anathoth':'The town appears among the places where families settle.','tyre':'Merchants from Tyre bring fish and goods to Jerusalem on the Sabbath.'}
for p in places:
 p.pop('verseScope',None);p['sourceIds']=['web','atlas','atlas-canaan']
 if p['id'] in simple:p['summary']=simple[p['id']]

lds={1:'The Seminary lesson studies Nehemiah’s prayer after he hears about Jerusalem’s danger.',2:'Come, Follow Me asks how Nehemiah answers those who mock the work.',3:'The Seminary lesson connects each small repair with doing a part in God’s work.',4:'Come, Follow Me studies prayer and steady work during threats.',5:'What would stopping these charges change for the families?',6:'Come, Follow Me asks how Nehemiah stays focused when others try to stop him.',7:'Why do the guards need clear instructions after the wall is built?',8:'Come, Follow Me asks what helps people understand scripture, as the teachers do here.',9:'The people recall mercy during repeated failure. How does this shape their new promises?',10:'The Seminary overview studies promises about marriage and Sabbath rest.',11:'Who keeps daily temple service possible while families settle in different towns?',12:'How do the women and children join the public thanks?',13:'The Seminary overview emphasizes Sabbath rest and keeping covenants.'}
chapters=[]
for n,(title,summary,meaning,pids,locs) in enumerate(rows,1):
 hs=[s['id'] for s in sources if s['perspective']=='historical' and n in s.get('chapterCoverage',[])];ls=[s['id'] for s in sources if s['perspective']=='lds' and n in s.get('chapterCoverage',[])]
 chapters.append(dict(chapter=n,title=title,summary=summary,meaning=meaning,people=pids.split(','),places=locs.split(','),sourceIds=['web','atlas','atlas-canaan']+hs,lds=dict(text=lds[n],sourceIds=ls),eventOrder=n,dateLabel='Chapter order',historicalNote='Havea emphasizes the workers’ own choices.' if n in [3,5] else 'Havea questions the rules about foreign wives. McClellan connects them with protecting group identity.' if n==13 else 'Throntveit connects wall repairs, public teaching, and daily worship.',mapNote='Town markers show named places. The city’s gates and individual wall sections are not mapped.',route=[],routeEvidence='The map does not reconstruct a precise road or wall circuit.'))
finish(dict(id='nehemiah',bibleCode='NEH',name='Nehemiah',description='Walls · family debts · God’s law · daily worship',chapterCount=13,scripture=scripture('nehemiah','NEH',13),chapters=chapters,people=people,places=places,sources=sources,review=dict(date='2026-10-05',scope='All 406 scripture verses reviewed. Selected leaders and groups have profiles. Namesakes have restricted links. Exact wall sections and uncertain journeys remain unmapped.',nextBook='esther')))
