"""Job: reviewed chapter studies with each speaker's claims identified."""
import json
from book_common import OUT,source,person,scripture,finish
rows=[
('Job loses his children and wealth','Satan questions Job’s reasons for serving God. Four messengers report losses. Job mourns and worships.','Job’s good life does not protect his family from disaster.'),
('Illness and silent friends','Job suffers painful sores. His wife urges him to renounce God. Three friends sit silently with him.','The friends first share Job’s grief before they try to explain it.'),
('Job wishes he had not been born','Job curses the day of his birth. He asks why people in pain must keep living.','His speech gives words to grief that his earlier worship did not remove.'),
('Eliphaz explains suffering through guilt','Eliphaz recalls Job’s help for others. He claims innocent people do not perish.','Eliphaz’s claim conflicts with the opening account, which calls Job blameless.'),
('Eliphaz urges Job to accept correction','Eliphaz urges Job to seek God. He promises safety, children, and long life after correction.','His promises assume that Job’s losses began with wrongdoing.'),
('Job asks his friends for kindness','Job describes pain beyond his strength. He compares his friends to streams that disappear when needed.','He asks them to show his error instead of condemning his desperate words.'),
('Job addresses God in his pain','Job describes sleepless nights and painful skin. He asks God to leave him alone.','He keeps speaking to God while questioning why his short life receives constant scrutiny.'),
('Bildad blames wrongdoing','Bildad suggests Job’s children died for their sins. He promises renewed success if Job is upright.','Bildad turns a family’s deaths into an accusation.'),
('Job asks who could judge his case','Job describes God’s power over mountains, stars, and seas. He seeks someone to hear both sides.','He fears that unequal power prevents a fair hearing.'),
('Job asks why his maker harms him','Job recalls how God formed his body and gave him life. He asks why God now opposes him.','He asks for an explanation instead of accepting his friends’ verdict.'),
('Zophar demands that Job change','Zophar says Job deserves worse. He promises relief if Job removes wrongdoing from his home.','His confidence leaves little room to hear Job’s claim of innocence.'),
('Job challenges his friends’ wisdom','Job says he understands as much as his friends. He points to robbers who live safely.','He uses what he sees to challenge their claim that wrongdoing always brings immediate loss.'),
('Job seeks a hearing with God','Job accuses his friends of speaking falsely for God. He asks God to hear his case.','WEB reads verse 15 as having no hope. The King James Bible reads it as trust. Both retain Job’s resolve to defend himself.'),
('Job asks whether the dead live again','Job compares short human life with a tree that can grow again. He asks God to remember him.','The question about life after death appears within his fear of losing hope.'),
('Eliphaz condemns Job’s words','Eliphaz says Job’s own words prove guilt. He describes the fear and loss awaiting wicked people.','Eliphaz treats Job’s protest as evidence against him.'),
('Job calls his friends poor comforters','Job says he would strengthen them if their places were reversed. He asks for a witness in heaven.','He wants someone to support his case instead of adding blame.'),
('Job sees his hope nearing the grave','Job describes broken plans and public shame. He asks where his hope can go.','His friends’ promised bright future does not answer the darkness he experiences.'),
('Bildad describes the wicked person’s ruin','Bildad describes traps, disease, lost children, and a forgotten name. He calls this the wicked person’s fate.','His description echoes Job’s losses and deepens the accusation.'),
('Job asks for pity and a defender','Job describes relatives, servants, and friends turning away. He declares that his Redeemer lives.','He wants his words preserved and someone to support his claim.'),
('Zophar says wicked success ends quickly','Zophar describes stolen wealth turning into suffering. He says wicked people cannot keep their success.','His argument depends on a link between wealth, guilt, and ruin that Job will dispute.'),
('Job points to wicked people who prosper','Job describes wicked people growing old with safe homes and thriving children. He challenges his friends’ answers.','Their rule fails to explain lives where wrongdoing and comfort appear together.'),
('Eliphaz names sins he assumes Job committed','Eliphaz accuses Job of withholding food, clothing, and help. He urges Job to return to God.','The accusations grow more specific, though Eliphaz supplies no account of witnessing them.'),
('Job searches for God’s court','Job wants to present his case to God. He cannot find him, but insists he kept his commands.','Job’s confidence about his conduct stands beside his fear of God’s power.'),
('Job describes the suffering of the poor','Job describes stolen fields, hungry workers, and people without shelter. He asks why justice seems delayed.','The argument widens beyond his own pain to people harmed by others.'),
('Bildad questions human purity','Bildad says God rules above and even the stars lack purity before him. He compares people to worms.','His brief answer offers no direct help with Job’s examples of injustice.'),
('Job describes power beyond human knowledge','Job first asks how Bildad has helped him. He describes God’s power over sky, sea, and death.','Knowing that God is powerful does not settle their dispute about justice.'),
('Job holds to his innocence','Job refuses to admit the friends are right about him. He then describes the fate of oppressors.','He rejects their verdict while continuing to discuss judgment against wrongdoing.'),
('Where can wisdom be found?','A poem describes miners finding hidden metals. It asks where wisdom lies and says God knows its way.','Skill at finding treasure does not give people complete understanding.'),
('Job remembers respect and service','Job recalls public honor and his children nearby. He remembers helping widows and people in need.','He connects his former standing with care for others.'),
('Job describes shame and unanswered cries','Job contrasts former respect with mockery and pain. He says his calls to God receive no answer.','His changed treatment adds public humiliation to his physical suffering.'),
('Job gives his final defense','Job lists wrongs he says he avoided. He describes fairness toward servants, generosity, and welcome for strangers.','He asks for a written charge and a chance to answer it.'),
('Elihu begins after the others fall silent','Elihu becomes angry with Job and his three friends. He says youth does not prevent understanding.','He waited for older speakers but now claims they failed to answer.'),
('Elihu says suffering can teach','Elihu says God speaks through dreams and pain. He describes rescue through a messenger and renewed health.','This is Elihu’s explanation for suffering, given before God speaks.'),
('Elihu defends God’s justice','Elihu says God treats rich and poor without favor. He accuses Job of adding rebellion to sin.','His defense of justice becomes another charge against Job.'),
('Elihu challenges Job’s complaint','Elihu says human choices affect other people. He claims pride prevents cries for help from being heard.','He treats silence as a failure in the sufferer’s response.'),
('Elihu describes correction and the storm','Elihu says suffering opens people’s ears to instruction. He describes rain, clouds, and lightning.','His speech moves from explaining human pain to describing God’s work in nature.'),
('Elihu asks Job to consider God’s works','Elihu describes thunder, snow, and changing weather. He asks whether Job understands their workings.','His final questions prepare for the change from human debate to God’s speech.'),
('The Lord answers from the whirlwind','The Lord questions Job about earth, sea, dawn, weather, stars, and animals.','The answer draws Job into a world much larger than his dispute.'),
('The Lord describes wild animals','The Lord asks about goats, wild donkeys, oxen, ostriches, horses, hawks, and eagles.','These creatures have strength and freedom that people cannot command.'),
('Job falls silent and hears about behemoth','Job places his hand over his mouth. The Lord questions his judgment and describes behemoth’s strength.','The creature’s power challenges Job’s ability to govern the world he questions.'),
('The Lord describes Leviathan','The Lord describes Leviathan’s scales, strength, and frightening breath. Human tools cannot subdue it.','The poem presents power that exceeds human control.'),
('Job answers and prays for his friends','Job answers the Lord. The Lord rebukes the three friends. Job prays for them and receives renewed prosperity.','The friends need the prayer of the man they accused. Job’s daughters receive an inheritance.')]
defs=[
('job','Job','Man who protests suffering while seeking God','His losses lead to long exchanges with Eliphaz, Bildad, Zophar, and Elihu.','He challenges blame, asks for a hearing, and later prays for his friends.'),
('job-wife','Job’s wife','Wife who speaks during Job’s illness','She urges him to renounce God and die. Job later mentions her distress with his breath.','Her few words show grief reaching beyond Job himself.'),
('eliphaz-job','Eliphaz, Job’s friend','Temanite friend who speaks first','He joins Bildad and Zophar in visiting Job. The Lord later addresses his wrong words.','His certainty about guilt grows into specific accusations against Job.'),
('bildad','Bildad','Shuhite friend who appeals to earlier generations','He joins Eliphaz and Zophar and speaks three times before the debate ends.','He explains loss through wrongdoing and struggles to hear Job’s different account.'),
('zophar','Zophar','Naamathite friend who urges Job to change','He speaks twice and later joins the offering the Lord commands.','His answers insist that wicked success is brief, which Job disputes.'),
('elihu-job','Elihu, the younger speaker','Buzite speaker who speaks after the three friends','He is Barachel’s son, from Ram’s family. He waited because the others were older.','He offers another explanation of pain but receives no recorded answer from Job.'),
('barachel-family-job','Barachel and Ram’s family','Father and family named when Elihu enters','The introduction calls Elihu Barachel’s son and names Ram’s family.','The names identify the new speaker’s family rather than another turn in the debate.'),
('job-first-children','Job’s first children','Seven sons and three daughters lost in the opening account','They share feasts. A messenger reports their deaths when a strong wind destroys the house.','Their deaths make Job’s loss a family tragedy beyond the loss of wealth.'),
('job-messengers','The surviving messengers','Four survivors who report successive disasters','They report stolen animals, fire, dead servants, and the collapse that killed Job’s children.','Their closely spaced reports leave Job no pause between losses.'),
('sabeans-job','The Sabeans in Job','Raiders who take oxen and donkeys','A messenger reports that they attack and kill the servants tending the animals.','Their attack begins the series of reports that overturn Job’s household.'),
('chaldeans-job','The Chaldean raiders in Job','Three bands who take the camels','A messenger reports that they kill servants and carry off the camels.','This attack joins the other losses before Job hears about his children.'),
('jemimah','Jemimah','First named daughter in Job’s later family','Her sisters are Keziah and Keren Happuch. Their father gives them an inheritance with their brothers.','The ending names the daughters and records their place in the family’s property.'),
('keziah','Keziah','Second named daughter in Job’s later family','Her sisters are Jemimah and Keren Happuch. She shares the inheritance granted to them.','Her name gives an individual place to one of the children in the ending.'),
('keren-happuch','Keren Happuch','Third named daughter in Job’s later family','Her sisters are Jemimah and Keziah. She receives an inheritance among her brothers.','The ending records her name and her share of family property.'),
('job-later-sons','Job’s later sons','Seven sons mentioned in the ending','They have three named sisters. Job lives to see four generations of descendants.','The later household belongs to the renewed life described after Job’s prayer.'),
('job-siblings','Job’s brothers, sisters, and acquaintances','Visitors who comfort Job after the debate','They eat with him in his house and bring money and gold rings.','Their gifts and company give practical form to comfort.'),
('satan-job','Satan in Job’s opening scene','Accuser who challenges Job’s motives','He claims Job serves God because of protection. He later attacks Job’s health.','His challenge sets up the question of faith when rewards disappear.')]
people=[person(i,n,r,rel,'Job',m) for i,n,r,rel,m in defs]
g=json.loads((OUT/'genesis.json').read_text(encoding='utf8'))
people.append(dict(next(p for p in g['people'] if p['id']=='adam')))
aliases={'job-wife':['his wife','my wife'],'eliphaz-job':['Eliphaz'],'elihu-job':['Elihu'],'barachel-family-job':['Barachel','Ram'],'job-first-children':['his sons','his daughters','Your sons','your daughters'],'job-messengers':['a messenger'],'sabeans-job':['Sabeans'],'chaldeans-job':['Chaldeans'],'keren-happuch':['Keren Happuch'],'job-later-sons':['seven sons'],'job-siblings':['all his brothers','all his sisters'],'satan-job':['Satan']}
passages={'job':'Job 1–42','job-wife':'Job 2:9–10; 19:17; 31:10','eliphaz-job':'Job 2:11; 4–5; 15; 22; 42:7–9','bildad':'Job 2:11; 8; 18; 25; 42:9','zophar':'Job 2:11; 11; 20; 42:9','elihu-job':'Job 32–37','barachel-family-job':'Job 32:2, 6','job-first-children':'Job 1:2, 4–5, 13, 18–19','job-messengers':'Job 1:14–19','sabeans-job':'Job 1:15','chaldeans-job':'Job 1:17','jemimah':'Job 42:14–15','keziah':'Job 42:14–15','keren-happuch':'Job 42:14–15','job-later-sons':'Job 42:13, 16','job-siblings':'Job 42:11','satan-job':'Job 1:6–12; 2:1–7','adam':'Job 31:33; Genesis 3:8–13'}
scopes={'job-wife':{2:[9],19:[17],31:[10]},'barachel-family-job':{32:[2,6]},'job-first-children':{1:[4,13,18,19]},'job-messengers':{1:list(range(14,20))},'job-later-sons':{42:[13]},'job-siblings':{42:[11]},'adam':{31:[33]}}
for p in people:
 p['sourceIds']=['web'];p['placeIds']=[];p.pop('aliases',None);p.pop('verseScope',None)
 p['passages']=passages[p['id']]
 if p['id'] in aliases:p['linkNames']=aliases[p['id']]
 if p['id'] in scopes:p['verseScope']={str(k):v for k,v in scopes[p['id']].items()}
sources=[dict(next(s for s in g['sources'] if s['id']==i)) for i in ['web','atlas','atlas-canaan']]
def reviewed(i,title,url,summary,author,year,coverage,scope,limits,category='Scholarly study',perspective='historical'):
 publisher='Luther Seminary' if 'enterthebible.org' in url else 'Eerdmans' if 'eerdword.com' in url else 'Bible.org' if 'net.bible.org' in url else 'Mormon Stories' if 'mormonstories.org' in url else 'Wikipedia' if 'wikipedia.org' in url else 'The Church of Jesus Christ of Latter-day Saints'
 s=source(i,title,url,summary,category,perspective,limits);s.update(author=author,publisher=publisher,year=year,chapterCoverage=coverage,reviewed=dict(date='2026-10-05',scope=scope));sources.append(s);return s
reviewed('luther-job','Summary of Job · Luther Seminary','https://enterthebible.org/courses/job/lessons/summary-of-job/','Simundson and Schifferdecker stress the different speakers and their conflicting answers about suffering.','Daniel Simundson · revised Kathryn M. Schifferdecker',2024,list(range(1,43)),'Complete main Summary, So What, Where, Who, When, What, and How sections reviewed.','Literary teaching overview. It supplies no precise date or location for Job’s life.')
reviewed('luther-job-background','Background of Job · Luther Seminary','https://enterthebible.org/courses/job/lessons/background-of-job/','The authors discuss possible links between Job and questions raised during or after the exile.','Daniel Simundson · revised Kathryn M. Schifferdecker',2024,[],'Complete main background text reviewed.','Possible writing context, not evidence that the narrated events happened during the exile.')
reviewed('luther-job-issues','Introductory Issues in Job · Luther Seminary','https://enterthebible.org/courses/job/lessons/introductory-issues-in-job/','The study considers harmful comfort, competing explanations, and Job’s persistent cries to God.','Daniel Simundson · revised Kathryn M. Schifferdecker',2024,list(range(1,43)),'Sections Cause of suffering through The nature of God reviewed. The Satan section was not retrieved.','Uz has no secure location in this review. Interpretations of the final speeches differ.')
reviewed('seow-job-excerpt','Job 1–21: Interpretation and Commentary · introduction excerpt','https://eerdword.com/excerpt-from-c-l-seows-job-1-21-interpretation-and-commentary-illuminations/','Seow distinguishes the patient Job of the opening from the protesting Job in the speeches.','C. L. Seow · Eerdmans',2013,list(range(1,22)),'Complete publisher-authorized introduction excerpt, paragraphs 1–11, reviewed.','The full commentary was not read. The excerpt provides literary context rather than verse-by-verse review.')
reviewed('net-job-13','NET Bible notes · Job 13:15','https://classic.net.bible.org/verse.php?book=Job&chapter=13&theme=false&verse=15','The note explains the Hebrew readings behind translations expressing either hope or no hope.','NET Bible translators · Bible.org','Classic NET notes',[13],'Translation comparisons and translator notes 1–3 reviewed.','Original Hebrew was not copied from automatic captions. The note presents several possible readings.')
reviewed('mcclellan-job','Job and the problem of suffering · McClellan interview','https://www.mormonstories.org/how-thoughtful-mormons-stay-dan-mcclellan-part-3/','McClellan places Job among biblical discussions of why good people suffer and wicked people prosper.','Dan McClellan · Mormon Stories',2023,[1,2,3,21,24],'Original publisher transcript at 00:36:07–00:36:33 reviewed for the introduction of Job’s question.','The transcript mishears theodicy as the Odyssey. Only the clear discussion of Job’s question is paraphrased. Audio and the full interview were not reviewed.','McClellan commentary')
w=reviewed('wikipedia-job','Book of Job · reviewed Wikipedia revision','https://en.wikipedia.org/w/index.php?title=Book_of_Job&oldid=1377093894','The article outlines Job’s speeches and points readers to further scholarship.','Wikipedia contributors',2026,[],'Opening paragraphs and the Seow bibliography entry reviewed. Seow’s publisher excerpt was checked separately.','Encyclopedia background only. Disputed dates and interpretations require primary scholarly review.','Encyclopedia')
w.update(revisionId=1377093894,license='CC BY-SA 4.0',licenseUrl='https://creativecommons.org/licenses/by-sa/4.0/',citedSourceIds=['seow-job-excerpt'])
base='https://www.churchofjesuschrist.org/study/'
cfm=[1,2,3,4,5,8,11,12,13,14,16,19,21,22,23,24,31,38,39,40,42]
reviewed('cfm-job-2026','Come, Follow Me 2026 · Job',base+'manual/come-follow-me-for-home-and-church-old-testament-2026/33?lang=eng','The lesson studies faith, helpful friendship, resurrection, and God’s wider view.','The Church of Jesus Christ of Latter-day Saints',2026,cfm,'Complete main and children’s lesson sections reviewed. Coverage follows named reading blocks and specific discussion passages.','Linked Scripture Helps, talks, videos, and other scriptures were not reviewed. The lesson treats the opening conversation as poetry, not an actual bargain.','Come, Follow Me','lds')
reviewed('lds-job-111','Lesson 111: Job 1–16 · Seminary student material',base+'manual/old-testament-seminary-student-material-2018/job/lesson-111?lang=eng','The lesson contrasts Job’s suffering with his friends’ false accusations.','The Church of Jesus Christ of Latter-day Saints',2018,list(range(1,17)),'Complete main lesson and quiz text reviewed. Linked media were not reviewed.','Some chapters receive only a general summary. The lesson affirms a historical Job through religious sources. This is Church teaching, not independent historical verification.','LDS study manual','lds')
reviewed('lds-job-112','Lesson 112: Job 17–42 · Seminary student material',base+'manual/old-testament-seminary-student-material-2018/job/lesson-112?lang=eng','The lesson connects Job’s hope with resurrection and God’s plan.','The Church of Jesus Christ of Latter-day Saints',2018,list(range(17,43)),'Complete main lesson, embedded teaching excerpts, and quiz text reviewed.','Chapters 20–37 receive a brief general overview. Linked talks and videos were not reviewed. Later teaching remains distinct from the passage’s wording.','LDS study manual','lds')
prior=json.loads((OUT/'2-kings.json').read_text(encoding='utf8'))
jordan=dict(next(p for p in prior['places'] if p['id']=='jordan'))
jordan.update(name='Jordan River',summary='The behemoth poem names the Jordan when describing a swelling river.',limits='Reference marker for the river. Job’s home and the creature’s location are not placed here.',sourceIds=['web','atlas-canaan'])
lds={1:'Come, Follow Me reads the heavenly exchange as poetry about an accuser’s challenge.',2:'Come, Follow Me asks why faith should continue when expected rewards disappear.',3:'Come, Follow Me allows questions and faith to remain together during suffering.',4:'Come, Follow Me asks readers to examine the friends’ claim that pain proves guilt.',5:'Come, Follow Me questions the friends’ explanation that God is punishing Job.',8:'Come, Follow Me asks what goes wrong when friends explain pain through blame.',11:'Come, Follow Me questions Zophar’s claim that Job’s pain comes from wrongdoing.',12:'Come, Follow Me asks what Job knows about God while challenging his friends.',13:'Come, Follow Me follows the King James Bible’s reading about trusting God. WEB follows the other reading noted above.',14:'Come, Follow Me connects Job’s question about death with resurrection through Jesus Christ.',16:'Come, Follow Me asks how friends can strengthen someone instead of adding blame.',19:'Come, Follow Me reads Job’s Redeemer as Jesus Christ and invites reflection on resurrection.',21:'Come, Follow Me studies the contrast between wicked success and faithful suffering.',22:'Come, Follow Me uses Eliphaz’s accusation to ask how friends can offer better help.',23:'Come, Follow Me connects Job’s search with faith during unanswered questions.',24:'Come, Follow Me asks how Restoration scripture helps readers think about suffering.',31:'Come, Follow Me recalls Job’s repeated request for God to answer him.',38:'The Seminary lesson connects the joyful sons of God with life before birth.',39:'Come, Follow Me asks how the creatures in God’s speech change the reader’s view.',40:'Come, Follow Me asks readers to consider God’s creations from different views.',42:'The Seminary lesson connects Job’s prayer and renewed life with hope after loss.'}
questions={6:'Job asks for kindness before a verdict. How could his friends answer that request?',7:'Job speaks directly to God about pain. What does he ask God to change?',9:'Job wants someone to hear both sides. What prevents him from feeling heard?',10:'Job recalls the care that formed him. Why does his present pain make that memory difficult?',15:'Eliphaz treats protest as proof of guilt. What happens when listeners make that assumption?',17:'Job’s plans have broken apart. What kind of help could reach him now?',18:'Bildad describes the loss of a name and children. How might Job hear those words?',20:'Zophar links wickedness with brief success. What evidence would challenge his claim?',25:'Bildad speaks about human weakness. Does his answer address what Job asked?',26:'Job asks how Bildad helped him. What separates an impressive speech from useful comfort?',27:'Job refuses a false confession. Why would admitting his friends are right matter?',28:'The poem separates treasure from wisdom. What can skill and wealth fail to teach?',29:'Job remembers helping people in need. How does that memory answer Eliphaz’s accusations?',30:'Job’s neighbors add mockery to pain. What could they change without knowing why he suffers?',32:'Elihu waited for older speakers. Does his anger help him listen?',33:'Elihu says pain can teach. How could that idea help or hurt someone in distress?',34:'Elihu defends fairness while accusing Job. What evidence supports his charge?',35:'Elihu links unanswered cries with pride. What would Job’s earlier words challenge?',36:'Elihu promises good years after obedience. How does that promise compare with Job’s experience?',37:'Elihu asks about weather beyond human control. What changes when the next speaker is the Lord?',41:'The poem describes Leviathan beyond human control. What does that show about the limits of power?'}
chapters=[]
for n,(title,summary,meaning) in enumerate(rows,1):
 pids=['job']
 if n==1:pids+=['satan-job','job-first-children','job-messengers','sabeans-job','chaldeans-job']
 if n==2:pids+=['satan-job','job-wife','eliphaz-job','bildad','zophar']
 if n in [4,5,15,22]:pids+=['eliphaz-job']
 if n in [8,18,25]:pids+=['bildad']
 if n in [11,20]:pids+=['zophar']
 if n==19:pids+=['job-wife']
 if n==31:pids+=['job-wife','adam']
 if n in range(32,38):pids+=['elihu-job']
 if n==32:pids+=['barachel-family-job','eliphaz-job','bildad','zophar']
 if n==42:pids+=['eliphaz-job','bildad','zophar','jemimah','keziah','keren-happuch','job-later-sons','job-siblings']
 hs=[s['id'] for s in sources if s['perspective']=='historical' and n in s.get('chapterCoverage',[])]
 ls=[s['id'] for s in sources if s['perspective']=='lds' and n in s.get('chapterCoverage',[])]
 text=lds.get(n,questions[n] if n in questions else '')
 chapters.append(dict(chapter=n,title=title,summary=summary,meaning=meaning,people=pids,places=['jordan'] if n==40 else [],sourceIds=['web']+hs,lds=dict(text=text,sourceIds=ls),eventOrder=n,dateLabel='Chapter order',historicalNote=meaning,mapNote='The poem names the Jordan. This marker does not locate Job’s home.' if n==40 else 'Job’s home in Uz has no secure map location.',route=[],routeEvidence='No travel route is reconstructed.'))
finish(dict(id='job',bibleCode='JOB',name='Job',description='Loss · disputed blame · questions · renewed life',chapterCount=42,scripture=scripture('job','JOB',42),chapters=chapters,people=people,places=[jordan],sources=sources,review=dict(date='2026-10-05',scope='All 1,070 WEB verses reviewed. Speakers and claims are distinguished. Uz has no invented marker.',nextBook='psalms')))
