"""Build Zechariah with complete visions, selected reused profiles, and later readings kept separate."""
import json,sys
from book_common import ROOT,OUT,scripture,source,finish
DATE='2026-10-07'
t=scripture('zechariah','ZEC',14)
assert [len(t[str(n)]) for n in range(1,15)]==[21,13,10,14,11,15,14,23,17,12,17,14,9,21]
assert not any('\ufffd' in v['text'] for vv in t.values() for v in vv)
notes=json.loads((ROOT/'scripts/book-context-complete/zechariah.json').read_text(encoding='utf8'))
s=source('web','Zechariah · World English Bible','https://ebible.org/engwebp/ZEC01.htm','All fourteen chapters appear in the reading text.','Scripture','historical','Dated opening messages do not date every later vision. Symbolic figures and movements receive no certain historical identities or routes.')
s.update(author='World English Bible translators',publisher='eBible.org',chapterCoverage=list(range(1,15)),reviewed=dict(date=DATE,scope='All 211 verses read. Verse counts and character integrity checked.'));sources=[s]
s=source('couey-zechariah','Commentary on Zechariah 9:9-12','https://www.workingpreacher.org/commentaries/revised-common-lectionary/ordinary-14/commentary-on-zechariah-99-12','Couey explains the king’s arrival, removed weapons, and promised release of prisoners.','Scholarly study','historical','Proposed dates, Hebrew readings, and modern applications remain the author’s interpretations. Linked works were not independently reviewed.')
s.update(author='J. Blake Couey',year=2020,publisher='Luther Seminary',chapterCoverage=[9],reviewed=dict(date=DATE,scope='Complete commentary body and footnotes read. Linked Alexander book and wider biblical comparisons were not independently reviewed.'));sources.append(s)
churchChapters=[1,2,3,7,8,9,11,12,13,14]
s=source('cfm-zechariah-2026','December 7–13: “Holiness unto the Lord” · Haggai 1–2; Zechariah 1–4; 7–14','https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-old-testament-2026/50?lang=eng','The lesson studies holiness and reads selected visions through later accounts about Jesus Christ.','LDS Come, Follow Me','lds','Later Gospel and Restoration connections remain Church readings. They do not identify every unnamed figure in the original visions.')
s.update(author='The Church of Jesus Christ of Latter-day Saints',year=2026,publisher='The Church of Jesus Christ of Latter-day Saints',chapterCoverage=churchChapters,reviewed=dict(date=DATE,scope='Introduction and adult Zechariah study sections read. Coverage follows the chapters actually discussed, not every chapter in the heading. Linked talks, videos, and Scripture Helps were not separately reviewed.'));sources.append(s)
old=json.loads((OUT/'ezra.json').read_text(encoding='utf8'));hag=json.loads((OUT/'haggai.json').read_text(encoding='utf8'));jer=json.loads((OUT/'jeremiah.json').read_text(encoding='utf8'));king=json.loads((OUT/'2-kings.json').read_text(encoding='utf8'));sam=json.loads((OUT/'1-samuel.json').read_text(encoding='utf8'));song=json.loads((OUT/'song-of-solomon.json').read_text(encoding='utf8'));sam2=json.loads((OUT/'2-samuel.json').read_text(encoding='utf8'))
p=dict(next(p for p in old['people'] if p['id']=='zechariah-prophet'));p.update(name='Zechariah, son of Berechiah',role='Prophet named in the opening and dated messages',relations='The opening names Berechiah as his father and Iddo as his grandfather.',passages='Zechariah 1:1, 7; 7:1, 8',meaning='His questions make the visions’ explanations part of the account rather than assumed knowledge.',sourceIds=['web'],placeIds=['jerusalem'],linkNames=['Zechariah'],verseScope={})
people=[p]
for id in ['zerubbabel','jeshua-priest','darius-ezra']:
 p=dict(next(p for p in hag['people'] if p['id']==id));p['sourceIds']=['web']
 if id=='zerubbabel':p.update(role='Governor addressed in the promise to finish the house',relations='He is the governor also addressed by Haggai during the rebuilding.',passages='Zechariah 4:6–10',meaning='The same hands must lay the foundation and finish the work despite small beginnings.')
 elif id=='jeshua-priest':p.update(role='High priest restored in one vision and crowned in another',relations='He is Jehozadak’s son, the high priest also addressed in Haggai.',passages='Zechariah 3; 6:11',meaning='Changed clothing shows removed wrongdoing, while his future service still requires obedience.')
 else:p.update(role='Persian king whose regnal years date the opening messages',relations='He is the Persian king also named in Haggai and Ezra.',passages='Zechariah 1:1, 7; 7:1',meaning='His second and fourth regnal years supply time references without dating the later visions.')
 people.append(p)
descriptions={
 'jerusalem':'Jerusalem receives promises of rebuilding, changed conduct, protection, and worship by many nations.',
 'babylon':'Babylon appears as the place from which people must leave or have brought gifts.',
 'damascus':'Damascus appears at the beginning of the warning against northern and coastal cities.',
 'tyre':'Tyre’s stored wealth and sea power face judgment before the promised king arrives.',
 'sidon':'Sidon appears with Tyre among places addressed in the opening warning of chapter nine.',
 'gaza':'Gaza’s king faces loss after the threatened fall of Tyre.',
 'ashkelon':'Ashkelon appears among cities threatened with fear and abandonment.',
 'ashdod':'Ashdod appears where outsiders will dwell as Philistine pride is removed.',
 'ekron':'Ekron faces disappointed hope before a later promise of inclusion among God’s people.',
 'egypt':'Egypt appears in promised gathering and the warning about nations refusing to worship.',
 'gilead':'Gilead appears among places where the gathered people will live.',
 'lebanon':'Lebanon appears in gathering promises and the lament over destroyed forests.',
 'bethel':'Bethel sends visitors who ask whether their long practice of fasting should continue.',
 'olives':'The Mount of Olives appears in the extraordinary vision of rescue during the final battle.'}
places=[]
for id,summary in descriptions.items():
 q=dict(next(q for d in [jer,old,king,sam,song,sam2] for q in d['places'] if q['id']==id));q.update(summary=summary,sourceIds=['web'],limits='Approximate city or regional reference. No visionary boundaries, split mountain path, or battle route is reconstructed.');places.append(q)
summaries=['A patrol reports peace elsewhere. God promises mercy for Jerusalem and confronts scattering powers.','Jerusalem grows beyond ordinary walls. God promises protection and welcomes many nations.','Joshua receives clean clothing and instructions for service after an accusation.','The lamp vision accompanies a promise that Zerubbabel will finish the house.','A scroll judges theft and false oaths. A covered basket carries Wickedness away.','Chariots patrol the earth. Gifts from returnees become crowns linked with the temple’s future.','Visitors ask about fasting. God answers with justice and protection for vulnerable neighbors.','Safe streets, fruitful work, truthful conduct, and joyful feasts mark the restored community.','Judgment on cities comes before a lowly king, released prisoners, and further battle images.','God confronts false guidance and promises strength and gathering for the scattered flock.','A doomed flock receives care and then abandonment. Broken staffs end Favor and Union.','Jerusalem receives defense. Rescue for Judah’s tents comes before mourning by separate families.','Cleansing follows false claims. A struck shepherd scatters sheep, and surviving people undergo testing.','Terrible conflict comes before changed waters, worship by nations, and holiness on ordinary objects.']
questions=['Why does the angel question the patrol’s report of peace?','How does the promise of protection change the meaning of the measuring line?','What must Joshua still do after receiving clean clothing?','Why does the promise mention both laying the foundation and finishing the house?','What happens when the curse enters houses built to shelter their owners?','How do gifts from distant people become part of the temple’s future?','Why does the answer move from fasting dates to injured neighbors?','What do playing children show about the city’s restored life?','How does removing weapons explain the announced peace?','How does failed guidance leave the people like untended sheep?','What happens when the people responsible for care treat the flock as profit?','Why does rescue for the tents come before honor for the capital?','What does the final exchange say about the survivors’ relationship with God?','How does holiness on cooking pots change the final image of worship?']
ldsNotes={1:'The lesson connects returning to God with becoming holy.',2:'The lesson studies God dwelling among a people who become holy.',3:'The lesson uses Joshua’s changed clothing to discuss holiness and changed conduct.',7:'The lesson connects holiness with compassion and protection for injured neighbors.',8:'The lesson studies truth and peace as part of a future holy community.',9:'The lesson reads the coming king through Matthew’s later account of Jesus entering Jerusalem.',11:'The lesson connects the weighed silver with Matthew’s later account concerning Judas.',12:'The lesson reads the pierced figure through John’s account and later Revelation.',13:'The lesson connects the struck shepherd with Matthew and the wounds with Restoration scripture.',14:'The lesson uses daily objects to discuss holiness and gives later readings about Christ’s return.'}
locations={1:['jerusalem'],2:['jerusalem','babylon'],3:['jerusalem'],4:[],5:[],6:['babylon'],7:['bethel','jerusalem'],8:['jerusalem'],9:['damascus','tyre','sidon','gaza','ashkelon','ashdod','ekron','jerusalem'],10:['egypt','gilead','lebanon'],11:['lebanon'],12:['jerusalem'],13:['jerusalem'],14:['jerusalem','olives','egypt']}
chapters=[]
for n,v,title,meaning in notes:
 ids=['zechariah-prophet'] if n<=8 else []
 if n in [1,7]:ids+=['darius-ezra']
 if n in [3,6]:ids+=['jeshua-priest']
 if n==4:ids+=['zerubbabel']
 loc=locations[n]
 chapters.append(dict(chapter=n,title=title,summary=summaries[n-1],meaning=meaning,people=ids,places=loc,sourceIds=['web']+(['couey-zechariah'] if n==9 else []),lds=dict(text=(ldsNotes[n]+' ' if n in ldsNotes else '')+'Study question. '+questions[n-1],sourceIds=['cfm-zechariah-2026'] if n in churchChapters else []),eventOrder=n,dateLabel='Book order',historicalNote=meaning,mapNote='Markers locate selected geographic references. Visions and promises do not establish traveled army or return paths.' if loc else 'The vision names no securely mapped location for its objects. Symbolic movements receive no ordinary route.',route=[],routeEvidence='Visions, regional promises, and town warnings do not establish continuous traveled routes.'))
data=dict(id='zechariah',bibleCode='ZEC',name='Zechariah',description='Night visions · restored service · justice · a lowly king · shepherds · holy daily life',chapterCount=14,scripture=t,chapters=chapters,people=people,places=places,sources=sources,review=dict(date=DATE,contextReviewDate=DATE,copyReviewDate=DATE,scope='All 211 WEB verses read for fourteen original contextual explanations. Four selected profiles reuse inspected Ezra artwork. The prophet remains distinct from other Zechariahs. Later unnamed figures, ancestors, donors, and messengers do not receive invented identities.',nextBook='malachi'))
if '--ready' in sys.argv:finish(data)
else:(ROOT/'review/zechariah-draft.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
