"""Build First Corinthians from reviewed text and authored contextual readings."""
import json,copy,sys
from book_common import ROOT,OUT,scripture,source,person,finish
DATE='2026-10-07';t=scripture('1-corinthians','1CO',16)
assert [len(t[str(n)]) for n in range(1,17)]==[31,16,23,21,13,20,40,13,27,33,34,31,13,40,58,24]
assert sum(map(len,t.values()))==437
assert not any('\ufffd' in str(v) for vv in t.values() for v in vv)
notes=json.loads((ROOT/'scripts/book-context-complete/1-corinthians.json').read_text(encoding='utf8'))
sources=[]
s=source('web','1 Corinthians · World English Bible','https://ebible.org/engwebp/1CO01.htm','All sixteen chapters supply the primary text for original close readings.','Scripture','historical','Original manuscripts, authorship, dates, and detailed reconstruction of Corinthian practices were not independently verified. The tension between women speaking prophecy in chapter eleven and the instruction concerning wives in chapter fourteen remains visible. No unsupported manuscript solution is added.')
s.update(author='World English Bible translators',publisher='eBible.org',chapterCoverage=list(range(1,17)),reviewed=dict(date=DATE,scope='All 437 verses read for sixteen original contextual explanations and exact selections. Surroundings, counts, and character integrity checked.'));sources.append(s)
s=source('whitfield-1cor','Commentary on 1 Corinthians 11:23-26','https://www.workingpreacher.org/commentaries/revised-common-lectionary/maundy-thursday/commentary-on-1-corinthians-1123-26-11','Whitfield connects remembering Jesus’ gift with overcoming divisions at the shared meal.','Scholarly study','historical','This remains Whitfield’s interpretation. Exact arrival times, household arrangements, dates, original Greek word comparisons, and his cited Hays and Holladay books were not independently verified. His mistaken 10:28 and 10:29 references are not repeated.')
s.update(author='Bryan J. Whitfield',publisher='Luther Seminary',year=2019,chapterCoverage=[11],reviewed=dict(date=DATE,scope='Complete commentary body and notes read through the publisher’s indexed page text. A combined print page returned a redirect error. The separate commentary supplies the attributed reading. Related articles and cited books were not reviewed.'));sources.append(s)
lessons=[(35,[1,2,3,6],'August 21–27 · 1 Corinthians 1–7','The lesson studies unity, God’s wisdom, and the body’s sacred place.'),(36,[9,10,11,12,13,14],'August 28–September 3 · 1 Corinthians 8–13','The lesson studies helpful gifts, temptation, the sacrament, and charity.'),(37,[14,15],'September 4–10 · 1 Corinthians 14–16','The lesson studies helping the gathered church, resurrection, and baptism for the dead.')]
for num,cc,title,summary in lessons:
 s=source('cfm-nt-2023-'+str(num),title,f'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-sunday-school-new-testament-2023/{num}?lang=eng',summary,'LDS Come, Follow Me','lds','Church teaching remains distinct from the letter’s own words. Listed coverage follows actual body discussion and cited Bible verses. Linked talks, videos, manuals, and Restoration passages were not independently reviewed.')
 s.update(author='The Church of Jesus Christ of Latter-day Saints',publisher='The Church of Jesus Christ of Latter-day Saints',year=2023,chapterCoverage=cc,reviewed=dict(date=DATE,scope='Complete lesson body and included additional resources read. Lesson 36 cites 14:12 for gifts and includes 9:14 in its teaching guidance. The heading alone does not extend coverage to omitted chapters.'));sources.append(s)
acts=json.loads((OUT/'acts.json').read_text(encoding='utf8'));sources.extend(copy.deepcopy([s for s in acts['sources'] if s['id'] in ['atlas-canaan','net-acts-map']]))
rows=[
 ('acts','paul','Paul','Letter speaker who challenges division and explains his own restraint','Timothy represents his teaching. Apollos follows a different visiting plan.','1 Corinthians 1–16','His refusal of material rights supplies an example for the use of freedom.',['Paul']),
 ('matthew','jesus','Jesus Christ','The crucified and risen Lord at the center of Paul’s argument','Paul connects the shared meal and the believers’ future with him.','1 Corinthians 1–16','His death and rising challenge the group’s measures of strength, ownership, and lasting hope.',['Jesus','Christ']),
 ('acts','peter','Cephas, also called Peter','Apostle named in the dispute over teachers and among resurrection witnesses','Paul mentions his travel with a believing wife.','1 Corinthians 1; 3; 9; 15','His name appears in competing party claims that Paul refuses to accept.',['Cephas']),
 ('acts','barnabas','Barnabas','Worker named with Paul in the question about material support','Paul asks whether only they must continue working for their own needs.','1 Corinthians 9:6','His example makes the argument about support concern another worker as well as Paul.',['Barnabas']),
 ('romans','timothy','Timothy','Trusted worker whom Paul sends to remind the group of his teaching','Paul asks the believers to receive him without fear or contempt.','1 Corinthians 4:17; 16:10–11','His welcome tests whether the group honors service rather than personal rank.',['Timothy']),
 ('acts','priscilla','Priscilla','Worker who sends greetings from a shared household','Aquila greets the believers with her. A church meets in their house.','1 Corinthians 16:19','Her household greeting connects Corinth with another gathering of believers.',['Priscilla']),
 ('acts','aquila','Aquila','Worker whose household gathering sends a greeting','He and Priscilla greet the believers warmly in the Lord.','1 Corinthians 16:19','His greeting makes the letter’s wider relationships visible at its close.',['Aquila']),
 ('exodus','moses','Moses','Remembered leader named in Paul’s law and wilderness examples','Paul recalls the people’s shared passage through the sea and cloud.','1 Corinthians 9:9; 10:2','His recalled people show that shared gifts do not remove responsibility for later conduct.',['Moses']),
 (None,'apollos','Apollos','Teacher whom some believers use as a competing party name','Paul describes his watering work and later urges him to visit.','1 Corinthians 1; 3; 4; 16','His different visiting plan shows that shared service does not require identical decisions.',['Apollos']),
 (None,'chloe','Chloe','Named person whose household supplies the report of divisions','Paul identifies her household when explaining what he has heard.','1 Corinthians 1:11','Her named connection gives the complaint a stated source rather than an unnamed rumor.',['Chloe'])]
people=[]
profileChapters={'paul':list(range(1,17)),'jesus':list(range(1,17)),'peter':[1,3,9,15],'barnabas':[9],'timothy':[4,16],'priscilla':[16],'aquila':[16],'moses':[9,10],'apollos':[1,3,4,16],'chloe':[1]}
for book,pid,name,role,relations,passages,meaning,links in rows:
 p=person(pid,name,role,relations,passages,meaning)
 if book:
  old=json.loads((OUT/(book+'.json')).read_text(encoding='utf8'));p['life']=next(x for x in old['people'] if x['id']==pid)['life']
 p.update(placeIds=[],linkNames=links,verseScope={});people.append(p)
places=copy.deepcopy([p for p in acts['places'] if p['id'] in ['corinth','jerusalem','ephesus']])
for p in places:p.update(verseScope={},summary={'corinth':'Corinth names the church receiving the letter.','jerusalem':'Jerusalem is the intended destination of the collected gift.','ephesus':'Ephesus appears in Paul’s recalled danger and planned stay.'}[p['id']])
summaries=['Paul thanks the believers and challenges their competing party claims.','Paul recalls weakness and describes wisdom received through the Spirit.','Jealousy leads into shared farming, building, and temple images.','Received gifts and the apostles’ hardship challenge the hearers’ boasting.','A reported sexual relationship leads into removal and the group’s own boundary.','Lawsuits and bodily conduct lead into questions about freedom and belonging.','Paul answers written questions about marriage, different conditions, and unmarried life.','Food offered to idols raises the conflict between knowledge, freedom, and conscience.','Paul defends material support but explains his refusal to use that right.','Wilderness warnings and shared tables lead into instructions about food in different settings.','Head coverings and unequal eating lead into shared belonging and remembrance.','Varied gifts serve one body whose members need each other.','Love gives gifts their value and lasts beyond partial knowledge.','Understandable speech, interpreters, and taking turns shape the gathered group.','Received witness and arguments about changed bodies answer denial of resurrection.','The collection, travel plans, visiting workers, and greetings close the letter.']
questions=['Why does Paul answer competing party names with questions about baptism and crucifixion?','Why does Paul recall his fear rather than present an impressive speaking record?','How do planting and watering differ from giving growth?','What does the question about received gifts expose in the hearers’ boasting?','Why does Paul distinguish the group’s own boundary from judgment outside?','How can an action claimed as freedom become a source of control?','Why does Paul distinguish commands from his own judgment about unmarried life?','How does the observer’s conscience change the confident believer’s food choice?','Why does Paul defend a right that he chooses not to use?','Why does an explicit notice about food change the invited meal?','How does waiting for others answer the shame caused by unequal eating?','Why does the body give greater honor to apparently weaker members?','How does love answer the earlier jealousy and boasting?','Why do interpreters and taking turns matter for the gathered group?','How does future resurrection give meaning to present labor?','Why should the believers approve the people carrying their gift?']
teach={1:'The selected lesson teaches unity in Christ’s Church.',2:'The selected lesson teaches reliance on God’s wisdom.',3:'The selected lesson uses God’s building to teach shared work and unity.',6:'The selected lesson teaches that physical bodies are sacred.',9:'The selected lesson cites Paul’s instruction about support for gospel teachers.',10:'The selected lesson teaches escape from temptation and unity through the sacrament.',11:'The selected lesson connects self examination and the sacrament with unity.',12:'The selected lesson teaches using spiritual gifts to help others.',13:'The selected lesson teaches charity as the greatest spiritual gift.',14:'The selected lessons teach using gifts to support the gathered church.',15:'The selected lesson teaches universal resurrection and connects baptism for the dead with temple service. These later Church practices remain distinct from Paul’s brief reference.'}
lessonIds={n:['cfm-nt-2023-'+str(num) for num,cc,_,_ in lessons if n in cc] for n in range(1,17)}
chapters=[]
for n,v,title,meaning in notes:
 loc=['corinth'] if n==1 else ['ephesus'] if n==15 else ['jerusalem','ephesus'] if n==16 else []
 chapters.append(dict(chapter=n,title=title,summary=summaries[n-1],meaning=meaning,people=[pid for pid,cc in profileChapters.items() if n in cc],places=loc,sourceIds=['web']+(['whitfield-1cor'] if n==11 else []),lds=dict(text=teach.get(n,'')+(' ' if n in teach else '')+'Study question. '+questions[n-1],sourceIds=lessonIds[n]),eventOrder=n,dateLabel='Book order',historicalNote=meaning,mapNote='Selected markers show the receiving church, recalled settings, and intended destinations. No exact household or journey is assigned.',route=[],routeEvidence='Named settings do not establish exact routes or completed travel plans.'))
data=dict(id='1-corinthians',bibleCode='1CO',name='1 Corinthians',description='Unity · freedom · shared meals · gifts · love · resurrection',chapterCount=16,scripture=t,chapters=chapters,people=people,places=places,sources=sources,review=dict(date=DATE,contextReviewDate=DATE,copyReviewDate=DATE,scope='All 437 verses read for sixteen original explanations and exact Scripture selections. Ten selected profiles and three city references do not claim exhaustive coverage. Three lesson bodies retain actual passage coverage. Whitfield’s interpretation remains attributed. Original manuscripts, Greek vocabulary, authorship, dates, detailed ancient customs, and competing explanations of women’s speech or baptism for the dead were not independently verified.',nextBook='2-corinthians'))
if '--ready' in sys.argv:finish(data)
else:(ROOT/'review/1-corinthians-draft.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
