"""Reviewed Proverbs draft. Publish only after portrait and reader checks."""
import csv,json,sys
from book_common import ROOT,OUT,source,person,scripture,finish
def load(slug):return json.loads((OUT/(slug+'.json')).read_text(encoding='utf8'))
g=load('genesis');sources=[dict(next(s for s in g['sources'] if s['id']==i)) for i in ['web','atlas-canaan']]
sources[0].update(title='Proverbs · World English Bible',url='https://ebible.org/engwebp/PRO01.htm',summary='The public-domain text supplies all 31 chapters.',limits='The collection includes teaching speeches, poems, and short sayings. Chapter order does not date their composition.')
def reviewed(i,title,url,summary,author,year,coverage,scope,limits,publisher,category='Scholarly study',perspective='historical'):
 s=source(i,title,url,summary,category,perspective,limits);s.update(author=author,year=year,publisher=publisher,chapterCoverage=coverage,reviewed=dict(date='2026-10-05',scope=scope));sources.append(s);return s
base='https://enterthebible.org/courses/proverbs/lessons/'
reviewed('luther-proverbs','Summary of Proverbs · Luther Seminary',base+'summary-of-proverbs/','The authors explain poems, sayings, and learning through family and community.','James Limburg · revised Diane Jacobson',2024,list(range(1,32)),'Complete main summary reviewed. General context for the collection, not commentary on every individual verse.','The collection names several speakers and groups. Association with Solomon does not establish his authorship of every saying.','Luther Seminary')
reviewed('luther-proverbs-background','Background of Proverbs · Luther Seminary',base+'background-of-proverbs/','The authors discuss family teaching and possible training in royal courts.','James Limburg · revised Diane Jacobson',2024,[],'Complete main background reviewed.','Proposed settings for teaching do not establish dates for individual sayings.','Luther Seminary')
reviewed('fox-proverbs-record','Proverbs 1-9 · publisher record','https://yalebooks.yale.edu/book/9780300139594/proverbs-1-9/','Yale identifies Michael V. Fox’s translation and commentary.','Michael V. Fox',2000,[],'Publisher description and publication record reviewed. Commentary text not reviewed.','Bibliographic verification only. No verse interpretation is attributed to unread commentary.','Yale University Press')
w=reviewed('wiki-proverbs','Book of Proverbs · Wikipedia','https://en.wikipedia.org/w/index.php?title=Book_of_Proverbs&oldid=1378031573','The overview identifies divisions and named collections.','Wikipedia contributors',2026,[],'Opening, structure, bibliography, revision footer, and license reviewed. Fox’s cited work checked against Yale’s publisher record.','Overview and bibliography discovery. Reader explanations use scripture and reviewed named sources.','Wikipedia','Wikipedia overview')
w.update(revisionId=1378031573,revisionUrl=w['url'],license='CC BY-SA 4.0',licenseUrl='https://creativecommons.org/licenses/by-sa/4.0/',citedSourceIds=['fox-proverbs-record'])
church='https://www.churchofjesuschrist.org/study/manual/'
reviewed('cfm-proverbs','Proverbs · Come, Follow Me 2026 · lesson 37',church+'come-follow-me-for-home-and-church-old-testament-2026/37?lang=eng','The lesson teaches trust, respectful speech, and wisdom expressed through daily conduct.','The Church of Jesus Christ of Latter-day Saints',2026,[1,2,3,4,8,15,16,22,31],'Complete main lesson and children’s sections reviewed. Coverage includes assigned Proverbs chapters and the explicit reference to 8:13. Linked talks and videos not separately reviewed.','Later Church applications remain distinct from the book’s ancient speakers and original study questions.','The Church of Jesus Christ of Latter-day Saints','Come, Follow Me','lds')
helps=church+'scripture-helps-old-testament/35-proverbs-1-4-15-16-22-31-ecclesiastes-1-3-11-12?lang=eng'
reviewed('lds-proverbs-helps','Proverbs · Scripture Helps',helps,'Church notes discuss Woman Wisdom, correction, Lemuel, and the capable woman.','The Church of Jesus Christ of Latter-day Saints',2026,[1,3,8,13,15,22,31],'Main Proverbs sections reviewed, including the rod of correction and the alphabet poem. Linked works were not independently reviewed.','The note on the rod gives a modern Church application. It does not replace the physical wording of other verses.','The Church of Jesus Christ of Latter-day Saints','LDS study manual','lds')
dm=reviewed('dm-proverbs-rod','Ep. 227 – The Bible Says So w/ Dan McClellan','https://zencastr.com/z/UD11AGSm','McClellan disputes reading the rod sayings as only gentle guidance.','Dan McClellan · interview guest',2025,[23],'Publisher introduction and relevant rod-of-correction exchange reviewed in the publisher transcript.','The transcript uses generic speaker labels. Audio was not reviewed. Only the relevant exchange is used, without quotation.','Growing Up Christian','Scholar commentary');dm['group']='mcclellan'
people=[];reuse={}
def profile(i,name,role,relations,passages,meaning,coverage,aliases=None,scope=None,art=None):
 p=person(i,name,role,relations,passages,meaning);p['placeIds']=[];p['chapterCoverage']=coverage
 if aliases is not None:p['linkNames']=aliases
 if scope:p['verseScope']={str(k):v for k,v in scope.items()}
 people.append(p)
 if art:reuse[i]=art
profile('solomon','Solomon','King named in three collection headings','The opening identifies him as David’s son and Israel’s king.','Proverbs 1:1; 10:1; 25:1','His name connects the collections with remembered royal wisdom.',[1,10,25],art=('1-kings','solomon'))
profile('david','David','Father named beside Solomon','The opening uses his name to identify Solomon’s family.','Proverbs 1:1','The family name connects the opening with Israel’s earlier king.',[1],art=('1-samuel','david'))
profile('hezekiah','Hezekiah','King whose men copy sayings','Chapter 25 names his men as copying sayings associated with Solomon.','Proverbs 25:1','Their work shows sayings being collected after Solomon’s time.',[25],art=('2-kings','hezekiah'))
profile('parents-proverbs','The teaching parents','Father and mother who guide a learner','The teacher urges a son to hear both parents.','Proverbs 1:8–9; 4:1–4; 6:20–23','Their teaching prepares him to resist pressure from others.',[1,4,6],['your father','your mother','my father'],{1:[8],4:[3],6:[20]})
profile('wisdom-proverbs','Woman Wisdom','Wisdom pictured as a woman who speaks','She calls publicly, praises fair conduct, and invites learners to her table.','Proverbs 1:20–33; 8:1–36; 9:1–6','Her voice lets the poems show wisdom teaching, warning, and welcoming.',[1,8,9],['Wisdom','wisdom'],{1:list(range(20,34)),8:list(range(1,37)),9:list(range(1,7))})
profile('folly-proverbs','Woman Folly','Foolishness pictured as a woman who invites guests','She offers stolen food. Her guests do not understand the danger.','Proverbs 9:13–18','Her welcome imitates Wisdom’s invitation while leading guests toward death.',[9],['foolish woman'],{9:[13]})
profile('unfaithful-woman-proverbs','The woman in the adultery warnings','Married woman who seeks another partner','In chapter 7, she tells a young man her husband is away.','Proverbs 2:16–19; 5:3–14; 6:24–35; 7:10–23','The teacher contrasts her promises with harm to people and marriages.',[2,5,6,7],['immoral woman','adulteress','evil woman','woman'],{2:[16],5:[3],6:[24,26,32],7:[10]})
profile('young-learner-proverbs','The young man in chapter 7','Learner who follows a tempting invitation','The teacher observes him walking toward the woman’s house.','Proverbs 7:7–23','He notices the invitation without understanding where his choice leads.',[7],['young man'],{7:[7]})
profile('agur','Agur','Speaker who admits limited understanding','The heading calls him Jakeh’s son. He asks God for enough food.','Proverbs 30:1–9','His request addresses dangers he sees in both hunger and wealth.',[30])
profile('agur-named-men','Jakeh, Ithiel, and Ucal','Names in the introduction to Agur’s words','WEB names Jakeh as Agur’s father and mentions Ithiel and Ucal.','Proverbs 30:1','These names introduce the speech. The verse gives no further account of their actions.',[30],['Jakeh','Ithiel','Ucal'],{30:[1]})
profile('lemuel','Lemuel','King who recalls his mother’s teaching','His mother urges him to protect poor people and judge fairly.','Proverbs 31:1–9','Her advice connects his private habits with his public duties.',[31])
profile('lemuel-mother','Lemuel’s mother','Teacher who advises her royal son','She warns against drink that makes rulers forget people’s rights.','Proverbs 31:1–9','She tells him to speak for people who cannot defend themselves.',[31],['mother'],{31:[1]})
profile('capable-woman-proverbs','The capable woman','Woman praised for work, care, and wise speech','She manages trade, buys a field, plants a vineyard, and helps poor people.','Proverbs 31:10–31','Her family praises work that supports the household and benefits neighbors.',[31],['worthy woman'],{31:[10]})
egypt=dict(next(p for p in g['places'] if p['id']=='egypt'));egypt.update(summary='The woman mentions Egyptian linen covering her bed.',sourceIds=['web','atlas-canaan'],limits='A reference to cloth in Proverbs 7:16. It does not establish the woman’s location or a journey.')
rows=list(csv.DictReader((ROOT/'scripts/proverbs-notes.tsv').open(encoding='utf8'),delimiter='\t'));text=scripture('proverbs','PRO',31)
lessons={1:'Come, Follow Me explains fearing God as love and obedience.',2:'Come, Follow Me invites readers to seek wisdom from God.',3:'Come, Follow Me teaches trust in the Lord.',4:'Come, Follow Me connects the path image with following the Lord.',8:'Come, Follow Me points to the rejection of evil in verse 13.',13:'Scripture Helps applies the rod image to loving, consistent teaching.',15:'Come, Follow Me teaches kind words and patient answers.',16:'Come, Follow Me applies these sayings to how people communicate.',22:'Scripture Helps teaches loving correction and rejects using the rod to justify abuse.',31:'Come, Follow Me praises the woman’s strength, skill, and influence.'}
chapters=[]
for row in rows:
 n=int(row['chapter']);meaning=row['meaning']
 if n==23:meaning+=' McClellan reads the rod sayings as physical punishment.'
 hs=[s['id'] for s in sources if s['perspective']=='historical' and n in s.get('chapterCoverage',[])]
 ls=[s['id'] for s in sources if s['perspective']=='lds' and n in s.get('chapterCoverage',[])]
 chapters.append(dict(chapter=n,title=row['title'],summary=row['summary'],meaning=meaning,people=[p['id'] for p in people if n in p['chapterCoverage']],places=['egypt'] if n==7 else [],sourceIds=['web']+hs,lds=dict(text=(lessons.get(n,'')+' '+row['question']).strip(),sourceIds=ls),eventOrder=n,dateLabel='Chapter order',historicalNote=meaning,mapNote='Egypt names the cloth’s origin, not the scene’s location.' if n==7 else 'The chapter does not name a place for a map marker.',route=[],routeEvidence='No travel route is reconstructed.'))
for p in people:p.pop('chapterCoverage')
data=dict(id='proverbs',bibleCode='PRO',name='Proverbs',description='Wisdom · honest work · careful speech · fair conduct',chapterCount=31,scripture=text,chapters=chapters,people=people,places=[egypt],sources=sources,review=dict(date='2026-10-05',scope='All 915 WEB verses reviewed. Poems, named speakers, and later applications distinguished.',nextBook='ecclesiastes'))
(ROOT/'scripts/proverbs-art-reuse.json').write_text(json.dumps(reuse,indent=2)+'\n',encoding='utf8')
assert len(chapters)==31 and sum(map(len,text.values()))==915
if '--ready' in sys.argv:finish(data)
else:(ROOT/'review/proverbs-draft.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf8');print('Saved Proverbs draft: 31 chapters, 915 verses, 13 profiles.')
