"""Judges: local leaders, contested power, women’s agency, and social collapse."""
import json,re
from book_common import OUT,scripture,source,person,place,finish
J=json.loads((OUT/'joshua.json').read_text(encoding='utf-8'))
rows='''
Campaigns and remaining peoples|Judah and other tribes fight local campaigns. Caleb, Othniel, and Achsah reappear. Many Canaanite populations remain.|The opening records incomplete occupation and forced labor. It qualifies a reading of Joshua as complete removal of earlier inhabitants.|caleb,othniel,achsah,adonibezek|canaan,hebron,debir-town,jerusalem,bethel|The older manual introduces the period’s local leaders. Consider the difference between a narrative summary and each stated result.
The recurring cycle|An angel rebukes Israel. Joshua’s generation dies. Later generations serve other gods, face enemies, and receive deliverers.|The chapter gives the book’s religious explanation for recurring crises. This explanation is distinct from independent historical causes.|joshua|canaan,gilgal|Come, Follow Me studies repentance and the Lord’s repeated willingness to receive people who return.
Othniel, Ehud, and Shamgar|Othniel defeats Cushan-rishathaim. Ehud kills Eglon and leads a revolt against Moab. A short notice records Shamgar’s victory.|The leaders differ in background and tactics. The title judge includes military leadership, not only hearing legal cases.|othniel,cushan-rishathaim,ehud,eglon,shamgar|canaan,moab,jericho,jordan|The Church lesson studies deliverance and repentance. Keep its present application distinct from ancient assassination and warfare.
Deborah, Barak, and Jael|Deborah calls Barak against Sisera. The army defeats Sisera’s force near Kishon. Jael kills the fleeing commander.|Women hold decisive roles in the narrative. The account’s praise does not make its violence a present instruction.|deborah,barak,sisera,jabin-judges,jael,heber|hazor,tabor,kishon|Come, Follow Me studies Deborah’s influence and asks how faith can help other people act.
The song of Deborah|Deborah and Barak sing about the battle, participating tribes, Jael, and Sisera’s mother waiting for his return.|Poetry and the previous prose account present the conflict differently. Proposed dates for the poem remain scholarly interpretations.|deborah,barak,sisera,jael,shamgar|tabor,kishon,megiddo|The older manual studies willing service and courage. Read the poem’s celebration beside its depiction of harm.
Gideon’s call|Gideon receives a call during Midianite raids. He destroys his father’s altar and asks for signs with a fleece.|The account joins a reluctant leader with conflict in his own community. Gideon also receives the name Jerubbaal.|gideon,joash-gideon|ophrah,jezreel|Come, Follow Me studies trust when God’s instructions differ from what a person expects.
Gideon’s reduced force|Gideon’s army is reduced to three hundred. A dream encourages him. Trumpets, jars, and torches precede the enemy’s flight.|The story attributes victory to God rather than numbers. Its troop figures are narrative claims, not measured military records.|gideon,oreb,zeeb|jezreel,jordan|The Church lesson studies reliance on God. Consider how confidence changes when ordinary advantages are removed.
Victory, revenge, and the ephod|Gideon pursues Zebah and Zalmunna, punishes towns that refused help, and kills the kings. He rejects kingship but makes an ephod.|The closing account complicates a simple heroic portrait. The ephod becomes a snare, and Gideon’s household introduces the next conflict.|gideon,zebah,zalmunna,jether,abimelech-judges|succoth,penuel,ophrah|Come, Follow Me studies trust. The older manual also warns about the ephod and acknowledges the account’s change after victory.
Abimelech and Jotham’s warning|Abimelech kills his brothers and becomes king at Shechem. Jotham warns through a tree fable. Civil conflict ends with Abimelech’s death.|The fable questions destructive rule. The account links ambition, family killing, and retaliation against the community.|abimelech-judges,jotham-gideon,gaal,zebul,gideon|shechem,gerizim,thebez|The manual studies Jotham’s warning. Consider what happens when people give authority to a leader who threatens them.
Tola, Jair, and renewed distress|Brief notices record Tola and Jair. Israel serves several gods and faces Philistine and Ammonite pressure. The people confess and remove foreign gods.|The chapter combines short leadership records with the repeated crisis pattern. A stated term of service does not establish calendar dates.|tola,jair|canaan,gilead,ammon|The manual studies the return to God. Consider the actions that make a stated change visible.
Jephthah and his daughter|Gilead’s elders recall the expelled Jephthah to fight Ammon. He makes a vow. His only daughter greets him after victory.|The text says he fulfills his vow but does not narrate the act in detail. Its burnt-offering language produces a tragic reading.|jephthah,jephthah-daughter,moses,sihon,balak|gilead,ammon,heshbon|The older manual favors lifelong dedication over death. Hayes reads the story as sacrifice. The guide preserves this disagreement.
Conflict at the river|Jephthah’s men fight Ephraim and use pronunciation at Jordan crossings to identify fugitives. Short notices record Ibzan, Elon, and Abdon.|Speech becomes a lethal test of group identity. The episode deepens the book’s pattern of violence between related communities.|jephthah,ibzan,elon,abdon|gilead,jordan|The manual compares the conflict with Gideon’s earlier response. Consider how an insult can become collective harm.
Samson’s birth announced|An angel visits Manoah’s wife and later Manoah. The child is to be a Nazirite. Samson is born and begins to receive the Spirit.|The unnamed mother receives the first announcement and reasons calmly after the encounter. A Nazirite is distinct from a person from Nazareth.|samson,manoah,samson-mother|zorah,eshtaol|Come, Follow Me studies covenant faithfulness. The manual treats the angel as God’s messenger rather than naming him as Christ.
The wedding and the riddle|Samson seeks a woman from Timnah. He kills a lion and proposes a riddle. Threats force his wife to obtain its answer.|The wife acts under a threat to burn her family. The episode’s coercion must remain visible rather than becoming a simple betrayal story.|samson,manoah,samson-mother,samson-wife|timnah,ashkelon|The Church lesson studies Samson’s covenant conduct. Read that application beside the threat directed at his wife.
Retaliation at Lehi|Samson’s wife is given to another man. He burns crops. The Philistines burn her household. Samson’s retaliation continues at Lehi.|Harm spreads through reprisals against people, property, and families. Strength does not make each action a moral example.|samson,samson-wife|timnah,lehi|The manual studies Samson’s strength and thirst. It states that linking this Lehi with the Book of Mormon figure lacks evidence.
Delilah and Samson’s final act|Samson visits Gaza. Delilah receives payment to discover his weakness. He is captured and blinded, then destroys the temple during a gathering.|The account joins deception, captivity, prayer, revenge, and many deaths. Delilah’s ethnicity is not explicitly stated in the chapter.|samson,delilah|gaza,sorek|Come, Follow Me studies covenant faithfulness. The older manual distinguishes Samson’s gift of strength from consistent moral conduct.
Micah’s household shrine|Micah returns stolen silver to his mother. Images are made for a shrine. He hires a traveling Levite as priest.|The household seeks religious security through possessions and a hired priest. This Micah is distinct from the later prophetic book’s speaker.|micah-judges,jonathan-priest|ephraim-region,bethlehem|The manual reads this episode as part of religious decline. Consider the difference between a sacred object and faithful conduct.
The Danite migration|Danite scouts consult Micah’s priest. Armed men take the shrine objects and priest, then attack Laish and rename it Dan.|The narrative describes coercion and the destruction of a peaceful town. It does not present the migration as harmless settlement.|micah-judges,jonathan-priest,moses|zorah,eshtaol,ephraim-region,dan-city|The older manual places the migration in the book’s closing decline. Read the inhabitants’ loss beside the migrants’ claim.
The woman at Gibeah|A Levite retrieves his concubine from Bethlehem. At Gibeah, men threaten the guest. The woman is handed over and violently abused.|The woman is unnamed. Her suffering must remain central. Hospitality offered to a man does not excuse exposing a woman to violence.|levite-traveler,levite-concubine|bethlehem,jerusalem,gibeah|The manual treats the closing accounts as moral failure. The woman’s abuse is not an example for readers to follow.
War against Benjamin|The tribes gather at Mizpah after hearing the Levite’s report. Benjamin refuses their demand. Repeated battles bring mass death and destruction.|The Levite’s speech omits his own surrender of the woman. The war turns an atrocity into further collective violence.|levite-traveler,phinehas,eleazar,aaron|mizpah,gibeah,bethel,rimmon-rock|The manual describes the near destruction of Benjamin. Consider how a partial account can influence a community’s judgment.
Women taken and the closing refrain|The assembly regrets Benjamin’s losses. It attacks Jabesh-gilead and arranges the seizure of women at Shiloh.|The attempt to preserve a tribe creates further victims. The closing refrain leaves the book’s disorder unresolved.|benjamin|jabesh-gilead,shiloh,rimmon-rock|The older manual calls the arranged marriages unrighteous. Preserving a group does not excuse kidnapping or forced marriage.
'''.strip().splitlines()
assert len(rows)==21
sources=[source('web','Judges — World English Bible','https://ebible.org/engwebp/JDG01.htm','The public-domain reading text supplies all 21 chapters.','Scripture',limits='The text supplies the narrated events and named people. It does not independently verify dates or each historical claim.')]
sources.extend(dict(s) for s in J['sources'] if s['id'] in ['terrain','atlas','atlas-exodus','atlas-canaan'])
s=source('yale-13','The Deuteronomistic History: Prophets and Kings · Judges section','https://oyc.yale.edu/religious-studies/rlst-145/lecture-13','Hayes studies local leaders, the repeated crisis pattern, competing views of kingship, and the violence of the closing chapters.',limits='The reviewed section is a 2006 lecture interpretation. Proposed source layers and dates are not independently verified here.')
s.update(author='Christine Hayes',year='Fall 2006 course',reviewed='2026-10-05: Published transcript sections on the tribal setting and Judges, approximately 1:53–23:05, reviewed.');sources.append(s)
s=source('sbl-gender','Reading Gender in Judges: An Intertextual Approach','https://cart.sbl-site.org/books/0603109C','The volume studies how gender, social position, and relationships with other biblical texts shape readings of Judges.',limits='Publisher description, editor affiliations, and the indexed opening introduction excerpt were reviewed. The full volume and individual essays were not read.')
s.update(author='Shelley L. Birdsong, J. Cornelis de Vos, and Hyun Chul Paul Kim · editors',year='April 2023 · SBL Press',reviewed='2026-10-05: Publisher record and publicly indexed introduction excerpt reviewed.',chapterCoverage=[1,4,11,13,19,21]);sources.append(s)
s=source('net-judges-18','NET Bible · Judges 18:30 textual note','https://classic.net.bible.org/passage.php?mode=print&passage=Jdg+18%3A30','The translators compare Moses and Manasseh readings in Jonathan’s genealogy. They prefer Moses and discuss a suspended letter in Hebrew manuscripts.',limits='The published textual note was reviewed. Its explanation of scribal intention is an editorial judgment, not a complete manuscript review by this guide.')
s.update(author='NET Bible translation team',reviewed='2026-10-05: Published reading and textual note 3 reviewed.',chapterCoverage=[18]);sources.append(s)
for sid,title,slug,a,z,summary in [
('lds-judges-1','Judges 1–12: The Reign of the Judges, Part 1','judges-1-12-the-reign-of-the-judges-part-1',1,12,'The manual studies local deliverers, Deborah, Gideon, kingship, and Jephthah’s vow.'),
('lds-judges-2','Judges 13–21; Ruth 1–4: The Reign of the Judges, Part 2','judges-13-21-ruth-1-4-the-reign-of-the-judges-part-2',13,21,'The manual studies Samson’s calling, covenant conduct, household worship, migration, and the closing moral decline.')]:
 s=source(sid,title,'https://www.churchofjesuschrist.org/study/manual/old-testament-student-manual-genesis-2-samuel/'+slug+'?lang=eng',summary,'LDS study manual','lds',limits='This is 1980 Institute commentary. Its historical proposals are not independent archaeological evidence. The interpretation of Jephthah’s daughter remains disputed.')
 s.update(author='The Church of Jesus Christ of Latter-day Saints',year=1980,reviewed='2026-10-05: Relevant commentary sections and chapter coverage reviewed.',chapterCoverage=list(range(a,z+1)));sources.append(s)
places=[dict(p) for p in J['places'] if p['id'] in ['canaan','hebron','debir-town','jerusalem','bethel','gilgal','jordan','hazor','shechem','gerizim','shiloh','heshbon','gilead','jericho']]
for p in places:
 p['sourceIds']=['web','atlas-canaan'];p['summary']='Named place or region in Judges.';p['limits']='This is a broad locality or traditional identification. It does not verify the event’s date, exact route, or tribal boundary.'
for pid,name,lat,lng,note in [
('moab','Moab · broad region',31.5,35.75,'Regional marker only.'),('ammon','Ammon · broad region',31.95,35.94,'The named territory has no precise boundary polygon here.'),('tabor','Mount Tabor',32.687,35.391,'The mountain locality does not prove the battle account.'),('kishon','Kishon · river region',32.72,35.10,'The ancient battlefield and watercourse are not precisely traced.'),('megiddo','Megiddo · Tel Megiddo',32.585,35.184,'The site marker does not date the song or verify its battle.'),('ophrah','Ophrah · proposed region',32.15,35.25,'Gideon’s Ophrah is uncertain. This is a regional reference, not an identified house or altar.'),('jezreel','Jezreel · valley region',32.60,35.25,'The marker does not identify Gideon’s precise camp.'),('succoth','Succoth · proposed locality',32.20,35.62,'Identification and ancient routes remain uncertain.'),('penuel','Penuel · proposed region',32.19,35.72,'The regional marker does not verify the tower or encounter.'),('thebez','Thebez · traditional Tubas locality',32.32,35.37,'The marker does not identify Abimelech’s siege tower.'),('zorah','Zorah · traditional locality',31.78,34.96,'The marker does not identify Samson’s family home.'),('eshtaol','Eshtaol · traditional region',31.78,35.01,'The location is approximate.'),('timnah','Timnah · traditional Tel Batash',31.78,34.91,'The marker shows the proposed locality, not an identified wedding house.'),('ashkelon','Ashkelon · ancient site locality',31.67,34.55,'The site does not verify Samson’s narrated attack.'),('lehi','Lehi · uncertain foothill region',31.73,35.05,'The precise locality is uncertain. No link to the Book of Mormon Lehi is established.'),('gaza','Gaza · ancient locality',31.50,34.46,'This locality does not identify Samson’s prison or temple.'),('sorek','Sorek · valley region',31.80,34.98,'The marker does not identify Delilah’s house.'),('ephraim-region','Ephraim · hill-country region',32.00,35.20,'Micah’s house and the Levite’s home are not securely identified.'),('bethlehem','Bethlehem',31.705,35.202,'The town marker does not identify a particular ancient household.'),('dan-city','Laish / Dan · Tel Dan locality',33.25,35.65,'The marker does not prove the Danite attack or identify a shrine’s exact date.'),('gibeah','Gibeah · traditional Tell el-Ful',31.823,35.231,'The identification is traditional. No specific house or crime scene is identified.'),('mizpah','Mizpah · traditional Tell en-Nasbeh',31.884,35.214,'The marker does not verify the assembly’s date.'),('rimmon-rock','Rock of Rimmon · traditional region',31.946,35.30,'The precise refuge is uncertain.'),('jabesh-gilead','Jabesh-gilead · proposed region',32.40,35.65,'Competing site proposals remain. This is a regional reference.')]:
 places.append(place(pid,name,lat,lng,'Named place or region in Judges.',note,['web','atlas-canaan']))
people=[]
reuse=['joshua','moses','aaron','caleb','othniel','achsah','phinehas','eleazar','reuben','simeon','levi','judah','benjamin','ephraim','manasseh','zebulun','issachar','dan','naphtali','gad','asher','joseph','sihon','balak']
for p in J['people']:
 if p['id'] in reuse:people.append(dict(p))
new=[
('adonibezek','Adoni-bezek','Ruler captured in Judah’s campaign','He recalls his treatment of other kings.','Judges 1:5–7','The account presents his mutilation as a reversal of his own conduct. It does not prescribe that punishment today.'),
('cushan-rishathaim','Cushan-rishathaim','Enemy ruler in Othniel’s account','Named as king of Mesopotamia in the reading text.','Judges 3:8–10','He occupies the oppressor role in the book’s first deliverance cycle. His personal identity is not independently established.'),
('ehud','Ehud','Benjaminite deliverer','Son of Gera. He carries tribute to Eglon.','Judges 3:15–30; 4:1','His left-handed attack and escape drive the account’s defeat of Moabite power.'),
('eglon','Eglon','Moabite king killed by Ehud','He allies with Ammon and Amalek.','Judges 3:12–30','The account portrays him as a tribute-receiving oppressor. This person is distinct from the Canaanite town named Eglon.'),
('shamgar','Shamgar','Briefly recorded deliverer','Son of Anath.','Judges 3:31; 5:6','The book gives a short victory notice and recalls his days in the song. It supplies little biography.'),
('deborah','Deborah','Prophet and judge','The text identifies her as wife of Lappidoth. She calls Barak to lead.','Judges 4–5','She judges disputes, gives direction, and sings about the victory. Her authority is explicit in the account.'),
('barak','Barak','Commander called by Deborah','Son of Abinoam, from Kedesh in Naphtali.','Judges 4–5','He leads the gathered force with Deborah’s support. The song also bears his name.'),
('sisera','Sisera','Commander of Jabin’s army','He flees to Jael’s tent after defeat.','Judges 4–5','His flight ends with Jael’s decisive action. The song contrasts the outcome with his mother’s expectation.'),
('jabin-judges','Jabin','King of Hazor in Deborah’s account','Sisera commands his army.','Judges 4:2,7,23–24','This Jabin belongs to Judges 4. The guide keeps him separate from Joshua’s king of the same name.'),
('jael','Jael','Woman who kills Sisera','Wife of Heber the Kenite.','Judges 4–5','She receives the fleeing commander, then kills him. Both prose and song give her a decisive role.'),
('heber','Heber','Kenite connected with Jael’s household','Husband of Jael. His household has peace with Jabin.','Judges 4:11,17','His treaty relationship explains Sisera’s expectation of safety. The account does not say he directs Jael’s act.'),
('gideon','Gideon / Jerubbaal','Deliverer in the Midianite crisis','Son of Joash and father of Abimelech and Jotham.','Judges 6–9','His account combines reluctance, victory, revenge, rejection of kingship, and an ephod that becomes a snare.'),
('joash-gideon','Joash','Gideon’s father','His altar is destroyed by Gideon.','Judges 6:11,25–32; 7:14; 8:13,29,32','He answers the crowd’s demand to kill Gideon by asking whether Baal can defend himself. This is not the later king Joash.'),
('oreb','Oreb','Midianite commander','Named with Zeeb after the army’s defeat.','Judges 7:25; 8:3','His death appears in the pursuit account. His name also marks the rock named in the narrative.'),
('zeeb','Zeeb','Midianite commander','Named with Oreb after the army’s defeat.','Judges 7:25; 8:3','His death appears in the pursuit account. The guide does not identify his actual appearance or dates.'),
('zebah','Zebah','Midianite king pursued by Gideon','Named with Zalmunna.','Judges 8','The account links his execution with the killing of Gideon’s brothers. Revenge remains part of the story.'),
('zalmunna','Zalmunna','Midianite king pursued by Gideon','Named with Zebah.','Judges 8','He belongs to the pursued royal pair. The narrative gives limited personal detail beyond the conflict.'),
('jether','Jether','Gideon’s firstborn son','Gideon tells him to kill the captive kings.','Judges 8:20','His fear contrasts with Gideon’s command. The text identifies him as young, not as an experienced executioner.'),
('abimelech-judges','Abimelech','Gideon’s son who claims kingship','His mother is from Shechem. Jotham survives his attack on his brothers.','Judges 8:31; 9','His rise and fall show destructive ambition and retaliation. He is distinct from Genesis’s Abimelech.'),
('jotham-gideon','Jotham','Surviving son of Gideon','Brother of Abimelech.','Judges 9','His tree fable warns Shechem about its chosen ruler. He is distinct from the later king Jotham.'),
('gaal','Gaal','Challenger to Abimelech at Shechem','Son of Ebed.','Judges 9:26–41','He speaks against Abimelech and then loses the confrontation. His words help expose the town’s divided loyalties.'),
('zebul','Zebul','Official loyal to Abimelech','He opposes Gaal at Shechem.','Judges 9:28–41','His messages and tactics support Abimelech’s response. He is a person, not the tribal ancestor Zebulun.'),
('tola','Tola','Briefly recorded judge','Son of Puah, of Issachar.','Judges 10:1–2','The account records service and burial with little narrative detail. He is distinct from earlier ancestral names.'),
('jair','Jair','Gileadite judge','The account mentions thirty sons and their towns.','Judges 10:3–5','His household and towns signal local influence. His dates are not independently established.'),
('jephthah','Jephthah','Gileadite commander recalled from exile','Son of Gilead and a woman described as a prostitute. Father of one daughter.','Judges 11–12','He negotiates leadership and argues a territorial case. His vow brings tragedy to his only child.'),
('jephthah-daughter','Jephthah’s daughter','Unnamed only child affected by her father’s vow','Daughter of Jephthah. Her name is not given in Judges.','Judges 11:34–40','She greets her father, requests time with her companions, and becomes the subject of remembrance. Her loss remains central.'),
('ibzan','Ibzan','Briefly recorded judge','The account describes marriages for his sons and daughters.','Judges 12:8–10','His family arrangements mark social connections. The text does not identify him as Boaz.'),
('elon','Elon','Briefly recorded Zebulunite judge','His burial is placed in Aijalon in Zebulun.','Judges 12:11–12','The account gives a short term of service and burial notice. It supplies no extended life story.'),
('abdon','Abdon','Briefly recorded judge','Son of Hillel, from Pirathon.','Judges 12:13–15','His large family and their mounts indicate status in the narrative. They do not establish exact historical dates.'),
('samson','Samson','Nazirite and strongman in the Philistine conflict','Son of Manoah and his unnamed wife.','Judges 13–16','His gifted strength exists beside impulsive conduct and revenge. The account does not make every act a moral example.'),
('manoah','Manoah','Samson’s father','A Danite from Zorah, husband of Samson’s unnamed mother.','Judges 13–16','He seeks instruction after his wife’s angelic encounter. Her explanation answers his fear after the offering.'),
('samson-mother','Samson’s mother','Unnamed woman who receives the birth announcement','Wife of Manoah and mother of Samson.','Judges 13–14','She receives the first message and explains the encounter calmly. The account gives her an active role without naming her.'),
('samson-wife','Samson’s wife at Timnah','Unnamed Philistine woman under threat','Samson’s first wife. Her father later gives her to another man.','Judges 14–15','She reveals the riddle’s answer under threat to burn her household. Later violence kills her and her father.'),
('delilah','Delilah','Woman who discovers Samson’s weakness','Samson loves her. Philistine rulers offer payment for her help.','Judges 16:4–22','Repeated questioning leads to Samson’s capture. The text does not explicitly give her ethnicity or call her a prostitute.'),
('micah-judges','Micah','Owner of a household shrine','His unnamed mother dedicates returned silver. He hires a Levite.','Judges 17–18','He expects security from his shrine and priest but loses them to armed Danites. He is distinct from the prophet Micah.'),
('jonathan-priest','Jonathan','Levite priest taken with Micah’s shrine','Judges 18 identifies him as son of Gershom. The reading text says Moses.','Judges 17–18','The traveling priest accepts a larger tribal position. The final genealogy has a known textual variation, which the guide does not resolve.'),
('levite-traveler','The Levite traveler','Unnamed man whose report helps lead to civil war','Partner of the woman from Bethlehem.','Judges 19–20','He hands the woman to the attackers. His later speech omits that act. The account requires attention to her harm.'),
('levite-concubine','The woman from Bethlehem','Unnamed woman abused at Gibeah','The text calls her the Levite’s concubine.','Judges 19–20','She has almost no recorded speech. The violence against her and use of her body reveal the account’s severe moral failure.')]
for row in new:people.append(person(*row))
chapters=[]
for n,row in enumerate(rows,1):
 title,summary,meaning,pids,locs,lds=row.split('|');refs=['web','yale-13','atlas-canaan']+(['sbl-gender'] if n in [1,4,11,13,19,21] else [])+(['net-judges-18'] if n==18 else [])
 route={4:['tabor','kishon'],8:['jordan','succoth','penuel'],18:['zorah','ephraim-region','dan-city'],19:['bethlehem','jerusalem','gibeah']}.get(n,[])
 chapters.append(dict(chapter=n,title=title,summary=summary,meaning=meaning,people=pids.split(','),places=locs.split(','),sourceIds=refs,lds=dict(text=lds,sourceIds=['lds-judges-1' if n<=12 else 'lds-judges-2']),eventOrder=n,dateLabel='Chapter order · historical year uncertain',historicalNote='The book’s religious explanation and literary presentation remain distinct from independently verified historical evidence.',mapNote='Markers show named localities and approximate regions. They do not establish exact battle sites, ancient roads, or tribal boundaries.',route=route,routeEvidence='The simplified line follows the chapter’s named movement. It omits uncertain intermediate points and is not an excavated road.'))
text=scripture('judges','JDG',21)
new_ids={r[0] for r in new}
for p in people:
 pid=p['id'];p.update(sourceIds=['web'],placeIds=[],linkNames=[],life='Historical birth and death years are not securely known.')
 if pid not in new_ids:
  name=p['name'].split(' / ')[0]
  for c in chapters:
   if re.search(r'\b'+re.escape(name)+r'\b',' '.join(v['text'] for v in text[str(c['chapter'])])) and pid not in c['people']:c['people'].append(pid)
  p['passages']='Judges '+', '.join(str(c['chapter']) for c in chapters if pid in c['people'])
  if pid in ['caleb','othniel','achsah']:p['meaning']='This person appears in the opening land account. Read the individual’s actions beside the earlier account in Joshua.'
  elif pid in ['joshua','moses','aaron','eleazar','balak','sihon']:p['meaning']='The book recalls this earlier person or identifies a family line. It does not place the person in every later scene.'
  elif pid=='phinehas':p['meaning']='He appears as priest during the inquiry before the war against Benjamin. The passage identifies his family line.'
  else:p['role']='Ancestor recalled through a tribal name';p['meaning']='The name identifies a tribal community or ancestry. The portrait does not mean the ancestor attends these later events.'
 p['placeIds']={'caleb':['hebron'],'othniel':['debir-town'],'achsah':['debir-town'],'jabin-judges':['hazor'],'barak':['tabor'],'gideon':['ophrah'],'jephthah':['gilead'],'samson':['zorah','timnah','gaza'],'manoah':['zorah'],'samson-mother':['zorah'],'samson-wife':['timnah'],'delilah':['sorek'],'micah-judges':['ephraim-region'],'jonathan-priest':['ephraim-region','dan-city'],'levite-traveler':['bethlehem','gibeah'],'levite-concubine':['bethlehem','gibeah']}.get(pid,[])
 if pid=='gideon':p['name']='Gideon';p['linkNames']=['Jerubbaal','Jerubbesheth']
 if pid=='deborah':p['placeIds']=['bethel'];p['relations']+=' The text places her judging between Ramah and Bethel. The map shows the broad Bethel locality.'
 if pid=='jonathan-priest':p['linkNames']=['Levite']
 if pid=='levite-traveler':p['linkNames']=['Levite']
 if pid=='levite-concubine':p['linkNames']=['concubine']
finish(dict(id='judges',bibleCode='JDG',name='Judges',description='Deliverers · disputed power · faith · social collapse',chapterCount=21,scripture=text,chapters=chapters,people=people,places=places,sources=sources,review=dict(date='2026-10-05',scope='Chapter-level events, selected named people, and central unnamed women. Ancient violence remains distinct from present religious instruction.',nextBook='ruth')))
