"""Deuteronomy: narrative retelling, covenant laws, leadership, and tribal memory."""
import json
from book_common import ROOT,OUT,scripture,source,person,place,finish
NUM=json.loads((OUT/'numbers.json').read_text(encoding='utf-8'))
GEN=json.loads((OUT/'genesis.json').read_text(encoding='utf-8'))
rows='''
Moses recalls the failed entry|Moses addresses Israel east of the Jordan. He recalls appointed judges, the scouts’ report, and the refusal to enter Canaan.|The speech selects earlier events to teach the present generation. A remembered journey is not a new movement by the listeners.|moses,joshua,caleb|moab,sinai,kadesh,canaan|Consider how your account of a past decision shapes what others learn from it.
Neighboring lands and Sihon|Moses recalls travel near Edom, Moab, and Ammon. Israel must respect those territories. The speech then recounts war against Sihon.|The account distinguishes lands that Israel must leave alone from a territory acquired through war. Its violence remains part of the story.|moses,sihon,esau,lot|moab,edom,heshbon|Consider the limits placed on territorial claims. Read the whole account rather than only its victory language.
Og, eastern settlements, and Joshua|Moses recalls the defeat of Og and the allocation of eastern land. He encourages Joshua but cannot enter the land himself.|The account joins military success with a leadership limit. An eastern inheritance still carries duties toward the other tribes.|moses,og,joshua|moab,bashan,gilead,canaan|Consider how receiving a benefit can leave continuing obligations to others.
Remember the covenant|Moses urges obedience and warns against images. He recalls Horeb and sets apart three eastern refuge towns.|The speech makes remembered experience a duty to future generations. The warnings concern covenant loyalty rather than a measured history of every event.|moses|moab,sinai,gilead,bashan|Consider how you can teach what you have learned without adding claims that the text does not make.
The commandments recalled|Moses repeats the commandments and recalls Israel’s request for him to act as mediator. The Sabbath instruction remembers slavery in Egypt.|Compare this account with Exodus 20. The Sabbath reasons differ even though the command concerns the same weekly rest.|moses|moab,sinai,egypt|Consider how the memory of slavery can shape rest and care for other people.
Love, teach, and remember|Moses calls Israel to love the Lord and teach these words in daily life. He warns against forgetting after receiving a good land.|The commands connect memory with ordinary places and repeated actions. Prosperity can make dependence on others easier to forget.|moses,abraham,isaac,jacob|moab,canaan|Come, Follow Me studies love for God and teaching the next generation. Consider one daily practice that supports remembrance.
A chosen people and severe commands|The speech commands separation from surrounding worship and the destruction of named peoples. It also recalls God’s covenant with the ancestors.|The chapter combines divine love with commands for collective violence. Those commands must not become permission for violence against people today.|moses|moab,canaan|Read covenant responsibilities beside the harm described in the chapter. Keep ancient commands distinct from present Church conduct.
Remember in prosperity|Moses recalls wilderness hunger and manna. He warns that a prosperous people must not claim that its own strength supplied everything.|The chapter links material success with memory and humility. Its account of wilderness testing belongs to the text’s religious explanation.|moses|moab,canaan|The Church lesson asks readers to remember God in comfort as well as hardship. Consider what gratitude changes in your conduct.
The calf and intercession recalled|Moses denies that Israel receives the land because of its own righteousness. He recalls the golden calf, broken tablets, and his intercession.|The speech opposes self-congratulation with a record of failure. Moses’s remembered prayers stress the community’s dependence on mercy.|moses,aaron,abraham,isaac,jacob|moab,sinai,canaan|Consider how honest memory can resist claims of moral superiority.
New tablets and care for strangers|Moses recalls replacement tablets and the appointment of Levites. He calls Israel to love God and care for the stranger.|The commands join worship with social responsibility. Love for the stranger draws on the memory of being strangers in Egypt.|moses,aaron|moab,sinai,egypt|Consider how memory of vulnerability can change your treatment of a newcomer.
Teach the words and choose a path|Moses recalls Egypt and the judgment on Dathan and Abiram. He urges daily teaching and names Gerizim and Ebal for future blessings and curses.|The speech uses remembered events and an anticipated ceremony to press a choice. Naming the mountains does not place the present assembly there.|moses,dathan,abiram|moab,egypt,gerizim,ebal|Consider what habits help a family pass on its commitments.
The chosen place of worship|The law requires worship at a place God will choose. It distinguishes sacrifices from ordinary meat eaten at home and forbids consuming blood.|The chapter describes a central place without naming Jerusalem. Do not put a Jerusalem marker on the map as if this chapter named it.|moses|moab,canaan|Consider how shared worship can shape community life. Keep the text’s unnamed sanctuary distinct from a later identification.
Tests of covenant loyalty|The law addresses a prophet, close relative, or town that urges worship of other gods. It prescribes severe punishments.|The commands place loyalty above family and local ties. Their coercion belongs to an ancient legal setting and does not authorize present persecution.|moses|moab|Consider how to examine a religious claim carefully. Keep this ancient punishment system distinct from present conduct.
Food, tithes, and shared provision|The law distinguishes permitted foods and directs the use of tithes. A third-year provision supports Levites, strangers, orphans, and widows.|The chapter connects sacred identity with material care. Food rules and provision for vulnerable people have different functions within that system.|moses|moab,canaan|Consider how your use of resources can include people who lack stable support.
Release and an open hand|The law provides for debt release and the release of Hebrew slaves. It requires generosity toward people in need and gifts to people released from slavery.|The instructions address economic dependence within an unequal society. They require support as well as release from an obligation.|moses|moab|Come, Follow Me studies a willing heart in helping people in need. Consider whether your help preserves their dignity.
Festivals and fair judgment|The law describes Passover, weeks, and booths. It also commands judges to avoid partiality and bribery.|The festivals include people who might otherwise remain outside a household’s celebration. Fair judgment is a public duty.|moses|moab,canaan|Consider how celebrations and decisions can include people with less influence.
Judges and limits on kings|The law addresses prohibited worship, difficult cases, and a future king. The king must read the law and limit wealth, horses, and wives.|Royal power remains subject to instruction. The king must not raise himself above his fellow Israelites.|moses|moab,canaan|Consider what prevents a leader from treating authority as personal privilege.
Priests and a prophet like Moses|The law provides support for priests, rejects certain divination practices, and promises a prophet like Moses. It gives a test for a prophetic claim.|The chapter distinguishes authorized instruction from prohibited practices. Later Christian and LDS texts apply the promised prophet to Jesus Christ.|moses|moab|Come, Follow Me connects the prophet like Moses with Christ. Read that interpretation beside Acts 3 and 3 Nephi 20.
Refuge, boundaries, and witnesses|The law establishes refuge for accidental killers, protects boundary markers, and requires multiple witnesses. False testimony receives a stated penalty.|The procedures distinguish an accident from deliberate murder. An accusation alone cannot establish guilt in the stated system.|moses|moab,canaan|Consider why judgment needs witnesses and attention to circumstances.
Rules for warfare|The law gives exemptions from military service and different instructions for distant and nearby cities. It limits destruction of fruit trees.|The chapter contains both restraints and commands for collective killing. Those commands do not establish that each named conquest occurred.|moses|moab,canaan|Read the restraints and the violence together. Keep ancient war law distinct from present religious duty.
Unsolved killing and household laws|The law addresses an unidentified killer, a captive woman, inheritance, a rebellious son, and burial after execution.|The chapter brings public responsibility beside unequal household power and severe penalties. Its captive-marriage rules do not establish free consent.|moses|moab|Consider whose voice is absent from these laws. Keep the ancient penalties distinct from present family conduct.
Neighborly care and sexual laws|The law requires help with lost animals and safe roofs. It also gives clothing rules and severe laws about marriage accusations and sexual acts.|Practical care stands beside an unequal ancient sexual legal system. A failure to cry out must not become a modern test of consent.|moses|moab|Consider the duty to prevent foreseeable harm. Read the sexual laws within their ancient setting rather than using them to judge a survivor.
Assembly, camp, and promises|The law restricts assembly membership, regulates camp cleanliness, and protects a person who escapes slavery from forced return. It also concerns interest and vows.|The chapter contains both exclusion and protection. Read each rule rather than treating all outsiders as one category.|moses,balaam|moab,egypt,edom|Consider the protection offered to a person escaping slavery. Keep ancient membership restrictions distinct from present human worth.
Household changes and protection of the poor|The law concerns divorce and remarriage, loans, wages, testimony, and gleaning. It protects certain essential belongings from seizure.|Daily economic rules can reduce harm to people with less power. The chapter remembers slavery as a reason for fair treatment.|moses|moab,egypt|Consider how prompt payment and leaving resources for others can turn compassion into action.
Fair measures and family continuity|The law limits flogging, regulates marriage after a brother’s death, requires honest weights, and remembers Amalek’s attack.|The chapter combines restraint, household continuity, commerce, and hostility. The marriage rule belongs to an ancient inheritance system.|moses|moab|Consider why a fair measure matters when another person cannot verify your claim.
First produce and covenant declaration|The worshiper brings first produce and recounts the ancestors’ hardship, Egypt, and deliverance. A declaration accompanies the third-year tithe.|The ritual connects possession of land with remembered dependence and shared provision. It turns a gift into a spoken account of identity.|moses|moab,egypt,canaan|Consider how giving can include an honest account of what you received from others.
Instructions for Ebal and Gerizim|Moses and the elders give instructions for an altar, written law, and spoken curses after entry. Tribes receive roles on the two mountains.|This chapter plans a future ceremony. Its curses name hidden wrongs and failures of justice as well as worship offenses.|moses,reuben,simeon,levi,judah,joseph,benjamin,zebulun,issachar,dan,naphtali,gad,asher|moab,ebal,gerizim|Consider what a public promise requires when wrongdoing can remain hidden.
Blessings and terrible curses|The speech lists blessings for obedience and curses for disobedience. It describes disease, military defeat, siege, hunger, and exile.|The chapter expresses covenant consequences in severe terms. It cannot establish that a person’s present illness or suffering proves wrongdoing.|moses|moab,canaan,egypt|Read the whole warning with care. Avoid using its suffering language to assign blame to someone in distress.
The covenant assembly|Moses addresses leaders, families, and strangers at the covenant gathering. He warns against hidden disloyalty and describes a devastated land.|The commitment includes people present and people not present. The speech makes continuity across generations part of the covenant.|moses|moab|Come, Follow Me studies inward loyalty and shared covenant identity. Consider the effect of your choices on people who will follow you.
Return and choose life|Moses describes return after scattering and calls the people to love and obey God. He presents the instruction as near and calls them to choose life.|The chapter offers restoration beside warning. Its choice concerns love and conduct rather than a remote secret that cannot be reached.|moses,abraham,isaac,jacob|moab,canaan|The Church lesson compares these words with Lehi’s teaching about agency. Consider what choosing life requires in a daily decision.
Joshua, the written law, and the song|Moses encourages Joshua, gives the written law to priests, and commands public readings. A song will serve as a witness against future unfaithfulness.|Leadership, written instruction, and communal memory support continuity. The account also anticipates failure after Moses’s departure.|moses,joshua|moab|Consider how a community can preserve its commitments when a leader changes.
The Song of Moses|The poem recounts God’s care, Israel’s neglect, judgment, and vindication. Moses then receives instructions to go up Mount Nebo.|Poetry uses images that require interpretation. Deuteronomy 32 also has differences among surviving textual traditions that deserve separate study.|moses,joshua,aaron,jacob|moab,nebo|The older manual connects the rock image with Christ. Its race-related explanations require comparison with the Church’s current rejection of racial inferiority theories.
Blessings for the tribes|Moses blesses the tribes before his departure. The poem names tribal identities and describes their hopes, duties, and regions.|These ancestral names often designate communities, not the sons of Jacob standing before Moses. Simeon receives no separate blessing in this chapter.|moses,joseph,reuben,levi,judah,benjamin,ephraim,manasseh,zebulun,issachar,dan,naphtali,gad,asher|moab,canaan|Compare this poem with Genesis 49. Distinguish a tribal blessing from a secure date or a prediction independently verified by archaeology.
Moses’s departure and Joshua’s leadership|Moses views the land from Nebo. The chapter narrates his death and an unknown burial place. Joshua receives the people’s obedience.|The closing tribute honors Moses and confirms Joshua’s succession. The text does not identify a recoverable burial location.|moses,joshua,abraham,isaac,jacob|moab,nebo,canaan|LDS sources interpret Moses’s departure as translation, a change without ordinary death. Keep that interpretation distinct from this chapter’s stated account.
'''.strip().splitlines()
assert len(rows)==34
sources=[source('web','Deuteronomy — World English Bible','https://ebible.org/engwebp/DEU01.htm','The public-domain reading text supplies all 34 chapters.','Scripture',limits='The narrative, speeches, and laws are textual evidence. They do not independently verify each event.')]
sources.extend(dict(s) for s in NUM['sources'] if s['id'] in ['terrain','atlas','atlas-exodus','atlas-canaan'])
for sid,title,slug,summary,coverage in [
('lds-deut-1','Deuteronomy 1–16: An Exhortation to Obedience, Part 1','deuteronomy-1-16-an-exhortation-to-obedience-part-1','The manual studies Moses’s final addresses, remembrance, covenant loyalty, and community duties.',list(range(1,17))),
('lds-deut-2','Deuteronomy 17–33: An Exhortation to Obedience, Part 2','deuteronomy-17-33-an-exhortation-to-obedience-part-2','The manual studies leaders, laws, covenant consequences, tribal blessings, and Moses’s departure.',list(range(17,35)))]:
 s=source(sid,title,'https://www.churchofjesuschrist.org/study/manual/old-testament-student-manual-genesis-2-samuel/'+slug+'?lang=eng',summary,'LDS study manual','lds',limits='This is 1980 Institute commentary. Some proposals and quoted social explanations differ from current Church teaching. Its introduction’s race-related claims must be read beside Race and the Priesthood. It is not independent archaeological evidence.')
 s.update(author='The Church of Jesus Christ of Latter-day Saints',year=1980,reviewed='2026-10-05: Relevant commentary sections, chapter coverage, and edition information reviewed.',chapterCoverage=coverage);sources.append(s)
s=source('yale-11','On the Steps of Moab: Deuteronomy — Open Yale Courses','https://oyc.yale.edu/religious-studies/rlst-145/lecture-11','Hayes studies the book’s speeches, adapted laws, central worship, care for outsiders, and transfer of leadership.',limits='This is a university lecture interpretation. Proposed composition stages and dates are debated. They do not establish the historical dates of Moses’s speeches.')
s.update(author='Christine Hayes',year='Fall 2006 course',reviewed='2026-10-05: Published overview and relevant transcript sections on structure, legal changes, and leadership reviewed.');sources.append(s)
for sid,title,url,summary,chapters in [
('lds-prophet','3 Nephi 20:23','https://www.churchofjesuschrist.org/study/scriptures/bofm/3-ne/20?lang=eng&id=p23#p23','Jesus identifies himself with the promised prophet like Moses.',[18]),
('lds-agency','2 Nephi 2:26–29','https://www.churchofjesuschrist.org/study/scriptures/bofm/2-ne/2?lang=eng&id=p26-p29#p26','Lehi teaches agency and choice through redemption in Christ.',[30]),
('lds-moses','Alma 45:18–19','https://www.churchofjesuschrist.org/study/scriptures/bofm/alma/45?lang=eng&id=p18-p19#p18','The passage compares Alma’s departure with the tradition that the Lord took Moses to himself.',[34])]:
 s=source(sid,title,url,summary,'LDS scripture','lds',limits='This Restoration scripture supplies a later interpretation or comparison. It remains distinct from Deuteronomy’s own wording.');s.update(author='The Book of Mormon',reviewed='2026-10-05: Referenced passage reviewed.',chapterCoverage=chapters);sources.append(s)
s=source('lds-race','Race and the Priesthood · current teaching','https://www.churchofjesuschrist.org/study/manual/gospel-topics-essays/race-and-the-priesthood?lang=eng','The Church rejects theories that race reflects divine disfavor or unrighteous premortal conduct. It condemns racial inferiority theories.','LDS Gospel Topics essay','lds',limits='This source clarifies current Church teaching when an older manual quotes race-related explanations. It is not a translation of Deuteronomy 32.')
s.update(author='The Church of Jesus Christ of Latter-day Saints',reviewed='2026-10-05: The Church Today section reviewed.',chapterCoverage=[32]);sources.append(s)
s=source('net-deut-32','NET Bible · Deuteronomy 32:8–9 notes','https://classic.net.bible.org/passage.php/xml/passage.php?mode=print&passage=Deu+32%3A8-9','The translation notes compare the Masoretic, Qumran, and Greek readings of Deuteronomy 32:8. The translators prefer a reading about divine beings.',limits='These are scholarly translation notes. Their preference for an original reading is an editorial judgment, not a complete manuscript review by this guide.')
s.update(author='NET Bible translation team',reviewed='2026-10-05: Published reading and textual note 3 reviewed.',chapterCoverage=[32]);sources.append(s)
places=[dict(p) for p in NUM['places']]
places.extend([
place('nebo','Mount Nebo · traditional identification',31.768,35.726,'Deuteronomy 34 names Nebo as Moses’s viewing place.','The marker shows the traditional Nebo locality. It does not identify Moses’s grave or prove the narrated event.',['web','atlas-exodus']),
place('gerizim','Mount Gerizim',32.20,35.27,'Deuteronomy 11 and 27 name Gerizim for a future ceremony.','This is a geographical reference. Deuteronomy plans the ceremony but does not narrate its completion.',['web','atlas-canaan']),
place('ebal','Mount Ebal',32.24,35.28,'Deuteronomy 27 names Ebal for an altar and covenant ceremony.','This is a geographical reference. It does not establish the date or archaeological identity of the commanded altar.',['web','atlas-canaan'])])
people=[]
selected_num=['moses','aaron','miriam','joshua','caleb','sihon','og','balaam','dathan','abiram']
selected_gen=['abraham','isaac','jacob','esau','lot','joseph','reuben','simeon','levi','judah','benjamin','ephraim','manasseh']
for data,ids in [(NUM,selected_num),(GEN,selected_gen)]:
 for p in data['people']:
  if p['id'] in ids:people.append(dict(p))
for pid,name,mother in [('zebulun','Zebulun','Leah'),('issachar','Issachar','Leah'),('dan','Dan','Bilhah'),('naphtali','Naphtali','Bilhah'),('gad','Gad','Zilpah'),('asher','Asher','Zilpah')]:
 people.append(person(pid,name,'Ancestor recalled through a tribal name','Son of Jacob and '+mother+'. His name also identifies a later tribe.','Deuteronomy 27; 33','The name designates a tribal community in Moses’s words. The ancestral portrait does not imply that Jacob’s son attended the assembly.'))
passages={'moses':'Deuteronomy 1–34','aaron':'Deuteronomy 9–10; 32:50','miriam':'Deuteronomy 24:9','joshua':'Deuteronomy 1:38; 3:21,28; 31; 32:44; 34:9','caleb':'Deuteronomy 1:36','sihon':'Deuteronomy 1:4; 2:24–37; 3; 4:46; 29:7; 31:4','og':'Deuteronomy 1:4; 3; 4:47; 29:7; 31:4','balaam':'Deuteronomy 23:4–5','balak':'Deuteronomy 23:4','dathan':'Deuteronomy 11:6','abiram':'Deuteronomy 11:6','abraham':'Deuteronomy 1:8; 6:10; 9:5,27; 29:13; 30:20; 34:4','isaac':'Deuteronomy 1:8; 6:10; 9:5,27; 29:13; 30:20; 34:4','jacob':'Deuteronomy 1:8; 6:10; 9:5,27; 29:13; 30:20; 32–34','esau':'Deuteronomy 2:4–8,12,22,29','lot':'Deuteronomy 2:9,19','joseph':'Deuteronomy 27:12; 33:13–17','reuben':'Deuteronomy 3:12,16; 27:13; 33:6','simeon':'Deuteronomy 27:12','levi':'Deuteronomy 27:12; 33:8–11','judah':'Deuteronomy 27:12; 33:7','benjamin':'Deuteronomy 27:12; 33:12','ephraim':'Deuteronomy 33:17','manasseh':'Deuteronomy 3:13–15; 33:17'}
tribal=set(['joseph','reuben','simeon','levi','judah','benjamin','ephraim','manasseh','zebulun','issachar','dan','naphtali','gad','asher'])
meanings={'moses':'He recalls earlier events, teaches laws, and prepares Israel for his departure. The final chapter honors his service while placing Joshua in leadership.','aaron':'Moses remembers his role in the calf crisis and his death. These are retrospective accounts, not Aaron’s presence in the Moab assembly.','miriam':'The law recalls her wilderness affliction as an instruction about care with skin disease. Her earlier death is not retold here.','joshua':'Moses encourages and commissions him. The closing account confirms his authority after Moses’s departure.','caleb':'Moses recalls Caleb’s faithfulness during the earlier scouting decision. The speech promises him a portion of land.','sihon':'The speeches recall his refusal and defeat as part of the eastern settlement account. Those statements do not independently establish his dates.','og':'Moses recalls his defeat and associates Bashan with eastern inheritance. The text’s unusual bed description does not establish a measured portrait.','balaam':'The law recalls the attempted curse and its reversal into blessing. Read this later recollection beside Numbers 22–24.','balak':'The chapter remembers his attempt to hire Balaam. He is not a participant in Moses’s present assembly.','dathan':'Moses recalls the judgment on him as a remembered warning. He does not appear alive in this book’s setting.','abiram':'His earlier rebellion appears in Moses’s warning. The speech is retrospective, not a new encounter.'}
for p in people:
 pid=p['id'];p['passages']=passages.get(pid,p['passages']);p['placeIds']=[];p['linkNames']=[]
 if pid in tribal:
  p['role']='Ancestor recalled through a tribal name';p['meaning']='This ancestral name designates a tribal community in Moses’s words. The portrait recalls the ancestor and does not place him at the assembly.'
 elif pid in meanings:p['meaning']=meanings[pid]
 else:p['meaning']='Moses recalls this ancestor in covenant or kinship language. The account does not place the ancestor at the Moab assembly.'
 if pid=='jacob':
  p['name']='Jacob';p['linkNames']=[];p['role']='Ancestor recalled in covenant language';p['meaning']='Moses recalls Jacob as an ancestor in covenant promises. In the poems, Jacob also names the community of Israel. The portrait represents the ancestor, not the assembled people.'
 if pid=='esau':p['name']='Esau';p['linkNames']=[]
 if pid=='abraham':p['name']='Abraham';p['linkNames']=[]
 if pid=='moses':p['placeIds']=['moab','nebo','sinai']
 if pid=='joshua':p['placeIds']=['moab']
 p['life']='Historical birth and death years are not securely known.'
chapters=[]
for n,row in enumerate(rows,1):
 title,summary,meaning,pids,locs,lds=row.split('|')
 ids=pids.split(',');locs=locs.split(',');refs=['web','yale-11']+(['net-deut-32'] if n==32 else [])
 refs.extend(list(dict.fromkeys(sid for p in places if p['id'] in locs for sid in p['sourceIds'] if sid!='web')))
 ldsrefs=['lds-deut-1' if n<=16 else 'lds-deut-2']
 ldsrefs += {18:['lds-prophet'],30:['lds-agency'],32:['lds-race'],34:['lds-moses']}.get(n,[])
 route=['sinai','kadesh'] if n==1 else []
 chapters.append(dict(chapter=n,title=title,summary=summary,meaning=meaning,people=ids,places=locs,sourceIds=refs,lds=dict(text=lds,sourceIds=ldsrefs),eventOrder=n,dateLabel='Chapter order · historical year uncertain',historicalNote='Distinguish the speech’s recalled events from its present setting and future commands.',mapNote='Moab is the speech setting. Other markers show recalled places or future instructions. Regions and traditional locations are approximate.',route=route,routeEvidence='Moses recalls the Horeb-to-Kadesh journey in Deuteronomy 1. This is a retrospective, simplified line. It omits uncertain camps and does not show an excavated road.'))
finish(dict(id='deuteronomy',bibleCode='DEU',name='Deuteronomy',description='Remembrance · covenant · law · succession',chapterCount=34,scripture=scripture('deuteronomy','DEU',34),chapters=chapters,people=people,places=places,sources=sources,review=dict(date='2026-10-05',scope='Chapter-level speeches, laws, recalled people, and anticipated ceremonies. Tribal names remain distinct from ancestors attending the assembly.',nextBook='joshua')))
