"""Build Galatians from reviewed Scripture and original contextual notes."""
import json,copy,sys
from book_common import ROOT,OUT,scripture,source,person,finish
DATE='2026-10-07';t=scripture('galatians','GAL',6)
assert [len(t[str(n)]) for n in range(1,7)]==[24,21,29,31,26,18]
assert sum(map(len,t.values()))==149
assert not any('\ufffd' in str(v) for vv in t.values() for v in vv)
notes=json.loads((ROOT/'scripts/book-context-complete/galatians.json').read_text(encoding='utf8'));sources=[]
s=source('web','Galatians · World English Bible','https://ebible.org/engwebp/GAL01.htm','All six chapters supply the primary text for original close readings.','Scripture','historical','Paul’s reported disputes remain his account. Original manuscripts, exact dates, opponents’ identities, Greek vocabulary, and harmony with Acts were not independently verified. Hagar and Jerusalem remain part of Paul’s stated symbolic comparison rather than an independent description of Jewish belief.')
s.update(author='World English Bible translators',publisher='eBible.org',chapterCoverage=list(range(1,7)),reviewed=dict(date=DATE,scope='All 149 verses read for six original contextual explanations and exact selections. Surroundings, counts, and character integrity checked.'));sources.append(s)
s=source('works-galatians','Commentary on Galatians 3:23-29','https://www.workingpreacher.org/commentaries/revised-common-lectionary/ordinary-12-3/commentary-on-galatians-323-29-5','Works reads shared belonging through Christ within continuing difference.','Scholarly study','historical','This is Works’ interpretation. Her broader historical account of household guardians, baptismal practice, slavery, and the later church was not independently verified. Linked commentaries and podcasts were not reviewed.')
s.update(author='Carla Works',publisher='Luther Seminary',year=2022,chapterCoverage=[3],reviewed=dict(date=DATE,scope='Complete commentary body read. The guide attributes her reading of shared belonging within continuing difference. Opponents’ exact positions remain a reconstruction rather than an independently preserved reply.'));sources.append(s)
s=source('cfm-nt-2023-40','September 25–October 1 · Galatians','https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-sunday-school-new-testament-2023/40?lang=eng','The lesson studies freedom, the Spirit’s fruit, and patient work.','LDS Come, Follow Me','lds','Coverage follows actual chapter discussion. The lesson does not independently review chapter two. Included Hinckley and Soares passages were read here, not in their complete original works.')
s.update(author='The Church of Jesus Christ of Latter-day Saints',publisher='The Church of Jesus Christ of Latter-day Saints',year=2023,chapterCoverage=[1,3,4,5,6],reviewed=dict(date=DATE,scope='Complete lesson body and included resources read. Linked full talks, manuals, videos, and Restoration passages were not independently reviewed.'));sources.append(s)
acts=json.loads((OUT/'acts.json').read_text(encoding='utf8'));sources.extend(copy.deepcopy([s for s in acts['sources'] if s['id'] in ['atlas-canaan','net-acts-map']]))
rows=[
 ('acts','paul','Paul','Letter speaker defending his message and the believers’ freedom','Peter and Barnabas appear within his remembered dispute. Titus joins the earlier Jerusalem visit.','Galatians 1–6','His recalled life and arguments serve the present question about Gentile belonging.',['Paul']),
 ('matthew','jesus','Jesus Christ','The crucified and risen Lord through whom Paul describes received belonging','Paul connects faith, baptism, and promised inheritance with him.','Galatians 1–6','His gift supplies the basis for freedom expressed through love and shared service.',['Jesus','Christ']),
 ('acts','peter','Peter, also called Cephas','Apostle whom Paul visits and later challenges over divided meals','Paul describes his withdrawal from Gentiles after other people arrive.','Galatians 1:18; 2:7–14','His changed table practice shows a conflict between shared recognition and conduct under pressure.',['Peter','Cephas']),
 ('acts','barnabas','Barnabas','Companion who receives shared recognition but later joins the meal division','He travels with Paul and Titus to Jerusalem.','Galatians 2:1, 9, 13','His participation shows that pressure can affect even an accepted worker beside Paul.',['Barnabas']),
 ('2-corinthians','titus','Titus','Greek companion whom Paul says was not forced to receive circumcision','He joins Paul and Barnabas at the remembered Jerusalem visit.','Galatians 2:1–3','His presence turns the question about Gentile belonging into a decision concerning a particular person.',['Titus']),
 ('genesis','abraham','Abraham','Ancestor whose promise supplies the basis for Paul’s argument','His two sons and their mothers later become part of Paul’s symbolic comparison.','Galatians 3; 4','The promise’s earlier place prevents the later law from canceling its inheritance.',['Abraham']),
 ('genesis','hagar','Hagar','Mother whom Paul uses as a figure for bondage in his comparison','Paul places her son beside the free woman’s son.','Galatians 4:24–25','Her role here belongs to Paul’s argument rather than her own spoken account.',['Hagar']),
 ('genesis','isaac','Isaac','Promised son with whom Paul compares the believers','Paul calls the believers children of promise like him.','Galatians 4:28','His recalled birth connects the earlier promise with the hearers’ claimed inheritance.',['Isaac'])]
people=[];profileChapters={'paul':list(range(1,7)),'jesus':list(range(1,7)),'peter':[1,2],'barnabas':[2],'titus':[2],'abraham':[3,4],'hagar':[4],'isaac':[4]};art={}
for book,pid,name,role,relations,passages,meaning,links in rows:
 p=person(pid,name,role,relations,passages,meaning);old=json.loads((OUT/(book+'.json')).read_text(encoding='utf8'));p['life']=next(x for x in old['people'] if x['id']==pid)['life'];p.update(placeIds=[],linkNames=links,verseScope={});people.append(p)
 a=json.loads((OUT/(book+'-art.json')).read_text(encoding='utf8'));art[pid]=a[pid]
places=copy.deepcopy([p for p in acts['places'] if p['id'] in ['jerusalem','damascus','antioch-syria']])
for p in places:
 p.update(verseScope={},summary={'jerusalem':'Jerusalem appears in Paul’s remembered visits and his later symbolic comparison.','damascus':'Damascus appears in Paul’s remembered account of his early travels.','antioch-syria':'Antioch is the recalled setting of the dispute over shared meals.'}[p['id']])
 if p['id']=='antioch-syria':p['name']='Antioch';p.pop('linkNames',None)
 if p['id']=='jerusalem':p['verseScope']={'4':[25]}
summaries=['Paul challenges a competing message and recalls the source of his own call.','Shared recognition in Jerusalem leads into Paul’s recalled dispute over divided meals.','The received Spirit, Abraham’s promise, and baptism support shared inheritance.','Received belonging leads into Paul’s appeal and symbolic comparison of two mothers.','Freedom through Christ leads into service through love and the Spirit’s fruit.','Gentle repair, shared burdens, patient work, and the cross answer competing boasts.']
questions=['Why does Paul distinguish revelation from instruction by the earlier apostles?','How does Peter’s meal withdrawal conflict with the earlier shared recognition?','Why can the later law not cancel Abraham’s earlier promise?','Why must the two mothers’ roles here remain part of Paul’s stated comparison?','How does freedom become service rather than permission to harm others?','How do shared burdens and personal examination support each other?']
teach={1:'The selected lesson studies the problem of turning toward another message.',3:'The selected lesson connects receiving the Spirit with the gospel’s freedom.',4:'The selected lesson studies Paul’s appeal against returning to bondage.',5:'The selected lesson teaches freedom through love and conduct shaped by the Spirit.',6:'The selected lesson teaches patient work and the later consequences of choices.'};chapters=[]
for n,v,title,meaning in notes:
 loc=['jerusalem','damascus'] if n==1 else ['jerusalem','antioch-syria'] if n==2 else ['jerusalem'] if n==4 else []
 chapters.append(dict(chapter=n,title=title,summary=summaries[n-1],meaning=meaning,people=[pid for pid,cc in profileChapters.items() if n in cc],places=loc,sourceIds=['web']+(['works-galatians'] if n==3 else []),lds=dict(text=teach.get(n,'')+(' ' if n in teach else '')+'Study question. '+questions[n-1],sourceIds=['cfm-nt-2023-40'] if n in teach else []),eventOrder=n,dateLabel='Book order',historicalNote=meaning,mapNote='Markers show named earthly cities in Paul’s memories and comparison. Jerusalem above and Mount Sinai have no invented location.',route=[],routeEvidence='Remembered visits do not establish an exact route or complete travel history.'))
data=dict(id='galatians',bibleCode='GAL',name='Galatians',description='Promise · belonging · disputed meals · freedom · the Spirit',chapterCount=6,scripture=t,chapters=chapters,people=people,places=places,sources=sources,review=dict(date=DATE,contextReviewDate=DATE,copyReviewDate=DATE,scope='All 149 verses read for six original contextual explanations and exact selections. Eight selected profiles and three city references do not claim exhaustive coverage. One Church lesson retains actual chapter discussion. Works’ interpretation remains attributed. Opponents’ replies, exact dates, original manuscripts, Greek forms, Sinai’s location, and a reconstructed harmony with Acts were not independently verified.',nextBook='ephesians'))
if '--ready' in sys.argv:
 (OUT/'galatians-art.json').write_text(json.dumps(art,ensure_ascii=False,indent=2)+'\n',encoding='utf8');finish(data)
else:(ROOT/'review/galatians-draft.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
