"""Build Malachi with complete disputes and separate later Restoration readings."""
import json,sys
from book_common import ROOT,OUT,scripture,source,person,finish
DATE='2026-10-07'
t=scripture('malachi','MAL',4)
assert [len(t[str(n)]) for n in range(1,5)]==[14,17,18,6]
assert not any('\ufffd' in v['text'] for vv in t.values() for v in vv)
notes=json.loads((ROOT/'scripts/book-context-complete/malachi.json').read_text(encoding='utf8'))
s=source('web','Malachi · World English Bible','https://ebible.org/engwebp/MAL01.htm','All four chapters appear in the reading text.','Scripture','historical','The book supplies no secure personal biography for Malachi or exact date for its disputes.')
s.update(author='World English Bible translators',publisher='eBible.org',chapterCoverage=[1,2,3,4],reviewed=dict(date=DATE,scope='All 55 verses read. Verse counts and character integrity checked.'));sources=[s]
s=source('stewart-malachi','Commentary on Malachi 3:1-4','https://www.workingpreacher.org/commentaries/revised-common-lectionary/second-sunday-of-advent-3/commentary-on-malachi-31-4-8','Stewart explains the visitor’s uncertain identity and the purification of worship.','Scholarly study','historical','Whether Malachi is a personal name or a messenger title remains uncertain. Christian Advent applications are later readings.')
s.update(author='Anne Stewart',year=2024,publisher='Luther Seminary',chapterCoverage=[3],reviewed=dict(date=DATE,scope='Complete commentary body and note read. This 2024 page identifies previous publication in 2015. Linked related commentaries were not reviewed.'));sources.append(s)
s=source('cfm-malachi-2026','December 14–20: “I Have Loved You, Saith the Lord” · Malachi','https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-old-testament-2026/51?lang=eng','The lesson studies offerings, returning to God, tithing, and Elijah through Restoration scripture.','LDS Come, Follow Me','lds','Moroni’s changed quotation and the later Elijah account remain Church readings, separate from the original wording.')
s.update(author='The Church of Jesus Christ of Latter-day Saints',year=2026,publisher='The Church of Jesus Christ of Latter-day Saints',chapterCoverage=[1,2,3,4],reviewed=dict(date=DATE,scope='Introduction and adult study sections read, including the explicit 2:17 question. Linked conference messages, videos, and Scripture Helps were not separately reviewed.'));sources.append(s)
p=person('malachi','Malachi, the named messenger','Messenger named at the opening of the book','The book gives no family history or secure personal dates.','Malachi 1–4','The repeated disputes connect rejected offerings with failures in teaching and treatment of others.')
p.update(placeIds=[],linkNames=['Malachi'],verseScope={})
ex=json.loads((OUT/'exodus.json').read_text(encoding='utf8'));king=json.loads((OUT/'2-kings.json').read_text(encoding='utf8'));jer=json.loads((OUT/'jeremiah.json').read_text(encoding='utf8'))
m=dict(next(p for p in ex['people'] if p['id']=='moses'));m.update(role='Earlier servant whose instruction the people must remember',relations='The final chapter recalls the instruction given through him for Israel.',passages='Malachi 4:4',meaning='Remembered instruction connects preparation for the coming day with the people’s existing obligations.',sourceIds=['web'],placeIds=[],linkNames=['Moses'],verseScope={})
e=dict(next(p for p in king['people'] if p['id']=='elijah'));e.update(role='Prophet promised before the coming day of the Lord',relations='The closing promise connects his coming with changed hearts between parents and children.',passages='Malachi 4:5–6',meaning='His promised task concerns restored relationships before the warning’s final curse.',sourceIds=['web'],placeIds=[],linkNames=['Elijah'],verseScope={})
q=dict(next(q for q in jer['places'] if q['id']=='jerusalem'));q.update(summary='Jerusalem appears in the accusation about broken bonds and the promise of acceptable offerings.',sourceIds=['web'],limits='Approximate city marker. The disputes give no specific altar layout or travel route.')
d=dict(next(q for q in jer['places'] if q['id']=='edom'));d.update(summary='Edom appears in the opening dispute about love and the threatened rebuilding of ruined places.',sourceIds=['web'],limits='Broad regional reference. The passage gives no particular ruined town or border line.')
summaries=['God answers doubts about love and rejects offerings that expose contempt.','Priests corrupt teaching. Betrayed marriages and doubted justice continue the dispute.','A visitor purifies worship and judges wrongdoing. Disputes address food offerings and apparently successful evildoers.','The coming day brings judgment and healing. The ending recalls Moses and promises Elijah.']
questions=['Why does God compare the offerings with gifts presented to a governor?','Why can tears at the altar fail to answer betrayal of a spouse?','Whose injuries does the judgment name when it answers demands for justice?','Why does the final promise concern changed hearts between parents and children?']
ldsNotes=['The lesson asks readers to consider whether their offerings show honor for God.','The lesson uses the complaint about justice to examine attitudes during difficult times.','The lesson connects tithing with faith and returning to God.','The lesson reads Elijah’s promise through Moroni’s quotation and the later Kirtland Temple account.']
chapters=[]
for n,v,title,meaning in notes:
 loc=['edom'] if n==1 else ['jerusalem'] if n in [2,3] else []
 ids=['malachi']+(['moses','elijah'] if n==4 else [])
 chapters.append(dict(chapter=n,title=title,summary=summaries[n-1],meaning=meaning,people=ids,places=loc,sourceIds=['web']+(['stewart-malachi'] if n==3 else []),lds=dict(text=ldsNotes[n-1]+' Study question. '+questions[n-1],sourceIds=['cfm-malachi-2026']),eventOrder=n,dateLabel='Book order',historicalNote=meaning,mapNote='Markers locate selected geographic references. No movements or precise worship buildings are reconstructed.' if loc else 'The chapter names Horeb in remembered instruction. Its uncertain location receives no marker or route.',route=[],routeEvidence='Disputes and future promises give no continuous traveled route.'))
data=dict(id='malachi',bibleCode='MAL',name='Malachi',description='Doubted love · rejected offerings · fidelity · justice · changed hearts',chapterCount=4,scripture=t,chapters=chapters,people=[p,m,e],places=[q,d],sources=sources,review=dict(date=DATE,contextReviewDate=DATE,copyReviewDate=DATE,scope='All 55 WEB verses read for four original contextual explanations. Three selected profiles include an inspected messenger portrait and inspected reused Moses and Elijah artwork. The messenger’s personal identity remains uncertain.',nextBook='matthew'))
if '--ready' in sys.argv:finish(data)
else:(ROOT/'review/malachi-draft.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
