"""Build Amos with complete Scripture and original chapter explanations."""
import json,sys
from book_common import ROOT,OUT,scripture,source,person,finish
DATE='2026-10-07'
t=scripture('amos','AMO',9)
assert [len(t[str(n)]) for n in range(1,10)]==[15,16,15,13,27,14,17,14,15]
assert not any('\ufffd' in v['text'] for vv in t.values() for v in vv)
notes=json.loads((ROOT/'scripts/book-context-complete/amos.json').read_text(encoding='utf8'))
sources=[source('web','Amos · World English Bible','https://ebible.org/engwebp/AMO01.htm','All nine chapters appear in the reading text.','Scripture','historical','Relative dates remain as Scripture gives them. The guide assigns no exact earthquake year.')]
sources[0].update(author='World English Bible translators',publisher='eBible.org',chapterCoverage=list(range(1,10)),reviewed=dict(date=DATE,scope='All 146 WEB verses read. Verse counts and character integrity checked.'))
s=source('aaron-amos-5','Commentary on Amos 5:18-24','https://www.workingpreacher.org/commentaries/revised-common-lectionary/ordinary-32/commentary-on-amos-518-24','Aaron explains rejected worship and justice that must continue beyond a single act.','Scholarly study','historical','Aaron discusses differing readings of the water image. This interpretation does not prove every event or assumption about the audience.')
s.update(author='Charles L. Aaron, Jr.',year=2020,publisher='Luther Seminary',chapterCoverage=[5],reviewed=dict(date=DATE,scope='Complete commentary body read. Linked commentaries and podcasts were not reviewed.'));sources.append(s)
s=source('cfm-amos-2026','November 23–29: “Seek the Lord, and Ye Shall Live” · Amos, Obadiah, Jonah','https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-old-testament-2026/48?lang=eng','The lesson studies prophetic instruction, returning to God, and spiritual hunger.','LDS Come, Follow Me','lds','Notes cover Amos 3–5 and 7–8. The later Apostasy and Restoration application remains Church teaching.')
s.update(author='The Church of Jesus Christ of Latter-day Saints',year=2026,publisher='The Church of Jesus Christ of Latter-day Saints',chapterCoverage=[3,4,5,7,8],reviewed=dict(date=DATE,scope='Introduction and adult study sections read. Linked talks, videos, and Scripture Helps were not separately reviewed.'));sources.append(s)
people=[]
for row in [('amos','Amos','Herdsman and grower of sycamore figs who speaks to Israel','He disputes Amaziah’s claim that royal authority can stop his words.','Amos 1–9','His warnings connect worship with justice, honest trade, and care for poor people.'),('amaziah','Amaziah of Bethel','Priest who orders Amos away from the royal sanctuary','He reports Amos’s words to Jeroboam. He is distinct from the king named Amaziah.','Amos 7:10–17','His appeal to royal control brings the conflict over prophetic speech into public view.')]:
 p=person(*row);p.update(placeIds=[],linkNames=[p['id'].capitalize()]);people.append(p)
old=json.loads((OUT/'jeremiah.json').read_text(encoding='utf8'))
places=[]
for i,s in [('jerusalem','Jerusalem is named in warnings directed toward Judah and the opening divine roar.'),('damascus','Damascus receives a charge about violence and later marks a warning of distant captivity.'),('tyre','Tyre faces a charge about handing over whole captive communities.'),('edom','Edom faces charges about continuing violence against a brother people.'),('rabbah','Rabbah receives a warning within the speech against Ammon.'),('samaria','Samaria is the city where wealth, oppression, and false security receive public scrutiny.'),('egypt','Egypt appears among the remembered places of rescue and the witnesses to Samaria’s wrongdoing.')]:
 q=dict(next(p for p in old['places'] if p['id']==i));q.update(summary=s,sourceIds=['web'],limits='Approximate geographic reference. Prophetic warnings do not establish a traveled route or an exact battlefield.');places.append(q)
summaries=['Neighboring peoples face charges for violence, captivity, and broken agreements.','The charges turn toward Israel’s exploitation of needy people beside its altars.','Chosen belonging increases responsibility. Foreign witnesses must observe Samaria’s oppression.','Proud offerings continue while repeated disasters bring no return to God.','Seeking life requires fair courts. Worship cannot replace sustained justice.','Comfortable leaders refuse to grieve for others. Their leading place becomes first captivity.','Amos pleads for mercy, then disputes Amaziah’s attempt to protect the royal sanctuary.','Dishonest traders exploit poor buyers. A later famine concerns God’s words.','No hiding place can secure the sinful kingdom. The ending promises rebuilt homes and vineyards.']
questions=['What human costs do the repeated charges name?','Why do garments and wine beside altars expose wrongdoing?','Why does chosen belonging increase responsibility?','What remains unchanged throughout the repeated disasters?','How do unfair courts explain the rejection of festivals?','What suffering do the comfortable leaders refuse to grieve?','Why does Amaziah call Bethel the king’s sanctuary?','How do false measures connect trade with loss of freedom?','How do inhabited cities reverse earlier warnings about lost houses?']
ldsNotes={3:'The 2026 lesson connects prophetic speech with receiving God’s instruction.',4:'The lesson invites return to God during trials. It does not claim that God sends every personal trial.',5:'The lesson studies seeking God and choosing good as a path toward life.',7:'The lesson studies Amos’s calling as an example of God speaking through prophets.',8:'The lesson applies hunger for God’s words to spiritual life. It also connects this image with the later Apostasy and Restoration.'}
loc={1:['jerusalem','damascus','tyre','edom','rabbah'],2:['edom','jerusalem','egypt'],3:['samaria','egypt'],4:['samaria','egypt'],5:['damascus'],6:['samaria'],7:[],8:['samaria','egypt'],9:['egypt','edom']}
chapters=[]
for n,v,title,meaning in notes:
 chapters.append(dict(chapter=n,title=title,summary=summaries[n-1],meaning=meaning,people=['amos']+(['amaziah'] if n==7 else []),places=loc[n],sourceIds=['web']+(['aaron-amos-5'] if n==5 else []),lds=dict(text=(ldsNotes.get(n,'')+' Study question. '+questions[n-1]).strip(),sourceIds=['cfm-amos-2026'] if n in ldsNotes else []),eventOrder=n,dateLabel='Book order',historicalNote=meaning,mapNote='Selected named references have approximate markers. Warnings do not establish traveled routes.' if loc[n] else 'Selected places are not mapped in this chapter. No precise royal sanctuary location is assigned.',route=[],routeEvidence='No continuous traveled route is reconstructed from speeches.'))
data=dict(id='amos',bibleCode='AMO',name='Amos',description='Public justice · honest trade · rejected worship · challenged speech · restored homes',chapterCount=9,scripture=t,chapters=chapters,people=people,places=places,sources=sources,review=dict(date=DATE,contextReviewDate=DATE,copyReviewDate=DATE,scope='All WEB chapters read for nine original explanations. Two profiles are selected, not a complete inventory. Sources retain review and coverage limits.',nextBook='obadiah'))
if '--ready' in sys.argv:finish(data)
else:(ROOT/'review/amos-draft.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
