import json
from book_common import ROOT,OUT,scripture,source,person,place,finish
GEN=json.loads((OUT/'genesis.json').read_text(encoding='utf-8'))
rows='''
Oppression and the midwives|A new king enslaves Israel. Shiphrah and Puah refuse his order to kill boys.|The ruler fears a growing people. The midwives protect life against his command.|shiphrah,puah,pharaoh|egypt,rameses,pithom|Consider how reverence for God can require resistance to cruelty.
Moses preserved and exiled|Moses's mother hides him. Pharaoh's daughter adopts him. He later kills an Egyptian and flees.|Several women preserve a vulnerable child. Moses's later violence leads to exile.|moses,jochebed,miriam,pharaoh-daughter,zipporah,jethro|egypt,midian|Moses 1 expands Moses's later encounter with God. Keep that account distinct from his childhood.
The burning bush|God calls Moses at Horeb. Moses must confront Pharaoh and lead Israel out.|God hears the people's suffering. Moses questions his ability to carry the task.|moses|horeb,midian|The Church manual reads Moses's call as preparation for prophetic service.
Moses returns|God gives Moses signs. Aaron joins him. Zipporah acts during a dangerous encounter.|Moses voices his limits. Shared service and action carry the mission forward.|moses,aaron,zipporah|midian,egypt|Consider how help from others can accompany an assignment from God.
Pharaoh increases the burden|Moses and Aaron ask for release. Pharaoh withholds straw but demands the same brick count.|The first appeal brings worse conditions. The people question Moses's promise of deliverance.|moses,aaron,pharaoh|egypt|Consider the strain of trusting a promise when conditions first become worse.
God renews the promise|God promises deliverance and covenant belonging. A family record identifies Moses and Aaron.|Oppression makes the people unable to hear hope. God still names their promised future.|moses,aaron,amram,jochebed|egypt|The covenant promise includes belonging to God. Consider hope without blaming those exhausted by suffering.
Staff and river|Aaron's staff becomes a serpent. The Nile's water turns to blood.|The struggle reaches Egypt's source of life. Pharaoh continues to refuse release.|moses,aaron,pharaoh|egypt|Consider the effects of a ruler's refusal on the people under his power.
Frogs, lice, and flies|Three plagues strike Egypt. Pharaoh promises relief and then changes his decision.|Words given under pressure do not become lasting action. The conflict continues.|moses,aaron,pharaoh|egypt,goshen|Consider whether your promises remain firm when immediate pressure ends.
Livestock, boils, and hail|Further plagues affect animals and people. Some Egyptians heed the warning about hail.|The warnings leave room for response. Pharaoh's admission of guilt does not produce lasting change.|moses,aaron,pharaoh|egypt,goshen|Consider how repentance differs from a statement made only to end pain.
Locusts and darkness|Pharaoh rejects full release. Locusts consume crops. Darkness covers Egypt.|Partial offers keep the people under Pharaoh's control. The dispute concerns genuine freedom to worship.|moses,aaron,pharaoh|egypt|Consider how worship can require more than a restricted permission from a ruler.
The final plague announced|Moses announces the death of the firstborn. Pharaoh still refuses release.|The warning brings the conflict to a terrible cost. The account includes suffering beyond the ruler.|moses,pharaoh|egypt|Read the promised deliverance alongside the human cost within the narrative.
Passover and departure|Israel keeps Passover. The firstborn die. Pharaoh releases the people. They leave Rameses.|The meal becomes a lasting act of memory. Deliverance also carries grief through Egypt.|moses,aaron,pharaoh|rameses,succoth|The Church manual connects the Passover lamb with Jesus Christ. Study the sign and the remembered deliverance.
Remembering and the pillars|God commands remembrance of the firstborn and unleavened bread. Cloud and fire lead the people.|Memory takes the form of household teaching. The chosen route avoids an immediate return through fear.|moses,joseph|succoth,etham|Consider how repeated worship can teach children about God's deliverance.
The sea crossing|Pharaoh pursues Israel. Moses stretches out his hand. Israel crosses and the army is overwhelmed.|The narrative places fear beside deliverance. The precise crossing site remains unknown.|moses,pharaoh|sea-region|First Nephi 17 recalls this deliverance. Keep that later teaching distinct from the crossing narrative.
Songs and bitter water|Moses and Miriam lead songs. The people reach bitter water and then Elim.|Praise and need follow each other. The journey still requires water after a great deliverance.|moses,miriam|marah,elim|Consider how gratitude and present needs can both appear in a life of faith.
Manna and Sabbath|God provides manna and quail. The people gather food daily and rest on the Sabbath.|Daily provision tests trust. Limits on gathering restrain hoarding and support rest.|moses,aaron|wilderness-sin|The Church manual connects manna with reliance on God. Consider daily preparation and Sabbath rest.
Water and Amalek|God provides water at Rephidim. Joshua leads the fight against Amalek while others support Moses.|The people need both water and protection. Shared action supports leadership during danger.|moses,aaron,joshua,hur|rephidim|Consider why support for others belongs alongside individual faith.
Jethro's counsel|Jethro visits Moses. He advises shared responsibility for judging the people's disputes.|One leader cannot carry every need alone. Delegation makes judgment more accessible.|moses,jethro,zipporah|sinai|Consider how wise counsel can improve service and reduce an unfair burden.
At Sinai|Israel reaches Sinai. God offers a covenant. The people prepare for God's presence.|The covenant joins privilege with responsibility. Preparation marks the encounter as sacred.|moses,aaron|sinai|The Church manual connects covenant belonging with duties of holiness and service.
The Ten Commandments|God gives commands about worship and relationships. The people fear the encounter.|Freedom receives a moral structure. The commands protect worship, life, family, and trust.|moses|sinai|The Church manual studies each command as a continuing guide to faithful conduct.
Laws about servants and injury|The laws address servitude, violence, and responsibility for injury.|The laws regulate an unequal ancient society. Regulation does not remove the harm of slavery.|moses|sinai|Consider the difference between an ancient legal setting and present moral duties toward people.
Property and vulnerable people|The laws address theft, damaged property, loans, and care for strangers, widows, and orphans.|Justice concerns both property and people with little power. Israel must remember its own experience in Egypt.|moses|sinai|Consider how remembering past need can shape care for vulnerable people now.
Justice, rest, and festivals|God commands honest judgment, rest, and annual feasts. An angel will lead Israel.|Worship and justice belong together. The law includes care even toward an enemy's animal.|moses|sinai|Consider whether your worship also changes your judgment and treatment of others.
The covenant confirmed|Moses reads the covenant terms. Israel accepts them. Moses ascends the mountain.|The people hear before they commit. A shared meal and sacred signs mark belonging.|moses,aaron,nadab,abihu,joshua|sinai|A covenant includes an informed promise. Consider the duties that follow your agreement with God.
The ark, table, and lampstand|God gives plans for a sanctuary and its furnishings.|The sanctuary centers on God's presence among the people. Material gifts support a sacred purpose.|moses|sinai|The Church manual connects the tabernacle with worship and God's presence among His people.
The tabernacle structure|God specifies curtains, frames, coverings, and the inner veil.|The design marks distinct sacred spaces. Careful construction gives form to the worship setting.|moses|sinai|Consider how a prepared space can support reverence without replacing faithful conduct.
Altar, court, and light|God gives plans for the altar, courtyard, and daily lamp oil.|The outer space supports offerings and access. Continuing light requires repeated care.|moses,aaron|sinai|Consider the repeated work that sustains a place of worship.
The priests' clothing|God directs the making of Aaron's garments and the breastpiece bearing Israel's names.|The priest represents the people in worship. Sacred service carries names rather than only status.|moses,aaron,nadab,abihu,eleazar,ithamar|sinai|Consider what it means to carry other people's needs within sacred service.
Consecrating the priests|God gives instructions to appoint priests and make daily offerings.|Consecration sets people apart for service. The chapter's purpose is God's dwelling among Israel.|moses,aaron|sinai|The Church manual studies preparation for sacred service. Consider the duties beyond a title.
Incense, washing, and sacred oil|God gives instructions for incense, washing, the census payment, and sacred oil.|These repeated acts order worship and preparation. Sacred materials have a defined purpose.|moses,aaron|sinai|Consider how preparation can support worship without becoming only an outward routine.
Skilled workers and Sabbath|God appoints Bezalel and Oholiab. The Sabbath remains a covenant sign. Moses receives tablets.|Skilled labor serves worship. Even sacred construction does not erase the command to rest.|moses,bezalel,oholiab|sinai|Consider how creative skill and Sabbath observance can both serve God.
The golden calf|Aaron makes the calf. Moses intercedes, breaks the tablets, and confronts the camp.|The covenant breaks almost immediately. The account includes both intercession and severe judgment.|moses,aaron,joshua|sinai|Consider how quick substitutes for trust can damage a covenant relationship.
Moses seeks God's presence|Moses meets with God outside the camp. He asks for guidance and God's continuing presence.|Restoration concerns more than reaching a destination. Moses seeks the presence that gives the journey meaning.|moses,joshua|sinai|Consider whether your requests seek God's companionship as well as a desired outcome.
The covenant renewed|God declares mercy and justice. New tablets are given. Moses returns with a shining face.|Renewal follows covenant failure. Mercy does not make responsibility disappear.|moses|sinai|The Church manual reads renewal alongside repentance. Consider mercy with continuing responsibility.
Gifts and willing work|Moses teaches Sabbath rest. The people bring materials. Skilled workers begin their tasks.|The work uses willing gifts and different skills. Participation reaches beyond a single leader.|moses,bezalel,oholiab|sinai|Consider how willingness and varied skills can build a worshiping community.
More than enough|The gifts exceed the need. The workers build the tabernacle's curtains, frames, and veil.|Generosity serves a defined purpose. Leaders stop the collection when enough has been given.|bezalel,oholiab|sinai|Consider how wise stewardship includes knowing when a collection has met its need.
The furnishings made|Bezalel makes the ark, table, lampstand, and incense altar.|The workers carry the earlier instructions into action. Repeated detail emphasizes faithful completion.|bezalel|sinai|Consider the place of careful work in fulfilling a sacred responsibility.
Altar, court, and accounts|The workers build the outer furnishings. The chapter records the materials used.|Sacred work includes public accounting. The record names skilled workers and their responsibilities.|bezalel,oholiab,ithamar|sinai|Consider how clear records and accountable service can support trust.
Garments and inspection|The workers finish the priests' clothing. Moses inspects the completed work and blesses them.|Completion receives review rather than assumption. The blessing follows work done according to the instructions.|moses,aaron,bezalel,oholiab|sinai|Consider how careful review can honor the work of those who serve.
The tabernacle raised|Moses sets up the sanctuary. God's glory fills it. Cloud and fire guide later journeys.|The book ends with God's presence among a traveling people. Deliverance leads toward worship and continuing guidance.|moses,aaron|sinai|The Church manual connects the sanctuary with God's presence. Consider worship as part of the journey after deliverance.
'''.strip().splitlines()
web=source('web','Exodus — World English Bible','https://ebible.org/engwebp/EXO01.htm','The public-domain reading text supplies all 40 chapters.','Scripture',limits='The reading text narrates events. It does not independently confirm their historical dates.')
sources=[web]+[dict(s) for s in GEN['sources'] if s['id'] in ['atlas','atlas-canaan','terrain']]
sources.append(source('atlas-exodus','Bible Maps: Israel’s Exodus from Egypt and Entry into Canaan','https://www.churchofjesuschrist.org/study/scriptures/bible-maps/map-2?lang=eng','The Church-published map marks a traditional route and several uncertain sites.','Geography',limits='The displayed route is a study tradition. It does not establish a verified sea crossing or Sinai site.'))
for num,title,summary in [(7,'Israel in Egypt: Moses and the Beginning of Yahwism','Christine Hayes studies the transition from Joseph to Moses and the limits of external evidence.'),(8,'Exodus: From Egypt to Sinai','Christine Hayes studies deliverance, covenant, and the literary shape of Exodus.'),(9,'The Priestly Legacy','Christine Hayes examines priestly worship, sacrifice, purity, and sacred space.'),(10,'Biblical Law','Christine Hayes compares biblical law with ancient legal traditions.')]:sources.append(source(f'yale-{num}',title+' — Open Yale Courses',f'https://oyc.yale.edu/religious-studies/rlst-145/lecture-{num}',summary,limits='Academic interpretation remains separate from LDS teaching. Scholars debate dating and composition.'))
MANUAL='https://www.churchofjesuschrist.org/study/manual/old-testament-student-manual-genesis-2-samuel/'
for sid,title,slug in [('lds-call','Exodus 1–10: Let My People Go','exodus-1-10-let-my-people-go'),('lds-deliverance','Exodus 11–19: The Passover and the Exodus','exodus-11-19-the-passover-and-the-exodus'),('lds-commandments','Exodus 20: The Ten Commandments','exodus-20-the-ten-commandments'),('lds-law','Exodus 21–24; 31–35: The Mosaic Law: A Preparatory Gospel','exodus-21-24-31-35-the-mosaic-law-a-preparatory-gospel'),('lds-sanctuary','Exodus 25–30; 35–40: The House of the Lord in the Wilderness','exodus-25-30-35-40-the-house-of-the-lord-in-the-wilderness')]:sources.append(source(sid,title,MANUAL+slug+'?lang=eng','Church study notes discuss this passage range through LDS teachings.','LDS study manual','lds',limits='This older manual includes commentary. Its explanations are not independent archaeological evidence.'))
for sid,title,path in [('moses-1','Moses 1','pgp/moses/1'),('nephi-17','1 Nephi 17','bofm/1-ne/17')]:sources.append(source(sid,title,'https://www.churchofjesuschrist.org/study/scriptures/'+path+'?lang=eng','This LDS scripture provides a related Restoration reading.','LDS scripture','lds',limits='Keep this later scripture distinct from Exodus’s own words.'))
places=[dict(p) for p in GEN['places'] if p['id'] in ['egypt','goshen']]
for pid,name,a,b,summary,limits in [
('rameses','Rameses / eastern delta',30.8,31.84,'Israel builds storage cities and later departs from Rameses.','The marker represents a proposed eastern delta setting. The chronology remains debated.'),
('pithom','Pithom / eastern delta',30.55,32.07,'Exodus names Pithom as a storage city built under forced labor.','The identification is debated. This is an approximate regional marker.'),
('midian','Midian',28.4,35.3,'Moses seeks refuge among Jethro’s household in Midian.','This marker shows a broad region. It does not identify Moses’s home.'),
('horeb','Horeb / Sinai tradition',28.54,33.97,'God calls Moses at Horeb, the mountain of God.','The southern Sinai placement reflects a tradition. Other proposed locations exist.'),
('sinai','Sinai / traditional region',28.54,33.97,'Israel receives the covenant and builds the sanctuary near Sinai.','The mountain’s identity is disputed. This marker is not a verified site.'),
('succoth','Succoth / delta region',30.55,32.08,'Exodus names Succoth after the departure from Rameses.','The exact campsite is unknown. This is an approximate regional placement.'),
('etham','Etham / wilderness edge',30.5,32.3,'Israel reaches Etham at the wilderness edge.','The exact place is unknown. The marker follows a broad eastern delta setting.'),
('sea-region','Sea crossing / uncertain region',30.3,32.4,'Exodus 14 narrates a crossing through the sea.','This marker shows a broad possible region. It does not choose a verified crossing point.'),
('marah','Marah / uncertain wilderness site',29.4,32.7,'Israel reaches bitter water after leaving the sea.','The site is uncertain. This placement follows a traditional Sinai-region reading.'),
('elim','Elim / traditional region',29.2,32.9,'Exodus describes twelve springs and seventy palms at Elim.','The exact oasis is uncertain. The marker is a regional reference.'),
('wilderness-sin','Wilderness of Sin / traditional region',28.9,33.3,'Israel receives manna in the wilderness between Elim and Sinai.','Its boundaries are unknown. The marker follows a traditional southern route.'),
('rephidim','Rephidim / traditional region',28.73,33.65,'Israel needs water and fights Amalek near Rephidim.','The site is uncertain. The marker does not identify the rock or battlefield.')]:places.append(place(pid,name,a,b,summary,limits,['web','atlas-exodus']))
people=[]
for row in '''
moses|Moses|Prophet who leads Israel from Egypt|Son of Amram and Jochebed. Brother of Aaron and Miriam. Husband of Zipporah.|Exodus 2–40|His call begins the confrontation with Pharaoh. He later leads, intercedes, and receives covenant instructions.
aaron|Aaron|Moses's brother and appointed priest|Son of Amram and Jochebed. Father of Nadab, Abihu, Eleazar, and Ithamar.|Exodus 4–40|He speaks with Moses and serves in worship. His role in the calf episode also requires attention.
miriam|Miriam|Prophetess and sister of Moses|Sister of Moses and Aaron. The watching sister in Exodus 2 is unnamed there.|Exodus 15:20–21|She leads women in song after deliverance. Her later story continues in Numbers.
jochebed|Jochebed|Mother of Moses and Aaron|Wife of Amram. Member of Levi's family.|Exodus 2; 6:20|The family record names her. Exodus 2 describes the mother's actions to preserve Moses.
amram|Amram|Father of Moses and Aaron|Husband of Jochebed. Descendant of Levi.|Exodus 6:18–20|The family record links Moses and Aaron to Levi. Exodus records little direct action by Amram.
pharaoh-daughter|Pharaoh's daughter|Unnamed Egyptian woman who adopts Moses|Daughter of the ruler. Adoptive mother of Moses.|Exodus 2:5–10|She recognizes a Hebrew child and protects him. Exodus does not give her a personal name.
shiphrah|Shiphrah|Midwife who protects Hebrew boys|Named alongside Puah.|Exodus 1:15–21|She refuses the king's order to kill. Her action supports life under oppression.
puah|Puah|Midwife who resists the king's command|Named alongside Shiphrah.|Exodus 1:15–21|Her courage appears before Moses's public work. She protects children threatened by royal policy.
zipporah|Zipporah|Moses's wife|Daughter of Jethro. Mother of Gershom and Eliezer.|Exodus 2; 4; 18|She acts during the difficult circumcision episode. The short account leaves parts of the danger unexplained.
jethro|Jethro / Reuel|Priest of Midian and Moses's father-in-law|Father of Zipporah. The narrative uses more than one name in these accounts.|Exodus 2–4; 18|He welcomes Moses and later gives practical counsel. Shared judging reduces the burden on one leader.
pharaoh|Pharaoh|Title of the Egyptian rulers in Exodus|One ruler seeks Moses's death. A later ruler confronts Moses's demand.|Exodus 1–14|Exodus does not name these kings. Do not identify one with a particular reign as a settled fact.
joshua|Joshua|Military leader and Moses's assistant|Son of Nun. He later leads Israel in the book of Joshua.|Exodus 17; 24; 32–33|He leads the fight with Amalek and accompanies Moses. His service begins before his later leadership.
hur|Hur|Man who supports Moses during battle|He works with Aaron in Exodus 17. A Hur appears in Bezalel's family record.|Exodus 17:10–12; 24:14|He helps hold Moses's hands up. The action makes shared support visible within the narrative.
bezalel|Bezalel|Skilled worker appointed for the sanctuary|Son of Uri. Grandson of Hur. Member of Judah's tribe.|Exodus 31; 35–38|His skill includes work in metal, stone, and wood. He directs the making of sacred furnishings.
oholiab|Oholiab|Skilled worker alongside Bezalel|Son of Ahisamach. Member of Dan's tribe.|Exodus 31; 35–38|His work includes design and textiles. The sanctuary requires several kinds of skill.
nadab|Nadab|Son of Aaron who approaches Sinai|Son of Aaron. Brother of Abihu, Eleazar, and Ithamar.|Exodus 6; 24; 28|He joins the covenant encounter with the elders. His later death is narrated in Leviticus.
abihu|Abihu|Son of Aaron and appointed priest|Son of Aaron. Brother of Nadab, Eleazar, and Ithamar.|Exodus 6; 24; 28|He appears at the covenant meal and among the priests. His later account belongs to Leviticus.
eleazar|Eleazar|Son of Aaron and appointed priest|Brother of Nadab, Abihu, and Ithamar.|Exodus 6; 28|The family and clothing lists name him. His later responsibilities develop in other books.
ithamar|Ithamar|Son of Aaron who oversees sanctuary accounts|Brother of Nadab, Abihu, and Eleazar.|Exodus 6; 28; 38:21|The materials account places him over the Levites' service. Worship includes accountable work.
'''.strip().splitlines():people.append(person(*row.split('|')))
people.append(dict(next(p for p in GEN['people'] if p['id']=='joseph')))
chapters=[]
for n,row in enumerate(rows,1):
    title,summary,meaning,pids,placesIds,lds=row.split('|')
    group='lds-call' if n<=10 else 'lds-deliverance' if n<=19 else 'lds-commandments' if n==20 else 'lds-law' if n<=24 or n in [31,32,33,34] else 'lds-sanctuary'
    yale='yale-7' if n<=4 else 'yale-8' if n<=20 or n==32 else 'yale-10' if n<=24 else 'yale-9'
    historical='Yale’s lecture studies this narrative within Israel’s story of deliverance. The event dates remain debated.' if n<=18 else 'Yale’s lectures examine covenant, law, and priestly worship within their ancient settings.'
    chapters.append(dict(chapter=n,title=title,summary=summary,meaning=meaning,people=pids.split(','),places=placesIds.split(','),sourceIds=['web',yale,'atlas-exodus'],lds=dict(text=lds,sourceIds=[group]+(['moses-1'] if n==2 else ['nephi-17'] if n==14 else [])),eventOrder=n,dateLabel='Narrative order · historical year debated',mapNote='Site markers follow a traditional regional reading. Many campsites and the sea crossing remain uncertain.',historicalNote=historical,route=['egypt','midian'] if n==2 else ['midian','egypt'] if n==4 else ['rameses','succoth'] if n==12 else ['succoth','etham'] if n==13 else [],routeEvidence='The narrative connects these named regions. Lines do not establish the precise travel path.'))
finish(dict(id='exodus',bibleCode='EXO',name='Exodus',description='Deliverance · covenant · law · sacred worship',chapterCount=40,scripture=scripture('exodus','EXO',40),chapters=chapters,people=people,places=places,sources=sources,review=dict(date='2026-10-04',scope='All chapters use cached publisher text. Campsites, crossing locations, and event dates remain uncertain.',nextBook='leviticus')))
