"""Build Acts from reviewed publisher chapters and original close readings."""
import json,sys,copy
from book_common import ROOT,OUT,scripture,source,person,place,finish
DATE='2026-10-07';t=scripture('acts','ACT',28)
assert [len(t[str(n)]) for n in range(1,29)]==[26,47,26,37,42,15,60,40,43,48,30,25,52,28,41,40,34,28,41,38,40,30,35,27,27,32,44,31]
assert sum(map(len,t.values()))==1007
assert not any('\ufffd' in str(v) for vv in t.values() for v in vv)
notes=json.loads((ROOT/'scripts/book-context-complete/acts.json').read_text(encoding='utf8'))
base=json.loads((OUT/'matthew.json').read_text(encoding='utf8'));john=json.loads((OUT/'john.json').read_text(encoding='utf8'))
sources=[]
s=source('web','Acts · World English Bible','https://ebible.org/engwebp/ACT01.htm','All 28 chapters appear in the reading text.','Scripture','historical','The account supplies the primary text for original readings. It does not independently verify every event, speech, date, or identity. Publisher notes remain separate from Scripture.')
s.update(author='World English Bible translators',publisher='eBible.org',chapterCoverage=list(range(1,29)),reviewed=dict(date=DATE,scope='All 1,007 numbered verse positions read with selected passages in their surrounding chapters. Empty positions 8:37, 15:34, and 24:7 retain their exact publisher notes. Counts and character integrity checked.'));sources.append(s)
s=source('barreto-acts','Commentary on Acts 10:1-17, 34-35','https://www.workingpreacher.org/commentaries/narrative-lectionary/peters-vision/commentary-on-acts-101-17-34-35','Barreto reads the encounter through the change in Peter and the believing community.','Scholarly study','historical','This is Barreto’s interpretation. Linked essays, podcasts, and related commentaries were not reviewed. Broad claims about ancient groups were not independently verified.')
s.update(author='Eric Barreto',publisher='Luther Seminary',year=2015,chapterCoverage=[10],reviewed=dict(date=DATE,scope='Complete commentary read. The guide attributes its reading of Peter’s changed understanding. Original Greek texts and separately linked works were not reviewed.'));sources.append(s)
lessons=[(28,[1,2,3,4,5],'July 3–9 · Acts 1–5','The lesson teaches the Spirit’s guidance, called apostles, action, and bold witness.'),(29,[7,8,9],'July 10–16 · Acts 6–9','The lesson studies resistance, Simon’s request, Philip’s explanation, and changed lives.'),(30,[10,11,15],'July 17–23 · Acts 10–15','The lesson studies gradual revelation and God’s acceptance across peoples.'),(31,[16,17,18],'July 24–30 · Acts 16–21','The lesson studies courageous witness, spiritual guidance, and being God’s children.'),(32,[22,26,27],'July 31–August 6 · Acts 22–28','The lesson studies testimony, service, and response to the Lord’s servants.')]
for number,coverage,title,summary in lessons:
 s=source('cfm-nt-2023-'+str(number),title,f'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-sunday-school-new-testament-2023/{number:02}?lang=eng',summary,'LDS Come, Follow Me','lds','Selected Church teaching retains actual body coverage. Other chapter headings do not automatically receive teaching coverage.')
 s.update(author='The Church of Jesus Christ of Latter-day Saints',publisher='The Church of Jesus Christ of Latter-day Saints',year=2023,chapterCoverage=coverage,reviewed=dict(date=DATE,scope='Complete lesson body and included additional resources read. Linked talks, videos, manuals, and Restoration passages were not separately reviewed. Only listed Acts chapters receive lesson teaching.'));sources.append(s)
atlas=copy.deepcopy(next(s for s in john['sources'] if s['id']=='atlas-canaan'));sources.append(atlas)
s=source('net-acts-map','NET Bible · selected Acts location references','https://classic.net.bible.org/dictionary.php?word=Antioch','Selected opening descriptions and coordinates distinguish cities named in Acts.','Geographic reference','historical','Broad reference points do not verify ancient events, travel paths, buildings, or coastlines. Older encyclopedia claims about authorship, law, populations, and exact dates were not adopted.')
s.update(author='NET Bible editors and linked reference contributors',publisher='Bible.org',year=None,reviewed=dict(date=DATE,scope='Opening descriptions and coordinate lines read for Rome, Corinth, Ephesus, Athens, Antioch, Caesarea, and Philippi. The Caesarea page also supplies the distinct Philippi coordinate. Both Antiochs remain separate. Only these location references are used.'),links=[dict(label=w,url='https://classic.net.bible.org/dictionary.php?word='+w) for w in ['Rome','Corinth','Ephesus','Athens','Antioch','Caesarea']]);sources.append(s)
people=copy.deepcopy([p for p in base['people'] if p['id'] in ['jesus','peter','mary-mother']])+copy.deepcopy([p for p in john['people'] if p['id']=='thomas'])
for p in people:p.update(placeIds=[],verseScope={},linkNames=['Jesus'] if p['id']=='jesus' else ['Peter','Simon Peter'] if p['id']=='peter' else ['Mary'] if p['id']=='mary-mother' else ['Thomas'])
next(p for p in people if p['id']=='mary-mother').update(role='Mother of Jesus who joins the opening prayer group',relations='She prays with the apostles, other women, and Jesus’ brothers.',passages='Acts 1:14',meaning='Her presence connects the waiting group with Jesus’ earlier family story.',verseScope={'1':[14]})
next(p for p in people if p['id']=='jesus').update(role='Risen teacher who directs witnesses before his departure',relations='The apostles testify about him. Saul’s encounter changes his task.',passages='Acts 1–28',meaning='His name connects witness, healing, disputed hearings, and the message carried to Rome.')
next(p for p in people if p['id']=='peter').update(role='Apostle who speaks publicly and enters Cornelius’ household',relations='John accompanies his early witness. Other believers question his meal with Gentiles.',passages='Acts 1–12; 15',meaning='His remembered experience helps the Jerusalem meeting consider the shared gift of the Spirit.')
next(p for p in people if p['id']=='thomas').update(role='Apostle listed among the group waiting in Jerusalem',relations='He shares the upper room with the other named apostles.',passages='Acts 1:13',meaning='His place in the opening group connects Acts with the earlier resurrection witnesses.')
rows=[
 ('paul','Paul, also called Saul','Former persecutor who becomes a traveling witness','Barnabas supports his welcome. Silas and Timothy later travel with him.','Acts 7–28','His hearings and captivity carry witness into settings his earlier plans did not control.',['Paul','Saul']),
 ('barnabas','Barnabas','Cypriot Levite who gives money and supports other believers','He introduces Saul and later travels with him. Mark joins their service.','Acts 4; 9; 11–15','His encouragement connects shared material care with trust in a former opponent.',['Barnabas','Joses']),
 ('stephen','Stephen','One of seven selected men who speaks before the council','Other believers bury him after his death. Saul watches the stoning.','Acts 6–8; 11:19; 22:20','His speech follows rejected helpers before his own refusal to answer violence with revenge.',['Stephen']),
 ('philip-evangelist','Philip the evangelist','One of the seven who teaches in Samaria and explains Isaiah','He has four daughters who prophesy. His house later welcomes Paul’s group.','Acts 6; 8; 21','His explanation begins with another reader’s question and leads toward Jesus and baptism.',['Philip']),
 ('lydia','Lydia','Seller of purple who welcomes the visiting teachers','Her household receives baptism. Believers later gather at her house.','Acts 16:14–15, 40','Her invitation provides a household setting for the growing group after the riverside meeting.',['Lydia']),
 ('priscilla','Priscilla','Teacher and craft worker who helps Apollos learn more accurately','Aquila is her husband. They work and travel with Paul.','Acts 18','Her shared explanation turns Apollos’ incomplete preparation toward useful teaching among other believers.',['Priscilla']),
 ('aquila','Aquila','Jewish craft worker from Pontus who shares Paul’s trade','Priscilla is his wife. They teach Apollos together.','Acts 18','Work, housing, and private instruction connect his household with the wider teaching task.',['Aquila']),
 ('cornelius','Cornelius','Roman officer whose household receives Peter and the Spirit','He gathers relatives and close friends. Servants bring Peter from Joppa.','Acts 10','His earlier prayers and generosity stand beside the surprising gift witnessed by Peter’s companions.',['Cornelius']),
 ('tabitha','Tabitha, also called Dorcas','Disciple remembered for good works and clothing made for others','Widows show Peter the garments she made before her death.','Acts 9:36–42','The mourners’ displayed garments make her care visible before Peter presents her alive.',['Tabitha','Dorcas']),
 ('silas','Silas','Jerusalem messenger who later travels and suffers with Paul','Judas carries the meeting’s letter with him. Timothy joins the later journey.','Acts 15–18','Spoken encouragement supports the letter before prison tests his continued witness with Paul.',['Silas'])]
for pid,name,role,relations,passages,meaning,links in rows:
 p=person(pid,name,role,relations,passages,meaning);p.update(placeIds=[],linkNames=links,verseScope={});people.append(p)
profileChapters={'jesus':list(range(1,29)),'peter':list(range(1,13))+[15],'mary-mother':[1],'thomas':[1],'paul':list(range(7,29)),'barnabas':[4,9,11,12,13,14,15],'stephen':[6,7,8,11,22],'philip-evangelist':[6,8,21],'lydia':[16],'priscilla':[18],'aquila':[18],'cornelius':[10],'tabitha':[9],'silas':[15,16,17,18]}
next(p for p in people if p['id']=='paul')['verseScope']={'13':[v['verse'] for v in t['13'] if ('Paul' in v['text'] or 'Saul' in v['text']) and v['verse']!=21]}
next(p for p in people if p['id']=='jesus')['verseScope']={'13':[v['verse'] for v in t['13'] if 'Jesus' in v['text'] and v['verse']!=6]}
places=[]
for filename,pid,summary in [('matthew','jerusalem','Jerusalem holds the first witness, council disputes, and Paul’s arrest.'),('jeremiah','damascus','Damascus holds Saul’s changed task, healing, teaching, and escape.'),('2-chronicles','joppa','Joppa holds Tabitha’s household and Peter’s stay before Cornelius’ invitation.'),('matthew','tyre','Tyre appears in Herod’s dispute and Paul’s farewell journey.'),('matthew','sidon','Sidon appears in Herod’s dispute and the imprisoned traveler’s permitted visit.')]:
 d=json.loads((OUT/(filename+'.json')).read_text(encoding='utf8'));p=copy.deepcopy(next(p for p in d['places'] if p['id']==pid));p.update(summary=summary,verseScope={},sourceIds=['web','atlas-canaan']);places.append(p)
for pid,name,lat,lng,summary in [
 ('caesarea','Caesarea on the coast',32+29/60,34+53/60,'Caesarea holds Cornelius’ household and Paul’s later hearings in custody.'),
 ('rome','Rome',41.9,12+29/60,'Rome is the promised destination where Paul remains guarded while teaching visitors.'),
 ('corinth','Corinth',37.9,22+52/60,'Corinth holds shared work, extended teaching, and the hearing before Gallio.'),
 ('ephesus','Ephesus',37.95,27+22/60,'Ephesus holds Apollos’ instruction and the conflict over changed worship and trade.'),
 ('athens','Athens',37+59/60,23+44/60,'Athens holds the speech that begins with an altar and the hearers’ own poets.'),
 ('antioch-syria','Antioch in Syria',36.2,36.15,'Antioch in Syria supports teaching, relief, and the departure of Barnabas and Saul.'),
 ('antioch-pisidia','Antioch of Pisidia',38.3,31+10/60,'Pisidian Antioch holds a synagogue invitation, wider interest, and divided responses.'),
 ('philippi','Philippi',41,24+17/60,'Philippi holds Lydia’s welcome, the lost income dispute, imprisonment, and the jailer’s household.')]:
 places.append(place(pid,name,lat,lng,summary,'Broad city reference. Exact houses, riverside meeting points, courtrooms, and ancient routes remain unassigned.',['web','net-acts-map']))
next(p for p in places if p['id']=='antioch-syria').update(linkNames=['Antioch'],verseScope={'6':[5],'11':[19,20,22,26,27],'13':[1],'14':[26],'15':[22,23,30,35],'18':[22]})
next(p for p in places if p['id']=='antioch-pisidia').update(linkNames=['Antioch'],verseScope={'13':[14],'14':[19,21]})
locs={1:['jerusalem'],2:['jerusalem','rome'],3:['jerusalem'],4:['jerusalem'],5:['jerusalem'],6:['jerusalem','antioch-syria'],7:['jerusalem'],8:['jerusalem','caesarea'],9:['damascus','jerusalem','caesarea','joppa'],10:['caesarea','joppa','jerusalem'],11:['jerusalem','caesarea','joppa','antioch-syria'],12:['jerusalem','caesarea','tyre','sidon'],13:['antioch-syria','antioch-pisidia','jerusalem'],14:['antioch-pisidia','antioch-syria'],15:['jerusalem','antioch-syria'],16:['philippi','jerusalem'],17:['athens'],18:['athens','corinth','rome','ephesus','jerusalem','caesarea','antioch-syria'],19:['ephesus','corinth','jerusalem','rome'],20:['ephesus','philippi','jerusalem'],21:['tyre','caesarea','jerusalem'],22:['jerusalem','damascus'],23:['jerusalem','rome','caesarea'],24:['caesarea','jerusalem'],25:['caesarea','jerusalem','rome'],26:['caesarea','jerusalem','damascus'],27:['sidon'],28:['rome','jerusalem']}
summaries=['The waiting group selects Matthias after Jesus’ departure.','Many languages lead to Peter’s speech, baptism, and shared care.','A healing brings a crowd and Peter’s explanation.','A council threat meets continued witness, prayer, and shared possessions.','Deceit and deaths precede another arrest, hearing, beating, and continued teaching.','Unequal food service leads to seven appointments before Stephen faces charges.','Stephen answers through Israel’s remembered history before his stoning.','Scattered believers teach. Philip answers an official’s Scripture question.','Saul receives sight and baptism. Peter helps Aeneas and Tabitha.','Peter visits Cornelius’ household, where the Spirit interrupts his speech.','Peter explains the shared gift. Antioch sends relief toward Judea.','James dies, Peter leaves prison, and Herod receives fatal judgment.','Barnabas and Saul travel. Paul’s synagogue speech brings different responses.','Praise turns toward violence before the teachers revisit and strengthen communities.','A meeting answers the circumcision dispute. Paul and Barnabas later separate.','Lydia welcomes the travelers. A lost income dispute leads to prison and another household’s response.','Opposition and tested Scripture readings precede Paul’s speech in Athens.','Shared work and extended teaching precede Apollos’ private instruction.','Changed worship and practice bring costly losses and a trade protest.','Paul travels and gives the elders a farewell warning and example.','Warnings precede Jerusalem’s attempted peace, an accusation, violence, and arrest.','Paul recalls his changed task and claims citizenship before a proposed beating.','A divided council and a reported ambush lead to guarded travel.','Felix hears accusations and Paul’s answer but delays the case.','Festus hears the case. Paul’s appeal makes a clear written charge necessary.','Paul recalls his former violence and new witness before Agrippa.','A storm breaks the ship while the passengers reach land alive.','Malta’s help precedes Rome, guarded lodging, and continued teaching.']
questions=['Why does the replacement need to have accompanied Jesus’ whole ministry?','How does baptism lead into shared meals and care for needs?','Why does Peter refuse credit for the man’s changed condition?','How does the healed man’s presence affect the council’s options?','Why does Peter distinguish ownership from the lie about the sale?','How does the whole group help answer the widows’ complaint?','How does Stephen’s final prayer answer the violence against him?','How does the official’s question differ from Simon’s request for power?','Why does Ananias name his fear before approaching Saul?','What does the Spirit’s arrival change before Peter orders baptism?','Why does Peter compare the household’s gift with the group’s own beginning?','Why does the praying group struggle to believe Rhoda’s report?','How does the next Sabbath’s crowd change the earlier invitation’s outcome?','How do the teachers answer praise that gives them divine status?','Why do trusted messengers accompany the written decision?','How does rescue from suicide lead toward teaching, washed wounds, and a meal?','Why does Paul begin the Athens speech with the hearers’ worship and poetry?','How does private correction prepare Apollos to help other believers?','How does Demetrius connect income with religious honor in his appeal?','Why does Paul connect his own labor with helping weak people?','Which accusation comes from an assumption rather than witnessed temple entry?','Which recalled instruction makes the listening crowd demand Paul’s removal?','How does the nephew’s report change the planned journey?','How do fear and hoped-for money affect Felix’s delay?','Why does Festus still need a clear charge after Paul’s appeal?','Why does Paul exclude his chains from what he wishes for his hearers?','Why do promised lives still require the sailors to remain aboard?','Why does the book end with teaching rather than the appeal’s final verdict?']
teach={1:'The selected lesson teaches that apostles receive their call through revelation.',2:'The selected lesson connects the Spirit’s prompting with action.',3:'The selected lesson studies bold witness through the Holy Ghost.',4:'The selected lesson teaches the Spirit’s help in courageous witness.',5:'The selected lesson studies continued witness despite opposition.',7:'The selected lesson warns against resisting the Holy Ghost.',8:'The selected lesson connects the Spirit’s guidance with helping others understand Jesus.',9:'The selected lesson teaches that people can repent and change.',10:'The selected lesson teaches God’s acceptance across peoples and gradual revelation.',11:'The selected lesson studies Peter’s explanation as part of gradual revelation.',15:'The selected lesson studies the meeting’s decision through continuing revelation.',16:'The selected lesson teaches spiritual guidance and courage when sharing the gospel.',17:'The selected lesson teaches that people are God’s children.',18:'The selected lesson studies courage during Paul’s extended teaching.',22:'The selected lesson studies testimony through Paul’s recalled encounter.',26:'The selected lesson connects testimony with service to others.',27:'The selected lesson applies the voyage to following the Lord’s servants.'}
summaries[-1]='Malta gives help before Rome’s guarded lodging and continued teaching.'
lessonIds={c:['cfm-nt-2023-'+str(num)] for num,cc,_,_ in lessons for c in cc}
chapters=[]
for n,v,title,meaning in notes:
 loc=locs.get(n,[])
 chapters.append(dict(chapter=n,title=title,summary=summaries[n-1],meaning=meaning,people=[pid for pid,cc in profileChapters.items() if n in cc],places=loc,sourceIds=['web']+(['barreto-acts'] if n==10 else []),lds=dict(text=teach.get(n,'')+(' ' if n in teach else '')+'Study question. '+questions[n-1],sourceIds=lessonIds.get(n,[])),eventOrder=n,dateLabel='Book order',historicalNote=meaning,mapNote='Selected cities include present settings, remembered events, promised destinations, and origins. The two Antiochs remain separate. No complete journey or exact meeting site is assigned.',route=[],routeEvidence='Reference markers do not reconstruct ancient routes or verify the account.'))
data=dict(id='acts',bibleCode='ACT',name='Acts',description='Witness · shared care · disputed belonging · travel · hearings',chapterCount=28,scripture=t,chapters=chapters,people=people,places=places,sources=sources,review=dict(date=DATE,contextReviewDate=DATE,copyReviewDate=DATE,scope='All 1,007 numbered positions read for 28 original contextual explanations and exact selections. Fourteen selected profiles and thirteen city references do not claim exhaustive coverage. Five Church lesson bodies retain actual chapter teaching. Barreto’s reading remains attributed. Publisher notes at three empty positions remain separate. Original manuscripts, authorship, speech transcripts, historical law, precise dates, routes, and ancient coastlines were not independently verified.',nextBook='romans'))
if '--ready' in sys.argv:finish(data)
else:(ROOT/'review/acts-draft.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
