"""Ezra: complete reading text, selected identities, and reviewed source scopes."""
import json
from book_common import OUT,source,person,scripture,finish
rows=[
('Cyrus permits return','Cyrus announces temple rebuilding. Families prepare to return, and Sheshbazzar receives the temple vessels.','Restoration depends on people, material support, and imperial permission. Sheshbazzar is not automatically identified with Zerubbabel.','cyrus,jeremiah,nebuchadnezzar,sheshbazzar,mithredath-treasurer','jerusalem,babylon'),
('The returning community','A register names returning families and temple workers. Some priestly families cannot establish their descent.','The list records claims to belonging and service. Shared names do not identify every ancestor with a famous later person.','zerubbabel,jeshua-priest,nebuchadnezzar,returning-families','jerusalem,babylon'),
('Altar, foundations, joy, and grief','Jeshua and Zerubbabel lead renewed offerings and temple work. The foundation ceremony brings both celebration and grief.','Communal rebuilding can contain different memories and emotions. The Levite Jeshua in verse 9 remains distinct from the priest.','jeshua-priest,zerubbabel,moses,david,asaph-singer,cyrus','jerusalem,sidon,tyre,lebanon,joppa'),
('Opposition and royal letters','An offer of help is rejected. Opposition and letters to Persian rulers interrupt rebuilding before work resumes under Darius.','The chapter groups opposition across different reigns. Its letter sequence does not provide a simple continuous chronology.','zerubbabel,jeshua-priest,cyrus,darius-ezra,ahasuerus-ezra,artaxerxes-ezra,mithredath-writer,rehum-chancellor,shimshai','jerusalem,samaria'),
('Prophets and an official inquiry','Haggai and Zechariah encourage rebuilding. Tattenai requests a search for Cyrus’s decree, and the leaders explain their account.','Local testimony and imperial records shape the dispute. Sheshbazzar’s earlier foundation work is recalled without resolving every identity question.','haggai,zechariah-prophet,zerubbabel,jeshua-priest,tattenai,shethar-bozenai,sheshbazzar,cyrus,nebuchadnezzar,darius-ezra','jerusalem,babylon'),
('The decree, dedication, and Passover','The archive search supports rebuilding. Darius supplies protection and resources. The community dedicates the temple and celebrates Passover.','The account records welcome for people joining worship. Its royal punishment order is an ancient decree, not a present instruction.','darius-ezra,cyrus,artaxerxes-ezra,haggai,zechariah-prophet','jerusalem,babylon'),
('Ezra and the royal commission','Ezra is introduced through priestly descent and Torah study. Artaxerxes authorizes his journey, supplies, and administrative responsibilities.','Study, practice, and teaching are joined. Ezra departs from Babylon in the text; the guide does not substitute a different starting city.','ezra,aaron,moses,artaxerxes-ezra','babylon,jerusalem'),
('Preparing and accounting for the journey','Ezra gathers travelers and recruits temple workers through Iddo. Prayer precedes the journey, and the treasures are counted at arrival.','Responsibility includes preparation and accounting. Ahava and Casiphia have uncertain locations, so no invented route joins their markers.','ezra,artaxerxes-ezra,iddo-casiphia,sherebiah,hashabiah,meremoth,eleazar-phinehas,jozabad-ezra,noadiah-ezra,david','babylon,jerusalem'),
('Ezra’s prayer over community boundaries','Leaders report marriages across community boundaries. Ezra mourns and offers a prayer about guilt, mercy, and the surviving community.','The prayer expresses Ezra’s interpretation. Scholarly and Church readings differ about these boundaries and the spouses’ presumed religious practices.','ezra,foreign-wives-children','jerusalem'),
('The marriage investigation','Shecaniah proposes separation from foreign wives and children. Ezra summons an assembly, and an investigation names households involved.','The account gives little information about the affected women and children. Their individual beliefs, choices, and later lives remain unstated.','ezra,shecaniah-jehiel,jehohanan-eliashib,jeshua-priest,foreign-wives-children,marriage-objectors,shabbethai','jerusalem')]
prior={};places_prior={}
for slug in ['genesis','exodus','numbers','1-samuel','2-samuel','1-kings','2-kings','1-chronicles','2-chronicles']:
 b=json.loads((OUT/f'{slug}.json').read_text(encoding='utf8'))
 prior.update({p['id']:p for p in b['people']});places_prior.update({p['id']:p for p in b['places']})
new=[
('sheshbazzar','Sheshbazzar','Leader entrusted with temple vessels','Called prince of Judah and later governor.','1:8–11; 5:14–16','The narrative credits him with an early foundation. His identity with Zerubbabel remains uncertain.'),
('mithredath-treasurer','Mithredath, Cyrus’s treasurer','Official counting the temple vessels','Works under Cyrus when the vessels are delivered to Sheshbazzar.','1:8','He is not automatically the letter writer with the same name in chapter 4.'),
('jeshua-priest','Jeshua, son of Jozadak','Priestly leader in the returning community','Works with Zerubbabel. His descendants appear in the marriage investigation.','2:2; 3:2,8; 4:3; 5:2; 10:18','He is distinct from Jeshua ancestors and Levites in service lists.'),
('returning-families','The returning families and temple workers','Community recorded in the return register','The register includes families, priests, Levites, singers, gatekeepers, and other temple workers.','2','The selected group profile does not establish individual identities for every register name.'),
('darius-ezra','Darius, the Persian king','Ruler during temple rebuilding and dedication','Receives the provincial inquiry and authorizes continued work.','4:24; 5; 6','The text connects his reign with restored work. The guide does not invent an exact event-year map.'),
('ahasuerus-ezra','Ahasuerus, the ruler named in opposition','Persian ruler recalled in an accusation notice','Named in a short notice before Artaxerxes’s correspondence.','4:6','The notice is brief. It does not narrate Esther’s complete royal setting.'),
('artaxerxes-ezra','Artaxerxes, the Persian king','Ruler in correspondence and Ezra’s commission','Named in the rebuilding letters and Ezra’s travel authorization.','4; 6:14; 7; 8:1','Chronology and regnal identification require comparison. The chapter sequence is not a dated itinerary.'),
('mithredath-writer','Mithredath, the letter writer','Participant in correspondence against Jerusalem','Named with Bishlam and Tabeel in the Artaxerxes notice.','4:7','Shared spelling does not establish identity with Cyrus’s treasurer.'),
('rehum-chancellor','Rehum, the chancellor','Official opposing Jerusalem’s rebuilding','Writes with Shimshai and other associates.','4:8–23','He is distinct from the Rehum named among returning leaders in 2:2.'),
('shimshai','Shimshai, the scribe','Official composing opposition correspondence','Associated with Rehum in the letter and response.','4:8–23','The account emphasizes written accusations and royal enforcement, not a complete personal biography.'),
('haggai','Haggai','Prophet encouraging temple rebuilding','Works alongside Zechariah during Zerubbabel and Jeshua’s leadership.','5:1; 6:14','Ezra names his encouragement. His separate prophetic book supplies additional material.'),
('zechariah-prophet','Zechariah, the prophet associated with Iddo','Prophet encouraging temple rebuilding','Called son of Iddo in Ezra.','5:1; 6:14','He is distinct from service-list Zechariahs and the earlier prophet killed under Joash.'),
('tattenai','Tattenai','Provincial governor investigating temple work','Governor beyond the River, acting with Shethar Bozenai.','5; 6','He reports the builders’ explanation and seeks documentary confirmation.'),
('shethar-bozenai','Shethar Bozenai','Official participating in the provincial inquiry','Associated with Tattenai and their companions.','5; 6','The narrative records official inquiry and later compliance with Darius’s order.'),
('ezra','Ezra','Priestly scribe studying and teaching Torah','Introduced through a priestly genealogy and supported by Artaxerxes’s commission.','7–10','His leadership joins scripture, administration, prayer, and contested marriage boundaries.'),
('iddo-casiphia','Iddo, the leader at Casiphia','Leader asked to supply temple workers','Ezra sends a delegation to him at Casiphia.','8:17','He is not automatically Zechariah’s ancestor Iddo. Casiphia’s exact location remains uncertain.'),
('sherebiah','Sherebiah','Levite recruited for temple service','Named with his sons and brothers in the traveling community.','8:18,24','Service and treasure stewardship belong together. Verse 24’s priestly wording requires careful comparison.'),
('hashabiah','Hashabiah, the recruited Levite','Temple worker and treasure steward','Named with Jeshaiah and the descendants of Merari.','8:19,24','His name does not identify him with earlier Chronicles officers.'),
('meremoth','Meremoth, son of Uriah','Priest receiving the weighed temple treasures','Works with Eleazar and two Levites at arrival.','8:33','The count records accountability. The brief notice does not provide a full life history.'),
('eleazar-phinehas','Eleazar, son of Phinehas','Temple worker receiving the treasures','Works with Meremoth at the arrival accounting.','8:33','He is not Aaron’s earlier son Eleazar merely because their names match.'),
('jozabad-ezra','Jozabad, son of Jeshua','Levite receiving the weighed treasures','Works with Noadiah, Meremoth, and Eleazar.','8:33','The guide does not automatically merge him with Jozabad in the chapter 10 register.'),
('noadiah-ezra','Noadiah, son of Binnui','Levite receiving the weighed treasures','Named with Jozabad in the arrival accounting.','8:33','He is distinct from the prophetess Noadiah named in Nehemiah.'),
('shecaniah-jehiel','Shecaniah, son of Jehiel','Speaker proposing separation from foreign spouses','Of the descendants of Elam.','10:2–4','His proposal addresses a community boundary. The wives’ own voices and future circumstances are not reported.'),
('jehohanan-eliashib','Jehohanan, son of Eliashib','Person associated with Ezra’s fasting room','Ezra enters his chamber after the proposal.','10:6','This notice does not identify him with every later Jehohanan or Eliashib.'),
('foreign-wives-children','The foreign wives and their children','Households affected by the separation proposal','The account discusses them but does not supply individual portraits or complete personal histories.','9–10','Their beliefs and later lives remain unstated. Interpretive artwork cannot supply missing testimony.'),
('marriage-objectors','Jonathan and Jahzeiah','Named participants opposing the proposal in this translation','Jonathan son of Asahel and Jahzeiah son of Tikvah appear in 10:15.','10:15','Translations differ in this difficult notice. Meshullam and Shabbethai are named as helpers, with the reference requiring care.'),
('shabbethai','Shabbethai, the Levite','Participant named in the contested investigation notice','Named with Meshullam in relation to Jonathan and Jahzeiah.','10:15','The verse’s wording and the direction of support require comparison across translations.')]
defs={i:person(i,n,r,rel,'Ezra '+refs,m) for i,n,r,rel,refs,m in new}
ids=list(dict.fromkeys(pid for row in rows for pid in row[3].split(',')))
people=[dict(defs[pid] if pid in defs else prior[pid]) for pid in ids]
# Locations stated or directly established by these scenes. Leave uncertain sites unmarked.
locations={'ezra':['babylon','jerusalem'],'sheshbazzar':['babylon','jerusalem'],
 'zerubbabel':['jerusalem'],'jeshua-priest':['jerusalem'],'haggai':['jerusalem'],
 'zechariah-prophet':['jerusalem'],'tattenai':['jerusalem'],'shethar-bozenai':['jerusalem'],
 'rehum-chancellor':['samaria'],'shimshai':['samaria'],'meremoth':['jerusalem'],
 'eleazar-phinehas':['jerusalem'],'jozabad-ezra':['jerusalem'],'noadiah-ezra':['jerusalem'],
 'shecaniah-jehiel':['jerusalem'],'jehohanan-eliashib':['jerusalem'],
 'marriage-objectors':['jerusalem'],'shabbethai':['jerusalem']}
aliases={'mithredath-treasurer':['Mithredath'],'mithredath-writer':['Mithredath'],'jeshua-priest':['Jeshua'],'darius-ezra':['Darius'],'ahasuerus-ezra':['Ahasuerus'],'artaxerxes-ezra':['Artaxerxes'],'rehum-chancellor':['Rehum'],'shimshai':['Shimshai'],'zechariah-prophet':['Zechariah'],'iddo-casiphia':['Iddo'],'hashabiah':['Hashabiah'],'eleazar-phinehas':['Eleazar'],'jozabad-ezra':['Jozabad'],'noadiah-ezra':['Noadiah'],'shecaniah-jehiel':['Shecaniah'],'jehohanan-eliashib':['Jehohanan'],'asaph-singer':['Asaph']}
scopes={'jehohanan-eliashib':{10:[6]},'shecaniah-jehiel':{10:[2]},'jeshua-priest':{2:[2],3:[2,8],10:[18]},'rehum-chancellor':{4:[8,9,17,23]},'zechariah-prophet':{5:[1],6:[14]},'iddo-casiphia':{8:[17]},'hashabiah':{8:[19,24]},'jozabad-ezra':{8:[33]},'sherebiah':{8:[18,24]},'david':{8:[2]},'asaph-singer':{3:[10]},'aaron':{7:[5]}}
aliases.update({'meremoth':['Meremoth'],'sherebiah':['Sherebiah'],'shabbethai':['Shabbethai'],
 'returning-families':['returning families','temple workers'],
 'foreign-wives-children':['foreign wives','foreign women','women from other nations'],
 'marriage-objectors':['Jonathan','Jahzeiah']})
scopes.update({'meremoth':{8:[33]},'shabbethai':{10:[15]},'marriage-objectors':{10:[15]}})
context={'zerubbabel':('Returning leader directing temple rebuilding','Son of Shealtiel in Ezra.','His leadership accompanies Jeshua’s priestly work. Identity with Sheshbazzar remains uncertain.'),'asaph-singer':('Earlier singer remembered through his descendants','The singers in 3:10 are descendants of Asaph.','The ancestral reference does not establish Asaph’s presence at this later ceremony.'),'david':('Earlier king remembered in worship and ancestry','His instructions and royal family are recalled.','References preserve ancestral memory rather than a new appearance in the returning community.'),'cyrus':('Persian ruler authorizing temple rebuilding','The proclamation and returned vessels support the community.','Ezra presents imperial permission within its account of restoration.'),'jeremiah':('Earlier prophet recalled in Cyrus’s proclamation','His message is invoked in the opening verse.','This notice does not retell the full book of Jeremiah.'),'nebuchadnezzar':('Earlier Babylonian ruler remembered for deportation and temple loss','His actions explain the returned community and vessels.','The references recall an earlier crisis rather than making him a contemporary of Ezra.')}
for p in people:
 p['linkNames']=aliases.get(p['id'],[]);p['verseScope']={str(k):v for k,v in scopes.get(p['id'],{}).items()}
 p['sourceIds']=['web'];p['placeIds']=locations.get(p['id'],[]);p['life']='Birth and death years are not securely known.'
 if p['id'] in context:p['role'],p['relations'],p['meaning']=context[p['id']]
 p['passages']='Ezra '+', '.join(str(n) for n,row in enumerate(rows,1) if p['id'] in row[3].split(','))
needed_places=list(dict.fromkeys(pid for row in rows for pid in row[4].split(',')))
places=[dict(places_prior[pid]) for pid in needed_places]
for p in places:
 p.pop('verseScope',None);p['sourceIds']=['web','atlas','atlas-canaan']
sources=[source('web','Ezra · World English Bible','https://ebible.org/engwebp/EZR01.htm','Complete public-domain reading text for ten chapters.','Scripture',limits='Narration does not independently verify every event, identity, appearance, or private belief.')]
previous=json.loads((OUT/'2-chronicles.json').read_text(encoding='utf8'))
sources.extend(dict(s) for s in previous['sources'] if s['id'] in ['terrain','atlas','atlas-canaan'])
def reviewed(i,title,url,summary,author,year,coverage,scope,limits,category='Scholarly study',perspective='historical'):
 s=source(i,title,url,summary,category,perspective,limits);s.update(author=author,year=year,chapterCoverage=coverage,reviewed='2026-10-05: '+scope);sources.append(s)
reviewed('luther-ezra','Summary of Ezra · Luther Seminary','https://enterthebible.org/courses/ezra/lessons/summary-of-ezra/','The overview studies temple rebuilding, communal identity, and the book’s literary structure.','Mark Throntveit · revised Jione Havea',2023,[1,2,4,6,7,9,10],'Complete main Summary, So What, Where, Who, When, What, and How sections reviewed.','Scholarly teaching context. Editing dates, authorship, and interpretation remain debated.')
reviewed('havea-ezra','Bible in the World: Ezra · Luther Seminary','https://enterthebible.org/courses/ezra/lessons/bible-in-the-world-ezra/','Havea considers return migration, people who remained, and exclusion through community boundaries.','Jione Havea','Date not displayed',[2,4,9,10],'Complete main Remigrants, Natives, and Polyculturalism sections reviewed.','A named interpretive reading and modern comparison. It does not recover each ancient person’s beliefs.')
reviewed('eskenazi-excerpt','A Resistant Model of Peoplehood · Yale University Press','https://yalebooks.yale.edu/2023/07/20/ezra-a-new-translation-with-introduction-and-commentary-by-tamara-cohn-eskenazi/','Eskenazi studies community survival, scripture, literary structure, and rebuilding under Persian rule.','Tamara Cohn Eskenazi',2023,[1,2,3,6,7,9,10],'Complete authorized preface and introduction excerpt reviewed. The full commentary was not read.','This publisher excerpt supplies literary context. It does not establish consensus or verify every narrated event.')
s=source('eskenazi-record','Ezra: A New Translation with Introduction and Commentary · publisher record','https://yalebooks.yale.edu/book/9780300149692/ezra/','Yale verifies Eskenazi’s commentary, publication date, and ISBN.','Verified bibliography',limits='Publisher description and publication metadata reviewed. The full 504-page commentary was not read.');s.update(author='Tamara Cohn Eskenazi',year=2023,reviewed='2026-10-05: Publisher description and metadata reviewed.',isbn='9780300149692');sources.append(s)
reviewed('mcclellan-ezra','Ezra–Nehemiah and foreign marriages · McClellan interview','https://www.relationscapes.org/p/mcclellan-transcript/','McClellan interprets the foreign-marriage policy as protecting a post-exilic community boundary.','Dan McClellan · interview with Blair Hodges','Publisher transcript; date not displayed',[9,10],'Relevant publisher transcript passage in the section beginning 01:08:49 reviewed. The complete interview and audio were not reviewed.','The timestamp locates the section, not the exact utterance. This interpretation does not prove the wives’ beliefs or supply Church teaching.','McClellan commentary')
sources[-1]['group']='mcclellan'
wiki=source('wiki-ezra','Book of Ezra · Wikipedia','https://en.wikipedia.org/wiki/Book_of_Ezra','The opening supplies book structure and leads to bibliography.','Encyclopedia background',limits='Opening four paragraphs reviewed. Broad historical claims require comparison with scholarly sources.');wiki.update(author='Wikipedia contributors',year='Reviewed revision',chapterCoverage=[1,4,7,10],reviewed='2026-10-05: Opening four paragraphs of revision 1368563443 reviewed.',revisionId='1368563443',revisionUrl='https://en.wikipedia.org/w/index.php?oldid=1368563443',license='CC BY-SA 4.0',licenseUrl='https://creativecommons.org/licenses/by-sa/4.0/',citedSourceIds=['eskenazi-record']);sources.append(wiki)
base='https://www.churchofjesuschrist.org/study/manual/'
reviewed('cfm-ezra-2026','Come, Follow Me 2026 · Ezra 1; 3–7; Nehemiah selections',base+'come-follow-me-for-home-and-church-old-testament-2026/31?lang=eng','The lesson studies temple rebuilding, help from others, opposition, joy, and God’s guidance.','The Church of Jesus Christ of Latter-day Saints',2026,[1,3,4,5,6,7],'Complete main lesson, home and Church sections, and children’s sections reviewed. Linked supplements were not reviewed.','Faith teaching and application. Its Nehemiah 8 material does not constitute coverage of Ezra 8.','Come, Follow Me','lds')
reviewed('lds-ezra-intro','Introduction to Ezra · Seminary teacher manual',base+'old-testament-seminary-teacher-manual/introduction-to-the-book-of-ezra?lang=eng','The introduction supplies Church teaching context for restoration and Ezra’s two main narrative divisions.','The Church of Jesus Christ of Latter-day Saints',2014,list(range(1,11)),'Complete main introduction reviewed.','General book introduction, not verse-by-verse commentary. Approximate dates and possible Sheshbazzar identification remain uncertain.','LDS study manual','lds')
reviewed('lds-ezra-104','Lesson 104: Ezra 7–10 · Seminary teacher manual',base+'old-testament-seminary-teacher-manual/introduction-to-the-book-of-ezra/lesson-104-ezra-7-10?lang=eng','The lesson connects study, practice, teaching, prayer, and repentance. It interprets the marriages through idolatry concerns.','The Church of Jesus Christ of Latter-day Saints',2014,[7,8,9,10],'Introduction and Suggestions for Teaching reviewed. The complete background tail and linked talks were not reviewed.','LDS interpretation does not independently establish every wife’s beliefs. The route uses Ezra’s Babylon origin rather than the lesson’s Shushan description.','LDS study manual','lds')
reviewed('ezra-kjv-10','Ezra 10:15 · King James translation and footnote','https://www.churchofjesuschrist.org/study/scriptures/ot/ezra/10?lang=eng','The main text describes work on the case. Its footnote gives a likely reading of opposition.','The Church of Jesus Christ of Latter-day Saints · Bible study edition','Edition date not checked',[10],'Verse 15 and its Hebrew translation footnote compared with the World English Bible.','The editions describe the men’s role differently. This comparison does not settle the Hebrew wording.','Translation notes')
historical={1:'Eskenazi reads restoration within Persian rule and communal survival.',2:'Havea asks readers to consider returnees and the people who remained.',3:'Eskenazi treats temple rebuilding as part of reconstructing communal life.',4:'The letter sequence spans different reigns. The overview cautions against a simple continuous chronology.',5:'The narrative gives both the builders’ testimony and the officials’ inquiry.',6:'Imperial support and community worship are joined in the literary account.',7:'Eskenazi emphasizes scripture’s role in shaping a surviving community.',8:'The text names Babylon as the starting point. Ahava and Casiphia remain unlocated in this map.',9:'McClellan and Havea emphasize exclusion and communal boundaries. The Church lesson emphasizes idolatry and repentance.',10:'The interpretations differ. No source reviewed supplies the unnamed wives’ complete beliefs or later histories.'}
lds={1:'Come, Follow Me studies how people outside the community can help God’s work.',3:'Come, Follow Me considers the joy and grief accompanying temple rebuilding.',4:'Come, Follow Me studies responses to opposition.',5:'Come, Follow Me places renewed work within the rebuilding narrative.',6:'Come, Follow Me studies temple dedication and communal joy.',7:'The Church lesson joins scripture study with practice and teaching.',8:'The Seminary lesson studies fasting, prayer, and trust before the journey.',9:'The Seminary lesson reads the marriages through idolatry and repentance. The wives’ individual beliefs remain unstated in Ezra.',10:'The Seminary lesson applies confession and repentance. It does not supply the affected families’ later histories.'}
chapters=[]
for n,(title,summary,meaning,pids,locs) in enumerate(rows,1):
 hs=[s['id'] for s in sources if s['perspective']=='historical' and n in s.get('chapterCoverage',[])];ls=[s['id'] for s in sources if s['perspective']=='lds' and n in s.get('chapterCoverage',[])]
 chapters.append(dict(chapter=n,title=title,summary=summary,meaning=meaning,people=pids.split(','),places=locs.split(','),sourceIds=['web','atlas','atlas-canaan']+hs,lds=dict(text=lds.get(n,'The Seminary introduction places the returning families within the restoration account.'),sourceIds=ls),eventOrder=n,dateLabel='Chapter order · Persian reign sequence requires comparison',historicalNote=historical[n],mapNote='Selected known places and broad regions. Ahava, Casiphia, and the archive destination are not assigned unsupported coordinates.',route=[],routeEvidence='No exact ancient journey route is reconstructed.'))
finish(dict(id='ezra',bibleCode='EZR',name='Ezra',description='Return · temple rebuilding · God’s law · families',chapterCount=10,scripture=scripture('ezra','EZR',10),chapters=chapters,people=people,places=places,sources=sources,review=dict(date='2026-10-05',scope='All scripture and original chapter studies reviewed. Profiles cover selected leaders and groups, not every register name. Source records distinguish actual review from unread full works.',nextBook='nehemiah')))
