"""Build Hosea with complete Scripture and original contextual readings."""
import json,sys
from book_common import ROOT,OUT,scripture,source,person,finish
DATE='2026-10-07'
t=scripture('hosea','HOS',14)
assert [len(t[str(n)]) for n in range(1,15)]==[11,23,5,19,15,11,16,14,17,15,12,14,16,9]
assert not any('\ufffd' in v['text'] for vv in t.values() for v in vv)
notes=json.loads((ROOT/'scripts/book-context-complete/hosea.json').read_text(encoding='utf8'))
sources=[source('web','Hosea · World English Bible','https://ebible.org/engwebp/HOS01.htm','All fourteen chapters appear in the reading text.','Scripture','historical','The guide preserves the WEB wording. Family comparisons do not supply a complete household biography.')]
sources[0].update(author='World English Bible translators',publisher='eBible.org',chapterCoverage=list(range(1,15)),reviewed=dict(date=DATE,scope='All 197 verses read from cached publisher text. Chapter verse counts and character integrity checked.'))
s=source('couey-hosea-11','Commentary on Hosea 11:1-11','https://www.workingpreacher.org/commentaries/revised-common-lectionary/ordinary-18-3/commentary-on-hosea-111-11-4','Couey examines parental care, animal comparisons, and the choice of compassion.','Scholarly study','historical','The commentary offers interpretation. Its translation proposals and modern comparisons are not independent evidence of events.')
s.update(author='J. Blake Couey',year=2019,publisher='Luther Seminary',chapterCoverage=[11],reviewed=dict(date=DATE,scope='Complete commentary body read. Linked commentaries and podcasts were not reviewed.'));sources.append(s)
s=source('cfm-hosea-2026','November 16–22: “I Will Love Them Freely” · Hosea and Joel','https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-old-testament-2026/47?lang=eng','The lesson applies restored belonging and sincere devotion to covenant life.','LDS Come, Follow Me','lds','Applied Hosea notes cover chapters 1–3, 6, and 14. Its later Christian applications remain in the LDS perspective.')
s.update(author='The Church of Jesus Christ of Latter-day Saints',year=2026,publisher='The Church of Jesus Christ of Latter-day Saints',chapterCoverage=[1,2,3,6,14],reviewed=dict(date=DATE,scope='Introduction and adult study sections read, including Joel. Linked talks, videos, and Bible Dictionary entries were not separately reviewed.'));sources.append(s)
people=[]
for row in [
 ('hosea','Hosea','Prophet whose household introduces Israel’s broken relationship with God','He is Beeri’s son and Gomer’s husband.','Hosea 1–14','His speeches connect worship with conduct, failed rule, and the invitation to return.'),
 ('gomer','Gomer','Woman named as Hosea’s wife','She is Diblaim’s daughter. The opening names three children in the household.','Hosea 1:3–9','The account gives no direct speech or detailed explanation of her choices.')]:
 p=person(*row);p.update(placeIds=[],linkNames=[]);people.append(p)
old=json.loads((OUT/'jeremiah.json').read_text(encoding='utf8'))
places=[]
for i,s in [('samaria','Samaria appears in accusations and warnings about failed royal and religious protection.'),('egypt','Egypt appears in memories of rescue, foreign appeals, and warnings about displacement.')]:
 p=dict(next(p for p in old['places'] if p['id']==i));p.update(summary=s,sourceIds=['web'],limits='Approximate city or broad region marker. It does not trace a journey or establish a precise battle site.');places.append(p)
summaries=['Children’s names announce judgment. A closing promise reverses rejection.','Threats against daily supplies give way to justice, compassion, and restored belonging.','A household waiting period explains Israel’s loss of rule and worship.','Priests and people face charges about violence, rejected knowledge, and unequal blame.','Priests and rulers face judgment. Assyria cannot heal Ephraim’s wound.','Confident promises meet a charge of disappearing love and continued violence.','Court plots and foreign appeals expose dangers the people fail to recognize.','Manufactured idols, chosen rulers, and fortresses cannot secure Israel’s future.','Celebration gives way to warnings of displacement, failed worship, and terrible loss.','Prosperity produces more altars. Sowing righteousness offers a different response.','Remembered parental care interrupts the threat of destruction with compassion.','Memories of Jacob challenge dishonest wealth and confidence in alliances.','Forgotten wilderness care gives way to warnings that rulers cannot prevent.','Israel must reject false help. God promises freely given love and restored growth.']
questions=['How does the closing promise reverse the children’s names?','What words define the renewed relationship after the threats?','What details remain unknown about the unnamed woman?','Why does the speech refuse to blame daughters alone?','Why can Assyria not cure the wound described here?','How do charges of violence challenge the opening promises?','What dangers do the oven and dove reveal?','Why does naming the craftsman matter for the calf?','How does lost land affect worship as well as food?','What would a different harvest require from the people?','How does the lion’s role change at the end?','How do memories of Jacob challenge dishonest wealth?','Why does remembered care make forgetfulness more serious?','How do the plant pictures reverse earlier losses?']
ldsNotes={1:'The 2026 lesson connects unfaithfulness with a broken covenant relationship.',2:'The lesson studies renewed belonging through God’s love and mercy.',3:'The lesson invites readers to consider God’s continued invitation to return.',6:'The lesson connects mercy with sincere devotion beyond outward religious acts.',14:'The lesson studies freely given love and the blessings of repentance.'}
loc={1:[],2:['egypt'],3:[],4:[],5:[],6:[],7:['samaria','egypt'],8:['samaria','egypt'],9:['egypt'],10:['samaria'],11:['egypt'],12:['egypt'],13:['samaria','egypt'],14:[]}
chapters=[]
for n,v,title,meaning in notes:
 chapters.append(dict(chapter=n,title=title,summary=summaries[n-1],meaning=meaning,people=['hosea']+(['gomer'] if n==1 else []),places=loc[n],sourceIds=['web']+(['couey-hosea-11'] if n==11 else []),lds=dict(text=(ldsNotes.get(n,'')+' Study question. '+questions[n-1]).strip(),sourceIds=['cfm-hosea-2026'] if n in ldsNotes else []),eventOrder=n,dateLabel='Book order',historicalNote=meaning,mapNote='Markers locate selected named references. Warnings and comparisons do not establish traveled routes.' if loc[n] else 'This chapter has no mapped places. Uncertain sites and unnamed settings remain unmapped.',route=[],routeEvidence='No continuous journey is reconstructed from speeches and comparisons.'))
data=dict(id='hosea',bibleCode='HOS',name='Hosea',description='Broken belonging · failed rulers · remembered care · freely given love',chapterCount=14,scripture=t,chapters=chapters,people=people,places=places,sources=sources,review=dict(date=DATE,contextReviewDate=DATE,copyReviewDate=DATE,scope='All WEB chapters read. Fourteen original close readings distinguish Scripture from scoped commentary and Church teaching. Two profiles are selected, not a complete person inventory.',nextBook='joel'))
if '--ready' in sys.argv:finish(data)
else:(ROOT/'review/hosea-draft.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
