"""Build Luke with complete publisher text and scoped close readings."""
import json,copy,sys
from book_common import ROOT,OUT,scripture,source,finish
DATE='2026-10-07'
t=scripture('luke','LUK',24)
assert [len(t[str(n)]) for n in range(1,25)]==[80,52,38,44,39,49,50,56,62,42,54,59,35,35,32,31,37,43,48,47,38,71,56,53]
assert sum(map(len,t.values()))==1151
assert not any('\ufffd' in v['text'] for vv in t.values() for v in vv)
assert t['17'][35]['publisherNote']=='Some Greek manuscripts add: “Two will be in the field: the one taken, and the other left.”'
base=json.loads((OUT/'matthew.json').read_text(encoding='utf8'))
mark=json.loads((OUT/'mark.json').read_text(encoding='utf8'))
notes=json.loads((ROOT/'scripts/book-context-complete/luke.json').read_text(encoding='utf8'))
sources=[]
s=source('web','Luke · World English Bible','https://ebible.org/engwebp/LUK01.htm','All 24 chapters retain the publisher’s numbered verse positions.','Scripture','historical','Close reading does not independently verify every event or date. Luke 17:36 has a publisher note instead of verse text.')
s.update(author='World English Bible translators',publisher='eBible.org',chapterCoverage=list(range(1,25)),reviewed=dict(date=DATE,scope='All 1,151 numbered verse positions read. Luke 17:36 is empty in this edition and retains its separately labeled manuscript note. Every selected verse and surrounding chapter were read. Verse counts and character integrity checked.'));sources.append(s)
s=source('malcolm-luke','Commentary on Luke 16:19-31','https://www.workingpreacher.org/commentaries/revised-common-lectionary/ordinary-26-3/commentary-on-luke-1619-31-5','Malcolm connects the reversal after death with neglected poverty during life.','Scholarly study','historical','This is Malcolm’s reading. The guide does not turn the story into a mapped afterlife or independently verify social generalizations.')
s.update(author='Lois Malcolm',publisher='Luther Seminary',year=2013,chapterCoverage=[16],reviewed=dict(date=DATE,scope='Complete commentary body read. Linked works, related commentaries, and podcast were not reviewed. The source’s other chapter comparisons do not receive automatic coverage.'));sources.append(s)
lessons=[(2,[1],'January 2–8 · Matthew 1; Luke 1','The lesson studies Mary, Elizabeth, and Zacharias through faithful responses and waiting.'),(5,[3],'January 23–29 · Matthew 3; Mark 1; Luke 3','The lesson uses John’s concrete instructions to explain changed conduct as evidence of repentance.'),(17,[10],'April 17–23 · Matthew 18; Luke 10','The lesson connects love for neighbors with the Samaritan’s practical care.'),(20,[18],'May 8–14 · Matthew 19–20; Mark 10; Luke 18','The lesson contrasts trust in God’s mercy with self-praise that condemns others.'),(27,[24],'June 26–July 2 · Matthew 28; Mark 16; Luke 24; John 20–21','The lesson teaches resurrection through the Gospel accounts.')]
for number,coverage,title,summary in lessons:
 s=source('cfm-nt-2023-'+str(number),title,f'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-sunday-school-new-testament-2023/{number:02}?lang=eng',summary,'LDS Come, Follow Me','lds','Selected Church teaching only. Lesson headings alone do not establish teaching coverage.')
 s.update(author='The Church of Jesus Christ of Latter-day Saints',publisher='The Church of Jesus Christ of Latter-day Saints',year=2023,chapterCoverage=coverage,reviewed=dict(date=DATE,scope='Complete lesson body and additional resources read. Linked talks, videos, dictionary articles, and other editions were not separately reviewed. Only listed Luke chapters receive teaching coverage.'));sources.append(s)
sources.extend(copy.deepcopy([s for s in mark['sources'] if s['id'] in ['net-nt-map','atlas-canaan']]))
people=copy.deepcopy(base['people'])
details={
 'jesus':('Teacher presented as the Savior and Christ','Mary is his mother. Joseph appears in the childhood accounts and the family list.','Luke 1–24','His welcome, teaching, suffering, and resurrection connect mercy with changed conduct.'),
 'mary-mother':('Mother who receives Gabriel’s message and keeps difficult sayings','Elizabeth is her relative. Joseph travels with her in the childhood account.','Luke 1–2; 8:19–21','Her song connects personal blessing with hungry people filled and powerful people brought down.'),
 'joseph-mary':('Mary’s husband in the childhood account','Luke describes his Davidic descent and names Heli in Jesus’ family list.','Luke 1:27; 2; 3:23; 4:22','His travel places the childhood account between Nazareth, Bethlehem, and Jerusalem.'),
 'john-baptizer':('Son of Elizabeth and Zacharias who prepares people for Jesus','Gabriel announces his birth. Herod later imprisons him.','Luke 1; 3; 5:33; 7:18–35; 9:7–19; 11:1; 16:16; 20:4–6','His instructions demand shared resources and an end to extortion rather than ancestry alone.'),
 'peter':('Fisherman who follows Jesus and later denies him','Andrew is his brother. Luke also mentions his wife’s mother.','Luke 4–6; 8–9; 12:41; 18:28; 22; 24:12','His failures remain beside Jesus’ prayer and the task to strengthen others after returning.'),
 'mary-magdalene':('Supporter and witness who carries the tomb report','Luke distinguishes her from Mary, Martha’s sister, and Mary the mother of James.','Luke 8:2; 24:10','Her named support and testimony connect the traveling group with the resurrection report.')}
profileChapters={'jesus':list(range(1,25)),'mary-mother':[1,2,8],'joseph-mary':[1,2,3,4],'john-baptizer':[1,3,5,7,9,11,16,20],'peter':[4,5,6,8,9,12,18,22,24],'mary-magdalene':[8,24]}
for p in people:
 p['role'],p['relations'],p['passages'],p['meaning']=details[p['id']];p['placeIds']=[];p['verseScope']={}
 if p['id']=='mary-mother':p['verseScope']={'1':[27,30,34,38,39,41,46,56],'2':[5,16,19,34],'8':[]}
 if p['id']=='joseph-mary':p['verseScope']={'1':[27],'2':[4,16,33,43],'3':[23],'4':[22]}
 if p['id']=='john-baptizer':
  p['linkNames']=['John the Baptizer','John'];p['verseScope']={str(n):[v['verse'] for v in t[str(n)] if 'John' in v['text']] for n in profileChapters['john-baptizer']};p['verseScope']['5']=[33];p['verseScope']['9']=[7,9,19]
 if p['id']=='peter':p['verseScope']={str(n):[v['verse'] for v in t[str(n)] if 'Peter' in v['text']] for n in profileChapters['peter']}
 if p['id']=='mary-magdalene':p['linkNames']=['Mary Magdalene','Mary'];p['verseScope']={'8':[2],'24':[10]}
placeText={'bethlehem':'The childhood account places the birth and shepherds’ visit in Bethlehem.','jerusalem':'Jerusalem holds temple visits, final teaching, execution, and the beginning of the witness task.','jordan':'John teaches and baptizes in the Jordan region. No exact baptism site is assigned.','galilee':'Galilee holds early work and appears in remembered words at the tomb.','nazareth':'Nazareth holds the childhood settlement and the disputed hometown teaching.','capernaum':'Capernaum appears in teaching, healing, and warnings to towns.','tyre':'Tyre appears among the crowd’s origins and in a judgment comparison.','sidon':'Sidon appears in the Elijah comparison, the crowd’s origins, and a town warning.','jericho':'Jericho holds Zacchaeus’ welcome and appears within the Samaritan story.','olives':'The Mount of Olives holds teaching nights, the entry’s descent, and prayer before arrest.','bethany':'Bethany appears beside the entry and the final blessing.','bethsaida':'The feeding setting and a warning name Bethsaida.','sea-galilee':'The lake holds fishing and crossings. Gennesaret is the lake name in the fishing account.'}
places=[]
for p in base['places']+mark['places']:
 if p['id'] in placeText and not any(q['id']==p['id'] for q in places):
  q=copy.deepcopy(p);q.update(summary=placeText[p['id']],verseScope={});places.append(q)
locs={1:['jerusalem','galilee','nazareth'],2:['nazareth','galilee','bethlehem','jerusalem'],3:['jordan','galilee'],4:['jordan','jerusalem','galilee','nazareth','capernaum','sidon'],5:['sea-galilee','galilee','jerusalem'],6:['jerusalem','tyre','sidon'],7:['capernaum'],8:['sea-galilee','galilee'],9:['bethsaida','jerusalem'],10:['bethsaida','tyre','sidon','capernaum','jerusalem','jericho'],13:['jerusalem'],17:['galilee','jerusalem'],18:['jerusalem','jericho','nazareth'],19:['jericho','jerusalem','bethany','olives'],20:['jerusalem'],21:['jerusalem','olives'],22:['jerusalem','olives'],23:['jerusalem','galilee'],24:['jerusalem','galilee','bethany']}
summaries=['Two birth promises lead to visits, naming, and songs about mercy.','Shepherds visit the child. Temple witnesses bless him before a later search.','John calls for changed conduct. Jesus receives baptism before a family list.','Testing leads to hometown rejection, teaching, and healing in Capernaum.','Fishermen follow Jesus. Healing and Levi’s feast lead to disputes.','Sabbath conflict leads to choosing twelve and teaching about enemies and obedience.','An officer trusts Jesus’ word. A widow receives her son, and a woman receives forgiveness.','Women support the group. Hearing stories lead to crossings and restored lives.','Food, confession, and the mountain scene lead toward Jerusalem amid misunderstanding.','Travelers return before a lawyer’s question receives the Samaritan story.','Prayer teaching leads to accusations and warnings about neglected justice.','Warnings about possessions and waiting test the use of entrusted resources.','Disaster reports lead to repentance, patient care, Sabbath release, and grief over Jerusalem.','A meal tests honor and invitations. Cost examples challenge the following crowd.','Lost sheep, a coin, and two sons explain celebration that some refuse.','A manager’s actions and reversed fortunes challenge the use of possessions.','Forgiveness and duty lead to ten healings and warnings about sudden judgment.','Prayer stories, children, a rich ruler, and a blind man test different responses.','Zacchaeus welcomes Jesus before the journey reaches praise, tears, and temple conflict.','Authority, taxes, and resurrection become disputes before a warning about honored scribes.','The widow’s gift leads to warnings about the temple, hardship, and watching.','Passover preparation leads to service teaching, prayer, arrest, and denials.','Pilate orders execution despite innocence claims. Witnesses remain and prepare for burial.','The tomb report meets disbelief before travelers and gathered disciples recognize Jesus.']
questions=['How does Mary’s song connect her own blessing with hungry and powerful people?','Why does Simeon place pain beside the promise of light?','How do John’s different answers address each group’s use of resources or power?','Why do the examples of Elijah and Elisha anger the hometown listeners?','How does the physician comparison explain the company at Levi’s meal?','Why does love for enemies go beyond exchanging equal favors?','What does Simon fail to see before Jesus compares their acts of welcome?','How does the family saying join hearing with doing?','Why does Jesus reject the disciples’ proposed fire?','How does the final neighbor question change the lawyer’s original question?','What connects clean surfaces with neglected justice in the meal dispute?','How does the returning master’s service change expectations about power?','Why does Jesus reject greater guilt as the explanation for the victims’ deaths?','How does inviting people unable to repay challenge the host’s expectations?','Why does the story end with the father’s appeal rather than the older son’s decision?','Why does Abraham point the brothers toward words they already have?','Why does Jesus identify the returning man as a foreigner?','How does the tax collector’s prayer differ from the Pharisee’s comparisons?','How do praise and tears coexist at the approach to Jerusalem?','Whom does Luke name as the immediate targets of the vineyard story?','Why does the warning about false timing claims follow the question about signs?','How does Jesus’ service answer the disciples’ rank dispute?','How do Pilate’s decisions differ from his repeated announcements?','How do remembered words, explained Scripture, and shared food shape recognition?']
ldsTeach={1:'The selected lesson studies faithful responses and waiting through Mary, Elizabeth, and Zacharias.',3:'The selected lesson reads changed conduct as evidence of repentance.',10:'The selected lesson connects neighbor love with the Samaritan’s practical care.',18:'The selected lesson teaches trust in God’s mercy rather than condemning others through self-praise.',24:'The selected lesson teaches resurrection through the Gospel accounts.'}
ldsSources={c:['cfm-nt-2023-'+str(number)] for number,coverage,_,_ in lessons for c in coverage}
chapters=[]
for n,v,title,meaning in notes:
 loc=locs.get(n,[])
 chapters.append(dict(chapter=n,title=title,summary=summaries[n-1],meaning=meaning,people=[pid for pid,cc in profileChapters.items() if n in cc],places=loc,sourceIds=['web']+(['malcolm-luke'] if n==16 else []),lds=dict(text=ldsTeach.get(n,'')+(' ' if n in ldsTeach else '')+'Study question. '+questions[n-1],sourceIds=ldsSources.get(n,[])),eventOrder=n,dateLabel='Book order',historicalNote=meaning,mapNote='Selected markers distinguish events from remembered or story settings. Emmaus, Nain, unnamed houses, and exact routes have no assigned marker.' if loc else 'This chapter has no selected place markers. Unnamed teaching settings receive no invented location.',route=[],routeEvidence='Reference markers do not establish exact roads or merge events from different Gospel accounts.'))
data=dict(id='luke',bibleCode='LUK',name='Luke',description='Mercy · welcome · possessions · service · Jerusalem · resurrection',chapterCount=24,scripture=t,chapters=chapters,people=people,places=places,sources=sources,review=dict(date=DATE,contextReviewDate=DATE,copyReviewDate=DATE,scope='All 1,151 numbered WEB positions read for 24 original explanations and exact selections. The empty Luke 17:36 retains a separate publisher note. Six selected profiles do not form an exhaustive inventory. Five selected Church lessons retain actual coverage. No date reconciliation, authorship verification, exact routes, original manuscripts, or original language alignment is claimed.',nextBook='john'))
if '--ready' in sys.argv:finish(data)
else:(ROOT/'review/luke-draft.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
