"""Numbers chapter studies. Reading text comes from the publisher, not generated prose."""
import json
from book_common import ROOT,OUT,scripture,source,person,place,finish
EX=json.loads((OUT/'exodus.json').read_text(encoding='utf-8'))
rows='''
The first census|God commands a census of men eligible for war. Tribal leaders assist Moses and Aaron. Levites receive separate duties.|The account presents a community organized for travel and service. Its totals are textual claims, not independently verified population counts.|moses,aaron|sinai|Consider how preparation can serve a community without reducing people to their assigned roles.
The camp arranged|The tribes camp around the meeting tent in four groups. Their marching order follows the same arrangement.|The sanctuary stands at the center of the camp. The ordering gives each group a place and a duty.|moses,aaron|sinai|Consider what your daily arrangements show about your priorities.
Levites and firstborn|The chapter names Aaron’s sons and assigns duties to the Levite families. Levites stand in place of Israel’s firstborn.|Priestly work and other Levite service remain distinct. The account connects these duties with the rescue of the firstborn.|moses,aaron,eleazar,ithamar|sinai|The Church manual connects redemption of the firstborn with deliverance. Keep that interpretation distinct from the census figures.
Duties for moving the sanctuary|Moses and Aaron count Levites assigned to service. Kohath, Gershon, and Merari have different transport duties.|Shared service requires clear duties. The sacred objects receive protection during travel.|moses,aaron,eleazar,ithamar|sinai|Consider how careful preparation can help others carry their responsibilities.
Camp, restitution, and jealousy|The laws address exclusion from the camp, restitution for wrongs, and a ritual for a husband’s accusation against his wife.|The ritual belongs to an unequal ancient legal system. Read its words carefully before connecting it with modern medical or legal claims.|moses,aaron|sinai|Consider the difference between accusation and proof. Do not use this ancient ritual as present-day guidance.
Nazirite vows and blessing|The law describes a special vow, including limits on wine, hair cutting, and contact with the dead. Priests receive words of blessing.|The vow marks a period of dedication. The priestly blessing asks for protection, favor, and peace.|moses,aaron|sinai|Consider how a commitment can shape daily conduct. Read the blessing as a prayer for God’s care.
Gifts from the tribal leaders|Tribal leaders bring wagons, oxen, and offerings for the sanctuary. Each leader’s altar gift receives a separate account.|The repeated gifts give each tribe a place in the dedication. The transport gifts support different Levite duties.|moses,aaron,eleazar,ithamar|sinai|Consider how material gifts and practical support can make shared worship possible.
Levites prepared for service|Aaron tends the lamps. The Levites undergo cleansing and appointment before beginning their service.|Preparation concerns the community as well as the workers. The chapter also distinguishes ages for active duty and assistance.|moses,aaron|sinai|Consider how preparation and support can help people serve at different stages of life.
Passover and the guiding cloud|Israel keeps Passover at Sinai. People unable to observe it at the first time receive another date. The cloud directs camp movements.|The instructions address a real problem within the community. The cloud gives a shared signal for travel and rest.|moses,aaron|sinai|Consider how faithful observance can include people whose circumstances require accommodation.
Departure from Sinai|God gives instructions for silver trumpets. Israel leaves Sinai. Moses invites Hobab to help guide the journey.|Signals and local knowledge both support the journey. The account brings the organized camp into movement.|moses,aaron,hobab|sinai|Consider how shared signals and practical experience can help a group act together.
Complaints, elders, and quail|The people complain about food. Moses asks for help. Seventy elders receive the Spirit, including Eldad and Medad in the camp.|Moses accepts help and welcomes others’ prophetic gifts. The desire for meat also leads to judgment in the narrative.|moses,aaron,joshua,eldad,medad|sinai|Come, Follow Me studies gratitude and meekness here. Consider Moses’s response to Eldad and Medad.
Miriam and Aaron challenge Moses|Miriam and Aaron speak against Moses. God defends Moses’s special role. Miriam becomes afflicted, and Moses prays for her.|The account joins disputed authority with concern for a family member. The camp waits while Miriam remains outside it.|moses,aaron,miriam|sinai|The Church lesson studies respect for prophetic service. Read that theme alongside Moses’s prayer for Miriam.
The spies report on Canaan|Moses sends twelve men to inspect Canaan. They return with fruit and reports of strong settlements. Caleb urges action.|The same observations produce different judgments. The account distinguishes what the scouts see from what they conclude.|moses,aaron,joshua,caleb|kadesh,canaan,hebron|The Church lesson studies Caleb’s faith. Consider how fear affects your use of available evidence.
The people refuse to enter|The people want to return to Egypt. Joshua and Caleb urge trust. Moses intercedes, and the generation receives a judgment of wandering.|The story gives consequences to a community decision. A later attack fails after the people reject the warning to remain.|moses,aaron,joshua,caleb|kadesh,canaan|Come, Follow Me connects this account with hope through faith. Consider the duties that accompany trust.
Offerings and reminders|The laws describe offerings after entry into the land. They address unintentional error, deliberate defiance, a Sabbath case, and garment fringes.|The chapter places future worship beside present failures. Visible reminders help connect ordinary life with covenant duties.|moses,aaron|kadesh|Consider what reminders help you keep commitments. Keep the ancient civil punishment distinct from present practice.
Korah, Dathan, and Abiram rebel|Korah and other leaders challenge Moses and Aaron. The account describes severe judgment and a later plague. Aaron makes atonement for the people.|The chapter concerns authority, rivalry, and communal danger. Moses and Aaron also act to protect the congregation.|moses,aaron,korah,dathan,abiram|kadesh|The manual studies priestly authority. Read the entire account, including the leaders’ concern for people facing judgment.
Aaron’s staff buds|Each tribal leader supplies a staff. Aaron’s staff produces buds, flowers, and almonds. It remains as a sign at the sanctuary.|The sign settles the dispute within the narrative. It does not provide external evidence for the event.|moses,aaron|kadesh|Consider how the account links authority with the end of destructive rivalry.
Priestly duties and support|God assigns duties to Aaron, his sons, and the Levites. Offerings and tithes support their service.|The chapter joins sacred work with material provision. It also places duties and limits on those who receive support.|moses,aaron,eleazar,ithamar|kadesh|Consider the responsibilities that accompany community support for religious service.
The red heifer and cleansing|The law describes ashes from a red heifer and water used after contact with the dead. Eleazar has a role in preparing the rite.|Contact with death changes ritual status. Ritual impurity must remain distinct from personal moral guilt.|moses,aaron,eleazar|kadesh|Consider the difference between ritual status and wrongdoing. Avoid treating bereavement as evidence of moral failure.
Miriam dies, water flows, and Aaron dies|Miriam dies at Kadesh. Moses strikes the rock during a dispute over water. Edom refuses passage. Aaron dies after Eleazar receives his garments.|The chapter records loss and leadership transition. Moses and Aaron also receive a judgment about entry into the land.|moses,aaron,miriam,eleazar|kadesh,edom|The Church lesson studies meekness and trust. Read leadership duties alongside grief and the account’s limits on authority.
The bronze serpent and eastern victories|The people suffer snakebites and receive a bronze serpent as a sign for healing. Israel then defeats Sihon and Og.|The narrative combines complaint, healing, journeys, and war. Its victories do not establish a precise army route.|moses,aaron,sihon,og|edom,moab,heshbon,bashan|Come, Follow Me connects the serpent with looking to Christ. Compare Alma 33 and Helaman 8.
Balak sends for Balaam|Balak asks Balaam to curse Israel. During Balaam’s journey, his donkey sees an angel before he does. Balaam must speak the words God gives.|The story questions the seer’s perception. The donkey recognizes the obstruction that Balaam initially misses.|moses,balaam,balak|moab|The Church lesson studies pressure to act against God’s will. Keep later comments about Balaam distinct from this chapter’s sequence.
Balaam blesses Israel|Balak builds altars and seeks a curse. Balaam instead pronounces blessings. They move to another vantage point, but the result remains a blessing.|A king cannot purchase the desired divine answer. The repeated attempts expose the limits of Balak’s control.|balaam,balak|moab|Consider the pressure to give an answer that a powerful person wants to hear.
A star and a scepter|Balaam gives further oracles about Israel and neighboring peoples. Balak dismisses him after the blessings continue.|The poems describe rule and future conflict through images of a star and scepter. Later interpreters read these images in different ways.|balaam,balak|moab|The Church manual connects the star and scepter with Christ. Identify that connection as an LDS interpretation.
Peor and Phinehas|Israel joins worship at Peor. Phinehas kills Zimri and Cozbi during the crisis. The account describes the end of a plague.|The story links worship, communal danger, and priestly zeal. Its violence requires historical context and cannot authorize present violence.|moses,aaron,eleazar,phinehas,zimri,cozbi|moab|Read the manual’s priesthood discussion with care. Keep ancient narrative violence distinct from present religious duties.
The second census|Moses and Eleazar count the next generation. The families receive lists, and inheritance depends on group size. Joshua and Caleb survive from the earlier census.|The census prepares for land allocation. Its numbers remain claims within the text, not an independent population survey.|moses,eleazar,joshua,caleb|moab|Consider how continuity and change affect a community preparing for a new stage.
The daughters’ petition and Joshua’s appointment|Zelophehad’s daughters ask for an inheritance because their father had no sons. God accepts their claim. Moses appoints Joshua before the congregation.|A petition leads to a legal instruction. Leadership also passes through a public appointment rather than a private assumption.|moses,eleazar,joshua,mahlah,noah-daughter,hoglah,milcah-daughter,tirzah|moab|Consider how careful listening can reveal a gap in existing rules. The manual also studies Joshua’s appointment.
Daily, Sabbath, and festival offerings|The laws list offerings for each day, Sabbaths, new moons, Passover, and the feast of first produce.|The calendar gives worship a regular pattern. The chapter specifies what the community must supply.|moses,eleazar|moab|Consider how repeated acts can sustain remembrance and gratitude.
Offerings in the seventh month|The law gives offerings for the trumpet day, the Day of Atonement, and the feast of booths.|A changing pattern of offerings marks the festival days. The text joins sacred time with shared material commitments.|moses,eleazar|moab|Consider how a calendar can help a community remember its duties together.
Vows and household authority|The laws regulate vows. Fathers and husbands can cancel certain vows made by women under the stated conditions.|The rules reflect unequal household authority in the ancient system. A vow also carries a serious expectation of fulfillment.|moses|moab|Consider the responsibility of making promises. Do not transfer the ancient household rules directly into present relationships.
War against Midian|Israel attacks Midian, and Balaam dies. Moses gives severe instructions about captives. The chapter also divides spoils and describes cleansing.|The account includes violence against children and women. Its stated religious setting does not remove the need to examine that harm.|moses,eleazar,phinehas,balaam|moab|Read the entire chapter, including its violence. Keep this ancient war account distinct from present Church conduct.
Eastern tribes make a promise|Reuben and Gad request land east of the Jordan. Moses requires their fighting men to assist the other tribes. Families can remain in the eastern settlements.|The agreement joins a local request with shared responsibility. Land preference does not cancel the duty to support other tribes.|moses,eleazar,joshua|moab,gilead,heshbon|Consider how a personal or group benefit can carry obligations to the wider community.
The journey remembered|The chapter lists camps from Egypt to the plains of Moab. It then gives instructions for entry into Canaan.|The list preserves a narrative itinerary. Many camp identifications remain uncertain, so the map cannot show every stop as a verified point.|moses,aaron|egypt,sinai,kadesh,moab|Consider how a community records its journey. Distinguish named camps from places whose locations are secure.
Borders and appointed leaders|God describes the land’s boundaries and names leaders to divide it. Eleazar and Joshua receive leading roles.|The boundaries concern an anticipated allocation. A description in the text is not proof that the community controlled every named border.|moses,eleazar,joshua,caleb|canaan,moab|Consider how clear duties can support a shared allocation. Keep expected borders distinct from verified historical control.
Levite towns and cities of refuge|The law provides towns for Levites and refuge for people accused of killing. It distinguishes accidental death from intentional murder.|The instructions require judgment about motive, witnesses, and circumstances. Refuge limits immediate retaliation while a case receives review.|moses,eleazar|moab,canaan|Consider how fair judgment requires more than an accusation. Read the ancient procedures within their legal setting.
Inheritance and marriage|Leaders from Manasseh question the effects of the daughters’ inheritance. The daughters marry within their father’s tribe under the new instruction.|The final chapter preserves the daughters’ inheritance while limiting its transfer between tribes. The protection comes with a restriction on marriage.|moses,mahlah,noah-daughter,hoglah,milcah-daughter,tirzah|moab|Consider both the protection and the limits in this legal decision. Keep its tribal setting distinct from present marriage choices.
'''.strip().splitlines()
assert len(rows)==36
sources=[source('web','Numbers — World English Bible','https://ebible.org/engwebp/NUM01.htm','The public-domain reading text supplies all 36 chapters.','Scripture',limits='The text narrates events and gives census totals. It does not independently verify those events or totals.')]
sources.extend(dict(s) for s in EX['sources'] if s['id'] in ['terrain','atlas-exodus','atlas-canaan','atlas'])
for sid,title,slug,summary in [
 ('lds-wilderness-1','Numbers 1–12: Wilderness Wanderings, Part 1','numbers-1-12-wilderness-wanderings-part-1','The manual studies camp order, Levite service, and the early wilderness accounts.'),
 ('lds-wilderness-2','Numbers 13–36: Wilderness Wanderings, Part 2','numbers-13-36-wilderness-wanderings-part-2','The manual studies the scouts, leadership disputes, Balaam, priestly duties, and inheritance.')]:
 s=source(sid,title,'https://www.churchofjesuschrist.org/study/manual/old-testament-student-manual-genesis-2-samuel/'+slug+'?lang=eng',summary,'LDS study manual','lds',limits='This is older Institute commentary, published in 1980. Some explanations are proposals, not official Church positions or independent historical evidence.')
 s.update(author='The Church of Jesus Christ of Latter-day Saints',year=1980,reviewed='2026-10-05: Relevant manual sections and edition information reviewed.');sources.append(s)
sources.append(source('alma-33','Alma 33:18–22','https://www.churchofjesuschrist.org/study/scriptures/bofm/alma/33?lang=eng&id=p18-p22#p18','Alma reads the bronze serpent as a sign connected with faith in the Son of God.','LDS scripture','lds',limits='This Restoration scripture supplies a later interpretation, distinct from Numbers’s own words.'))
sources.append(source('helaman-8','Helaman 8:13–15','https://www.churchofjesuschrist.org/study/scriptures/bofm/hel/8?lang=eng&id=p13-p15#p13','Nephi connects Moses’s raised serpent with the Son of God.','LDS scripture','lds',limits='This is a later scriptural interpretation. It does not establish an archaeological identification.'))
for n,summary in [(8,'Hayes studies complaint, intercession, and leadership in Numbers 11 and 14.'),(9,'Hayes studies priestly service, holiness, and the difference between ritual and moral impurity.'),(10,'Hayes compares biblical laws with their ancient legal setting.')]:
 s=source(f'yale-{n}',{8:'Exodus: From Egypt to Sinai',9:'The Priestly Legacy',10:'Biblical Law'}[n]+' — Open Yale Courses',f'https://oyc.yale.edu/religious-studies/rlst-145/lecture-{n}',summary,limits='These are university lecture interpretations. Relevant context does not verify every event or every law in Numbers.')
 s.update(author='Christine Hayes',year='Fall 2006 course',reviewed='2026-10-05: Relevant lecture transcript sections and published course scope reviewed.');sources.append(s)
places=[dict(p) for p in EX['places'] if p['id'] in ['sinai','egypt']]
places.extend([
 place('kadesh','Kadesh-barnea · proposed region',30.65,34.43,'The narrative uses Kadesh as a base near Canaan.','The marker indicates the traditional Ain el-Qudeirat region. It does not verify a wilderness camp.',['web','atlas-exodus']),
 place('canaan','Canaan · broad region',31.7,35.1,'The scouts inspect the land that Israel expects to enter.','This marker represents a broad region, not a precise border or campsite.',['web','atlas-canaan']),
 place('hebron','Hebron',31.53,35.10,'The scouts reach Hebron in Numbers 13.','The modern city indicates the general locality. The marker does not verify the scouts’ visit.',['web','atlas-canaan']),
 place('edom','Edom · broad region',30.75,35.5,'Edom refuses Israel permission to pass through its territory.','The marker represents a region. It does not identify a king’s residence or exact border.',['web','atlas-exodus']),
 place('moab','Plains of Moab · approximate region',31.85,35.65,'Israel camps east of the Jordan opposite Jericho.','This is a regional display point. The camp and Balaam’s vantage points are not securely located.',['web','atlas-exodus']),
 place('heshbon','Heshbon · proposed locality',31.80,35.81,'The text associates Heshbon with Sihon’s rule.','Tall Hisban is a traditional identification. Its remains do not independently establish Sihon’s reign.',['web','atlas-exodus']),
 place('bashan','Bashan · broad region',32.65,36.10,'The account describes conflict with Og in Bashan.','The marker indicates a broad region, not a verified battle site or capital.',['web','atlas']),
 place('gilead','Gilead · broad region',32.10,35.80,'Eastern tribes request settlements in this region.','The point represents a region. It does not establish ancient settlement boundaries.',['web','atlas'])])
people=[dict(p) for p in EX['people'] if p['id'] in ['moses','aaron','miriam','joshua','eleazar','ithamar']]
details={
 'moses':('Numbers 1–36','He organizes the camp, conveys laws, intercedes, and appoints Joshua. The narrative also places limits on his entry into Canaan.'),
 'aaron':('Numbers 1–20; 33','He serves as priest and helps lead the community. Eleazar receives his garments before his death in Numbers 20.'),
 'miriam':('Numbers 12; 20:1','She challenges Moses with Aaron. Moses prays for her recovery. The book later records her death at Kadesh.'),
 'joshua':('Numbers 11:28; 13–14; 26–27; 32; 34','He supports entry into Canaan with Caleb. Moses later appoints him to lead the community.'),
 'eleazar':('Numbers 3–4; 19–20; 26–27; 31–34','He prepares the red-heifer rite, succeeds Aaron, and assists with the new census and land allocation.'),
 'ithamar':('Numbers 3–4','He supervises transport duties assigned to the Gershonite and Merarite families.')}
for p in people:p['passages'],p['meaning']=details[p['id']];p.pop('placeIds',None)
for args in [
 ('caleb','Caleb','Scout who urges trust','Son of Jephunneh. He serves alongside Joshua.','Numbers 13–14; 26:65; 32; 34:19','He draws a different conclusion from the other scouts. The account preserves his role across the generations.'),
 ('hobab','Hobab','Invited wilderness guide','Son of Reuel, the Midianite. His exact relationship to Moses depends on how the kinship term is read.','Numbers 10:29–32','Moses values his knowledge of camping places. The passage records the invitation but does not explicitly give his final response.'),
 ('eldad','Eldad','Elder who prophesies in the camp','Named with Medad among the registered elders.','Numbers 11:26–30','His prophetic activity outside the meeting tent prompts Joshua’s objection and Moses’s generous response.'),
 ('medad','Medad','Elder who prophesies in the camp','Named with Eldad among the registered elders.','Numbers 11:26–30','His experience shows that the narrative does not confine the Spirit’s activity to one gathering place.'),
 ('korah','Korah','Levite who challenges Moses and Aaron','Son of Izhar, from the Kohathite family.','Numbers 16; 26:9–11','His challenge concerns holiness and authority. Numbers 26 states that his sons did not die.'),
 ('dathan','Dathan','Reubenite leader in the rebellion','Son of Eliab. Brother of Abiram.','Numbers 16; 26:9–10','He rejects Moses’s summons and disputes his leadership. The narrative describes judgment on the rebels’ households.'),
 ('abiram','Abiram','Reubenite leader in the rebellion','Son of Eliab. Brother of Dathan.','Numbers 16; 26:9–10','He joins Dathan’s refusal to meet Moses. Their account concerns a challenge to political leadership as well as priestly dispute.'),
 ('balaam','Balaam','Seer asked to curse Israel','Son of Beor. Balak seeks his services.','Numbers 22–24; 31:8,16','He blesses Israel despite Balak’s requests. Numbers 31 later connects him with the Peor crisis and records his death.'),
 ('balak','Balak','King of Moab','Son of Zippor. He sends for Balaam.','Numbers 22–24','He tries gifts, altars, and different vantage points to obtain a curse. The account repeatedly frustrates his plans.'),
 ('phinehas','Phinehas','Priest in the Peor and Midian accounts','Son of Eleazar. Grandson of Aaron.','Numbers 25; 31:6','His violent action ends a crisis in the narrative. The account requires historical context and cannot authorize present violence.'),
 ('zimri','Zimri','Simeonite leader killed at Peor','Son of Salu. The narrative places him with Cozbi.','Numbers 25:6–15','The text names him after describing his death. His tribal status adds a leadership dimension to the crisis.'),
 ('cozbi','Cozbi','Midianite woman killed at Peor','Daughter of Zur, a Midianite leader.','Numbers 25:6–18','The narrative gives her name and family but no direct speech. Do not invent her motives or consent.'),
 ('sihon','Sihon','Amorite king associated with Heshbon','Ruler who refuses passage and fights Israel.','Numbers 21:21–30; 32','His defeat gives the account a basis for eastern settlement. His dates and historical identity remain uncertain.'),
 ('og','Og','King of Bashan','Ruler opposed by Israel in the northern region.','Numbers 21:33–35; 32','His defeat extends the narrative’s eastern victories. A regional marker does not identify the battle site.')]:people.append(person(*args))
for pid,name in [('mahlah','Mahlah'),('noah-daughter','Noah'),('hoglah','Hoglah'),('milcah-daughter','Milcah'),('tirzah','Tirzah')]:
 people.append(person(pid,name,'Daughter who petitions for an inheritance','Daughter of Zelophehad, from Manasseh. She acts with her four sisters.','Numbers 26:33; 27:1–11; 36','The sisters’ shared petition prompts a law about inheritance. Chapter 36 preserves their inheritance under a tribal marriage restriction.'))
chapters=[]
for n,row in enumerate(rows,1):
 title,summary,meaning,pids,placesIds,lds=row.split('|')
 if n in [21,25]:pids=','.join(pid for pid in pids.split(',') if pid!='aaron')
 refs=['web']
 if n in [11,13,14,16,20]:refs.append('yale-8')
 if n in [3,4,5,6,7,8,9,15,17,18,19,25,28,29,31]:refs.append('yale-9')
 if n in [5,15,27,30,32,34,35,36]:refs.append('yale-10')
 locs=[] if n in [11,12,15,16,17,18,19] else placesIds.split(',')
 refs.extend(list(dict.fromkeys(sid for p in places if p['id'] in locs for sid in p['sourceIds'] if sid!='web')))
 chapters.append(dict(chapter=n,title=title,summary=summary,meaning=meaning,people=pids.split(','),places=locs,sourceIds=refs,lds=dict(text=lds,sourceIds=['lds-wilderness-1' if n<=12 else 'lds-wilderness-2']+(['alma-33','helaman-8'] if n==21 else [])),eventOrder=n,dateLabel='Chapter order · historical year uncertain',mapNote='Markers show regions or traditional identifications. Many campsites, the sea crossing, and Mount Hor lack secure locations.',historicalNote='Read narrative claims separately from independently established dates and places.',route=['egypt','sinai','kadesh','moab'] if n==33 else [],routeEvidence='Numbers 33 names this broad sequence. The line omits uncertain camps and does not show an excavated travel path.'))
# Do not treat a chapter's general setting as a verified personal itinerary.
for p in people:
 p['placeIds']=[]
 p['life']='Birth and death years are not securely known.'
finish(dict(id='numbers',bibleCode='NUM',name='Numbers',description='Wilderness · leadership · covenant · inheritance',chapterCount=36,scripture=scripture('numbers','NUM',36),chapters=chapters,people=people,places=places,sources=sources,review=dict(date='2026-10-05',scope='Chapter accounts and laws. Census totals, campsites, and event dates require separate historical evidence.',nextBook='deuteronomy')))
