"""First Kings: reviewed chapters, separate names, and the shared Isaiah reader."""
import json
from book_common import OUT,source,person,place,scripture,finish
rows=[
('Solomon is anointed during a succession dispute','Adonijah gathers supporters at En Rogel. Bathsheba and Nathan approach David, who orders Solomon’s anointing at Gihon.','Succession depends on public recognition and access to the aging king. Abishag serves David, but the text denies sexual relations.','david,solomon,adonijah,abishag,bathsheba,nathan-prophet,joab,abiathar,zadok,benaiah,jonathan-abiathar','jerusalem,en-rogel,gihon','Original study reflection: examine who has a voice when leaders transfer authority.'),
('David dies and Solomon consolidates power','David gives final instructions. Solomon removes Abiathar and orders the deaths of Adonijah, Joab, and Shimei.','The royal transition combines covenant advice, political threats, and executions. The guide does not infer every private motive behind the request for Abishag.','david,solomon,adonijah,abishag,bathsheba,joab,abiathar,zadok,benaiah,shimei-gera,barzillai,abner,amasa','jerusalem,anathoth,gath','Original study reflection: distinguish a ruler’s claim of justice from proof that every action is justified.'),
('Solomon asks for wisdom and judges a dispute','At Gibeon, Solomon asks for an understanding heart. In Jerusalem, two women dispute the identity of a living infant.','The threatened division of the child exposes a difference between the women’s responses. It is a judgment story, not a recommended parenting test.','solomon,judgment-women,pharaoh-daughter-solomon','gibeon,jerusalem','Come, Follow Me encourages seeking discernment between right and wrong.'),
('Officials, provisions, and wisdom','The chapter lists officials, regional suppliers, royal provisions, and Solomon’s reputation for wisdom.','A prosperous court requires workers, food, and administration. Its numerical claims are preserved as textual claims, not independently measured totals.','solomon,adoniram,zadok,abiathar,benaiah','jerusalem','Original study reflection: identify the labor and resources behind a description of prosperity.'),
('Hiram supplies timber for the temple','Solomon and Hiram arrange timber and food exchanges. Adoniram supervises a labor levy, while builders prepare stone and wood.','International cooperation and compelled labor support construction. The guide keeps workers visible alongside the royal achievement.','solomon,hiram,adoniram','jerusalem,tyre,lebanon','Original study reflection: consider how sacred projects affect the people who build them.'),
('The temple is built','The account describes the temple’s rooms, wooden carvings, gold covering, and cherubim. God’s promise also requires faithful conduct.','The building description is a literary account. The map marks Jerusalem without claiming a verified floor plan or exact surviving foundation.','solomon','jerusalem','Come, Follow Me invites reflection on sacred space and temple symbols.'),
('Royal buildings and bronze furnishings','Solomon’s palace buildings are described. Hiram the bronze worker makes pillars, the sea, movable stands, and other vessels.','Hiram the artisan is distinct from the king of Tyre. The chapter describes craft knowledge and materials alongside royal buildings.','solomon,hiram-artisan,pharaoh-daughter-solomon','jerusalem,tyre,succoth,zarethan','The older manual connects the bronze sea with baptism. This is an LDS interpretation, not archaeological proof.'),
('The ark enters the temple and Solomon prays','The ark is brought into the sanctuary. Solomon prays about justice, forgiveness, drought, foreigners, war, and exile.','The prayer says heaven cannot contain God. It joins a particular sacred house with concern for people beyond Israel.','solomon','jerusalem','Come, Follow Me connects the dedication prayer with temple covenants and walking in God’s ways.'),
('Promises, warnings, labor, and trade','God answers Solomon with a promise and warning. The chapter describes towns, building projects, labor, and ships sailing toward Ophir.','Sacred status does not remove accountability. Ophir’s location is disputed, so the guide does not invent a destination or sea route.','solomon,hiram,pharaoh-daughter-solomon','jerusalem,tyre,galilee,gezer,hazor,megiddo,ezion-geber','Come, Follow Me studies God’s promises and the responsibility to keep covenants.'),
('The queen of Sheba visits','The queen tests Solomon with questions and sees the court. Gifts, trade, gold, horses, and royal wealth follow.','The narrative presents international reputation and abundance. The queen is unnamed, and no exact journey or independent inventory is established here.','solomon,queen-sheba','jerusalem','Original study reflection: compare admiration for wealth with the responsibilities of a ruler.'),
('Solomon turns away and adversaries rise','Solomon supports other gods. Hadad and Rezon become adversaries. Ahijah promises Jeroboam a kingdom, and Solomon later dies.','The account holds Solomon responsible for his worship. It also recalls displaced people and rival powers, rather than only court prosperity.','solomon,hadad-edom,rezon,jeroboam,ahijah-shiloh,rehoboam,shishak,tahpenes,genubath,pharaoh-daughter-solomon','jerusalem,edom,egypt,damascus,shiloh,zeredah','Come, Follow Me asks readers to examine influences that turn their hearts from God.'),
('Rehoboam rejects the petition and the kingdom divides','Rehoboam rejects advice to ease the people’s burden. The northern tribes follow Jeroboam, who establishes worship at Bethel and Dan.','Labor grievances and political decisions contribute to division. The calves’ form and function need interpretation beyond assuming every worshiper’s private belief.','rehoboam,jeroboam,shemaiah,adoram','shechem,jerusalem,bethel,dan,penuel','Come, Follow Me studies the effect of leaders’ choices and the need for good counsel.'),
('A man of God confronts Bethel','A man of God announces judgment at Bethel. An older prophet deceives him into eating, and a lion later kills him.','The account combines a future oracle, signs, deception, and death. The older prophet’s claim is explicitly false. The guide does not invent either man’s name.','jeroboam,judah-man-god,bethel-old-prophet','bethel','Original study reflection: test a claimed revelation without assuming that status makes every claim reliable.'),
('Ahijah speaks and Shishak attacks Jerusalem','Jeroboam’s disguised wife visits Ahijah about their son Abijah. The child dies. The account then describes Rehoboam’s rule and Shishak’s attack.','Royal households and ordinary people bear consequences in the account. Abijah the child is distinct from Abijam, Rehoboam’s successor.','jeroboam,jeroboam-wife,ahijah-shiloh,abijah-child,rehoboam,naamah,shishak,abijam','tirzah,shiloh,jerusalem,egypt','Original study reflection: retain the child and grieving household when assessing a royal judgment.'),
('Judah’s rulers and a new northern dynasty','Abijam and Asa rule Judah. Asa seeks Ben Hadad’s help against Baasha. Baasha kills Nadab and destroys Jeroboam’s household.','The succession notices assess worship and record conflict. The same royal name can refer to different rulers in different generations.','abijam,asa,maacah-queen,ben-hadad-asa,nadab,baasha','jerusalem,tirzah,ramah,gebа,mizpah,damascus,gibbethon','Original study reflection: compare religious reform with the use of war and purchased alliances.'),
('Rapid succession leads to Omri and Ahab','Jehu condemns Baasha’s house. Zimri kills Elah and is defeated. Omri prevails over Tibni, builds Samaria, and is succeeded by Ahab.','The narrative records unstable transfers of power. Ahab’s marriage and temple practices lead into the Elijah accounts. Hiel’s sons remain named in the rebuilding notice.','jehu-hanani,baasha,elah,zimri,omri,tibni,shemer,ahab,jezebel,hiel','tirzah,gibbethon,samaria,sidon,jericho','Original study reflection: consider the human costs of a sequence summarized as royal succession.'),
('Elijah and the widow at Zarephath','Elijah announces drought, receives food at Cherith, and stays with a widow at Zarephath. Her food endures, and her son returns to life.','The widow expresses scarcity, fear, and grief. Her words matter alongside the prophet’s actions. Cherith’s exact location remains uncertain.','elijah,ahab,zarephath-widow,zarephath-son','cherith,zarephath,gilead','Come, Follow Me studies the widow’s trust amid scarcity.'),
('Elijah confronts Ahab at Carmel','Obadiah meets Elijah. At Carmel, Elijah challenges divided allegiance. Fire answers his prayer, the Baal prophets are killed, and rain returns.','The narrative connects rain with divine power and includes mass killing. A religious application does not remove that violence from the account.','elijah,ahab,obadiah-palace,elijah-servant','samaria,carmel,kishon,jezreel','Come, Follow Me uses Elijah’s challenge to examine commitment to God.'),
('Elijah receives care and calls Elisha','Threatened by Jezebel, Elijah flees, asks to die, receives food, and travels to Horeb. He receives renewed work and places his mantle on Elisha.','Food, rest, and divine communication precede renewed service. The commands to appoint Hazael and Jehu are not reported as completed here.','elijah,jezebel,elisha,hazael,jehu-nimshi','jezreel,beersheba,horeb,abel-meholah','Come, Follow Me studies the quiet voice and Elisha’s willingness to respond.'),
('Ahab defeats Ben Hadad and releases him','Ben Hadad attacks Samaria. Prophets advise Ahab, and Israel wins two battles. Ahab releases his opponent and receives a prophetic rebuke.','Military success and divine approval are not identical. The king called Ben Hadad here is kept distinct from Asa’s earlier ally.','ahab,ben-hadad-ahab,ahab-prophets','samaria,aphek','Original study reflection: examine how victory can still leave a leader accountable for a decision.'),
('Naboth is killed and Elijah confronts Ahab','Naboth refuses to give up his vineyard. Jezebel arranges false accusations and his killing. Ahab takes possession, and Elijah announces judgment.','The king benefits from an injustice carried out through officials and false testimony. Naboth’s refusal concerns inherited land, not simple unwillingness to sell.','naboth,ahab,jezebel,elijah','jezreel,samaria','Original study reflection: consider how a person can benefit from wrongdoing arranged by another.'),
('Micaiah warns Ahab before the final battle','Ahab and Jehoshaphat seek counsel about Ramoth Gilead. Micaiah describes a heavenly council and predicts defeat. Ahab dies in battle.','A large agreement among prophets does not settle the question of truth. The council scene raises difficult questions about deception and divine agency.','ahab,jehoshaphat,micaiah,zedekiah-chenaanah,amon-governor,joash-prince,ahaziah-ahab','samaria,ramoth-gilead,jerusalem,ezion-geber','The older manual reads the council as divine permission. This remains an LDS interpretation of a difficult scene.')]

defs=[
('solomon','Solomon','King whose wisdom and temple building accompany later failure','Son of David and Bathsheba. Father of Rehoboam.','1–11','He asks for wisdom, builds the temple, and later supports other gods. Achievement does not cancel responsibility.'),
('adonijah','Adonijah','Royal son who claims the throne','Son of David and Haggith. Half-brother of Solomon.','1–2','He gathers supporters and later requests Abishag as wife. Solomon orders his death.'),
('abishag','Abishag','Young Shunammite who serves the aging David','Attendant brought to David. Requested as wife by Adonijah.','1–2','The account denies sexual relations with David. It does not report her own wishes about the later request.'),
('judgment-women','The two women before Solomon','Unnamed women disputing the living child','Both live in the same house and have infants. The text calls them prostitutes.','3:16–28','One urges that the child remain alive. Their names and later lives are not supplied.'),
('pharaoh-daughter-solomon','Pharaoh’s daughter, Solomon’s wife','Unnamed royal woman in a marriage alliance','Wife of Solomon. Distinct from the princess who finds Moses in Exodus.','3:1; 7:8; 9:16,24; 11:1','Her house and marriage enter the royal account. The text does not identify her father by a secure Egyptian royal name.'),
('adoniram','Adoniram','Official supervising the labor levy','Son of Abda. Serves Solomon.','4:6; 5:14','The construction story includes compelled labor. Identification with Adoram in chapter 12 remains a proposed connection.'),
('hiram-artisan','Hiram, the bronze worker','Craftsman making temple furnishings','Son of a Naphtalite widow and a Tyrian bronze worker. Distinct from King Hiram.','7:13–45','Skill and knowledge contribute to sacred construction. He is not the king who supplies timber.'),
('queen-sheba','The queen of Sheba','Unnamed visiting ruler who questions Solomon','Brings gifts and tests the king with questions.','10:1–13','The narrative praises wisdom through a foreign ruler’s visit. Her exact identity and itinerary remain uncertain.'),
('hadad-edom','Hadad','Edomite adversary who returns from Egypt','Escapes conflict in Edom as a child. Father of Genubath.','11:14–22','The account recalls exile and family losses behind opposition to Solomon.'),
('rezon','Rezon','Adversary who rules at Damascus','Son of Eliada. Former servant of Hadadezer.','11:23–25','His rise supplies another perspective on the limits of Solomon’s rule.'),
('jeroboam','Jeroboam','First northern king after the division','Son of Nebat and the widow Zeruah. Father of Abijah and Nadab.','11–15','He receives Ahijah’s promise and establishes royal shrines. Fear of losing power shapes his decision.'),
('ahijah-shiloh','Ahijah, the Shilonite','Prophet who addresses Jeroboam’s future','From Shiloh. Distinct from the scribe Ahijah in chapter 4.','11:29–39; 14:1–18','He announces both a kingdom and judgment. Blindness does not prevent the narrative’s recognition scene.'),
('rehoboam','Rehoboam','King whose harsh answer precedes the division','Son of Solomon and Naamah. Father of Abijam.','11–15','He rejects advice to ease burdens and retains Judah’s kingdom.'),
('shishak','Shishak','Egyptian king who receives Jeroboam and attacks Jerusalem','Named in relation to Jeroboam’s flight and Rehoboam’s losses.','11:40; 14:25–26','The reading text names him. It does not identify every Egyptian king elsewhere as the same ruler.'),
('tahpenes','Tahpenes','Egyptian queen named in Hadad’s refuge account','Sister of Hadad’s wife. Raises Genubath within the royal household.','11:19–20','The text gives household connections without a securely established modern identification.'),
('genubath','Genubath','Son of Hadad raised in Egypt','Mother is Tahpenes’s sister.','11:20','His childhood links the refugee household with the Egyptian court.'),
('shemaiah','Shemaiah','Man of God who counsels against the civil war','Speaks to Rehoboam and Judah.','12:22–24','His instruction interrupts the planned attack on the northern tribes.'),
('adoram','Adoram','Labor official killed during the division','Sent by Rehoboam to the northern assembly.','12:18','The people stone him. The guide does not silently merge him with Adoniram.'),
('judah-man-god','The man of God from Judah','Unnamed speaker at Jeroboam’s altar','Receives instructions that the older prophet falsely contradicts.','13','He announces judgment and later dies. His identity remains unnamed.'),
('bethel-old-prophet','The older prophet at Bethel','Unnamed prophet who deceives the visiting man','Father of sons who report the altar scene.','13','The text explicitly says he lies. He later mourns the man he deceived.'),
('jeroboam-wife','Jeroboam’s wife','Unnamed mother who visits Ahijah in disguise','Mother of the sick child Abijah.','14:1–18','She seeks news about her child and returns before his death.'),
('abijah-child','Abijah, Jeroboam’s son','Child whose illness prompts the visit to Ahijah','Son of Jeroboam and his unnamed wife.','14:1–18','He dies and receives burial. He is distinct from Judah’s king Abijam.'),
('naamah','Naamah','Ammonite mother of Rehoboam','Named twice in the account of his reign.','14:21,31','Her origin is recorded, but the text gives no independent account of her actions.'),
('abijam','Abijam','King of Judah between Rehoboam and Asa','Son of Rehoboam. Maacah is called his mother.','14:31; 15:1–8','The text criticizes his conduct while retaining the promise associated with David.'),
('asa','Asa','Judean king associated with reform and alliance','Successor of Abijam. Father of Jehoshaphat.','15; 22','He removes cult objects and seeks Syrian help against Baasha. The narrative reports both reform and war.'),
('maacah-queen','Maacah','Royal mother removed by Asa','The text calls her mother of Abijam and of Asa.','15:2,10,13','The family wording requires care. This profile does not invent a single solution or merge her with David’s wife.'),
('ben-hadad-asa','Ben Hadad, Asa’s ally','Syrian king paid to attack Baasha’s territory','Son of Tabrimmon, son of Hezion.','15:18–20','He is kept distinct from the later king opposed by Ahab.'),
('nadab','Nadab','Northern king killed by Baasha','Son of Jeroboam.','14:20; 15:25–31','His death ends his brief rule and precedes destruction of his household. He is not Aaron’s son.'),
('baasha','Baasha','Northern ruler who replaces Nadab','Son of Ahijah of the house of Issachar. Father of Elah.','15–16','He besieges Ramah and receives prophetic condemnation. His father is not the Shilonite prophet.'),
('jehu-hanani','Jehu, Hanani’s son','Prophet who condemns Baasha’s dynasty','Son of Hanani. Distinct from Jehu son of Nimshi.','16:1–7,12','His words interpret the dynasty’s collapse within the narrative.'),
('elah','Elah','Northern king killed by his officer','Son of Baasha. Zimri kills him at Tirzah.','16:6–14','His brief rule ends during a coup. No wider personal biography is established here.'),
('zimri','Zimri','Officer who takes power for seven days','Kills Elah. Opposed by Omri’s army.','16:9–20','He burns the royal house over himself when the city falls. The account does not establish a modern diagnosis.'),
('omri','Omri','Army commander who becomes king and builds Samaria','Opponent of Tibni. Father of Ahab.','16:16–30','He establishes a new royal center. Political achievement and the narrator’s religious judgment differ.'),
('tibni','Tibni','Rival claimant during Omri’s rise','Son of Ginath.','16:21–22','Part of the people support him. His death ends the account’s divided succession.'),
('shemer','Shemer','Owner who sells Samaria’s hill','Sells the site to Omri for two talents of silver.','16:24','The account connects the city’s name with his name. Exact property boundaries are not supplied.'),
('ahab','Ahab','Northern king confronted by Elijah and Micaiah','Son of Omri. Husband of Jezebel. Father of Ahaziah.','16–22','His reign includes military success, Naboth’s dispossession, prophetic conflict, and death in battle.'),
('jezebel','Jezebel','Royal woman who threatens Elijah and arranges Naboth’s killing','Daughter of Ethbaal, king of the Sidonians. Wife of Ahab.','16:31; 18–19; 21','The text assigns her specific harmful acts. It does not justify condemning all foreign women.'),
('hiel','Hiel','Bethelite associated with rebuilding Jericho','Father of Abiram and Segub.','16:34','The notice names the sons lost during rebuilding. The guide does not invent how they died.'),
('elijah','Elijah','Prophet confronting royal conduct and divided worship','Called a Tishbite from the inhabitants of Gilead. Calls Elisha.','17–19; 21','His story includes provision, grief, confrontation, exhaustion, care, and renewed work.'),
('zarephath-widow','The widow of Zarephath','Unnamed woman who houses Elijah amid scarcity','Mother of a son who becomes ill and returns to life.','17:8–24','She speaks about hunger and grief. Her experience remains part of the account, not only a test for the prophet.'),
('zarephath-son','The widow’s son','Unnamed child in Elijah’s healing account','Son of the widow at Zarephath.','17:12,17–24','The story reports his return to life without giving his name or later biography.'),
('obadiah-palace','Obadiah','Palace official who hides endangered prophets','Serves Ahab and fears the LORD.','18:3–16','He risks his position to protect prophets. He is not securely identified as the author of the book of Obadiah.'),
('elijah-servant','Elijah’s unnamed servant','Helper who watches for the cloud','Sent repeatedly to look toward the sea.','18:43–44; 19:3','The chapter names no servant. The guide does not assume that every later servant is this person.'),
('elisha','Elisha','Farmer called through Elijah’s mantle','Son of Shaphat. From Abel Meholah.','19:16,19–21','He leaves his former work to serve Elijah. His later ministry belongs to 2 Kings.'),
('hazael','Hazael','Future Syrian king named in Elijah’s commission','Named in the instruction at Horeb.','19:15–17','The chapter commands his appointment but does not narrate Elijah completing it.'),
('jehu-nimshi','Jehu, Nimshi’s son','Future northern ruler named in Elijah’s commission','Distinct from the prophet Jehu son of Hanani.','19:16–17','The chapter commands his appointment. The later transition is narrated in 2 Kings.'),
('ben-hadad-ahab','Ben Hadad, Ahab’s opponent','Syrian king defeated and released by Ahab','Commands allied kings against Samaria.','20','The account records two campaigns. He is kept distinct from Asa’s earlier ally.'),
('ahab-prophets','The prophets who counsel Ahab','Unnamed prophetic speakers in the battle account','Give military instructions and later confront the king.','20','The text does not securely identify every speaker as the same person. This is a group profile.'),
('naboth','Naboth','Jezreelite killed through false accusations','Owner of inherited vineyard land beside Ahab’s palace.','21','He refuses to surrender the inheritance. Officials act on Jezebel’s letters, and Ahab takes the land.'),
('jehoshaphat','Jehoshaphat','Judean king who seeks counsel before battle','Son of Asa and Azubah. Father of Jehoram.','22','He asks for a prophet of the LORD, joins Ahab, and survives the battle.'),
('micaiah','Micaiah','Prophet who reports the heavenly council','Son of Imlah. Imprisoned after warning Ahab.','22:8–28','He resists pressure to agree with the other prophets. His vision includes troubling divine permission and deception.'),
('zedekiah-chenaanah','Zedekiah','Prophet who opposes Micaiah','Son of Chenaanah. Makes iron horns.','22:11,24–25','He claims victory and strikes Micaiah. He is distinct from the later Judean king.'),
('amon-governor','Amon','City governor ordered to hold Micaiah','Receives the king’s instruction with Joash.','22:26','He is distinct from the later Judean king named Amon.'),
('joash-prince','Joash','King’s son named in Micaiah’s imprisonment order','Appears with the governor Amon.','22:26','The text gives limited information. He is not merged with later same-name kings.'),
('ahaziah-ahab','Ahaziah','Northern king who succeeds Ahab','Son of Ahab.','22:40,49–53','His reign begins at the end of this book and continues in 2 Kings.')]
people=[person(i,n,r,rel,'1 Kings '+refs,m) for i,n,r,rel,refs,m in defs]
old=json.loads((OUT/'2-samuel.json').read_text(encoding='utf-8'))
reuse={'david':'1–2; 3:3,6,14; 5:3–5; 8:15–26; 11:4–6,12–13,32–38','bathsheba':'1–2','nathan-prophet':'1','joab':'1–2','abiathar':'1–2; 4:4','zadok':'1–2; 4:2,4','benaiah':'1–2; 4:4','jonathan-abiathar':'1:42–48','shimei-gera':'2:8–9,36–46','barzillai':'2:7','abner':'2:5,32','amasa':'2:5,32','hiram':'5; 9–10'}
for p in old['people']:
 if p['id'] in reuse:people.append(dict(p,passages='1 Kings '+reuse[p['id']],sourceIds=['web'],placeIds=[],linkNames=[]))
updates={'david':('Aging king who names Solomon as successor','He confirms Solomon’s succession and gives final instructions. His death closes the earlier royal narrative.'),'bathsheba':('Royal mother who advocates for Solomon','She approaches David about succession and later carries Adonijah’s request to Solomon.'),'nathan-prophet':('Prophet who supports Solomon’s succession','He advises Bathsheba and participates in Solomon’s anointing.'),'joab':('Commander who supports Adonijah','He takes refuge at the altar, but Solomon orders Benaiah to kill him.'),'abiathar':('Priest removed after supporting Adonijah','Solomon spares his life but removes him from office and sends him to Anathoth.'),'zadok':('Priest who anoints Solomon','He supports Solomon’s succession and replaces Abiathar.'),'benaiah':('Officer who carries out Solomon’s commands','He participates in the anointing and later executes the king’s orders.'),'jonathan-abiathar':('Messenger who reports Solomon’s anointing','He brings news that ends Adonijah’s feast.'),'shimei-gera':('Benjaminite placed under Solomon’s restriction','He leaves Jerusalem to retrieve servants and is executed after breaking the imposed condition.'),'barzillai':('Earlier supporter recalled in David’s instructions','David asks Solomon to show kindness to his sons. The chapter recalls his earlier help.'),'abner':('Earlier commander recalled in David’s instructions','David recalls Joab’s killing of him. This is a remembered event from 2 Samuel.'),'amasa':('Earlier commander recalled in David’s instructions','David recalls Joab’s killing of him. His presence is a remembered event.'),'hiram':('King of Tyre supplying timber and skilled workers','He cooperates with Solomon and receives towns that displease him. He is distinct from Hiram the artisan.')}
for p in people:
 if p['id'] in updates:p.update(role=updates[p['id']][0],meaning=updates[p['id']][1])
aliases={'hiram-artisan':['Hiram'],'ahijah-shiloh':['Ahijah'],'ben-hadad-asa':['Ben Hadad'],'ben-hadad-ahab':['Ben Hadad'],'jehu-hanani':['Jehu'],'jehu-nimshi':['Jehu'],'abijah-child':['Abijah'],'jonathan-abiathar':['Jonathan'],'pharaoh-daughter-solomon':['Pharaoh’s daughter'],'zarephath-widow':['widow'],'judgment-women':['two women']}
scopes={'shimei-gera':{'1':[],'4':[]},'zadok':{'4':[4]},'abiathar':{'4':[4]},'benaiah':{'4':[4]},'nathan-prophet':{'4':[]},'ahijah-shiloh':{'4':[],'15':[]},'hiram':{'7':[]},'hiram-artisan':{'5':[],'9':[],'10':[]},'jehoshaphat':{'4':[]}}
for p in people:
 p['linkNames']=aliases.get(p['id'],[])
 if p['id'] in scopes:p['verseScope']=scopes[p['id']]
coords=[('gihon','Gihon · Jerusalem spring',31.773,35.236),('anathoth','Anathoth · proposed locality',31.815,35.261),('lebanon','Lebanon · broad mountain region',34.00,35.85),('succoth','Succoth · proposed locality',32.20,35.63),('zarethan','Zarethan · locality uncertain',32.27,35.58),('galilee','Galilee · broad region',32.85,35.30),('hazor','Hazor',33.017,35.569),('megiddo','Megiddo',32.585,35.184),('ezion-geber','Ezion Geber · disputed Gulf of Aqaba locality',29.55,35.0),('egypt','Egypt · broad region',30.05,31.23),('damascus','Damascus',33.513,36.292),('shiloh','Shiloh',32.055,35.289),('zeredah','Zeredah · locality uncertain',32.04,35.02),('shechem','Shechem',32.213,35.282),('bethel','Bethel · proposed locality',31.93,35.22),('penuel','Penuel · proposed locality',32.185,35.694),('tirzah','Tirzah · proposed locality',32.287,35.342),('ramah','Ramah · Benjamin locality',31.853,35.237),('geba','Geba · proposed locality',31.857,35.259),('mizpah','Mizpah · Benjamin identification uncertain',31.886,35.215),('gibbethon','Gibbethon · locality uncertain',31.94,34.80),('samaria','Samaria',32.276,35.194),('cherith','Cherith · broad eastern Jordan setting, exact brook unknown',32.20,35.85),('zarephath','Zarephath · coastal locality',33.46,35.30),('carmel','Mount Carmel · broad mountain setting',32.73,35.04),('kishon','Kishon · broad river setting',32.75,35.12),('jezreel','Jezreel',32.557,35.329),('horeb','Horeb · traditional Sinai region, identification disputed',28.54,33.97),('abel-meholah','Abel Meholah · proposed locality',32.35,35.53),('aphek','Aphek · battle locality uncertain',32.82,35.71),('ramoth-gilead','Ramoth Gilead · locality disputed',32.47,35.85)]
needed=['jerusalem','en-rogel','gath','gibeon','tyre','gezer','edom','dan','sidon','jericho','gilead','beersheba']
places=[dict(p) for p in old['places'] if p['id'] in needed]+[place(i,n,lat,lng,'Named town or broad setting in the chapter.','Reference marker only. Proposed or broad locations do not establish an exact house, shrine, brook, mountain, battle position, or ancient road.',['web','atlas-canaan']) for i,n,lat,lng in coords]
sources=[source('web','1 Kings · World English Bible','https://ebible.org/engwebp/1KI01.htm','Public-domain reading text for all 22 chapters.','Scripture',limits='The reading text preserves narrative claims. It does not independently verify dates, appearances, quantities, or every event.')]+[dict(s) for s in old['sources'] if s['id'] in ['terrain','atlas','atlas-canaan']]
def reviewed(i,title,url,summary,author,year,coverage,scope,limits,category='Scholarly study',perspective='historical',group=None):
 s=source(i,title,url,summary,category,perspective,limits);s.update(author=author,year=year,chapterCoverage=coverage,reviewed='2026-10-05: '+scope)
 if group:s['group']=group
 sources.append(s)
reviewed('yale-solomon','Solomon · Yale Bible Study','https://yalebiblestudy.org/courses/kings-and-chronicles/lessons/kings-part-1-discussion-g/','The guide studies the mixture of royal praise, criticism, and theological history.','Yale Divinity School · course presented by Joel S. Baden and John J. Collins','Linked course',list(range(1,12)),'Main study-guide text and course presenter record reviewed.','Proposed literary sources and assessments of Solomon’s economy remain interpretations. They do not verify every narrated action.')
reviewed('yale-division','The divided monarchy · Yale Bible Study','https://yalebiblestudy.org/courses/kings-and-chronicles/lessons/the-book-of-kings-part-2-study-guide/','The guide examines construction burdens, political division, royal shrines, and the northern monarchy.','Yale Divinity School · Kings and Chronicles course','Linked course',[5,6,7,8,9,11,12,16,21],'Main study-guide text reviewed.','Its claim that temple construction defied God’s instruction is not adopted. Its broad economic and pre-monarchy reconstructions need independent evidence.')
reviewed('yale-prophets','Prophetic authority · Yale Bible Study','https://yalebiblestudy.org/courses/kings-and-chronicles/lessons/the-book-of-kings-part-3-study-guide/','The guide examines prophetic opposition to royal abuse and stories of provision and healing.','Yale Divinity School · Kings and Chronicles course','Linked course',[17,18,19,21],'Prophetic Authority and Prophetic Miracles sections reviewed.','Use only for its literary framework. Its count of Baal prophets differs from 1 Kings 18:19. Later reference errors and attribution of Jehu’s actions to Elijah are not adopted.')
reviewed('nelson-record','First and Second Kings · published edition record','https://books.google.com/books/about/First_and_Second_Kings.html?id=RCgUvQOIvD0C','The edition record identifies Nelson’s commentary and its treatment of Kings as theological literature.','Richard D. Nelson · Westminster John Knox Press',1987,[],'Licensed Google Books edition metadata and contents reviewed.','The full commentary was not read. This record verifies the work cited in Wikipedia, not every argument attributed to it.')
reviewed('wiki-1-kings','Books of Kings · Wikipedia','https://en.wikipedia.org/wiki/Books_of_Kings','The opening locates Kings in the biblical account of monarchy and introduces Solomon’s succession.','Wikipedia contributors','Reviewed revision',[1,11,12,22],'Opening four substantive paragraphs reviewed at revision 1376823112.','Use for background and source discovery. Broad reliability and composition claims require separate evidence.','Encyclopedia background')
sources[-1].update(revisionId='1376823112',revisionUrl='https://en.wikipedia.org/w/index.php?oldid=1376823112',license='CC BY-SA 4.0',licenseUrl='https://creativecommons.org/licenses/by-sa/4.0/',citedSourceIds=['nelson-record'])
reviewed('porter-record','God Among the Gods · thesis record','https://digitalcommons.liberty.edu/masters/141/','The university record identifies the thesis that McClellan critiques.','Daniel F. Porter · Liberty University',2010,[],'University record and abstract reviewed.','The linked thesis returned an access error. Its full argument and House commentary citations were not checked. The abstract is not adopted as consensus.')
reviewed('dm-kings-council','1 Kings 22 and the divine council · original McClellan commentary','https://danielomcclellan.wordpress.com/2010/07/30/new-masters-thesis-on-the-divine-council/','McClellan contrasts readings of the heavenly council and questions an assumed uniform biblical theology.','Dan McClellan','July 30, 2010',[22],'Original post’s paragraph on 1 Kings 22 reviewed. Related Porter thesis record verified.','Older critical commentary. Porter’s full thesis and House’s commentary were not read. One post does not establish scholarly consensus.','Scholar commentary',group='mcclellan')
sources[-1]['citedSourceIds']=['porter-record']
base='https://www.churchofjesuschrist.org/study/manual/'
reviewed('lds-kings-solomon','1 Kings 1–11 · Institute commentary',base+'old-testament-student-manual-kings-malachi/chapter-1?lang=eng','The manual studies wisdom, temple furnishings, dedication, and Solomon’s failure.','The Church of Jesus Christ of Latter-day Saints',1982,[7],'Sections 1-16–1-17, 1-23, 1-32–1-35, 1-39, and 1-44–1-45 reviewed.','Older motive claims and historical reconstructions are not adopted as verified facts. The bronze sea comparison is Church interpretation.','LDS study manual','lds')
reviewed('lds-kings-division','1 Kings 12 · Institute commentary',base+'old-testament-student-manual-kings-malachi/chapter-4?lang=eng','The manual studies counsel, division, and royal worship policy.','The Church of Jesus Christ of Latter-day Saints',1982,[],'Sections 4-2–4-12 reviewed, covering the division in chapter 12.','Later sections on chapters 13–16 were not reviewed. Proposed private motives and precise dates need other evidence.','LDS study manual','lds')
reviewed('lds-kings-elijah','1 Kings 17–22 · Institute commentary',base+'old-testament-student-manual-kings-malachi/chapter-5?lang=eng','The manual studies Elijah’s service, quiet revelation, prophetic calling, and the heavenly council.','The Church of Jesus Christ of Latter-day Saints',1982,[22],'Sections 5-2–5-31 reviewed.','Church interpretation remains separate from archaeological evidence. Its Baal identification and completed Hazael appointment claim are not adopted.','LDS study manual','lds')
reviewed('cfm-kings-solomon','Come, Follow Me 2026 · Solomon and the temple',base+'come-follow-me-for-home-and-church-old-testament-2026/26?lang=eng','The lesson studies discernment, temple covenants, and lasting faithfulness.','The Church of Jesus Christ of Latter-day Saints',2026,[3,6,8,9,11],'First Kings teaching sections reviewed: 3; 6–9; 11.','Modern LDS application does not prove that ancient temple practice was identical.','Come, Follow Me','lds')
reviewed('cfm-kings-elijah','Come, Follow Me 2026 · division and Elijah',base+'come-follow-me-for-home-and-church-old-testament-2026/27?lang=eng','The lesson studies counsel, the widow’s faith, commitment, and quiet revelation.','The Church of Jesus Christ of Latter-day Saints',2026,[12,17,18,19],'Main teaching text reviewed, especially sections on 12 and 17–19.','The lesson selects passages rather than commenting on every verse in chapters 12–22.','Come, Follow Me','lds')
routes={1:['en-rogel','gihon'],2:['jerusalem','gath','jerusalem'],5:['tyre','lebanon','jerusalem'],11:['edom','egypt'],12:['shechem','jerusalem'],14:['shiloh','tirzah'],17:['cherith','zarephath'],18:['carmel','jezreel'],19:['jezreel','beersheba','horeb'],22:['samaria','ramoth-gilead']}
chapters=[]
for n,(title,summary,meaning,pids,locs,lds) in enumerate(rows,1):
 locs=locs.replace('gebа','geba')
 ids=['web','atlas-canaan']+[s['id'] for s in sources if s['perspective']=='historical' and n in s.get('chapterCoverage',[])]
 refs=[s['id'] for s in sources if s['perspective']=='lds' and n in s.get('chapterCoverage',[])]
 chapters.append(dict(chapter=n,title=title,summary=summary,meaning=meaning,people=pids.split(','),places=locs.split(','),sourceIds=ids,lds=dict(text=lds,sourceIds=refs),eventOrder=n,dateLabel='Chapter order · historical year uncertain',historicalNote='Narrative order and regnal notices do not supply an independently verified date for every event.',mapNote='Named towns and approximate regions. Disputed sites and exact buildings remain uncertain.',route=routes.get(n,[]),routeEvidence='Connects named settings in narrative order. Approximate lines do not reconstruct ancient roads, sea voyages, or exact battle movements.'))
locations={'solomon':['jerusalem','gibeon'],'adonijah':['jerusalem','en-rogel'],'abishag':['jerusalem'],'judgment-women':['jerusalem'],'pharaoh-daughter-solomon':['jerusalem'],'adoniram':['lebanon'],'hiram-artisan':['tyre','jerusalem'],'queen-sheba':['jerusalem'],'hadad-edom':['edom','egypt'],'rezon':['damascus'],'jeroboam':['zeredah','egypt','shechem','tirzah'],'ahijah-shiloh':['shiloh'],'rehoboam':['shechem','jerusalem'],'shishak':['egypt','jerusalem'],'tahpenes':['egypt'],'genubath':['egypt'],'shemaiah':['jerusalem'],'adoram':['shechem'],'judah-man-god':['bethel'],'bethel-old-prophet':['bethel'],'jeroboam-wife':['shiloh','tirzah'],'abijah-child':['tirzah'],'naamah':[],'abijam':['jerusalem'],'asa':['jerusalem'],'maacah-queen':['jerusalem'],'ben-hadad-asa':['damascus'],'nadab':['gibbethon'],'baasha':['tirzah','ramah'],'jehu-hanani':[],'elah':['tirzah'],'zimri':['tirzah'],'omri':['gibbethon','tirzah','samaria'],'tibni':[],'shemer':['samaria'],'ahab':['samaria','jezreel','ramoth-gilead'],'jezebel':['samaria','jezreel'],'hiel':['jericho','bethel'],'elijah':['gilead','cherith','zarephath','carmel','beersheba','horeb'],'zarephath-widow':['zarephath'],'zarephath-son':['zarephath'],'obadiah-palace':['samaria'],'elijah-servant':['carmel','beersheba'],'elisha':['abel-meholah'],'hazael':[],'jehu-nimshi':[],'ben-hadad-ahab':['samaria','aphek'],'ahab-prophets':['samaria','aphek'],'naboth':['jezreel'],'jehoshaphat':['jerusalem','ramoth-gilead'],'micaiah':['samaria'],'zedekiah-chenaanah':['samaria'],'amon-governor':['samaria'],'joash-prince':['samaria'],'ahaziah-ahab':['samaria'],'david':['jerusalem'],'bathsheba':['jerusalem'],'nathan-prophet':['jerusalem'],'joab':['jerusalem'],'abiathar':['anathoth','jerusalem'],'zadok':['jerusalem'],'benaiah':['jerusalem'],'jonathan-abiathar':['en-rogel'],'shimei-gera':['jerusalem','gath'],'barzillai':[],'abner':[],'amasa':[],'hiram':['tyre']}
for p in people:p['placeIds']=locations[p['id']]
finish(dict(id='1-kings',bibleCode='1KI',name='1 Kings',description='Solomon · temple · divided kingdoms · Elijah · Naboth · Micaiah',chapterCount=22,scripture=scripture('1-kings','1KI',22),chapters=chapters,people=people,places=places,sources=sources,review=dict(date='2026-10-05',scope='Chapter-level studies and selected people. Same-name people remain separate. Reviewed scope and access limits accompany source records.',nextBook='2-kings')))
