import { addSourcePreviews } from './source-previews.mjs';
import { addChapterGeography } from './chapter-geography.mjs';
import { readFile, writeFile } from 'node:fs/promises';
import { addFullIsaiah } from './full-isaiah.mjs';
import { addComeFollowMe } from './come-follow-me.mjs';
import { addMcClellan } from './mcclellan.mjs';
import { addGeneralConference } from './general-conference.mjs';
import { addPrismAndHarmony } from './prism-and-harmony.mjs';
import { addChapterEnrichment } from './chapter-enrichment.mjs';
import { addAncientRoads } from './ancient-roads.mjs';

const sources = [];
function s(id,title,author,year,type,url,summary,limitations,license='Linked reading; original study guide summary, no article reproduction') { sources.push({id,title,author,year,type,url,summary,limitations,license}); }
s('web','Isaiah — World English Bible','World English Bible project','2026 retrieval','Biblical text','https://ebible.org/engwebp/ISA01.htm','The complete book of Isaiah in the public-domain World English Bible. Chapter notes distinguish the biblical account from historical evidence.','This is an English translation. It gives the Bible’s account. Other sources are needed to test its events against history.','Public domain; engwebp edition, punctuation preserved; navigation and footnotes excluded from reader.');
for(const c of [37,38,39]) s('web'+c,`Isaiah ${c} — World English Bible`,'World English Bible project','2026 retrieval','Biblical text',`https://ebible.org/engwebp/ISA${c}.htm`,'The full chapter in the World English Bible, with the publisher’s notes.','This chapter gives the Bible’s account. Other sources are needed to test its events against history.','Public domain');
s('met701','Sennacherib and Jerusalem','Ira Spar · The Metropolitan Museum of Art','2014','Museum scholarship','https://www.metmuseum.org/exhibitions/listings/2014/assyria-to-iberia/blog/posts/sennacherib-and-jerusalem','The museum looks at old writings, wall pictures, and the Bible. These sources tell about the war in 701 BCE. Judah lost many towns, but Jerusalem did not fall.','The museum joins several sources. We still do not know why Assyria left.');
s('rinap','Sennacherib: inscription with the Hezekiah passage','Royal Inscriptions of the Neo-Assyrian Period, ORACC','Digital edition','Primary evidence','https://oracc.museum.upenn.edu/rinap/rinap3/Q003945','Scholars edited this Assyrian royal writing and translated it. It tells of attacks on Hezekiah’s walled towns.','Parts of this royal account are missing. It praises the king’s power. Its numbers and victory claims may not be exact.');
s('lachish','Sennacherib receives the spoils of Lachish','British Museum · collection 1856,0909.14','Relief dated 700–692 BCE','Primary evidence','https://www.britishmuseum.org/collection/object/W_1856-0909-14_7','A relief is a picture carved on a wall. This palace relief names Lachish. It shows Assyria taking the city, as the king’s court saw it.','The relief was carved after the campaign. Its pictures praise Assyria’s victory. They do not show every detail in Isaiah.');
s('anderson','Isaiah 36–39: rethinking priority and historical reliability','Joel E. Anderson and Pieter M. Venter · HTS 65(1)','2009','Peer-reviewed research','https://www.scielo.org.za/scielo.php?pid=S0259-94222009000100009&script=sci_arttext','The writers compare Isaiah with the same story in Kings. They think Isaiah’s form came first. They study words that repeat and where the story was placed.','Other experts do not agree. Kings may have come first. Both books may also use an older source.');
s('yale','First Isaiah: historical context and authenticity','Yale Divinity School · Yale Bible Study','Undated','Academic teaching','https://yalebiblestudy.org/courses/first-isaiah/lessons/historical-context-study-guide/','This lesson tells about Isaiah’s time. It also tells why Zion and David’s royal family mattered. Some parts of the book may come from later times.','This is a short lesson. It does not give every reason for each date.');
s('metchron','Mesopotamia, 1000 BCE–1 CE','The Metropolitan Museum of Art','Undated','Museum scholarship','https://www.metmuseum.org/toah/ht/04/wam.html','This page shows when three empires ruled. They were Assyria, Babylon, and Persia. It also gives dates for the falls of Nineveh and Jerusalem.','This page covers a long span of time. Some dates are ranges. Other sources give the dates for Carchemish and the first fall of Jerusalem.');
s('livius605','Jerusalem Chronicle (ABC 5)','Livius.org · Jona Lendering','Undated','Ancient chronicle translation','https://www.livius.org/sources/content/mesopotamian-chronicles-content/abc-5-jerusalem-chronicle/','This page gives a free translation of the Babylonian Chronicle. It covers the 605 BCE Carchemish campaign. It also covers the 597 BCE capture of Jerusalem.','This web page presents an ancient record. The tablet is brief and damaged. It cannot give a complete account of either campaign.');
s('cyrus','The Cyrus Cylinder','British Museum · collection 1880,0617.1941','539 BCE setting','Primary evidence','https://www.britishmuseum.org/collection/object/W_1880-0617.1941','Cyrus had this royal message written on clay. It tells how he took Babylon. It also says he gave holy places back to some people.','The message does not name Judah. It does not say that people from Judah went home.');
s('strong','A Concise Dictionary of the Words in the Hebrew Bible','James Strong · Open Scriptures XML edition','1894 / digital edition','Historical lexicon','https://github.com/openscriptures/strongs','This dictionary lists Hebrew words in their dictionary forms. It gives the possible meanings of each word.','This is an older dictionary. A list of meanings cannot show which one fits a verse. The link opens the project page. The XML dictionary is too large for GitHub’s normal preview.','Source XML declares Public Domain. Only selected headwords and lexical information are used.');
s('oshb','Open Scriptures Hebrew Bible','Open Scriptures contributors / Westminster Leningrad Codex','Digital edition','Hebrew text','https://hb.openscriptures.org/','This source gives the Hebrew text with a label for each word. The guide uses them to check selected word notes against their verses.','The app checks selected words, not every English–Hebrew match. It shows Hebrew dictionary forms. The forms in the verses can differ. The link opens the project overview instead of the oversized Isaiah XML file.','Hebrew text public domain; lemma/morphology data CC BY 4.0. Original work of the Open Scriptures Hebrew Bible, https://hb.openscriptures.org/.');
for(const c of [7,36,37,38,39]) s('lxx'+c,`Isaiah ${c} — Swete’s Septuagint`,'Henry Barclay Swete; digitization/hosting by Eliran Wong','Historic Greek edition','Greek text',`https://biblehub.com/sepd/isaiah/${c}.htm`,'This page gives a Greek text to compare with the Hebrew. Each selected word note shows a form from this chapter.','Greek forms can differ between editions. The app does not list all differences between manuscripts.','Underlying historic Greek text is public domain; Bible Hub digitization/hosting is attributed to Eliran Wong under GPL-3.0; only short quotations are used.');
s('ldsmanual','Isaiah 36–39: historical transition and gospel principles','The Church of Jesus Christ of Latter-day Saints','2003','LDS teaching manual','https://www.churchofjesuschrist.org/study/manual/old-testament-seminary-teacher-resource-manual/the-book-of-isaiah/isaiah-36-39?lang=eng','This manual shows the danger move from Assyria to Babylon. It also teaches about mercy, repentance, suffering, and hope.','This manual gives ideas for Church teachers. It is not separate proof of history. A teaching idea is not always Church doctrine.');
s('ldslesson','Lesson 124: Isaiah 36–41','The Church of Jesus Christ of Latter-day Saints','2014','LDS teaching manual','https://www.churchofjesuschrist.org/study/manual/old-testament-seminary-teacher-manual/introduction-to-the-book-of-isaiah/lesson-124-isaiah-36-41?lang=eng','This lesson asks readers to learn trust in God from Jerusalem’s rescue. It also connects these chapters to Kings.','This lesson teaches faith. It is not separate proof of history.');
s('condie','Some Scriptural Lessons on Leadership','Spencer J. Condie · General Conference','April 1990','LDS conference talk','https://www.churchofjesuschrist.org/study/general-conference/1990/04/some-scriptural-lessons-on-leadership?lang=eng','This talk uses Hezekiah’s changes and trust as an example of good leadership.','The talk draws on Kings and Chronicles. It does not explain every verse in Isaiah. It does not study historical dates.');
s('ldsisaiah','3 Nephi 23: search Isaiah’s words','The Church of Jesus Christ of Latter-day Saints','Scriptural text','LDS scripture','https://www.churchofjesuschrist.org/study/scriptures/bofm/3-ne/23?lang=eng','This Book of Mormon chapter tells readers to search Isaiah’s words with care.','This later scripture invites careful study. It is not proof of any one event in Isaiah.');
s('earth','Natural Earth: geographic base data','Natural Earth contributors','50m physical dataset','Geographic data','https://www.naturalearthdata.com/about/terms-of-use/','This data set gives the coastlines and lakes on the map.','This modern data uses broad shapes. It does not show ancient shores or the borders of kingdoms.','Public domain.');
s('geo','Bible geographic atlas','OpenBible.info','Digital gazetteer','Geographic reference','https://www.openbible.info/geo/','This source helps us place Bible sites on the map.','Some old sites are hard to find. A map point shows the common choice. The app marks places that are not known for sure.','Linked reference; coordinates are rounded to regional precision.');

const passages=[];
function p(id,chapter,start,end,title,summary,year,dateLabel,uncertainty,placeIds,sourceIds,ldsText,ldsIds=['ldslesson']) { passages.push({id,chapter,start,end,title,summary,year,dateLabel,uncertainty,placeIds,sourceIds,lds:{text:ldsText,sourceIds:ldsIds}}); }
p('assyria-arrives',36,1,3,'The Assyrian crisis','In King Hezekiah’s fourteenth year, Sennacherib of Assyria captures Judah’s walled cities. He sends his officer Rabshakeh from Lachish to Jerusalem with a large army. Rabshakeh stops by the water channel of the upper pool. Three of Hezekiah’s officials come out to meet him. Assyrian palace reliefs also show Lachish.',-701,'701 BCE · campaign setting','The campaign took place in 701 BCE. The map connects the cities named in the passage. The exact route is unknown.',['lachish','jerusalem','nineveh'],['web','lachish','met701'],'Read Hezekiah’s crisis as an invitation to trust God while facing a real political danger. Church teaching treats the historical setting as the background for that spiritual question. Judah’s walled cities have fallen (verse 1). What is left for Hezekiah to trust?');
p('war-of-words',36,4,22,'A battle over trust','Rabshakeh asks what Hezekiah trusts. He calls Egypt a broken reed that cuts the hand that leans on it. He says the LORD himself sent Assyria. Judah’s officials ask for Aramaic, but he shouts in the Jews’ language. He offers the people food and a new land if they give up. He says no god has saved a land from Assyria. The people stay silent, as the king ordered.',-701,'701 BCE · narrative setting','Isaiah records these speeches as part of the account. No separate record from the campaign confirms their exact words.',['jerusalem','memphis','samaria','hamath','arpad'],['web'],'The repeated question of whom to trust can be read alongside Hezekiah’s leadership. Condie’s conference talk applies his example to communities choosing change. Rabshakeh asks what Hezekiah trusts (verse 4). Why do the people answer him with silence in verse 21?',['condie','ldslesson']);
p('letter-prayer',37,1,20,'The letter and the prayer','Hezekiah tears his clothes, goes to the LORD’s house, and sends to Isaiah. Isaiah says not to fear: the king of Assyria will hear news and go home. Sennacherib sends a letter that mocks Hezekiah’s God. Hezekiah spreads the letter before the LORD. His prayer admits Assyria’s victories and says the fallen gods were wood and stone. He asks God to save Judah so all kingdoms know the LORD alone is God.',-701,'701 BCE · narrative setting','The passage explains the events through faith in God. It does not provide separate historical proof of how Jerusalem survived.',['jerusalem','libnah','harran'],['web37'],'Hezekiah’s prayer offers a faithful model for turning toward God in distress. This is a devotional reading of the narrative, alongside the evidence discussed in Historical mode. Hezekiah spreads the letter before the LORD (verse 14). What reason does verse 20 give for rescue?');
p('city-survives',37,21,37,'Jerusalem survives','Isaiah sends the LORD’s answer to Hezekiah. Zion laughs at Sennacherib, who has mocked the Holy One of Israel. The LORD says he planned Assyria’s victories long ago. He will turn Assyria back with a hook in its nose. A remnant of Judah will take root again. Isaiah’s account says the LORD’s angel struck 185,000 in the Assyrian camp. Sennacherib returns to Nineveh. Assyrian accounts describe a royal victory.',-701,'701 BCE · main crisis','The sources give different explanations. The app cannot confirm the exact battle route or the number of deaths.',['jerusalem','nineveh'],['web37','rinap','met701'],'LDS teaching reads the city’s preservation as an expression of God’s power to deliver. The remnant image also invites reflection on renewal after devastation. Verse 31 promises a remnant that takes root. What does verse 35 say moves the LORD to defend the city?');
p('sennacherib-end',37,38,38,'A later death closes the story','The chapter ends with Sennacherib’s death in his own land. His sons kill him in the house of his god Nisroch. His son Esar Haddon becomes king. Many years pass between his return home and his death.',-681,'681 BCE · later aftermath','This verse describes a later time. Do not date it to the night or year of the 701 BCE crisis.',['nineveh'],['web37','metchron'],'A faithful reading sees the ending as fulfillment of the earlier prophecy. The timeline shows the years between these events. Sennacherib mocked Judah’s God and dies in his own god’s house (verse 38). What does that ending answer?');
p('illness-sign',38,1,8,'Illness and a sign','Hezekiah is sick and near death. Isaiah tells him to set his house in order. Hezekiah turns to the wall, prays, and weeps. The LORD sends Isaiah back: he has heard, and he adds fifteen years. He also promises to defend the city from Assyria. As a sign, the shadow goes back ten steps on the sundial of Ahaz. Verse 6 shows why chapter order may differ from the order of events.',-701,'Around the Assyrian crisis · date uncertain','The map uses 701 BCE to show the setting. The date of Hezekiah’s illness is uncertain.',['jerusalem'],['web38','anderson'],'The Lord’s promise to hear prayer offers hope in times of need. Hezekiah’s recovery does not promise the same outcome for every illness. Hezekiah turns to the wall and weeps (verses 2–3). What two things does verse 5 say the LORD has done?',['ldsmanual']);
p('song-recovery',38,9,22,'Hezekiah’s song after recovery','Hezekiah writes a poem after he recovers. He thought he would enter Sheol in the middle of his life. His life felt like a tent pulled down and cloth cut from a loom. He moaned like a dove and asked the Lord for help. Then he says God spoke, acted, and put his sins behind his back. Sheol cannot praise God, but the living can. Fathers will tell their children. Isaiah had told them to lay a cake of figs on the boil.',-701,'Hezekiah’s lifetime · exact date unknown','The poem appears in Isaiah 38, but its exact date is unknown. The map shows Jerusalem as its setting.',['jerusalem'],['web38'],'Church teaching uses this passage to discuss suffering, mercy, and forgiveness. The poem offers ideas for reflection. It does not promise physical recovery for everyone. Hezekiah says the living can praise God (verse 19). What does he want fathers to tell children?',['ldsmanual']);
p('babylon-envoys',39,1,8,'Babylon and Judah’s future','The king of Babylon sends letters and a gift after Hezekiah’s sickness. Hezekiah is pleased and shows the envoys all his treasure and weapons. Isaiah asks where the men came from and what they saw. Hezekiah says they came from Babylon and saw everything. Isaiah gives the LORD’s word: all of it will be carried to Babylon. Some of Hezekiah’s own sons will serve in Babylon’s palace. Hezekiah calls the word good, because there will be peace in his days.',-703,'Late eighth century BCE · embassy date debated','The map uses 703 BCE to show the setting. The visit’s exact date is uncertain. Chapter order does not prove the visit followed the 701 BCE crisis. Select 597 or 587/586 BCE to study later events.',['babylon','jerusalem'],['web39','anderson','met701'],'The Church manual reads these chapters as a transition from Assyrian danger to Babylonian captivity. Consider the contrast between present security and responsibility for future generations. Hezekiah calls the word “good” because peace lasts his lifetime (verse 8). Who bears the cost in verse 7?',['ldsmanual']);

const places=[];
function pl(id,name,lat,lng,summary,chapter=36,verse=1,sourceIds=['geo','web']) {places.push({id,name,lat,lng,summary,chapter,verse,sourceIds});}
pl('jerusalem','Jerusalem',31.778,35.235,'Jerusalem was Judah’s royal city and the home of its temple. Isaiah 36–39 tells what happened to King Hezekiah there.',36,2);
pl('lachish','Lachish',31.565,34.849,'Lachish was a strong city in Judah. It was southwest of Jerusalem. Isaiah 36:2 names this city.',36,2,['geo','lachish','web']);
pl('nineveh','Nineveh',36.36,43.15,'Nineveh was a royal city of Assyria, linked with Sennacherib’s palace. Sennacherib goes home to Nineveh in Isaiah 37:37.',37,37,['geo','web37','lachish']);
pl('babylon','Babylon',32.54,44.42,'Babylon was a city and a kingdom. Its king sends letters and a gift to Hezekiah in Isaiah 39. Isaiah says the royal treasures will be carried there.',39,1,['geo','web39']);
pl('samaria','Samaria',32.276,35.195,'Samaria had been the capital of the northern kingdom. In Isaiah 36:19, Rabshakeh names it among the places Assyria beat.',36,19);
pl('hamath','Hamath',35.133,36.75,'Hamath was a city in Syria. Rabshakeh lists it among the kingdoms Assyria beat (Isaiah 36:19).',36,19);
pl('arpad','Arpad',36.467,37.10,'Rabshakeh names Arpad with Hamath in his speech (Isaiah 36:19). Arpad is usually placed at Tell Rifat. The exact spot is not certain.',36,19);
pl('harran','Harran',36.864,39.032,'Sennacherib’s letter names Harran among the places earlier Assyrian kings destroyed (Isaiah 37:12).',37,12,['geo','web37']);
pl('gozan','Gozan',36.83,40.04,'Gozan is usually linked with Guzana / Tell Halaf. Sennacherib’s letter names it among the places earlier Assyrian kings destroyed (Isaiah 37:12).',37,12,['geo','web37']);
pl('libnah','Libnah · approximate',31.63,34.91,'Isaiah 37:8 places the Assyrian king at Libnah after Lachish. Its exact location is uncertain.',37,8,['geo','web37']);
pl('tyre','Tyre',33.27,35.20,'Tyre was a city on the coast. It lay in the region of Assyria’s western campaign.',36,1,['geo','met701']);
pl('sidon','Sidon',33.56,35.37,'Sidon was a Phoenician city on the coast. Historians place it in Assyria’s wider western campaign.',36,1,['geo','met701']);
pl('ashkelon','Ashkelon',31.665,34.548,'Ashkelon was a Philistine city on the coast. Assyria’s western campaign affected it.',36,1,['geo','met701']);
pl('ekron','Ekron',31.778,34.85,'Ekron was a Philistine city. It was part of the campaign and of fights over loyalty to Assyria.',36,1,['geo','met701']);
pl('memphis','Memphis · Egypt',29.849,31.254,'Memphis was a city in Egypt. Isaiah 36:6 does not name it. There Rabshakeh mocks Judah for leaning on Egypt.',36,6);
pl('damascus','Damascus',33.51,36.29,'Damascus was a city in inland Syria.',36,1,['geo']);
pl('carchemish','Carchemish',36.83,38.015,'Carchemish stood at a crossing of the Euphrates River. A later battle there helped Babylon gain power in the west.',39,6,['geo','metchron']);
pl('susa','Susa',32.189,48.257,'Susa was a city east of Babylon, in the Persian world. Isaiah does not describe an event at Susa.',39,6,['geo','metchron']);

const events=[];
function ev(id,year,dateLabel,title,summary,sourceIds,placeIds,chapter=36,verse=1,uncertainty='The year helps place the event in time. Map routes and areas are approximate.') {events.push({id,year,dateLabel,title,summary,sourceIds,placeIds,chapter,verse,uncertainty});}
ev('background',-780,'Early eighth century BCE','Early eighth-century setting','Judah and Israel face the growing power of Assyria. This date shows an earlier setting. It does not mark one event.',['yale','metchron'],['jerusalem','samaria'],1,1,'780 BCE is where the timeline starts. It is not Isaiah’s birth or a campaign.');
ev('northern-fall',-722,'722/721 BCE','The northern kingdom falls','Rabshakeh uses Samaria’s fall as a warning in Isaiah 36:19. Assyria took the city, faced another revolt, and tightened its control.',['metchron','web'],['samaria'],36,19,'722/721 BCE covers several steps of conquest and control. Scholars differ on the date of each step.');
ev('sargon-death',-705,'705 BCE','A new Assyrian king','Sargon II dies, and Sennacherib becomes king of Assyria. Lands under Assyria push back against its rule.',['met701'],['nineveh']);
ev('babylon703',-703,'703 BCE','Babylon challenges Assyria','Sennacherib defeats Merodach-baladan in Babylonia. Isaiah 39:1 names this ruler. He sends letters and a gift to Hezekiah.',['met701'],['babylon'],39,1);
ev('western701',-701,'701 BCE','Sennacherib’s western campaign','The Assyrian army reaches Judah. Isaiah, the royal Assyrian writings, and the Lachish wall carvings each tell of it.',['met701','rinap','lachish'],['lachish','jerusalem']);
ev('lachish-art',-695,'700–692 BCE','Palace reliefs show Lachish','The palace wall carvings show the fall of Lachish for the Assyrian court. Carvers made them after the event.',['lachish'],['nineveh','lachish'],36,2,'The museum dates the reliefs to 700–692 BCE. The timeline shows them at 695 BCE.');
ev('death681',-681,'681 BCE','Sennacherib’s reign ends','Isaiah 37:38 tells of Sennacherib’s death. His sons kill him many years after the invasion.',['web37','metchron'],['nineveh'],37,38);
ev('nineveh612',-612,'612 BCE','Nineveh falls','Nineveh falls, and Assyria grows weak. Some Assyrian forces keep fighting.',['metchron'],['nineveh'],39,6);
ev('carchemish605',-605,'605 BCE','Babylon gains power in the west','The battle at Carchemish helps Babylon gain power in the eastern Mediterranean region.',['livius605'],['carchemish'],39,6);
ev('jerusalem597',-597,'597 BCE','Jerusalem and royal deportation','Babylon captures Jerusalem and takes its king into exile. These later events help explain the warning in Isaiah 39.',['livius605','web39'],['jerusalem','babylon'],39,6);
ev('jerusalem586',-586,'587/586 BCE','Jerusalem and the temple destroyed','Babylon destroys Jerusalem and the temple. This happens long after the Assyrian crisis.',['metchron','yale'],['jerusalem','babylon'],39,6,'Scholars date the destruction to 587 or 586 BCE. The app shows both dates.');
ev('cyrus539',-539,'539 BCE','Persia takes Babylon','Cyrus conquers Babylon. The Cyrus Cylinder says he helped restore worship. It does not mention the return of Judah’s exiles.',['cyrus','yale'],['babylon'],39,6);

const campaigns=[
 {id:'lachish-mission',title:'From Lachish to Jerusalem',start:-702,end:-700,dateLabel:'701 BCE · narrative setting',points:[[31.565,34.849],[31.66,34.98],[31.778,35.235]],summary:'In Isaiah 36:2, the king of Assyria sends Rabshakeh from Lachish to Jerusalem. He comes with a large army.',detail:'Isaiah does not name Rabshakeh’s road. The line does not show where Sennacherib himself went. Assyrian palace reliefs also show Lachish.',uncertainty:'The line connects places in the account. The exact route is unknown.',sourceIds:['web','lachish'],chapter:36,verse:2},
 {id:'west-campaign',title:'The Assyrian campaign in the west',start:-702,end:-700,dateLabel:'701 BCE',points:[[33.56,35.37],[33.27,35.2],[32.2,34.95],[31.665,34.548],[31.778,34.85],[31.565,34.849]],summary:'Assyria’s western campaign affected these places before the army came to Jerusalem.',detail:'Assyrian royal writings tell of attacks on Hezekiah’s walled towns. They call the campaign a royal victory. Palace reliefs show the fall of Lachish. These records help explain Judah’s losses. Isaiah tells how Jerusalem survived. The royal records praise Sennacherib’s power. They do not prove the army went through every place shown.',uncertainty:'The order of stops and the route are approximate.',sourceIds:['met701','rinap'],chapter:36,verse:1},
 {id:'babylon-envoys-route',title:'The Babylonian embassy',start:-710,end:-701,dateLabel:'Late eighth century BCE · exact date debated',points:[[32.54,44.42],[34.3,40.8],[35.3,38.4],[33.51,36.29],[31.778,35.235]],summary:'In Isaiah 39, Babylon’s king sends envoys to Hezekiah with letters and a gift.',detail:'Isaiah 39 does not name the envoys’ road or the year of the visit.',uncertainty:'The line connects the two cities. The travel route and exact date are unknown.',sourceIds:['web39','anderson'],chapter:39,verse:1},
 {id:'exile-horizon',title:'Exile in Babylon',start:-597,end:-539,dateLabel:'597–539 BCE · later events',points:[[31.778,35.235],[33.51,36.29],[35.3,38.4],[34.3,40.8],[32.54,44.42]],summary:'Isaiah 39:6–7 gives a warning. The king’s treasures and some of his sons will go to Babylon. Babylon later took Jerusalem’s king into exile.',detail:'No one road into exile is known. People did not travel the whole time from 597 to 539 BCE.',uncertainty:'The line connects the cities. The exact route into exile is unknown.',sourceIds:['web39','metchron'],chapter:39,verse:6}
];
const regions=[
 {id:'babylonia-early',faction:'babylonia',name:'Land near Babylon · approximate',start:-780,end:-606,points:[[33.6,43.5],[33.7,45.0],[32.6,46.1],[30.8,47.1],[30.5,46.0],[31.4,44.5],[32.5,43.3]],color:'#783951',summary:'This is the land near Babylon and the river lands to its south. Kings from Babylon and Assyria fought to rule it.',uncertainty:'The shape does not show a firm border. Rule changed over time. Sennacherib beat Merodach-baladan in 703 BCE. Babylon became the main power in 605 BCE.',sourceIds:['metchron','met701','web39']},
 {id:'judah',name:'Land of Judah · approximate',start:-780,end:-587,points:[[31.95,34.91],[31.95,35.34],[31.38,35.42],[31.1,35.1],[31.3,34.75]],color:'#79cbd8',summary:'Judah was a land of hills and lowlands. Jerusalem was its royal city.',uncertainty:'The shape does not show a firm border. Rule changed over time.',sourceIds:['geo','web']},
 {id:'philistia',faction:'philistia',name:'Philistine city-states · approximate',start:-780,end:-604,chapterCoverage:[9,11,14,20,23,36],points:[[31.95,34.55],[31.82,34.82],[31.28,34.72],[31.15,34.32],[31.72,34.38]],color:'#a4634f',summary:'Philistia had several city-states on the southern coast. They included Ashdod, Ashkelon, Ekron, Gaza, and Gath.',uncertainty:'The shape is a simple guide. Control changed by city and year. Assyria and Babylon both put pressure on these cities.',sourceIds:['geo','web14','wiki-ekron']},
 {id:'egypt-region',faction:'egypt',name:'Egyptian realm · approximate',start:-780,end:-539,chapterCoverage:[11,19,20,23,27,30,31,36,37],points:[[31.7,29.7],[31.7,32.6],[30.2,32.8],[29.5,31.9],[24,32.1],[24,30.4],[29.4,30.5]],color:'#4f8278',summary:'Egypt controlled the Nile valley and delta. Its armies, horses, and wealth made it seem like a strong ally. Yet its divided rulers made that help unsafe.',uncertainty:'The shape is a simple guide. Egypt’s ruling families and power centers changed during Isaiah’s time. Kushite rulers also governed Egypt for part of this period.',sourceIds:['geo','web19','web30','web31']},
 {id:'cush-region',faction:'cush',name:'Cushite realm · approximate',start:-780,end:-539,chapterCoverage:[11,18,20,37],points:[[24,30.4],[24,33],[18,33.5],[12.5,32.7],[12.5,29.2],[18,30.4]],color:'#7b5f8e',summary:'Cush was a kingdom south of Egypt in Nubia. Kushite kings also ruled Egypt during part of Isaiah’s time.',uncertainty:'The shape is a simple guide. It shows only the northern part of Cush. Control changed over time.',sourceIds:['geo','web18','web20','wiki-taharqa']},
 {id:'assyria',name:'Lands under Assyria · approximate',start:-722,end:-613,points:[[37.5,35.6],[37.5,44.9],[34.0,44.9],[33.0,39.2],[31.4,35.9],[32.3,34.9]],color:'#568cf0',summary:'Assyria ruled some of these lands itself. Other kings ruled the rest for Assyria. They had to pay Assyria.',uncertainty:'Assyria did not rule all these lands in the same way. Its power also changed over time. The shape does not show a firm border for each year.',sourceIds:['metchron','met701']},
 {id:'babylonia',name:'Lands under Babylon · approximate',start:-605,end:-540,points:[[36.8,36.2],[36.6,44.9],[30.5,47.0],[29.9,43.0],[31.0,35.0],[33.2,35.4]],color:'#9284d7',summary:'Babylon ruled these lands after Assyria grew weak.',uncertainty:'The shape does not show a firm border. Rule changed over time.',sourceIds:['metchron']},
 {id:'persian',name:'Lands under Persia · approximate',start:-539,end:-539,points:[[38,35],[38,50],[29,50],[29,35]],color:'#58bcaf',summary:'Persia took control of Babylon in 539 BCE.',uncertainty:'The shape shows only part of the land Cyrus ruled.',sourceIds:['cyrus']}
];
const periods=[{id:'pre',label:'Before Isaiah',start:-780,end:-741,description:'Earlier eighth-century setting'},{id:'isaiah',label:'Isaiah',start:-740,end:-681,description:'Assyria, Judah, and Isaiah’s ministry'},{id:'post',label:'After Isaiah',start:-680,end:-539,description:'Later events in Babylon and Persia'}];
const guides=[
 {id:'crisis',title:'The Assyrian crisis',description:'Follow the Assyrian threat from Lachish to Jerusalem.',steps:[
  {title:'Find the two cities',text:'Find Lachish on the map. Rabshakeh, an Assyrian officer, travels from here to Jerusalem. His exact road is unknown.',chapter:36,verse:2,year:-701,placeId:'lachish',sourceIds:['web','lachish']},
  {title:'Listen to the argument',text:'Rabshakeh mocks Judah’s trust in Egypt and in Hezekiah. What reason does he give against each one?',chapter:36,verse:6,year:-701,placeId:'jerusalem',sourceIds:['web']},
  {title:'The people on the wall',text:'Judah’s officials ask Rabshakeh to speak Aramaic. He shouts to the people on the wall in their own language. Why does he choose that?',chapter:36,verse:11,year:-701,placeId:'jerusalem',sourceIds:['web','oshb']},
  {title:'A threat to move the people',text:'Rabshakeh offers food and a new land if the people give up. Yet he will take them from their home. How does he make giving up sound good?',chapter:36,verse:17,year:-701,placeId:'jerusalem',sourceIds:['web']}
 ]},
 {id:'evidence',title:'Two accounts, one crisis',description:'Compare Isaiah’s account with Assyrian records.',steps:[
  {title:'The palace viewpoint',text:'Look at the palace relief. What does it show about the winning king? What does it leave out?',chapter:36,verse:2,year:-695,placeId:'nineveh',sourceIds:['lachish']},
  {title:'The royal inscription',text:'The Assyrian royal writing calls the campaign a victory for the king. Why was it written? Why was Isaiah’s account written?',chapter:37,verse:18,year:-701,placeId:'jerusalem',sourceIds:['rinap']},
  {title:'How the account ends',text:'Isaiah says the LORD’s angel struck the Assyrian camp and saved Jerusalem. The Assyrian account tells of a royal victory. What does each account want its readers to know?',chapter:37,verse:36,year:-701,placeId:'jerusalem',sourceIds:['web37','met701']},
  {title:'Years between events',text:'The last verse tells of Sennacherib’s death many years later. Two verses side by side can be far apart in time.',chapter:37,verse:38,year:-681,placeId:'nineveh',sourceIds:['web37','metchron']}
 ]},
 {id:'horizon',title:'Babylon and Judah’s future',description:'Study the events before and after Isaiah 39.',steps:[
  {title:'A sick king',text:'Hezekiah is sick in chapter 38. Verse 6 still promises to defend the city from Assyria. So chapter order may differ from the order of events.',chapter:38,verse:6,year:-701,placeId:'jerusalem',sourceIds:['web38','anderson']},
  {title:'Visitors from Babylon',text:'Babylon sends visitors to Hezekiah. Their visit’s exact date is uncertain. The map uses 703 BCE to show the setting.',chapter:39,verse:1,year:-703,placeId:'babylon',sourceIds:['web39']},
  {title:'Jerusalem’s later destruction',text:'Babylon destroys Jerusalem in 587/586 BCE. Isaiah had warned that the palace treasures would go to Babylon. How does the later event fit his warning?',chapter:39,verse:6,year:-586,placeId:'jerusalem',sourceIds:['web39','metchron']},
  {title:'Persia takes Babylon',text:'The timeline ends with Cyrus’s conquest. The Cyrus Cylinder gives a royal account. It does not mention the return of Judah’s exiles.',chapter:39,verse:6,year:-539,placeId:'babylon',sourceIds:['cyrus']}
 ]}
];
const out={sources,passages,events,places,campaigns,regions,words:[],guides,periods,editorial:{status:'We checked the sources. A subject expert has not reviewed the full guide.',periodNote:'These timeline sections help with navigation. They do not set fixed dates for Isaiah’s work or for who wrote each part.',mapNote:'This is a physical reference map. Historical areas and routes use simple shapes. Modern coasts and lakes may differ from ancient ones.'}};
addComeFollowMe(out);
addMcClellan(out);
addGeneralConference(out);
addFullIsaiah(out, JSON.parse(await readFile(new URL('../dist/data/scripture.json', import.meta.url), 'utf8')));
for (const campaign of out.campaigns) campaign.faction = ['lachish-mission', 'west-campaign'].includes(campaign.id) ? 'assyria' : 'babylonia';
addPrismAndHarmony(out);
addAncientRoads(out);
addSourcePreviews(out);
await addChapterGeography(out, JSON.parse(await readFile(new URL('../dist/data/scripture.json', import.meta.url), 'utf8')));
addChapterEnrichment(out, JSON.parse(await readFile(new URL('../dist/data/scripture.json', import.meta.url), 'utf8')));
await writeFile(new URL('../dist/data/content.json',import.meta.url),JSON.stringify(out,null,2));
console.log(`Created ${out.sources.length} sources, ${out.passages.length} passages, ${out.events.length} events, ${out.places.length} places and ${out.guides.length} guides.`);
