import { addSourcePreviews } from './source-previews.mjs';
import { addChapterGeography } from './chapter-geography.mjs';
import { readFile, writeFile } from 'node:fs/promises';
import { addFullIsaiah } from './full-isaiah.mjs';
import { addComeFollowMe } from './come-follow-me.mjs';
import { addMcClellan } from './mcclellan.mjs';
import { addGeneralConference } from './general-conference.mjs';

const sources = [];
function s(id,title,author,year,type,url,summary,limitations,license='Linked reading; original Meridian summary, no article reproduction') { sources.push({id,title,author,year,type,url,summary,limitations,license}); }
s('web','Isaiah 36–39 — World English Bible','World English Bible project','2026 retrieval','Biblical text','https://ebible.org/engwebp/ISA36.htm','The full text of Isaiah 36–39. It describes the Assyrian crisis, Hezekiah’s illness, and visitors from Babylon.','This is an English translation. It records the biblical account. Separate sources are needed to compare its events with other historical evidence.','Public domain; engwebp edition, punctuation preserved; navigation and footnotes excluded from reader.');
for(const c of [37,38,39]) s('web'+c,`Isaiah ${c} — World English Bible`,'World English Bible project','2026 retrieval','Biblical text',`https://ebible.org/engwebp/ISA${c}.htm`,'Read the full chapter, including the publisher’s notes.','Compare the account’s religious message with the separate historical evidence.','Public domain');
s('met701','Sennacherib and Jerusalem','Ira Spar · The Metropolitan Museum of Art','2014','Museum scholarship','https://www.metmuseum.org/exhibitions/listings/2014/assyria-to-iberia/blog/posts/sennacherib-and-jerusalem','Explains the 701 BCE campaign through royal inscriptions, palace reliefs, and the biblical narrative. Useful for comparing Judah’s devastation with Jerusalem’s survival.','The museum brings several sources together. Its explanation for the Assyrian withdrawal remains open to debate.');
s('rinap','Sennacherib: inscription with the Hezekiah passage','Royal Inscriptions of the Neo-Assyrian Period, ORACC','Digital edition','Primary evidence','https://oracc.museum.upenn.edu/rinap/rinap3/Q003945','Provides an edited Assyrian inscription and translation describing attacks on Hezekiah’s fortified settlements.','Parts of this royal account are missing. It promotes the king’s power. Examine its numbers and victory claims with care.');
s('lachish','Sennacherib receives the spoils of Lachish','British Museum · collection 1856,0909.14','Relief dated 700–692 BCE','Primary evidence','https://www.britishmuseum.org/collection/object/W_1856-0909-14_7','The palace relief identifies Lachish and depicts its conquest from the Assyrian court’s viewpoint.','The date of the relief is not the campaign date. Its images celebrate imperial victory; they do not document every detail of Isaiah.');
s('anderson','Isaiah 36–39: rethinking priority and historical reliability','Joel E. Anderson and Pieter M. Venter · HTS 65(1)','2009','Peer-reviewed research','https://www.scielo.org.za/scielo.php?pid=S0259-94222009000100009&script=sci_arttext','Argues that Isaiah’s narrative precedes its Kings parallel and preserves a coherent early interpretation of the crisis. Compares literary repetition and editorial placement.','This is one contested proposal. The authors discuss alternatives, including Kings-first and shared-source explanations.');
s('yale','First Isaiah: historical context and authenticity','Yale Divinity School · Yale Bible Study','Undated','Academic teaching','https://yalebiblestudy.org/courses/first-isaiah/lessons/historical-context-study-guide/','Distinguishes Isaiah of Jerusalem’s setting from later materials in the book and explains the historical importance of Zion and the Davidic monarchy.','A concise historical-critical introduction; not a full argument for every dating judgment.');
s('metchron','Mesopotamia, 1000 BCE–1 CE','The Metropolitan Museum of Art','Undated','Museum scholarship','https://www.metmuseum.org/toah/ht/04/wam.html','An overview of imperial succession from Assyria to Babylonia and Persia, with chronology for the fall of Nineveh and Jerusalem.','Broad chronological framework. Some dates, including Jerusalem’s destruction, are given as ranges; it is not the source for the 605 BCE Carchemish or 597 BCE Jerusalem entries.');
s('livius605','Jerusalem Chronicle (ABC 5)','Livius.org · Jona Lendering','Undated','Ancient chronicle translation','https://www.livius.org/sources/content/mesopotamian-chronicles-content/abc-5-jerusalem-chronicle/','Provides a freely readable translation and context for the Babylonian Chronicle’s 605 BCE Carchemish campaign and 597 BCE capture of Jerusalem.','A secondary web presentation of an ancient chronicle; the tablet is terse and damaged, so it cannot supply a complete narrative of either campaign.');
s('cyrus','The Cyrus Cylinder','British Museum · collection 1880,0617.1941','539 BCE setting','Primary evidence','https://www.britishmuseum.org/collection/object/W_1880-0617-1941','A Babylonian royal inscription presenting Cyrus’s conquest and his restoration of cults.','It does not mention Judah or directly record the return of Judean exiles.');
s('strong','A Concise Dictionary of the Words in the Hebrew Bible','James Strong · Open Scriptures XML edition','1894 / digital edition','Historical lexicon','https://github.com/openscriptures/strongs/blob/master/hebrew/StrongHebrewG.xml','Lists Hebrew dictionary forms and their possible meanings. Use it with the passage to study a word.','This is an older dictionary. Compare its meanings with the passage. A list of meanings alone cannot tell you which one applies.','Source XML declares Public Domain. Only selected headwords and lexical information are used.');
s('oshb','Open Scriptures Hebrew Bible','Open Scriptures contributors / Westminster Leningrad Codex','Digital edition','Hebrew text','https://github.com/openscriptures/morphhb/blob/master/wlc/Isa.xml','Provides the Hebrew text and word identifiers. Meridian uses these to check selected word studies against their verses.','The app checks selected words, not every English–Hebrew match. It shows Hebrew dictionary forms. The forms in the verses can differ.','Hebrew text public domain; lemma/morphology data CC BY 4.0. Original work of the Open Scriptures Hebrew Bible, https://hb.openscriptures.org/.');
for(const c of [36,37,38,39]) s('lxx'+c,`Isaiah ${c} — Swete’s Septuagint`,'Henry Barclay Swete; digitization/hosting by Eliran Wong','Historic Greek edition','Greek text',`https://biblehub.com/sepd/isaiah/${c}.htm`,'Provides a Greek text to compare with the Hebrew. Each selected entry shows a form from this chapter. Other editions can differ.','Greek forms can differ between editions. The app does not list all differences between manuscripts.','Underlying historic Greek text is public domain; Bible Hub digitization/hosting is attributed to Eliran Wong under GPL-3.0; only short quotations are used.');
s('ldsmanual','Isaiah 36–39: historical transition and gospel principles','The Church of Jesus Christ of Latter-day Saints','2003','LDS teaching manual','https://www.churchofjesuschrist.org/study/manual/old-testament-seminary-teacher-resource-manual/the-book-of-isaiah/isaiah-36-39?lang=eng','Presents the shift from Assyrian danger to Babylonian threat and teaching themes of mercy, repentance, suffering, and hope.','This source gives Church teaching suggestions. It is not independent historical evidence. A teaching suggestion does not necessarily state Church doctrine.');
s('ldslesson','Lesson 124: Isaiah 36–41','The Church of Jesus Christ of Latter-day Saints','2014','LDS teaching manual','https://www.churchofjesuschrist.org/study/manual/old-testament-seminary-teacher-manual/introduction-to-the-book-of-isaiah/lesson-124-isaiah-36-41?lang=eng','Invites readers to learn trust in God from the deliverance narrative and connects these chapters to Kings.','Devotional interpretation is identified separately from the historical reconstruction.');
s('condie','Some Scriptural Lessons on Leadership','Spencer J. Condie · General Conference','April 1990','LDS conference talk','https://www.churchofjesuschrist.org/study/general-conference/1990/04/some-scriptural-lessons-on-leadership?lang=eng','Uses Hezekiah’s reforms and trust as an example of leaders helping a community change.','An application of Kings and Chronicles, not a verse-by-verse treatment of Isaiah or a historical dating study.');
s('ldsisaiah','3 Nephi 23: search Isaiah’s words','The Church of Jesus Christ of Latter-day Saints','Scriptural text','LDS scripture','https://www.churchofjesuschrist.org/study/scriptures/bofm/3-ne/23?lang=eng','Provides a Restoration-scripture reason to study Isaiah carefully.','A later scriptural invitation to study Isaiah; not a direct quotation of Isaiah 36–39.');
s('earth','Natural Earth: geographic base data','Natural Earth contributors','50m physical dataset','Geographic data','https://www.naturalearthdata.com/about/terms-of-use/','Provides coastlines and lakes for the local map.','Modern physical reference data at a generalized scale; ancient waterlines and political boundaries are not supplied.','Public domain.');
s('geo','Bible geographic atlas','OpenBible.info','Digital gazetteer','Geographic reference','https://www.openbible.info/geo/','A reference for approximate site identification and coordinates.','Map points represent conventional site identifications at regional scale; uncertain ancient locations are labeled.','Linked reference; coordinates in this pilot rounded to regional precision.');

const passages=[];
function p(id,chapter,start,end,title,summary,year,dateLabel,uncertainty,placeIds,sourceIds,ldsText,ldsIds=['ldslesson']) { passages.push({id,chapter,start,end,title,summary,year,dateLabel,uncertainty,placeIds,sourceIds,lds:{text:ldsText,sourceIds:ldsIds}}); }
p('assyria-arrives',36,1,3,'The Assyrian crisis','Assyria captures Judah’s fortified towns. An Assyrian official then travels from Lachish to confront Jerusalem. Assyrian palace reliefs also show Lachish.',-701,'701 BCE · campaign setting','The campaign took place in 701 BCE. The map connects the cities named in the passage. The exact route is unknown.',['lachish','jerusalem','nineveh'],['web','lachish','met701'],'Read Hezekiah’s crisis as an invitation to trust God while facing a real political danger. Church teaching treats the historical setting as the background for that spiritual question.');
p('war-of-words',36,4,22,'A battle over trust','The Assyrian speaker challenges trust in Egypt, Hezekiah, and Judah’s God. He speaks to the people on the wall. He promises food but also describes moving them to another land.',-701,'701 BCE · narrative setting','Isaiah records these speeches as part of the account. No separate record from the campaign confirms their exact words.',['jerusalem','memphis','samaria','hamath','arpad'],['web'],'The repeated question of whom to trust can be read alongside Hezekiah’s leadership. Condie’s conference talk applies his example to communities choosing change.',['condie','ldslesson']);
p('letter-prayer',37,1,20,'The letter and the prayer','Hezekiah takes the threatening message to the temple. His prayer names Assyria’s victories and declares that Judah’s God is the Creator.',-701,'701 BCE · narrative setting','The passage explains the events through faith in God. It does not provide separate historical proof of how Jerusalem survived.',['jerusalem','libnah','harran'],['web37'],'Hezekiah’s prayer offers a faithful model for turning toward God in distress. This is a devotional reading of the narrative, alongside the evidence discussed in Historical mode.');
p('city-survives',37,21,37,'Jerusalem survives','Isaiah compares the survivors to a plant that takes root again. His account credits God with saving Jerusalem. Assyrian accounts describe a royal victory.',-701,'701 BCE · main crisis','The sources give different explanations. The app cannot confirm the exact battle route or the number of deaths.',['jerusalem','nineveh'],['web37','rinap','met701'],'LDS teaching reads the city’s preservation as an expression of God’s power to deliver. The remnant image also invites reflection on renewal after devastation.');
p('sennacherib-end',37,38,38,'A later death closes the story','The chapter ends with Sennacherib’s death in his own land. Many years pass between his return home and his death.',-681,'681 BCE · later aftermath','This verse should not be dated to the same night or year as the 701 BCE crisis.',['nineveh'],['web37','metchron'],'A faithful reading sees the ending as fulfillment of the earlier prophecy. The timeline shows the years between these events.');
p('illness-sign',38,1,8,'Illness and a sign','Hezekiah becomes ill. God promises to save him and the city. Verse 6 shows why chapter order may differ from the order of events.',-701,'Around the Assyrian crisis · date uncertain','The map uses 701 BCE to show the setting. The date of Hezekiah’s illness is uncertain.',['jerusalem'],['web38','anderson'],'The Lord’s promise to hear prayer offers hope in times of need. Hezekiah’s recovery does not promise the same outcome for every illness.',['ldsmanual']);
p('song-recovery',38,9,22,'Hezekiah’s song after recovery','The poem moves through images of Sheol, a tent, a loom, birds, and the pit. It ends with living people praising God and passing faithfulness to their children.',-701,'Hezekiah’s lifetime · exact date unknown','The poem appears in Isaiah 38, but its exact date is unknown. The map shows Jerusalem as its setting.',['jerusalem'],['web38'],'Church teaching uses this passage to discuss suffering, mercy, and forgiveness. The poem offers ideas for reflection. It does not promise physical recovery for everyone.',['ldsmanual']);
p('babylon-envoys',39,1,8,'Babylon and Judah’s future','Visitors from Babylon meet Hezekiah. Isaiah warns that Babylon will later take the palace wealth and the king’s descendants.',-703,'Late eighth century BCE · embassy date debated','The map uses 703 BCE to show the setting. The visit’s exact date is uncertain. Chapter order does not prove the visit followed the 701 BCE crisis. Select 597 or 587/586 BCE to study later events.',['babylon','jerusalem'],['web39','anderson','met701'],'The Church manual reads these chapters as a transition from Assyrian danger to Babylonian captivity. Consider the contrast between present security and responsibility for future generations.',['ldsmanual']);

const places=[];
function pl(id,name,lat,lng,summary,chapter=36,verse=1,sourceIds=['geo','web']) {places.push({id,name,lat,lng,summary,chapter,verse,sourceIds});}
pl('jerusalem','Jerusalem',31.778,35.235,'Judah’s royal and temple city; the central setting of the confrontation and Hezekiah narratives.',36,2);
pl('lachish','Lachish',31.565,34.849,'A fortified Judahite city named in Isaiah 36:2 and in the Assyrian reliefs. Its position southwest of Jerusalem matters to the narrative.',36,2,['geo','lachish','web']);
pl('nineveh','Nineveh',36.36,43.15,'Assyrian royal center associated with Sennacherib’s palace and the final scene in Isaiah 37.',37,37,['geo','web37','lachish']);
pl('babylon','Babylon',32.54,44.42,'The city and political power named in Isaiah 39; later the destination imagined for the royal treasures.',39,1,['geo','web39']);
pl('samaria','Samaria',32.276,35.195,'The former northern capital named among Assyria’s examples of defeated places in Isaiah 36:19.',36,19);
pl('hamath','Hamath',35.133,36.75,'A Syrian city that the Assyrian speaker lists among defeated kingdoms.',36,19);
pl('arpad','Arpad',36.467,37.10,'Conventionally identified with Tell Rifat; named with Hamath in the speech. The marker is approximate.',36,19);
pl('harran','Harran',36.864,39.032,'Named in the letter as a warning drawn from Assyria’s earlier conquests.',37,12,['geo','web37']);
pl('gozan','Gozan',36.83,40.04,'Usually associated with Guzana / Tell Halaf. The letter names it as an example of imperial conquest.',37,12,['geo','web37']);
pl('libnah','Libnah · approximate',31.63,34.91,'Isaiah 37:8 places the Assyrian king at Libnah after Lachish. Its exact location is uncertain. The marker shows an approximate location.',37,8,['geo','web37']);
pl('tyre','Tyre',33.27,35.20,'A coastal city that helps show the region between Assyria, Judah, and Egypt.',36,1,['geo','met701']);
pl('sidon','Sidon',33.56,35.37,'A Phoenician city in the wider western campaign described in Assyrian historical reconstructions.',36,1,['geo','met701']);
pl('ashkelon','Ashkelon',31.665,34.548,'A Philistine coastal city affected by the western campaign.',36,1,['geo','met701']);
pl('ekron','Ekron',31.778,34.85,'A Philistine city involved in the campaign and disputes about loyalty to Assyria.',36,1,['geo','met701']);
pl('memphis','Memphis · Egypt',29.849,31.254,'Regional reference point for Egypt, whose reliability as an ally is attacked in Isaiah 36:6.',36,6);
pl('damascus','Damascus',33.51,36.29,'Regional orientation point in inland Syria. This marker does not claim that every campaign passed through the city.',36,1,['geo']);
pl('carchemish','Carchemish',36.83,38.015,'Euphrates crossing and later battle setting important to Babylon’s rise in the Levant.',39,6,['geo','metchron']);
pl('susa','Susa',32.189,48.257,'A city east of Babylon that helps show the Persian setting. Isaiah 36–39 does not describe events here.',39,6,['geo','metchron']);

const events=[];
function ev(id,year,dateLabel,title,summary,sourceIds,placeIds,chapter=36,verse=1,uncertainty='The year helps place the event in time. Map routes and areas are approximate.') {events.push({id,year,dateLabel,title,summary,sourceIds,placeIds,chapter,verse,uncertainty});}
ev('background',-780,'Early eighth century BCE','Before the crisis','Judah and Israel face the growing power of Assyria. This date shows the earlier setting. It does not mark one event.',['yale','metchron'],['jerusalem','samaria'],36,1,'780 BCE marks the pilot’s chosen viewing boundary, not Isaiah’s birth or a campaign.');
ev('northern-fall',-722,'722/721 BCE','The northern kingdom falls','The speaker in Isaiah 36 uses Samaria’s defeat as a warning. Assyria took the city, faced another revolt, and strengthened its control.',['metchron','web'],['samaria'],36,19,'722/721 BCE refers to several stages of conquest and control. Scholars differ on the dates of these stages.');
ev('sargon-death',-705,'705 BCE','A new Assyrian king','Sargon II dies and Sennacherib succeeds him. Subject states contest Assyrian power.',['met701'],['nineveh']);
ev('babylon703',-703,'703 BCE','Babylon challenges Assyria','Sennacherib defeats Merodach-baladan in Babylonia, providing context for the ruler named in Isaiah 39.',['met701'],['babylon'],39,1);
ev('western701',-701,'701 BCE','Sennacherib’s western campaign','The Assyrian campaign reaches Judah. Compare the narrative, the royal inscriptions, and the Lachish reliefs.',['met701','rinap','lachish'],['lachish','jerusalem']);
ev('lachish-art',-695,'700–692 BCE','Palace reliefs show Lachish','The palace reliefs present the conquest for an Assyrian royal audience. The artifact was made after the event it depicts.',['lachish'],['nineveh','lachish'],36,2,'695 BCE is a display position within the museum’s dating range of 700–692 BCE.');
ev('death681',-681,'681 BCE','Sennacherib’s reign ends','The later death at the end of Isaiah 37 extends the narrative beyond the invasion year.',['web37','metchron'],['nineveh'],37,38);
ev('nineveh612',-612,'612 BCE','Nineveh falls','The fall of Nineveh weakens Assyrian power. Some Assyrian forces continue to resist.',['metchron'],['nineveh'],39,6);
ev('carchemish605',-605,'605 BCE','Babylon gains power in the west','The battle at Carchemish helps Babylon gain power in the eastern Mediterranean region.',['livius605'],['carchemish'],39,6);
ev('jerusalem597',-597,'597 BCE','Jerusalem and royal deportation','Babylon captures Jerusalem and takes its king into exile. These later events help explain the warning in Isaiah 39.',['livius605','web39'],['jerusalem','babylon'],39,6);
ev('jerusalem586',-586,'587/586 BCE','Jerusalem and the temple destroyed','Babylon destroys Jerusalem and the temple. This event occurs long after the Assyrian crisis.',['metchron','yale'],['jerusalem','babylon'],39,6,'Scholars date the destruction to 587 or 586 BCE. The app shows both dates.');
ev('cyrus539',-539,'539 BCE','Persia takes Babylon','Cyrus conquers Babylon. The Cyrus Cylinder describes his support for restoring worship. It does not mention the return of Judah’s exiles.',['cyrus','yale'],['babylon'],39,6);

const campaigns=[
 {id:'lachish-mission',title:'From Lachish to Jerusalem',start:-702,end:-700,dateLabel:'701 BCE · narrative setting',points:[[31.565,34.849],[31.66,34.98],[31.778,35.235]],summary:'Isaiah 36:2 sends the Assyrian representative from Lachish to Jerusalem. The connection brings the campaign to the city’s walls.',detail:'The line connects Lachish and Jerusalem. The passage does not establish the official’s exact road or travel time. It does not trace Sennacherib’s movements. Compare the chapter with the Assyrian reliefs of Lachish.',uncertainty:'The line connects places in the account. The exact route is unknown.',sourceIds:['web','lachish'],chapter:36,verse:2},
 {id:'west-campaign',title:'The Assyrian campaign in the west',start:-702,end:-700,dateLabel:'701 BCE',points:[[33.56,35.37],[33.27,35.2],[32.2,34.95],[31.665,34.548],[31.778,34.85],[31.565,34.849]],summary:'A regional view of places affected by the western campaign before the confrontation at Jerusalem.',detail:'The royal account describes victories and defeated rulers. The map connects places to show the region. It does not confirm travel through every stop.',uncertainty:'The order of stops and the route are approximate.',sourceIds:['met701','rinap'],chapter:36,verse:1},
 {id:'babylon-envoys-route',title:'The Babylonian embassy',start:-710,end:-701,dateLabel:'Late eighth century BCE · exact date debated',points:[[32.54,44.42],[34.3,40.8],[35.3,38.4],[33.51,36.29],[31.778,35.235]],summary:'Isaiah 39 links Babylonian visitors with Hezekiah’s court.',detail:'The curve connects Babylon and Jerusalem through the north. The passage does not establish this route or the visit’s exact year.',uncertainty:'The line connects the two cities. The travel route and exact date are unknown.',sourceIds:['web39','anderson'],chapter:39,verse:1},
 {id:'exile-horizon',title:'Exile in Babylon',start:-597,end:-539,dateLabel:'597–539 BCE · later events',points:[[31.778,35.235],[33.51,36.29],[35.3,38.4],[34.3,40.8],[32.54,44.42]],summary:'Compare Jerusalem and Babylon to study the later events described in Isaiah 39.',detail:'The map connects Jerusalem and Babylon. The line does not show one confirmed route into exile. People did not travel continuously throughout this period.',uncertainty:'The line connects the cities. The exact route into exile is unknown.',sourceIds:['web39','metchron'],chapter:39,verse:6}
];
const regions=[
 {id:'babylonia-early',faction:'babylonia',name:'Babylonia · approximate regional influence',start:-780,end:-606,points:[[33.6,43.5],[33.7,45.0],[32.6,46.1],[30.8,47.1],[30.5,46.0],[31.4,44.5],[32.5,43.3]],color:'#783951',summary:'The shaded area marks Babylonia around Babylon and the southern river plains. Local rulers and Assyrian kings contested power here.',uncertainty:'This shape provides regional context, not exact borders or continuous independent rule. Sennacherib defeated Merodach-baladan in 703 BCE. The later empire appears from 605 BCE.',sourceIds:['metchron','met701','web39']},
 {id:'judah',name:'Judah · regional focus',start:-780,end:-587,points:[[31.95,34.91],[31.95,35.34],[31.38,35.42],[31.1,35.1],[31.3,34.75]],color:'#79cbd8',summary:'The shaded area shows Judah’s hill country and nearby lowlands.',uncertainty:'The area is approximate. Borders and local control varied.',sourceIds:['geo','web']},
 {id:'assyria',name:'Assyrian influence · approximate',start:-722,end:-613,points:[[37.5,35.6],[37.5,44.9],[34.0,44.9],[33.0,39.2],[31.4,35.9],[32.3,34.9]],color:'#568cf0',summary:'The shaded area shows approximate Assyrian influence. Assyria governed some areas directly. Other rulers paid tribute.',uncertainty:'The area of influence changed over time. The shape does not show exact yearly borders or equal control in all areas.',sourceIds:['metchron','met701']},
 {id:'babylonia',name:'Babylonian influence · approximate',start:-605,end:-540,points:[[36.8,36.2],[36.6,44.9],[30.5,47.0],[29.9,43.0],[31.0,35.0],[33.2,35.4]],color:'#9284d7',summary:'The shaded area shows approximate Babylonian influence after the Assyrian crisis.',uncertainty:'The area of influence is approximate. Select the area to see its sources.',sourceIds:['metchron']},
 {id:'persian',name:'Persian transition · regional focus',start:-539,end:-539,points:[[38,35],[38,50],[29,50],[29,35]],color:'#58bcaf',summary:'The final frame marks the transfer of Babylon to Persian rule.',uncertainty:'Regional focus only; not the complete borders of Cyrus’s empire.',sourceIds:['cyrus']}
];
const periods=[{id:'pre',label:'Before Isaiah',start:-780,end:-741,description:'Before the events in Isaiah 36–39'},{id:'isaiah',label:'Isaiah',start:-740,end:-681,description:'Assyria, Judah, and Hezekiah'},{id:'post',label:'After Isaiah',start:-680,end:-539,description:'Later events in Babylon and Persia'}];
const guides=[
 {id:'crisis',title:'The Assyrian crisis',description:'Follow the Assyrian threat from Lachish to Jerusalem.',steps:[
  {title:'Locate the two cities',text:'Find Lachish on the map. An Assyrian official travels from here to Jerusalem. The line connects the cities; the exact route is unknown.',chapter:36,verse:2,year:-701,placeId:'lachish',sourceIds:['web','lachish']},
  {title:'Listen to the argument',text:'The speaker challenges trust in Egypt and Hezekiah. How does he use these places to support his argument?',chapter:36,verse:6,year:-701,placeId:'jerusalem',sourceIds:['web']},
  {title:'A public audience',text:'The officials request Aramaic. The speaker addresses the people on the wall in their own language. Why does his choice matter?',chapter:36,verse:11,year:-701,placeId:'jerusalem',sourceIds:['web','oshb']},
  {title:'A threat to move the people',text:'Compare the offer of food and land with the promised removal to another land. How does the speech make submission sound attractive?',chapter:36,verse:17,year:-701,placeId:'jerusalem',sourceIds:['web']}
 ]},
 {id:'evidence',title:'Two accounts, one crisis',description:'Compare Isaiah’s account with Assyrian records.',steps:[
  {title:'The palace viewpoint',text:'What does this image emphasize about the victorious king? What does it leave out?',chapter:36,verse:2,year:-695,placeId:'nineveh',sourceIds:['lachish']},
  {title:'The royal inscription',text:'The Assyrian inscription presents the campaign as a royal victory. Compare its purpose with the biblical account.',chapter:37,verse:18,year:-701,placeId:'jerusalem',sourceIds:['rinap']},
  {title:'How the account ends',text:'Isaiah credits God with saving Jerusalem. Compare this explanation with the Assyrian account. Consider the purpose and limits of each source.',chapter:37,verse:36,year:-701,placeId:'jerusalem',sourceIds:['web37','met701']},
  {title:'Years between events',text:'The final verse describes a death many years later. Consecutive verses can describe events that are far apart in time.',chapter:37,verse:38,year:-681,placeId:'nineveh',sourceIds:['web37','metchron']}
 ]},
 {id:'horizon',title:'Babylon and Judah’s future',description:'Study the events before and after Isaiah 39.',steps:[
  {title:'A vulnerable king',text:'Chapter 38 describes Hezekiah’s illness and a promise to defend Jerusalem. Chapter order alone does not establish the order of these events.',chapter:38,verse:6,year:-701,placeId:'jerusalem',sourceIds:['web38','anderson']},
  {title:'Visitors from Babylon',text:'Babylon sends visitors to Hezekiah. Their visit’s exact date is uncertain. The map uses 703 BCE to show the setting.',chapter:39,verse:1,year:-703,placeId:'babylon',sourceIds:['web39']},
  {title:'Jerusalem’s later destruction',text:'The timeline shows Jerusalem’s destruction in 587/586 BCE. Compare Isaiah’s warning about the palace treasures with this later event.',chapter:39,verse:6,year:-586,placeId:'jerusalem',sourceIds:['web39','metchron']},
  {title:'Persia takes Babylon',text:'The timeline ends with Cyrus’s conquest. The Cyrus Cylinder gives a royal account. It does not mention the return of Judah’s exiles.',chapter:39,verse:6,year:-539,placeId:'babylon',sourceIds:['cyrus']}
 ]}
];
const out={sources,passages,events,places,campaigns,regions,words:[],guides,periods,editorial:{status:'Source-checked pilot; not independently reviewed by a specialist',periodNote:'These are editorial navigation windows for the pilot, not boundaries of authorship or fixed dates for Isaiah’s ministry.',mapNote:'Physical reference map; historical areas and routes are schematic. Modern coastlines and lakes may differ from ancient ones.'}};
addComeFollowMe(out);
addMcClellan(out);
addGeneralConference(out);
addFullIsaiah(out, JSON.parse(await readFile(new URL('../dist/data/scripture.json', import.meta.url), 'utf8')));
for (const campaign of out.campaigns) campaign.faction = ['lachish-mission', 'west-campaign'].includes(campaign.id) ? 'assyria' : 'babylonia';
addSourcePreviews(out);
await addChapterGeography(out, JSON.parse(await readFile(new URL('../dist/data/scripture.json', import.meta.url), 'utf8')));
await writeFile(new URL('../dist/data/content.json',import.meta.url),JSON.stringify(out,null,2));
console.log(`Created ${sources.length} sources, ${passages.length} passages, ${events.length} events, ${places.length} places and ${guides.length} guides.`);
