import { addSourcePreviews } from './source-previews.mjs';
import { addChapterGeography } from './chapter-geography.mjs';
import { readFile, writeFile } from 'node:fs/promises';
import { addFullIsaiah } from './full-isaiah.mjs';
import { addComeFollowMe } from './come-follow-me.mjs';
import { addMcClellan } from './mcclellan.mjs';
import { addGeneralConference } from './general-conference.mjs';
import { addPrismAndHarmony } from './prism-and-harmony.mjs';
import { addChapterEnrichment } from './chapter-enrichment.mjs';
import { addAncientRoads } from './ancient-roads.mjs';

const sources = [];
function s(id,title,author,year,type,url,summary,limitations,license='Linked reading; original study guide summary, no article reproduction') { sources.push({id,title,author,year,type,url,summary,limitations,license}); }
s('web','Isaiah — World English Bible','World English Bible project','2026 retrieval','Biblical text','https://ebible.org/engwebp/ISA01.htm','The complete book of Isaiah in the public-domain World English Bible. Chapter notes distinguish the biblical account from historical evidence.','This is an English translation. It records the biblical account. Separate sources are needed to compare its events with other historical evidence.','Public domain; engwebp edition, punctuation preserved; navigation and footnotes excluded from reader.');
for(const c of [37,38,39]) s('web'+c,`Isaiah ${c} — World English Bible`,'World English Bible project','2026 retrieval','Biblical text',`https://ebible.org/engwebp/ISA${c}.htm`,'Read the full chapter, including the publisher’s notes.','Compare the account’s religious message with the separate historical evidence.','Public domain');
s('met701','Sennacherib and Jerusalem','Ira Spar · The Metropolitan Museum of Art','2014','Museum scholarship','https://www.metmuseum.org/exhibitions/listings/2014/assyria-to-iberia/blog/posts/sennacherib-and-jerusalem','The museum looks at old writings, wall pictures, and the Bible. These sources tell about the war in 701 BCE. Judah lost many towns, but Jerusalem lived.','The museum joins several sources. We still do not know why Assyria left.');
s('rinap','Sennacherib: inscription with the Hezekiah passage','Royal Inscriptions of the Neo-Assyrian Period, ORACC','Digital edition','Primary evidence','https://oracc.museum.upenn.edu/rinap/rinap3/Q003945','Provides an edited Assyrian inscription and translation describing attacks on Hezekiah’s fortified settlements.','Parts of this royal account are missing. It promotes the king’s power. Examine its numbers and victory claims with care.');
s('lachish','Sennacherib receives the spoils of Lachish','British Museum · collection 1856,0909.14','Relief dated 700–692 BCE','Primary evidence','https://www.britishmuseum.org/collection/object/W_1856-0909-14_7','The palace relief identifies Lachish and depicts its conquest from the Assyrian court’s viewpoint.','The date of the relief is not the campaign date. Its images celebrate imperial victory; they do not document every detail of Isaiah.');
s('anderson','Isaiah 36–39: rethinking priority and historical reliability','Joel E. Anderson and Pieter M. Venter · HTS 65(1)','2009','Peer-reviewed research','https://www.scielo.org.za/scielo.php?pid=S0259-94222009000100009&script=sci_arttext','The writers compare Isaiah with the same story in Kings. They think Isaiah’s form came first. They study words that repeat and where the story was placed.','Other experts do not agree. Kings may have come first. Both books may also use an older source.');
s('yale','First Isaiah: historical context and authenticity','Yale Divinity School · Yale Bible Study','Undated','Academic teaching','https://yalebiblestudy.org/courses/first-isaiah/lessons/historical-context-study-guide/','This lesson tells about Isaiah’s time. It also tells why Zion and David’s royal family mattered. Some parts of the book may come from later times.','This is a short lesson. It does not give every reason for each date.');
s('metchron','Mesopotamia, 1000 BCE–1 CE','The Metropolitan Museum of Art','Undated','Museum scholarship','https://www.metmuseum.org/toah/ht/04/wam.html','This page shows when three empires ruled. They were Assyria, Babylon, and Persia. It also gives dates for the falls of Nineveh and Jerusalem.','This is a wide view of time. Some dates are ranges. Other sources give the dates for Carchemish and the first fall of Jerusalem.');
s('livius605','Jerusalem Chronicle (ABC 5)','Livius.org · Jona Lendering','Undated','Ancient chronicle translation','https://www.livius.org/sources/content/mesopotamian-chronicles-content/abc-5-jerusalem-chronicle/','Gives a free translation of the Babylonian Chronicle. It covers the 605 BCE Carchemish campaign. It also covers the 597 BCE capture of Jerusalem.','This web page presents an ancient record. The tablet is brief and damaged. It cannot give a complete account of either campaign.');
s('cyrus','The Cyrus Cylinder','British Museum · collection 1880,0617.1941','539 BCE setting','Primary evidence','https://www.britishmuseum.org/collection/object/W_1880-0617.1941','Cyrus had this royal message written on clay. It tells how he took Babylon. It also says he gave holy places back to some people.','The message does not name Judah. It does not say that people from Judah went home.');
s('strong','A Concise Dictionary of the Words in the Hebrew Bible','James Strong · Open Scriptures XML edition','1894 / digital edition','Historical lexicon','https://github.com/openscriptures/strongs','Lists Hebrew dictionary forms and their possible meanings. Use it with the passage to study a word.','This is an older dictionary. Compare its meanings with the passage. A list of meanings alone cannot show which one applies. The link opens the project page. The XML dictionary is too large for GitHub’s normal preview.','Source XML declares Public Domain. Only selected headwords and lexical information are used.');
s('oshb','Open Scriptures Hebrew Bible','Open Scriptures contributors / Westminster Leningrad Codex','Digital edition','Hebrew text','https://hb.openscriptures.org/','Provides the Hebrew text and word identifiers. This study guide uses these to check selected word studies against their verses.','The app checks selected words, not every English–Hebrew match. It shows Hebrew dictionary forms. The forms in the verses can differ. The link opens the project overview instead of the oversized Isaiah XML file.','Hebrew text public domain; lemma/morphology data CC BY 4.0. Original work of the Open Scriptures Hebrew Bible, https://hb.openscriptures.org/.');
for(const c of [7,36,37,38,39]) s('lxx'+c,`Isaiah ${c} — Swete’s Septuagint`,'Henry Barclay Swete; digitization/hosting by Eliran Wong','Historic Greek edition','Greek text',`https://biblehub.com/sepd/isaiah/${c}.htm`,'Provides a Greek text to compare with the Hebrew. Each selected entry shows a form from this chapter. Other editions can differ.','Greek forms can differ between editions. The app does not list all differences between manuscripts.','Underlying historic Greek text is public domain; Bible Hub digitization/hosting is attributed to Eliran Wong under GPL-3.0; only short quotations are used.');
s('ldsmanual','Isaiah 36–39: historical transition and gospel principles','The Church of Jesus Christ of Latter-day Saints','2003','LDS teaching manual','https://www.churchofjesuschrist.org/study/manual/old-testament-seminary-teacher-resource-manual/the-book-of-isaiah/isaiah-36-39?lang=eng','Shows the change from Assyrian danger to Babylonian danger. It also teaches about mercy, repentance, suffering, and hope.','This source gives Church teaching suggestions. It is not independent historical evidence. A teaching suggestion does not necessarily state Church doctrine.');
s('ldslesson','Lesson 124: Isaiah 36–41','The Church of Jesus Christ of Latter-day Saints','2014','LDS teaching manual','https://www.churchofjesuschrist.org/study/manual/old-testament-seminary-teacher-manual/introduction-to-the-book-of-isaiah/lesson-124-isaiah-36-41?lang=eng','Invites readers to learn trust in God from the rescue account. It also connects these chapters to Kings.','The app keeps this faith-based reading separate from its history notes.');
s('condie','Some Scriptural Lessons on Leadership','Spencer J. Condie · General Conference','April 1990','LDS conference talk','https://www.churchofjesuschrist.org/study/general-conference/1990/04/some-scriptural-lessons-on-leadership?lang=eng','Uses Hezekiah’s changes and trust as an example of good leadership.','This source applies Kings and Chronicles. It does not explain every verse in Isaiah. It is not a study of historical dates.');
s('ldsisaiah','3 Nephi 23: search Isaiah’s words','The Church of Jesus Christ of Latter-day Saints','Scriptural text','LDS scripture','https://www.churchofjesuschrist.org/study/scriptures/bofm/3-ne/23?lang=eng','Provides a Restoration-scripture reason to study Isaiah carefully.','This later scriptural invitation supports careful study. It is not historical evidence for a specific event in Isaiah.');
s('earth','Natural Earth: geographic base data','Natural Earth contributors','50m physical dataset','Geographic data','https://www.naturalearthdata.com/about/terms-of-use/','Provides coastlines and lakes for the local map.','This modern map uses broad shapes. It does not show ancient waterlines or political borders.','Public domain.');
s('geo','Bible geographic atlas','OpenBible.info','Digital gazetteer','Geographic reference','https://www.openbible.info/geo/','This source helps us place Bible sites on the map.','Some old sites are hard to find. A map point shows the common choice. The app marks places that are not known for sure.','Linked reference; coordinates are rounded to regional precision.');

const passages=[];
function p(id,chapter,start,end,title,summary,year,dateLabel,uncertainty,placeIds,sourceIds,ldsText,ldsIds=['ldslesson']) { passages.push({id,chapter,start,end,title,summary,year,dateLabel,uncertainty,placeIds,sourceIds,lds:{text:ldsText,sourceIds:ldsIds}}); }
p('assyria-arrives',36,1,3,'The Assyrian crisis','In King Hezekiah’s fourteenth year, Sennacherib of Assyria captures Judah’s walled cities. He sends his officer Rabshakeh from Lachish to Jerusalem with a large army. Rabshakeh stops by the water channel of the upper pool. Three of Hezekiah’s officials come out to meet him. Assyrian palace reliefs also show Lachish.',-701,'701 BCE · campaign setting','The campaign took place in 701 BCE. The map connects the cities named in the passage. The exact route is unknown.',['lachish','jerusalem','nineveh'],['web','lachish','met701'],'Read Hezekiah’s crisis as an invitation to trust God while facing a real political danger. Church teaching treats the historical setting as the background for that spiritual question. Judah’s walled cities have fallen (verse 1). What is left for Hezekiah to trust?');
p('war-of-words',36,4,22,'A battle over trust','Rabshakeh asks what Hezekiah trusts. He calls Egypt a broken reed that cuts the hand that leans on it. He says the LORD himself sent Assyria. Judah’s officials ask for Aramaic, but he shouts in the Jews’ language. He offers the people food and a new land if they give up. He says no god has saved a land from Assyria. The people stay silent, as the king ordered.',-701,'701 BCE · narrative setting','Isaiah records these speeches as part of the account. No separate record from the campaign confirms their exact words.',['jerusalem','memphis','samaria','hamath','arpad'],['web'],'The repeated question of whom to trust can be read alongside Hezekiah’s leadership. Condie’s conference talk applies his example to communities choosing change. Rabshakeh asks what Hezekiah trusts (verse 4). Why do the people answer him with silence in verse 21?',['condie','ldslesson']);
p('letter-prayer',37,1,20,'The letter and the prayer','Hezekiah tears his clothes, goes to the LORD’s house, and sends to Isaiah. Isaiah says not to fear: the king of Assyria will hear news and go home. Sennacherib sends a letter that mocks Hezekiah’s God. Hezekiah spreads the letter before the LORD. His prayer admits Assyria’s victories and says the fallen gods were wood and stone. He asks God to save Judah so all kingdoms know the LORD alone is God.',-701,'701 BCE · narrative setting','The passage explains the events through faith in God. It does not provide separate historical proof of how Jerusalem survived.',['jerusalem','libnah','harran'],['web37'],'Hezekiah’s prayer offers a faithful model for turning toward God in distress. This is a devotional reading of the narrative, alongside the evidence discussed in Historical mode. Hezekiah spreads the letter before the LORD (verse 14). What reason does verse 20 give for rescue?');
p('city-survives',37,21,37,'Jerusalem survives','Isaiah sends the LORD’s answer to Hezekiah. Zion laughs at Sennacherib, who has mocked the Holy One of Israel. The LORD says he planned Assyria’s victories long ago. He will turn Assyria back with a hook in its nose. A remnant of Judah will take root again. Isaiah’s account says the LORD’s angel struck 185,000 in the Assyrian camp. Sennacherib returns to Nineveh. Assyrian accounts describe a royal victory.',-701,'701 BCE · main crisis','The sources give different explanations. The app cannot confirm the exact battle route or the number of deaths.',['jerusalem','nineveh'],['web37','rinap','met701'],'LDS teaching reads the city’s preservation as an expression of God’s power to deliver. The remnant image also invites reflection on renewal after devastation. Verse 31 promises a remnant that takes root. What does verse 35 say moves the LORD to defend the city?');
p('sennacherib-end',37,38,38,'A later death closes the story','The chapter ends with Sennacherib’s death in his own land. His sons kill him in the house of his god Nisroch. His son Esar Haddon becomes king. Many years pass between his return home and his death.',-681,'681 BCE · later aftermath','This verse describes a later time. Do not date it to the night or year of the 701 BCE crisis.',['nineveh'],['web37','metchron'],'A faithful reading sees the ending as fulfillment of the earlier prophecy. The timeline shows the years between these events. Sennacherib mocked Judah’s God and dies in his own god’s house (verse 38). What does that ending answer?');
p('illness-sign',38,1,8,'Illness and a sign','Hezekiah is sick and near death. Isaiah tells him to set his house in order. Hezekiah turns to the wall, prays, and weeps. The LORD sends Isaiah back: he has heard, and he adds fifteen years. He also promises to defend the city from Assyria. As a sign, the shadow goes back ten steps on the sundial of Ahaz. Verse 6 shows why chapter order may differ from the order of events.',-701,'Around the Assyrian crisis · date uncertain','The map uses 701 BCE to show the setting. The date of Hezekiah’s illness is uncertain.',['jerusalem'],['web38','anderson'],'The Lord’s promise to hear prayer offers hope in times of need. Hezekiah’s recovery does not promise the same outcome for every illness. Hezekiah turns to the wall and weeps (verses 2–3). What two things does verse 5 say the LORD has done?',['ldsmanual']);
p('song-recovery',38,9,22,'Hezekiah’s song after recovery','Hezekiah writes a poem after he recovers. He thought he would enter Sheol in the middle of his life. His life felt like a tent pulled down and cloth cut from a loom. He moaned like a dove and asked the Lord for help. Then he says God spoke, acted, and put his sins behind his back. Sheol cannot praise God, but the living can. Fathers will tell their children. Isaiah had told them to lay a cake of figs on the boil.',-701,'Hezekiah’s lifetime · exact date unknown','The poem appears in Isaiah 38, but its exact date is unknown. The map shows Jerusalem as its setting.',['jerusalem'],['web38'],'Church teaching uses this passage to discuss suffering, mercy, and forgiveness. The poem offers ideas for reflection. It does not promise physical recovery for everyone. Hezekiah says the living can praise God (verse 19). What does he want fathers to tell children?',['ldsmanual']);
p('babylon-envoys',39,1,8,'Babylon and Judah’s future','The king of Babylon sends letters and a gift after Hezekiah’s sickness. Hezekiah is pleased and shows the envoys all his treasure and weapons. Isaiah asks where the men came from and what they saw. Hezekiah says they came from Babylon and saw everything. Isaiah gives the LORD’s word: all of it will be carried to Babylon. Some of Hezekiah’s own sons will serve in Babylon’s palace. Hezekiah calls the word good, because there will be peace in his days.',-703,'Late eighth century BCE · embassy date debated','The map uses 703 BCE to show the setting. The visit’s exact date is uncertain. Chapter order does not prove the visit followed the 701 BCE crisis. Select 597 or 587/586 BCE to study later events.',['babylon','jerusalem'],['web39','anderson','met701'],'The Church manual reads these chapters as a transition from Assyrian danger to Babylonian captivity. Consider the contrast between present security and responsibility for future generations. Hezekiah calls the word “good” because peace lasts his lifetime (verse 8). Who bears the cost in verse 7?',['ldsmanual']);

const places=[];
function pl(id,name,lat,lng,summary,chapter=36,verse=1,sourceIds=['geo','web']) {places.push({id,name,lat,lng,summary,chapter,verse,sourceIds});}
pl('jerusalem','Jerusalem',31.778,35.235,'Judah’s royal and temple city; the central setting of the confrontation and Hezekiah narratives.',36,2);
pl('lachish','Lachish',31.565,34.849,'Lachish was a strong city in Judah. It was southwest of Jerusalem. Isaiah 36:2 names this city.',36,2,['geo','lachish','web']);
pl('nineveh','Nineveh',36.36,43.15,'Assyrian royal center associated with Sennacherib’s palace and the final scene in Isaiah 37.',37,37,['geo','web37','lachish']);
pl('babylon','Babylon',32.54,44.42,'The city and political power named in Isaiah 39; later the destination imagined for the royal treasures.',39,1,['geo','web39']);
pl('samaria','Samaria',32.276,35.195,'The former northern capital named among Assyria’s examples of defeated places in Isaiah 36:19.',36,19);
pl('hamath','Hamath',35.133,36.75,'A Syrian city that the Assyrian speaker lists among defeated kingdoms.',36,19);
pl('arpad','Arpad',36.467,37.10,'Conventionally identified with Tell Rifat; named with Hamath in the speech. The marker is approximate.',36,19);
pl('harran','Harran',36.864,39.032,'Named in the letter as a warning drawn from Assyria’s earlier conquests.',37,12,['geo','web37']);
pl('gozan','Gozan',36.83,40.04,'Usually associated with Guzana / Tell Halaf. The letter names it as an example of imperial conquest.',37,12,['geo','web37']);
pl('libnah','Libnah · approximate',31.63,34.91,'Isaiah 37:8 places the Assyrian king at Libnah after Lachish. Its exact location is uncertain. The marker shows an approximate location.',37,8,['geo','web37']);
pl('tyre','Tyre',33.27,35.20,'A coastal city that helps show the region between Assyria, Judah, and Egypt.',36,1,['geo','met701']);
pl('sidon','Sidon',33.56,35.37,'A Phoenician city in the wider western campaign described in Assyrian historical reconstructions.',36,1,['geo','met701']);
pl('ashkelon','Ashkelon',31.665,34.548,'A Philistine coastal city affected by the western campaign.',36,1,['geo','met701']);
pl('ekron','Ekron',31.778,34.85,'A Philistine city involved in the campaign and disputes about loyalty to Assyria.',36,1,['geo','met701']);
pl('memphis','Memphis · Egypt',29.849,31.254,'Regional reference point for Egypt, whose reliability as an ally is attacked in Isaiah 36:6.',36,6);
pl('damascus','Damascus',33.51,36.29,'Regional orientation point in inland Syria. This marker does not claim that every campaign passed through the city.',36,1,['geo']);
pl('carchemish','Carchemish',36.83,38.015,'Euphrates crossing and later battle setting important to Babylon’s rise in the Levant.',39,6,['geo','metchron']);
pl('susa','Susa',32.189,48.257,'A city east of Babylon that helps show the Persian setting. Isaiah does not describe an event at Susa.',39,6,['geo','metchron']);

const events=[];
function ev(id,year,dateLabel,title,summary,sourceIds,placeIds,chapter=36,verse=1,uncertainty='The year helps place the event in time. Map routes and areas are approximate.') {events.push({id,year,dateLabel,title,summary,sourceIds,placeIds,chapter,verse,uncertainty});}
ev('background',-780,'Early eighth century BCE','Early eighth-century setting','Judah and Israel face the growing power of Assyria. This date shows an earlier setting. It does not mark one event.',['yale','metchron'],['jerusalem','samaria'],1,1,'780 BCE marks the timeline’s viewing boundary, not Isaiah’s birth or a campaign.');
ev('northern-fall',-722,'722/721 BCE','The northern kingdom falls','The speaker in Isaiah 36 uses Samaria’s defeat as a warning. Assyria took the city, faced another revolt, and strengthened its control.',['metchron','web'],['samaria'],36,19,'722/721 BCE refers to several stages of conquest and control. Scholars differ on the dates of these stages.');
ev('sargon-death',-705,'705 BCE','A new Assyrian king','Sargon II dies and Sennacherib succeeds him. Subject states contest Assyrian power.',['met701'],['nineveh']);
ev('babylon703',-703,'703 BCE','Babylon challenges Assyria','Sennacherib defeats Merodach-baladan in Babylonia, providing context for the ruler named in Isaiah 39.',['met701'],['babylon'],39,1);
ev('western701',-701,'701 BCE','Sennacherib’s western campaign','The Assyrian campaign reaches Judah. Compare the narrative, the royal inscriptions, and the Lachish reliefs.',['met701','rinap','lachish'],['lachish','jerusalem']);
ev('lachish-art',-695,'700–692 BCE','Palace reliefs show Lachish','The palace reliefs present the conquest for an Assyrian royal audience. The artifact was made after the event it depicts.',['lachish'],['nineveh','lachish'],36,2,'695 BCE is a display position within the museum’s dating range of 700–692 BCE.');
ev('death681',-681,'681 BCE','Sennacherib’s reign ends','Isaiah 37 ends with a later death. The account moves many years beyond the invasion.',['web37','metchron'],['nineveh'],37,38);
ev('nineveh612',-612,'612 BCE','Nineveh falls','The fall of Nineveh weakens Assyrian power. Some Assyrian forces continue to resist.',['metchron'],['nineveh'],39,6);
ev('carchemish605',-605,'605 BCE','Babylon gains power in the west','The battle at Carchemish helps Babylon gain power in the eastern Mediterranean region.',['livius605'],['carchemish'],39,6);
ev('jerusalem597',-597,'597 BCE','Jerusalem and royal deportation','Babylon captures Jerusalem and takes its king into exile. These later events help explain the warning in Isaiah 39.',['livius605','web39'],['jerusalem','babylon'],39,6);
ev('jerusalem586',-586,'587/586 BCE','Jerusalem and the temple destroyed','Babylon destroys Jerusalem and the temple. This event occurs long after the Assyrian crisis.',['metchron','yale'],['jerusalem','babylon'],39,6,'Scholars date the destruction to 587 or 586 BCE. The app shows both dates.');
ev('cyrus539',-539,'539 BCE','Persia takes Babylon','Cyrus conquers Babylon. The Cyrus Cylinder describes his support for restoring worship. It does not mention the return of Judah’s exiles.',['cyrus','yale'],['babylon'],39,6);

const campaigns=[
 {id:'lachish-mission',title:'From Lachish to Jerusalem',start:-702,end:-700,dateLabel:'701 BCE · narrative setting',points:[[31.565,34.849],[31.66,34.98],[31.778,35.235]],summary:'Isaiah 36:2 sends the Assyrian representative from Lachish to Jerusalem. The connection brings the campaign to the city’s walls.',detail:'The line connects Lachish and Jerusalem. The passage does not establish the official’s exact road or travel time. It does not trace Sennacherib’s movements. Compare the chapter with the Assyrian reliefs of Lachish.',uncertainty:'The line connects places in the account. The exact route is unknown.',sourceIds:['web','lachish'],chapter:36,verse:2},
 {id:'west-campaign',title:'The Assyrian campaign in the west',start:-702,end:-700,dateLabel:'701 BCE',points:[[33.56,35.37],[33.27,35.2],[32.2,34.95],[31.665,34.548],[31.778,34.85],[31.565,34.849]],summary:'A regional view of places affected by the western campaign before the confrontation at Jerusalem.',detail:'Assyrian inscriptions describe attacks on Hezekiah’s fortified towns and present the campaign as a royal victory. Palace reliefs depict the conquest of Lachish. These records help explain Judah’s losses, while the biblical account describes Jerusalem’s survival. The royal records promote Sennacherib’s power; they do not confirm travel through every mapped stop.',uncertainty:'The order of stops and the route are approximate.',sourceIds:['met701','rinap'],chapter:36,verse:1},
 {id:'babylon-envoys-route',title:'The Babylonian embassy',start:-710,end:-701,dateLabel:'Late eighth century BCE · exact date debated',points:[[32.54,44.42],[34.3,40.8],[35.3,38.4],[33.51,36.29],[31.778,35.235]],summary:'Isaiah 39 links Babylonian visitors with Hezekiah’s court.',detail:'The curve connects Babylon and Jerusalem through the north. The passage does not establish this route or the visit’s exact year.',uncertainty:'The line connects the two cities. The travel route and exact date are unknown.',sourceIds:['web39','anderson'],chapter:39,verse:1},
 {id:'exile-horizon',title:'Exile in Babylon',start:-597,end:-539,dateLabel:'597–539 BCE · later events',points:[[31.778,35.235],[33.51,36.29],[35.3,38.4],[34.3,40.8],[32.54,44.42]],summary:'Compare Jerusalem and Babylon to study the later events described in Isaiah 39.',detail:'The map connects Jerusalem and Babylon. The line does not show one confirmed route into exile. People did not travel continuously throughout this period.',uncertainty:'The line connects the cities. The exact route into exile is unknown.',sourceIds:['web39','metchron'],chapter:39,verse:6}
];
const regions=[
 {id:'babylonia-early',faction:'babylonia',name:'Land near Babylon · approximate',start:-780,end:-606,points:[[33.6,43.5],[33.7,45.0],[32.6,46.1],[30.8,47.1],[30.5,46.0],[31.4,44.5],[32.5,43.3]],color:'#783951',summary:'This shaded area shows the land near Babylon. It also shows the river lands to the south. Kings from Babylon and Assyria fought to rule this land.',uncertainty:'The shape does not show a firm border. Rule changed over time. Sennacherib beat Merodach-baladan in 703 BCE. Babylon became the main power in 605 BCE.',sourceIds:['metchron','met701','web39']},
 {id:'judah',name:'Land of Judah · approximate',start:-780,end:-587,points:[[31.95,34.91],[31.95,35.34],[31.38,35.42],[31.1,35.1],[31.3,34.75]],color:'#79cbd8',summary:'This shaded area shows the hills and lowlands of Judah.',uncertainty:'The shape does not show a firm border. Rule changed over time.',sourceIds:['geo','web']},
 {id:'philistia',faction:'philistia',name:'Philistine city-states · approximate',start:-780,end:-604,chapterCoverage:[9,11,14,20,23,36],points:[[31.95,34.55],[31.82,34.82],[31.28,34.72],[31.15,34.32],[31.72,34.38]],color:'#a4634f',summary:'Philistia had several city-states on the southern coast. They included Ashdod, Ashkelon, Ekron, Gaza, and Gath.',uncertainty:'The shape is a simple guide. Control changed by city and year. Assyria and Babylon both put pressure on these cities.',sourceIds:['geo','web14','wiki-ekron']},
 {id:'egypt-region',faction:'egypt',name:'Egyptian realm · approximate',start:-780,end:-539,chapterCoverage:[11,19,20,23,27,30,31,36,37],points:[[31.7,29.7],[31.7,32.6],[30.2,32.8],[29.5,31.9],[24,32.1],[24,30.4],[29.4,30.5]],color:'#4f8278',summary:'Egypt controlled the Nile valley and delta. Its armies, horses, and wealth made it seem like a strong ally. Yet its divided rulers made that help unsafe.',uncertainty:'The shape is a simple guide. Egypt’s ruling families and power centers changed during Isaiah’s time. Kushite rulers also governed Egypt for part of this period.',sourceIds:['geo','web19','web30','web31']},
 {id:'cush-region',faction:'cush',name:'Cushite realm · approximate',start:-780,end:-539,chapterCoverage:[11,18,20,37],points:[[24,30.4],[24,33],[18,33.5],[12.5,32.7],[12.5,29.2],[18,30.4]],color:'#7b5f8e',summary:'Cush was a kingdom south of Egypt in Nubia. Kushite kings also ruled Egypt during part of Isaiah’s historical setting.',uncertainty:'The shape is a simple guide. It shows only the northern part of Cush. Control changed over time.',sourceIds:['geo','web18','web20','wiki-taharqa']},
 {id:'assyria',name:'Lands under Assyria · approximate',start:-722,end:-613,points:[[37.5,35.6],[37.5,44.9],[34.0,44.9],[33.0,39.2],[31.4,35.9],[32.3,34.9]],color:'#568cf0',summary:'This shaded area shows lands ruled by Assyria. Assyria ruled some lands. Other kings ruled some lands for Assyria. They had to pay Assyria.',uncertainty:'Assyria did not rule all these lands in the same way. Its power also changed over time. The shape does not show a firm border for each year.',sourceIds:['metchron','met701']},
 {id:'babylonia',name:'Lands under Babylon · approximate',start:-605,end:-540,points:[[36.8,36.2],[36.6,44.9],[30.5,47.0],[29.9,43.0],[31.0,35.0],[33.2,35.4]],color:'#9284d7',summary:'This shaded area shows lands that Babylon ruled after Assyria grew weak.',uncertainty:'The shape does not show a firm border. Rule changed over time.',sourceIds:['metchron']},
 {id:'persian',name:'Lands under Persia · approximate',start:-539,end:-539,points:[[38,35],[38,50],[29,50],[29,35]],color:'#58bcaf',summary:'This shaded area shows Babylon when Persia took control.',uncertainty:'The shape shows only part of the land Cyrus ruled.',sourceIds:['cyrus']}
];
const periods=[{id:'pre',label:'Before Isaiah',start:-780,end:-741,description:'Earlier eighth-century setting'},{id:'isaiah',label:'Isaiah',start:-740,end:-681,description:'Assyria, Judah, and Isaiah’s ministry'},{id:'post',label:'After Isaiah',start:-680,end:-539,description:'Later events in Babylon and Persia'}];
const guides=[
 {id:'crisis',title:'The Assyrian crisis',description:'Follow the Assyrian threat from Lachish to Jerusalem.',steps:[
  {title:'Locate the two cities',text:'Find Lachish on the map. An Assyrian official travels from here to Jerusalem. The line connects the cities; the exact route is unknown.',chapter:36,verse:2,year:-701,placeId:'lachish',sourceIds:['web','lachish']},
  {title:'Listen to the argument',text:'The speaker challenges trust in Egypt and Hezekiah. How does he use these places to support his argument?',chapter:36,verse:6,year:-701,placeId:'jerusalem',sourceIds:['web']},
  {title:'A public audience',text:'The officials request Aramaic. The speaker addresses the people on the wall in their own language. Why does his choice matter?',chapter:36,verse:11,year:-701,placeId:'jerusalem',sourceIds:['web','oshb']},
  {title:'A threat to move the people',text:'Compare the offer of food and land with the promised removal to another land. How does the speech make submission sound attractive?',chapter:36,verse:17,year:-701,placeId:'jerusalem',sourceIds:['web']}
 ]},
 {id:'evidence',title:'Two accounts, one crisis',description:'Compare Isaiah’s account with Assyrian records.',steps:[
  {title:'The palace viewpoint',text:'What does this image emphasize about the victorious king? What does it leave out?',chapter:36,verse:2,year:-695,placeId:'nineveh',sourceIds:['lachish']},
  {title:'The royal inscription',text:'The Assyrian inscription presents the campaign as a royal victory. Compare its purpose with the biblical account.',chapter:37,verse:18,year:-701,placeId:'jerusalem',sourceIds:['rinap']},
  {title:'How the account ends',text:'Isaiah credits God with saving Jerusalem. Compare this explanation with the Assyrian account. Consider the purpose and limits of each source.',chapter:37,verse:36,year:-701,placeId:'jerusalem',sourceIds:['web37','met701']},
  {title:'Years between events',text:'The final verse describes a death many years later. Consecutive verses can describe events that are far apart in time.',chapter:37,verse:38,year:-681,placeId:'nineveh',sourceIds:['web37','metchron']}
 ]},
 {id:'horizon',title:'Babylon and Judah’s future',description:'Study the events before and after Isaiah 39.',steps:[
  {title:'A vulnerable king',text:'Chapter 38 describes Hezekiah’s illness and a promise to defend Jerusalem. Chapter order alone does not establish the order of these events.',chapter:38,verse:6,year:-701,placeId:'jerusalem',sourceIds:['web38','anderson']},
  {title:'Visitors from Babylon',text:'Babylon sends visitors to Hezekiah. Their visit’s exact date is uncertain. The map uses 703 BCE to show the setting.',chapter:39,verse:1,year:-703,placeId:'babylon',sourceIds:['web39']},
  {title:'Jerusalem’s later destruction',text:'The timeline shows Jerusalem’s destruction in 587/586 BCE. Compare Isaiah’s warning about the palace treasures with this later event.',chapter:39,verse:6,year:-586,placeId:'jerusalem',sourceIds:['web39','metchron']},
  {title:'Persia takes Babylon',text:'The timeline ends with Cyrus’s conquest. The Cyrus Cylinder gives a royal account. It does not mention the return of Judah’s exiles.',chapter:39,verse:6,year:-539,placeId:'babylon',sourceIds:['cyrus']}
 ]}
];
const out={sources,passages,events,places,campaigns,regions,words:[],guides,periods,editorial:{status:'We checked the sources. A subject expert has not reviewed the full guide.',periodNote:'These timeline sections help with navigation. They do not set fixed dates for Isaiah’s work or for who wrote each part.',mapNote:'This is a physical reference map. Historical areas and routes use simple shapes. Modern coasts and lakes may differ from ancient ones.'}};
addComeFollowMe(out);
addMcClellan(out);
addGeneralConference(out);
addFullIsaiah(out, JSON.parse(await readFile(new URL('../dist/data/scripture.json', import.meta.url), 'utf8')));
for (const campaign of out.campaigns) campaign.faction = ['lachish-mission', 'west-campaign'].includes(campaign.id) ? 'assyria' : 'babylonia';
addPrismAndHarmony(out);
addAncientRoads(out);
addSourcePreviews(out);
await addChapterGeography(out, JSON.parse(await readFile(new URL('../dist/data/scripture.json', import.meta.url), 'utf8')));
addChapterEnrichment(out, JSON.parse(await readFile(new URL('../dist/data/scripture.json', import.meta.url), 'utf8')));
await writeFile(new URL('../dist/data/content.json',import.meta.url),JSON.stringify(out,null,2));
console.log(`Created ${out.sources.length} sources, ${out.passages.length} passages, ${out.events.length} events, ${out.places.length} places and ${out.guides.length} guides.`);
