// Original reading notes. These summarize the cited chapter, not an independent historical reconstruction.
// Fields: chapter | title | reading summary | devotional question | map reference places.
const notes = `
1|Worship and justice|The opening vision addresses Judah and Jerusalem. Sacrifices cannot replace justice for vulnerable people. The chapter joins a call to repentance with a promise to restore the city.|How can worship lead to care for people who lack protection?|jerusalem
2|Nations learn peace|The nations come to the LORD's mountain to learn his ways. The vision of peace gives way to a warning against pride, wealth, and idols. Human power cannot provide lasting security.|What would learning the Lord's ways change about how you treat others?|jerusalem
3|Leadership and responsibility|Judah loses stable leadership. The LORD brings a case against leaders who exploit the poor. The chapter's images of lost luxury end with Jerusalem mourning its losses.|How should people with authority answer for the treatment of the poor?|jerusalem
4|Cleansing and shelter|Verse 1 continues the distress described in chapter 3. The remaining verses picture a purified Jerusalem under divine protection. Cloud, fire, and shelter describe the LORD's presence with the survivors.|How do cleansing and protection work together in this promise?|jerusalem
5|The vineyard and its fruit|A vineyard song becomes an accusation against Israel and Judah. God looks for justice but finds bloodshed. Warnings against exploitation and moral confusion lead to an image of an approaching army.|What actions would count as good fruit in your community?|jerusalem
6|Isaiah's call|Isaiah sees the Lord in the year of King Uzziah's death. A burning coal cleanses his lips before he accepts a difficult commission. The account ends with devastation and the image of a holy seed.|How does Isaiah's awareness of his weakness affect his response to the call?|jerusalem
7|Ahaz faces a threat|Aram and Israel threaten Judah, and Isaiah tells Ahaz not to fear. The sign of Immanuel concerns this crisis, while Christian readings also connect it with Jesus. Assyria becomes a danger to Judah itself.|How does fear affect Ahaz's willingness to trust the Lord?|jerusalem,damascus,samaria
8|Signs and competing voices|Isaiah's child's name announces plunder approaching Damascus and Samaria. Assyria appears as a flood reaching Judah. The prophet contrasts trust in the LORD with fear and consultation of the dead.|Which voices do people consult when they feel afraid?|jerusalem,damascus,samaria
9|Light and a just ruler|Light breaks into a land of distress. A promised child bears royal titles and establishes justice. The chapter then turns to judgment against pride, corrupt leadership, and conflict within Israel.|How does the promised ruler's justice shape a faithful reading of hope?|samaria,jerusalem
10|Assyria and the remnant|The chapter condemns unjust decrees before addressing Assyria as an instrument that becomes proud. A remnant returns to the mighty God. An approaching army threatens Zion, but the final image cuts down lofty trees.|How can success lead people to forget their responsibility to others?|jerusalem,samaria
11|A ruler from Jesse's line|A shoot from Jesse's stump receives the LORD's spirit and judges with justice. Peace reaches even the animal world. The chapter pictures scattered people gathering and divisions within Israel ending.|What does this vision teach about justice for the poor?|jerusalem
12|Songs of salvation|Two short songs respond to deliverance with trust and thanksgiving. Images of water, singing, and public witness describe the people's response. Zion celebrates the presence of the Holy One of Israel.|What would it mean to share gratitude without hiding earlier fear?|jerusalem
13|Judgment on Babylon|The oracle announces the day of the LORD through images of war and cosmic disorder. It names the Medes in the attack on Babylon. The ruined city becomes a warning about imperial pride.|How does the fall of a powerful city challenge confidence in worldly security?|babylon
14|A fallen king|Israel's relief from oppression leads into a taunt against Babylon's king. The fallen morning star belongs to this poem about royal pride. Oracles against Assyria and Philistia follow the taunt.|How does the poem expose the cost of a ruler's ambition?|babylon,jerusalem
15|Mourning for Moab|Moab's towns face destruction and flight. The poem describes public grief, failed harvests, and refugees carrying their possessions. Its lament gives attention to the suffering of Judah's neighbor.|What does attention to a neighboring people's grief ask of the reader?|
16|Refuge and Moab's pride|Moab seeks protection, and a just throne in David's tent appears in the appeal. Pride and ruined vineyards dominate the lament. The closing notice gives a three-year limit for Moab's loss of glory.|How does this chapter place pride beside the need for refuge?|jerusalem
17|Damascus and Israel|Damascus and Ephraim face loss, though a small remnant remains. The poem contrasts looking to the Maker with reliance on human-made altars. The noise of threatening nations ends in sudden defeat.|What changes when people look to their Maker rather than their own works?|damascus,samaria
18|Messengers from Cush|The oracle addresses a land associated with Cush and describes swift messengers. The LORD watches quietly before cutting back growth. The closing scene brings a gift to Mount Zion.|What does the contrast between urgent messengers and divine waiting invite you to consider?|jerusalem
19|Egypt, Assyria, and Israel|Egypt faces conflict, failed counsel, and economic distress. The ending imagines Egyptians turning to the LORD. A shared blessing joins Egypt, Assyria, and Israel in worship.|How does the shared blessing challenge hostility toward other peoples?|memphis,jerusalem
20|A sign against reliance on Egypt|The chapter names Sargon's capture of Ashdod. Isaiah's exposed and barefoot appearance serves as a sign of captivity for Egypt and Cush. Those who trusted these powers face disappointment.|What makes a source of security appear stronger than it is?|
21|Watchmen and warnings|A watchman announces Babylon's fall. Brief oracles then address Dumah and Arabia. Waiting, flight, and aid for refugees connect the chapter's scenes.|How do watchfulness and care for fugitives belong together?|babylon
22|Jerusalem under scrutiny|Jerusalem prepares defenses but fails to look to the one who made them possible. Celebration replaces repentance. A second oracle removes Shebna and gives Eliakim authority, pictured by a key and a peg.|How can practical preparation coexist with trust and accountability?|jerusalem
23|Tyre and the sea trade|The lament follows the disruption of Tyre's trading network. Sidon and distant ports share the shock. The ending pictures renewed trade whose proceeds serve those who dwell before the LORD.|What responsibilities come with wealth gained through trade?|tyre,sidon
24|The earth brought low|A vision of widespread judgment crosses social ranks. Broken obligations accompany ruined celebration and a desolate city. The final scene places the LORD's reign on Mount Zion above earthly powers.|How do broken commitments harm a whole community?|jerusalem
25|A feast and the end of death|Praise for deliverance leads to a feast for all peoples on the mountain. God removes the covering over the nations and swallows up death. The chapter ends by bringing down Moab's pride.|What does a feast for all peoples suggest about the reach of divine mercy?|jerusalem
26|Trust while waiting|A song in Judah contrasts the secure city with a proud city brought low. The speakers long for justice and describe their failed efforts through childbirth imagery. Hope for the dead accompanies a call to wait through judgment.|How does this song hold trust and distress together?|jerusalem
27|A vineyard restored|The LORD defeats Leviathan, a creature in the poem's imagery. A new vineyard song describes protection and fruitfulness. Judgment, purification, and a trumpet gathering the scattered lead toward worship in Jerusalem.|How does the protected vineyard differ from the vineyard in chapter 5?|jerusalem
28|A foundation and false security|Ephraim's proud crown falls, and drunken leaders in Judah also face rebuke. Jerusalem's rulers claim security through a covenant with death. A sure foundation and a farmer's varied methods offer different images of divine action.|What distinguishes a reliable foundation from an agreement based on false confidence?|samaria,jerusalem
29|Jerusalem and hidden counsel|Ariel, associated here with Jerusalem, faces siege and unexpected deliverance. A sealed book and empty worship expose failures of understanding. The ending promises hearing, sight, and justice for people who suffer.|How can words of worship become separated from the heart?|jerusalem
30|An alliance and an invitation|Judah seeks help from Egypt without listening to the LORD. The chapter contrasts restless escape with quiet trust. Promises of mercy, guidance, and healing lead into judgment on Assyria.|What makes quiet trust difficult when urgent action seems necessary?|jerusalem,memphis
31|Horses cannot save|The oracle rejects dependence on Egypt's horses and chariots. Human strength cannot replace the LORD's protection of Jerusalem. Assyria's fall follows a call to return from idolatry.|How can resources become objects of trust beyond their real value?|jerusalem,memphis
32|Justice and peace|A righteous king and just rulers introduce a vision of clear judgment. A warning to complacent women precedes images of ruined fields. The outpouring of the spirit brings justice, peace, and secure homes.|How does the chapter connect peace with justice rather than comfort alone?|jerusalem
33|Help in a time of danger|A destroyer faces destruction as the people ask the LORD for strength. Broken agreements and empty roads show the crisis. The final vision presents Zion with a righteous king, security, and forgiveness.|Which actions does the chapter associate with living near divine holiness?|jerusalem
34|Judgment pictured through Edom|Judgment on the nations focuses on Edom. Images of sacrifice, fire, and abandoned land describe its ruin. Animals inhabit places that once belonged to human power.|What do the images of abandoned cities communicate about the limits of power?|
35|A road home|The wilderness blossoms as weak hands and fearful hearts receive encouragement. Healing and abundant water transform the scene. A holy highway brings the redeemed to Zion with lasting joy.|How do physical restoration and return to God support each other in this vision?|jerusalem
40|Comfort and renewed strength|A voice prepares a way for the LORD and announces comfort to Jerusalem. The chapter contrasts fading human life with God's enduring word. The Creator's power answers the complaint that the people's way is hidden.|How does the promise of renewed strength speak to people who feel forgotten?|jerusalem
41|Do not fear|The nations face a challenge concerning events stirred up from the east. Israel, named as God's servant, receives help and reassurance. A dispute with idols asks who can explain what is coming.|How does being called God's servant change the way Israel can face fear?|jerusalem
42|A servant who brings justice|The LORD's servant brings justice without crushing the weak. A new song announces divine action across lands and seas. The chapter then confronts the blindness and deafness of the people called to serve.|How can a gentle manner serve a firm commitment to justice?|
43|Called by name|God promises to be with Israel through water and fire. The people serve as witnesses to the LORD's saving power. A new way through the wilderness stands beside a rebuke for sin and a promise of forgiveness.|What does remembrance of earlier rescue contribute to hope for something new?|babylon,jerusalem
44|The Creator and the idol maker|The LORD promises water and spirit to Jacob's descendants. A satire describes people using the same wood for fuel and a god. The ending names Cyrus in connection with rebuilding Jerusalem and the temple.|How does the idol-making account expose dependence on what people create?|jerusalem,babylon
45|Cyrus and the LORD's purpose|Cyrus is addressed as the LORD's anointed, though he does not know the LORD. The chapter presents the Creator as directing events beyond Israel. It closes with an invitation for the ends of the earth to turn and be saved.|What does the use of Cyrus suggest about whom God can work through?|babylon,jerusalem
46|The God who carries|Babylon's gods become burdens carried by animals. The LORD instead promises to carry the people from birth to old age. The chapter calls them to remember divine purpose and coming deliverance.|How does the contrast between carrying an idol and being carried change the image of trust?|babylon
47|Babylon brought down|Babylon appears as a queen losing her throne and status. Cruelty and self-confidence meet sudden loss. Sorcery and astrology cannot protect her from the announced judgment.|How can confidence in special knowledge prevent honest recognition of wrongdoing?|babylon
48|Leaving Babylon|The LORD confronts Israel's stubbornness and explains earlier announcements. The speaker calls the people to listen to divine instruction. A command to leave Babylon recalls provision during the wilderness journey.|What stands between hearing instruction and allowing it to change conduct?|babylon,jerusalem
49|A servant and remembered Zion|A servant called from the womb receives a mission reaching beyond Israel. Zion fears abandonment, but God answers with images of a mother's care and engraved hands. The return of children expands the city's hope.|How does the chapter answer Zion's fear that God has forgotten her?|jerusalem
50|A listening servant|Questions about divorce and debt introduce a challenge to the people's account of their separation from God. A taught and listening servant endures abuse while trusting divine help. The closing appeal contrasts trust in darkness with self-made light.|How does listening prepare the servant to sustain someone who is weary?|
51|Remember and awaken|The people seeking righteousness are told to remember Abraham and Sarah. Images of creation and the exodus support renewed hope. Jerusalem's cup of suffering will pass to her tormentors.|How can remembering earlier generations strengthen a community under pressure?|jerusalem
52|Good news for Zion|Zion is told to awake and leave captivity behind. A messenger announces peace and God's reign as watchmen celebrate return. The final verses introduce an exalted servant whose appearance has shocked many.|How does the announcement of peace prepare the reader for the servant passage that follows?|jerusalem
53|The suffering servant|The speakers reconsider a rejected figure whose suffering they had misunderstood. The servant bears the wrongdoing of others and faces death. The poem moves from rejection and burial toward vindication and a share with the great.|In a Christian reading, how does this passage deepen reflection on Jesus Christ's suffering?|
54|A covenant of peace|A barren woman and a deserted wife become images of Zion's restoration. The LORD promises compassion and a covenant of peace. The city receives a beautiful rebuilding, taught children, and protection against accusation.|How do the family images express belonging after rejection?|jerusalem
55|An invitation without price|The thirsty receive an invitation to food and drink without payment. A lasting covenant extends the call beyond Israel. God's effective word and a joyful departure close the chapter.|What would it mean to seek what truly nourishes without treating grace as a purchase?|
56|A house of prayer for all peoples|Justice and Sabbath observance introduce promises for foreigners and eunuchs who keep the covenant. God's house welcomes peoples who feared exclusion. The closing passage condemns negligent watchmen and self-serving shepherds.|How does the promise of belonging challenge assumptions about who can draw near to God?|jerusalem
57|False worship and healing|The death of the righteous contrasts with corrupt worship and misplaced reliance. The high and holy God also dwells with the contrite. A promise of healing and peace ends with a warning to the wicked.|What does God's nearness to the contrite teach about repentance?|
58|The fast God chooses|The people ask why God has not noticed their fasting. The answer exposes oppression beneath their religious practice. Feeding the hungry, sheltering the homeless, and honoring the Sabbath accompany promises of restoration.|What concrete act of care can give substance to your worship?|jerusalem
59|Justice lost and a redeemer promised|The chapter traces separation from God to violence, deceit, and injustice. A communal confession describes truth stumbling in public life. The LORD intervenes as a warrior and promises a redeemer to Zion.|How can a community acknowledge shared wrongdoing without avoiding personal responsibility?|jerusalem
60|Zion receives light|Light rises over Zion while darkness covers the earth. Nations and returning children bring wealth to the city. The vision ends with peace, righteousness, and the LORD as everlasting light.|How can the image of received light guide service to other people?|jerusalem
61|Good news and restored lives|An anointed speaker announces good news, release, and comfort for mourners. Ruined places will be rebuilt, and shame gives way to a lasting covenant. The closing voice rejoices in salvation and righteousness.|In a Christian reading, how does Jesus's mission connect proclamation with care for people in distress?|jerusalem
62|A new name for Zion|The speaker refuses silence until Zion's vindication becomes visible. Marriage imagery replaces names of abandonment. Watchmen call on the LORD as a road is prepared for the people's return.|How do new names change the way the restored community understands itself?|jerusalem
63|Judgment and remembered mercy|A warrior comes from Edom with stained garments after judgment. The chapter then recalls the LORD's compassion and past rescue. A communal prayer asks why God's presence now seems distant.|How can prayer name painful questions while remembering earlier mercy?|
64|A prayer for God's return|The prayer asks God to come down as in earlier acts of power. The people confess impurity and appeal to God as Father and potter. The ruined sanctuary becomes a reason to plead for renewed attention.|What does the image of clay in a potter's hands add to confession?|jerusalem
65|Judgment and new creation|The LORD answers a rebellious people while distinguishing servants who will receive blessing. New heavens and a new earth introduce a joyful Jerusalem. Secure homes, fruitful work, and peace replace former distress.|Which parts of ordinary life does the promised renewal restore?|jerusalem
66|Humility, comfort, and all nations|The LORD values humility above claims based on a temple alone. Zion's sudden birth and maternal comfort accompany judgment. The book ends with gathered nations, continuing worship, and a severe picture of rebellion's outcome.|How do comfort and accountability shape the book's final invitation?|jerusalem
`.trim().split('\n').map(line => {
  const [chapter,title,summary,question,places] = line.split('|');
  return { chapter:Number(chapter),title,summary,question,placeIds:places ? places.split(',') : [] };
});

// Reader copy. Each note keeps the main idea but uses short, direct sentences.
const simpleNotes = `
1|Isaiah sees a vision about Judah and Jerusalem. God says his people have left him. Their cities are burned, and strangers take their land. Jerusalem is left alone. The people still bring offerings and pray. God refuses their worship and tells them to do right. He gives them a choice: obey and eat well, or refuse and face the sword. He promises to give the city fair judges again.|God refuses prayers from people who harm others. What do verses 16–17 tell them to do?
2|Isaiah sees what will happen in later days. The LORD’s mountain stands above all other hills. Many peoples go up to learn his ways. He settles their disputes, and they turn swords into plow blades. Then the vision turns to Jacob’s people now. Their land is full of silver, horses, and idols. A day of the LORD will bring down every proud thing. People will throw their idols to moles and bats.|The nations ask to learn the LORD’s ways (verse 3). What do they give up in verse 4?
3|The LORD takes bread, water, and leaders away from Jerusalem and Judah. Soldiers, judges, prophets, and elders are gone. Boys rule, and neighbors hurt each other. One man begs his brother to rule the ruin, and the brother refuses. Then the LORD stands up as judge. He charges the elders and leaders with robbing the poor. He also says the proud women of Zion will lose their fine things. The city gates mourn, and the men fall in war.|The LORD asks leaders why they “crush my people” (verse 15). What does verse 14 say is in their houses?
4|Verse 1 ends the war scene from chapter 3. So few men are left that seven women ask one man for his name. Then the picture changes. The LORD’s branch and the land’s fruit become the pride of the survivors. Those left in Jerusalem are called holy. The Lord washes the city’s filth and blood away with justice and burning. He covers Mount Zion with cloud by day and fire by night. A shelter gives shade from heat and cover from storm.|The city is washed in verse 4 and sheltered in verse 6. Why does the washing come first?
5|A singer begins a love song about a friend’s vineyard. The owner dug, cleared stones, planted good vines, and built a tower. The vines gave wild grapes. The owner asks Judah to judge, then says he will break down its wall. Verse 7 names the vineyard: Israel and Judah. Six cries of “Woe” name land grabbers, heavy drinkers, and judges who take bribes. The LORD’s anger burns, and his hand stays stretched out. He whistles for a far nation, and its army comes fast.|The owner asks what more he could have done (verse 4). What did he expect to find in verse 7?
6|Isaiah tells what he saw in the year King Uzziah died. The Lord sits on a high throne in the temple. Six-winged beings called seraphim call out, “Holy, holy, holy.” The doorposts shake, and smoke fills the house. Isaiah says he is ruined because his lips are unclean. A seraph touches his mouth with a hot coal and says his sin is forgiven. The Lord asks whom to send, and Isaiah offers to go. His message will not be understood until the land lies empty.|Isaiah says “Send me” before he hears the task. What does the Lord tell him in verses 9–12?
7|The kings of Syria and Israel march against King Ahaz in Jerusalem. Ahaz and his people shake with fear. The LORD sends Isaiah and his son to meet Ahaz by the upper pool. Isaiah says the two kings are only smoking stubs, and their plan will fail. The LORD offers Ahaz a sign, but Ahaz refuses to ask. Isaiah gives one anyway: the virgin will bear a son named Immanuel. Before the boy can choose good, both enemy lands will be empty. Then the LORD will bring the king of Assyria on Judah.|Ahaz is told to keep calm and believe (verses 4 and 9). What does he do when offered a sign?
8|Isaiah writes the name Maher Shalal Hash Baz on a large tablet. The prophetess bears Isaiah a son, and the boy gets that name. Before the boy can talk, Assyria will plunder Damascus and Samaria. The people refused the quiet waters of Shiloah. So the king of Assyria will come like a flood, up to Judah’s neck. The LORD warns Isaiah not to share the people’s fears. Isaiah seals the teaching among his followers and waits. People who ask the dead for help will find only darkness.|The people fear two kings. What does verse 14 say the LORD becomes for those who fear him?
9|The gloom over Zebulun and Naphtali ends. People who walked in darkness see a great light. The oppressor’s rod breaks, and armor and bloody clothes burn. A child is born who will rule on David’s throne. His names include Wonderful Counselor and Prince of Peace. Then the word turns against Israel and Samaria. They boast that they will rebuild with cut stone. Enemies, lying leaders, and fighting between tribes follow, and the LORD’s hand stays stretched out.|Verse 7 says the child rules with justice and righteousness. Who does the verse say will make this happen?
10|The chapter opens with woe to lawmakers who rob widows and the fatherless. Then the LORD calls Assyria the rod of his anger. He sends Assyria against a people who anger him. But Assyria’s king plans to destroy many nations and boasts of his own strength. The LORD will punish that pride after his work on Jerusalem. A remnant of Israel will return and lean on the LORD. An army marches town by town toward Jerusalem. Then the LORD cuts down the tall trees.|Assyria’s king says his own hand did it (verse 13). How does verse 15 answer him?
11|A shoot grows from the stock of Jesse. The LORD’s Spirit rests on him with wisdom, counsel, and might. He does not judge by what he sees or hears. He judges the poor with fairness and strikes the wicked with his words. Wolf and lamb, cow and bear, child and snake live without harm. The nations look for this root of Jesse. The Lord gathers his scattered people from Assyria, Egypt, and far lands. Ephraim and Judah stop fighting each other, and a road opens for those who return.|This king does not judge by what he sees or hears (verse 3). Who gains from that in verse 4?
12|This chapter is a short song for “that day.” The singer thanks the LORD because his anger has turned away. The singer says, “God is my salvation,” and will trust without fear. The people draw water with joy from the wells of salvation. They tell the nations what the LORD has done. Zion is told to shout, because the Holy One of Israel is great among them.|The singer says, “I will trust, and will not be afraid” (verse 2). What had changed in verse 1?
13|Isaiah sees a message about Babylon. A banner goes up, and the LORD gathers an army from far lands. The day of the LORD comes with anger. Hands go weak, hearts melt, and the sun, moon, and stars go dark. The LORD says he will punish evil and end the pride of the proud. He stirs up the Medes, who do not care for silver or gold. Babylon, the glory of kingdoms, will fall like Sodom and Gomorrah. Only wild animals will live there.|Verse 19 calls Babylon “the glory of kingdoms.” What does verse 11 say the LORD will do to the proud?
14|The LORD will have compassion on Jacob and settle Israel in its own land. Then Israel will sing a taunt against the king of Babylon. The whole earth rests and sings. Dead kings in Sheol, the place of the dead, say he is weak like them. He said he would rise above the stars. He is thrown out without a tomb. The LORD also swears to break Assyria in his land. A last message warns Philistia not to rejoice.|The king said, “I will make myself like the Most High” (verse 14). Where does verse 15 say he goes?
15|This is a message about Moab. Two Moabite cities, Ar and Kir, fall in one night. People go up to the high places to weep. They shave their heads, cut their beards, and wear rough sackcloth. The cry spreads from town to town, and soldiers shake. The speaker says, “My heart cries out for Moab!” Nobles flee to Zoar, weeping as they climb. The waters dry up or run with blood, and more trouble is coming.|The speaker’s heart “cries out for Moab” (verse 5). Why does a message of judgment include grief?
16|Moab is told to send lambs to the ruler on Mount Zion. Moab’s women are like birds pushed from a nest at the Arnon river crossings. A voice asks for shelter: hide the outcasts and do not betray them. A throne will stand in David’s tent, with a judge who seeks justice. But Moab’s pride is well known, and its boasts are empty. Its vines and harvest songs stop, and the speaker weeps for them. Moab’s prayers at its high place will not work. Within three years its glory will be small.|Moab’s outcasts ask for a hiding place (verses 3–4). What kind of ruler does verse 5 describe?
17|This is a message about Damascus. Damascus will stop being a city and become a heap of ruins. Ephraim loses its fortress too. Jacob’s glory grows thin, like a field after harvest. Only a few olives stay on the highest branches. In that day people will look to their Maker, not to altars they made. They forgot the God who saved them, so their planting gives no harvest. Many nations roar like the sea, but by morning they are gone.|People look to their Maker and not to what their fingers made (verses 7–8). What had they forgotten in verse 10?
18|The message speaks to a land beyond the rivers of Ethiopia. It sends messengers in papyrus boats. They go to a tall, smooth people whose land the rivers divide. All the world is told to watch for a banner and listen for a trumpet. The LORD says he will stay still and watch, like heat in sunshine. Before the harvest he cuts off the branches and leaves them for birds and animals. Then that tall people will bring a gift to the LORD at Mount Zion.|The LORD says, “I will be still, and I will see” (verse 4). What happens before the harvest in verse 5?
19|This is a message about Egypt. The LORD rides a swift cloud to Egypt, and its idols shake. Egyptians fight each other, and a cruel king rules them. The Nile dries up, and fishermen and weavers lose their work. Pharaoh’s wise men give foolish advice. Then five Egyptian cities swear to the LORD, and an altar to him stands there. The LORD strikes Egypt and heals it. A highway joins Egypt and Assyria, and the LORD blesses both with Israel.|The LORD calls Egypt “my people” (verse 25). What does verse 22 say he does before that?
20|Assyria’s commander takes the city of Ashdod for King Sargon. At that time the LORD tells Isaiah to take off his sackcloth and sandals. Isaiah walks naked and barefoot for three years. The LORD says this is a sign about Egypt and Ethiopia. Assyria’s king will lead their captives away the same way, young and old. People who trusted Egypt and Ethiopia will be ashamed. The people of the coast will ask how they can escape.|The coast people fled to Egypt for help (verse 6). What does Isaiah’s sign show them about Egypt?
21|Three short messages follow. In the first, Isaiah sees a hard vision and shakes with pain. A watchman stands at his post day and night. He sees riders in pairs and hears, “Fallen, fallen is Babylon.” In the second, a voice from Seir asks the watchman about the night. He answers that morning comes, and also night. In the third, people of Tema bring water and bread to those fleeing battle. Within a year the glory of Kedar will fail.|Tema’s people meet the fugitives with water and bread (verse 14). What were the fugitives running from in verse 15?
22|This message is about the “valley of vision,” and it speaks to Jerusalem. The people are on the rooftops shouting, but their rulers fled and were captured. The speaker weeps for the city. Enemy chariots fill the valleys. The people check weapons, break down houses to fix the wall, and store water. They do not look to the one who planned it. They feast and say, “Let’s eat and drink, for tomorrow we will die.” Then Shebna the palace manager loses his place to Eliakim.|The city fixes its walls and stores water (verses 9–11). What does verse 11 say the people left out?
23|This is a message about Tyre. Ships of Tarshish are told to howl, because Tyre’s harbor and houses are gone. Tyre was the market of nations, and grain from the Nile made it rich. Its traders were like princes. Who planned its fall? The LORD of Armies planned it, to shame the pride of all glory. Tyre will be forgotten for seventy years. Then it trades again, and its earnings feed those who live before the LORD.|Tyre’s traders were “the honorable of the earth” (verse 8). What does verse 9 say the LORD planned for that honor?
24|The LORD empties the earth and scatters its people. Priest and people, master and servant, lender and borrower all share the same end. The earth mourns because its people broke the laws and the everlasting covenant. Wine, music, and joy stop, and the city is broken. A few remain, like olives after shaking, and they sing from far coasts. The speaker still cries, “Woe is me!” The earth sways like a drunk man and falls. The LORD punishes powers above and kings below, and he reigns on Mount Zion.|Verse 5 says the earth is polluted “under its inhabitants.” What three things does the verse say they did?
25|The speaker praises the LORD for wonderful things planned long ago. The LORD turned a strong city into a heap. He has been a stronghold for the poor and shade from the heat. On this mountain he will make a rich feast for all peoples. He will destroy the veil that covers all nations. He swallows up death forever and wipes tears from all faces. The people say they waited for this God, and he will save them. Moab’s pride is brought down to the dust.|Sheol opens its mouth for people in 5:14. What does the LORD swallow in 25:8?
26|Judah will sing this song in that day. The singers have a strong city, and salvation is its walls. The LORD keeps a steady mind in peace because it trusts him. He brought the high city down, and the feet of the poor walk on it. The singers say they waited for the LORD through the night. Other lords ruled them, and their own efforts gave birth only to wind. Then comes a promise: “Your dead shall live.” The people are told to hide a little while until the anger passes.|The people say they “gave birth, it seems, only to wind” (verse 18). What does verse 19 promise next?
27|In that day the LORD kills leviathan, the twisting serpent of the sea. In a new vineyard song, the LORD keeps the vineyard and waters it. He says he has no anger. Thorns may be burned or may make peace with him. Jacob will take root, and Israel will fill the world with fruit. Jacob’s sin is forgiven when the altar stones are crushed like chalk. The strong city lies empty. A great trumpet calls the lost from Assyria and Egypt to worship in Jerusalem.|The vineyard in chapter 5 gave wild grapes. What does Israel give in 27:6, and who waters it in verse 3?
28|Woe comes to Ephraim’s drunk leaders, whose crown is a fading flower. A strong one from the Lord will throw it down like a hailstorm. Priests and prophets stagger with drink too. They ask if the teaching is for small children: “line on line, here a little.” Jerusalem’s rulers say they made a covenant with death. The Lord GOD lays a tested cornerstone in Zion and measures with justice. Hail will sweep away their shelter of lies. A farmer does not plow or thresh forever, and this wisdom comes from the LORD.|The rulers hide under a “covenant with death” (verse 15). What does the Lord GOD lay in Zion in verse 16?
29|Woe comes to Ariel, the city where David camped. The LORD will camp against it, and its voice will whisper from the dust. Then its enemies blow away like chaff, like a dream after waking. The prophets are in a deep sleep, and the vision is like a sealed book. The Lord says this people honors him with lips while their hearts are far away. He will do a wonder, and the wisdom of the wise will fail. In a little while the deaf will hear and the blind will see. The humble will rejoice, and Jacob will no longer be ashamed.|This people honors the Lord with their lips (verse 13). Where does the verse say their heart is?
30|The LORD says woe to rebellious children who go to Egypt without asking him. Their envoys carry treasure through a desert, but Egypt’s help is empty. The people tell the prophets to say only pleasant things. So their sin is like a bulging wall that breaks at once. The Lord GOD offered rescue through returning and rest, and they refused. Still the LORD waits to be gracious. A voice will say, “This is the way.” He will heal his people and strike Assyria with his rod.|The Lord GOD says strength is “in quietness and in confidence” (verse 15). What did the people choose in verse 16?
31|Woe comes to those who go down to Egypt for help. They trust many chariots and strong horsemen and do not seek the LORD. The Egyptians are men and not God, and their horses are flesh. When the LORD stretches out his hand, helper and helped fall together. The LORD will fight for Mount Zion like a lion over its prey. He will guard Jerusalem like hovering birds. Israel is called to return and throw away its idols. The Assyrian will fall by a sword that is not a man’s.|Judah trusts chariots “because they are many” (verse 1). What does verse 3 say horses are made of?
32|A king will reign in righteousness, and princes will rule with justice. Each will be like shelter from wind and water in a dry place. Eyes will see, ears will listen, and fools will no longer be called noble. Then the speaker warns the women who feel safe. In little more than a year the grape harvest will fail. Thorns will grow, and the palace and city will be empty. This lasts until the Spirit is poured out from on high. Then justice lives in the land, and its fruit is peace and safe homes.|The women in verse 9 are “at ease.” How is the quietness in verse 17 different from theirs?
33|Woe comes to a destroyer who has not yet been destroyed. The people ask the LORD to be gracious, because they have waited for him. Envoys of peace weep, the roads are empty, and the land withers. The LORD says, “Now I will arise.” Sinners in Zion ask who can live with the burning fire. The answer is one who walks rightly, refuses bribes, and turns from bloodshed. That person will see the king and a quiet Jerusalem. The LORD is judge, lawgiver, and king, and he will save.|Verse 22 calls the LORD judge, lawgiver, and king. What kind of person can live with him in verse 15?
34|All nations are called to listen. The LORD is angry with the nations and their armies. The sky rolls up like a scroll, and its stars fade like leaves. His sword comes down on Edom, with a great slaughter at Bozrah. The LORD has a day of vengeance for Zion’s cause. Edom’s streams turn to pitch, and its smoke rises forever. Owls, ravens, jackals, and snakes take over its palaces. The LORD’s book says not one of these animals will be missing.|The LORD has “a year of recompense for the cause of Zion” (verse 8). Whose case is being settled?
35|The desert will be glad and bloom. It will see the glory of the LORD. Weak hands and shaking knees are to be made strong. The fearful are told that God will come and save them. Then the blind see, the deaf hear, the lame leap, and the mute sing. Water breaks out in the dry land. A road called the Holy Way runs through it, and no lion is there. The LORD’s ransomed people come to Zion singing, and sorrow flees.|The ransomed walk a road with no lion on it (verses 9–10). What flees from them at the end of verse 10?
40|God says, “Comfort, comfort my people.” Jerusalem’s hard service is over, and her sin is pardoned. A voice calls for a level road in the desert for the LORD. Another voice says people are like grass, but God’s word stands forever. Zion is told to say, “Behold, your God!” He comes with power and carries lambs like a shepherd. No one taught him, and no nation or idol compares with him. Jacob says God has missed his case, yet those who wait gain new strength.|Jacob says, “My way is hidden from the LORD” (verse 27). How do verses 28–29 answer him?
41|The LORD calls the far coasts to meet him in court. He asks who raised up a conqueror from the east. The answer is the LORD, the first and with the last. The nations are afraid, and their workers nail idols down so they will not fall. The LORD calls Israel his servant, chosen and not thrown away. He tells Israel not to fear, because he will help and hold it up. He will give water to the poor and trees to the desert. He dares the idols to tell the future, and they cannot.|The nations nail their idol so it will not fall (verse 7). Who holds whom up in verse 10?
42|The LORD presents his servant and puts his Spirit on him. The servant brings justice to the nations without shouting in the street. He does not break a bruised reed or put out a weak wick. He is a light for the nations, to open blind eyes and free prisoners. All the earth is called to sing a new song. The LORD, long silent, goes out like a warrior and leads the blind. Then he calls his own servant blind and deaf. Israel was robbed because it would not walk in his ways.|The servant will not break “a bruised reed” (verse 3). What is he sent to bring in verses 1 and 4?
43|The LORD who made Jacob says not to fear. He has redeemed Israel, called it by name, and says, “You are mine.” He will be with them through water and fire. He will gather their children from east, west, north, and south. The nations are called to court, and Israel is the LORD’s witness. For Israel’s sake he sends to Babylon. He is doing a new thing: a road and rivers in the desert. Israel wore him out with sins, yet he blots them out for his own sake.|The LORD says, “You are mine” (verse 1). What does verse 2 promise in water and fire?
44|The LORD tells Jacob his servant not to fear. He will pour water on dry ground and his Spirit on their children. He is the first and the last, and there is no other God. Then the chapter describes an idol maker. He burns half a tree to cook and bows to the other half. No one stops to think that it is a block of wood. The LORD tells Israel he has wiped out its sins like a cloud. He says Jerusalem will be built, and he names Cyrus as his shepherd.|The LORD calls Cyrus “my shepherd” (verse 28). What two things does the verse say will be built or laid?
45|The LORD speaks to Cyrus, his anointed, and holds his right hand. He will open gates before Cyrus and give him hidden treasure. He does this for Jacob’s sake, though Cyrus has not known him. The LORD says he forms light and darkness, peace and trouble. Woe comes to anyone who argues with his Maker, like clay with a potter. Cyrus will build the city and free the exiles without payment. The LORD did not speak in secret. He calls all the ends of the earth to look to him and be saved.|Cyrus has “not known” the LORD (verse 4). For whose sake does the verse say he is called?
46|Bel and Nebo bow down. Animals carry their idols as heavy loads, and the idols go into captivity. The LORD tells Jacob’s house that he has carried them from birth. He will carry them to old age and gray hair. People pay a goldsmith to make a god, then lift it on their shoulders. It stands where they set it and cannot answer. The LORD declares the end from the beginning. He calls a bird of prey from the east and brings salvation to Zion.|People carry their god on their shoulders (verse 7). Who carries whom in verse 4?
47|Babylon is told to come down and sit in the dust. She will grind flour at the millstones and be called tender no more. The LORD says he gave his people into her hand, and she showed no mercy. She laid a heavy yoke even on the old. She said, “I will be a princess forever.” In one day she will lose both children and husband. Her spells and star readers cannot save her. They burn like stubble, and no one is left to help.|Babylon says, “No one sees me” (verse 10). What did she do to captives in verse 6?
48|The LORD speaks to Jacob’s house, who swear by his name but not in truth. He told them things long ago so they could not credit an idol. Now he tells new things they have not heard. He holds back his anger for his own name’s sake. He has tested them in the furnace of suffering. He says their peace would have been like a river if they had listened. Then the order comes: leave Babylon and shout that the LORD has redeemed Jacob. There is no peace for the wicked.|Israel is called stubborn in verse 4 and told to leave Babylon in verse 20. Why does the LORD act, according to verse 11?
49|The servant speaks to far peoples. The LORD called him before birth and made his mouth like a sharp sword. The servant says he has worked for nothing, yet his reward is with God. The LORD says restoring Israel is too small a task. The servant will be a light to the nations. Captives will come out and be led by springs of water. Zion says the LORD has forgotten her. He answers that a mother may forget her baby, but he will not forget Zion.|Zion says, “The LORD has forsaken me” (verse 14). What two pictures answer her in verses 15–16?
50|The LORD asks for the divorce paper and the name of any lender he owed. He says the people were sold for their own sins. He asks why no one answered when he called. Then a servant speaks. The Lord GOD wakes his ear each morning and gives him words for the weary. He gave his back to those who beat him and did not hide from spitting. He sets his face like flint, because the Lord GOD will help him. Those who fear the LORD are told to trust him in the dark.|The servant’s ear is opened “morning by morning” (verse 4). What does he do with what he hears in verses 5–6?
51|The LORD speaks to those who seek him. Look to Abraham and Sarah, he says: Abraham was one, and God made him many. The LORD will comfort Zion and make her desert like Eden. The sky will fade like smoke, but his salvation lasts forever. A voice calls the LORD’s arm to wake, as when it dried the sea. The LORD asks why they fear men who die like grass. Jerusalem has drunk the cup of his anger to the bottom. He takes the cup from her hand and gives it to those who hurt her.|The LORD made Abraham many when he was “but one” (verse 2). What does verse 3 say he will do for Zion’s waste places?
52|Zion is told to wake, put on fine clothes, and shake off the dust. The LORD says she was sold for nothing and will be bought back without money. His people were taken away, and his name is mocked all day. So they will know his name. A messenger runs on the mountains with good news: “Your God reigns!” The watchmen sing as the LORD returns to Zion. The people leave without rushing, with the LORD ahead and behind. The LORD says his marred servant will be lifted very high.|The messenger tells Zion that her God reigns (verse 7). Who was ruling over the people in verse 5?
53|A group speaks and asks who has believed their message. The servant grew like a root in dry ground, with no beauty to draw them. People despised him, and the speakers did not respect him. They thought God was striking him. But he carried their sickness and was pierced for their wrongs. Like a silent lamb, he did not open his mouth. He was cut off and buried with the wicked, though he had done no violence. After his suffering he will see light, and he will make many righteous.|The speakers first thought the servant was “struck by God” (verse 4). What do they say he carried?
54|A woman with no children is told to sing. She will have many children, so she must make her tent bigger. She will forget the shame of her youth. Her Maker is her husband and her Redeemer. He left her for a short moment and gathers her with great mercy. As he swore about Noah’s flood, he swears not to be angry with her. He will rebuild her with jewels, and the LORD will teach her children. No weapon made against her will succeed.|Mountains may move, but two things will not leave (verse 10). What are they?
55|The LORD calls everyone who is thirsty to come to the water. Those with no money may buy wine and milk without price. He asks why they spend money on what is not bread. If they listen, they will live, and he will make a lasting covenant with them. They should seek the LORD while he is near and return for pardon. His thoughts are higher than theirs, as the sky is above the earth. His word is like rain: it does what he sends it to do. They will go out with joy, and the trees will clap.|The LORD says to buy “without money and without price” (verse 1). What are people spending money on in verse 2?
56|The LORD says to keep justice, because his salvation is near. The one who keeps the Sabbath and does no evil is blessed. A foreigner should not say the LORD will shut him out. A eunuch, a man who cannot father children, should not call himself a dry tree. The LORD will give faithful eunuchs a name better than sons and daughters. He will bring foreigners who hold to his covenant to his holy mountain. His house will be called a house of prayer for all peoples. But Israel’s watchmen are blind, like dogs that cannot bark.|A foreigner fears the LORD will “separate me from his people” (verse 3). What does verse 7 promise instead?
57|Good people die, and no one thinks about it. They enter peace. Then the LORD charges others with worship under trees and killing children in the valleys. They set their bed on a high mountain and sent envoys far away. Their collected idols cannot save them, and a breath will carry them off. A voice says to clear the road for God’s people. The high and holy One says he also lives with the humble. He will not be angry forever and will heal, but the wicked have no peace.|The high and lofty One lives in two places (verse 15). What does he do for the humble there?
58|The LORD tells the speaker to shout Israel’s sins like a trumpet. The people seek him daily and ask why he ignores their fasts. He answers that on fast days they push their workers and fight. Bowing the head like a reed is not the fast he chose. His fast is to free the oppressed and break every yoke. It is to feed the hungry, house the poor, and clothe the naked. Then their light will break out, and he will answer, “Here I am.” If they honor the Sabbath, they will delight in the LORD.|The people ask why God ignores their fast (verse 3). What fast does he choose in verses 6–7?
59|The LORD’s hand is not too short to save, and his ear can hear. The people’s sins have come between them and God. Their hands shed blood, their lips lie, and no one goes to court honestly. Then the people speak: they look for light and walk in darkness. They admit that truth has fallen in the street. The LORD sees that there is no justice and no one to step in. So his own arm saves, and he puts on righteousness like armor. A Redeemer will come to Zion, to those in Jacob who turn from wrong.|The LORD “wondered that there was no intercessor” (verse 16). What does he do when no one steps in?
60|Zion is told to rise and shine, because her light has come. Darkness covers the earth, but the LORD’s glory rises on her. Nations and kings come to her light. Her sons and daughters come home from far away. Camels bring gold and frankincense, and ships bring her children. Foreigners rebuild her walls, and her gates stay open day and night. Peace and righteousness will rule her, and violence will end. The LORD will be her lasting light in place of sun and moon.|Nations come to Zion’s light (verse 3). Whose light does verse 1 say it is?
61|A speaker says the Lord GOD’s Spirit is on him. The LORD has anointed him to bring good news to the humble. He is sent to heal broken hearts and announce freedom to captives. He proclaims the year of the LORD’s favor and comforts those who mourn. They get a garland in place of ashes and will rebuild old ruins. They will be called the LORD’s priests. The LORD says he loves justice and will make a lasting covenant with them. The speaker rejoices, clothed in salvation like a bride or groom.|The speaker is sent to “proclaim liberty to the captives” (verse 1). What do the freed people do in verse 4?
62|The speaker will not keep quiet until Zion’s righteousness shines like dawn. Nations and kings will see it, and the LORD will give her a new name. She will no longer be called Forsaken, or her land Desolate. Her new names are Hephzibah and Beulah, because the LORD delights in her. God will rejoice over her as a groom over a bride. Watchmen on the walls must give the LORD no rest. He swears that enemies will no longer eat her grain. The people will be called the Holy People, the LORD’s Redeemed.|Zion called herself forsaken in 49:14. What two new names does she get in 62:4, and why?
63|A watcher asks who comes from Edom in red clothes. The one coming says he trod the wine press alone, in anger, with no helper. Then a speaker recalls the LORD’s loving kindness to Israel. He became their Savior and carried them in the old days. But they rebelled and grieved his Holy Spirit, and he fought against them. The people remember Moses and the sea. They ask God to look down, calling him “our Father.” They ask why enemies have trampled his holy place.|Verse 9 says, “In all their affliction he was afflicted.” What did the people do next in verse 10?
64|The prayer goes on. The people ask God to tear the heavens and come down, as he once did. No eye has seen a God like him, who works for those who wait. They confess long sin and ask, “Shall we be saved?” All their right acts are like a dirty cloth, and they fade like leaves. No one calls on his name. Still they call him Father and potter, and themselves clay. Zion is a wilderness, the temple is burned, and they ask for an answer.|The people call their right acts “a polluted garment” (verse 6). What do they call God in verse 8?
65|The LORD says he let himself be found by people who did not seek him. All day he held out his hands to a rebellious people. They offer sacrifices in gardens, sit among graves, and eat pig’s meat. He will repay them, yet he spares some, like a good grape cluster. His servants will eat and sing, and those who left him will go hungry. Then he says he creates new heavens and a new earth. People will build houses and live in them, and plant vineyards and eat. Wolf and lamb will feed together.|In the new earth, people “will not build and another inhabit” (verse 22). What loss from chapter 1 does that undo?
66|The LORD says heaven is his throne and earth his footstool. He asks what house people could build for him. He looks to the one who is poor, sorry, and trembles at his word. He rejects offerings from those who choose their own ways. Zion gives birth to a nation in one day, before her pain comes. The LORD will comfort Jerusalem as a mother comforts her child. He comes with fire to judge, and gathers all nations to see his glory. All flesh will worship him, and the rebels’ bodies lie outside.|The LORD asks what house anyone could build for him (verse 1). To whom does he look in verse 2?
`.trim().split('\n').map(line => {
  const [chapter, summary, question] = line.split('|');
  return [Number(chapter), {summary, question}];
});
const simpleNoteByChapter = new Map(simpleNotes);
for (const note of notes) Object.assign(note, simpleNoteByChapter.get(note.chapter));

export function addFullIsaiah(content, scripture) {
  const web = content.sources.find(s => s.id === 'web');
  web.title = 'Isaiah — World English Bible';
  web.summary = 'The complete book of Isaiah in the public-domain World English Bible. Chapter notes distinguish the biblical account from historical evidence.';
  web.url = 'https://ebible.org/engwebp/ISA01.htm';
  for (const note of notes) {
    const c = note.chapter, sourceId = `web${c}`;
    content.sources.push({id:sourceId,title:`Isaiah ${c} — World English Bible`,author:'World English Bible project',year:'2026 retrieval',type:'Biblical text',url:`https://ebible.org/engwebp/ISA${String(c).padStart(2,'0')}.htm`,summary:note.summary,limitations:'This source gives the Bible text. The notes and questions are original study material. The notes are study help, not proof from history.',license:'Public domain'});
    const lesson = c <= 12 ? 38 : c <= 35 ? 39 : c <= 49 ? 40 : c <= 57 ? 41 : 42;
    const direct = !(c >= 15 && c <= 21 || c === 23 || c >= 31 && c <= 34);
    const lds = {
      text:`${note.question} ${direct ? 'Read the linked Come, Follow Me lesson for the Church study perspective.' : 'The linked Come, Follow Me lesson covers nearby chapters. This question comes from the study guide. The lesson does not teach this chapter.'}`,
      sourceIds:[sourceId,`cfm2026-${lesson}`]
    };
    content.passages.push({id:`isaiah-${c}`,chapter:c,start:1,end:scripture.chapters[c].length,title:note.title,summary:note.summary,year:null,dateLabel:'Literary context · no assigned event year',uncertainty:'',placeIds:note.placeIds,sourceIds:[sourceId],lds});
  }
  // Link existing conference evidence directly to the chapters it cites.
  for (const passage of content.passages) {
    const matching = content.sources.filter(s => s.group === 'conference-year' && s.scriptureReferences?.some(ref => {
      const match = ref.label.match(/Isaiah\s+(\d+)(?=\D|$)/i);
      return match && Number(match[1]) === passage.chapter;
    }));
    if (matching.length) {
      passage.lds.sourceIds = [...new Set([...passage.lds.sourceIds, ...matching.map(s => s.id)])];
      passage.lds.text += ' The linked conference talks cite this chapter. See each source summary for its use of the passage.';
    }
  }
  content.passages.sort((a,b) => a.chapter-b.chapter || a.start-b.start);
  for (const [chapter, sourceId] of [[28,'dm-line'],[53,'dm-isaiah53']]) {
    content.passages.find(p => p.chapter === chapter).sourceIds.push(sourceId);
  }
  content.editorial.status = 'Complete reading text with original chapter notes. Historical research and language notes remain selected, not exhaustive.';
  content.editorial.periodNote = 'The timeline covers selected events from 780–539 BCE. It does not date every passage. It also does not show every proposed date for when parts of Isaiah were written.';
  content.guides.push(
    {id:'justice',title:'Worship and justice',description:'Trace care for vulnerable people across Isaiah.',steps:[
      {title:'Learn to do good',text:'Read Isaiah 1:10–20. Compare the criticism of worship with the command to defend vulnerable people.',chapter:1,verse:17,placeId:'jerusalem',sourceIds:['web1']},
      {title:'The vineyard',text:'Read Isaiah 5:1–7. Identify the fruit the vineyard owner expected and what he received.',chapter:5,verse:7,placeId:'jerusalem',sourceIds:['web5']},
      {title:'The chosen fast',text:'Read Isaiah 58:3–12. Name the actions that make worship visible in daily life.',chapter:58,verse:6,placeId:'jerusalem',sourceIds:['web58']}
    ]},
    {id:'comfort',title:'Comfort and return',description:'Follow images of strength, remembrance, and renewed belonging.',steps:[
      {title:'Strength for the weary',text:'Read Isaiah 40:27–31. Notice how the reply addresses the complaint that God does not see the people.',chapter:40,verse:31,placeId:'jerusalem',sourceIds:['web40']},
      {title:'Zion remembered',text:'Read Isaiah 49:14–18. Compare Zion’s complaint with the images in God’s answer.',chapter:49,verse:15,placeId:'jerusalem',sourceIds:['web49']},
      {title:'A covenant of peace',text:'Read Isaiah 54:7–17. Consider how the promise answers abandonment and fear.',chapter:54,verse:10,placeId:'jerusalem',sourceIds:['web54']}
    ]},
    {id:'servant',title:'Read the servant passages',description:'Compare the servant’s work, suffering, and vindication.',steps:[
      {title:'Justice without crushing',text:'Read Isaiah 42:1–9. Describe the servant’s task and manner. Keep questions of identity separate from these observations.',chapter:42,verse:1,sourceIds:['web42']},
      {title:'A wider mission',text:'Read Isaiah 49:1–6. Notice how the passage names Israel and also describes restoring Israel.',chapter:49,verse:6,sourceIds:['web49']},
      {title:'Suffering and vindication',text:'Read Isaiah 52:13 through 53:12. Track the speakers and how their view of the servant changes. Compare Christian interpretation in LDS mode.',chapter:53,verse:4,sourceIds:['web52','web53']}
    ]}
  );
}
