"""Write compressed WebP copies beside the master images in dist/assets.

The PNG and JPEG files stay in place as masters and as page fallbacks.
Pages request the WebP copies first. Run this script after any image change.

    python scripts/optimize-images.py           # write missing or stale copies
    python scripts/optimize-images.py --force   # write every copy again
"""
import base64, io, json, re, sys
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'dist/assets'
MASTER_TYPES = {'.png', '.jpg', '.jpeg'}
# Portrait copies by short side: avatar, directory card, large card.
PORTRAIT_SIZES = {'-192': 192, '-480': 480, '': 960}
PHOTO_LONG_SIDE = 1600
# The map overlay keeps its measured resolution.
FULL_SIZE = {'relief.png'}
SKIPPED_FOLDERS = {'trailer'}


def plan(master):
    """Return (output path, resize rule, quality) for each copy of one master."""
    relative = master.relative_to(ASSETS)
    folder = relative.parts[0] if len(relative.parts) > 1 else ''
    if folder == 'portraits':
        return [(master.with_name(f'{master.stem}{suffix}.webp'), ('short', size), 80) for suffix, size in PORTRAIT_SIZES.items()]
    if folder == 'terrain':
        return [(master.with_suffix('.webp'), None, 82)]
    rule = None if relative.name in FULL_SIZE else ('long', PHOTO_LONG_SIDE)
    return [(master.with_suffix('.webp'), rule, 82)]


def masters():
    return sorted(p for p in ASSETS.rglob('*') if p.suffix.lower() in MASTER_TYPES
                  and p.relative_to(ASSETS).parts[0] not in SKIPPED_FOLDERS)


def resized(image, rule):
    if not rule: return image
    side, limit = rule
    current = min(image.size) if side == 'short' else max(image.size)
    if current <= limit: return image
    scale = limit / current
    return image.resize((max(1, round(image.width * scale)), max(1, round(image.height * scale))), Image.LANCZOS)


def convert(job):
    master, force = job
    written = 0
    stamp = master.stat().st_mtime
    outputs = [o for o in plan(master) if force or not o[0].exists() or o[0].stat().st_mtime < stamp]
    if not outputs: return 0
    with Image.open(master) as source:
        image = source.convert('RGBA' if 'A' in source.getbands() or 'transparency' in source.info else 'RGB')
    for output, rule, quality in outputs:
        resized(image, rule).save(output, 'WEBP', quality=quality, method=5)
        written += 1
    return written


def cover_placeholders():
    """Write tiny blurred previews for the directory covers named in books.js."""
    block = re.search(r'const bookArtwork=\{(.*?)\};', (ROOT / 'dist/books.js').read_text(encoding='utf-8'), re.S)[1]
    previews = {}
    for artwork in sorted(set(re.findall(r':\s*"([^"]+)"', block))):
        with Image.open(ASSETS / 'portraits' / artwork) as source:
            small = resized(source.convert('RGB'), ('short', 20))
        data = io.BytesIO()
        small.save(data, 'WEBP', quality=45, method=6)
        previews[artwork] = 'data:image/webp;base64,' + base64.b64encode(data.getvalue()).decode()
    text = '// Generated by scripts/optimize-images.py. Do not edit.\nexport default ' + json.dumps(previews, indent=0) + ';\n'
    (ROOT / 'dist/book-cover-placeholders.js').write_text(text, encoding='utf-8', newline='\n')
    return len(previews)


if __name__ == '__main__':
    force = '--force' in sys.argv
    jobs = [(master, force) for master in masters()]
    stems = [master.with_suffix('') for master, _ in jobs]
    assert len(stems) == len(set(stems)), 'Two masters share one name. Their WebP copies would collide.'
    with ProcessPoolExecutor() as pool:
        written = sum(pool.map(convert, jobs, chunksize=32))
    print(f'Checked {len(jobs)} masters. Wrote {written} WebP copies.')
    print(f'Wrote {cover_placeholders()} directory cover previews.')
