"""Maintain Third John's distinct people and limited evidence."""
import json
from book_common import ROOT
date='2026-10-07'
rows=[('gaius-letter','Gaius','Recipient praised for faithful welcome and help given to traveling believers','The elder rejoices at reports about his conduct and asks him to continue his support.','His hospitality makes received truth visible through help for people beyond his familiar circle.'),('diotrephes','Diotrephes','Assembly member accused of rejecting the elder and excluding people who welcome the brothers','The elder says he loves to be first and refuses the visiting brothers.','His conduct introduces a conflict over welcome and authority without preserving his own account.'),('demetrius-letter','Demetrius','Person recommended through testimony about his conduct','The elder adds his own testimony to the good report from others.','His recommendation gives Gaius a positive example beside the warning about Diotrephes.')]
people=[dict(id=i,name=n,reuse='3-john',role=ro,relations=re,meaning=m,chapters=[1],passages='Third John 1',linkNames=[n]) for i,n,ro,re,m in rows]
cfm=dict(id='cfm-nt-2023-49',reuse='1-john',summary='The lesson connects joy with helping others walk in truth and warns against harmful conduct.',chapterCoverage=[1],limits='Third John coverage follows actual discussion of 1:1–4 and 9–11. Linked Restoration texts and reference entries were not independently reviewed.',reviewed=dict(date=date,scope='Complete shared lesson body and resource list read. Only its actual Third John discussion supports this reference.'))
sch=dict(id='usccb-3-john',title='Introduction to the Third Letter of John',url='https://bible.usccb.org/bible/3john/0',author='United States Conference of Catholic Bishops',publisher='United States Conference of Catholic Bishops',category='Scholarly study',perspective='historical',summary='The introduction offers several possible motives for Diotrephes\x27 refusal.',limits='These are competing interpretations rather than established motives. Historical authorship, exact local offices, audience conditions, and Demetrius\x27 possible delivery role were not independently verified.',chapterCoverage=[1],reviewed=dict(date=date,scope='Complete three-paragraph introduction read through indexed source text. The guide attributes its range of possible motives and preserves uncertainty.'))
cfg=dict(name='3 John',code='3JN',date=date,verseCounts=[14],nextBook='jude',description='Faithful welcome · shared support · disputed authority · personal testimony',limits='The elder has no assigned personal identity. Gaius and Demetrius are not identified with same-name people elsewhere. Historical authorship, dates, Greek forms, exact local setting, and the opposing party\x27s own account were not independently verified.',review='All fourteen WEB verses read for an original explanation and exact selection. Three selected named profiles use newly inspected artwork and remain separate from same-name people elsewhere. The travelers have no invented route or destination. Competing USCCB readings remain attributed. Actual Church discussion remains separate.',sources=[cfm,sch],people=people,places=[],chapters={'1':dict(question='How does support for visiting believers make a host a fellow worker for truth?',teaching='The selected Church lesson connects joy with helping others walk in truth.',ldsSources=[cfm['id']],historicalSources=[sch['id']])})
(ROOT/'scripts/book-records/3-john.json').write_text(json.dumps(cfg,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
