"""Use matched existing art and distinct prompts for new Nehemiah profiles."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parent.parent
OUT=ROOT/'dist/data/books'
book=json.loads((OUT/'nehemiah.json').read_text(encoding='utf8'))
prior={}
for f in OUT.glob('*-art.json'):
 if f.stem!='nehemiah-art':prior.update(json.loads(f.read_text(encoding='utf8')))
records={p['id']:dict(prior[p['id']]) for p in book['people'] if p['id'] in prior}
faces=['broad square face, short salt-and-pepper beard, cropped curls','long oval face, shaved cheeks, loose dark waves','round face, neat black beard, high forehead','angular face, silver beard, receding hair','high cheekbones, trimmed copper-gray beard, short curls','wide nose, dark stubble, swept hair','narrow face, full gray beard, deep-set eyes','soft oval face, clean-shaven cheeks, thick straight hair']
poses=['standing waist-up with one open hand','seated half-body with relaxed hands','close chest-up with head turned left','side profile beside a doorway','waist-up leaning against a low wall','close three-quarter portrait looking slightly upward','half-body looking down at a plain rolled cloth','standing half-body with shoulders turned and face toward the viewer']
colors=['teal and flax','ochre and indigo','plum and olive','rust and cream','sage and charcoal','copper and blue-gray','burgundy and sand','navy and pale green']
settings=['a pale limestone courtyard in cool dawn light','a shaded plaster room with violet shadows','an olive grove in soft green light','a stone doorway in warm late sunlight','rose-colored hills at dusk','a quiet garden with pale blue morning sky','a woven shelter with soft amber light','a shaded wall beside green vines']
groups={
 'wall-builders':'Exactly four distinct adult ancient Levantine workers, two men and two women, modest rust, indigo, cream, and olive woven clothes. One woman sits beside a stone block, one stands sideways, an older bearded man holds a plain wooden tool low, and a younger clean-shaven man faces the wall. Waist-up framing, attentive calm expressions, sunlit limestone work area, varied face shapes. No crowd or text.',
 'shallum-daughters':'Exactly one middle-aged ancient Levantine father and two distinct adult daughters, fully clothed in modest woven sage, copper, and blue clothes. Father with broad face and short gray beard stands behind. One daughter has dark curls and a round face, the other a long face and straight hair. Half-body group beside a low stone wall, relaxed working poses, focused gentle expressions, cool morning light. No additional people.',
 'debt-families':'Respectful group portrait of two adult ancient Levantine parents and two children, fully clothed in cream, olive, rust, and muted blue woven clothes. Mother with round face sits with a child beside her; father with long face and cropped beard stands sideways with the other child. Quiet thoughtful expressions, shaded courtyard with a small grain basket, half-body view. No chains, distress spectacle, tears, text, or additional people.',
 'law-teachers':'Exactly three distinct adult ancient Levantine men in modest indigo, flax, and sage woven clothes, waist-up around one plain unmarked scroll. One older gray-bearded man sits in profile, a clean-shaven younger man looks downward, a broad-faced dark-bearded man listens. Quiet stone courtyard, soft afternoon blue shadows, composed expressions. No lettering or additional figures.',
 'covenant-families':'Exactly four ancient Levantine people, two distinct adult women, one adult man, and one child, fully clothed in modest plum, olive, cream, and blue woven clothes. Waist-up informal group beneath a leafy shelter, one woman seated, the other standing sideways, man with shaved cheeks behind, child beside seated woman. Calm attentive expressions, warm pale evening light. No additional people or writing.',
 'city-settlers':'Exactly two distinct adult ancient Levantine women and one adult man, fully clothed in modest copper, teal, and flax woven clothes. One older woman with gray curls sits beside a wicker basket, a younger woman with long dark hair stands in side profile, and a square-faced bearded man leans at a stone doorway. Waist-up portrait, peaceful hopeful expressions, pale blue dawn light. No text or crowd.',
 'wall-singers':'Exactly three distinct adult ancient Levantine male singers in modest green, indigo, and ochre woven clothes. An older broad-faced silver-bearded man holds a small plain lyre at waist height, a younger clean-shaven oval-faced man turns sideways, and a dark-bearded long-faced man looks up slightly. Half-body group beside limestone, joyful restrained expressions, warm afternoon light. No text or extra figures.',
 'foreign-families-nehemiah':'Exactly two distinct adult ancient Near Eastern women and two children, all fully clothed in modest teal, plum, flax, and rust woven clothes. One woman with oval face and dark waves stands in profile, the other with a broad face and short curls sits beside a child. The second child stands beside the first woman. Half-body family portrait in a garden with pale green vines and lavender shadows, thoughtful calm expressions. No distress spectacle, text, extra people, or claimed national appearance.',
 'noadiah-prophetess':'Mature ancient Levantine woman with angular face, gray-threaded dark curls, steady serious gaze, modest plum woven tunic and pale green shawl. Seated waist-up in three-quarter view, one hand relaxed on her knee, pale limestone bench beside olive trees, cool blue-green afternoon light. No male figure, text, or halo.'}
manifest_path=ROOT/'scripts/nehemiah-generated-portraits.json'
manifest=json.loads(manifest_path.read_text(encoding='utf8')) if manifest_path.exists() else {}
for j,p in enumerate(book['people']):
 if p['id'] in records or p['id'] in manifest:continue
 scene=groups.get(p['id'],f'One adult ancient Levantine man with {faces[j%8]}, {poses[(j+2)%8]}, modest woven clothes in {colors[(j+3)%8]}, {settings[(j+5)%8]}, {["thoughtful direct gaze","gentle listening expression","serious lowered gaze","slight warm smile"][j%4]}.')
 manifest[p['id']]=dict(name=p['name'],prompt=f'Create a finished Bible study portrait of {p["name"]}, {p["role"]}. '+scene+' Painterly realistic illustration, visible brush texture, natural human anatomy. Distinct faces, specified composition and color. Keep faces high enough for a square top-centered crop. One composition, no grid, lettering, modern objects, medieval armor, graphic violence, halo, or claim of known likeness.',src=f'assets/portraits/nehemiah/{p["id"]}.png',mode='built-in image generation')
for pid,item in manifest.items():
 if (ROOT/'dist'/item['src']).exists():records[pid]=dict(src=item['src'],generated=True,title=item['name']+' · interpretive portrait',credit='AI-generated illustration',license='Generated artwork',note='Artistic interpretation. Appearance, age, and setting are not verified historical evidence.')
manifest_path.write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
(OUT/'nehemiah-art.json').write_text(json.dumps(records,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
print('Portraits available:',len(records),'Remaining:',[p['id'] for p in book['people'] if p['id'] not in records])
