"""Distinct directions for Job's people and groups."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parent.parent
OUT=ROOT/'dist/data/books'
book=json.loads((OUT/'job.json').read_text(encoding='utf8'))
genesis=json.loads((OUT/'genesis-art.json').read_text(encoding='utf8'))
records={'adam':dict(genesis['adam'])}
scenes={
'job':'One mature ancient Near Eastern man with a narrow weathered face, short gray beard and cropped dark-gray hair. Seated waist-up on a low stone, shoulders slightly bent, one hand open in a questioning gesture. Modest coarse flax tunic and indigo cloth, tired but attentive expression, soft rose desert hills and gray-green evening sky. Subtle healed skin marks, no graphic wounds.',
'job-wife':'One mature ancient Near Eastern woman, broad face, deep-set brown eyes, dark hair with gray threads beneath a cream cloth. Close three-quarter chest-up view, modest rust and sage woven clothing, weary concerned expression, pale courtyard wall with cool lavender shade. Natural mature proportions.',
'eliphaz-job':'One elderly ancient Near Eastern man, long silver beard, bald crown, strong brow and angular cheeks. Standing half-body in side view, one hand raised low as if explaining, modest plum and ochre woven clothes. Confident serious expression, blue-gray stone doorway with warm sunset edges.',
'bildad':'One older ancient Near Eastern man, wide rounded face, short dark beard with gray at the chin, close curled hair. Seated chest-up front view with head tilted slightly left, modest olive and cream clothes. Firm thoughtful expression, reed-lined room, soft copper light.',
'zophar':'One mature ancient Near Eastern man, narrow face, straight dark hair and clean-shaven cheeks. Standing waist-up turned right, arms resting loosely, modest navy and pale terracotta robes. Intent restrained expression, green hillside and pale blue morning sky.',
'elihu-job':'One young adult ancient Near Eastern man, round face, short black curls, slight stubble, warm brown skin. Seated half-body leaning forward with one open hand, modest teal and sand woven clothing. Eager focused expression, shaded clay courtyard and warm cream light. Clearly an adult.',
'barachel-family-job':'Exactly two distinct adult ancient Near Eastern men as a representative family portrait. An older broad-faced man with white beard seated in profile, and a middle-aged long-faced man with black beard standing behind. Modest charcoal and sage clothing, calm expressions, pale plaster wall, soft blue-green reflected light.',
'job-first-children':'Exactly ten young adult ancient Near Eastern siblings, seven men and three women, all fully clothed. Two-depth waist-up group beside a courtyard table, six seated and four standing, ten separated visible heads. Different faces, hairstyles and modest rust, olive, cream, indigo, plum, teal and ochre garments. Quiet warm expressions, pale garden vines, soft morning light. Peaceful portrait, no disaster or death.',
'job-messengers':'Exactly four distinct adult ancient Near Eastern male messengers, waist-up informal group. One graying bearded elder seated in profile, one young round-faced clean-shaven man, one broad-faced dark-bearded man turned sideways, and one angular man with short stubble. Modest flax, muted blue, rust and olive clothes. Worried but restrained expressions, pale hills and cool dusty violet sky. No graphic harm.',
'sabeans-job':'Exactly three distinct adult ancient Near Eastern male travelers as representative Sabean raiders, waist-up group, varied dark beards and faces. Modest ochre, pale blue and charcoal clothing, one seated and two standing in different directions. Neutral expressions, warm rocky desert and muted green-gray sky. No ethnic caricature, weapons, violence or plunder.',
'chaldeans-job':'Exactly three distinct adult ancient Near Eastern men as representative Chaldean raiders, waist-up group. One wide-faced gray-bearded elder in indigo seated, one long-faced clean-shaven man in cream standing sideward, one round-faced man with dark beard in burgundy. Quiet neutral expressions, pale clay wall and cool teal shadows. No ethnic caricature, weapons, violence or plunder.',
'jemimah':'One adult young ancient Near Eastern woman, rounded face, wide-set brown eyes and tight dark curls loosely gathered. Standing waist-up front view with shoulders gently angled, modest sage dress and cream shawl. Warm quiet smile, pale ochre courtyard with green leaves, early sunlight. No crown or jewelry display.',
'keziah':'One adult young ancient Near Eastern woman, long oval face, arched brows, straight black hair in a loose braid. Seated half-body looking left, modest plum dress and pale blue outer cloth, hands relaxed separately. Thoughtful soft expression, rose stone bench and blue-green garden shade. No crown.',
'keren-happuch':'One adult young ancient Near Eastern woman, broad cheeks, strong nose, large dark eyes and short loose black waves. Close chest-up three-quarter right view, modest ochre and deep teal clothes. Composed attentive expression, lavender-gray hills under pale blue dawn sky. No crown.',
'job-later-sons':'Exactly seven distinct adult ancient Near Eastern brothers, waist-up informal two-row group, three seated and four standing, all seven heads visible. Different faces, hair and beard styles, modest cream, rust, navy, sage, plum, charcoal and pale blue clothes. Gentle thoughtful expressions, shaded courtyard with reed baskets and warm reflected light.',
'job-siblings':'Exactly four mature ancient Near Eastern adults as representative brothers, sisters and acquaintances, two women and two men. One silver-haired woman seated near a dark-bearded man, an older gray-bearded man standing sideways beside a dark-haired woman. Modest indigo, flax, olive and muted copper garments. Concerned kind expressions, pale stone doorway, soft blue morning shade.',
'satan-job':'One adult male figure as a restrained artistic personification of the accuser in Job, no claim of historical appearance. Narrow angular face, short black beard, dark curls, near-profile chest-up framing. Modest charcoal and muted gold ancient woven garments, questioning composed expression, abstract pale blue and gray cloud-like background. Human anatomy, no horns, wings, red skin, monster traits, throne, flames or violence.'}
manifest_path=ROOT/'scripts/job-generated-portraits.json'
manifest=json.loads(manifest_path.read_text(encoding='utf8')) if manifest_path.exists() else {}
for p in book['people']:
 if p['id'] in records:continue
 manifest.setdefault(p['id'],dict(name=p['name'],prompt=f'Create a finished Bible study portrait of {p["name"]}, {p["role"]}. '+scenes[p['id']]+' Painterly realistic illustration with visible brush texture, natural anatomy and modest ancient clothing. Keep faces high enough for a square top-centered crop. One composition, no grid, visible writing, modern objects, medieval armor, halos or claim of known likeness.',src=f'assets/portraits/job/{p["id"]}.png',mode='built-in image generation'))
for pid,item in manifest.items():
 if (ROOT/'dist'/item['src']).exists():records[pid]=dict(src=item['src'],generated=True,title=item['name']+' · interpretive portrait',credit='AI-generated illustration',license='Generated artwork',note='Artistic interpretation. Appearance, age, and setting are not verified historical evidence.')
manifest_path.write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
(OUT/'job-art.json').write_text(json.dumps(records,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
print('Portraits available:',len(records),'Remaining:',[p['id'] for p in book['people'] if p['id'] not in records])
