"""Maintain James's selected profiles and actual source coverage."""
import json
from book_common import ROOT
date='2026-10-07';people=[]
rows=[
('james-letter','James','james','Named letter speaker who addresses the twelve tribes in their scattering','He calls himself a servant of God and of the Lord Jesus Christ.','His instruction tests received faith through speech, fair treatment, and practical care.',[1,2,3,4,5]),
('jesus','Jesus Christ','matthew','Lord named in the greeting and the warning against favoring wealthy visitors','The hearers\x27 faith in him must not accompany preference based on clothing or wealth.','His named place grounds the challenge to unequal treatment within the assembly.',[1,2]),
('abraham','Abraham','genesis','Father whose offering of Isaac supplies an example of faith working through action','The speaker joins his trust, action, and description as God\x27s friend.','His example connects professed trust with conduct that completes its expression.',[2]),
('isaac','Isaac','genesis','Son named in the example of Abraham\x27s offering','His place appears within the argument that Abraham\x27s faith worked through action.','His brief mention makes the example concern a costly act rather than words alone.',[2]),
('rahab','Rahab','joshua','Woman whose reception and sending of the messengers supplies an example of active faith','The speaker places her example beside Abraham\x27s offering.','Her different circumstances widen the argument about faith expressed through action.',[2]),
('job','Job','job','Enduring sufferer recalled beside the Lord\x27s compassion and mercy','The speaker asks the hearers to remember his endurance and its outcome.','His example supports patience without making present suffering evidence of abandonment.',[5]),
('elijah','Elijah','1-kings','Prophet whose prayer and received rain supply an example of effective prayer','The speaker stresses that his nature was like that of the hearers.','His example connects shared human limits with the call to pray for one another.',[5])]
for pid,name,reuse,role,rel,meaning,cc in rows:
 p=dict(id=pid,name=name,reuse=reuse,role=role,relations=rel,meaning=meaning,chapters=cc,passages='James '+', '.join(map(str,cc)))
 if pid=='jesus':p['linkNames']=['Jesus','Christ']
 people.append(p)
cfm=dict(id='cfm-nt-2023-47',title='November 13–19 · James',url='https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-sunday-school-new-testament-2023/47?lang=eng',author='The Church of Jesus Christ of Latter-day Saints',publisher='The Church of Jesus Christ of Latter-day Saints',year=2023,category='LDS Come, Follow Me',perspective='lds',summary='The lesson joins seeking wisdom, patient endurance, active faith, and responsible words.',limits='Coverage follows actual discussion of chapters one, two, three, and five. Its Joseph Smith application remains Church teaching. Linked Restoration passages, a talk, and a video were not independently reviewed.',chapterCoverage=[1,2,3,5],reviewed=dict(date=date,scope='Complete lesson body read. Its teaching sections discuss wisdom, endurance, faith and works, fair treatment, and speech.'))
sch=dict(id='sigmon-james',title='Commentary on James 2:1-10 [11-13] 14-17',url='https://www.workingpreacher.org/commentaries/revised-common-lectionary/ordinary-23-2/commentary-on-james-21-10-11-13-14-17-5',author='Casey Thornburgh Sigmon',publisher='Luther Seminary',year=2021,category='Scholarly study',perspective='historical',summary='Sigmon connects preference for wealth with a gap between professed faith and conduct.',limits='This is Sigmon\x27s interpretation. Broader economic generalizations, ancient literature, modern political claims, and linked campaign material were not independently verified.',chapterCoverage=[2],reviewed=dict(date=date,scope='Complete commentary body read. The guide attributes her connection between preference for wealth and conduct that contradicts professed faith.'))
questions=['Why does the mirror example make hearing without action a form of self-deception?','How does the unmet need for food test a spoken claim to faith?','Why does blessing God conflict with cursing people made in God\x27s image?','How does uncertainty about tomorrow challenge both boasting and delayed good work?','How do withheld wages and shared prayer make endurance include care for other people?']
chapters={str(n):dict(question=q) for n,q in enumerate(questions,1)}
for n,t in [(1,'The selected Church lesson applies asking for wisdom to Joseph Smith\x27s experience.'),(2,'The selected Church lesson joins active faith with love regardless of outward appearance.'),(3,'The selected Church lesson teaches words that help people rather than cause harm.'),(5,'The selected Church lesson joins patient endurance with fair treatment of others.')]:chapters[str(n)].update(teaching=t,ldsSources=[cfm['id']])
chapters['2']['historicalSources']=[sch['id']]
cfg=dict(name='James',code='JAS',date=date,verseCounts=[27,26,18,17,20],nextBook='1-peter',description='Wisdom · active faith · fair treatment · speech · shared care',limits='James is the named letter speaker. His identification with a specific historical James, authorship, dates, Greek forms, manuscripts, exact addressed communities, and a full harmony with other letters were not independently verified. The unnamed trading city remains unlocated.',review='All 108 verses read for five original contextual explanations and exact selections. Seven selected profiles do not claim exhaustive coverage. The speaker is not securely identified with another James. No unnamed city is assigned a location. Actual lesson discussion supplies Church scope. Sigmon\x27s interpretation remains attributed.',sources=[cfm,sch],people=people,places=[],chapters=chapters)
(ROOT/'scripts/book-records/james.json').write_text(json.dumps(cfg,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
