"""Maintain the selected profiles and reviewed source scope for Second Timothy."""
import json,copy
from book_common import ROOT,OUT
date='2026-10-07'
first=json.loads((ROOT/'scripts/book-records/1-timothy.json').read_text(encoding='utf8'))
people=copy.deepcopy(first['people'][:3])
for p in people:p.update(chapters=[1,2,3,4],passages='Second Timothy 1–4')
people[0].update(role='Named letter speaker who recalls chains, abandonment, and the approach of his departure',relations='He asks Timothy to continue teaching and come with needed belongings.',meaning='His confident hope remains connected with dependence on support and forgiveness for absent helpers.')
people[1].update(role='Addressed worker charged with preserving teaching and patiently correcting others',relations='His grandmother Lois and mother Eunice are remembered for sincere faith.',meaning='The letter connects his public task with faith received through personal relationships.')
people[2].update(role='Risen Lord whose promised life supports endurance and continued teaching',relations='Paul connects resurrection, future judgment, and the reward for faithfulness with him.',meaning='His promised life makes continued service meaningful despite chains and the approach of death.')
people.extend([
 dict(id='titus',name='Titus',reuse='2-corinthians',role='Worker whose departure for Dalmatia appears among the closing travel notices',relations='The letter names his journey while asking Timothy to come soon.',passages='Second Timothy 4:10',meaning='His brief notice places the final appeal within a wider network of workers.',chapters=[4]),
 dict(id='tychicus',name='Tychicus',reuse='ephesians',role='Worker whom the speaker says he sent to Ephesus',relations='His sending appears beside the request for Timothy to bring Mark.',passages='Second Timothy 4:12',meaning='His brief notice connects the speaker\x27s needs with continuing work elsewhere.',chapters=[4])])
cfm=copy.deepcopy(first['sources'][1]);cfm.update(chapterCoverage=[1,3,4],summary='The lesson connects courage, Scripture, and continued faithful teaching.',limits='Second Timothy coverage follows actual discussion of chapters one, three, and four. Linked talks and Restoration passages were not independently reviewed.',reviewed=dict(date=date,scope='Complete lesson body and resources read. Only its actual Second Timothy discussion supports these Church references.'))
sch=dict(id='skinner-timothy',title='Commentary on 2 Timothy 3:14—4:5',url='https://www.workingpreacher.org/commentaries/revised-common-lectionary/ordinary-29-3/commentary-on-2-timothy-314-45-3',author='Matt Skinner',publisher='Luther Seminary',year=2013,category='Scholarly study',perspective='historical',summary='Skinner emphasizes Scripture\x27s usefulness for faithful service and patient teaching.',limits='This is Skinner\x27s interpretation. His Greek analysis, authorship discussion linked elsewhere, and a reconstructed history of Scripture were not independently verified.',chapterCoverage=[3],reviewed=dict(date=date,scope='Complete commentary body read. The guide attributes his emphasis on Scripture\x27s usefulness for Timothy\x27s work.'))
chapters={str(n):dict(question=q) for n,q in enumerate(['How does remembered family faith support courage before present danger?','Why must correction remain gentle when false teaching harms others?','How does Scripture\x27s usefulness lead into good work rather than knowledge alone?','Why do ordinary requests remain beside confident language about completion and reward?'],1)}
for n,teaching in [(1,'The selected Church lesson teaches courage through power, love, and a sound mind.'),(3,'The selected Church lesson teaches that Scripture can make readers wise for salvation.'),(4,'The selected Church lesson teaches continued faithfulness when hearers prefer false teaching.')]:chapters[str(n)].update(teaching=teaching,ldsSources=[cfm['id']])
chapters['3']['historicalSources']=[sch['id']]
places=[dict(id=pid,reuse='acts',chapters=cc,summary=summary,verseScope={},linkNames=[name]) for pid,cc,summary,name in [('rome',[1],'Rome is where Onesiphorus sought the chained speaker.','Rome'),('ephesus',[1,4],'Ephesus appears in remembered service and the sending of Tychicus.','Ephesus'),('corinth',[4],'Corinth is named in the closing notice about Erastus.','Corinth')]]
cfg=dict(name='2 Timothy',code='2TI',date=date,verseCounts=[18,26,17,22],nextBook='titus',description='Remembered faith · chains · patient correction · Scripture · departure',limits='Paul is the named letter speaker. Historical authorship, dates, Greek forms, manuscripts, and a complete harmony of the travel notices were not independently verified. No exact prison site is assigned.',review='All 83 verses read for four original contextual explanations and exact selections. Five selected profiles and three city references do not claim exhaustive coverage. Actual Church discussion supplies its chapter scope. Skinner\x27s interpretation remains attributed. Authorship, dates, and a complete travel harmony were not independently verified.',sources=[cfm,sch],people=people,places=places,chapters=chapters)
(ROOT/'scripts/book-records/2-timothy.json').write_text(json.dumps(cfg,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
