"""Maintain Revelation's scoped lessons, selected profiles, and reference geography."""
import json
from book_common import ROOT
date='2026-10-07'
rows=[('john-vision','John','revelation','Named visionary who addresses seven assemblies and records what he hears and sees','He calls himself their brother and partner in oppression, kingdom, and endurance.','His received visions become a written appeal for hearing, keeping, and faithful endurance.',list(range(1,23))),('jesus','Jesus Christ','matthew','Living witness and Lamb whose death and victory ground rescue and judgment','The visions connect his authority with redeemed people, testimony, and shared worship.','His victory tests claims to power while offering life to those who follow him.',[1,2,3,5,6,7,11,12,13,14,15,17,19,20,21,22]),('balaam','Balaam','numbers','Recalled teacher whose error supplies a comparison within the Pergamum message','The message connects him with Balak and the stumbling of Israel.','His recalled teaching makes tolerated conduct a concern despite the assembly\x27s earlier endurance.',[2]),('balak','Balak','numbers','Ruler recalled within the warning about Balaam\x27s teaching','The speaker names him as the person Balaam taught to place a stumbling block.', 'His mention gives the warning a recalled comparison rather than a reconstructed local incident.',[2]),('david','David','1-samuel','Recalled king whose name appears in images of authority and promised descent','The key, root, and offspring references connect his name with the victorious speaker.','These images concern received authority and promise rather than a new episode in his life.',[3,5,22]),('moses','Moses','exodus','Servant of God named in the victors\x27 song','His song is joined with the song of the Lamb beside the glassy sea.','His recalled name connects praise of just rule with rescue.',[15])]
people=[dict(id=i,name=n,reuse=r,role=ro,relations=re,meaning=m,chapters=c,passages='Revelation '+', '.join(map(str,c))) for i,n,r,ro,re,m,c in rows]
people[1].update(linkNames=['Jesus','Christ','Lamb'],verseScope={'13':[8]})
sources=[]
lessonrows=[(50,'December 4–10 · Revelation 1–5',[1,2,3,5],'The lesson connects living Christ, assembly-specific counsel, and the Lamb\x27s worthiness.','Complete lesson body and included Holland excerpt read. Chapter four has no actual lesson discussion.'),(51,'December 11–17 · Revelation 6–14',list(range(6,15)),'The lesson connects opened seals, lasting rule, testimony, and the restored gospel.','Complete lesson body read. Coverage follows its explicit discussion of six, seven through eleven, and twelve through fourteen.'),(53,'December 25–31 · Revelation 15–22',list(range(17,23)),'The lesson connects leaving wrongdoing, preparation for judgment, and celestial glory.','Complete lesson body and included Cook excerpt read. Chapters fifteen and sixteen have no actual lesson discussion.')]
for n,title,cc,summary,scope in lessonrows:
 sources.append(dict(id=f'cfm-nt-2023-{n}',title=title,url=f'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-sunday-school-new-testament-2023/{n}?lang=eng',author='The Church of Jesus Christ of Latter-day Saints',publisher='The Church of Jesus Christ of Latter-day Saints',year=2023,category='LDS Come, Follow Me',perspective='lds',summary=summary,limits='Applications remain Church teaching. Linked full talks, videos, Restoration passages, reference entries, and historical descriptions of sealing practices were not independently reviewed. Coverage follows actual discussion rather than the broad title.',chapterCoverage=cc,reviewed=dict(date=date,scope=scope)))
sch=dict(id='carey-revelation',title='Commentary on Revelation 21:1-6a',url='https://www.workingpreacher.org/commentaries/revised-common-lectionary/all-saints-day/commentary-on-revelation-211-6a-4',author='Greg Carey',publisher='Luther Seminary',year=2015,category='Scholarly study',perspective='historical',summary='Carey reads the descending city as renewal of shared life rather than escape.',limits='This is Carey\x27s interpretation. Ancient marriage claims, Greek forms, wider Jewish literature, empire identifications, and modern applications were not independently verified. His wider chapter twenty-two comparison does not extend the selected commentary coverage.',chapterCoverage=[21],reviewed=dict(date=date,scope='Complete commentary body read. The guide attributes his emphasis on renewal and the city\x27s descent.'))
sources.append(sch)
geos=[('patmos','Patmos',37+18/60,26+32/60,'https://classic.net.bible.org/dictionary.php/xml/dictionary.php?word=Patmos',[1],{'1':[9]},'John names the island as his setting for received testimony.'),('smyrna','Smyrna',38+27/60,27+9/60,'https://classic.net.bible.org/dictionary.php?word=Smyrna',[1,2],{},'The city receives a message about poverty, testing, and faithful endurance.'),('pergamum','Pergamum',39+7/60,27+9/60,'https://classic.net.bible.org/dictionary.php/dictionary.php?word=Pergamum',[1,2],{},'The city receives praise for endurance beside warnings about tolerated teaching.'),('thyatira','Thyatira',38+55/60,27+51/60,'https://classic.net.bible.org/dictionary.php?theme=false&word=Thyatira',[1,2],{},'The city receives praise for service beside a warning about harmful teaching.'),('sardis','Sardis',38+28/60,28+6/60,'https://classic.net.bible.org/dictionary.php?word=Sardis',[1,3],{},'The city receives a call to wake and strengthen remaining works.'),('philadelphia','Philadelphia',38+20/60,28+31/60,'https://classic.net.bible.org/dictionary.php/xml/dictionary.php?word=Philadelphia',[1,3],{},'The city receives assurance despite little power and a command to hold firmly.')]
places=[]
for i,name,lat,lng,url,cc,vs,summary in geos:
 sid='net-'+i
 sources.append(dict(id=sid,title='NET Bible dictionary · '+name,url=url,author='NET Bible dictionary editors',publisher='Bible.org',edition='Online dictionary locality entry',category='Historical context',perspective='historical',summary='The locality description and coordinate line support an approximate geographic reference.',limits='Only locality and coordinates were checked. Older population figures, ethnic accusations, etymologies, archaeology, religious customs, and exile traditions were not independently verified. The marker does not locate an exact building or validate a vision.',chapterCoverage=cc,reviewed=dict(date=date,scope='Opening locality description and Google Maps coordinate line read through indexed original-source text. Broader legacy dictionary claims are not used.')))
 places.append(dict(id=i,name=name,lat=lat,lng=lng,chapters=cc,summary=summary,limits='This is an approximate city or island reference, without an exact meeting place or cave.',sourceIds=['web',sid],verseScope=vs,linkNames=[name]))
places.extend([dict(id='ephesus',reuse='acts',chapters=[1,2],summary='The first addressed city receives praise and a call to recover abandoned love.',verseScope={},linkNames=['Ephesus']),dict(id='laodicea',reuse='colossians',chapters=[1,3],summary='The city receives a warning against self-sufficiency and an invitation to repent.',verseScope={},linkNames=['Laodicea'])])
qs=['Why does the living speaker answer fear before giving the command to write?','Why does praise for endurance fail to remove the need for repentance?','How can a reputation for life or wealth conceal the condition the speaker names?','Why do the elders surrender crowns while praising the source of created life?','How does the Lamb\x27s death explain worthiness to open the book?','Why do the killed witnesses still ask how long judgment will wait?','How do shelter and wiped tears answer the earlier question about standing?','Why do the saints\x27 prayers appear before the trumpet judgments?','Why does destruction fail to produce repentance in the surviving people?','How do sweetness and bitterness shape the renewed task of speaking prophecy?','Why does the witnesses\x27 restored life precede the announcement of lasting rule?','How can continued earthly danger occur within the account of the dragon\x27s defeat?','How does control over buying and selling turn worship into coercion?','How does following the Lamb differ from the beast\x27s enforced worship?','Why does the victors\x27 song appear before the final plagues?','What does the warning about alertness require when it gives no date?','How do the city\x27s supporting rulers become agents of its destruction?','Why does leaving the city require refusing participation in its wrongdoing?','How does wedding clothing differ from the city\x27s purchased splendor?','How does judgment of great and small limit the apparent protection of power?','How does the descending city answer earlier accounts of loss and exploitation?','How do freely offered water and faithful hearing belong together in the final invitation?']
chapters={str(n):dict(question=q) for n,q in enumerate(qs,1)}
teach={1:'The Church lesson reads these images as testimony that Christ lives and guides the Church.',2:'The selected Church lesson connects these distinct messages with Christ\x27s knowledge of personal trials.',3:'The selected Church lesson connects these promises with Christ\x27s help in overcoming trials.',5:'The selected Church lesson reads the sealed book through Christ\x27s unique role in salvation.',6:'The selected Church lesson connects opened seals with the Savior\x27s authority.',7:'The selected Church lesson studies this vision within the hope of lasting divine rule.',8:'The selected Church lesson studies these trumpet scenes within the hope of lasting divine rule.',9:'The selected Church lesson asks how lasting divine rule gives hope amid plagues.',10:'The selected Church lesson invites questions about these scenes within the hope of divine rule.',11:'The selected Church lesson emphasizes the announcement of the Lord\x27s lasting kingdom.',12:'The selected Church lesson connects this victory with testimony and the Lamb\x27s blood.',13:'The selected Church lesson compares the dragon\x27s methods with the Lamb\x27s response.',14:'The selected Church lesson connects the angel\x27s gospel with Restoration teaching and shared participation.',17:'The selected Church lesson reads Babylon as a warning against the world\x27s wickedness.',18:'The selected Church lesson connects departure from Babylon with refusing participation in wrongdoing.',19:'The selected Church lesson connects this vision with preparation for the Second Coming.',20:'The selected Church lesson connects opened books with final judgment and present choices.',21:'The selected Church lesson reads these promises through the hope of celestial glory.',22:'The selected Church lesson connects the opening river and light promises with celestial glory.'}
for n,t in teach.items():
 sid=next(s['id'] for s in sources if s['id'].startswith('cfm-') and n in s['chapterCoverage'])
 chapters[str(n)].update(teaching=t,ldsSources=[sid])
chapters['21']['historicalSources']=[sch['id']]
cfg=dict(name='Revelation',code='REV',date=date,verseCounts=[20,29,22,11,14,17,17,13,21,11,19,17,18,20,8,21,18,24,21,15,27,21],nextBook=None,description='Assembly messages · faithful witness · coercive power · judgment · renewed life',limits='John is the named visionary without secure identification with the apostle or Gospel author. Historical authorship, dates, Greek forms, exact opponents, full symbolic identities, modern weapon or technology identifications, and a dated prediction schedule were not independently verified. Heavenly and symbolic cities have no literal assigned coordinates.',review='All 404 verses read for 22 original contextual explanations and exact selections. Six selected named profiles do not claim exhaustive coverage. Eight reference markers identify the seven addressed cities and Patmos. New NET references use reviewed locality and coordinate lines without broader legacy claims. The Lamb alias excludes the second beast at 13:11. Carey\x27s reading and actual Church coverage remain distinct. No exact cave, heavenly room, symbolic Babylon, New Jerusalem, or complete vision route is assigned.',sources=sources,people=people,places=places,chapters=chapters,mapNote='Markers locate addressed cities and the stated island. Heavenly and symbolic settings have no assigned literal coordinates.')
for s in sources:
 if s['id'].startswith('net-'):
  for n in s['chapterCoverage']:
   cfg['chapters'][str(n)].setdefault('historicalSources',[]).append(s['id'])
(ROOT/'scripts/book-records/revelation.json').write_text(json.dumps(cfg,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
