"""Prepare distinct portraits for the book's speaker and unnamed examples."""
import json
from book_common import ROOT,OUT
b=json.loads((ROOT/'review/ecclesiastes-draft.json').read_text(encoding='utf8'))
reuse=json.loads((ROOT/'scripts/ecclesiastes-art-reuse.json').read_text(encoding='utf8'))
records={i:dict(json.loads((OUT/(slug+'-art.json')).read_text(encoding='utf8'))[pid]) for i,(slug,pid) in reuse.items()}
scenes={
'preacher-ecclesiastes':'One mature ancient Near Eastern man representing the unnamed Preacher, not an identified portrait of Solomon. Long angular face, salt-and-pepper trimmed beard, thick dark-gray hair. Seated waist-up near profile facing left, looking across a terrace with a questioning expression. Modest dark blue robe and pale copper shawl. Pale stone Jerusalem terrace, misty lavender hills, cool dawn light. No crown.',
'closing-writer-ecclesiastes':'One middle-aged ancient Near Eastern male writer. Broad face, small neat black beard, closely curled hair. Standing chest-up front view angled right, calm attentive expression. Modest sage tunic and cream outer cloth. Shaded pale ochre plaster room, a rolled scroll held low away from face, soft window light. No visible writing.',
'solitary-worker-ecclesiastes':'One older ancient Near Eastern male worker. Round face, receding gray-black hair, rough short gray beard, deep brown eyes. Seated half-body turned right with folded hands resting on a stone ledge. Modest faded charcoal tunic and muted rust shawl. Tired questioning expression, empty clay courtyard and pale blue evening sky. No pile of money.',
'young-king-ecclesiastes':'One young adult ancient Near Eastern man representing the wise youth in Ecclesiastes 4. Clean-shaven narrow face, straight dark hair, thoughtful brown eyes. Standing waist-up side view facing left, modest cream tunic with dark plum mantle. Quiet focused expression, pale stone entrance and olive trees, fresh golden morning light. Simple woven headband, no extravagant crown.',
'old-king-ecclesiastes':'One elderly ancient Near Eastern ruler representing the old king in Ecclesiastes 4. Wide face, thick white beard, silver curls, brown eyes. Seated chest-up facing forward, chin raised slightly, reserved stubborn expression. Modest muted teal robe with narrow gold edging, simple bronze headband. Cool blue-gray audience room with pale cream pillars. Natural age lines.',
'poor-rescuer-ecclesiastes':'One mature ancient Near Eastern man representing the poor wise rescuer in Ecclesiastes 9. Lean oval face, short dark beard, black wavy hair, brown eyes. Standing half-body angled right with open hand explaining calmly. Modest patched ochre tunic and gray-green shawl. Small town stone gateway with pale rose wall and gentle afternoon light. No weapons.',
'attacking-king-ecclesiastes':'One adult ancient Near Eastern male ruler representing the unnamed attacking king in Ecclesiastes 9. Broad forehead, strong nose, short curly dark beard, brown eyes. Chest-up profile facing right, serious intent expression. Modest burgundy robe and dark olive mantle with restrained bronze trim, plain fabric headband. Distant beige earthworks under pale gray-blue cloudy sky. No modern gear or violence.',
'beloved-wife-ecclesiastes':'One mature ancient Near Eastern woman representing the wife in Ecclesiastes 9’s advice. Round face, warm brown eyes, dark loosely braided hair. Seated waist-up turned left, gentle relaxed smile. Modest indigo dress and soft sage shawl, hands resting separately beside a woven basket. Quiet courtyard with pale peach plaster, green fig leaves and golden evening light.'}
path=ROOT/'scripts/ecclesiastes-generated-portraits.json';manifest=json.loads(path.read_text(encoding='utf8')) if path.exists() else {}
for p in b['people']:
 if p['id'] in records:continue
 manifest.setdefault(p['id'],dict(name=p['name'],prompt='Create one finished Bible study portrait. '+scenes[p['id']]+' Painterly realistic illustration, visible brush texture, natural anatomy, modest ancient clothing. Keep faces in upper half for top-centered square crop. Single composition, no grid, visible writing, modern objects, medieval armor or halos. Artistic interpretation, no claim of known likeness.',src='assets/portraits/ecclesiastes/'+p['id']+'.png',mode='built-in image generation'))
for pid,item in manifest.items():
 if (ROOT/'dist'/item['src']).exists():records[pid]=dict(src=item['src'],generated=True,title=item['name']+' · interpretive portrait',credit='AI-generated illustration',license='Generated artwork',note='Artistic interpretation. Appearance, age, and setting are not verified historical evidence.')
path.write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf8');(OUT/'ecclesiastes-art.json').write_text(json.dumps(records,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
print('Prepared',len(manifest),'new portraits. Available:',len(records))
