"""Maintain First John's selected profiles and scoped evidence."""
import json
from book_common import ROOT
date='2026-10-07'
people=[dict(id='jesus',name='Jesus Christ',reuse='matthew',role='Son whose revealed life supplies the message, cleansing, and example of love',relations='The unnamed speaker connects fellowship with the Father and his Son.',meaning='Confession about him must become conduct shaped by his love.',chapters=[1,2,3,4,5],passages='First John 1–5',linkNames=['Jesus','Christ']),dict(id='cain',name='Cain',reuse='genesis',role='Brother recalled through killing as the opposite of love',relations='The letter contrasts his evil deeds with his brother\x27s righteous deeds.',meaning='His recalled act makes hatred incompatible with the claimed passage from death into life.',chapters=[3],passages='First John 3:12')]
cfm=dict(id='cfm-nt-2023-49',title='November 27–December 3 · First–Third John and Jude',url='https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-sunday-school-new-testament-2023/49?lang=eng',author='The Church of Jesus Christ of Latter-day Saints',publisher='The Church of Jesus Christ of Latter-day Saints',year=2023,category='LDS Come, Follow Me',perspective='lds',summary='The lesson connects God\x27s light and love with conduct and remaining in Christ\x27s teaching.',limits='First John coverage follows actual discussion in all five chapters. Linked Restoration texts, hymns, and reference entries were not independently reviewed. The lesson\x27s apostasy application remains Church teaching.',chapterCoverage=[1,2,3,4,5],reviewed=dict(date=date,scope='Complete lesson body and resource list read. References follow actual discussion rather than the broad lesson title.'))
sch=dict(id='ok-john',title='Commentary on 1 John 3:16-24',url='https://www.workingpreacher.org/commentaries/revised-common-lectionary/fourth-sunday-of-easter-2/commentary-on-1-john-316-24-6',author='Janette H. Ok',publisher='Luther Seminary',year=2024,category='Scholarly study',perspective='historical',summary='Ok connects practical love with attention to fellow believers\x27 material needs.',limits='This is Ok\x27s interpretation. Greek word analysis, wider claims about unique wording, and modern examples were not independently verified. The guide does not reconstruct exact audience conditions.',chapterCoverage=[3],reviewed=dict(date=date,scope='Complete commentary body read. The guide attributes her connection between practical love and attention to material need.'))
qs=['Why does honest confession belong within walking in light?','How does love for a visible brother test a claim about knowing Christ?','How can shared goods give visible form to love?','Why does hatred toward a brother contradict professed love for God?','How does asking according to God\x27s will shape confidence in prayer?']
chapters={str(n):dict(question=q,ldsSources=[cfm['id']],teaching='The selected Church lesson connects God\x27s light and love with the conduct described here.') for n,q in enumerate(qs,1)}
chapters['3']['historicalSources']=[sch['id']]
cfg=dict(name='1 John',code='1JN',date=date,verseCounts=[10,29,24,21,21],nextBook='2-john',description='Shared witness · honest confession · practical love · careful testing · confidence',limits='The speaker is unnamed. Historical authorship, dates, Greek forms, manuscripts, exact audience conditions, and the identity of departed opponents were not independently verified. No city or modern opponent is assigned.',review='All 105 verses read for five original contextual explanations and exact selections. Two selected named profiles reuse inspected artwork. Unnamed participants have no invented personal identities. No specific setting is assigned. Ok\x27s reading remains attributed. Church teaching remains distinct from the original close readings.',sources=[cfm,sch],people=people,places=[],chapters=chapters)
(ROOT/'scripts/book-records/1-john.json').write_text(json.dumps(cfg,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
