"""Maintain Jude's selected recalled people and limited source treatment."""
import json
from book_common import ROOT
date='2026-10-07'
rows=[('jude-letter','Jude','jude','Named speaker who changes his intended subject to warn against harmful teaching','He identifies himself as a servant of Jesus Christ and brother of James.','His final commands join protection of received faith with mercy toward people in danger.'),('jesus','Jesus Christ','matthew','Lord whose mercy remains the ground of hope for eternal life','Jude identifies himself as his servant and warns against denying him.','Waiting for his mercy belongs beside active care and prayer.'),('moses','Moses','exodus','Person recalled through the dispute about his body','Jude describes Michael\x27s restrained reply during a dispute with the devil.','His mention serves a comparison about speech rather than locating his grave.'),('cain','Cain','genesis','Recalled figure whose way supplies a negative comparison','Jude places his way beside Balaam\x27s error and Korah\x27s rebellion.','The comparison joins wrongdoing with the broader warning about present conduct.'),('balaam','Balaam','numbers','Figure recalled through error connected with payment','His example stands among the warning\x27s three named comparisons.','Desire for gain helps explain why claimed spiritual standing does not ensure sound conduct.'),('korah','Korah','numbers','Figure recalled through rebellion and destruction','His remembered rebellion stands beside Cain and Balaam.','His mention connects the present warning with the consequences of earlier rebellion.'),('enoch','Enoch','genesis','Figure to whom Jude attributes a saying about coming judgment','Jude calls him the seventh from Adam and quotes the judgment saying.','His attributed words strengthen the warning without supplying a complete account of their earlier transmission.'),('adam','Adam','genesis','Ancestor named in the description of Enoch','Jude uses his name to place Enoch within an ancestral sequence.','His brief mention identifies the recalled speaker rather than developing a creation account.')]
people=[dict(id=i,name=n,reuse=r,role=ro,relations=re,meaning=m,chapters=[1],passages='Jude 1',linkNames=[n]) for i,n,r,ro,re,m in rows]
people[1]['linkNames']=['Jesus','Christ']
cfm=dict(id='cfm-nt-2023-49',reuse='1-john',summary='The lesson connects Jude\x27s warning images with resisting false teaching and showing compassion.',chapterCoverage=[1],limits='Coverage follows the lesson\x27s actual Jude discussion. Linked reference entries and Restoration passages were not independently reviewed. The apostasy application remains Church teaching.',reviewed=dict(date=date,scope='Complete shared lesson body and resource list read. Jude discussion includes warning imagery, prayer, and compassion.'))
sch=dict(id='usccb-jude',title='Introduction to the Letter of Jude',url='https://bible.usccb.org/bible/jude/0',author='United States Conference of Catholic Bishops',publisher='United States Conference of Catholic Bishops',category='Scholarly study',perspective='historical',summary='The introduction reads the change of subject as an urgent response to harmful teachers.',limits='This is the introduction\x27s interpretation. Historical identities, authorship proposals, dates, reconstructed opponents, literary borrowing, and the cited earlier works were not independently verified.',chapterCoverage=[1],reviewed=dict(date=date,scope='Complete five-paragraph introduction read through indexed source text. The guide attributes only its reading of the changed purpose and urgent warning.'))
places=[dict(id='sodom',reuse='genesis',chapters=[1],summary='Jude recalls Sodom\x27s destruction within the warning comparisons.',verseScope={'1':[7]},linkNames=['Sodom'])]
cfg=dict(name='Jude',code='JUD',date=date,verseCounts=[25],nextBook='revelation',description='Urgent warning · failed promises · restrained speech · mercy · keeping power',limits='Jude is the named letter speaker, without secure identification with a Gospel relative or apostle. Historical authorship, dates, Greek forms, exact opponents, and the earlier transmission of the Michael and Enoch accounts were not independently verified. Sodom remains a disputed regional marker.',review='All 25 verses read for an original explanation and exact selection. Eight selected profiles include an inspected letter-speaker portrait and reused artwork. No exact grave, angelic dwelling, or regional city site is assigned. The USCCB reading remains attributed. Church application remains distinct from the close reading.',sources=[cfm,sch],people=people,places=places,chapters={'1':dict(question='Why does a warning about harmful teaching end with mercy and rescue?',teaching='The selected Church lesson joins Jude\x27s warning images with prayer and compassion.',ldsSources=[cfm['id']],historicalSources=[sch['id']])})
(ROOT/'scripts/book-records/jude.json').write_text(json.dumps(cfg,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
