"""Maintain First Peter's selected profiles and limited source coverage."""
import json
from book_common import ROOT
date='2026-10-07';people=[]
rows=[
('peter','Peter','acts','Named letter speaker who addresses scattered believers and identifies himself as a fellow elder','He recalls Christ\x27s suffering and names Silvanus as a faithful brother.','His final instructions connect leadership with willing care rather than domination.',[1,2,3,4,5]),
('jesus','Jesus Christ','matthew','Risen Lord whose suffering and enduring life ground hope, conduct, and rescue','The letter presents him as the rejected stone, shepherd, and source of access to God.','His example connects refusal of revenge with confidence in God\x27s judgment.',[1,2,3,4,5]),
('sarah','Sarah','genesis','Woman recalled in the instructions to wives about conduct and freedom from terror','The speaker names her obedience to Abraham within the household comparison.','Her named example belongs to unequal directions that also require husbands to honor joint heirs.',[3]),
('abraham','Abraham','genesis','Husband named within Sarah\x27s example in the household instructions','The speaker recalls Sarah addressing him as lord.','His brief mention belongs to the letter\x27s comparison rather than a reconstructed household scene.',[3]),
('noah','Noah','genesis','Ship builder recalled in the account of rescue through water','The speaker connects patient waiting in his days with eight people saved through water.','His account supplies the comparison leading into baptism and conscience before God.',[3]),
('silas','Silvanus','acts','Faithful brother through whom the speaker says he wrote the brief appeal','He appears beside the closing testimony about the grace in which the hearers stand.','His named work keeps the letter\x27s delivery within shared support.',[5])]
for pid,name,reuse,role,rel,meaning,cc in rows:
 p=dict(id=pid,name=name,reuse=reuse,role=role,relations=rel,meaning=meaning,chapters=cc,passages='First Peter '+', '.join(map(str,cc)))
 if pid=='jesus':p['linkNames']=['Jesus','Christ']
 people.append(p)
cfm=dict(id='cfm-nt-2023-48',title='November 20–26 · First and Second Peter',url='https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-sunday-school-new-testament-2023/48?lang=eng',author='The Church of Jesus Christ of Latter-day Saints',publisher='The Church of Jesus Christ of Latter-day Saints',year=2023,category='LDS Come, Follow Me',perspective='lds',summary='The lesson connects trials, belonging to God, and teaching to the dead.',limits='First Peter coverage follows actual discussion of chapters one through four. The spirit-world explanation is Church teaching. The included Christofferson excerpt was read, but the linked full talk, Restoration texts, and Greek meanings were not independently reviewed.',chapterCoverage=[1,2,3,4],reviewed=dict(date=date,scope='Complete lesson body and included resource quotation read. Only actual First Peter discussion supports these chapter references.'))
sch=dict(id='brown-peter',title='Commentary on 1 Peter 2:19-25',url='https://www.workingpreacher.org/commentaries/revised-common-lectionary/fourth-sunday-of-easter/commentary-on-1-peter-219-25-3',author='Jeannine K. Brown',publisher='Luther Seminary',year=2017,category='Scholarly study',perspective='historical',summary='Brown reads direct address to bound workers as giving vulnerable hearers a meaningful role.',limits='This is Brown\x27s interpretation. Wider household-code history, Greek analysis, precise audience conditions, and cited books were not independently verified. The actual instructions retain unequal power and do not explicitly abolish the relationship.',chapterCoverage=[2],reviewed=dict(date=date,scope='Complete commentary body and four notes read. The guide attributes her emphasis on direct address to vulnerable hearers.'))
qs=['Why does a secure inheritance lead into sincere love rather than private confidence alone?','How does the refusal of revenge place judgment beyond the present power of harsh masters?','Why must an answer about hope include humility and a good conscience?','How do hospitality and received gifts make love practical during insult and pressure?','How does the chief Shepherd\x27s promised appearance limit the authority of present leaders?']
chapters={str(n):dict(question=q) for n,q in enumerate(qs,1)}
teach={1:'The selected Church lesson connects trials with living hope and belonging to God.',2:'The selected Church lesson connects Christ\x27s example with faithful conduct during trials.',3:'The selected Church lesson reads the imprisoned spirits through Christ\x27s visit to the spirit world.',4:'The selected Church lesson connects teaching to the dead with God\x27s just judgment.'}
for n,t in teach.items():chapters[str(n)].update(teaching=t,ldsSources=[cfm['id']])
chapters['2']['historicalSources']=[sch['id']]
cfg=dict(name='1 Peter',code='1PE',date=date,verseCounts=[25,25,22,19,14],nextBook='2-peter',description='Living hope · shared belonging · unequal power · gentle witness · willing care',limits='Peter is the named letter speaker. Historical authorship, dates, Greek forms, manuscripts, exact audience conditions, identity of the imprisoned spirits, and whether Babylon identifies a literal city were not independently verified. No spirit-world or Babylon location is assigned.',review='All 105 verses read for five original contextual explanations and exact selections. Six selected profiles do not claim exhaustive coverage. Broad addressed regions and the uncertain Babylon reference have no invented exact setting. Brown\x27s reading remains attributed. Actual Church lesson coverage and spirit-world teaching remain separate from the original close readings.',sources=[cfm,sch],people=people,places=[],chapters=chapters)
(ROOT/'scripts/book-records/1-peter.json').write_text(json.dumps(cfg,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
