"""Maintain Hebrews's selected profiles and reviewed source scope."""
import copy,json
from book_common import ROOT
date='2026-10-07'
people=[]
rows=[
('jesus','Jesus Christ','matthew','Son and high priest whose self-offering grounds the argument about access to God','The writer connects shared suffering, enduring life, and heavenly service with him.','His work joins confidence before God with mutual care and patient endurance.',list(range(1,14))),
('moses','Moses','exodus','Faithful servant whose household care and received tent pattern support the comparisons','The writer recalls his leadership, law, received pattern, and choice of mistreatment.','His faithfulness is honored within comparisons about the Son and continued trust.',[3,7,8,9,10,11,12]),
('aaron','Aaron','exodus','Called priest whose role supplies a comparison for appointment and repeated service','The writer names his calling, priestly order, and rod within the tent.','His appointed role helps explain why priestly honor cannot be claimed for oneself.',[5,7,9]),
('melchizedek','Melchizedek','genesis','King and priest whose meeting with Abraham supports the argument about enduring priesthood','He blesses Abraham and receives a tenth of the returned goods.','The writer uses his blessing and the account\x27s silence about ancestry to explain its comparison.',[5,6,7]),
('abraham','Abraham','genesis','Promise receiver whose patient waiting and meeting with Melchizedek support the argument','He receives a promise and blessing, gives tribute, and waits with trust.','His unfinished earthly life places faith within waiting rather than immediate visible completion.',[2,6,7,11]),
('sarah','Sarah','genesis','Woman whose trust in the promise is recalled within the examples of faith','The writer connects her promised child with confidence in the one who promised.','Her example joins waiting and received power within the repeated account of faith.',[11]),
('rahab','Rahab','joshua','Woman whose reception of the spies is recalled as an act of faith','The writer contrasts her rescue with the destruction of those who refused.','Her brief example widens the account of faith beyond the ancestors of Israel.',[11]),
('timothy','Timothy','romans','Freed brother whose possible arrival appears in the closing notice','The speaker hopes to visit the hearers with him if he arrives soon.','His notice places the final appeal within shared relationships and uncertain travel plans.',[13])]
for pid,name,reuse,role,rel,meaning,cc in rows:
 p=dict(id=pid,name=name,reuse=reuse,role=role,relations=rel,meaning=meaning,chapters=cc,passages='Hebrews '+', '.join(map(str,cc)))
 if pid=='jesus':p['linkNames']=['Jesus','Christ']
 people.append(p)
def cfm(number,title,cc,summary,scope):
 return dict(id=f'cfm-nt-2023-{number}',title=title,url=f'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-sunday-school-new-testament-2023/{number}?lang=eng',author='The Church of Jesus Christ of Latter-day Saints',publisher='The Church of Jesus Christ of Latter-day Saints',year=2023,category='LDS Come, Follow Me',perspective='lds',summary=summary,limits='Coverage follows the actual lesson body rather than its title. Church applications to callings and ordinances remain distinct from independent historical evidence. The lesson\x27s naming of Paul does not settle authorship. Linked videos, talks, and Restoration texts were not independently reviewed.',chapterCoverage=cc,reviewed=dict(date=date,scope=scope))
sources=[cfm(45,'October 30–November 5 · Hebrews 1–6',[1,2,3,4,5],'The lesson connects Christ\x27s suffering with help, responsive hearts, and called service.','Complete lesson body and resource list read. Actual discussion covers chapters one through five. Chapter six is not separately discussed.'),cfm(46,'November 6–12 · Hebrews 7–13',[7,8,9,10,11],'The lesson connects ordinances with Christ and faith with trust in unfinished promises.','Complete lesson body and included Holland quotation read. Actual discussion covers chapters seven through eleven. Linked full talks and videos were not reviewed.')]
sch=dict(id='foskett-hebrews',title='Commentary on Hebrews 11:29—12:2',url='https://www.workingpreacher.org/commentaries/revised-common-lectionary/ordinary-20-3/commentary-on-hebrews-1129-122-4',author='Mary Foskett',publisher='Luther Seminary',year=2019,category='Scholarly study',perspective='historical',summary='Foskett connects present hearers with a wider history of faithful endurance.',limits='This is Foskett\x27s interpretation. Specific unnamed sufferers, authorship, precise audience history, and Greek forms were not independently verified. Endurance is not presented as approval of every form of suffering.',chapterCoverage=[11],reviewed=dict(date=date,scope='Complete commentary body read. The guide attributes its connection of present hearers with earlier lives of endurance.'))
sources.append(sch)
qs=['Why does the Son\x27s place give weight to the message received?','How does shared suffering explain the high priest\x27s ability to help?','Why does the repeated word today require mutual encouragement?','How does offered mercy stand beside the exposure of hidden intentions?','Why does mature judgment require practice rather than passive hearing?','How does remembered service keep the warning connected with confident hope?','Why does continuing life answer the limit imposed by the deaths of priests?','Why does the new covenant promise turn from buildings toward law within people?','How does cleansing the conscience extend the argument beyond restricted entry?','Why does confidence before God lead into encouragement of love and good work?','Why do victories and painful deaths appear within the same account of faith?','How do commands to strengthen weak limbs make endurance a shared task?','Why does praise join sharing and care for prisoners in the closing directions?']
chapters={str(n):dict(question=q) for n,q in enumerate(qs,1)}
teach={1:'The selected Church lesson teaches that Jesus Christ is the author of eternal salvation.',2:'The selected Church lesson connects Christ\x27s suffering with his ability to help us.',3:'The selected Church lesson teaches responsive hearts rather than refusal of God\x27s blessings.',4:'The selected Church lesson connects Christ\x27s suffering with offered mercy and help.',5:'The selected Church lesson applies called priestly service to authorized Church callings.',7:'The selected Church lesson connects Melchizedek Priesthood ordinances with approaching Jesus Christ.',8:'The selected Church lesson reads ancient ordinances as pointing toward Jesus Christ.',9:'The selected Church lesson reads ancient ordinances as pointing toward Jesus Christ.',10:'The selected Church lesson joins meaningful ordinances with continued confidence and trust.',11:'The selected Church lesson teaches faith as trust in promises not yet fulfilled.'}
for n,t in teach.items():chapters[str(n)].update(teaching=t,ldsSources=[sources[0 if n<7 else 1]['id']])
chapters['11']['historicalSources']=[sch['id']]
cfg=dict(name='Hebrews',code='HEB',date=date,verseCounts=[14,18,19,16,14,20,28,13,28,39,40,29,25],nextBook='james',description='The Son · shared suffering · priesthood · access · promises · endurance',limits='The work does not name its speaker. Historical authorship, dates, Greek forms, manuscripts, exact audience, and archaeological reconstruction of its tent description were not independently verified. The comparisons state the writer\x27s argument rather than an independent dismissal of all Jewish worship. Heavenly Jerusalem is not assigned an earthly marker.',review='All 303 verses read for thirteen original contextual explanations and exact selections. Eight selected profiles and one recalled city do not claim exhaustive coverage. Church scope follows actual lesson discussion. Foskett\x27s interpretation remains attributed. The speaker remains unnamed. No exact heavenly setting, audience location, or tent reconstruction is supplied.',sources=sources,people=people,places=[dict(id='jericho',reuse='joshua',chapters=[11],summary='Jericho is recalled in the account of the walls falling after repeated circling.',linkNames=['Jericho'],verseScope={'11':[30]})],chapters=chapters)
(ROOT/'scripts/book-records/hebrews.json').write_text(json.dumps(cfg,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
