"""Prepare distinct adult portraits and preserve reviewed same-person reuse."""
import json
from book_common import ROOT,OUT

book=json.loads((ROOT/'review/jeremiah-draft.json').read_text(encoding='utf8'))
reuse=json.loads((ROOT/'scripts/jeremiah-art-reuse.json').read_text(encoding='utf8'))
scenes={
'hilkiah-father':'Judean priest about 60, brown skin, long gray beard. Seated chest-up profile right, gentle thoughtful expression, cream robe and pale sage shawl. Anathoth stone doorway, cool morning sky.',
'uriah-shemaiah':'Judean prophet about 40, olive-brown skin, long dark curls and short beard. Waist-up angled left, serious troubled face, rust tunic and cream mantle. Pale sandy roadside with distant palms, cloudy daylight.',
'micah-prophet':'Judean prophet about 55, medium brown skin, broad weathered face, gray-black curly beard. Close face portrait three-quarter right, intent calm expression, modest dark teal robe. Pale green rural hills, soft afternoon light.',
'elnathan-achbor':'Judean official about 50, brown skin, square face, cropped dark-gray beard. Half-body standing facing left, reserved expression, cream tunic with burgundy mantle. Pale palace steps, muted gold sunset.',
'elasah-shaphan':'Judean royal messenger about 35, medium brown skin, narrow face and short black beard. Chest-up angled right, attentive expression, modest ochre robe and blue shoulder cloth. Light gray city archway, bright morning.',
'gemariah-hilkiah':'Judean messenger about 45, deep brown skin, rounded face, wavy dark hair, close beard. Waist-up seated almost front-facing, patient expression, modest pale gray robe and rust sash. Reed-lined riverbank with cream sky.',
'ahab-kolaiah':'Judean prophet in Babylon about 40, warm brown skin, broad face, short thick beard. Close chest-up left profile, assertive expression, modest muted plum robe. Pale blue courtyard and distant brick wall, cool light. No crown.',
'zedekiah-maaseiah':'Judean prophet in Babylon about 50, olive-brown skin, angular face, gray-black hair and beard. Half-body turned right, guarded expression, modest brown robe and muted green wrap. Pale ochre brick lane, overcast daylight. No crown.',
'shemaiah-nehelamite':'Judean letter writer in Babylon about 45, medium brown skin, lean face, tight curls, close beard. Seated waist-up toward left, disapproving expression, modest indigo tunic. Unmarked rolled papyrus held low. Pale ivory domestic room, warm window light.',
'hanamel':'Judean landowner about 40, brown skin, rounded face, dark wavy hair and beard. Waist-up standing three-quarter right, cautious hopeful smile, modest olive tunic and cream scarf. Anathoth field and pale limestone wall, golden morning light.',
'rechabites':'Three adult Judean family members, two men and one woman, all over 30 with distinct brown faces. Waist-up different angles, composed serious expressions, modest rust, sage, and cream clothes. Pale woven tent entrance and dry grass, soft cloudy light. No drinking scene.',
'jaazaniah-rechabite':'Judean family leader about 55, deep brown skin, broad face, gray beard and dark-gray curls. Chest-up near front-facing, steady expression, modest brown tunic and dusty blue mantle. Pale temple courtyard, clear afternoon sky.',
'gemariah-shaphan':'Judean official about 60, olive-brown skin, long angular face, gray beard. Seated half-body in right profile, concerned thoughtful expression, modest cream robe and muted burgundy shawl. Pale stone temple room, soft light from a doorway.',
'micaiah-gemariah':'Judean listener about 28, warm brown skin, slender face, short black curls and light beard. Close chest-up three-quarter left, alert thoughtful expression, modest teal tunic and cream wrap. Pale rose temple wall, green tree shadows.',
'elishama-scribe':'Judean scribe about 50, medium brown skin, broad face, short gray beard. Waist-up seated toward right, focused expression, modest ochre robe with charcoal shoulder cloth. Wooden shelves with unmarked scrolls, pale plaster, warm lamplight.',
'delaiah-shemaiah':'Judean official about 45, olive-brown skin, rounded face, wavy dark hair and full beard. Half-body standing near front-facing, worried expression, modest muted violet robe and cream sash. Pale ivory palace doorway, cool blue shadows.',
'zedekiah-hananiah':'Judean official about 35, warm brown skin, square face, short black beard. Chest-up strict left profile, watchful expression, modest sage tunic and ochre mantle. Pale courtyard with a clay jar and distant stone bench. Soft evening light. No crown.',
'jehudi':'Judean messenger and reader about 35, medium brown skin, narrow face, short dark curls and beard. Seated waist-up three-quarter right, serious attentive expression, modest rust tunic and pale gray wrap. Unmarked scroll held low. Cream royal chamber, soft winter daylight.',
'arrest-officers':'Three adult Judean royal officers, all over 35, distinct brown faces and varied dark or gray beards. Chest-up grouped at different angles, stern reserved expressions, modest dark green, brown, and cream garments. Pale stone passage, muted blue dawn. No violence or weapons in use.',
'jehucal-shelemiah':'Judean official about 45, medium brown skin, angular face, short dark-gray beard. Waist-up standing toward left, tense expression, modest indigo robe and muted gold sash. Pale stone court with dry tree shadows, harsh afternoon light.',
'irijah':'Judean gate guard about 30, brown skin, broad face, cropped dark hair and short beard. Close chest-up facing right, suspicious expression, modest charcoal tunic and brown shoulder cloth, simple bronze helmet. Pale city gate, cool cloudy daylight. No violence.',
'jonathan-scribe':'Judean scribe about 55, olive-brown skin, narrow face, gray curls and trimmed beard. Half-body seated left profile, reserved serious expression, modest pale ochre robe and olive shawl. Cream domestic wall, unmarked scrolls on a low table, warm shaded light.',
'hostile-officials':'Two adult Judean officials, one about 45 with a lean brown face and dark beard, one about 60 with a broad brown face and gray beard. Waist-up one front-facing and one right profile, stern expressions, modest plum and dark olive robes. Pale palace courtyard, gray-blue sky. No violence.',
'malchijah-royal':'Judean adult royal son about 30, warm brown skin, rounded face, short dark curls and neat beard. Chest-up angled left, distant thoughtful expression, modest deep blue robe with narrow gold edging. Pale stone royal court, soft rose evening light. No crown.',
'babylonian-officers':'Three adult ancient Babylonian officers, all over 40 with distinct brown faces and dark beards. Half-body grouped in varied directions, alert composed expressions. Modest ochre, blue, and brown robes with simple bronze headpieces. Pale Jerusalem stone and muted dusty sky. No violence, no medieval armor.',
'jonathan-kareah':'Judean commander about 35, deep brown skin, angular face, short black curls and beard. Waist-up standing three-quarter right, cautious expression, modest rust tunic and cream outer cloth. Pale Mizpah stone wall and distant green fields, morning light.',
'baalis':'Adult ancient Ammonite king about 50, medium brown skin, broad face, curly black-gray beard. Close chest-up left profile, guarded serious expression, modest plum robe with narrow bronze trim and plain royal headband. Pale sandstone palace, blue-green shadows.',
'jezaniah-hoshaiah':'Judean community leader about 45, warm brown skin, narrow face, wavy dark hair and beard. Half-body seated toward left, worried questioning expression, modest sage robe and tan scarf. Pale roadside shelter, dry grass and distant hills, soft daylight.',
'azariah-hoshaiah':'Judean community leader about 45, warm brown skin, narrow face, wavy dark hair and beard. Chest-up standing toward right, tense challenging expression, modest muted teal robe and cream scarf. Pale sandy road with distant palms, cloudy daylight. Appearance is interpretive; do not claim a verified separate identity from Jezaniah son of Hoshaiah.',
'women-queen':'Three adult Judean women living in Egypt, ages about 30, 45, and 60, distinct brown faces with dark or gray hair. Waist-up at varied angles, confident, questioning, and serious expressions, modest cream, coral, and olive dresses with shawls. Pale plaster courtyard, small plain clay bowls, distant palm, warm morning light. No goddess statue or text.',
'hophra':'Adult ancient Egyptian king about 50, medium brown skin, broad clean-shaven face. Seated chest-up nearly front-facing, composed concerned expression, modest white linen garment, narrow gold-blue collar, simple royal striped headcloth. Pale sandstone column, muted turquoise background, warm side light. No hieroglyphs.',
'seraiah-neriah':'Judean official about 40, olive-brown skin, slender face, dark-gray curls and short beard. Waist-up standing right profile, solemn focused expression, modest cream tunic and burgundy wrap. Unmarked rolled scroll held low beside a pale riverbank, cool misty morning. No writing.'
}
path=ROOT/'scripts/jeremiah-generated-portraits.json'
manifest=json.loads(path.read_text(encoding='utf8'))
for p in book['people']:
 if p['id'] in reuse or p['id'] in manifest:continue
 manifest[p['id']]=dict(name=p['name'],prompt='Create one finished Bible study portrait. '+scenes[p['id']]+' Painterly realistic illustration with visible brush texture, natural anatomy, modest ancient clothing. One composition, face high for square crop. No text, letters, signature, watermark, halos, grid, or modern objects. Interpretive artwork, not a verified likeness.',src='review/jeremiah-portraits/'+p['id']+'.png',mode='built-in image generation')
assert set(manifest)|set(reuse)=={p['id'] for p in book['people']}
path.write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
print('Prepared',len(manifest),'distinct new portraits;',len(reuse),'same-person reuse references.')
