"""Maintain Titus's selected records and reviewed source scope."""
import json,copy
from book_common import ROOT
date='2026-10-07';first=json.loads((ROOT/'scripts/book-records/2-timothy.json').read_text(encoding='utf8'))
people=copy.deepcopy([p for p in first['people'] if p['id'] in ['paul','titus','jesus','tychicus']])
updates={
'paul':('Named letter speaker who directs Titus to complete work on Crete','He calls Titus a true child in their common faith.','His instructions connect sound teaching with tested care and work that meets needs.',[1,2,3]),
'titus':('Addressed worker charged with appointing elders and teaching conduct that fits sound doctrine','Paul asks him to continue work on Crete and later come to Nicopolis.','His task connects tested leaders, household instruction, and support for traveling workers.',[1,2,3]),
'jesus':('Savior whose grace and self-giving ground the call to good work','The letter connects his past gift and promised appearing with present conduct.','His work makes good deeds a response to grace rather than its purchase price.',[1,2,3]),
'tychicus':('Worker named as a possible replacement before Titus leaves for Nicopolis','The speaker may send him or Artemas to Titus.','The alternative sending keeps care for the assembly within shared work.',[3])}
for p in people:
 role,rel,meaning,cc=updates[p['id']];p.update(role=role,relations=rel,meaning=meaning,chapters=cc,passages='Titus '+('1–3' if len(cc)>1 else '3:12'))
people.append(dict(id='apollos',name='Apollos',reuse='1-corinthians',role='Traveling worker whom Titus must help continue his journey',relations='The speaker asks that he and Zenas lack nothing for their journey.',passages='Titus 3:13',meaning='His need makes the call to useful work concrete through material support.',chapters=[3]))
cfm=copy.deepcopy(first['sources'][0]);cfm.update(chapterCoverage=[1,2],summary='The lesson connects sound doctrine with protection from false teaching.',limits='Titus coverage follows actual discussion of chapters one and two. The title alone does not establish chapter three or Philemon coverage. Linked Restoration passages were not independently reviewed.',reviewed=dict(date=date,scope='Complete lesson body and resource list read. Its actual Titus discussion supports only chapters one and two.'))
sch=dict(id='pietz-titus',title='Commentary on Titus 2:11-14',url='https://www.workingpreacher.org/commentaries/revised-common-lectionary/christmas-eve-nativity-of-our-lord/commentary-on-titus-211-14-10',author='Jennifer Vija Pietz',publisher='Luther Seminary',year=2017,category='Scholarly study',perspective='historical',summary='Pietz reads grace as the basis of changed conduct and good work.',limits='This is Pietz\x27s interpretation. Greek analysis, authorship, broader social claims about Crete, household codes, and cited books were not independently verified.',chapterCoverage=[2],reviewed=dict(date=date,scope='Complete commentary body and two notes read. The guide attributes the connection between grace and good work.'))
net=dict(id='net-crete',title='NET Bible · Crete',url='https://classic.net.bible.org/dictionary.php/dictionary.php?word=CRETE',author='NET Bible reference editors',publisher='Bible.org',category='Reference work',perspective='historical',summary='The dictionary identifies Crete as an island and supplies reference coordinates.',limits='Only the opening locality description and coordinate line support the island marker. Old historical claims, ethnic stereotypes, exact towns, and travel sequences were not independently verified.',reviewed=dict(date=date,scope='Opening island description and coordinate line read: 35 degrees 10 minutes north, 25 degrees east.'))
chapters={str(n):dict(question=q) for n,q in enumerate(['Why does a teacher\x27s conduct matter when whole households face disruption?','How does grace supply the reason for good work within these unequal instructions?','How do the closing travel requests make useful work concrete?'],1)}
for n in [1,2]:chapters[str(n)].update(teaching='The selected Church lesson teaches sound doctrine as protection against false instruction.',ldsSources=[cfm['id']])
chapters['2']['historicalSources']=[sch['id']]
cfg=dict(name='Titus',code='TIT',date=date,verseCounts=[16,15,15],nextBook='philemon',description='Tested leaders · household care · grace · good work · shared support',limits='Paul is the named letter speaker. Historical authorship, dates, Greek forms, manuscripts, ethnic generalizations, and a complete travel harmony were not independently verified. The quoted insult is not independent evidence for every Cretan. Nicopolis is not assigned a secure location.',review='All 46 verses read for three original contextual explanations and exact selections. Five selected profiles and one island reference do not claim exhaustive coverage. Church coverage follows actual discussion. Pietz\x27s reading remains attributed. NET locality and coordinates support Crete without an exact town. No independent ethnic character claim or secure Nicopolis identification is made.',sources=[cfm,sch,net],people=people,places=[dict(id='crete',name='Crete',lat=35+10/60,lng=25,summary='Crete is the island where Titus remains to complete work and appoint elders.',limits='Island reference rather than an exact town or meeting house.',sourceIds=['web','net-crete'],chapters=[1],verseScope={'1':[5]},linkNames=['Crete'])],chapters=chapters)
(ROOT/'scripts/book-records/titus.json').write_text(json.dumps(cfg,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
