"""Distinct portrait directions for Esther's selected people and groups."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parent.parent
OUT=ROOT/'dist/data/books'
book=json.loads((OUT/'esther.json').read_text(encoding='utf8'))
prior={}
for f in OUT.glob('*-art.json'):
 if f.stem!='esther-art':prior.update(json.loads(f.read_text(encoding='utf8')))
records={p['id']:dict(prior[p['id']]) for p in book['people'] if p['id'] in ['jehoiachin','nebuchadnezzar']}
scenes={
'ahasuerus-esther':'Exactly one mature ancient Persian man, broad face, full dark curled beard, strong nose, seated half-body in side view, indigo and copper layered woven clothing, restrained gold headband and soft ancient cap. One hand on a plain chair arm. Reserved serious expression, pale stone room and muted blue shadows. No European crown.',
'vashti':'Exactly one mature ancient Persian woman, long oval face, black waves, poised direct gaze. Standing waist-up with shoulders turned, modest deep plum dress and pale sage outer cloth, small ancient gold headband. One relaxed hand raised slightly, warm ochre plaster background with blue-green hanging cloth. Resolute calm expression.',
'memucan':'Exactly one older ancient Persian male adviser, bald crown, long silver beard, rounded face, heavy brows. Close chest-up side profile, modest burgundy and sand clothing. Thoughtful downward gaze, shadowed reed-lined room, warm amber light.',
'royal-servants-esther':'Exactly seven distinct adult ancient Persian male palace servants, all fully clothed, informal two-depth group, waist-up, different face shapes, hair lengths, facial hair, ages and modest blue-gray, rust, cream, teal, olive, burgundy and ochre clothing. Three seated in front and four standing behind. Composed attentive expressions, pale stone arcade, soft morning light. No weapons.',
'royal-princes-esther':'Exactly six distinct adult ancient Persian male advisers, informal waist-up group around a plain low table. One bald elder with silver beard, two clean-shaven men of different face shapes, and three men with different dark beards. Modest indigo, flax, plum, copper, sage, and charcoal clothes, no European crowns. Quiet listening expressions, green garden doorway, cool pale sunlight.',
'esther':'Exactly one adult young ancient Jewish woman in a Persian palace, round face, deep brown eyes, thick dark curls partly gathered. Seated half-body facing three-quarter right, modest teal woven dress and cream shawl, restrained ancient gold headband. Hands folded loosely, thoughtful steady expression, pale limestone bench, soft olive-green garden and blue morning light. Natural adult proportions.',
'mordecai':'Exactly one mature ancient Jewish man, long face, graying black beard, receding curls, lean build. Standing waist-up in near profile with head turned toward viewer, modest cream tunic with rust and navy woven outer cloth. Calm watchful expression, sunlit stone gate passage, warm late light. No crown.',
'hegai':'Exactly one middle-aged ancient Persian male palace steward, wide face, clean-shaven cheeks, short thick curls. Close three-quarter chest-up framing, modest sage and ochre clothing, gentle listening expression, one hand holding a plain folded cloth low, shaded blue plaster room and pale shelf.',
'shaashgaz':'Exactly one mature ancient Persian male palace steward, narrow angular face, black stubble, close cropped hair. Seated half-body looking left, modest charcoal and muted copper clothing, serious restrained expression, lavender shadows in a pale stone doorway, hands resting separately on knees.',
'abihail-esther':'Exactly one mature ancient Jewish man, soft oval face, short silver-threaded beard, swept dark hair. Close chest-up front view, modest flax and pale green clothing, slight warm smile, quiet rose-colored hills and cool blue-gray evening sky. No other person.',
'mordecai-ancestors':'Exactly three distinct adult ancient Jewish men in one waist-up family group, a broad-faced silver-bearded elder seated, a long-faced dark-bearded middle-aged man turned sideways, and a younger round-faced clean-shaven man standing behind. Modest olive, rust, and cream woven clothes, calm expressions, shaded courtyard with brown clay vessels and pale morning light. No writing.',
'bigthan-teresh':'Exactly two distinct adult ancient Persian male doorkeepers, one square-faced man with short black beard, the other long-faced clean-shaven with straight dark hair. Fully clothed modest navy and copper tunics, waist-up standing on opposite sides of a pale stone doorway. Serious quiet expressions, cool purple-blue shade. No violence or weapons.',
'esther-maidens':'Exactly three distinct adult ancient Near Eastern women, fully clothed in modest sage, plum and pale blue woven clothes, informal waist-up group beside a low courtyard bench. An older broad-faced woman seated, a younger oval-faced woman standing sideways, and an adult angular-faced woman leaning slightly forward. Gentle attentive expressions, green vines and warm cream stone, diffused afternoon light.',
'haman':'Exactly one middle-aged ancient Persian court official, angular face, neatly pointed dark beard, receding hairline, upright half-body pose, shoulders square, head turned slightly right. Modest burgundy and dark teal layered woven clothing with a small gold clasp. Self-assured restrained expression, cream plaster column and dark blue background. Human face, no sinister fantasy features or crown.',
'zeresh':'Exactly one mature ancient Near Eastern woman, high cheekbones, straight black hair with gray threads, composed analytical expression. Seated waist-up in side view with face turned toward viewer, modest ochre dress and muted indigo outer cloth, one open hand low, warm rose plaster room with pale woven hanging, cool side light.',
'hathach':'Exactly one adult ancient Persian male messenger, youthful long oval face, clean-shaven, loose dark waves. Standing half-body turned left, modest blue-gray and flax clothes, one hand holding a plain unmarked rolled paper low. Alert listening expression, pale stone city square and warm golden early light.',
'harbonah':'Exactly one older ancient Persian male palace servant, broad face, cropped gray curls, short gray stubble. Close chest-up profile, modest plum tunic and cream outer cloth, steady serious gaze to the left. Shaded garden doorway, soft green reflected light and cool lavender shadows.',
'jewish-families-esther':'Exactly two adult ancient Jewish parents and two fully clothed children, modest rust, indigo, cream and sage woven clothing. Mother with oval face and curls seated beside one child, broad-faced dark-bearded father standing sideways behind the second child. Waist-up respectful family portrait, quiet thoughtful expressions, shaded limestone courtyard, pale grain basket, blue-green morning light. No distress spectacle.',
'royal-scribes-esther':'Exactly three distinct adult ancient Persian male writers, fully clothed in modest teal, ochre and charcoal robes, waist-up at a low plain wooden table with blank sheets and unmarked rolls. A bald gray-bearded elder seated in profile, a young clean-shaven round-faced man looking downward, and a long-faced dark-bearded man listening. Warm reed-lined room, soft copper light. No visible writing.',
'royal-couriers-esther':'Exactly three distinct adult ancient Persian male couriers, fully clothed in modest pale green, navy and rust garments. Waist-up group, one standing frontward with a plain unmarked roll, one seated in profile, one turned sideways looking beyond the viewer. Different faces and facial hair, calm alert expressions. Pale hills and muted blue dawn sky, a horse barely visible behind, no weapons.',
'haman-sons':'Exactly ten distinct adult ancient Near Eastern men, fully clothed in varied modest copper, olive, indigo, plum, cream, teal, navy, ochre, rust and charcoal woven clothes. Waist-up informal two-row group, five seated in front and five standing behind. All ten heads clearly visible and separated, diverse face shapes, hair and beard styles, quiet neutral expressions. Pale shaded courtyard, soft blue-green afternoon light. No violence, gallows, text or additional people.'}
manifest_path=ROOT/'scripts/esther-generated-portraits.json'
manifest=json.loads(manifest_path.read_text(encoding='utf8')) if manifest_path.exists() else {}
for p in book['people']:
 if p['id'] in records:continue
 manifest.setdefault(p['id'],dict(name=p['name'],prompt=f'Create a finished Bible study portrait of {p["name"]}, {p["role"]}. '+scenes[p['id']]+' Painterly realistic illustration with visible brush texture, natural human anatomy and ancient clothing. Keep faces high enough for a square top-centered crop. One composition, no grid, lettering, modern objects, medieval armor, halos, nudity or claim of known likeness.',src=f'assets/portraits/esther/{p["id"]}.png',mode='built-in image generation'))
for pid,item in manifest.items():
 if (ROOT/'dist'/item['src']).exists():records[pid]=dict(src=item['src'],generated=True,title=item['name']+' · interpretive portrait',credit='AI-generated illustration',license='Generated artwork',note='Artistic interpretation. Appearance, age, and setting are not verified historical evidence.')
manifest_path.write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
(OUT/'esther-art.json').write_text(json.dumps(records,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
print('Portraits available:',len(records),'Remaining:',[p['id'] for p in book['people'] if p['id'] not in records])
