"""Prepare varied adult portraits for the voices and people in the poems."""
import json
from book_common import ROOT,OUT
b=json.loads((ROOT/'review/song-of-solomon-draft.json').read_text(encoding='utf8'))
reuse=json.loads((ROOT/'scripts/song-of-solomon-art-reuse.json').read_text(encoding='utf8'))
records={i:dict(json.loads((OUT/(slug+'-art.json')).read_text(encoding='utf8'))[pid]) for i,(slug,pid) in reuse.items()}
scenes={
'woman-song':'One adult ancient Near Eastern woman, age about 28, deep warm brown sun-darkened skin, oval face, dark curly hair in a loose braid, brown eyes. Waist-up standing angled left, confident calm smile, modest muted coral dress and indigo shawl. Vineyard path, pale cream sky, olive-green leaves, clear morning light. Face in upper half.',
'lover-song':'One adult ancient Near Eastern male lover, age about 30, warm brown skin, strong rounded face, thick black curly hair and short full beard, brown eyes. Close chest-up three-quarter view turned right, relaxed affectionate expression. Modest sage tunic and pale gold mantle. Cedar grove with soft blue distant hills, cool afternoon light. No crown.',
'women-song':'Three adult ancient Near Eastern women friends, all visibly over age 25, varied brown complexions and distinct faces. Waist-up grouped closely at different angles, one listening, one questioning, one gently smiling. Modest cream, plum, and teal clothes with simple shawls. Pale rose Jerusalem courtyard, clay jars and a green tree. Faces in upper half, restrained golden sunset light.',
'brothers-song':'Two adult ancient Near Eastern men, visibly over age 30, distinct faces, one lean bearded man and one broad-faced man with short curls. Half-body standing in conversation, one facing left and one near front, concerned serious expressions. Modest rust and charcoal tunics, rough cream outer cloths. Vineyard boundary with pale gray stone wall, dry straw colors, cloudy daylight. No children.',
'watchmen-song':'Two adult ancient Near Eastern city watchmen, one tall with an angular face and trimmed dark beard, one stocky with gray stubble. Chest-up views from different angles, stern reserved faces. Modest dark olive and brown garments, simple bronze helmets, no medieval armor. Pale stone city wall at night with muted blue sky and warm torchlight. No visible violence or victims. Faces clear in upper half.',
'solomon-guards-song':'Two adult ancient Near Eastern royal guards, distinct dark-brown faces, black beards, one in profile left and one front-facing. Waist-up standing alert, composed intent expressions. Modest muted burgundy and ochre robes, simple bronze headpieces and restrained armor. Cropped sheathed swords low at waist. Pale lavender dawn near a distant ornate wooden carriage. No medieval armor, no violence.',
'solomon-mother-song':'One mature ancient Near Eastern royal mother, age about 60, warm brown skin, broad face, dark-gray braided hair, brown eyes, slight proud smile. Seated half-body near profile right, wearing a modest deep blue robe and cream head veil with narrow gold edging. One simple crown held low on folded cloth. Pale ivory palace steps with cool mint shadow and soft morning light. Do not identify her as Bathsheba.',
'woman-mother-song':'One older adult ancient Near Eastern mother, age about 55, medium brown skin, angular face with natural age lines, dark-gray wavy hair, thoughtful warm expression. Waist-up seated front-facing angled left, modest olive dress and dusty rose shawl. Shaded simple domestic doorway, pale apricot plaster, woven mat, soft warm window light. Hands resting separately on her lap.',
'pharaoh-song':'One adult ancient Egyptian male ruler, age about 45, medium brown skin, clean-shaven broad face, dark brown eyes. Chest-up strict profile facing left, composed serious expression, modest white linen upper garment, narrow gold-and-blue collar, simple royal striped headcloth. Pale sandstone chariot courtyard with distant horses and muted turquoise dawn sky. No writing or hieroglyphs. Unnamed ruler, not a specific Exodus Pharaoh.'}
path=ROOT/'scripts/song-of-solomon-generated-portraits.json';manifest=json.loads(path.read_text(encoding='utf8')) if path.exists() else {}
for p in b['people']:
 if p['id'] in records:continue
 manifest.setdefault(p['id'],dict(name=p['name'],prompt='Create one finished Bible study portrait. '+scenes[p['id']]+' Painterly realistic illustration with visible brush texture, natural anatomy, modest ancient clothing. Single composition with face high for square crop. No text, lettering, signature, watermark, halos, grid, or modern objects. Interpretive artwork, not a verified likeness.',src='assets/portraits/song-of-solomon/'+p['id']+'.png',mode='built-in image generation'))
for pid,item in manifest.items():
 if (ROOT/'dist'/item['src']).exists():records[pid]=dict(src=item['src'],generated=True,title=item['name']+' · interpretive portrait',credit='AI-generated illustration',license='Generated artwork',note='Artistic interpretation. Appearance, age, and setting are not verified historical evidence.')
path.write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf8');(OUT/'song-of-solomon-art.json').write_text(json.dumps(records,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
print('Prepared',len(manifest),'new portraits. Available:',len(records))
