"""Maintain Philemon's selected records without inventing its unnamed setting."""
import copy,json
from book_common import ROOT
date='2026-10-07';first=json.loads((ROOT/'scripts/book-records/1-timothy.json').read_text(encoding='utf8'))
people=copy.deepcopy(first['people'][:3])
updates={
'paul':('Prisoner and letter speaker who appeals for Onesimus and offers to carry any debt','He names Timothy beside himself and asks Philemon to receive Onesimus as a partner.','His appeal combines affection, remembered obligation, and material responsibility rather than a bare command.'),
'timothy':('Worker named beside Paul in the opening greeting','Paul calls him a brother before addressing the household assembly.','His named presence keeps the appeal within shared relationships.'),
'jesus':('Lord whose grace and shared faith ground the appeal for Onesimus','Paul connects love, partnership, and the closing blessing with him.','Shared belonging supplies the reason to receive Onesimus as more than a bound worker.')}
for p in people:
 role,rel,meaning=updates[p['id']];p.update(role=role,relations=rel,meaning=meaning,chapters=[1],passages='Philemon 1')
people.extend([
 dict(id='philemon',name='Philemon',reuse='philemon',role='Addressed household host asked to receive Onesimus as a beloved brother',relations='Paul praises his love and asks him to receive Onesimus as Paul himself.',passages='Philemon 1:1–22',meaning='The appeal tests whether praised love can change conduct within an unequal relationship.',chapters=[1]),
 dict(id='onesimus',name='Onesimus',reuse='colossians',role='Person sent back with an appeal for reception as a beloved brother',relations='Paul calls him his child and own heart, and offers to carry any debt.',passages='Philemon 1:10–21',meaning='His place makes partnership demand care for a person whose own response remains unrecorded.',chapters=[1]),
 dict(id='epaphras',name='Epaphras',reuse='colossians',role='Fellow prisoner who sends a greeting beside the closing workers',relations='Paul names him before Mark, Aristarchus, Demas, and Luke.',passages='Philemon 1:23',meaning='His greeting places imprisonment within a continuing network of shared work.',chapters=[1])])
sch=dict(id='pietz-philemon',title='Commentary on Philemon 1:1-21',url='https://www.workingpreacher.org/commentaries/revised-common-lectionary/ordinary-23-3/commentary-on-philemon-11-21-4',author='Jennifer Vija Pietz',publisher='Luther Seminary',year=2019,category='Scholarly study',perspective='historical',summary='Pietz emphasizes changed relationships while recognizing uncertainty about a request for legal freedom.',limits='This is Pietz\x27s interpretation. Her proposed runaway account, precise legal setting, broader history of slavery, and the eventual outcome were not independently verified. The letter does not record Onesimus\x27s own response.',chapterCoverage=[1],reviewed=dict(date=date,scope='Complete commentary body read. The guide attributes its emphasis on changed relationships and uncertainty about required legal freedom.'))
cfg=dict(name='Philemon',code='PHM',date=date,verseCounts=[25],nextBook='hebrews',description='Household assembly · affection · debt · partnership · reception as a brother',limits='Paul is the named letter speaker. Historical authorship, dates, Greek forms, manuscripts, the reason for separation, exact location, legal freedom, and the eventual response were not independently verified. Colossae and a prison city are not inferred.',review='All 25 verses read for one original contextual explanation and exact selection. Six selected profiles do not claim exhaustive coverage. No exact location is assigned. Pietz\x27s interpretation remains attributed. The reviewed Church lesson does not discuss Philemon in its body, so its title supplies no chapter reference.',sources=[sch],people=people,places=[],chapters={'1':dict(question='Why does receiving Onesimus as Paul himself make partnership costly?',historicalSources=[sch['id']])})
(ROOT/'scripts/book-records/philemon.json').write_text(json.dumps(cfg,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
