"""Maintain Second Peter's selected profiles and limited sources."""
import json
from book_common import ROOT
date='2026-10-07'
rows=[
('peter','Peter','acts','Named speaker who recalls the mountain witness and prepares reminders before his death','He addresses believers and later names Paul as a beloved brother.','His reminders connect received knowledge with conduct and continued growth.',[1,2,3]),
('jesus','Jesus Christ','matthew','Lord whose power supplies gifts for life and whose coming remains promised','The speaker recalls the voice identifying him as the beloved Son.','His promised coming makes present conduct significant even when waiting continues.',[1,2,3]),
('noah','Noah','genesis','Herald of righteousness recalled as preserved during the flood','He appears among earlier examples of judgment and rescue.','His preservation prevents the judgment comparisons from excluding the possibility of rescue.',[2]),
('lot','Lot','genesis','Man recalled as distressed by wrongdoing and rescued from destruction','His rescue stands beside the destruction of Sodom and Gomorrah.','The comparison connects judgment with the Lord\x27s ability to rescue the godly.',[2]),
('balaam','Balaam','numbers','Prophet recalled through his desire for payment and the donkey\x27s rebuke','His recalled error supplies a comparison for the false teachers\x27 greed.','The rebuke exposes the contradiction between claimed knowledge and corrupt desire.',[2]),
('paul','Paul','romans','Beloved brother whose letters the speaker says contain difficult passages','The speaker warns that unstable readers twist his letters alongside other Scriptures.','His mention makes responsible reading part of the final call to growth.',[3])]
people=[dict(id=i,name=n,reuse=r,role=ro,relations=re,meaning=m,chapters=c,passages='Second Peter '+', '.join(map(str,c))) for i,n,r,ro,re,m,c in rows]
people[1]['linkNames']=['Jesus','Christ']
cfm=dict(id='cfm-nt-2023-48',reuse='1-peter',summary='The lesson connects growth in Christlike qualities with developing divine nature.',chapterCoverage=[1],limits='Only actual Second Peter chapter one discussion supports this reference. First Peter applications, linked talks, and Restoration texts do not extend coverage to other chapters.',reviewed=dict(date=date,scope='Complete lesson body and included resource excerpt read. Second Peter coverage follows the actual discussion of 1:1–11.'))
sch=dict(id='lange-peter',title='Commentary on 2 Peter 3:8-15a',url='https://www.workingpreacher.org/commentaries/revised-common-lectionary/second-sunday-of-advent-2/commentary-on-2-peter-38-15a',author='Dirk G. Lange',publisher='Luther Seminary',year=2011,category='Scholarly study',perspective='historical',summary='Lange reads waiting as hope that changes present conduct.',limits='This is Lange\x27s interpretation. His historical authorship assertion, Greek comparisons, and wider historical claims were not independently verified. The guide assigns no exact date to the promised coming.',chapterCoverage=[3],reviewed=dict(date=date,scope='Complete commentary body read. The guide attributes his connection between waiting, hope, and present conduct.'))
qs=['How does growth in love prevent received knowledge from remaining idle?','Why can promised freedom become a form of slavery when conduct remains corrupt?','How does patient waiting change present conduct without supplying a date for the coming day?']
chapters={str(n):dict(question=q) for n,q in enumerate(qs,1)}
chapters['1'].update(teaching='The selected Church lesson connects growing Christlike qualities with developing our divine nature.',ldsSources=[cfm['id']])
chapters['3']['historicalSources']=[sch['id']]
places=[dict(id='sodom',reuse='genesis',chapters=[2],summary='The letter recalls Sodom\x27s destruction beside Lot\x27s rescue.',verseScope={'2':[6]},linkNames=['Sodom'])]
cfg=dict(name='2 Peter',code='2PE',date=date,verseCounts=[21,22,18],nextBook='1-john',description='Growing qualities · recalled rescue · corrupt promises · patient hope',limits='Peter is the named speaker. Historical authorship, dates, Greek forms, exact audience conditions, and the mountain\x27s identity were not independently verified. The coming day has no calculated date. Sodom remains a disputed regional marker.',review='All 61 verses read for three original explanations and exact selections. Six selected profiles reuse inspected artwork. The map marks a disputed recalled region rather than an exact city. Lange\x27s reading remains attributed. Actual Church lesson coverage remains separate from original close readings.',sources=[cfm,sch],people=people,places=places,chapters=chapters)
(ROOT/'scripts/book-records/2-peter.json').write_text(json.dumps(cfg,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
