"""Apply sentence-level editorial corrections to persistent Revelation context."""
import json
from book_common import ROOT
p=ROOT/'scripts/book-context-complete/revelation.json';rows=json.loads(p.read_text(encoding='utf8'))
fixes={
1:{'Writing therefore serves people who must hear and keep the message rather than merely admire it.':'Writing serves people who must hear and keep the message rather than merely admire it.'},
4:{'The scene establishes the source of authority before the following question about opening the sealed book.':'The scene establishes authority before the following question about opening the sealed book.'},
5:{'The sealed book creates a problem because no creature can open it or inspect its contents.':'The sealed book creates a problem because no creature can open it or inspect it.','The widening chorus makes the Lamb\x27s victory grounds for shared praise rather than one nation\x27s privilege.':'The chorus makes the Lamb\x27s victory grounds for shared praise rather than one nation\x27s privilege.'},
6:{'The sixth seal removes ordinary security across social ranks and ends with the question of standing.':'The sixth seal removes security across social ranks and ends with the question of standing.'},
7:{'The Lamb becomes their shepherd, while wiped tears give rescue the form of care for sufferers.':'The Lamb becomes their shepherd, while wiped tears make rescue include care for sufferers.'},
9:{'The next trumpet releases bound angels and a vast horse army whose mouths bring deadly plagues.':'The next trumpet releases bound angels and a horse army whose mouths bring deadly plagues.','The ending therefore makes failed repentance the issue rather than presenting pain as certain moral improvement.':'The ending makes failed repentance the issue rather than presenting pain as certain moral improvement.'},
10:{'The mighty angel spans land and sea, placing the little book within a scene of authority.':'The angel spans land and sea, placing the little book within a scene of authority.','The renewed task concerns peoples and kings, joining received words with the cost of speaking them.':'The renewed task concerns peoples and kings, joining received words with the cost of speaking.'},
11:{'Public refusal of burial and celebration make that defeat appear complete before God\x27s breath restores life.':'Refused burial and public celebration make defeat appear complete before God\x27s breath restores life.','The opened heavenly temple completes this turn without requiring a mapped earthly site for every symbol.':'The opened heavenly temple completes this turn without requiring an earthly site for every symbol.'},
12:{'The announced victory rests on the Lamb\x27s blood and testimony held even under threat of death.':'The announced victory rests on the Lamb\x27s blood and testimony held under threat of death.','Earthly suffering can therefore continue within the account of victory without proving that rescue has failed.':'Earthly suffering can continue within the account of victory without proving that rescue has failed.'},
14:{'The Lamb\x27s followers bear his name rather than the beast\x27s mark described in the preceding chapter.':'The Lamb\x27s followers bear his name rather than the beast\x27s mark in the preceding chapter.','Angelic messages call every people toward the Creator while announcing Babylon\x27s fall and opposing beast worship.':'Angels call every people toward the Creator while announcing Babylon\x27s fall and opposing beast worship.'},
15:{'Their song joins Moses with the Lamb, connecting received rescue with praise rather than personal achievement.':'Their song joins Moses with the Lamb, connecting rescue with praise rather than personal achievement.','Worship therefore frames the approaching judgment without claiming that its destructive scenes are gentle or incidental.':'Worship frames approaching judgment without claiming that its destructive scenes are gentle or incidental.'},
17:{'The scene makes shared destructive power unstable without supplying a secure list of historical or modern kings.':'Shared destructive power becomes unstable without supplying a secure list of historical or modern kings.'},
18:{'Babylon\x27s declared fall introduces a command to leave so that God\x27s people avoid participation in wrongdoing.':'Babylon\x27s fall introduces a command to leave so that God\x27s people avoid participation in wrongdoing.','Their distance expresses fear of her torment rather than care for those harmed by her power.':'Their distance expresses fear of torment rather than care for those harmed by her power.','The merchandise list includes human bodies and souls, exposing people within the same trade as goods.':'The merchandise list includes human bodies and souls, exposing people within the trade as goods.'},
19:{'The wedding clothing receives an explicit explanation as the saints\x27 righteous acts rather than purchased luxury.':'The wedding clothing receives explanation as the saints\x27 righteous acts rather than purchased luxury.','The final violent supper contrasts with the wedding invitation, keeping rescue and judgment distinct within the vision.':'The violent supper contrasts with the wedding invitation, keeping rescue and judgment distinct.'},
20:{'Judgment according to works removes the protection that rank or earthly power might seem to offer.':'Judgment according to works removes the protection that rank or power might seem to offer.','Death and Hades themselves enter the fire, so even their custody of the dead cannot remain final.':'Death and Hades enter the fire, so their custody of the dead cannot remain final.'},
21:{'Carey reads the descending city as renewal of shared life rather than escape from the world.':'Carey reads the descending city as renewed shared life rather than escape from the world.','Open gates and light for nations describe welcome, while the closing exclusion preserves truth and purity.':'Open gates and light for nations describe welcome, while exclusion preserves truth and purity.'},
22:{'The final prayer and grace return the visions to assemblies who must hear, keep, and await.':'Prayer and grace return the visions to assemblies who must hear, keep, and await.'}}
for r in rows:
 for old,new in fixes.get(r[0],{}).items():
  assert old in r[3];r[3]=r[3].replace(old,new)
p.write_text(json.dumps(rows,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
